lilak: anaFitPulse.C File Reference
anaFitPulse.C File Reference
#include "ejungwooA.h"
#include "setChannels.h"
#include "LKPulseAnalyzer.h"
#include "LKChannelAnalyzer.h"
#include "LKPulse.h"
Functions
void anaFitPulse (double scaleBeta=0.7)
void NextChannel (int pass=0)
Variables
TClonesArray * fChannelArray = nullptr
TCanvas * fCvs
TCanvas * fCvsDebug
int fCvsDX = 1200
int fCvsDY = 720
int fCvsGroupDX = 3
int fCvsGroupDY = 2
const char * fDataPath = "data"
TexAT2 * fDetector
bool fEndOfEvent = true
int fIdxChannel = 0
int fMaxInputFiles = 1
int fNumChannels
int fNumCvsGroup = 0
LKRun * fRun
Function Documentation
anaFitPulse()
void anaFitPulse (double scaleBeta = 0.7)
Definition at line 26 of file anaFitPulse.C.
References ejungwoo::Canvas(), e_cvs, fChannelArray, fCvs, fCvsDebug, fDetector, fMaxInputFiles, fRun, fSelTypes, fTypeNames, lk_logger, and NextChannel().
NextChannel()
void NextChannel (int pass = 0)
Definition at line 99 of file anaFitPulse.C.
References ana, e_frame, e_test, e_warning, fChannelArray, fCvs, fCvsDebug, fDetector, fEndOfEvent, fIdxChannel, fNumChannels, ejungwoo::Frame(), fRun, fSelTypes, fTypeNames, LKChannelAnalyzer::GetBuffer(), LKRun::GetCurrentEventID(), ejungwoo::MakeChannelHist(), and NextChannel().
Referenced by anaFitPulse(), and NextChannel().
Variable Documentation
fChannelArray
TClonesArray* fChannelArray = nullptr
Definition at line 17 of file anaFitPulse.C.
Referenced by anaFitPulse(), and NextChannel().
fCvs
TCanvas* fCvs
Definition at line 21 of file anaFitPulse.C.
Referenced by anaFitPulse(), and NextChannel().
fCvsDebug
TCanvas* fCvsDebug
Definition at line 22 of file anaFitPulse.C.
Referenced by anaFitPulse(), and NextChannel().
fCvsDX
int fCvsDX = 1200
Definition at line 7 of file anaFitPulse.C.
fCvsDY
int fCvsDY = 720
Definition at line 8 of file anaFitPulse.C.
fCvsGroupDX
int fCvsGroupDX = 3
Definition at line 9 of file anaFitPulse.C.
fCvsGroupDY
int fCvsGroupDY = 2
Definition at line 10 of file anaFitPulse.C.
fDataPath
const char* fDataPath = "data"
Definition at line 13 of file anaFitPulse.C.
fDetector
TexAT2* fDetector
Definition at line 19 of file anaFitPulse.C.
Referenced by anaFitPulse(), and NextChannel().
fEndOfEvent
bool fEndOfEvent = true
Definition at line 16 of file anaFitPulse.C.
Referenced by NextChannel().
fIdxChannel
int fIdxChannel = 0
Definition at line 15 of file anaFitPulse.C.
Referenced by NextChannel().
fMaxInputFiles
int fMaxInputFiles = 1
Definition at line 12 of file anaFitPulse.C.
Referenced by anaFitPulse().
fNumChannels
int fNumChannels
Definition at line 14 of file anaFitPulse.C.
Referenced by NextChannel().
fNumCvsGroup
int fNumCvsGroup = 0
Definition at line 11 of file anaFitPulse.C.
fRun
LKRun* fRun
Definition at line 18 of file anaFitPulse.C.
Referenced by anaFitPulse(), and NextChannel().