lilak: read_conv.C File Reference
calibration_xesus/read_conv.C File Reference
#include "read_conv.h"
Functions
void read_conv (int RunN=303)
Function Documentation
read_conv()
void read_conv (int RunN = 303)
Definition at line 3 of file calibration_xesus/read_conv.C.
References cCSD, channelArray, CSD_junction, CSD_ohmic, cX6, def(), det, det_back, E_junction, E_ohmic, E_ohmic_raw, EvsPos, hCSD_junction, hCSD_ohmic, hitpattern, iChannel, iEvent, LvsR, readmap(), stark_map, strip, strip_back, StripvsPos, treedef(), X6_det, X6_strip, X6aget, X6asad, X6chan, X6cobo, X6Mult, X6nrj, and X6tree.