LILAK: check_tracks.C File Reference
check_tracks.C File Reference
#include "LKLogger.h"
Functions
void check_tracks ()
void nextEvent ()
Variables
TClonesArray * fHitArray [6]
TObjArray * fHitArrayAll = nullptr
TClonesArray * fTrackArray
Function Documentation
check_tracks()
void check_tracks ()
Definition at line 59 of file check_tracks.C.
References e_error, fHitArray, fTrackArray, nextEvent(), and run.
nextEvent()
void nextEvent ()
Definition at line 7 of file check_tracks.C.
References e_info, e_warning, fHitArray, fHitArrayAll, fTrackArray, and LKRun::GetRun().
Referenced by check_tracks().
Variable Documentation
fHitArray
TClonesArray* fHitArray[6]
Definition at line 4 of file check_tracks.C.
Referenced by check_tracks(), and nextEvent().
fHitArrayAll
TObjArray* fHitArrayAll = nullptr
Definition at line 3 of file check_tracks.C.
Referenced by nextEvent().
fTrackArray
TClonesArray* fTrackArray
Definition at line 5 of file check_tracks.C.
Referenced by check_tracks(), and nextEvent().