lilak: LKHitArray Class Reference
LKHitArray Class Reference
#include <LKHitArray.h>
Public Member Functions
void AddHit (LKHit *hit)
void AddXYZW (Double_t x, Double_t y, Double_t z, Double_t w=0)
Fit is not possible if point is added through this method.
void AddXYZW (TVector3 pos, Double_t w=0)
Fit is not possible if point is added through this method.
ClassDef (LKHitArray, 1)
virtual void Clear (Option_t *option="C")
virtual void Copy (TObject &object) const
TCanvas * DrawFitCircle (axis_t ref=LKVector3::kZ)
TGraphErrors * DrawGraph (axis_t, axis_t)
LKGeoCircle FitCircle (axis_t ref=LKVector3::kZ)
LKGeoHelix FitHelix (axis_t ref=LKVector3::kZ)
LKGeoLine FitLine ()
LKGeoPlane FitPlane ()
Double_t GetAXX () const
W * SUM_i (<x>-x_i)^2 : diagonal compoent of matrix A.
Double_t GetAXY () const
W * SUM_i (<x>-x_i)*(<y>-y_i) : off-diagonal compoent of matrix A.
Double_t GetAYY () const
W * SUM_i (<y>-y_i)^2 : diagonal compoent of matrix A.
Double_t GetAYZ () const
W * SUM_i (<y>-y_i)*(<z>-z_i) : off-diagonal compoent of matrix A.
Double_t GetAZX () const
W * SUM_i (<z>-z_i)*(<x>-x_i) : off-diagonal compoent of matrix A.
Double_t GetAZZ () const
W * SUM_i (<z>-z_i)^2 : diagonal compoent of matrix A.
Double_t GetChargeSum () const
TVector3 GetCoSquaredMean () const
LKVector3 GetCoSquaredMean (axis_t) const
TVector3 GetCovariance () const
LKVector3 GetCovariance (axis_t) const
LKHit * GetHit (Int_t idx) const
Int_t GetHitID (Int_t idx) const
LKHit * GetLastHit () const
TVector3 GetMean () const
LKVector3 GetMean (axis_t) const
Double_t GetMeanX () const
Double_t GetMeanXX () const
Double_t GetMeanXY () const
Double_t GetMeanY () const
Double_t GetMeanYY () const
Double_t GetMeanYZ () const
Double_t GetMeanZ () const
Double_t GetMeanZX () const
Double_t GetMeanZZ () const
Int_t GetNumHits () const
TVector3 GetSquaredMean () const
LKVector3 GetSquaredMean (axis_t) const
TVector3 GetStdDev () const
LKVector3 GetStdDev (axis_t) const
TVector3 GetVariance () const
LKVector3 GetVariance (axis_t) const
Double_t GetVarianceX () const
SUM_i (<x>-x_i)^2.
Double_t GetVarianceY () const
SUM_i (<y>-y_i)^2.
Double_t GetVarianceZ () const
SUM_i (<z>-z_i)^2.
Double_t GetW () const
LKHitArray (Int_t size=1000)
void MoveHitsTo (LKHitArray *hitArray)
virtual void Print (Option_t *option="") const
void PrintHitIDs (Int_t rank) const
void PrintHits (Int_t rank) const
bool RemoveHit (Int_t iHit)
bool RemoveHit (LKHit *hit)
virtual void RemoveLastHit ()
void SortByCharge (bool sortEarlierIfSmaller=true)
void SortByDistanceTo (TVector3 point, bool sortEarlierIfCloser=true)
void SortByLayer (bool sortEarlierIfSmaller=true)
void SortByX (bool sortEarlierIfSmaller=true)
void SortByY (bool sortEarlierIfSmaller=true)
void SortByZ (bool sortEarlierIfSmaller=true)
bool Subtract (Double_t x, Double_t y, Double_t z, Double_t w=0)
Fit is not possible if point is removed through this method.
bool Subtract (TVector3 pos, Double_t w=0)
Fit is not possible if point is removed through this method.
virtual ~LKHitArray ()
Private Attributes
Double_t fEX = 0
<x> Mean value of x
Double_t fEXX = 0
<x*x> Mean value of x*x
Double_t fEXY = 0
<x*y> Mean value of x*y
Double_t fEY = 0
<y> Mean value of y
Double_t fEYY = 0
<y*y> Mean value of y*y
Double_t fEYZ = 0
<y*z> Mean value of y*z
Double_t fEZ = 0
<z> Mean value of z
Double_t fEZX = 0
<z*x> Mean value of z*y
Double_t fEZZ = 0
<z*z> Mean value of z*z
Int_t fN = 0
Number of hits.
LKODRFitter * fODRFitter = nullptr
Double_t fW = 0
Sum of charge.
Detailed Description
Definition at line 24 of file LKHitArray.h.
Constructor & Destructor Documentation
LKHitArray()
LKHitArray::LKHitArray (Int_t size = 1000)
Definition at line 13 of file LKHitArray.cpp.
References Clear().
~LKHitArray()
LKHitArray::~LKHitArray () virtual
Definition at line 19 of file LKHitArray.cpp.
Member Function Documentation
AddHit()
void LKHitArray::AddHit (LKHit * hit)
Definition at line 721 of file LKHitArray.cpp.
References AddXYZW(), LKHit::GetCharge(), LKHit::GetX(), LKHit::GetY(), and LKHit::GetZ().
Referenced by LKHit::AddHit(), GETChannel::AddHit(), LKTracklet::AddHit(), LKLinearTrack::CopyFrom(), MoveHitsTo(), LKTracklet::RecoverHitArrayWithHitID(), and LKTracklet::RecoverHitArrayWithTrackID().
AddXYZW() [1/2]
void LKHitArray::AddXYZW (Double_t x, Double_t y, Double_t z, Double_t w = 0)
Fit is not possible if point is added through this method.
Definition at line 733 of file LKHitArray.cpp.
References fEX, fEXX, fEXY, fEY, fEYY, fEYZ, fEZ, fEZX, fEZZ, fN, and fW.
AddXYZW() [2/2]
void LKHitArray::AddXYZW (TVector3 pos, Double_t w = 0)
Fit is not possible if point is added through this method.
Definition at line 728 of file LKHitArray.cpp.
References AddXYZW().
Referenced by AddHit(), and AddXYZW().
ClassDef()
LKHitArray::ClassDef (LKHitArray , 1)
Clear()
void LKHitArray::Clear (Option_t * option = "C") virtual
Definition at line 88 of file LKHitArray.cpp.
References fEX, fEXX, fEXY, fEY, fEYY, fEYZ, fEZ, fEZX, fEZZ, fN, fODRFitter, and fW.
Referenced by ClassImp(), ClassImp(), GETChannel::Clear(), GETChannel::ClearHits(), LKTracklet::ClearHits(), LKHitArray(), MoveHitsTo(), GETChannel::PullOutHits(), and GETChannel::PullOutHits().
Copy()
void LKHitArray::Copy (TObject & object) const virtual
Definition at line 135 of file LKHitArray.cpp.
References LKHit::AddHit(), and next().
DrawFitCircle()
TCanvas * LKHitArray::DrawFitCircle (axis_t ref = LKVector3::kZ)
Definition at line 340 of file LKHitArray.cpp.
References cvs1, cvs2, LKGeoLine::DrawArrowXY(), LKGeoCircle::DrawCircle(), LKGeoSphere::DrawCircleXY(), LKGeoSphere::DrawCircleYZ(), fN, fODRFitter, fW, LKODRFitter::GetFitter(), GetHit(), GetLastHit(), GetMean(), GetVariance(), LKVector3::I(), LKVector3::J(), LKVector3::K(), LKGeoCircle::SetCircle(), and LKGeometry::SetRMS().
DrawGraph()
TGraphErrors * LKHitArray::DrawGraph (axis_t axis1, axis_t axis2)
Definition at line 852 of file LKHitArray.cpp.
References LKVector3::At(), LKHit::GetPosition(), next(), and SetPoint().
FitCircle()
LKGeoCircle LKHitArray::FitCircle (axis_t ref = LKVector3::kZ)
Definition at line 236 of file LKHitArray.cpp.
References fN, fODRFitter, fW, LKODRFitter::GetFitter(), GetMean(), GetVariance(), LKVector3::I(), LKVector3::J(), LKVector3::K(), LKGeoCircle::SetCircle(), and LKGeometry::SetRMS().
Referenced by FitHelix().
FitHelix()
LKGeoHelix LKHitArray::FitHelix (axis_t ref = LKVector3::kZ)
Definition at line 610 of file LKHitArray.cpp.
References FitCircle(), fN, fW, LKHit::GetAlpha(), GetHit(), LKHit::GetPosition(), LKGeoHelix::HelicoidMap(), LKGeoHelix::SetA(), LKGeoHelix::SetH(), LKGeoHelix::SetI(), LKGeoHelix::SetJ(), LKGeoHelix::SetK(), LKGeoHelix::SetR(), LKGeometry::SetRMS(), LKGeoHelix::SetRMSR(), LKGeoHelix::SetRMST(), LKGeoHelix::SetS(), LKGeoHelix::SetT(), SortByX(), SortByY(), and SortByZ().
Referenced by LKHelixTrack::Fit(), and LKTracklet::FitHelix().
FitLine()
LKGeoLine LKHitArray::FitLine ()
Definition at line 178 of file LKHitArray.cpp.
References fEX, fEY, fEZ, fN, fODRFitter, fW, GetAXX(), GetAXY(), GetAYY(), GetAYZ(), GetAZX(), GetAZZ(), LKODRFitter::GetDirection(), LKODRFitter::GetFitter(), LKGeoLine::SetLine(), and LKGeometry::SetRMS().
Referenced by LKLinearTrack::Fit(), LKTracklet::FitLine(), and LKHelixTrack::FitPlane().
FitPlane()
LKGeoPlane LKHitArray::FitPlane ()
Definition at line 204 of file LKHitArray.cpp.
References fEX, fEY, fEZ, fN, fODRFitter, fW, GetAXX(), GetAXY(), GetAYY(), GetAYZ(), GetAZX(), GetAZZ(), LKODRFitter::GetFitter(), LKGeoPlane::SetPlane(), and LKGeometry::SetRMS().
Referenced by LKHelixTrack::FitPlane(), and LKTracklet::FitPlane().
GetAXX()
Double_t LKHitArray::GetAXX () const
W * SUM_i (<x>-x_i)^2 : diagonal compoent of matrix A.
Definition at line 831 of file LKHitArray.cpp.
References fEX, fEXX, and fW.
Referenced by FitLine(), and FitPlane().
GetAXY()
Double_t LKHitArray::GetAXY () const
W * SUM_i (<x>-x_i)*(<y>-y_i) : off-diagonal compoent of matrix A.
Definition at line 834 of file LKHitArray.cpp.
References fEX, fEXY, fEY, and fW.
Referenced by FitLine(), and FitPlane().
GetAYY()
Double_t LKHitArray::GetAYY () const
W * SUM_i (<y>-y_i)^2 : diagonal compoent of matrix A.
Definition at line 832 of file LKHitArray.cpp.
References fEY, fEYY, and fW.
Referenced by FitLine(), and FitPlane().
GetAYZ()
Double_t LKHitArray::GetAYZ () const
W * SUM_i (<y>-y_i)*(<z>-z_i) : off-diagonal compoent of matrix A.
Definition at line 835 of file LKHitArray.cpp.
References fEY, fEYZ, fEZ, and fW.
Referenced by FitLine(), and FitPlane().
GetAZX()
Double_t LKHitArray::GetAZX () const
W * SUM_i (<z>-z_i)*(<x>-x_i) : off-diagonal compoent of matrix A.
Definition at line 836 of file LKHitArray.cpp.
References fEX, fEZ, fEZX, and fW.
Referenced by FitLine(), and FitPlane().
GetAZZ()
Double_t LKHitArray::GetAZZ () const
W * SUM_i (<z>-z_i)^2 : diagonal compoent of matrix A.
Definition at line 833 of file LKHitArray.cpp.
References fEZ, fEZZ, and fW.
Referenced by FitLine(), and FitPlane().
GetChargeSum()
Double_t LKHitArray::GetChargeSum () const
Definition at line 814 of file LKHitArray.cpp.
References fW.
GetCoSquaredMean() [1/2]
TVector3 LKHitArray::GetCoSquaredMean () const
Definition at line 843 of file LKHitArray.cpp.
References fEXY, fEYZ, and fEZX.
Referenced by LKHit::GetCoSquaredMean().
GetCoSquaredMean() [2/2]
LKVector3 LKHitArray::GetCoSquaredMean (axis_t ref) const
Definition at line 850 of file LKHitArray.cpp.
References fEXY, fEYZ, and fEZX.
GetCovariance() [1/2]
TVector3 LKHitArray::GetCovariance () const
Definition at line 840 of file LKHitArray.cpp.
References fEX, fEXY, fEY, fEYZ, fEZ, and fEZX.
Referenced by LKHit::GetCovariance().
GetCovariance() [2/2]
LKVector3 LKHitArray::GetCovariance (axis_t ref) const
Definition at line 847 of file LKHitArray.cpp.
References fEX, fEXY, fEY, fEYZ, fEZ, and fEZX.
GetHit()
LKHit * LKHitArray::GetHit (Int_t idx) const
Definition at line 23 of file LKHitArray.cpp.
Referenced by LKHelixTrack::Continuity(), LKTracklet::Continuity(), LKHelixTrack::Copy(), DrawFitCircle(), LKLinearTrack::Fit(), FitHelix(), GETChannel::GetHit(), LKTracklet::GetHit(), GETChannel::PullOutHits(), GETChannel::PullOutHits(), GETChannel::PullOutNextFreeHit(), RemoveHit(), RemoveHit(), RemoveLastHit(), and LKLinearTrack::SetLine().
GetHitID()
Int_t LKHitArray::GetHitID (Int_t idx) const
Referenced by Print(), PrintHitIDs(), and RemoveHit().
GetLastHit()
LKHit * LKHitArray::GetLastHit () const
Definition at line 28 of file LKHitArray.cpp.
Referenced by DrawFitCircle().
GetMean() [1/2]
TVector3 LKHitArray::GetMean () const
Definition at line 838 of file LKHitArray.cpp.
References fEX, fEY, and fEZ.
Referenced by DrawFitCircle(), FitCircle(), LKHit::GetMean(), LKTracklet::GetMean(), LKHelixTrack::PerpLine(), LKHelixTrack::PerpPlane(), and LKHelixTrack::Print().
GetMean() [2/2]
LKVector3 LKHitArray::GetMean (axis_t ref) const
Definition at line 845 of file LKHitArray.cpp.
References fEX, fEY, and fEZ.
GetMeanX()
Double_t LKHitArray::GetMeanX () const
Definition at line 816 of file LKHitArray.cpp.
References fEX.
Referenced by LKHit::AddHit(), and LKHit::RemoveHit().
GetMeanXX()
Double_t LKHitArray::GetMeanXX () const
Definition at line 820 of file LKHitArray.cpp.
References fEXX.
GetMeanXY()
Double_t LKHitArray::GetMeanXY () const
Definition at line 823 of file LKHitArray.cpp.
References fEXY.
GetMeanY()
Double_t LKHitArray::GetMeanY () const
Definition at line 817 of file LKHitArray.cpp.
References fEY.
Referenced by LKHit::AddHit(), and LKHit::RemoveHit().
GetMeanYY()
Double_t LKHitArray::GetMeanYY () const
Definition at line 821 of file LKHitArray.cpp.
References fEYY.
GetMeanYZ()
Double_t LKHitArray::GetMeanYZ () const
Definition at line 824 of file LKHitArray.cpp.
References fEYZ.
GetMeanZ()
Double_t LKHitArray::GetMeanZ () const
Definition at line 818 of file LKHitArray.cpp.
References fEZ.
Referenced by LKHit::AddHit(), and LKHit::RemoveHit().
GetMeanZX()
Double_t LKHitArray::GetMeanZX () const
Definition at line 825 of file LKHitArray.cpp.
References fEZX.
GetMeanZZ()
Double_t LKHitArray::GetMeanZZ () const
Definition at line 822 of file LKHitArray.cpp.
References fEZZ.
GetNumHits()
Int_t LKHitArray::GetNumHits () const
Definition at line 810 of file LKHitArray.cpp.
References fN.
Referenced by LKHelixTrack::Continuity(), LKTracklet::Continuity(), LKHelixTrack::Copy(), LKLinearTrack::Fit(), GETChannel::GetNumHits(), LKTracklet::IsHoldingHits(), LKHelixTrack::Print(), LKLinearTrack::Print(), GETChannel::PullOutHits(), GETChannel::PullOutHits(), GETChannel::PullOutNextFreeHit(), and LKLinearTrack::SetLine().
GetSquaredMean() [1/2]
TVector3 LKHitArray::GetSquaredMean () const
Definition at line 842 of file LKHitArray.cpp.
References fEXX, fEYY, and fEZZ.
Referenced by LKHit::GetSquaredMean().
GetSquaredMean() [2/2]
LKVector3 LKHitArray::GetSquaredMean (axis_t ref) const
Definition at line 849 of file LKHitArray.cpp.
References fEXX, fEYY, and fEZZ.
GetStdDev() [1/2]
TVector3 LKHitArray::GetStdDev () const
Definition at line 841 of file LKHitArray.cpp.
References fEX, fEXY, fEY, fEYZ, fEZ, and fEZX.
Referenced by LKHit::GetStdDev().
GetStdDev() [2/2]
LKVector3 LKHitArray::GetStdDev (axis_t ref) const
Definition at line 848 of file LKHitArray.cpp.
References fEX, fEXY, fEY, fEYZ, fEZ, and fEZX.
GetVariance() [1/2]
TVector3 LKHitArray::GetVariance () const
Definition at line 839 of file LKHitArray.cpp.
References fEX, fEXX, fEY, fEYY, fEZ, and fEZZ.
Referenced by DrawFitCircle(), FitCircle(), and LKHit::GetVariance().
GetVariance() [2/2]
LKVector3 LKHitArray::GetVariance (axis_t ref) const
Definition at line 846 of file LKHitArray.cpp.
References fEX, fEXX, fEY, fEYY, fEZ, and fEZZ.
GetVarianceX()
Double_t LKHitArray::GetVarianceX () const
SUM_i (<x>-x_i)^2.
Definition at line 827 of file LKHitArray.cpp.
References fEX, and fEXX.
Referenced by Print().
GetVarianceY()
Double_t LKHitArray::GetVarianceY () const
SUM_i (<y>-y_i)^2.
Definition at line 828 of file LKHitArray.cpp.
References fEY, and fEYY.
Referenced by Print().
GetVarianceZ()
Double_t LKHitArray::GetVarianceZ () const
SUM_i (<z>-z_i)^2.
Definition at line 829 of file LKHitArray.cpp.
References fEZ, and fEZZ.
Referenced by Print().
GetW()
Double_t LKHitArray::GetW () const
Definition at line 813 of file LKHitArray.cpp.
References fW.
Referenced by LKHit::AddHit(), LKTracklet::GetChargeSum(), LKHelixTrack::Print(), and LKHit::RemoveHit().
MoveHitsTo()
void LKHitArray::MoveHitsTo (LKHitArray * hitArray)
Definition at line 147 of file LKHitArray.cpp.
References AddHit(), Clear(), and next().
Print()
void LKHitArray::Print (Option_t * option = "") const virtual
Definition at line 109 of file LKHitArray.cpp.
References e_cout, e_info, fEX, fEXX, fEXY, fEY, fEYY, fEYZ, fEZ, fEZX, fEZZ, fN, fW, GetHitID(), GetVarianceX(), GetVarianceY(), GetVarianceZ(), and next().
Referenced by GETChannel::Print(), and PrintHits().
PrintHitIDs()
void LKHitArray::PrintHitIDs (Int_t rank) const
Definition at line 156 of file LKHitArray.cpp.
References e_cout, e_info, fN, GetHitID(), and next().
PrintHits()
void LKHitArray::PrintHits (Int_t rank) const
Definition at line 168 of file LKHitArray.cpp.
References next(), and Print().
Referenced by LKHelixTrack::Print().
RemoveHit() [1/2]
bool LKHitArray::RemoveHit (Int_t iHit)
Definition at line 751 of file LKHitArray.cpp.
References GetHit(), and Subtract().
RemoveHit() [2/2]
bool LKHitArray::RemoveHit (LKHit * hit)
Definition at line 759 of file LKHitArray.cpp.
References fN, LKHit::GetCharge(), GetHit(), GetHitID(), LKHit::GetX(), LKHit::GetY(), LKHit::GetZ(), and Subtract().
Referenced by GETChannel::PullOutNextFreeHit(), LKHit::RemoveHit(), and LKTracklet::RemoveHit().
RemoveLastHit()
void LKHitArray::RemoveLastHit () virtual
Definition at line 776 of file LKHitArray.cpp.
References GetHit(), and Subtract().
SortByCharge()
void LKHitArray::SortByCharge (bool sortEarlierIfSmaller = true)
Definition at line 60 of file LKHitArray.cpp.
References next().
SortByDistanceTo()
void LKHitArray::SortByDistanceTo (TVector3 point, bool sortEarlierIfCloser = true)
Definition at line 69 of file LKHitArray.cpp.
References next().
SortByLayer()
void LKHitArray::SortByLayer (bool sortEarlierIfSmaller = true)
Definition at line 78 of file LKHitArray.cpp.
References next().
SortByX()
void LKHitArray::SortByX (bool sortEarlierIfSmaller = true)
Definition at line 33 of file LKHitArray.cpp.
References next().
Referenced by FitHelix().
SortByY()
void LKHitArray::SortByY (bool sortEarlierIfSmaller = true)
Definition at line 42 of file LKHitArray.cpp.
References next().
Referenced by FitHelix().
SortByZ()
void LKHitArray::SortByZ (bool sortEarlierIfSmaller = true)
Definition at line 51 of file LKHitArray.cpp.
References next().
Referenced by FitHelix().
Subtract() [1/2]
bool LKHitArray::Subtract (Double_t x, Double_t y, Double_t z, Double_t w = 0)
Fit is not possible if point is removed through this method.
Definition at line 790 of file LKHitArray.cpp.
References fEX, fEXX, fEXY, fEY, fEYY, fEYZ, fEZ, fEZX, fEZZ, fN, and fW.
Subtract() [2/2]
bool LKHitArray::Subtract (TVector3 pos, Double_t w = 0)
Fit is not possible if point is removed through this method.
Definition at line 785 of file LKHitArray.cpp.
References Subtract().
Referenced by RemoveHit(), RemoveHit(), RemoveLastHit(), and Subtract().
Member Data Documentation
fEX
Double_t LKHitArray::fEX = 0 private
<x> Mean value of x
Definition at line 29 of file LKHitArray.h.
Referenced by AddXYZW(), Clear(), FitLine(), FitPlane(), GetAXX(), GetAXY(), GetAZX(), GetCovariance(), GetCovariance(), GetMean(), GetMean(), GetMeanX(), GetStdDev(), GetStdDev(), GetVariance(), GetVariance(), GetVarianceX(), Print(), and Subtract().
fEXX
Double_t LKHitArray::fEXX = 0 private
<x*x> Mean value of x*x
Definition at line 32 of file LKHitArray.h.
Referenced by AddXYZW(), Clear(), GetAXX(), GetMeanXX(), GetSquaredMean(), GetSquaredMean(), GetVariance(), GetVariance(), GetVarianceX(), Print(), and Subtract().
fEXY
Double_t LKHitArray::fEXY = 0 private
<x*y> Mean value of x*y
Definition at line 35 of file LKHitArray.h.
Referenced by AddXYZW(), Clear(), GetAXY(), GetCoSquaredMean(), GetCoSquaredMean(), GetCovariance(), GetCovariance(), GetMeanXY(), GetStdDev(), GetStdDev(), Print(), and Subtract().
fEY
Double_t LKHitArray::fEY = 0 private
<y> Mean value of y
Definition at line 30 of file LKHitArray.h.
Referenced by AddXYZW(), Clear(), FitLine(), FitPlane(), GetAXY(), GetAYY(), GetAYZ(), GetCovariance(), GetCovariance(), GetMean(), GetMean(), GetMeanY(), GetStdDev(), GetStdDev(), GetVariance(), GetVariance(), GetVarianceY(), Print(), and Subtract().
fEYY
Double_t LKHitArray::fEYY = 0 private
<y*y> Mean value of y*y
Definition at line 33 of file LKHitArray.h.
Referenced by AddXYZW(), Clear(), GetAYY(), GetMeanYY(), GetSquaredMean(), GetSquaredMean(), GetVariance(), GetVariance(), GetVarianceY(), Print(), and Subtract().
fEYZ
Double_t LKHitArray::fEYZ = 0 private
<y*z> Mean value of y*z
Definition at line 36 of file LKHitArray.h.
Referenced by AddXYZW(), Clear(), GetAYZ(), GetCoSquaredMean(), GetCoSquaredMean(), GetCovariance(), GetCovariance(), GetMeanYZ(), GetStdDev(), GetStdDev(), Print(), and Subtract().
fEZ
Double_t LKHitArray::fEZ = 0 private
<z> Mean value of z
Definition at line 31 of file LKHitArray.h.
Referenced by AddXYZW(), Clear(), FitLine(), FitPlane(), GetAYZ(), GetAZX(), GetAZZ(), GetCovariance(), GetCovariance(), GetMean(), GetMean(), GetMeanZ(), GetStdDev(), GetStdDev(), GetVariance(), GetVariance(), GetVarianceZ(), Print(), and Subtract().
fEZX
Double_t LKHitArray::fEZX = 0 private
<z*x> Mean value of z*y
Definition at line 37 of file LKHitArray.h.
Referenced by AddXYZW(), Clear(), GetAZX(), GetCoSquaredMean(), GetCoSquaredMean(), GetCovariance(), GetCovariance(), GetMeanZX(), GetStdDev(), GetStdDev(), Print(), and Subtract().
fEZZ
Double_t LKHitArray::fEZZ = 0 private
<z*z> Mean value of z*z
Definition at line 34 of file LKHitArray.h.
Referenced by AddXYZW(), Clear(), GetAZZ(), GetMeanZZ(), GetSquaredMean(), GetSquaredMean(), GetVariance(), GetVariance(), GetVarianceZ(), Print(), and Subtract().
fN
Int_t LKHitArray::fN = 0 private
Number of hits.
Definition at line 27 of file LKHitArray.h.
Referenced by AddXYZW(), Clear(), DrawFitCircle(), FitCircle(), FitHelix(), FitLine(), FitPlane(), GetNumHits(), Print(), PrintHitIDs(), RemoveHit(), and Subtract().
fODRFitter
LKODRFitter* LKHitArray::fODRFitter = nullptr private
Definition at line 39 of file LKHitArray.h.
Referenced by Clear(), DrawFitCircle(), FitCircle(), FitLine(), and FitPlane().
fW
Double_t LKHitArray::fW = 0 private
Sum of charge.
Definition at line 28 of file LKHitArray.h.
Referenced by AddXYZW(), Clear(), DrawFitCircle(), FitCircle(), FitHelix(), FitLine(), FitPlane(), GetAXX(), GetAXY(), GetAYY(), GetAYZ(), GetAZX(), GetAZZ(), GetChargeSum(), GetW(), Print(), and Subtract().
The documentation for this class was generated from the following files:
LKHitArray.h
LKHitArray.cpp