LILAK: ATTPCDetectorConstruction Class Reference
ATTPCDetectorConstruction Class Reference
#include <ATTPCDetectorConstruction.h>
Public Member Functions
ATTPCDetectorConstruction ()
virtual G4VPhysicalVolume * Construct ()
virtual ~ATTPCDetectorConstruction ()
Detailed Description
Definition at line 9 of file ATTPCDetectorConstruction.h.
Constructor & Destructor Documentation
ATTPCDetectorConstruction()
ATTPCDetectorConstruction::ATTPCDetectorConstruction ()
Definition at line 20 of file ATTPCDetectorConstruction.cpp.
~ATTPCDetectorConstruction()
ATTPCDetectorConstruction::~ATTPCDetectorConstruction () virtual
Definition at line 25 of file ATTPCDetectorConstruction.cpp.
Member Function Documentation
Construct()
G4VPhysicalVolume * ATTPCDetectorConstruction::Construct () virtual
Definition at line 29 of file ATTPCDetectorConstruction.cpp.
References ATTPC20RectanglePad::GetPadGap(), ATTPCHoneyCombPad::GetPadGap(), ATTPCRectanglePad::GetPadGap(), ATTPCStripPad::GetPadGap(), ATTPC20RectanglePad::GetPadHeight(), ATTPCHoneyCombPad::GetPadHeight(), ATTPCRectanglePad::GetPadHeight(), ATTPCStripPad::GetPadHeight(), ATTPC20RectanglePad::GetPadWidth(), ATTPCHoneyCombPad::GetPadWidth(), ATTPCRectanglePad::GetPadWidth(), and ATTPCStripPad::GetPadWidth().
The documentation for this class was generated from the following files:
ATTPCDetectorConstruction.h
ATTPCDetectorConstruction.cpp