lilak: LKGeometry Class Reference
LKGeometry Class Reference
#include <LKGeometry.h>
Public Member Functions
Double_t GetRMS () const
LKGeometry ()
void SetRMS (Double_t val)
virtual ~LKGeometry ()
Protected Attributes
Double_t fRMS = -1
Detailed Description
Definition at line 6 of file LKGeometry.h.
Constructor & Destructor Documentation
LKGeometry()
LKGeometry::LKGeometry () inline
Definition at line 12 of file LKGeometry.h.
~LKGeometry()
virtual LKGeometry::~LKGeometry () inline virtual
Definition at line 13 of file LKGeometry.h.
Member Function Documentation
GetRMS()
Double_t LKGeometry::GetRMS () const inline
Definition at line 16 of file LKGeometry.h.
References fRMS.
Referenced by LKTracklet::FitHelix(), LKTracklet::FitLine(), and LKTracklet::FitPlane().
SetRMS()
void LKGeometry::SetRMS (Double_t val) inline
Definition at line 15 of file LKGeometry.h.
References fRMS.
Referenced by LKHitArray::DrawFitCircle(), LKHelixTrack::Fit(), LKHitArray::FitCircle(), LKHitArray::FitHelix(), LKHitArray::FitLine(), LKHitArray::FitPlane(), and LKHelixTrack::FitPlane().
Member Data Documentation
fRMS
Double_t LKGeometry::fRMS = -1 protected
Definition at line 9 of file LKGeometry.h.
Referenced by LKLinearTrack::Fit(), GetRMS(), and SetRMS().
The documentation for this class was generated from the following file:
LKGeometry.h