LILAK: Json::ValueConstIterator Class Reference
Json::ValueConstIterator Class Reference
const iterator for object and array value.
#include <json.h>
Public Types
using difference_type = int
using iterator_category = std::bidirectional_iterator_tag
using pointer = const Value *
using reference = const Value &
using SelfType = ValueConstIterator
using size_t = unsigned int
using value_type = const Value
Public Member Functions
UInt index () const
Value key () const
char const * memberName () const
char const * memberName (char const **end) const
String name () const
bool operator!= (const SelfType &other) const
reference operator* () const
SelfType & operator++ ()
SelfType operator++ (int)
difference_type operator- (const SelfType &other) const
SelfType & operator-- ()
SelfType operator-- (int)
pointer operator-> () const
SelfType & operator= (const ValueIteratorBase &other)
bool operator== (const SelfType &other) const
ValueConstIterator ()
ValueConstIterator (ValueIterator const &other)
Protected Member Functions
difference_type computeDistance (const SelfType &other) const
void copy (const SelfType &other)
void decrement ()
Value & deref ()
const Value & deref () const
void increment ()
bool isEqual (const SelfType &other) const
Private Member Functions
ValueConstIterator (const Value::ObjectValues::iterator &current)
Private Attributes
Value::ObjectValues::iterator current_
bool isNull_ {true}
Friends
class Value
Detailed Description
const iterator for object and array value.
Definition at line 1347 of file json.h.
Member Typedef Documentation
difference_type
using Json::ValueIteratorBase::difference_type = int inherited
Definition at line 1277 of file json.h.
iterator_category
using Json::ValueIteratorBase::iterator_category = std::bidirectional_iterator_tag inherited
Definition at line 1275 of file json.h.
pointer
using Json::ValueConstIterator::pointer = const Value*
Definition at line 1355 of file json.h.
reference
using Json::ValueConstIterator::reference = const Value&
Definition at line 1354 of file json.h.
SelfType
using Json::ValueConstIterator::SelfType = ValueConstIterator
Definition at line 1356 of file json.h.
size_t
using Json::ValueIteratorBase::size_t = unsigned int inherited
Definition at line 1276 of file json.h.
value_type
using Json::ValueConstIterator::value_type = const Value
Definition at line 1351 of file json.h.
Constructor & Destructor Documentation
ValueConstIterator() [1/3]
Json::ValueConstIterator::ValueConstIterator () default
ValueConstIterator() [2/3]
Json::ValueConstIterator::ValueConstIterator (ValueIterator const & other)
Definition at line 2378 of file jsoncpp.cpp.
ValueConstIterator() [3/3]
Json::ValueConstIterator::ValueConstIterator (const Value::ObjectValues::iterator & current) explicit private
Definition at line 2374 of file jsoncpp.cpp.
Member Function Documentation
computeDistance()
ValueIteratorBase::difference_type Json::ValueIteratorBase::computeDistance (const SelfType & other) const protected inherited
Definition at line 2288 of file jsoncpp.cpp.
References Json::ValueIteratorBase::current_, and Json::ValueIteratorBase::isNull_.
Referenced by Json::ValueIteratorBase::operator-().
copy()
void Json::ValueIteratorBase::copy (const SelfType & other) protected inherited
Definition at line 2318 of file jsoncpp.cpp.
References Json::ValueIteratorBase::current_, and Json::ValueIteratorBase::isNull_.
Referenced by Json::ValueIterator::operator=(), and operator=().
decrement()
void Json::ValueIteratorBase::decrement () protected inherited
Definition at line 2285 of file jsoncpp.cpp.
References Json::ValueIteratorBase::current_.
deref() [1/2]
Value & Json::ValueIteratorBase::deref () protected inherited
Definition at line 2280 of file jsoncpp.cpp.
References Json::ValueIteratorBase::current_.
deref() [2/2]
const Value & Json::ValueIteratorBase::deref () const protected inherited
Internal utility functions to assist with implementing other iterator functions. The const and non-const versions of the "deref" protected methods expose the protected current_ member variable in a way that can often be optimized away by the compiler.
Definition at line 2281 of file jsoncpp.cpp.
References Json::ValueIteratorBase::current_.
increment()
void Json::ValueIteratorBase::increment () protected inherited
Definition at line 2283 of file jsoncpp.cpp.
References Json::ValueIteratorBase::current_.
index()
UInt Json::ValueIteratorBase::index () const inherited
Return the index of the referenced Value, or -1 if it is not an arrayValue.
Definition at line 2333 of file jsoncpp.cpp.
References Json::Value::CZString::data(), and Json::Value::CZString::index().
isEqual()
bool Json::ValueIteratorBase::isEqual (const SelfType & other) const protected inherited
Definition at line 2311 of file jsoncpp.cpp.
References Json::ValueIteratorBase::current_, and Json::ValueIteratorBase::isNull_.
key()
Value Json::ValueIteratorBase::key () const inherited
Return either the index or the member name of the referenced value as a Value.
Definition at line 2323 of file jsoncpp.cpp.
References Json::Value::CZString::data(), Json::Value::CZString::index(), Json::Value::CZString::isStaticString(), and Json::Value::CZString::length().
memberName() [1/2]
char const * Json::ValueIteratorBase::memberName () const inherited
Return the member name of the referenced Value. "" if it is not an objectValue.
Deprecated:
This cannot be used for UTF-8 strings, since there can be embedded nulls.
Definition at line 2349 of file jsoncpp.cpp.
Referenced by Json::ValueIteratorBase::name().
memberName() [2/2]
char const * Json::ValueIteratorBase::memberName (char const ** end) const inherited
Return the member name of the referenced Value, or NULL if it is not an objectValue.
Note
Better version than memberName(). Allows embedded nulls.
Definition at line 2354 of file jsoncpp.cpp.
name()
String Json::ValueIteratorBase::name () const inherited
Return the member name of the referenced Value, or "" if it is not an objectValue.
Note
Avoid c_str() on result, as embedded zeroes are possible.
Definition at line 2340 of file jsoncpp.cpp.
References Json::ValueIteratorBase::memberName().
operator!=()
bool Json::ValueIteratorBase::operator!= (const SelfType & other) const inline inherited
Definition at line 1282 of file json.h.
operator*()
reference Json::ValueConstIterator::operator* () const inline
Definition at line 1391 of file json.h.
operator++() [1/2]
SelfType & Json::ValueConstIterator::operator++ () inline
Definition at line 1386 of file json.h.
operator++() [2/2]
SelfType Json::ValueConstIterator::operator++ (int) inline
Definition at line 1369 of file json.h.
operator-()
difference_type Json::ValueIteratorBase::operator- (const SelfType & other) const inline inherited
Definition at line 1284 of file json.h.
References Json::ValueIteratorBase::computeDistance().
operator--() [1/2]
SelfType & Json::ValueConstIterator::operator-- () inline
Definition at line 1381 of file json.h.
operator--() [2/2]
SelfType Json::ValueConstIterator::operator-- (int) inline
Definition at line 1375 of file json.h.
operator->()
pointer Json::ValueConstIterator::operator-> () const inline
Definition at line 1393 of file json.h.
operator=()
ValueConstIterator & Json::ValueConstIterator::operator= (const ValueIteratorBase & other)
Definition at line 2381 of file jsoncpp.cpp.
References Json::ValueIteratorBase::copy().
operator==()
bool Json::ValueIteratorBase::operator== (const SelfType & other) const inline inherited
Definition at line 1280 of file json.h.
Friends And Related Symbol Documentation
Value
friend class Value friend
Definition at line 1348 of file json.h.
Member Data Documentation
current_
Value::ObjectValues::iterator Json::ValueIteratorBase::current_ private inherited
Definition at line 1333 of file json.h.
Referenced by Json::ValueIteratorBase::computeDistance(), Json::ValueIteratorBase::copy(), Json::ValueIteratorBase::decrement(), Json::ValueIteratorBase::deref(), Json::ValueIteratorBase::deref(), Json::ValueIteratorBase::increment(), and Json::ValueIteratorBase::isEqual().
isNull_
bool Json::ValueIteratorBase::isNull_ {true} private inherited
Definition at line 1335 of file json.h.
Referenced by Json::ValueIteratorBase::computeDistance(), Json::ValueIteratorBase::copy(), and Json::ValueIteratorBase::isEqual().
The documentation for this class was generated from the following files:
json.h
jsoncpp.cpp