lilak: LKDetector Class Reference
LKDetector Class Reference
#include <LKDetector.h>
Public Member Functions
void AddPlane (LKDetectorPlane *plane, Int_t planeID=0)
TGeoVolume * CreateGeoTop (TString name="TOP")
void FinishGeometry ()
virtual LKChannelAnalyzer * GetChannelAnalyzer (int id=0)
LKDetectorPlane * GetDetectorPlane (Int_t idx=0)
virtual bool GetEffectiveDimension (Double_t &x1, Double_t &y1, Double_t &z1, Double_t &x2, Double_t &y2, Double_t &z2)
TGeoManager * GetGeoManager ()
Int_t GetNumPlanes ()
LKDetectorSystem * GetParent ()
virtual bool Init ()
virtual bool IsInBoundary (Double_t x, Double_t y, Double_t z)
LKDetector ()
LKDetector (const char *name, const char *title)
virtual void Print (Option_t *option="") const
void SetGeoManager (TGeoManager *)
void SetParent (LKDetectorSystem *system)
void SetRun (LKRun *run)
void SetTransparency (Int_t transparency)
virtual ~LKDetector ()
Public Member Functions inherited from LKGear
void AddPar (LKParameterContainer *par)
void AddPar (TString fname)
virtual void AddParameterContainer (LKParameterContainer *par)
virtual void AddParameterContainer (TString fname)
void CreateParameterContainer ()
LKParameterContainer * GetPar () const
LKParameterContainer * GetParameterContainer () const
Int_t GetRank () const
LKGear ()
void SetPar (LKParameterContainer *par)
virtual void SetParameterContainer (LKParameterContainer *par)
virtual void SetRank (Int_t rank)
void SetRun (LKRun *run)
virtual ~LKGear ()
Protected Member Functions
virtual bool BuildDetectorPlane ()
virtual bool BuildGeometry ()
Protected Attributes
LKChannelAnalyzer * fChannelAnalyzer0 = nullptr
TObjArray * fDetectorPlaneArray
TGeoManager * fGeoManager = nullptr
Int_t fNumPlanes = 0
int fNX
int fNY
int fNZ
LKDetectorSystem * fParent = nullptr
bool fUsePixelSpace
double fX1
double fX2
double fY1
double fY2
double fZ1
double fZ2
Protected Attributes inherited from LKGear
LKParameterContainer * fPar = nullptr
Int_t fRank = 0
LKRun * fRun = nullptr
Detailed Description
Definition at line 16 of file LKDetector.h.
Constructor & Destructor Documentation
LKDetector() [1/2]
LKDetector::LKDetector ()
LKDetector() [2/2]
LKDetector::LKDetector (const char * name, const char * title)
Definition at line 14 of file LKDetector.cpp.
~LKDetector()
virtual LKDetector::~LKDetector () inline virtual
Definition at line 21 of file LKDetector.h.
Member Function Documentation
AddPlane()
void LKDetector::AddPlane (LKDetectorPlane * plane, Int_t planeID = 0)
Definition at line 61 of file LKDetector.cpp.
References fDetectorPlaneArray, fNumPlanes, LKGear::fPar, LKGear::fRank, LKGear::fRun, LKGear::SetPar(), LKGear::SetRank(), and SetRun().
Referenced by AToMX::BuildDetectorPlane(), LAMPSTPC::BuildDetectorPlane(), STARK::BuildDetectorPlane(), TeBAT::BuildDetectorPlane(), TexAT2::BuildDetectorPlane(), LHTpc::BuildDetectorPlane(), and ATTPC::BuildDetectorPlane().
BuildDetectorPlane()
virtual bool LKDetector::BuildDetectorPlane () inline protected virtual
Reimplemented in AToMX, LAMPSTPC, STARK, TeBAT, TexAT2, LHTpc, and ATTPC.
Definition at line 50 of file LKDetector.h.
Referenced by Init().
BuildGeometry()
virtual bool LKDetector::BuildGeometry () inline protected virtual
Reimplemented in LAMPSTPC, TexAT2, LHTpc, and ATTPC.
Definition at line 49 of file LKDetector.h.
CreateGeoTop()
TGeoVolume * LKDetector::CreateGeoTop (TString name = "TOP")
Definition at line 81 of file LKDetector.cpp.
References fGeoManager, fParent, and lk_info.
Referenced by LHTpc::BuildGeometry().
FinishGeometry()
void LKDetector::FinishGeometry ()
Definition at line 94 of file LKDetector.cpp.
References fGeoManager, fParent, and lk_info.
Referenced by LHTpc::BuildGeometry(), and ATTPC::BuildGeometry().
GetChannelAnalyzer()
LKChannelAnalyzer * LKDetector::GetChannelAnalyzer (int id = 0) virtual
Reimplemented in TexAT2.
Definition at line 144 of file LKDetector.cpp.
References LKParameterContainer::CheckPar(), fChannelAnalyzer0, and LKGear::fPar.
GetDetectorPlane()
LKDetectorPlane * LKDetector::GetDetectorPlane (Int_t idx = 0)
Definition at line 76 of file LKDetector.cpp.
References fDetectorPlaneArray.
Referenced by LKTpc::GetPadPlane().
GetEffectiveDimension()
bool LKDetector::GetEffectiveDimension (Double_t & x1, Double_t & y1, Double_t & z1, Double_t & x2, Double_t & y2, Double_t & z2) virtual
Reimplemented in LAMPSTPC, and TexAT2.
Definition at line 122 of file LKDetector.cpp.
References fNX, fNY, fNZ, fUsePixelSpace, fX1, fX2, fY1, fY2, fZ1, fZ2, y2, z1, and z2.
GetGeoManager()
TGeoManager * LKDetector::GetGeoManager ()
Definition at line 50 of file LKDetector.cpp.
References fGeoManager.
GetNumPlanes()
Int_t LKDetector::GetNumPlanes ()
Definition at line 74 of file LKDetector.cpp.
References fNumPlanes.
GetParent()
LKDetectorSystem * LKDetector::GetParent ()
Definition at line 78 of file LKDetector.cpp.
References fParent.
Init()
bool LKDetector::Init () virtual
Reimplemented in LAMPSTPC, TexAT2, LHTpc, and ATTPC.
Definition at line 28 of file LKDetector.cpp.
References BuildDetectorPlane(), fDetectorPlaneArray, fNumPlanes, fNX, fNY, fNZ, LKGear::fPar, fUsePixelSpace, fX1, fX2, fY1, fY2, fZ1, fZ2, Init(), lk_error, and LKGear::SetPar().
Referenced by LAMPSTPC::Init(), Init(), and TexAT2::Init().
IsInBoundary()
bool LKDetector::IsInBoundary (Double_t x, Double_t y, Double_t z) virtual
Reimplemented in LAMPSTPC, and TexAT2.
Definition at line 115 of file LKDetector.cpp.
References fX1, fY1, fZ1, and fZ2.
Print()
void LKDetector::Print (Option_t * option = "") const virtual
Reimplemented in LAMPSTPC, and TexAT2.
Definition at line 19 of file LKDetector.cpp.
References fDetectorPlaneArray, fNumPlanes, lk_info, and Print().
Referenced by Print().
SetGeoManager()
void LKDetector::SetGeoManager (TGeoManager * man)
Definition at line 51 of file LKDetector.cpp.
References fGeoManager.
SetParent()
void LKDetector::SetParent (LKDetectorSystem * system)
Definition at line 79 of file LKDetector.cpp.
References fParent.
SetRun()
void LKDetector::SetRun (LKRun * run)
Definition at line 106 of file LKDetector.cpp.
References fDetectorPlaneArray, fNumPlanes, LKGear::fRun, run, and SetRun().
Referenced by AddPlane(), and SetRun().
SetTransparency()
void LKDetector::SetTransparency (Int_t transparency)
Definition at line 53 of file LKDetector.cpp.
References SetTransparency().
Referenced by LHTpc::BuildGeometry(), ATTPC::BuildGeometry(), and SetTransparency().
Member Data Documentation
fChannelAnalyzer0
LKChannelAnalyzer* LKDetector::fChannelAnalyzer0 = nullptr protected
Definition at line 59 of file LKDetector.h.
Referenced by GetChannelAnalyzer().
fDetectorPlaneArray
TObjArray* LKDetector::fDetectorPlaneArray protected
Definition at line 55 of file LKDetector.h.
Referenced by AddPlane(), GetDetectorPlane(), LHTpc::GetDriftPlane(), ATTPC::GetDriftPlane(), Init(), LAMPSTPC::LAMPSTPC(), Print(), SetRun(), and TexAT2::TexAT2().
fGeoManager
TGeoManager* LKDetector::fGeoManager = nullptr protected
Definition at line 52 of file LKDetector.h.
Referenced by LHTpc::BuildGeometry(), ATTPC::BuildGeometry(), CreateGeoTop(), FinishGeometry(), GetGeoManager(), and SetGeoManager().
fNumPlanes
Int_t LKDetector::fNumPlanes = 0 protected
Definition at line 54 of file LKDetector.h.
Referenced by AddPlane(), GetNumPlanes(), Init(), Print(), and SetRun().
fNX
int LKDetector::fNX protected
Definition at line 61 of file LKDetector.h.
Referenced by GetEffectiveDimension(), and Init().
fNY
int LKDetector::fNY protected
Definition at line 65 of file LKDetector.h.
Referenced by GetEffectiveDimension(), and Init().
fNZ
int LKDetector::fNZ protected
Definition at line 69 of file LKDetector.h.
Referenced by GetEffectiveDimension(), and Init().
fParent
LKDetectorSystem* LKDetector::fParent = nullptr protected
Definition at line 57 of file LKDetector.h.
Referenced by CreateGeoTop(), FinishGeometry(), GetParent(), and SetParent().
fUsePixelSpace
bool LKDetector::fUsePixelSpace protected
Definition at line 73 of file LKDetector.h.
Referenced by GetEffectiveDimension(), and Init().
fX1
double LKDetector::fX1 protected
Definition at line 62 of file LKDetector.h.
Referenced by GetEffectiveDimension(), Init(), and IsInBoundary().
fX2
double LKDetector::fX2 protected
Definition at line 63 of file LKDetector.h.
Referenced by GetEffectiveDimension(), and Init().
fY1
double LKDetector::fY1 protected
Definition at line 67 of file LKDetector.h.
Referenced by GetEffectiveDimension(), Init(), and IsInBoundary().
fY2
double LKDetector::fY2 protected
Definition at line 66 of file LKDetector.h.
Referenced by GetEffectiveDimension(), and Init().
fZ1
double LKDetector::fZ1 protected
Definition at line 70 of file LKDetector.h.
Referenced by GetEffectiveDimension(), Init(), and IsInBoundary().
fZ2
double LKDetector::fZ2 protected
Definition at line 71 of file LKDetector.h.
Referenced by GetEffectiveDimension(), Init(), and IsInBoundary().
The documentation for this class was generated from the following files:
LKDetector.h
LKDetector.cpp