LILAK: Json::ValueIterator Class Reference
Json::ValueIterator Class Reference
Iterator for object and array value.
#include <json.h>
Public Types
using difference_type = int
using iterator_category = std::bidirectional_iterator_tag
using pointer = Value *
using reference = Value &
using SelfType = ValueIterator
using size_t = unsigned int
using value_type = Value
Public Member Functions
UInt index () const
Value key () const
char const * memberName () const
char const * memberName (char const **end) const
String name () const
bool operator!= (const SelfType &other) const
reference operator* () const
SelfType & operator++ ()
SelfType operator++ (int)
difference_type operator- (const SelfType &other) const
SelfType & operator-- ()
SelfType operator-- (int)
pointer operator-> () const
SelfType & operator= (const SelfType &other)
bool operator== (const SelfType &other) const
ValueIterator ()
ValueIterator (const ValueConstIterator &other)
ValueIterator (const ValueIterator &other)
Protected Member Functions
difference_type computeDistance (const SelfType &other) const
void copy (const SelfType &other)
void decrement ()
Value & deref ()
const Value & deref () const
void increment ()
bool isEqual (const SelfType &other) const
Private Member Functions
ValueIterator (const Value::ObjectValues::iterator &current)
Private Attributes
Value::ObjectValues::iterator current_
bool isNull_ {true}
Friends
class Value
Detailed Description
Iterator for object and array value.
Definition at line 1398 of file json.h.
Member Typedef Documentation
difference_type
using Json::ValueIterator::difference_type = int
Definition at line 1404 of file json.h.
iterator_category
using Json::ValueIteratorBase::iterator_category = std::bidirectional_iterator_tag inherited
Definition at line 1275 of file json.h.
pointer
using Json::ValueIterator::pointer = Value*
Definition at line 1406 of file json.h.
reference
using Json::ValueIterator::reference = Value&
Definition at line 1405 of file json.h.
SelfType
using Json::ValueIterator::SelfType = ValueIterator
Definition at line 1407 of file json.h.
size_t
using Json::ValueIterator::size_t = unsigned int
Definition at line 1403 of file json.h.
value_type
using Json::ValueIterator::value_type = Value
Definition at line 1402 of file json.h.
Constructor & Destructor Documentation
ValueIterator() [1/4]
Json::ValueIterator::ValueIterator () default
ValueIterator() [2/4]
Json::ValueIterator::ValueIterator (const ValueConstIterator & other) explicit
Definition at line 2400 of file jsoncpp.cpp.
References Json::throwRuntimeError().
ValueIterator() [3/4]
Json::ValueIterator::ValueIterator (const ValueIterator & other) default
ValueIterator() [4/4]
Json::ValueIterator::ValueIterator (const Value::ObjectValues::iterator & current) explicit private
Definition at line 2397 of file jsoncpp.cpp.
Member Function Documentation
computeDistance()
ValueIteratorBase::difference_type Json::ValueIteratorBase::computeDistance (const SelfType & other) const protected inherited
Definition at line 2288 of file jsoncpp.cpp.
References Json::ValueIteratorBase::current_, and Json::ValueIteratorBase::isNull_.
Referenced by Json::ValueIteratorBase::operator-().
copy()
void Json::ValueIteratorBase::copy (const SelfType & other) protected inherited
Definition at line 2318 of file jsoncpp.cpp.
References Json::ValueIteratorBase::current_, and Json::ValueIteratorBase::isNull_.
Referenced by operator=(), and Json::ValueConstIterator::operator=().
decrement()
void Json::ValueIteratorBase::decrement () protected inherited
Definition at line 2285 of file jsoncpp.cpp.
References Json::ValueIteratorBase::current_.
deref() [1/2]
Value & Json::ValueIteratorBase::deref () protected inherited
Definition at line 2280 of file jsoncpp.cpp.
References Json::ValueIteratorBase::current_.
deref() [2/2]
const Value & Json::ValueIteratorBase::deref () const protected inherited
Internal utility functions to assist with implementing other iterator functions. The const and non-const versions of the "deref" protected methods expose the protected current_ member variable in a way that can often be optimized away by the compiler.
Definition at line 2281 of file jsoncpp.cpp.
References Json::ValueIteratorBase::current_.
increment()
void Json::ValueIteratorBase::increment () protected inherited
Definition at line 2283 of file jsoncpp.cpp.
References Json::ValueIteratorBase::current_.
index()
UInt Json::ValueIteratorBase::index () const inherited
Return the index of the referenced Value, or -1 if it is not an arrayValue.
Definition at line 2333 of file jsoncpp.cpp.
References Json::Value::CZString::data(), and Json::Value::CZString::index().
isEqual()
bool Json::ValueIteratorBase::isEqual (const SelfType & other) const protected inherited
Definition at line 2311 of file jsoncpp.cpp.
References Json::ValueIteratorBase::current_, and Json::ValueIteratorBase::isNull_.
key()
Value Json::ValueIteratorBase::key () const inherited
Return either the index or the member name of the referenced value as a Value.
Definition at line 2323 of file jsoncpp.cpp.
References Json::Value::CZString::data(), Json::Value::CZString::index(), Json::Value::CZString::isStaticString(), and Json::Value::CZString::length().
memberName() [1/2]
char const * Json::ValueIteratorBase::memberName () const inherited
Return the member name of the referenced Value. "" if it is not an objectValue.
Deprecated:
This cannot be used for UTF-8 strings, since there can be embedded nulls.
Definition at line 2349 of file jsoncpp.cpp.
Referenced by Json::ValueIteratorBase::name().
memberName() [2/2]
char const * Json::ValueIteratorBase::memberName (char const ** end) const inherited
Return the member name of the referenced Value, or NULL if it is not an objectValue.
Note
Better version than memberName(). Allows embedded nulls.
Definition at line 2354 of file jsoncpp.cpp.
name()
String Json::ValueIteratorBase::name () const inherited
Return the member name of the referenced Value, or "" if it is not an objectValue.
Note
Avoid c_str() on result, as embedded zeroes are possible.
Definition at line 2340 of file jsoncpp.cpp.
References Json::ValueIteratorBase::memberName().
operator!=()
bool Json::ValueIteratorBase::operator!= (const SelfType & other) const inline inherited
Definition at line 1282 of file json.h.
operator*()
reference Json::ValueIterator::operator* () const inline
The return value of non-const iterators can be changed, so the these functions are not const because the returned references/pointers can be used to change state of the base class.
Definition at line 1448 of file json.h.
operator++() [1/2]
SelfType & Json::ValueIterator::operator++ () inline
Definition at line 1438 of file json.h.
operator++() [2/2]
SelfType Json::ValueIterator::operator++ (int) inline
Definition at line 1421 of file json.h.
operator-()
difference_type Json::ValueIteratorBase::operator- (const SelfType & other) const inline inherited
Definition at line 1284 of file json.h.
References Json::ValueIteratorBase::computeDistance().
operator--() [1/2]
SelfType & Json::ValueIterator::operator-- () inline
Definition at line 1433 of file json.h.
operator--() [2/2]
SelfType Json::ValueIterator::operator-- (int) inline
Definition at line 1427 of file json.h.
operator->()
pointer Json::ValueIterator::operator-> () const inline
Definition at line 1449 of file json.h.
operator=()
ValueIterator & Json::ValueIterator::operator= (const SelfType & other)
Definition at line 2407 of file jsoncpp.cpp.
References Json::ValueIteratorBase::copy().
operator==()
bool Json::ValueIteratorBase::operator== (const SelfType & other) const inline inherited
Definition at line 1280 of file json.h.
Friends And Related Symbol Documentation
Value
friend class Value friend
Definition at line 1399 of file json.h.
Member Data Documentation
current_
Value::ObjectValues::iterator Json::ValueIteratorBase::current_ private inherited
Definition at line 1333 of file json.h.
Referenced by Json::ValueIteratorBase::computeDistance(), Json::ValueIteratorBase::copy(), Json::ValueIteratorBase::decrement(), Json::ValueIteratorBase::deref(), Json::ValueIteratorBase::deref(), Json::ValueIteratorBase::increment(), and Json::ValueIteratorBase::isEqual().
isNull_
bool Json::ValueIteratorBase::isNull_ {true} private inherited
Definition at line 1335 of file json.h.
Referenced by Json::ValueIteratorBase::computeDistance(), Json::ValueIteratorBase::copy(), and Json::ValueIteratorBase::isEqual().
The documentation for this class was generated from the following files:
json.h
jsoncpp.cpp