lilak: LKMisc Class Reference
LKMisc Class Reference
#include <LKMisc.h>
Public Member Functions
LKMisc ()
virtual ~LKMisc ()
Static Public Member Functions
static void DrawColors ()
static void DrawColors (vector< int > colors)
static void DrawMarkers ()
static double EvalPedestal (double *buffer, int length, int method=0)
static double EvalPedestalSamplingMethod (double *buffer, int length, int sampleLength=50, double cvCut=0.2, bool subtractPedestal=false)
cvCut: stdDev/mean cut for collecting samples used for calculating pedestal.
static double FWHM (double *buffer, int length)
static double FWHM (double *buffer, int length, int xPeak, double amplitude, double pedestal, double &xMin, double &xMax)
static LKMisc * GetMisc ()
Private Member Functions
ClassDef (LKMisc, 1)
Static Private Attributes
static LKMisc * fInstance = nullptr
Detailed Description
Definition at line 9 of file tool/LKMisc.h.
Constructor & Destructor Documentation
LKMisc()
LKMisc::LKMisc ()
Definition at line 25 of file tool/LKMisc.cpp.
References fInstance, and LKMisc().
Referenced by LKMisc().
~LKMisc()
virtual LKMisc::~LKMisc () inline virtual
Definition at line 25 of file tool/LKMisc.h.
Member Function Documentation
ClassDef()
LKMisc::ClassDef (LKMisc , 1) private
DrawColors() [1/2]
void LKMisc::DrawColors () static
Definition at line 343 of file tool/LKMisc.cpp.
References cvs1, cvs2, DrawColors(), and e_painter.
Referenced by DrawColors(), and DrawColors().
DrawColors() [2/2]
void LKMisc::DrawColors (vector< int > colors) static
Definition at line 388 of file tool/LKMisc.cpp.
References cvs, DrawColors(), e_painter, x, and y.
DrawMarkers()
void LKMisc::DrawMarkers () static
Definition at line 354 of file tool/LKMisc.cpp.
References cvs, DrawMarkers(), e_painter, x, and y.
Referenced by DrawMarkers().
EvalPedestal()
double LKMisc::EvalPedestal (double * buffer, int length, int method = 0) static
Definition at line 176 of file tool/LKMisc.cpp.
References e_error, EvalPedestal(), and EvalPedestalSamplingMethod().
Referenced by EvalPedestal(), and FWHM().
EvalPedestalSamplingMethod()
double LKMisc::EvalPedestalSamplingMethod (double * buffer, int length, int sampleLength = 50, double cvCut = 0.2, bool subtractPedestal = false) static
cvCut: stdDev/mean cut for collecting samples used for calculating pedestal.
Definition at line 183 of file tool/LKMisc.cpp.
References EvalPedestalSamplingMethod(), and lk_debug.
Referenced by EvalPedestal(), and EvalPedestalSamplingMethod().
FWHM() [1/2]
double LKMisc::FWHM (double * buffer, int length) static
Definition at line 29 of file tool/LKMisc.cpp.
References EvalPedestal(), FWHM(), lk_debug, and x.
Referenced by FWHM(), and FWHM().
FWHM() [2/2]
double LKMisc::FWHM (double * buffer, int length, int xPeak, double amplitude, double pedestal, double & xMin, double & xMax) static
Definition at line 57 of file tool/LKMisc.cpp.
References FWHM(), lk_debug, x, x0, y, y0, and y2.
GetMisc()
LKMisc * LKMisc::GetMisc () static
Definition at line 19 of file tool/LKMisc.cpp.
References fInstance, and GetMisc().
Referenced by GetMisc().
Member Data Documentation
fInstance
LKMisc * LKMisc::fInstance = nullptr static private
Definition at line 29 of file tool/LKMisc.h.
Referenced by GetMisc(), and LKMisc().
The documentation for this class was generated from the following files:
tool/LKMisc.h
tool/LKMisc.cpp