LILAK: ATTPCPhysicsList Class Reference
ATTPCPhysicsList Class Reference
#include <ATTPCPhysicsList.h>
Public Member Functions
ATTPCPhysicsList ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
virtual void SetCuts ()
virtual ~ATTPCPhysicsList ()
Protected Member Functions
void AddLimiterProcess ()
void AddProcessParameter ()
Detailed Description
Definition at line 14 of file ATTPCPhysicsList.h.
Constructor & Destructor Documentation
ATTPCPhysicsList()
ATTPCPhysicsList::ATTPCPhysicsList ()
Definition at line 60 of file ATTPCPhysicsList.cpp.
~ATTPCPhysicsList()
ATTPCPhysicsList::~ATTPCPhysicsList ()
Definition at line 74 of file ATTPCPhysicsList.cpp.
Member Function Documentation
AddLimiterProcess()
void ATTPCPhysicsList::AddLimiterProcess () protected
Definition at line 286 of file ATTPCPhysicsList.cpp.
Referenced by ConstructProcess().
AddProcessParameter()
void ATTPCPhysicsList::AddProcessParameter () protected
Definition at line 111 of file ATTPCPhysicsList.cpp.
Referenced by ConstructProcess().
ConstructParticle()
void ATTPCPhysicsList::ConstructParticle () virtual
Definition at line 78 of file ATTPCPhysicsList.cpp.
ConstructProcess()
void ATTPCPhysicsList::ConstructProcess () virtual
Definition at line 93 of file ATTPCPhysicsList.cpp.
References AddLimiterProcess(), and AddProcessParameter().
SetCuts()
void ATTPCPhysicsList::SetCuts () virtual
Definition at line 100 of file ATTPCPhysicsList.cpp.
The documentation for this class was generated from the following files:
ATTPCPhysicsList.h
ATTPCPhysicsList.cpp