lilak: LKGeoRotated Class Reference
LKGeoRotated Class Reference
#include <LKGeoRotated.h>
Public Member Functions
virtual void Clear (Option_t *option="")
virtual TVector3 GetCenter () const
TRotation GetRotation () const
TVector3 InvRotate (TVector3 pos) const
LKGeoRotated ()
TVector3 Rotate (TVector3 pos) const
void SetRotation (TRotation rot)
virtual ~LKGeoRotated ()
Public Member Functions inherited from LKGeometry
Double_t GetRMS () const
LKGeometry ()
void SetRMS (Double_t val)
virtual ~LKGeometry ()
Protected Attributes
TRotation fRotation
Protected Attributes inherited from LKGeometry
Double_t fRMS = -1
Detailed Description
Definition at line 7 of file LKGeoRotated.h.
Constructor & Destructor Documentation
LKGeoRotated()
LKGeoRotated::LKGeoRotated () inline
Definition at line 13 of file LKGeoRotated.h.
~LKGeoRotated()
virtual LKGeoRotated::~LKGeoRotated () inline virtual
Definition at line 14 of file LKGeoRotated.h.
Member Function Documentation
Clear()
virtual void LKGeoRotated::Clear (Option_t * option = "") virtual
Reimplemented in LKGeoBox.
Referenced by LKGeoBox::Clear().
GetCenter()
virtual TVector3 LKGeoRotated::GetCenter () const inline virtual
Reimplemented in LKGeo2DBox, and LKGeoBox.
Definition at line 18 of file LKGeoRotated.h.
Referenced by InvRotate(), and Rotate().
GetRotation()
TRotation LKGeoRotated::GetRotation () const inline
Definition at line 24 of file LKGeoRotated.h.
References fRotation.
InvRotate()
TVector3 LKGeoRotated::InvRotate (TVector3 pos) const
Definition at line 19 of file LKGeoRotated.cpp.
References fRotation, and GetCenter().
Rotate()
TVector3 LKGeoRotated::Rotate (TVector3 pos) const
Definition at line 10 of file LKGeoRotated.cpp.
References fRotation, and GetCenter().
SetRotation()
void LKGeoRotated::SetRotation (TRotation rot) inline
Definition at line 23 of file LKGeoRotated.h.
References fRotation.
Member Data Documentation
fRotation
TRotation LKGeoRotated::fRotation protected
Definition at line 10 of file LKGeoRotated.h.
Referenced by ClassImp(), GetRotation(), InvRotate(), Rotate(), and SetRotation().
The documentation for this class was generated from the following files:
LKGeoRotated.h
LKGeoRotated.cpp