LILAK: LKWPoint Class Reference
LKWPoint Class Reference
position data with weight
#include <LKWPoint.h>
Public Member Functions
virtual void Clear (Option_t *option="")
virtual void Copy (TObject &object) const
virtual bool DrawByDefault ()
return true if to be displayed on eve.
TVector3 GetPosition () const
LKVector3 GetPosition (LKVector3::Axis ref) const
LKWPoint ()
LKWPoint (Double_t x, Double_t y, Double_t z, Double_t w=1)
Double_t & operator[] (int i)
Double_t operator[] (int i) const
virtual void Print (Option_t *option="") const
void Set (Double_t x, Double_t y, Double_t z, Double_t w=1)
void SetPosition (Double_t x, Double_t y, Double_t z)
void SetPosition (TVector3 pos)
void SetWeight (Double_t w)
Double_t w () const
Double_t W () const
Double_t x () const
Double_t X () const
Double_t y () const
Double_t Y () const
Double_t z () const
Double_t Z () const
Protected Attributes
Double_t fW
Double_t fX
Double_t fY
Double_t fZ
Detailed Description
position data with weight
Definition at line 17 of file LKWPoint.h.
Constructor & Destructor Documentation
LKWPoint() [1/2]
LKWPoint::LKWPoint ()
LKWPoint() [2/2]
LKWPoint::LKWPoint (Double_t x, Double_t y, Double_t z, Double_t w = 1)
Definition at line 14 of file LKWPoint.cpp.
References Set(), w(), x(), y(), and z().
Member Function Documentation
Clear()
void LKWPoint::Clear (Option_t * option = "") virtual
Reimplemented from LKContainer.
Definition at line 44 of file LKWPoint.cpp.
References LKContainer::Clear(), fW, fX, fY, and fZ.
Referenced by ClassImp().
Copy()
void LKWPoint::Copy (TObject & object) const virtual
Reimplemented from LKContainer.
Definition at line 53 of file LKWPoint.cpp.
References LKContainer::Copy(), fW, fX, fY, and fZ.
DrawByDefault()
virtual bool LKContainer::DrawByDefault () inline virtual inherited
return true if to be displayed on eve.
Reimplemented in LKHit, and LKTracklet.
Definition at line 18 of file LKContainer.h.
Referenced by LKEveTask::DrawEve3D().
GetPosition() [1/2]
TVector3 LKWPoint::GetPosition () const inline
Definition at line 32 of file LKWPoint.h.
References fX, fY, and fZ.
GetPosition() [2/2]
LKVector3 LKWPoint::GetPosition (LKVector3::Axis ref) const inline
Definition at line 33 of file LKWPoint.h.
References fX, fY, and fZ.
operator[]() [1/2]
Double_t & LKWPoint::operator[] (int i) inline
Definition at line 45 of file LKWPoint.h.
References fX, fY, and fZ.
operator[]() [2/2]
Double_t LKWPoint::operator[] (int i) const inline
Definition at line 59 of file LKWPoint.h.
References fX, fY, and fZ.
Print()
void LKWPoint::Print (Option_t * option = "") const virtual
Definition at line 27 of file LKWPoint.cpp.
References e_info, fW, fX, fY, and fZ.
Set()
void LKWPoint::Set (Double_t x, Double_t y, Double_t z, Double_t w = 1)
Definition at line 19 of file LKWPoint.cpp.
References fW, fX, fY, fZ, w(), x(), y(), and z().
Referenced by LKWPoint().
SetPosition() [1/2]
void LKWPoint::SetPosition (Double_t x, Double_t y, Double_t z)
Definition at line 63 of file LKWPoint.cpp.
References fX, fY, fZ, x(), y(), and z().
SetPosition() [2/2]
void LKWPoint::SetPosition (TVector3 pos)
Definition at line 70 of file LKWPoint.cpp.
References fX, fY, and fZ.
SetWeight()
void LKWPoint::SetWeight (Double_t w)
Definition at line 61 of file LKWPoint.cpp.
References fW, and w().
w()
Double_t LKWPoint::w () const inline
Definition at line 38 of file LKWPoint.h.
References fW.
Referenced by LKWPoint(), Set(), and SetWeight().
W()
Double_t LKWPoint::W () const inline
Definition at line 43 of file LKWPoint.h.
References fW.
x()
Double_t LKWPoint::x () const inline
Definition at line 35 of file LKWPoint.h.
References fX.
Referenced by LKWPoint(), Set(), and SetPosition().
X()
Double_t LKWPoint::X () const inline
Definition at line 40 of file LKWPoint.h.
References fX.
y()
Double_t LKWPoint::y () const inline
Definition at line 36 of file LKWPoint.h.
References fY.
Referenced by LKWPoint(), Set(), and SetPosition().
Y()
Double_t LKWPoint::Y () const inline
Definition at line 41 of file LKWPoint.h.
References fY.
z()
Double_t LKWPoint::z () const inline
Definition at line 37 of file LKWPoint.h.
References fZ.
Referenced by LKWPoint(), Set(), and SetPosition().
Z()
Double_t LKWPoint::Z () const inline
Definition at line 42 of file LKWPoint.h.
References fZ.
Member Data Documentation
fW
Double_t LKWPoint::fW protected
Definition at line 85 of file LKWPoint.h.
Referenced by Clear(), Copy(), Print(), Set(), SetWeight(), w(), and W().
fX
Double_t LKWPoint::fX protected
Definition at line 82 of file LKWPoint.h.
Referenced by Clear(), Copy(), GetPosition(), GetPosition(), operator[](), operator[](), Print(), Set(), SetPosition(), SetPosition(), x(), and X().
fY
Double_t LKWPoint::fY protected
Definition at line 83 of file LKWPoint.h.
Referenced by Clear(), Copy(), GetPosition(), GetPosition(), operator[](), operator[](), Print(), Set(), SetPosition(), SetPosition(), y(), and Y().
fZ
Double_t LKWPoint::fZ protected
Definition at line 84 of file LKWPoint.h.
Referenced by Clear(), Copy(), GetPosition(), GetPosition(), operator[](), operator[](), Print(), Set(), SetPosition(), SetPosition(), z(), and Z().
The documentation for this class was generated from the following files:
LKWPoint.h
LKWPoint.cpp