lilak: LKChannel Class Reference
LKChannel Class Reference
#include <LKChannel.h>
Public Member Functions
virtual void Clear (Option_t *option="")
virtual TObject * Clone (const char *newname="") const
virtual void Copy (TObject &obj) const
int GetChannelID () const
int GetDetID () const
double GetEnergy () const
double GetNoiseScale () const
int GetPadID () const
double GetPedestal () const
double GetTime () const
LKChannel ()
virtual void Print (Option_t *option="") const
void SetChannelID (int value)
void SetDetID (int value)
void SetEnergy (double value)
void SetNoiseScale (double value)
void SetPadID (int value)
void SetPedestal (double value)
void SetTime (double value)
virtual ~LKChannel ()
Public Member Functions inherited from LKContainer
virtual void Clear (Option_t *option="")
virtual TObject * Clone (const char *newname="") const
virtual void Copy (TObject &object) const
virtual bool DrawByDefault ()
return true if to be displayed on eve.
LKContainer ()
virtual ~LKContainer ()
Protected Attributes
int fChannelID = -1
double fEnergy = -1
double fNoiseScale = -1
int fPadID = -1
double fPedestal = -1
double fTime = -1
Detailed Description
General channel Note that PadID is shared with DetID Use PadID for TPC, and DetID for Other detectors
Definition at line 15 of file LKChannel.h.
Constructor & Destructor Documentation
LKChannel()
LKChannel::LKChannel ()
~LKChannel()
virtual LKChannel::~LKChannel () inline virtual
Definition at line 19 of file LKChannel.h.
Member Function Documentation
Clear()
void LKChannel::Clear (Option_t * option = "") virtual
Reimplemented from LKContainer.
Reimplemented in GETChannel, LKPad, and LKSiChannel.
Definition at line 12 of file LKChannel.cpp.
References LKContainer::Clear(), fChannelID, fEnergy, fNoiseScale, fPadID, fPedestal, and fTime.
Referenced by ClassImp(), and GETChannel::Clear().
Clone()
TObject * LKChannel::Clone (const char * newname = "") const virtual
Reimplemented from LKContainer.
Reimplemented in GETChannel, and LKSiChannel.
Definition at line 36 of file LKChannel.cpp.
References LKContainer::Clone(), fChannelID, fEnergy, fNoiseScale, fPadID, fPedestal, fTime, SetChannelID(), SetEnergy(), SetNoiseScale(), SetPadID(), SetPedestal(), and SetTime().
Referenced by GETChannel::Clone().
Copy()
void LKChannel::Copy (TObject & obj) const virtual
Reimplemented from LKContainer.
Reimplemented in GETChannel, and LKSiChannel.
Definition at line 24 of file LKChannel.cpp.
References LKContainer::Copy(), fChannelID, fEnergy, fNoiseScale, fPadID, fPedestal, and fTime.
Referenced by GETChannel::Copy().
GetChannelID()
int LKChannel::GetChannelID () const inline
Definition at line 35 of file LKChannel.h.
References fChannelID.
Referenced by LKPad::SetPad().
GetDetID()
int LKChannel::GetDetID () const inline
Definition at line 36 of file LKChannel.h.
References fPadID.
GetEnergy()
double LKChannel::GetEnergy () const inline
Definition at line 39 of file LKChannel.h.
References fEnergy.
Referenced by LKPad::CopyPadData(), LKPad::SetPad(), and SKSiArrayPlane::SetSiChannelData().
GetNoiseScale()
double LKChannel::GetNoiseScale () const inline
Definition at line 41 of file LKChannel.h.
References fNoiseScale.
Referenced by LKPad::CopyPadData(), LKPad::SetPad(), and SKSiArrayPlane::SetSiChannelData().
GetPadID()
int LKChannel::GetPadID () const inline
Definition at line 37 of file LKChannel.h.
References fPadID.
Referenced by LKDetectorPlane::FillDataToHist(), LKPadPlane::FillDataToHist(), LTPadPlane::FillDataToHist(), LKEvePlane::FillDataToHistEventDisplay1(), LKSiChannel::GetDetID(), LHPadPlaneFan::MapPad(), LKDetectorPlane::PadNeighborChecker(), LKPadPlane::PadNeighborChecker(), and LKPad::SetPad().
GetPedestal()
double LKChannel::GetPedestal () const inline
Definition at line 40 of file LKChannel.h.
References fPedestal.
Referenced by LKPad::CopyPadData(), LKPad::SetPad(), and SKSiArrayPlane::SetSiChannelData().
GetTime()
double LKChannel::GetTime () const inline
Definition at line 38 of file LKChannel.h.
References fTime.
Referenced by LKPad::CopyPadData(), LKPad::SetPad(), and SKSiArrayPlane::SetSiChannelData().
Print()
void LKChannel::Print (Option_t * option = "") const virtual
Reimplemented in GETChannel, LKPad, and LKSiChannel.
Definition at line 48 of file LKChannel.cpp.
References e_info, fChannelID, fEnergy, fNoiseScale, fPadID, fPedestal, and fTime.
Referenced by GETChannel::Print().
SetChannelID()
void LKChannel::SetChannelID (int value) inline
Definition at line 27 of file LKChannel.h.
References fChannelID.
Referenced by Clone().
SetDetID()
void LKChannel::SetDetID (int value) inline
Definition at line 29 of file LKChannel.h.
References fPadID.
SetEnergy()
void LKChannel::SetEnergy (double value) inline
Definition at line 31 of file LKChannel.h.
References fEnergy.
Referenced by Clone().
SetNoiseScale()
void LKChannel::SetNoiseScale (double value) inline
Definition at line 33 of file LKChannel.h.
References fNoiseScale.
Referenced by Clone().
SetPadID()
void LKChannel::SetPadID (int value) inline
Definition at line 28 of file LKChannel.h.
References fPadID.
Referenced by Clone(), and LKSiChannel::SetDetID().
SetPedestal()
void LKChannel::SetPedestal (double value) inline
Definition at line 32 of file LKChannel.h.
References fPedestal.
Referenced by Clone().
SetTime()
void LKChannel::SetTime (double value) inline
Definition at line 30 of file LKChannel.h.
References fTime.
Referenced by Clone().
Member Data Documentation
fChannelID
int LKChannel::fChannelID = -1 protected
Definition at line 44 of file LKChannel.h.
Referenced by Clear(), Clone(), Copy(), GetChannelID(), LKPad::GetHist(), LKSiChannel::GetName(), LKSiChannel::GetTitle(), Print(), LKSiChannel::Print(), SetChannelID(), LKPad::SetHist(), and LKPad::SetPad().
fEnergy
double LKChannel::fEnergy = -1 protected
Definition at line 47 of file LKChannel.h.
Referenced by Clear(), LKSiChannel::Clear(), Clone(), Copy(), LKPad::CopyPadData(), GetEnergy(), LKSiChannel::GetEnergy1(), LKSiChannel::GetEnergyPos(), LKSiChannel::GetEnergySum(), GETChannel::GetHitGraph(), Print(), LKSiChannel::Print(), SetEnergy(), LKSiChannel::SetEnergy1(), and LKPad::SetPad().
fNoiseScale
double LKChannel::fNoiseScale = -1 protected
Definition at line 49 of file LKChannel.h.
Referenced by Clear(), Clone(), Copy(), LKPad::CopyPadData(), GetNoiseScale(), Print(), SetNoiseScale(), and LKPad::SetPad().
fPadID
int LKChannel::fPadID = -1 protected
Definition at line 45 of file LKChannel.h.
Referenced by Clear(), Clone(), Copy(), GetDetID(), LKSiChannel::GetName(), GetPadID(), LKSiChannel::GetTitle(), LKSiChannel::IsPair(), Print(), LKSiChannel::Print(), SetDetID(), LKPad::SetPad(), and SetPadID().
fPedestal
double LKChannel::fPedestal = -1 protected
Definition at line 48 of file LKChannel.h.
Referenced by Clear(), Clone(), Copy(), LKPad::CopyPadData(), GETChannel::GetHitGraph(), GETChannel::GetIntegral(), LKSiChannel::GetIntegral(), GetPedestal(), Print(), LKPad::SetPad(), and SetPedestal().
fTime
double LKChannel::fTime = -1 protected
Definition at line 46 of file LKChannel.h.
Referenced by Clear(), Clone(), Copy(), LKPad::CopyPadData(), GETChannel::GetHitGraph(), GetTime(), Print(), LKPad::SetPad(), and SetTime().
The documentation for this class was generated from the following files:
LKChannel.h
LKChannel.cpp