LILAK: LHTpc Class Reference
LHTpc Class Reference
#include <LHTpc.h>
Public Member Functions
virtual LKPadPlane * GetDriftPlane (TVector3 pos)
virtual TVector3 GetEField (TVector3 pos)
LKVector3::Axis GetEFieldAxis ()
virtual bool Init ()
LHTpc ()
virtual ~LHTpc ()
Public Member Functions inherited from LKDetector
void AddPlane (LKDetectorPlane *plane, Int_t planeID=0)
TGeoVolume * CreateGeoTop (TString name="TOP")
void FinishGeometry ()
LKDetectorPlane * GetDetectorPlane (Int_t idx=0)
TGeoManager * GetGeoManager ()
Int_t GetNumPlanes ()
LKDetectorSystem * GetParent ()
LKPulseGenerator * GetPulseGenerator ()
virtual bool Init ()=0
virtual bool IsInBoundary (Double_t x, Double_t y, Double_t z)
LKDetector ()
LKDetector (const char *name, const char *title)
virtual void Print (Option_t *option="") const
void SetGeoManager (TGeoManager *)
void SetParent (LKDetectorSystem *system)
void SetRun (LKRun *run)
void SetTransparency (Int_t transparency)
virtual ~LKDetector ()
Public Member Functions inherited from LKGear
void AddPar (LKParameterContainer *par)
void AddPar (TString fname)
virtual void AddParameterContainer (LKParameterContainer *par)
virtual void AddParameterContainer (TString fname)
void CreateParameterContainer ()
LKParameterContainer * GetPar () const
LKParameterContainer * GetParameterContainer () const
Int_t GetRank () const
LKGear ()
void SetPar (LKParameterContainer *par)
virtual void SetParameterContainer (LKParameterContainer *par)
virtual void SetRank (Int_t rank)
void SetRun (LKRun *run)
virtual ~LKGear ()
Protected Member Functions
virtual bool BuildDetectorPlane ()
virtual bool BuildGeometry ()
virtual bool BuildDetectorPlane ()=0
virtual bool BuildGeometry ()=0
Protected Attributes
LKVector3::Axis fEFieldAxis = LKVector3::kY
Protected Attributes inherited from LKDetector
TObjArray * fDetectorPlaneArray
TGeoManager * fGeoManager = nullptr
Int_t fNumPlanes = 0
LKDetectorSystem * fParent = nullptr
LKPulseGenerator * fPulseGenerator = nullptr
Protected Attributes inherited from LKGear
LKParameterContainer * fPar = nullptr
Int_t fRank = 0
LKRun * fRun = nullptr
Detailed Description
Definition at line 7 of file LHTpc.h.
Constructor & Destructor Documentation
LHTpc()
LHTpc::LHTpc ()
~LHTpc()
virtual LHTpc::~LHTpc () inline virtual
Definition at line 11 of file LHTpc.h.
Member Function Documentation
BuildDetectorPlane()
bool LHTpc::BuildDetectorPlane () protected virtual
Implements LKDetector.
Definition at line 77 of file LHTpc.cpp.
References LKGear::AddParameterContainer(), LKDetector::AddPlane(), LKParameterContainer::CheckPar(), LKGear::fPar, LKParameterContainer::GetParString(), Init(), LKVector3::kX, and LKVector3::kY.
Referenced by Init().
BuildGeometry()
bool LHTpc::BuildGeometry () protected virtual
Implements LKDetector.
Definition at line 43 of file LHTpc.cpp.
References LKDetector::CreateGeoTop(), LKDetector::fGeoManager, LKDetector::FinishGeometry(), LKGear::fPar, and LKDetector::SetTransparency().
Referenced by Init().
GetDriftPlane()
LKPadPlane * LHTpc::GetDriftPlane (TVector3 pos) virtual
Definition at line 38 of file LHTpc.cpp.
References LKDetector::fDetectorPlaneArray.
GetEField()
TVector3 LHTpc::GetEField (TVector3 pos) virtual
Definition at line 31 of file LHTpc.cpp.
References LKVector3::AddAt(), and fEFieldAxis.
GetEFieldAxis()
LKVector3::Axis LHTpc::GetEFieldAxis ()
Definition at line 26 of file LHTpc.cpp.
References fEFieldAxis.
Init()
bool LHTpc::Init () virtual
Implements LKDetector.
Definition at line 13 of file LHTpc.cpp.
References BuildDetectorPlane(), and BuildGeometry().
Referenced by BuildDetectorPlane().
Member Data Documentation
fEFieldAxis
LKVector3::Axis LHTpc::fEFieldAxis = LKVector3::kY protected
Definition at line 24 of file LHTpc.h.
Referenced by GetEField(), and GetEFieldAxis().
The documentation for this class was generated from the following files:
LHTpc.h
LHTpc.cpp