lilak: LKDetectorPlane Class Reference
LKDetectorPlane Class Reference
#include <LKDetectorPlane.h>
Public Member Functions
void AddChannel (LKChannel *channel)
Add channel to channel array in detector plane. For interanl use.
void AddHit (LKHit *hit)
void AddPad (LKPad *pad)
Add pad to pad array in detector plane. For interanl use.
virtual void Clear (Option_t *option="")
virtual void Draw (Option_t *option="")
Implementation recommanded for event display. Draw event display to the canvas.
virtual void DrawFrame (Option_t *option="")
virtual void DrawHist (Option_t *option="")
virtual void DriftElectron (TVector3 posGlobal, TVector3 &posFinal, double &driftLength)
virtual double DriftElectronBack (double tb)
virtual void DriftElectronBack (int padID, double tb, TVector3 &posReco, double &driftLength)
virtual void DriftElectronBack (LKPad *pad, double tb, TVector3 &posReco, double &driftLength)
virtual void FillDataToHist ()
Implementation recommanded. Fill data to histograms.
void FillPlane (double i, double j, double tb, double charge, int trackID=-1)
Find pad corresponding to the position (i,j) and fill time-bin by amount of charge.
virtual int FindChannelID (double i, double j)
Implementation recommanded. Find channel using position.
virtual int FindChannelID (int section, int layer, int row)
Implementation recommanded. Find channel using section, layer, row info.
virtual int FindPadID (double i, double j)
virtual int FindPadID (int cobo, int asad, int aget, int chan)
virtual int FindPadID (int section, int layer, int row)
virtual TPad * Get3DEventPad ()
If user wants to place 3D event display other than default canvas, this method should return corresponding TPad.
virtual axis_t GetAxis1 (int iPad=0) const
virtual axis_t GetAxis2 (int iPad=0) const
virtual axis_t GetAxis3 () const
virtual axis_t GetAxisDrift () const
virtual TCanvas * GetCanvas (Option_t *option="")
Implementation recommanded for event display.
LKChannel * GetChannel (int idx)
virtual LKChannelAnalyzer * GetChannelAnalyzer (int id=0)
TObjArray * GetChannelArray ()
LKChannel * GetChannelFast (int idx)
virtual TPad * GetCPad (int iPad)
For grabbing inner pads of canvas.
virtual TH2 * GetHist (Option_t *option="-1")
int GetNChannels ()
virtual int GetNumCPads ()
Get number of inner pads of canvas.
int GetNumPads ()
LKPad * GetPad (double i, double j)
LKPad * GetPad (int cobo, int asad, int aget, int chan)
LKPad * GetPad (int padID)
LKPad * GetPad (int section, int layer, int row)
TObjArray * GetPadArray ()
LKPad * GetPadFast (int idx)
int GetPlaneID () const
double GetPosition () const
virtual TVector3 GetPositionError (int padID)
double GetTbToLength () const
virtual TVector3 GlobalToLocalAxis (TVector3 posGlobal)
Implementation recommanded. Convert global position to local detector plane position.
void GrabNeighborPads (vector< LKPad * > *pads, vector< LKPad * > *neighborPads)
For tracking use.
virtual bool Init ()
virtual bool IsInBoundary (double i, double j)
Implementation recommanded. Return if position (i,j) is inside the effective detector plane boundary.
LKDetectorPlane ()
LKDetectorPlane (const char *name, const char *title)
virtual TVector3 LocalToGlobalAxis (TVector3 posLocal)
virtual double PadDisplacement () const
Return average pad displacement to each other.
bool PadMapChecker ()
bool PadNeighborChecker ()
bool PadPositionChecker (bool checkCorners=true)
virtual void Print (Option_t *option="") const
void PullOutNeighborHits (double x, double y, int range, LKHitArray *neighborHits)
For tracking use.
void PullOutNeighborHits (double x, double y, int range, vector< LKHit * > *neighborHits)
For tracking use.
void PullOutNeighborHits (LKHitArray *hits, LKHitArray *neighborHits)
For tracking use.
void PullOutNeighborHits (TVector2 p, int range, vector< LKHit * > *neighborHits)
For tracking use.
void PullOutNeighborHits (vector< LKHit * > *hits, vector< LKHit * > *neighborHits)
For tracking use.
virtual LKHit * PullOutNextFreeHit ()
For tracking use.
virtual void ResetEvent ()
For tracking use.
virtual void ResetHitMap ()
For tracking use.
virtual bool SetDataFromBranch ()
Implementation recommanded. Set waveform and hit data from input tree branches to pads.
void SetDetector (LKDetector *detector)
void SetDetectorName (TString name)
void SetHitArray (TClonesArray *hitArray)
void SetPadArray (TClonesArray *padArray)
void SetPlaneID (int id)
virtual ~LKDetectorPlane ()
Public Member Functions inherited from LKGear
void AddPar (LKParameterContainer *par)
void AddPar (TString fname)
virtual void AddParameterContainer (LKParameterContainer *par)
virtual void AddParameterContainer (TString fname)
void CreateParameterContainer ()
LKParameterContainer * GetPar () const
LKParameterContainer * GetParameterContainer () const
Int_t GetRank () const
LKGear ()
void SetPar (LKParameterContainer *par)
virtual void SetParameterContainer (LKParameterContainer *par)
virtual void SetRank (Int_t rank)
void SetRun (LKRun *run)
virtual ~LKGear ()
Protected Attributes
axis_t fAxis1 = LKVector3::kNon
Axis-1 lying in plane. Must be set by input parameter.
axis_t fAxis2 = LKVector3::kNon
Axis-2 lying in plane. Must be set by input parameter.
axis_t fAxis3 = LKVector3::kNon
Axis-3 = Axis-1 x Axis-2 perpendicular to plane.
axis_t fAxisDrift = LKVector3::kNon
Axis perpendicular to plane, in electron drifting direction. Must be set by input parameter.
TCanvas * fCanvas = nullptr
LKChannelAnalyzer * fChannelAnalyzer = nullptr
TObjArray * fChannelArray = nullptr
TCanvas * fCvsChannelBuffer = nullptr
LKDetector * fDetector = nullptr
TString fDetName
int fFreePadIdx = 0
TGraph * fGraphChannelBoundary = nullptr
TGraph * fGraphChannelBoundaryNb [20] = {0}
TH2 * fH2Plane = nullptr
bool fHitDataIsSet = false
bool fPadDataIsSet = false
int fPlaneID = -1
Detector plane id.
double fPosition
Global position of pad plane center.
double fTbToLength = 1
time-bin (tb) to position conversion factor. Must be set by input parameter.
Protected Attributes inherited from LKGear
LKParameterContainer * fPar = nullptr
Int_t fRank = 0
LKRun * fRun = nullptr
Detailed Description
Definition at line 25 of file LKDetectorPlane.h.
Constructor & Destructor Documentation
LKDetectorPlane() [1/2]
LKDetectorPlane::LKDetectorPlane ()
LKDetectorPlane() [2/2]
LKDetectorPlane::LKDetectorPlane (const char * name, const char * title)
Definition at line 14 of file LKDetectorPlane.cpp.
~LKDetectorPlane()
virtual LKDetectorPlane::~LKDetectorPlane () inline virtual
Definition at line 54 of file LKDetectorPlane.h.
Member Function Documentation
AddChannel()
void LKDetectorPlane::AddChannel (LKChannel * channel) inline
Add channel to channel array in detector plane. For interanl use.
Definition at line 116 of file LKDetectorPlane.h.
References fChannelArray.
Referenced by SKSiArrayPlane::FillDataToHistEventDisplay1().
AddHit()
void LKDetectorPlane::AddHit (LKHit * hit)
Definition at line 118 of file LKDetectorPlane.cpp.
References AddHit(), and GetPadFast().
Referenced by AddHit(), and SetHitArray().
AddPad()
void LKDetectorPlane::AddPad (LKPad * pad) inline
Add pad to pad array in detector plane. For interanl use.
Definition at line 117 of file LKDetectorPlane.h.
References fChannelArray.
Clear()
void LKDetectorPlane::Clear (Option_t * option = "") virtual
Reimplemented in LTPadPlane, LKEvePlane, LKPadPlane, LKEvePlane, TTMicromegas, and TTFrontPlane.
Definition at line 19 of file LKDetectorPlane.cpp.
References Clear(), and fChannelArray.
Referenced by Clear(), LKEvePlane::Clear(), TTMicromegas::Clear(), Draw(), DrawHist(), and SetDataFromBranch().
Draw()
void LKDetectorPlane::Draw (Option_t * option = "") virtual
Implementation recommanded for event display. Draw event display to the canvas.
Reimplemented in LKEvePlane, LKEvePlane, TTMicromegas, TTFrontPlane, ATTPC20RectanglePad, ATTPCHoneyCombPad, ATTPCRectanglePad, and ATTPCStripPad.
Definition at line 660 of file LKDetectorPlane.cpp.
References Clear(), cvs, Draw(), DrawFrame(), FillDataToHist(), GetCanvas(), GetHist(), and SetDataFromBranch().
Referenced by Draw(), LHPadPlaneFan::DrawFrame(), LHPadPlaneRCut::DrawFrame(), LKPadPlane::DrawHist(), and DrawHist().
DrawFrame()
virtual void LKDetectorPlane::DrawFrame (Option_t * option = "") inline virtual
Reimplemented in LKEvePlane, LKEvePlane, TTMicromegas, LHPadPlaneFan, LHPadPlaneRCut, LHPadPlaneYCut, ATTPC20RectanglePad, ATTPCHoneyCombPad, ATTPCRectanglePad, ATTPCStripPad, and TTFrontPlane.
Definition at line 80 of file LKDetectorPlane.h.
Referenced by Draw(), LKPadPlane::DrawHist(), and DrawHist().
DrawHist()
void LKDetectorPlane::DrawHist (Option_t * option = "") virtual
Reimplemented in LKEvePlane, and LKEvePlane.
Definition at line 635 of file LKDetectorPlane.cpp.
References Clear(), Draw(), DrawFrame(), fCanvas, FillDataToHist(), GetCanvas(), and GetHist().
DriftElectron()
void LKDetectorPlane::DriftElectron (TVector3 posGlobal, TVector3 & posFinal, double & driftLength) virtual
Implementation recommanded. Return position (x,y,z). x,y is pad position in pad plane. z is pad plane position of electron-drift-axis (for simulation)
Parameters
posGlobal[in] Given global position of the electron.
posFinal[in] Final position of electron after full drift (at the pad plane).
driftLength[out] Final drift length of the electron
Definition at line 679 of file LKDetectorPlane.cpp.
References LKVector3::At(), fAxis1, fAxis2, fAxis3, and fPosition.
DriftElectronBack() [1/3]
double LKDetectorPlane::DriftElectronBack (double tb) virtual
Implementation recommanded. return drift length
Definition at line 708 of file LKDetectorPlane.cpp.
References fPosition, and fTbToLength.
DriftElectronBack() [2/3]
void LKDetectorPlane::DriftElectronBack (int padID, double tb, TVector3 & posReco, double & driftLength) virtual
Reimplemented in LKEvePlane, and LKEvePlane.
Definition at line 702 of file LKDetectorPlane.cpp.
References DriftElectronBack(), and GetPad().
DriftElectronBack() [3/3]
void LKDetectorPlane::DriftElectronBack (LKPad * pad, double tb, TVector3 & posReco, double & driftLength) virtual
Implementation recommanded. Set poseReco to global position using pad position, and time-bin tb. Pad position must be set from Init(). Conversion from time-bin (tb) to position in time-axis (post) is calculated by : post = fTbToLength * tb + fPosition [fTbToLength] is tb to position conversion factor with direction and [fPosition] is detector plane position in time-axis.
Parameters
pad[in] channel (pad)
tb[in] Time-bin
posReco[out] Reconstructed position of electron(?) before drift.
driftLength[out] Drift length of the electron from the reconstructed position.
Definition at line 689 of file LKDetectorPlane.cpp.
References fAxis3, fAxisDrift, fPosition, fTbToLength, LKPad::GetI(), LKPad::GetJ(), LKVector3::GetXYZ(), LKVector3::SetI(), LKVector3::SetJ(), and LKVector3::SetK().
Referenced by DriftElectronBack().
FillDataToHist()
void LKDetectorPlane::FillDataToHist () virtual
Implementation recommanded. Fill data to histograms.
Reimplemented in LKPadPlane, TTMicromegas, and TTFrontPlane.
Definition at line 136 of file LKDetectorPlane.cpp.
References fChannelArray, fH2Plane, fHitDataIsSet, fPadDataIsSet, LKGear::fPar, GetHist(), LKPad::GetI(), LKPad::GetJ(), LKPad::GetLayer(), GETChannel::GetNumHits(), LKChannel::GetPadID(), LKPad::GetRow(), LKPad::GetSection(), lk_error, and lk_info.
Referenced by LKEvePlane::ClickedControlEvent1(), Draw(), LKEvePlane::Draw(), DrawHist(), LKEvePlane::DrawHist(), and LKEvePlane::UpdateFill().
FillPlane()
void LKDetectorPlane::FillPlane (double i, double j, double tb, double charge, int trackID = -1)
Find pad corresponding to the position (i,j) and fill time-bin by amount of charge.
Definition at line 125 of file LKDetectorPlane.cpp.
References fChannelArray, and FindPadID().
FindChannelID() [1/2]
virtual int LKDetectorPlane::FindChannelID (double i, double j) inline virtual
Implementation recommanded. Find channel using position.
Reimplemented in LKEvePlane, and LKEvePlane.
Definition at line 124 of file LKDetectorPlane.h.
Referenced by FindPadID(), and FindPadID().
FindChannelID() [2/2]
virtual int LKDetectorPlane::FindChannelID (int section, int layer, int row) inline virtual
Implementation recommanded. Find channel using section, layer, row info.
Reimplemented in LKEvePlane, and LKEvePlane.
Definition at line 125 of file LKDetectorPlane.h.
FindPadID() [1/3]
virtual int LKDetectorPlane::FindPadID (double i, double j) inline virtual
Reimplemented in LTPadPlane.
Definition at line 126 of file LKDetectorPlane.h.
References FindChannelID().
Referenced by FillPlane(), GetPad(), GetPad(), GetPad(), PadMapChecker(), PadPositionChecker(), PullOutNeighborHits(), and PullOutNeighborHits().
FindPadID() [2/3]
virtual int LKDetectorPlane::FindPadID (int cobo, int asad, int aget, int chan) inline virtual
Reimplemented in LTPadPlane, LKEvePlane, LKMicromegas, SKSiArrayPlane, and LKEvePlane.
Definition at line 128 of file LKDetectorPlane.h.
FindPadID() [3/3]
virtual int LKDetectorPlane::FindPadID (int section, int layer, int row) inline virtual
Reimplemented in LTPadPlane.
Definition at line 127 of file LKDetectorPlane.h.
References FindChannelID().
Get3DEventPad()
virtual TPad * LKDetectorPlane::Get3DEventPad () inline virtual
If user wants to place 3D event display other than default canvas, this method should return corresponding TPad.
Reimplemented in LKEvePlane, LKMicromegas, SKSiArrayPlane, and LKEvePlane.
Definition at line 84 of file LKDetectorPlane.h.
GetAxis1()
virtual axis_t LKDetectorPlane::GetAxis1 (int iPad = 0) const inline virtual
Reimplemented in LKEvePlane, and LKEvePlane.
Definition at line 62 of file LKDetectorPlane.h.
References fAxis1.
Referenced by LKTracklet::TrajectoryOnPlane().
GetAxis2()
virtual axis_t LKDetectorPlane::GetAxis2 (int iPad = 0) const inline virtual
Reimplemented in LKEvePlane, and LKEvePlane.
Definition at line 63 of file LKDetectorPlane.h.
References fAxis2.
Referenced by LKTracklet::TrajectoryOnPlane().
GetAxis3()
virtual axis_t LKDetectorPlane::GetAxis3 () const inline virtual
Definition at line 64 of file LKDetectorPlane.h.
References fAxis3.
GetAxisDrift()
virtual axis_t LKDetectorPlane::GetAxisDrift () const inline virtual
Definition at line 65 of file LKDetectorPlane.h.
References fAxisDrift.
GetCanvas()
TCanvas * LKDetectorPlane::GetCanvas (Option_t * option = "") virtual
Implementation recommanded for event display.
Reimplemented in LKEvePlane, SKSiArrayPlane, LKEvePlane, TTMicromegas, ATTPC20RectanglePad, ATTPCHoneyCombPad, ATTPCRectanglePad, ATTPCStripPad, TTFrontPlane, LHPadPlaneFan, LHPadPlaneRCut, and LHPadPlaneYCut.
Definition at line 653 of file LKDetectorPlane.cpp.
References fCanvas, fPlaneID, and LKPainter::GetPainter().
Referenced by Draw(), DrawHist(), and GetCPad().
GetChannel()
LKChannel * LKDetectorPlane::GetChannel (int idx)
Definition at line 47 of file LKDetectorPlane.cpp.
References fChannelArray.
GetChannelAnalyzer()
LKChannelAnalyzer * LKDetectorPlane::GetChannelAnalyzer (int id = 0) virtual
Reimplemented in LTPadPlane, LKEvePlane, and LKEvePlane.
Definition at line 714 of file LKDetectorPlane.cpp.
References LKParameterContainer::CheckPar(), fChannelAnalyzer, LKGear::fPar, and Print().
Referenced by TTMicromegas::SelectAndDrawChannel(), and TTFrontPlane::SelectAndDrawChannel().
GetChannelArray()
TObjArray * LKDetectorPlane::GetChannelArray () inline
Definition at line 121 of file LKDetectorPlane.h.
References fChannelArray.
GetChannelFast()
LKChannel * LKDetectorPlane::GetChannelFast (int idx) inline
Definition at line 129 of file LKDetectorPlane.h.
References fChannelArray.
GetCPad()
virtual TPad * LKDetectorPlane::GetCPad (int iPad) inline virtual
For grabbing inner pads of canvas.
Reimplemented in LKEvePlane, LKEvePlane, and TTMicromegas.
Definition at line 83 of file LKDetectorPlane.h.
References GetCanvas().
GetHist()
virtual TH2 * LKDetectorPlane::GetHist (Option_t * option = "-1") inline virtual
Reimplemented in SKSiArrayPlane, TTMicromegas, ATTPC20RectanglePad, ATTPCHoneyCombPad, ATTPCRectanglePad, ATTPCStripPad, TTFrontPlane, LKEvePlane, LKEvePlane, LHPadPlaneFan, LHPadPlaneRCut, and LHPadPlaneYCut.
Definition at line 79 of file LKDetectorPlane.h.
Referenced by Draw(), LKPadPlane::DrawHist(), DrawHist(), FillDataToHist(), and LKPadPlane::FillDataToHist().
GetNChannels()
int LKDetectorPlane::GetNChannels () inline
Definition at line 119 of file LKDetectorPlane.h.
References fChannelArray.
Referenced by GetNumPads(), and LKPadPlane::GetNumPads().
GetNumCPads()
virtual int LKDetectorPlane::GetNumCPads () inline virtual
Get number of inner pads of canvas.
Reimplemented in LKEvePlane, LKEvePlane, and TTMicromegas.
Definition at line 82 of file LKDetectorPlane.h.
GetNumPads()
int LKDetectorPlane::GetNumPads () inline
Definition at line 120 of file LKDetectorPlane.h.
References GetNChannels().
GetPad() [1/4]
LKPad * LKDetectorPlane::GetPad (double i, double j)
Definition at line 61 of file LKDetectorPlane.cpp.
References FindPadID(), and GetPad().
GetPad() [2/4]
LKPad * LKDetectorPlane::GetPad (int cobo, int asad, int aget, int chan)
Definition at line 77 of file LKDetectorPlane.cpp.
References FindPadID(), and GetPad().
GetPad() [3/4]
LKPad * LKDetectorPlane::GetPad (int padID)
Definition at line 54 of file LKDetectorPlane.cpp.
References fChannelArray.
Referenced by DriftElectronBack(), GetPad(), GetPad(), GetPad(), and LTPadPlane::Init().
GetPad() [4/4]
LKPad * LKDetectorPlane::GetPad (int section, int layer, int row)
Definition at line 69 of file LKDetectorPlane.cpp.
References FindPadID(), and GetPad().
GetPadArray()
TObjArray * LKDetectorPlane::GetPadArray ()
Definition at line 430 of file LKDetectorPlane.cpp.
References fChannelArray.
GetPadFast()
LKPad * LKDetectorPlane::GetPadFast (int idx) inline
Definition at line 130 of file LKDetectorPlane.h.
References fChannelArray.
Referenced by AddHit(), SetHitArray(), and SetPadArray().
GetPlaneID()
int LKDetectorPlane::GetPlaneID () const inline
Definition at line 59 of file LKDetectorPlane.h.
References fPlaneID.
Referenced by SetPadArray(), and LKPadPlane::SetPadArray().
GetPosition()
double LKDetectorPlane::GetPosition () const inline
Definition at line 67 of file LKDetectorPlane.h.
References fPosition.
Referenced by TTMicromegas::FillDataToHist(), TTFrontPlane::FillDataToHist(), LKEvePlane::FillDataToHistEventDisplay1(), LKMicromegas::FillDataToHistEventDisplay2(), ATTPCStripPad::Init(), PadNeighborChecker(), LKPadPlane::PadNeighborChecker(), PadPositionChecker(), and LKPadPlane::PadPositionChecker().
GetPositionError()
virtual TVector3 LKDetectorPlane::GetPositionError (int padID) inline virtual
Reimplemented in LKMicromegas.
Definition at line 112 of file LKDetectorPlane.h.
GetTbToLength()
double LKDetectorPlane::GetTbToLength () const inline
Definition at line 66 of file LKDetectorPlane.h.
References fTbToLength.
GlobalToLocalAxis()
virtual TVector3 LKDetectorPlane::GlobalToLocalAxis (TVector3 posGlobal) inline virtual
Implementation recommanded. Convert global position to local detector plane position.
Reimplemented in LKEvePlane, and LKEvePlane.
Definition at line 88 of file LKDetectorPlane.h.
Referenced by LKPadPlane::DriftElectron().
GrabNeighborPads()
void LKDetectorPlane::GrabNeighborPads (vector< LKPad * > * pads, vector< LKPad * > * neighborPads)
For tracking use.
Definition at line 417 of file LKDetectorPlane.cpp.
Referenced by PullOutNeighborHits(), PullOutNeighborHits(), and LHPadPlaneFan::PullOutNeighborHitsIn().
Init()
virtual bool LKDetectorPlane::Init () inline virtual
Implementation recommanded. Init() method should implement pad information (id, position, neighbor) and add channel using AddChannel() or AddPad() method. All parameters should be configured such as axis-1,2,3, fPosition, fTbToLength from parameter container.
Reimplemented in LTPadPlane, LKEvePlane, LKMicromegas, SKSiArrayPlane, LKEvePlane, TTMicromegas, LHPadPlaneFan, LHPadPlaneRCut, LHPadPlaneYCut, ATTPC20RectanglePad, ATTPCHoneyCombPad, ATTPCRectanglePad, ATTPCStripPad, and TTFrontPlane.
Definition at line 75 of file LKDetectorPlane.h.
IsInBoundary()
virtual bool LKDetectorPlane::IsInBoundary (double i, double j) inline virtual
Implementation recommanded. Return if position (i,j) is inside the effective detector plane boundary.
Reimplemented in LTPadPlane, LKEvePlane, and LKEvePlane.
Definition at line 87 of file LKDetectorPlane.h.
LocalToGlobalAxis()
virtual TVector3 LKDetectorPlane::LocalToGlobalAxis (TVector3 posLocal) inline virtual
Implementation recommanded. Convert local position to global detector plane position
Reimplemented in LKEvePlane, and LKEvePlane.
Definition at line 89 of file LKDetectorPlane.h.
PadDisplacement()
virtual double LKDetectorPlane::PadDisplacement () const inline virtual
Return average pad displacement to each other.
Reimplemented in LTPadPlane, LKEvePlane, LKPadPlane, LKEvePlane, LHPadPlaneFan, LHPadPlaneRCut, LHPadPlaneYCut, ATTPC20RectanglePad, ATTPCHoneyCombPad, ATTPCRectanglePad, and ATTPCStripPad.
Definition at line 86 of file LKDetectorPlane.h.
PadMapChecker()
bool LKDetectorPlane::PadMapChecker ()
Self debugging tool. Result will be printed out. For each pad, check 1) section, layer, row map 2) cobo, aget, asad, chan map
Definition at line 432 of file LKDetectorPlane.cpp.
References fChannelArray, FindPadID(), lk_info, and lk_warning.
PadNeighborChecker()
bool LKDetectorPlane::PadNeighborChecker ()
Self debugging tool. Result will be printed out. For each pad, check number of registered neighbor pads.
Definition at line 539 of file LKDetectorPlane.cpp.
References fChannelArray, LKPad::GetI(), LKPad::GetJ(), LKChannel::GetPadID(), GetPosition(), and lk_info.
PadPositionChecker()
bool LKDetectorPlane::PadPositionChecker (bool checkCorners = true)
Self debugging tool. Result will be printed out. For each pad, check if pad found from FindPadID() using pad position of itself matches.
Definition at line 487 of file LKDetectorPlane.cpp.
References fChannelArray, FindPadID(), LKPad::GetPadCorners(), GetPosition(), lk_info, and lk_warning.
Print()
void LKDetectorPlane::Print (Option_t * option = "") const virtual
Reimplemented in LTPadPlane, LKEvePlane, LKPadPlane, SKSiArrayPlane, LKEvePlane, TTMicromegas, and TTFrontPlane.
Definition at line 28 of file LKDetectorPlane.cpp.
References fChannelArray, iChannel, and lk_info.
Referenced by GetChannelAnalyzer().
PullOutNeighborHits() [1/5]
void LKDetectorPlane::PullOutNeighborHits (double x, double y, int range, LKHitArray * neighborHits)
For tracking use.
Definition at line 328 of file LKDetectorPlane.cpp.
References fChannelArray, FindPadID(), and GrabNeighborPads().
PullOutNeighborHits() [2/5]
void LKDetectorPlane::PullOutNeighborHits (double x, double y, int range, vector< LKHit * > * neighborHits)
For tracking use.
Definition at line 380 of file LKDetectorPlane.cpp.
References fChannelArray, FindPadID(), and GrabNeighborPads().
PullOutNeighborHits() [3/5]
void LKDetectorPlane::PullOutNeighborHits (LKHitArray * hits, LKHitArray * neighborHits)
For tracking use.
Definition at line 315 of file LKDetectorPlane.cpp.
References fChannelArray.
PullOutNeighborHits() [4/5]
void LKDetectorPlane::PullOutNeighborHits (TVector2 p, int range, vector< LKHit * > * neighborHits)
For tracking use.
Definition at line 375 of file LKDetectorPlane.cpp.
References PullOutNeighborHits().
PullOutNeighborHits() [5/5]
void LKDetectorPlane::PullOutNeighborHits (vector< LKHit * > * hits, vector< LKHit * > * neighborHits)
For tracking use.
Definition at line 365 of file LKDetectorPlane.cpp.
References fChannelArray.
Referenced by PullOutNeighborHits().
PullOutNextFreeHit()
LKHit * LKDetectorPlane::PullOutNextFreeHit () virtual
For tracking use.
Reimplemented in LKPadPlane.
Definition at line 300 of file LKDetectorPlane.cpp.
References fChannelArray, fFreePadIdx, and PullOutNextFreeHit().
Referenced by PullOutNextFreeHit(), and LHPadPlaneFan::PullOutNextFreeHitIn().
ResetEvent()
void LKDetectorPlane::ResetEvent () virtual
For tracking use.
Reimplemented in LKPadPlane.
Definition at line 277 of file LKDetectorPlane.cpp.
References fChannelArray, and fFreePadIdx.
ResetHitMap()
void LKDetectorPlane::ResetHitMap () virtual
For tracking use.
Reimplemented in LKPadPlane, and LHPadPlaneFan.
Definition at line 288 of file LKDetectorPlane.cpp.
References fChannelArray, and fFreePadIdx.
Referenced by LHPadPlaneFan::ResetHitMap().
SetDataFromBranch()
bool LKDetectorPlane::SetDataFromBranch () virtual
Implementation recommanded. Set waveform and hit data from input tree branches to pads.
Reimplemented in LKEvePlane, LKPadPlane, SKSiArrayPlane, LKEvePlane, TTMicromegas, and TTFrontPlane.
Definition at line 233 of file LKDetectorPlane.cpp.
References Clear(), LKGear::fPar, LKGear::fRun, lk_cout, lk_error, lk_info, lk_warning, SetHitArray(), and SetPadArray().
Referenced by Draw().
SetDetector()
void LKDetectorPlane::SetDetector (LKDetector * detector) inline
Definition at line 56 of file LKDetectorPlane.h.
References fDetector.
SetDetectorName()
void LKDetectorPlane::SetDetectorName (TString name) inline
Definition at line 57 of file LKDetectorPlane.h.
References fDetName.
SetHitArray()
void LKDetectorPlane::SetHitArray (TClonesArray * hitArray)
Definition at line 102 of file LKDetectorPlane.cpp.
References AddHit(), fHitDataIsSet, and GetPadFast().
Referenced by SetDataFromBranch().
SetPadArray()
void LKDetectorPlane::SetPadArray (TClonesArray * padArray)
Definition at line 85 of file LKDetectorPlane.cpp.
References fPadDataIsSet, fPlaneID, GetPadFast(), and GetPlaneID().
Referenced by SetDataFromBranch().
SetPlaneID()
void LKDetectorPlane::SetPlaneID (int id) inline
Definition at line 58 of file LKDetectorPlane.h.
References fPlaneID.
Referenced by LKMicromegas::Init(), ATTPC20RectanglePad::Init(), ATTPCHoneyCombPad::Init(), ATTPCRectanglePad::Init(), and ATTPCStripPad::Init().
Member Data Documentation
fAxis1
axis_t LKDetectorPlane::fAxis1 = LKVector3::kNon protected
Axis-1 lying in plane. Must be set by input parameter.
Definition at line 33 of file LKDetectorPlane.h.
Referenced by DriftElectron(), ATTPC20RectanglePad::FindPadID(), ATTPCHoneyCombPad::FindPadID(), ATTPCRectanglePad::FindPadID(), ATTPCStripPad::FindPadID(), GetAxis1(), LKEvePlane::GetAxis1(), ATTPC20RectanglePad::GetHist(), ATTPCHoneyCombPad::GetHist(), ATTPCRectanglePad::GetHist(), ATTPCStripPad::GetHist(), LTPadPlane::Init(), ATTPC20RectanglePad::Init(), ATTPCHoneyCombPad::Init(), ATTPCRectanglePad::Init(), ATTPCStripPad::Init(), LKEvePlane::LKEvePlane(), LKMicromegas::LKMicromegas(), and TTMicromegas::TTMicromegas().
fAxis2
axis_t LKDetectorPlane::fAxis2 = LKVector3::kNon protected
Axis-2 lying in plane. Must be set by input parameter.
Definition at line 34 of file LKDetectorPlane.h.
Referenced by DriftElectron(), ATTPC20RectanglePad::FindPadID(), ATTPCHoneyCombPad::FindPadID(), ATTPCRectanglePad::FindPadID(), ATTPCStripPad::FindPadID(), GetAxis2(), LKEvePlane::GetAxis2(), ATTPC20RectanglePad::GetHist(), ATTPCHoneyCombPad::GetHist(), ATTPCRectanglePad::GetHist(), ATTPCStripPad::GetHist(), LTPadPlane::Init(), ATTPC20RectanglePad::Init(), ATTPCHoneyCombPad::Init(), ATTPCRectanglePad::Init(), ATTPCStripPad::Init(), LKEvePlane::LKEvePlane(), LKMicromegas::LKMicromegas(), and TTMicromegas::TTMicromegas().
fAxis3
axis_t LKDetectorPlane::fAxis3 = LKVector3::kNon protected
Axis-3 = Axis-1 x Axis-2 perpendicular to plane.
Definition at line 35 of file LKDetectorPlane.h.
Referenced by DriftElectron(), LKEvePlane::DriftElectronBack(), DriftElectronBack(), GetAxis3(), LTPadPlane::Init(), LKEvePlane::LKEvePlane(), and LKMicromegas::LKMicromegas().
fAxisDrift
axis_t LKDetectorPlane::fAxisDrift = LKVector3::kNon protected
Axis perpendicular to plane, in electron drifting direction. Must be set by input parameter.
Definition at line 36 of file LKDetectorPlane.h.
Referenced by LKEvePlane::DriftElectronBack(), DriftElectronBack(), LKEvePlane::FillDataToHistEventDisplay1(), LKMicromegas::FillDataToHistEventDisplay2(), GetAxisDrift(), LTPadPlane::Init(), LKEvePlane::LKEvePlane(), and LKMicromegas::LKMicromegas().
fCanvas
TCanvas* LKDetectorPlane::fCanvas = nullptr protected
Definition at line 41 of file LKDetectorPlane.h.
Referenced by LKEvePlane::ClickedControlEvent2(), LKPadPlane::DrawHist(), DrawHist(), GetCanvas(), LKEvePlane::GetCanvas(), SKSiArrayPlane::GetCanvas(), TTMicromegas::GetCanvas(), ATTPC20RectanglePad::GetCanvas(), ATTPCHoneyCombPad::GetCanvas(), ATTPCRectanglePad::GetCanvas(), ATTPCStripPad::GetCanvas(), TTFrontPlane::GetCanvas(), LHPadPlaneFan::GetCanvas(), LHPadPlaneRCut::GetCanvas(), LHPadPlaneYCut::GetCanvas(), TTMicromegas::GetCPad(), TTMicromegas::SelectAndDrawChannel(), TTFrontPlane::SelectAndDrawChannel(), and SKSiArrayPlane::UpdateDataDisplays().
fChannelAnalyzer
LKChannelAnalyzer* LKDetectorPlane::fChannelAnalyzer = nullptr protected
Definition at line 29 of file LKDetectorPlane.h.
Referenced by LKMicromegas::FillDataToHistEventDisplay2(), LTPadPlane::GetChannelAnalyzer(), GetChannelAnalyzer(), LKEvePlane::GetChannelAnalyzer(), LTPadPlane::Init(), LKEvePlane::LKEvePlane(), LKMicromegas::LKMicromegas(), and LKEvePlane::UpdateChannelBuffer().
fChannelArray
TObjArray* LKDetectorPlane::fChannelArray = nullptr protected
Definition at line 40 of file LKDetectorPlane.h.
Referenced by AddChannel(), LHPadPlaneFan::AddPad(), AddPad(), Clear(), LKPadPlane::Clear(), LKEvePlane::ClickedControlEvent2(), LTPadPlane::ClickedEventDisplay1(), LKEvePlane::ClickedEventDisplay1(), LKEvePlane::ClickedEventDisplay2(), LKEvePlane::DriftElectronBack(), LKPadPlane::FillBufferIn(), FillDataToHist(), LKPadPlane::FillDataToHist(), LTPadPlane::FillDataToHist(), LKEvePlane::FillDataToHistEventDisplay1(), LKMicromegas::FillDataToHistEventDisplay2(), FillPlane(), LKEvePlane::FindPad(), LKMicromegas::FindPad(), GetChannel(), GetChannelArray(), GetChannelFast(), ATTPC20RectanglePad::GetHist(), ATTPCHoneyCombPad::GetHist(), ATTPCRectanglePad::GetHist(), ATTPCStripPad::GetHist(), LHPadPlaneFan::GetHist(), LHPadPlaneRCut::GetHist(), LHPadPlaneYCut::GetHist(), LTPadPlane::GetHistEventDisplay2(), GetNChannels(), GetPad(), LKPadPlane::GetPad(), GetPadArray(), LKPadPlane::GetPadArray(), GetPadFast(), LKPadPlane::GetPadFast(), LKMicromegas::GetPositionError(), LTPadPlane::Init(), LKMicromegas::Init(), LHPadPlaneFan::Init(), LHPadPlaneRCut::Init(), LHPadPlaneYCut::Init(), ATTPC20RectanglePad::Init(), ATTPCHoneyCombPad::Init(), ATTPCRectanglePad::Init(), ATTPCStripPad::Init(), LHPadPlaneRCut::NewPad(), LHPadPlaneYCut::NewPad(), PadMapChecker(), PadNeighborChecker(), LKPadPlane::PadNeighborChecker(), PadPositionChecker(), LKPadPlane::PadPositionChecker(), Print(), LKPadPlane::Print(), PullOutNeighborHits(), PullOutNeighborHits(), LKPadPlane::PullOutNeighborHits(), LKPadPlane::PullOutNeighborHits(), PullOutNeighborHits(), LKPadPlane::PullOutNeighborHits(), PullOutNeighborHits(), LKPadPlane::PullOutNeighborHits(), LHPadPlaneFan::PullOutNeighborHitsIn(), PullOutNextFreeHit(), LKPadPlane::PullOutNextFreeHit(), LHPadPlaneFan::PullOutNextFreeHitIn(), ResetEvent(), LKPadPlane::ResetEvent(), ResetHitMap(), LKPadPlane::ResetHitMap(), LKEvePlane::SetDataFromBranch(), LKEvePlane::UpdateChannelBuffer(), and LKMicromegas::UpdateChannelBuffer().
fCvsChannelBuffer
TCanvas* LKDetectorPlane::fCvsChannelBuffer = nullptr protected
Definition at line 43 of file LKDetectorPlane.h.
fDetector
LKDetector* LKDetectorPlane::fDetector = nullptr protected
Definition at line 28 of file LKDetectorPlane.h.
Referenced by TTMicromegas::SelectAndDrawChannel(), TTFrontPlane::SelectAndDrawChannel(), and SetDetector().
fDetName
TString LKDetectorPlane::fDetName protected
Definition at line 30 of file LKDetectorPlane.h.
Referenced by ATMicromegas::ATMicromegas(), LKMicromegas::Init(), SKSiArrayPlane::Init(), SetDetectorName(), and TBMicromegas::TBMicromegas().
fFreePadIdx
int LKDetectorPlane::fFreePadIdx = 0 protected
Definition at line 46 of file LKDetectorPlane.h.
Referenced by PullOutNextFreeHit(), ResetEvent(), and ResetHitMap().
fGraphChannelBoundary
TGraph* LKDetectorPlane::fGraphChannelBoundary = nullptr protected
Definition at line 44 of file LKDetectorPlane.h.
fGraphChannelBoundaryNb
TGraph* LKDetectorPlane::fGraphChannelBoundaryNb[20] = {0} protected
Definition at line 45 of file LKDetectorPlane.h.
fH2Plane
TH2* LKDetectorPlane::fH2Plane = nullptr protected
Definition at line 42 of file LKDetectorPlane.h.
Referenced by FillDataToHist(), LKPadPlane::FillDataToHist(), ATTPC20RectanglePad::GetHist(), ATTPCHoneyCombPad::GetHist(), ATTPCRectanglePad::GetHist(), ATTPCStripPad::GetHist(), LHPadPlaneFan::GetHist(), LHPadPlaneRCut::GetHist(), and LHPadPlaneYCut::GetHist().
fHitDataIsSet
bool LKDetectorPlane::fHitDataIsSet = false protected
Definition at line 49 of file LKDetectorPlane.h.
Referenced by FillDataToHist(), and SetHitArray().
fPadDataIsSet
bool LKDetectorPlane::fPadDataIsSet = false protected
Definition at line 48 of file LKDetectorPlane.h.
Referenced by FillDataToHist(), and SetPadArray().
fPlaneID
int LKDetectorPlane::fPlaneID = -1 protected
Detector plane id.
Definition at line 32 of file LKDetectorPlane.h.
Referenced by GetCanvas(), ATTPC20RectanglePad::GetCanvas(), ATTPCHoneyCombPad::GetCanvas(), ATTPCRectanglePad::GetCanvas(), ATTPCStripPad::GetCanvas(), LHPadPlaneFan::GetCanvas(), LHPadPlaneRCut::GetCanvas(), LHPadPlaneYCut::GetCanvas(), GetPlaneID(), ATTPC20RectanglePad::Init(), ATTPCHoneyCombPad::Init(), ATTPCRectanglePad::Init(), ATTPCStripPad::Init(), SetPadArray(), LKPadPlane::SetPadArray(), and SetPlaneID().
fPosition
double LKDetectorPlane::fPosition protected
Global position of pad plane center.
Definition at line 38 of file LKDetectorPlane.h.
Referenced by DriftElectron(), DriftElectronBack(), LKEvePlane::DriftElectronBack(), DriftElectronBack(), GetPosition(), LTPadPlane::Init(), LKEvePlane::Init(), and LKMicromegas::Init().
fTbToLength
double LKDetectorPlane::fTbToLength = 1 protected
time-bin (tb) to position conversion factor. Must be set by input parameter.
Definition at line 37 of file LKDetectorPlane.h.
Referenced by DriftElectronBack(), LKEvePlane::DriftElectronBack(), DriftElectronBack(), LKMicromegas::GetPositionError(), GetTbToLength(), LTPadPlane::Init(), LKEvePlane::Init(), and LKMicromegas::Init().
The documentation for this class was generated from the following files:
LKDetectorPlane.h
LKDetectorPlane.cpp