LILAK: LKRun Class Reference
LKRun Class Reference
#include <LKRun.h>
Public Member Functions
void Add (LKTask *task)
Add task to be executed every event.
virtual void Add (TTask *task)
void AddDetector (LKDetector *detector)
Set detector.
void AddFriend (TString fileName)
Add file to input file.
void AddInputFile (TString fileName, TString treeName="event")
Add file to input file.
void AddInputList (TString fileName, TString treeName="event")
Input file.
void AddPar (LKParameterContainer *par)
void AddPar (TString fname)
void AddParAfter (TString fname)
virtual void AddParameterContainer (LKParameterContainer *par)
virtual void AddParameterContainer (TString fname)
void AlwaysPrintMessage ()
bool CheckMute ()
void ClearArrays ()
TString ConfigureFileName ()
bool ConfigureRunFromFileName (TString inputName)
void CreateParameterContainer ()
void DoNotFillCurrentEvent ()
bool EndOfRun ()
bool EndOfRunTask ()
bool EndOfRunTasks ()
bool ExecuteEvent (Long64_t eventID=-1)
Run just one event of eventID.
bool ExecuteFirstEvent ()
bool ExecuteLastEvent ()
bool ExecuteNextEvent ()
bool ExecutePreviousEvent ()
LKDetector * FindDetector (const char *name)
LKDetectorPlane * FindDetectorPlane (const char *name)
TClonesArray * GetBranchA (Int_t idx)
TClonesArray * GetBranchA (TString name)
Get branch in TClonesArray by name. Return nullptr if branch is not inherited from TClonesArray.
TString GetBranchName (Int_t idx) const
Long64_t GetCurrentEventID () const
Get current eventID.
TString GetDataPath ()
LKDetector * GetDetector (Int_t idx=0) const
LKDetectorPlane * GetDetectorPlane (Int_t iDetector=0, Int_t iPlane=0)
LKDetectorSystem * GetDetectorSystem () const
Int_t GetDivision () const
Long64_t GetEndEventID () const
Get ending eventID.
Long64_t GetEntries () const
Int_t GetEntry (Long64_t entry=0, Int_t getall=0)
Int_t GetEvent (Long64_t entry)
Equavalent to GetEntry of input tree.
Long64_t GetEventCount () const
Get eventID count [eventa count] = [current event ID] - [start event ID].
TString GetFileHash (TString name)
TChain * GetFriendChain (Int_t iFriend) const
LKParameterContainer * GetG4ProcessTable () const
LKParameterContainer * GetG4SDTable () const
LKParameterContainer * GetG4VolumeTable () const
TChain * GetInputChain () const
TFile * GetInputFile ()
TTree * GetInputTree () const
bool GetNextEvent ()
Int_t GetNumBranches () const
Long64_t GetNumEvents () const
Equavalent to GetNumEvents.
Long64_t GetNumRunEntries () const
Number of events used in the run.
TFile * GetOutputFile ()
TString GetOutputFileName () const
TTree * GetOutputTree ()
LKParameterContainer * GetPar () const
LKParameterContainer * GetParameterContainer () const
Int_t GetRank () const
LKParameterContainer * GetRunHeader ()
Int_t GetRunID () const
const char * GetRunName () const
Long64_t GetStartEventID () const
Get starting eventID.
TString GetTag () const
bool Init ()
void InitAndCollectParameters (TString fileName="")
bool InitTask ()
bool InitTasks ()
bool IsCleanExit ()
virtual bool IsEventTrigger ()
TClonesArray * KeepBranchA (TString name)
LKRun ()
LKRun (TString runName, Int_t id, Int_t division, TString tag)
TString MakeFullRunName () const
void Print (Option_t *option="all") const
void PrintEvent (Long64_t entry=-1, TString branchNames="", Int_t numPrintCut=-1)
void PrintEvent (TString branchNames, Int_t numPrintCut=-1)
TClonesArray * RegisterBranchA (TString name, const char *className, Int_t size=100, bool persistent=true)
bool RegisterObject (TString name, TObject *obj)
void Run (Long64_t numEvents=-1)
Run number of events numEvents from the first point.
void Run (Long64_t startID, Long64_t endID)
Run in range: from startID to endID.
bool RunEvent (Long64_t eventID=-2)
Run event of eventID.
bool RunSelectedEvent (TString selection)
Find event that matches the given selection and run. The selection is set from first call of RunSelectedEvent.
void SetAutoEndOfRun (Bool_t val)
void SetAutoTermination (Bool_t val)
void SetDataPath (TString path)
void SetDivision (Int_t division)
void SetEntries (Long64_t num)
Set total number of entries. Use only input do not exist.
void SetEventCountForMessage (Long64_t val)
void SetEventTrigger (LKTask *task)
void SetInputFile (TString fileName, TString treeName="event")
Add file to input file.
void SetInputTreeName (TString treeName)
Set input tree name.
void SetNumEvents (Long64_t num)
Equavalent to SetEntries.
void SetNumPrintMessage (Long64_t num)
void SetOutputFile (TString name, bool addVersion=false)
Output file.
void SetPar (LKParameterContainer *par)
virtual void SetParameterContainer (LKParameterContainer *par)
virtual void SetRank (Int_t rank)
void SetRun (LKRun *run)
void SetRunName (TString name, Int_t id=0, Int_t division=-1, TString tag="")
Set Run name and id.
void SetSplit (Int_t split, Long64_t numEventsInSplit)
void SetTag (TString tag)
void SignalEndOfRun ()
virtual void SignalNextEvent ()
bool StartOfRun (Long64_t numEvents=-1)
void Terminate (TObject *obj, TString message="")
void WriteExitLog (TString path)
bool WriteOutputFile ()
virtual ~LKRun ()
Static Public Member Functions
static bool CheckFileExistence (TString fileName)
static TString ConfigureDataPath (TString name, bool search=false, TString pathData="", bool addVersion=false)
static LKRun * GetRun ()
Get LKRun static pointer.
static void PrintLILAK ()
Print compiled LILAK information.
Protected Member Functions
void ProcessWriteExitLog ()
Protected Attributes
LKParameterContainer * fPar = nullptr
Int_t fRank = 0
LKRun * fRun = nullptr
Private Attributes
bool fAddVersion = false
Bool_t fAutoEndOfRun = true
Bool_t fAutoTerminate = true
std::vector< TString > fBranchNames
TClonesArray ** fBranchPtr
std::map< TString, TClonesArray * > fBranchPtrMap
bool fCleanExit = false
Int_t fCountBranches = 0
Int_t fCountRunObjects = 0
Long64_t fCurrentEventID = 0
Long64_t fCurrSelEventID = 0
TString fDataPath = ""
LKDetectorSystem * fDetectorSystem = nullptr
Int_t fDivision = -1
Long64_t fEndEventID = -1
bool fErrorInputFile = false
Long64_t fEventCount = 0
Long64_t fEventCountForMessage = 0
LKTask * fEventTrigger = nullptr
TString fExitLogPath
bool fFillCurrentEvent = true
vector< TString > fFriendFileNameArray
TObjArray * fFriendTrees = nullptr
LKParameterContainer * fG4ProcessTable = nullptr
List of Geant4 physics process.
LKParameterContainer * fG4SDTable = nullptr
List of Geant4 sensitive detectors.
LKParameterContainer * fG4VolumeTable = nullptr
Long64_t fIdxEntry = 0
bool fInitialized = false
TFile * fInputFile = nullptr
TString fInputFileName = ""
std::vector< TString > fInputFileNameArray
TChain * fInputTree = nullptr
TObjArray * fInputTreeBranchArray = nullptr
TString fInputTreeName = ""
TString fInputVersion = ""
std::vector< TString > fListOfGitBranches
std::vector< TString > fListOfGitHashTags
std::vector< Int_t > fListOfNumTagsInGitBranches
std::vector< TString > fListOfVersionMarks
Long64_t fNumEntries = 0
Long64_t fNumEventsInSplit = -1
Int_t fNumFriends = 0
Long64_t fNumPrintMessage = 20
Long64_t fNumRunEntries = 0
Long64_t fNumSelEntries
TString fOuputHash = ""
TFile * fOutputFile = nullptr
TString fOutputFileName = ""
TTree * fOutputTree = nullptr
TString fParAddAfter = ""
TObjArray * fPersistentBranchArray = nullptr
Long64_t fPrevSelEventID = 0
bool fRunHasStarted = false
LKParameterContainer * fRunHeader = nullptr
Int_t fRunID = -1
TString fRunName = "run"
bool fRunNameIsSet = false
TString fRunObjectName [20]
TObject ** fRunObjectPtr
std::map< TString, TObject * > fRunObjectPtrMap
TString fSelectionString
TEntryList * fSelEntryList = nullptr
bool fSignalEndOfRun = false
Int_t fSplit = -1
Int_t fSplitInput = -1
Long64_t fStartEventID = -1
TString fTag = ""
TString fTagInput = ""
TObjArray * fTemporaryBranchArray = nullptr
Int_t fTreeNumber = -1
bool fUsingEventTrigger = false
Static Private Attributes
static LKRun * fInstance
Detailed Description
If output file name is not set, output file name will be named as below. In general: [run_name]_[run_id(4-digits)].[lilak_version].root; If tag exist: [run_name]_[run_id(4-digits)].[user-tag].[lilak_version].root; If splited: [run_name]_[run_id(4-digits)]_s[split_no].[user-tag].[lilak_version].root;
Definition at line 35 of file LKRun.h.
Constructor & Destructor Documentation
LKRun() [1/2]
LKRun::LKRun (TString runName, Int_t id, Int_t division, TString tag)
Definition at line 27 of file LKRun.cpp.
References AddInputFile(), AlwaysPrintMessage(), LKGear::CreateParameterContainer(), fBranchPtr, fDetectorSystem, fDivision, fFriendTrees, fInputTreeBranchArray, fInstance, fListOfGitBranches, fListOfGitHashTags, fListOfNumTagsInGitBranches, fListOfVersionMarks, fPersistentBranchArray, fRunID, fRunName, fRunObjectPtr, fTag, fTemporaryBranchArray, and LILAK_PATH.
LKRun() [2/2]
LKRun::LKRun () inline
Definition at line 41 of file LKRun.h.
~LKRun()
virtual LKRun::~LKRun () inline virtual
Definition at line 42 of file LKRun.h.
Member Function Documentation
Add() [1/2]
void LKRun::Add (LKTask * task)
Add task to be executed every event.
Definition at line 488 of file LKRun.cpp.
References LKTask::Add(), LKTask::IsEventTrigger(), SetEventTrigger(), and LKGear::SetRun().
Referenced by Init(), and RegisterBranchA().
Add() [2/2]
void LKTask::Add (TTask * task) virtual inherited
Definition at line 16 of file LKTask.cpp.
References LKGear::AddPar(), LKGear::fPar, LKGear::fRank, and LKTask::SetRank().
Referenced by Add(), LKEveTask::ConfigureDetectorPlanes(), LKEveTask::DrawEve3D(), LKNoiseSubtractionTask::Exec(), TTHTTrackingTask::TransformAndSelectHits(), and httask::TransformAndSelectHits().
AddDetector()
void LKRun::AddDetector (LKDetector * detector)
Set detector.
Definition at line 1422 of file LKRun.cpp.
References AddDetector(), LKGear::CreateParameterContainer(), fDetectorSystem, LKGear::fPar, and LKGear::SetRun().
Referenced by AddDetector().
AddFriend()
void LKRun::AddFriend (TString fileName)
Add file to input file.
Definition at line 534 of file LKRun.cpp.
References ConfigureDataPath(), fDataPath, fErrorInputFile, fFriendFileNameArray, and lk_error.
Referenced by Init().
AddInputFile()
void LKRun::AddInputFile (TString fileName, TString treeName = "event")
Add file to input file.
Definition at line 520 of file LKRun.cpp.
References ConfigureDataPath(), fDataPath, fErrorInputFile, fInputFileNameArray, fInputTreeName, fInputVersion, GetFileHash(), and lk_error.
Referenced by AddInputList(), LKRun(), and SetInputFile().
AddInputList()
void LKRun::AddInputList (TString fileName, TString treeName = "event")
Input file.
Add file to input file
Definition at line 512 of file LKRun.cpp.
References AddInputFile().
AddPar() [1/2]
void LKGear::AddPar (LKParameterContainer * par) inline inherited
Definition at line 27 of file LKGear.h.
References LKGear::AddParameterContainer().
Referenced by LKTask::Add(), EndOfRun(), Init(), LKG4RunManager::Initialize(), LAMPSTPC::LAMPSTPC(), LAMPSTPC::LAMPSTPC(), LKDetectorSystem::SetDetectorPar(), SetEventTrigger(), LKG4RunManager::SetSensitiveDetector(), LKG4RunManager::SetVolume(), StartOfRun(), TexAT2::TexAT2(), TexAT2::TexAT2(), and TTMicromegas::WriteCurrentChannel().
AddPar() [2/2]
void LKGear::AddPar (TString fname) inline inherited
Definition at line 28 of file LKGear.h.
References LKGear::AddParameterContainer().
AddParAfter()
void LKRun::AddParAfter (TString fname) inline
Definition at line 120 of file LKRun.h.
References fParAddAfter.
AddParameterContainer() [1/2]
void LKGear::AddParameterContainer (LKParameterContainer * par) virtual inherited
Definition at line 14 of file LKGear.cpp.
References LKGear::AddParameterContainer(), and LKGear::fPar.
Referenced by LKGear::AddPar(), LKGear::AddPar(), LKGear::AddParameterContainer(), LHTpc::BuildDetectorPlane(), and Init().
AddParameterContainer() [2/2]
void LKGear::AddParameterContainer (TString fname) virtual inherited
Definition at line 22 of file LKGear.cpp.
References LKGear::fPar.
AlwaysPrintMessage()
void LKRun::AlwaysPrintMessage () inline
Definition at line 116 of file LKRun.h.
References fEventCountForMessage.
Referenced by LKRun().
CheckFileExistence()
bool LKRun::CheckFileExistence (TString fileName) static
Definition at line 1414 of file LKRun.cpp.
Referenced by ConfigureDataPath(), and Init().
CheckMute()
bool LKRun::CheckMute () inline
Definition at line 247 of file LKRun.h.
References fEventCount, and fEventCountForMessage.
ClearArrays()
void LKRun::ClearArrays ()
Definition at line 1261 of file LKRun.cpp.
References fPersistentBranchArray, fTemporaryBranchArray, and GetEntries().
ConfigureDataPath()
TString LKRun::ConfigureDataPath (TString name, bool search = false, TString pathData = "", bool addVersion = false) static
Definition at line 373 of file LKRun.cpp.
References CheckFileExistence(), e_info, LILAK_MAINPROJECT_VERSION, and LILAK_PATH.
Referenced by AddFriend(), AddInputFile(), ConfigureFileName(), and Init().
ConfigureFileName()
TString LKRun::ConfigureFileName ()
Definition at line 212 of file LKRun.cpp.
References ConfigureDataPath(), fDataPath, and MakeFullRunName().
Referenced by Init().
ConfigureRunFromFileName()
bool LKRun::ConfigureRunFromFileName (TString inputName)
Definition at line 119 of file LKRun.cpp.
References fRunID, fRunName, fSplit, fTag, and GetEntries().
Referenced by Init().
CreateParameterContainer()
void LKGear::CreateParameterContainer () inherited
Referenced by AddDetector(), and LKRun().
DoNotFillCurrentEvent()
void LKRun::DoNotFillCurrentEvent () inline
Definition at line 248 of file LKRun.h.
References fFillCurrentEvent.
EndOfRun()
bool LKRun::EndOfRun () virtual
Reimplemented from LKTask.
Definition at line 1343 of file LKRun.cpp.
References LKGear::AddPar(), e_cout, EndOfRun(), LKTask::EndOfRunTasks(), fAutoTerminate, fCleanExit, fEndEventID, fEventTrigger, fIdxEntry, fRunHasStarted, fRunHeader, fSignalEndOfRun, fStartEventID, fUsingEventTrigger, lk_info, Print(), ProcessWriteExitLog(), Terminate(), and WriteOutputFile().
Referenced by EndOfRun(), and Run().
EndOfRunTask()
bool LKTask::EndOfRunTask () inherited
Definition at line 58 of file LKTask.cpp.
References LKTask::EndOfRun(), and LKTask::EndOfRunTasks().
EndOfRunTasks()
bool LKTask::EndOfRunTasks () inherited
Definition at line 75 of file LKTask.cpp.
References LKTask::EndOfRun(), lk_info, and lk_warning.
Referenced by EndOfRun(), and LKTask::EndOfRunTask().
ExecuteEvent()
bool LKRun::ExecuteEvent (Long64_t eventID = -1)
Run just one event of eventID.
Definition at line 1177 of file LKRun.cpp.
References e_cout, fCurrentEventID, fEventCount, fEventCountForMessage, fFillCurrentEvent, fNumEntries, fNumRunEntries, fOutputTree, fRunHasStarted, fSignalEndOfRun, GetEntry(), lk_error, lk_info, lk_set_message, and StartOfRun().
Referenced by ExecuteFirstEvent(), ExecuteLastEvent(), ExecuteNextEvent(), ExecutePreviousEvent(), next(), Run(), RunEvent(), and RunSelectedEvent().
ExecuteFirstEvent()
bool LKRun::ExecuteFirstEvent () inline
Definition at line 244 of file LKRun.h.
References ExecuteEvent().
ExecuteLastEvent()
bool LKRun::ExecuteLastEvent () inline
Definition at line 245 of file LKRun.h.
References ExecuteEvent().
ExecuteNextEvent()
bool LKRun::ExecuteNextEvent () inline
Definition at line 242 of file LKRun.h.
References ExecuteEvent().
Referenced by next().
ExecutePreviousEvent()
bool LKRun::ExecutePreviousEvent () inline
Definition at line 243 of file LKRun.h.
References ExecuteEvent().
FindDetector()
LKDetector * LKRun::FindDetector (const char * name)
Definition at line 1434 of file LKRun.cpp.
References fDetectorSystem, and FindDetector().
Referenced by FindDetector().
FindDetectorPlane()
LKDetectorPlane * LKRun::FindDetectorPlane (const char * name)
Definition at line 1435 of file LKRun.cpp.
References fDetectorSystem, and FindDetectorPlane().
Referenced by FindDetectorPlane().
GetBranchA() [1/2]
TClonesArray * LKRun::GetBranchA (Int_t idx)
Definition at line 998 of file LKRun.cpp.
References fBranchPtr.
GetBranchA() [2/2]
TClonesArray * LKRun::GetBranchA (TString name)
Get branch in TClonesArray by name. Return nullptr if branch is not inherited from TClonesArray.
Definition at line 1007 of file LKRun.cpp.
References fBranchPtrMap, and lk_error.
Referenced by KeepBranchA().
GetBranchName()
TString LKRun::GetBranchName (Int_t idx) const
Definition at line 963 of file LKRun.cpp.
References fBranchNames.
Referenced by LKEveTask::Init().
GetCurrentEventID()
Long64_t LKRun::GetCurrentEventID () const inline
Get current eventID.
Definition at line 197 of file LKRun.h.
References fCurrentEventID.
Referenced by LKEvePlane::ClickedControlEvent2(), and NextChannel().
GetDataPath()
TString LKRun::GetDataPath () inline
Definition at line 88 of file LKRun.h.
References fDataPath.
Referenced by LKPulseExtractionTask::Init(), and TTPulseExtractionTask::Init().
GetDetector()
LKDetector * LKRun::GetDetector (Int_t idx = 0) const
Definition at line 1429 of file LKRun.cpp.
References fDetectorSystem.
Referenced by GetDetectorPlane(), and Init().
GetDetectorPlane()
LKDetectorPlane * LKRun::GetDetectorPlane (Int_t iDetector = 0, Int_t iPlane = 0)
Definition at line 1430 of file LKRun.cpp.
References GetDetector(), and GetDetectorPlane().
Referenced by GetDetectorPlane(), and Init().
GetDetectorSystem()
LKDetectorSystem * LKRun::GetDetectorSystem () const
Definition at line 1433 of file LKRun.cpp.
References fDetectorSystem.
Referenced by LKGETChannelViewer::Init(), and LKPulseShapeAnalysisTask::Init().
GetDivision()
Int_t LKRun::GetDivision () const inline
Definition at line 79 of file LKRun.h.
References fDivision.
GetEndEventID()
Long64_t LKRun::GetEndEventID () const inline
Get ending eventID.
Definition at line 196 of file LKRun.h.
References fEndEventID.
GetEntries()
Long64_t LKRun::GetEntries () const inline
Get total number of entries
Definition at line 184 of file LKRun.h.
References fNumEntries.
Referenced by ClearArrays(), ConfigureRunFromFileName(), GetFileHash(), Init(), Print(), and PrintEvent().
GetEntry()
Int_t LKRun::GetEntry (Long64_t entry = 0, Int_t getall = 0)
GetEntry current from input tree. For options For options see TTree::GetEntry : https://root.cern.ch/doc/master/classTTree.html#a14c88179bd5fd2116228707d6addea9f
Definition at line 1035 of file LKRun.cpp.
References fCurrentEventID, fInputTree, fNumFriends, fOutputTree, GetEntry(), and GetFriendChain().
Referenced by ExecuteEvent(), GetEntry(), GetEvent(), GetNextEvent(), Init(), and PrintEvent().
GetEvent()
Int_t LKRun::GetEvent (Long64_t entry) inline
Equavalent to GetEntry of input tree.
Definition at line 192 of file LKRun.h.
References GetEntry().
GetEventCount()
Long64_t LKRun::GetEventCount () const inline
Get eventID count [eventa count] = [current event ID] - [start event ID].
Definition at line 198 of file LKRun.h.
References fEventCount.
GetFileHash()
TString LKRun::GetFileHash (TString name)
Definition at line 362 of file LKRun.cpp.
References GetEntries().
Referenced by AddInputFile(), and Init().
GetFriendChain()
TChain * LKRun::GetFriendChain (Int_t iFriend) const
Definition at line 545 of file LKRun.cpp.
References fFriendTrees.
Referenced by GetEntry(), and Init().
GetG4ProcessTable()
LKParameterContainer * LKRun::GetG4ProcessTable () const inline
Definition at line 136 of file LKRun.h.
References fG4ProcessTable.
GetG4SDTable()
LKParameterContainer * LKRun::GetG4SDTable () const inline
Definition at line 137 of file LKRun.h.
References fG4SDTable.
GetG4VolumeTable()
LKParameterContainer * LKRun::GetG4VolumeTable () const inline
Definition at line 138 of file LKRun.h.
References fG4VolumeTable.
GetInputChain()
TChain * LKRun::GetInputChain () const inline
Definition at line 100 of file LKRun.h.
References fInputTree.
GetInputFile()
TFile * LKRun::GetInputFile () inline
Definition at line 98 of file LKRun.h.
References fInputFile.
Referenced by LKGETChannelViewer::Exec().
GetInputTree()
TTree * LKRun::GetInputTree () const inline
Definition at line 99 of file LKRun.h.
References fInputTree.
GetNextEvent()
bool LKRun::GetNextEvent ()
Definition at line 1052 of file LKRun.cpp.
References fCurrentEventID, and GetEntry().
GetNumBranches()
Int_t LKRun::GetNumBranches () const inline
Definition at line 173 of file LKRun.h.
References fCountBranches.
GetNumEvents()
Long64_t LKRun::GetNumEvents () const inline
Equavalent to GetNumEvents.
Definition at line 190 of file LKRun.h.
References fNumEntries.
Referenced by example_psa(), LKEvePlane::GetHistControlEvent1(), and LKEvePlane::SetPalette().
GetNumRunEntries()
Long64_t LKRun::GetNumRunEntries () const inline
Number of events used in the run.
Definition at line 191 of file LKRun.h.
References fNumRunEntries.
GetOutputFile()
TFile * LKRun::GetOutputFile () inline
Definition at line 109 of file LKRun.h.
References fOutputFile.
GetOutputFileName()
TString LKRun::GetOutputFileName () const inline
Definition at line 114 of file LKRun.h.
References fOutputFileName.
GetOutputTree()
TTree * LKRun::GetOutputTree () inline
Definition at line 110 of file LKRun.h.
References fOutputTree.
GetPar()
LKParameterContainer * LKGear::GetPar () const inherited
Definition at line 33 of file LKGear.cpp.
References LKGear::fPar.
GetParameterContainer()
LKParameterContainer * LKGear::GetParameterContainer () const inherited
Definition at line 32 of file LKGear.cpp.
References LKGear::fPar.
Referenced by ClassImp(), LHElectronicsTask::Init(), and LHVertexFindingTask::Init().
GetRank()
Int_t LKGear::GetRank () const inherited
Definition at line 36 of file LKGear.cpp.
References LKGear::fRank.
GetRun()
static LKRun * LKRun::GetRun () static
Get LKRun static pointer.
Referenced by TexAT2::CAACToGlobalPosition(), CAACtoRealDim(), ClassImp(), debug_htt(), LHPSATask::Init(), LHElectronicsTask::Init(), LHVertexFindingTask::Init(), next(), next(), next(), nextEvent(), run_digi(), run_eve(), run_read(), run_reco(), write(), and TTMicromegas::WriteCurrentChannel().
GetRunHeader()
LKParameterContainer * LKRun::GetRunHeader () inline
Definition at line 102 of file LKRun.h.
References fRunHeader.
GetRunID()
Int_t LKRun::GetRunID () const inline
Definition at line 78 of file LKRun.h.
References fRunID.
GetRunName()
const char * LKRun::GetRunName () const inline
Definition at line 77 of file LKRun.h.
References fRunName.
Referenced by LTPadPlane::FillDataToHist(), and LKEvePlane::FillDataToHistEventDisplay1().
GetStartEventID()
Long64_t LKRun::GetStartEventID () const inline
Get starting eventID.
Definition at line 195 of file LKRun.h.
References fStartEventID.
GetTag()
TString LKRun::GetTag () const inline
Definition at line 80 of file LKRun.h.
References fTag.
Init()
bool LKRun::Init () virtual
Initailize LKRun. Configure input and output files(trees and branches), input parameters and detectors Init() must be done before Run().
Reimplemented from LKTask.
Definition at line 547 of file LKRun.cpp.
References Add(), AddFriend(), LKGear::AddPar(), LKGear::AddParameterContainer(), CheckFileExistence(), LKParameterContainer::CheckPar(), ConfigureDataPath(), ConfigureFileName(), ConfigureRunFromFileName(), e_cout, fAddVersion, fBranchNames, fBranchPtr, fBranchPtrMap, fCountBranches, fCurrentEventID, fDataPath, fDetectorSystem, fDivision, fErrorInputFile, fEventTrigger, fFriendFileNameArray, fFriendTrees, fG4ProcessTable, fG4SDTable, fG4VolumeTable, fInitialized, fInputFile, fInputFileName, fInputFileNameArray, fInputTree, fInputTreeBranchArray, fInputTreeName, fInputVersion, fNumEntries, fNumEventsInSplit, fNumFriends, fOuputHash, fOutputFile, fOutputFileName, fOutputTree, LKGear::fPar, fParAddAfter, fRunHeader, fRunID, fRunName, fRunNameIsSet, fSplit, fSplitInput, fTag, fTagInput, fUsingEventTrigger, GetDetector(), GetDetectorPlane(), GetEntries(), GetEntry(), GetFileHash(), GetFriendChain(), LKDetectorSystem::GetNumDetectors(), LKDetectorSystem::GetNumPlanes(), Init(), LKTask::InitTasks(), LILAK_HOSTNAME, LILAK_MAINPROJECT_VERSION, LILAK_PATH, LILAK_USERNAME, LILAK_VERSION, lk_cout, lk_error, lk_info, lk_warning, next(), Print(), LKGear::SetPar(), LKGear::SetRun(), and Terminate().
Referenced by Init(), InitAndCollectParameters(), and StartOfRun().
InitAndCollectParameters()
void LKRun::InitAndCollectParameters (TString fileName = "")
Initailize LKRun and collect parameters. Print collected parameters to fileName. Print out to screen if fileName is null.
Definition at line 863 of file LKRun.cpp.
References LKGear::fPar, and Init().
InitTask()
bool LKTask::InitTask () inherited
Definition at line 25 of file LKTask.cpp.
References LKTask::Init(), and LKTask::InitTasks().
InitTasks()
bool LKTask::InitTasks () inherited
Definition at line 42 of file LKTask.cpp.
References LKTask::Init(), lk_info, and lk_warning.
Referenced by Init(), and LKTask::InitTask().
IsCleanExit()
bool LKRun::IsCleanExit () inline
Definition at line 227 of file LKRun.h.
References fCleanExit.
IsEventTrigger()
virtual bool LKTask::IsEventTrigger () inline virtual inherited
Reimplemented in LKMFMConversionTask.
Definition at line 32 of file LKTask.h.
Referenced by Add().
KeepBranchA()
TClonesArray * LKRun::KeepBranchA (TString name)
Definition at line 1019 of file LKRun.cpp.
References fOutputTree, GetBranchA(), and lk_info.
MakeFullRunName()
TString LKRun::MakeFullRunName () const
Definition at line 201 of file LKRun.cpp.
References fDivision, fRunID, fRunName, fSplit, and fTag.
Referenced by ConfigureFileName().
Print()
void LKRun::Print (Option_t * option = "all") const
options
all : Print all (below)
gen : Print general information
par : Print parameter information
out : Print output information
in : Print input information
det : Print detector information
task : Print detector information
Definition at line 219 of file LKRun.cpp.
References e_cout, fDetectorSystem, fFriendTrees, fInitialized, fInputFileName, fInputTree, fNumFriends, fOutputFileName, fOutputTree, LKGear::fPar, GetEntries(), lk_cout, lk_debug, lk_info, lk_warning, next(), Print(), and PrintLILAK().
Referenced by EndOfRun(), Init(), Print(), and PrintEvent().
PrintEvent() [1/2]
void LKRun::PrintEvent (Long64_t entry = -1, TString branchNames = "", Int_t numPrintCut = -1)
Print element of each branch in event
Parameters
entry Entry number. -1 will use the current entry.
branchNames ex) Track:Hit:RawData
numPrintCut The number of elements to be printed at most
Definition at line 319 of file LKRun.cpp.
References e_cout, fInputTreeBranchArray, fPersistentBranchArray, GetEntries(), GetEntry(), lk_info, and Print().
PrintEvent() [2/2]
void LKRun::PrintEvent (TString branchNames, Int_t numPrintCut = -1) inline
Definition at line 71 of file LKRun.h.
References PrintEvent().
Referenced by PrintEvent().
PrintLILAK()
void LKRun::PrintLILAK () static
Print compiled LILAK information.
Definition at line 100 of file LKRun.cpp.
References LILAK_HOSTNAME, LILAK_MAINPROJECT_VERSION, LILAK_PATH, LILAK_USERNAME, and LILAK_VERSION.
Referenced by Print().
ProcessWriteExitLog()
void LKRun::ProcessWriteExitLog () protected
Definition at line 1394 of file LKRun.cpp.
References fCleanExit, fExitLogPath, fOutputFile, fOutputFileName, fRunHeader, and lk_info.
Referenced by EndOfRun().
RegisterBranchA()
TClonesArray * LKRun::RegisterBranchA (TString name, const char * className, Int_t size = 100, bool persistent = true)
Create, register and return TClonesArray object. TClonesArray object will not be registered if same name already exist in the branch list and return fail. If persistent is true, branch will write it's data to output tree. If persistent is false, branch will not be written. However the data is accessible during the run One can set persistency using the parameter [branchName]/persistency
Definition at line 920 of file LKRun.cpp.
References Add(), fBranchNames, fBranchPtr, fBranchPtrMap, fCountBranches, fOutputTree, LKGear::fPar, fPersistentBranchArray, fTemporaryBranchArray, lk_error, and lk_info.
RegisterObject()
bool LKRun::RegisterObject (TString name, TObject * obj)
Register obj as a output branch with given name. obj will not be registered if same name already exist in the branch list and return fail. Object(obj) is recommanded to be TClones array ex) dataArray = new TClonesArray("TDataClass",1000); // 1000, for example should be around expected maximum number of "data" If persistent is true, branch will write it's data to output tree. If persistent is false, branch will not be written. However the data is accessible during the run One can set persistency using the parameter [branchName]/persistency Register obj and write directly to ouput file
Definition at line 909 of file LKRun.cpp.
References fCountRunObjects, fRunObjectName, fRunObjectPtr, fRunObjectPtrMap, and lk_error.
Run() [1/2]
void LKRun::Run (Long64_t numEvents = -1) virtual
Run number of events numEvents from the first point.
Run all events
Run(nid), Run(id1,id2), RunEvent(id) and RunSelectedEvent(selection):
‍StartOfRun() -> Run ExecTasks() for all event(s) -> Run EndOfRunTasks() -> Write trees, parameters, headers -> EndOfRun() Run Exec() for one event (will not write any object)
Reimplemented from LKTask.
Definition at line 1081 of file LKRun.cpp.
References e_cout, EndOfRun(), ExecuteEvent(), fCurrentEventID, fEndEventID, fEventTrigger, fIdxEntry, fStartEventID, fUsingEventTrigger, Run(), and StartOfRun().
Referenced by Run(), and Run().
Run() [2/2]
void LKRun::Run (Long64_t startID, Long64_t endID)
Run in range: from startID to endID.
Definition at line 1109 of file LKRun.cpp.
References fEndEventID, fNumEntries, fStartEventID, lk_error, and Run().
RunEvent()
bool LKRun::RunEvent (Long64_t eventID = -2)
Run event of eventID.
Definition at line 1123 of file LKRun.cpp.
References ExecuteEvent(), fNumEntries, SetNumPrintMessage(), and StartOfRun().
RunSelectedEvent()
bool LKRun::RunSelectedEvent (TString selection)
Find event that matches the given selection and run. The selection is set from first call of RunSelectedEvent.
Definition at line 1130 of file LKRun.cpp.
References ExecuteEvent(), fCurrSelEventID, fInputTree, fNumEntries, fNumRunEntries, fNumSelEntries, fPrevSelEventID, fSelectionString, fSelEntryList, fTreeNumber, lk_info, lk_warning, SetNumPrintMessage(), and StartOfRun().
SetAutoEndOfRun()
void LKRun::SetAutoEndOfRun (Bool_t val) inline
Definition at line 232 of file LKRun.h.
References fAutoEndOfRun.
SetAutoTermination()
void LKRun::SetAutoTermination (Bool_t val) inline
Definition at line 234 of file LKRun.h.
References fAutoTerminate.
SetDataPath()
void LKRun::SetDataPath (TString path) inline
Set data directory path. Default directory : path/to/LILAK/data Data path will not be used if full path of the input/ouput file is given. This is equivalent to setting parameter LKRun/DataPath. Hoever SetDataPath method has the higher priority over setting parameter
Definition at line 87 of file LKRun.h.
References fDataPath.
SetDivision()
void LKRun::SetDivision (Int_t division) inline
Definition at line 111 of file LKRun.h.
References fDivision.
SetEntries()
void LKRun::SetEntries (Long64_t num) inline
Set total number of entries. Use only input do not exist.
Definition at line 183 of file LKRun.h.
References fNumEntries.
Referenced by SetNumEvents().
SetEventCountForMessage()
void LKRun::SetEventCountForMessage (Long64_t val) inline
Definition at line 117 of file LKRun.h.
References fEventCountForMessage.
SetEventTrigger()
void LKRun::SetEventTrigger (LKTask * task)
Set EventTrigger which give signal to LKRun that evnet has started. EventTrigger should call LKRun::ExecuteNextEvent() when ever event start, from Exec() method. EventTrigger should Return from the Exec() method after all events has been executed.
Definition at line 499 of file LKRun.cpp.
References LKGear::AddPar(), fEventTrigger, LKGear::fPar, LKGear::fRank, fUsingEventTrigger, lk_error, LKTask::SetRank(), and LKGear::SetRun().
Referenced by Add().
SetInputFile()
void LKRun::SetInputFile (TString fileName, TString treeName = "event") inline
Add file to input file.
Definition at line 96 of file LKRun.h.
References AddInputFile().
SetInputTreeName()
void LKRun::SetInputTreeName (TString treeName) inline
Set input tree name.
Definition at line 97 of file LKRun.h.
References fInputTreeName.
SetNumEvents()
void LKRun::SetNumEvents (Long64_t num) inline
Equavalent to SetEntries.
Definition at line 189 of file LKRun.h.
References SetEntries().
SetNumPrintMessage()
void LKRun::SetNumPrintMessage (Long64_t num) inline
Definition at line 118 of file LKRun.h.
References fNumPrintMessage.
Referenced by RunEvent(), and RunSelectedEvent().
SetOutputFile()
void LKRun::SetOutputFile (TString name, bool addVersion = false) inline
Output file.
Definition at line 108 of file LKRun.h.
References fAddVersion, and fOutputFileName.
SetPar()
void LKGear::SetPar (LKParameterContainer * par) inline inherited
Definition at line 26 of file LKGear.h.
References LKGear::SetParameterContainer().
Referenced by LKDetector::AddPlane(), Init(), LKDetector::Init(), and LKMFMConversionTask::Init().
SetParameterContainer()
void LKGear::SetParameterContainer (LKParameterContainer * par) virtual inherited
Definition at line 10 of file LKGear.cpp.
References LKGear::fPar.
Referenced by ATTPC::BuildDetectorPlane(), and LKGear::SetPar().
SetRank()
void LKTask::SetRank (Int_t rank) virtual inherited
Reimplemented from LKGear.
Definition at line 91 of file LKTask.cpp.
References LKGear::fRank, and LKTask::SetRank().
Referenced by LKTask::Add(), SetEventTrigger(), and LKTask::SetRank().
SetRun()
void LKGear::SetRun (LKRun * run) inline inherited
Definition at line 36 of file LKGear.h.
References LKGear::fRun, and run.
Referenced by Add(), AddDetector(), Init(), LKDetectorSystem::SetDetector(), and SetEventTrigger().
SetRunName()
void LKRun::SetRunName (TString name, Int_t id = 0, Int_t division = -1, TString tag = "")
Set Run name and id.
Run name/id This is equivalent to setting parameter LKRun/RunName [name] [id] [division(optional)].[tag(optional)]
Definition at line 110 of file LKRun.cpp.
References fDivision, fRunID, fRunName, fRunNameIsSet, and fTag.
SetSplit()
void LKRun::SetSplit (Int_t split, Long64_t numEventsInSplit) inline
Definition at line 113 of file LKRun.h.
References fNumEventsInSplit, and fSplit.
SetTag()
void LKRun::SetTag (TString tag) inline
Definition at line 112 of file LKRun.h.
References fTag.
SignalEndOfRun()
void LKRun::SignalEndOfRun () inline
Definition at line 231 of file LKRun.h.
References fSignalEndOfRun.
SignalNextEvent()
virtual void LKTask::SignalNextEvent () inline virtual inherited
Reimplemented in LKMFMConversionTask.
Definition at line 33 of file LKTask.h.
StartOfRun()
bool LKRun::StartOfRun (Long64_t numEvents = -1)
Run ExecTasks() for single event. This will not write any object. In general Run() should be used instead of Event(). See descriptions in Run() for detail. If you want to write trees after using Event() method,
Definition at line 1279 of file LKRun.cpp.
References LKGear::AddPar(), fCleanExit, fEndEventID, fEventCount, fEventCountForMessage, fInitialized, fNumEntries, fNumEventsInSplit, fNumPrintMessage, fNumRunEntries, fRunHasStarted, fRunHeader, fSplit, fStartEventID, Init(), lk_error, and lk_info.
Referenced by ExecuteEvent(), Run(), RunEvent(), and RunSelectedEvent().
Terminate()
void LKRun::Terminate (TObject * obj, TString message = "")
Definition at line 1408 of file LKRun.cpp.
References lk_info, and Terminate().
Referenced by EndOfRun(), Init(), and Terminate().
WriteExitLog()
void LKRun::WriteExitLog (TString path)
Definition at line 1386 of file LKRun.cpp.
References fExitLogPath, and lk_error.
WriteOutputFile()
bool LKRun::WriteOutputFile ()
Definition at line 1055 of file LKRun.cpp.
References fCountRunObjects, fOutputFile, fOutputFileName, fOutputTree, LKGear::fPar, fRunHeader, fRunObjectName, fRunObjectPtr, LILAK_PATH, and lk_warning.
Referenced by EndOfRun().
Member Data Documentation
fAddVersion
bool LKRun::fAddVersion = false private
Definition at line 277 of file LKRun.h.
Referenced by Init(), and SetOutputFile().
fAutoEndOfRun
Bool_t LKRun::fAutoEndOfRun = true private
Definition at line 338 of file LKRun.h.
Referenced by SetAutoEndOfRun().
fAutoTerminate
Bool_t LKRun::fAutoTerminate = true private
Definition at line 339 of file LKRun.h.
Referenced by EndOfRun(), and SetAutoTermination().
fBranchNames
std::vector<TString> LKRun::fBranchNames private
Definition at line 293 of file LKRun.h.
Referenced by GetBranchName(), Init(), and RegisterBranchA().
fBranchPtr
TClonesArray** LKRun::fBranchPtr private
Definition at line 292 of file LKRun.h.
Referenced by GetBranchA(), Init(), LKRun(), and RegisterBranchA().
fBranchPtrMap
std::map<TString, TClonesArray*> LKRun::fBranchPtrMap private
Definition at line 294 of file LKRun.h.
Referenced by GetBranchA(), Init(), and RegisterBranchA().
fCleanExit
bool LKRun::fCleanExit = false private
Definition at line 324 of file LKRun.h.
Referenced by EndOfRun(), IsCleanExit(), ProcessWriteExitLog(), and StartOfRun().
fCountBranches
Int_t LKRun::fCountBranches = 0 private
Definition at line 291 of file LKRun.h.
Referenced by GetNumBranches(), Init(), and RegisterBranchA().
fCountRunObjects
Int_t LKRun::fCountRunObjects = 0 private
Definition at line 296 of file LKRun.h.
Referenced by RegisterObject(), and WriteOutputFile().
fCurrentEventID
Long64_t LKRun::fCurrentEventID = 0 private
Definition at line 318 of file LKRun.h.
Referenced by ExecuteEvent(), GetCurrentEventID(), GetEntry(), GetNextEvent(), Init(), and Run().
fCurrSelEventID
Long64_t LKRun::fCurrSelEventID = 0 private
Definition at line 308 of file LKRun.h.
Referenced by RunSelectedEvent().
fDataPath
TString LKRun::fDataPath = "" private
Definition at line 262 of file LKRun.h.
Referenced by AddFriend(), AddInputFile(), ConfigureFileName(), GetDataPath(), Init(), and SetDataPath().
fDetectorSystem
LKDetectorSystem* LKRun::fDetectorSystem = nullptr private
Definition at line 331 of file LKRun.h.
Referenced by AddDetector(), FindDetector(), FindDetectorPlane(), GetDetector(), GetDetectorSystem(), Init(), LKRun(), and Print().
fDivision
Int_t LKRun::fDivision = -1 private
Definition at line 257 of file LKRun.h.
Referenced by GetDivision(), Init(), LKRun(), MakeFullRunName(), SetDivision(), and SetRunName().
fEndEventID
Long64_t LKRun::fEndEventID = -1 private
Definition at line 317 of file LKRun.h.
Referenced by EndOfRun(), GetEndEventID(), Run(), Run(), and StartOfRun().
fErrorInputFile
bool LKRun::fErrorInputFile = false private
Definition at line 260 of file LKRun.h.
Referenced by AddFriend(), AddInputFile(), and Init().
fEventCount
Long64_t LKRun::fEventCount = 0 private
Definition at line 319 of file LKRun.h.
Referenced by CheckMute(), ExecuteEvent(), GetEventCount(), and StartOfRun().
fEventCountForMessage
Long64_t LKRun::fEventCountForMessage = 0 private
Definition at line 321 of file LKRun.h.
Referenced by AlwaysPrintMessage(), CheckMute(), ExecuteEvent(), SetEventCountForMessage(), and StartOfRun().
fEventTrigger
LKTask* LKRun::fEventTrigger = nullptr private
Definition at line 341 of file LKRun.h.
Referenced by EndOfRun(), Init(), Run(), and SetEventTrigger().
fExitLogPath
TString LKRun::fExitLogPath private
Definition at line 346 of file LKRun.h.
Referenced by ProcessWriteExitLog(), and WriteExitLog().
fFillCurrentEvent
bool LKRun::fFillCurrentEvent = true private
Definition at line 344 of file LKRun.h.
Referenced by DoNotFillCurrentEvent(), and ExecuteEvent().
fFriendFileNameArray
vector<TString> LKRun::fFriendFileNameArray private
Definition at line 274 of file LKRun.h.
Referenced by AddFriend(), and Init().
fFriendTrees
TObjArray* LKRun::fFriendTrees = nullptr private
Definition at line 273 of file LKRun.h.
Referenced by GetFriendChain(), Init(), LKRun(), and Print().
fG4ProcessTable
LKParameterContainer* LKRun::fG4ProcessTable = nullptr private
List of Geant4 physics process.
Definition at line 328 of file LKRun.h.
Referenced by GetG4ProcessTable(), and Init().
fG4SDTable
LKParameterContainer* LKRun::fG4SDTable = nullptr private
List of Geant4 sensitive detectors.
Definition at line 329 of file LKRun.h.
Referenced by GetG4SDTable(), and Init().
fG4VolumeTable
LKParameterContainer* LKRun::fG4VolumeTable = nullptr private
Definition at line 330 of file LKRun.h.
Referenced by GetG4VolumeTable(), and Init().
fIdxEntry
Long64_t LKRun::fIdxEntry = 0 private
Definition at line 315 of file LKRun.h.
Referenced by EndOfRun(), and Run().
fInitialized
bool LKRun::fInitialized = false private
Definition at line 259 of file LKRun.h.
Referenced by Init(), Print(), and StartOfRun().
fInputFile
TFile* LKRun::fInputFile = nullptr private
Definition at line 266 of file LKRun.h.
Referenced by GetInputFile(), and Init().
fInputFileName
TString LKRun::fInputFileName = "" private
Definition at line 264 of file LKRun.h.
Referenced by Init(), and Print().
fInputFileNameArray
std::vector<TString> LKRun::fInputFileNameArray private
Definition at line 268 of file LKRun.h.
Referenced by AddInputFile(), and Init().
fInputTree
TChain* LKRun::fInputTree = nullptr private
Definition at line 267 of file LKRun.h.
Referenced by GetEntry(), GetInputChain(), GetInputTree(), Init(), Print(), and RunSelectedEvent().
fInputTreeBranchArray
TObjArray* LKRun::fInputTreeBranchArray = nullptr private
Definition at line 289 of file LKRun.h.
Referenced by Init(), LKRun(), and PrintEvent().
fInputTreeName
TString LKRun::fInputTreeName = "" private
Definition at line 265 of file LKRun.h.
Referenced by AddInputFile(), Init(), and SetInputTreeName().
fInputVersion
TString LKRun::fInputVersion = "" private
Definition at line 263 of file LKRun.h.
Referenced by AddInputFile(), and Init().
fInstance
LKRun* LKRun::fInstance static private
Definition at line 349 of file LKRun.h.
Referenced by LKRun().
fListOfGitBranches
std::vector<TString> LKRun::fListOfGitBranches private
Definition at line 333 of file LKRun.h.
Referenced by LKRun().
fListOfGitHashTags
std::vector<TString> LKRun::fListOfGitHashTags private
Todo:
Definition at line 335 of file LKRun.h.
Referenced by LKRun().
fListOfNumTagsInGitBranches
std::vector<Int_t> LKRun::fListOfNumTagsInGitBranches private
Definition at line 334 of file LKRun.h.
Referenced by LKRun().
fListOfVersionMarks
std::vector<TString> LKRun::fListOfVersionMarks private
Todo:
Definition at line 336 of file LKRun.h.
Referenced by LKRun().
fNumEntries
Long64_t LKRun::fNumEntries = 0 private
Definition at line 301 of file LKRun.h.
Referenced by ExecuteEvent(), GetEntries(), GetNumEvents(), Init(), Run(), RunEvent(), RunSelectedEvent(), SetEntries(), and StartOfRun().
fNumEventsInSplit
Long64_t LKRun::fNumEventsInSplit = -1 private
Definition at line 283 of file LKRun.h.
Referenced by Init(), SetSplit(), and StartOfRun().
fNumFriends
Int_t LKRun::fNumFriends = 0 private
Definition at line 272 of file LKRun.h.
Referenced by GetEntry(), Init(), and Print().
fNumPrintMessage
Long64_t LKRun::fNumPrintMessage = 20 private
Definition at line 322 of file LKRun.h.
Referenced by SetNumPrintMessage(), and StartOfRun().
fNumRunEntries
Long64_t LKRun::fNumRunEntries = 0 private
Definition at line 320 of file LKRun.h.
Referenced by ExecuteEvent(), GetNumRunEntries(), RunSelectedEvent(), and StartOfRun().
fNumSelEntries
Long64_t LKRun::fNumSelEntries private
Definition at line 311 of file LKRun.h.
Referenced by RunSelectedEvent().
fOuputHash
TString LKRun::fOuputHash = "" private
Definition at line 278 of file LKRun.h.
Referenced by Init().
fOutputFile
TFile* LKRun::fOutputFile = nullptr private
Definition at line 284 of file LKRun.h.
Referenced by GetOutputFile(), Init(), ProcessWriteExitLog(), and WriteOutputFile().
fOutputFileName
TString LKRun::fOutputFileName = "" private
Definition at line 276 of file LKRun.h.
Referenced by GetOutputFileName(), Init(), Print(), ProcessWriteExitLog(), SetOutputFile(), and WriteOutputFile().
fOutputTree
TTree* LKRun::fOutputTree = nullptr private
Definition at line 285 of file LKRun.h.
Referenced by ExecuteEvent(), GetEntry(), GetOutputTree(), Init(), KeepBranchA(), Print(), RegisterBranchA(), and WriteOutputFile().
fPar
LKParameterContainer* LKGear::fPar = nullptr protected inherited
Definition at line 39 of file LKGear.h.
Referenced by LKTask::Add(), AddDetector(), LKGear::AddParameterContainer(), LKGear::AddParameterContainer(), LKDetector::AddPlane(), LHTpc::BuildDetectorPlane(), ATTPC::BuildDetectorPlane(), LHTpc::BuildGeometry(), ATTPC::BuildGeometry(), ClassImp(), ClassImp(), ClassImp(), ClassImp(), LKEveTask::DrawEve3D(), LKPadPlane::DrawHist(), LKG4RunManager::EndOfRun(), LKPulseExtractionTask::EndOfRun(), LKDetectorPlane::FillDataToHist(), LKPadPlane::FillDataToHist(), LTPadPlane::GetChannelAnalyzer(), LKDetector::GetChannelAnalyzer(), LKDetectorPlane::GetChannelAnalyzer(), LKEvePlane::GetChannelAnalyzer(), LKGear::GetPar(), LKGear::GetParameterContainer(), ATMicromegas::Init(), AToMX::Init(), LTPadPlane::Init(), Init(), LKDetector::Init(), LKEvePlane::Init(), LKMFMConversionTask::Init(), LKDriftElectronTask::Init(), LKEveTask::Init(), LKGETChannelViewer::Init(), LKNoiseSubtractionTask::Init(), LKPulseExtractionTask::Init(), LHPSATask::Init(), TexAT2::Init(), TTMicromegas::Init(), TTHTBeamTrackingTask::Init(), TTHTTrackingTask::Init(), TTPulseExtractionTask::Init(), LHPadPlaneFan::Init(), LHPadPlaneRCut::Init(), LHPadPlaneYCut::Init(), ATTPC::Init(), ATTPC20RectanglePad::Init(), ATTPCHoneyCombPad::Init(), ATTPCRectanglePad::Init(), ATTPCStripPad::Init(), TTFrontPlane::Init(), InitAndCollectParameters(), TexAT2::InitChannelAnalyzer(), LKG4RunManager::Initialize(), Print(), RegisterBranchA(), LKG4RunManager::Run(), LKDetectorPlane::SetDataFromBranch(), LKPadPlane::SetDataFromBranch(), LKDetectorSystem::SetDetectorPar(), LKEveTask::SetEveLineAtt(), LKEveTask::SetEveMarkerAtt(), SetEventTrigger(), LKEveTask::SetGraphAtt(), LKEveTask::SetGraphAtt(), LKG4RunManager::SetOutputFile(), LKGear::SetParameterContainer(), TTMicromegas::WriteCurrentChannel(), and WriteOutputFile().
fParAddAfter
TString LKRun::fParAddAfter = "" private
Definition at line 270 of file LKRun.h.
Referenced by AddParAfter(), and Init().
fPersistentBranchArray
TObjArray* LKRun::fPersistentBranchArray = nullptr private
Definition at line 287 of file LKRun.h.
Referenced by ClearArrays(), LKRun(), PrintEvent(), and RegisterBranchA().
fPrevSelEventID
Long64_t LKRun::fPrevSelEventID = 0 private
Definition at line 307 of file LKRun.h.
Referenced by RunSelectedEvent().
fRank
Int_t LKGear::fRank = 0 protected inherited
Definition at line 41 of file LKGear.h.
Referenced by LKTask::Add(), LKDetector::AddPlane(), LKGear::GetRank(), LKDetectorSystem::SetDetector(), SetEventTrigger(), LKGear::SetRank(), and LKTask::SetRank().
fRun
LKRun* LKGear::fRun = nullptr protected inherited
Definition at line 40 of file LKGear.h.
Referenced by LKDetector::AddPlane(), ClassImp(), ClassImp(), ClassImp(), LKEvePlane::ClickedControlEvent1(), LKEvePlane::ClickedControlEvent1(), LKEvePlane::ClickedControlEvent2(), LKEveTask::DrawDetectorPlanes(), LKEveTask::DrawEve3D(), LKPulseExtractionTask::EndOfRun(), TTPulseExtractionTask::EndOfRun(), LKGETChannelViewer::Exec(), LKPulseExtractionTask::Exec(), TTHitFindingHoughTask::Exec(), TTPulseExtractionTask::Exec(), TTMicromegas::FillDataToHist(), LTPadPlane::FillDataToHist(), LKEvePlane::FillDataToHistEventDisplay1(), LKEvePlane::GetHistControlEvent1(), LTPadPlane::Init(), LTEventPreviewTask::Init(), TTPulseAnalysisTask::Init(), LKEvePlane::Init(), LKMFMConversionTask::Init(), LKDriftElectronTask::Init(), LKEveTask::Init(), LKGETChannelViewer::Init(), LKNoiseSubtractionTask::Init(), LKPulseExtractionTask::Init(), LKPulseShapeAnalysisTask::Init(), TTBeamSelectionTask::Init(), TTDrawBeamEnergyTask::Init(), TTDrawRawWaveformTask::Init(), TTEventSelectionTask::Init(), TTFindBeamTimingTask::Init(), TTGetPedestalTask::Init(), TTPID_FSivsFCsI::Init(), TTPID_MMvsFSi::Init(), TTPID_MMvsX6::Init(), TTPID_X6vsCsI::Init(), TTReadEventListTask::Init(), TTHTtBeamTrackingTask::Init(), TTEventNumberSelectionTask::Init(), TTEventPreviewTask::Init(), TTHitFindingHoughTask::Init(), TTHTBeamTrackingTask::Init(), TTHTTrackingTask::Init(), TTPulseExtractionTask::Init(), httask::Init(), LKMFMConversionTask::Run(), LKGETChannelViewer::SelectMenu(), LKDetectorPlane::SetDataFromBranch(), LKPadPlane::SetDataFromBranch(), TTMicromegas::SetDataFromBranch(), TTFrontPlane::SetDataFromBranch(), LKDetectorSystem::SetDetector(), LKEvePlane::SetPalette(), LKGear::SetRun(), LKDetector::SetRun(), LKMFMConversionTask::SignalNextEvent(), LKEvePlane::UpdateControlEvent1(), and LKEvePlane::UpdateControlEvent2().
fRunHasStarted
bool LKRun::fRunHasStarted = false private
Definition at line 323 of file LKRun.h.
Referenced by EndOfRun(), ExecuteEvent(), and StartOfRun().
fRunHeader
LKParameterContainer* LKRun::fRunHeader = nullptr private
Definition at line 327 of file LKRun.h.
Referenced by EndOfRun(), GetRunHeader(), Init(), ProcessWriteExitLog(), StartOfRun(), and WriteOutputFile().
fRunID
Int_t LKRun::fRunID = -1 private
Definition at line 256 of file LKRun.h.
Referenced by ConfigureRunFromFileName(), GetRunID(), Init(), LKRun(), MakeFullRunName(), and SetRunName().
fRunName
TString LKRun::fRunName = "run" private
Definition at line 255 of file LKRun.h.
Referenced by ConfigureRunFromFileName(), GetRunName(), Init(), LKRun(), MakeFullRunName(), and SetRunName().
fRunNameIsSet
bool LKRun::fRunNameIsSet = false private
Definition at line 254 of file LKRun.h.
Referenced by Init(), and SetRunName().
fRunObjectName
TString LKRun::fRunObjectName[20] private
Definition at line 298 of file LKRun.h.
Referenced by RegisterObject(), and WriteOutputFile().
fRunObjectPtr
TObject** LKRun::fRunObjectPtr private
Definition at line 297 of file LKRun.h.
Referenced by LKRun(), RegisterObject(), and WriteOutputFile().
fRunObjectPtrMap
std::map<TString, TObject*> LKRun::fRunObjectPtrMap private
Definition at line 299 of file LKRun.h.
Referenced by RegisterObject().
fSelectionString
TString LKRun::fSelectionString private
Definition at line 310 of file LKRun.h.
Referenced by RunSelectedEvent().
fSelEntryList
TEntryList* LKRun::fSelEntryList = nullptr private
Definition at line 309 of file LKRun.h.
Referenced by RunSelectedEvent().
fSignalEndOfRun
bool LKRun::fSignalEndOfRun = false private
Definition at line 325 of file LKRun.h.
Referenced by EndOfRun(), ExecuteEvent(), and SignalEndOfRun().
fSplit
Int_t LKRun::fSplit = -1 private
Definition at line 281 of file LKRun.h.
Referenced by ConfigureRunFromFileName(), Init(), MakeFullRunName(), SetSplit(), and StartOfRun().
fSplitInput
Int_t LKRun::fSplitInput = -1 private
Definition at line 282 of file LKRun.h.
Referenced by Init().
fStartEventID
Long64_t LKRun::fStartEventID = -1 private
Definition at line 316 of file LKRun.h.
Referenced by EndOfRun(), GetStartEventID(), Run(), Run(), and StartOfRun().
fTag
TString LKRun::fTag = "" private
Definition at line 279 of file LKRun.h.
Referenced by ConfigureRunFromFileName(), GetTag(), Init(), LKRun(), MakeFullRunName(), SetRunName(), and SetTag().
fTagInput
TString LKRun::fTagInput = "" private
Definition at line 280 of file LKRun.h.
Referenced by Init().
fTemporaryBranchArray
TObjArray* LKRun::fTemporaryBranchArray = nullptr private
Definition at line 288 of file LKRun.h.
Referenced by ClearArrays(), LKRun(), and RegisterBranchA().
fTreeNumber
Int_t LKRun::fTreeNumber = -1 private
Definition at line 306 of file LKRun.h.
Referenced by RunSelectedEvent().
fUsingEventTrigger
bool LKRun::fUsingEventTrigger = false private
Definition at line 342 of file LKRun.h.
Referenced by EndOfRun(), Init(), Run(), and SetEventTrigger().
The documentation for this class was generated from the following files:
LKRun.h
LKRun.cpp