LILAK: LKExtrapolatedTrack Class Reference
LKExtrapolatedTrack Class Reference abstract
#include <LKExtrapolatedTrack.h>
Public Types
enum LKFitStatus : int {
kNone = -1 , kBad = 0 , kLine = 1 , kPlane = 2 ,
kHelix = 3 , kGenfitTrack = 4
}
Public Member Functions
virtual void AddHit (LKHit *hit)
void AddPoint (TVector3 point, Double_t length=-1)
virtual void Clear (Option_t *option="")
virtual void ClearHits ()
virtual double Continuity (double &totalLength, double &continuousLength, double distCut=25)
virtual double Continuity (double distCut=25)
virtual void Copy (TObject &object) const
virtual bool DoDrawOnDetectorPlane ()
virtual bool DrawByDefault ()
return true if to be displayed on eve.
virtual TVector3 ExtrapolateByLength (double l) const =0
Extrapolate by length (tail:0), returns extrapolated position.
virtual TVector3 ExtrapolateByLength (Double_t length) const
virtual TVector3 ExtrapolateByRatio (double r) const =0
Extrapolate by ratio (tail:0, head:1), returns extrapolated position.
virtual TVector3 ExtrapolateByRatio (Double_t) const
virtual TVector3 ExtrapolateHead (double l) const =0
Extrapolate head of track about length, returns extrapolated position.
virtual TVector3 ExtrapolateHead (Double_t) const
virtual TVector3 ExtrapolateTail (double l) const =0
Extrapolate tail of track about length, returns extrapolated position.
virtual TVector3 ExtrapolateTail (Double_t) const
virtual TVector3 ExtrapolateTo (TVector3) const
Extrapolate to POCA from point, returns extrapolated position.
void FillTrajectory (TGraphErrors *graphTrack, LKVector3::Axis axis1, LKVector3::Axis axis2)
void FillTrajectory (TGraphErrors *graphTrack, LKVector3::Axis axis1, LKVector3::Axis axis2, bool(*fisout)(TVector3 pos))
void FillTrajectory3D (TGraph2DErrors *graphTrack3D, LKVector3::Axis axis1, LKVector3::Axis axis2, LKVector3::Axis axis3)
void FillTrajectory3D (TGraph2DErrors *graphTrack3D, LKVector3::Axis axis1, LKVector3::Axis axis2, LKVector3::Axis axis3, bool(*fisout)(TVector3 pos))
virtual void FinalizeHits ()
virtual bool Fit ()
virtual LKGeoHelix FitHelix (LKVector3::Axis ref)
virtual LKGeoLine FitLine ()
virtual LKGeoPlane FitPlane ()
double GetChargeSum () const
LKTracklet::LKFitStatus GetFitStatus () const
TString GetFitStatusString () const
LKHit * GetHit (int idx) const
LKHitArray * GetHitArray ()
int GetHitID (int idx) const
std::vector< int > * GetHitIDArray ()
vector< Double_t > * GetLengths ()
TVector3 GetMean () const
int GetNumHits () const
Int_t GetNumPoints () const
Int_t GetParentID () const
int GetPDG () const
vector< TVector3 > * GetPoints ()
Int_t GetTrackID () const
bool IsBad () const
bool IsGenfitTrack () const
bool IsHelix () const
bool IsHoldingHits ()
bool IsLine () const
bool IsPlane () const
virtual Double_t LengthAt (TVector3) const
Length at POCA from point, where tail=0, head=TrackLength.
LKExtrapolatedTrack ()
virtual TVector3 Momentum (double B=0.5) const =0
Momentum of track at head.
virtual TVector3 Momentum (Double_t B=0.5) const
virtual TVector3 PositionAtHead () const
Position at head of helix.
virtual TVector3 PositionAtTail () const
Position at tail of helix.
virtual void Print (Option_t *option="") const
virtual int RecoverHitArrayWithHitID (TClonesArray *hitArray)
virtual int RecoverHitArrayWithTrackID (TClonesArray *hitArray)
virtual void RemoveHit (LKHit *hit)
void SetFitStatus (LKFitStatus value)
void SetIsBad ()
void SetIsGenfitTrack ()
void SetIsHelix ()
void SetIsLine ()
void SetIsPlane ()
void SetParentID (int val)
void SetParentID (Int_t id)
void SetPDG (int val)
void SetTrackID (int val)
void SetTrackID (Int_t id)
virtual void SortHits (bool increasing=true)
virtual Double_t TrackLength () const
Length of track calculated from head to tail.
virtual TGraphErrors * TrajectoryOnPlane (LKDetectorPlane *plane, double scale=1)
virtual TGraphErrors * TrajectoryOnPlane (LKVector3::Axis axis1, LKVector3::Axis axis2, bool(*fisout)(TVector3 pos), double scale=1)
virtual TGraphErrors * TrajectoryOnPlane (LKVector3::Axis axis1, LKVector3::Axis axis2, bool(*fisout)(TVector3 pos), Double_t scale=1)
virtual TGraphErrors * TrajectoryOnPlane (LKVector3::Axis axis1, LKVector3::Axis axis2, double scale=1)
virtual TGraphErrors * TrajectoryOnPlane (LKVector3::Axis axis1, LKVector3::Axis axis2, Double_t scale=1)
virtual ~LKExtrapolatedTrack ()
Protected Attributes
LKFitStatus fFitStatus
One of kBad, kHelix and kLine.
LKHitArray fHitArray
vector< int > fHitIDArray
int fPDG = -1
TGraphErrors * fTrajectoryOnPlane = nullptr
Private Attributes
vector< Double_t > fLengths
Int_t fParentID
vector< TVector3 > fPoints
Int_t fTrackID
Detailed Description
Track holding discrete points (which should be filled) from tail to head. The track position is calculated by 2-point (line) extrapolation.
Definition at line 16 of file LKExtrapolatedTrack.h.
Member Enumeration Documentation
LKFitStatus
enum LKTracklet::LKFitStatus : int inherited
Enumerator
kNone
kBad
kLine
kPlane
kHelix
kGenfitTrack
Definition at line 19 of file LKTracklet.h.
Constructor & Destructor Documentation
LKExtrapolatedTrack()
LKExtrapolatedTrack::LKExtrapolatedTrack ()
~LKExtrapolatedTrack()
virtual LKExtrapolatedTrack::~LKExtrapolatedTrack () inline virtual
Definition at line 20 of file LKExtrapolatedTrack.h.
Member Function Documentation
AddHit()
void LKTracklet::AddHit (LKHit * hit) virtual inherited
Definition at line 42 of file LKTracklet.cpp.
References LKHitArray::AddHit(), LKTracklet::fHitArray, LKTracklet::fHitIDArray, LKTracklet::fTrackID, LKHit::GetHitID(), and LKTracklet::SetTrackID().
AddPoint()
void LKExtrapolatedTrack::AddPoint (TVector3 point, Double_t length = -1)
Definition at line 49 of file LKExtrapolatedTrack.cpp.
References fLengths, and fPoints.
Clear()
void LKExtrapolatedTrack::Clear (Option_t * option = "") virtual
Reimplemented from LKTracklet.
Definition at line 15 of file LKExtrapolatedTrack.cpp.
References LKTracklet::Clear(), fParentID, fPoints, and fTrackID.
Referenced by ClassImp().
ClearHits()
void LKTracklet::ClearHits () virtual inherited
Definition at line 36 of file LKTracklet.cpp.
References LKHitArray::Clear(), LKTracklet::fHitArray, and LKTracklet::fHitIDArray.
Continuity() [1/2]
double LKTracklet::Continuity (double & totalLength, double & continuousLength, double distCut = 25) virtual inherited
Check continuity of the track. Hit array must be filled. Returns ratio of the continuous region. (-1 if less than 2 hits)
If difference between "length from hits" is smaller than distCut, (> pad-diagonal, < 2*pad-row) the region is considered to be connected.
The total length calculation is different from TrackLength(), because TrackLength() use only the head/tail alpha angle information but this method calculate length directly from the hit using Map(...) method.
Parameters
continuousLength calculated length of continuos region.
totalLength calculated total length of the track.
Reimplemented in LKHelixTrack.
Definition at line 214 of file LKTracklet.cpp.
References LKTracklet::fHitArray, LKHitArray::GetHit(), LKHitArray::GetNumHits(), LKHit::GetPosition(), and LKTracklet::SortHits().
Continuity() [2/2]
virtual double LKTracklet::Continuity (double distCut = 25) inline virtual inherited
Definition at line 164 of file LKTracklet.h.
References LKTracklet::Continuity().
Referenced by LKTracklet::Continuity().
Copy()
void LKContainer::Copy (TObject & object) const virtual inherited
Reimplemented in LKChannel, LKHoughPointRT, LKImagePoint, LKEventHeader, LKMCTagged, LKHit, LKVertex, LKWPoint, GETChannel, LKHelixTrack, LKImagePoint, TTBeamHeader, TTChannelCalibrationData, and TTEventHeader.
Definition at line 16 of file LKContainer.cpp.
Referenced by LKChannel::Copy(), LKHoughPointRT::Copy(), LKImagePoint::Copy(), LKEventHeader::Copy(), LKMCTagged::Copy(), LKHit::Copy(), LKWPoint::Copy(), TTBeamHeader::Copy(), TTChannelCalibrationData::Copy(), and TTEventHeader::Copy().
DoDrawOnDetectorPlane()
bool LKTracklet::DoDrawOnDetectorPlane () virtual inherited
Definition at line 155 of file LKTracklet.cpp.
DrawByDefault()
bool LKTracklet::DrawByDefault () virtual inherited
return true if to be displayed on eve.
Reimplemented from LKContainer.
Definition at line 116 of file LKTracklet.cpp.
ExtrapolateByLength() [1/2]
virtual TVector3 LKTracklet::ExtrapolateByLength (double l) const pure virtual inherited
Extrapolate by length (tail:0), returns extrapolated position.
ExtrapolateByLength() [2/2]
TVector3 LKExtrapolatedTrack::ExtrapolateByLength (Double_t length) const virtual
Definition at line 154 of file LKExtrapolatedTrack.cpp.
References fLengths, and fPoints.
ExtrapolateByRatio() [1/2]
virtual TVector3 LKTracklet::ExtrapolateByRatio (double r) const pure virtual inherited
Extrapolate by ratio (tail:0, head:1), returns extrapolated position.
Referenced by LKTracklet::FillTrajectory(), and LKTracklet::FillTrajectory3D().
ExtrapolateByRatio() [2/2]
virtual TVector3 LKExtrapolatedTrack::ExtrapolateByRatio (Double_t) const inline virtual
Definition at line 35 of file LKExtrapolatedTrack.h.
ExtrapolateHead() [1/2]
virtual TVector3 LKTracklet::ExtrapolateHead (double l) const pure virtual inherited
Extrapolate head of track about length, returns extrapolated position.
ExtrapolateHead() [2/2]
TVector3 LKExtrapolatedTrack::ExtrapolateHead (Double_t length) const virtual
Definition at line 118 of file LKExtrapolatedTrack.cpp.
References fPoints.
ExtrapolateTail() [1/2]
virtual TVector3 LKTracklet::ExtrapolateTail (double l) const pure virtual inherited
Extrapolate tail of track about length, returns extrapolated position.
ExtrapolateTail() [2/2]
TVector3 LKExtrapolatedTrack::ExtrapolateTail (Double_t length) const virtual
Definition at line 136 of file LKExtrapolatedTrack.cpp.
References fPoints.
ExtrapolateTo()
TVector3 LKExtrapolatedTrack::ExtrapolateTo (TVector3 point) const virtual
Extrapolate to POCA from point, returns extrapolated position.
Implements LKTracklet.
Definition at line 72 of file LKExtrapolatedTrack.cpp.
References LKGeoLine::ClosestPointOnLine(), and fPoints.
FillTrajectory() [1/2]
void LKTracklet::FillTrajectory (TGraphErrors * graphTrack, LKVector3::Axis axis1, LKVector3::Axis axis2) inherited
Definition at line 193 of file LKTracklet.cpp.
References LKTracklet::FillTrajectory().
FillTrajectory() [2/2]
void LKTracklet::FillTrajectory (TGraphErrors * graphTrack, LKVector3::Axis axis1, LKVector3::Axis axis2, bool(*)(TVector3 pos) fisout) inherited
Definition at line 184 of file LKTracklet.cpp.
References LKTracklet::ExtrapolateByRatio(), LKVector3::kZ, and SetPoint().
Referenced by LKTracklet::FillTrajectory(), and LKTracklet::TrajectoryOnPlane().
FillTrajectory3D() [1/2]
void LKTracklet::FillTrajectory3D (TGraph2DErrors * graphTrack3D, LKVector3::Axis axis1, LKVector3::Axis axis2, LKVector3::Axis axis3) inherited
Definition at line 208 of file LKTracklet.cpp.
References LKTracklet::FillTrajectory3D().
FillTrajectory3D() [2/2]
void LKTracklet::FillTrajectory3D (TGraph2DErrors * graphTrack3D, LKVector3::Axis axis1, LKVector3::Axis axis2, LKVector3::Axis axis3, bool(*)(TVector3 pos) fisout) inherited
Definition at line 199 of file LKTracklet.cpp.
References LKTracklet::ExtrapolateByRatio(), LKVector3::kZ, and SetPoint().
Referenced by LKTracklet::FillTrajectory3D().
FinalizeHits()
void LKTracklet::FinalizeHits () virtual inherited
Definition at line 62 of file LKTracklet.cpp.
References LKTracklet::fHitArray, LKTracklet::fTrackID, next(), and LKTracklet::SetTrackID().
Fit()
virtual bool LKTracklet::Fit () inline virtual inherited
Reimplemented in LKHelixTrack, and LKLinearTrack.
Definition at line 110 of file LKTracklet.h.
FitHelix()
LKGeoHelix LKTracklet::FitHelix (LKVector3::Axis ref) virtual inherited
Definition at line 260 of file LKTracklet.cpp.
References LKTracklet::fHitArray, LKHitArray::FitHelix(), LKGeometry::GetRMS(), and LKTracklet::SetIsHelix().
FitLine()
LKGeoLine LKTracklet::FitLine () virtual inherited
Definition at line 244 of file LKTracklet.cpp.
References LKTracklet::fHitArray, LKHitArray::FitLine(), LKGeometry::GetRMS(), and LKTracklet::SetIsLine().
FitPlane()
LKGeoPlane LKTracklet::FitPlane () virtual inherited
Reimplemented in LKHelixTrack.
Definition at line 252 of file LKTracklet.cpp.
References LKTracklet::fHitArray, LKHitArray::FitPlane(), LKGeometry::GetRMS(), and LKTracklet::SetIsPlane().
GetChargeSum()
double LKTracklet::GetChargeSum () const inline inherited
Definition at line 90 of file LKTracklet.h.
References LKTracklet::fHitArray, and LKHitArray::GetW().
GetFitStatus()
LKTracklet::LKFitStatus LKTracklet::GetFitStatus () const inline inherited
Definition at line 35 of file LKTracklet.h.
References LKTracklet::fFitStatus.
GetFitStatusString()
TString LKTracklet::GetFitStatusString () const inline inherited
Definition at line 42 of file LKTracklet.h.
References LKTracklet::fFitStatus, LKTracklet::kBad, LKTracklet::kGenfitTrack, LKTracklet::kHelix, LKTracklet::kLine, and LKTracklet::kPlane.
Referenced by LKHelixTrack::Print().
GetHit()
LKHit * LKTracklet::GetHit (int idx) const inline inherited
Definition at line 84 of file LKTracklet.h.
References LKTracklet::fHitArray, and LKHitArray::GetHit().
GetHitArray()
LKHitArray * LKTracklet::GetHitArray () inline inherited
Definition at line 86 of file LKTracklet.h.
References LKTracklet::fHitArray.
Referenced by LKLinearTrack::CopyFrom(), TTHTTrackingTask::MakeTrack(), and TTHTtBeamTrackingTask::MakeTrack().
GetHitID()
int LKTracklet::GetHitID (int idx) const inline inherited
Definition at line 85 of file LKTracklet.h.
References LKTracklet::fHitIDArray.
Referenced by LKTracklet::RecoverHitArrayWithHitID(), and LKTracklet::RemoveHit().
GetHitIDArray()
std::vector< int > * LKTracklet::GetHitIDArray () inline inherited
Definition at line 87 of file LKTracklet.h.
References LKTracklet::fHitIDArray.
Referenced by LKLinearTrack::CopyFrom().
GetLengths()
vector< Double_t > * LKExtrapolatedTrack::GetLengths ()
Definition at line 68 of file LKExtrapolatedTrack.cpp.
References fLengths.
GetMean()
TVector3 LKTracklet::GetMean () const inline inherited
Definition at line 89 of file LKTracklet.h.
References LKTracklet::fHitArray, and LKHitArray::GetMean().
GetNumHits()
int LKTracklet::GetNumHits () const inline inherited
Definition at line 83 of file LKTracklet.h.
References LKTracklet::fHitIDArray.
Referenced by LKLinearTrack::Print().
GetNumPoints()
Int_t LKExtrapolatedTrack::GetNumPoints () const
Definition at line 70 of file LKExtrapolatedTrack.cpp.
References fPoints.
Referenced by PositionAtHead(), PositionAtTail(), TrackLength(), TrajectoryOnPlane(), and TrajectoryOnPlane().
GetParentID()
Int_t LKExtrapolatedTrack::GetParentID () const
Definition at line 65 of file LKExtrapolatedTrack.cpp.
References fParentID.
GetPDG()
int LKTracklet::GetPDG () const inline inherited
Definition at line 81 of file LKTracklet.h.
References LKTracklet::fPDG.
Referenced by LKLinearTrack::CopyFrom(), and LKEveTask::SelectTrack().
GetPoints()
vector< TVector3 > * LKExtrapolatedTrack::GetPoints ()
Definition at line 67 of file LKExtrapolatedTrack.cpp.
References fPoints.
GetTrackID()
Int_t LKExtrapolatedTrack::GetTrackID () const
Definition at line 66 of file LKExtrapolatedTrack.cpp.
References fTrackID.
IsBad()
bool LKTracklet::IsBad () const inline inherited
Definition at line 36 of file LKTracklet.h.
References LKTracklet::fFitStatus, and LKTracklet::kBad.
IsGenfitTrack()
bool LKTracklet::IsGenfitTrack () const inline inherited
Definition at line 40 of file LKTracklet.h.
References LKTracklet::fFitStatus, and LKTracklet::kGenfitTrack.
Referenced by LKHelixTrack::Momentum().
IsHelix()
bool LKTracklet::IsHelix () const inline inherited
Definition at line 39 of file LKTracklet.h.
References LKTracklet::fFitStatus, and LKTracklet::kHelix.
Referenced by LKHelixTrack::Momentum().
IsHoldingHits()
bool LKTracklet::IsHoldingHits () inherited
Definition at line 107 of file LKTracklet.cpp.
References LKTracklet::fHitArray, LKTracklet::fHitIDArray, and LKHitArray::GetNumHits().
IsLine()
bool LKTracklet::IsLine () const inline inherited
Definition at line 37 of file LKTracklet.h.
References LKTracklet::fFitStatus, and LKTracklet::kLine.
IsPlane()
bool LKTracklet::IsPlane () const inline inherited
Definition at line 38 of file LKTracklet.h.
References LKTracklet::fFitStatus, and LKTracklet::kPlane.
LengthAt()
virtual Double_t LKExtrapolatedTrack::LengthAt (TVector3 point) const inline virtual
Length at POCA from point, where tail=0, head=TrackLength.
Implements LKTracklet.
Definition at line 37 of file LKExtrapolatedTrack.h.
Momentum() [1/2]
virtual TVector3 LKTracklet::Momentum (double B = 0.5) const pure virtual inherited
Momentum of track at head.
Momentum() [2/2]
TVector3 LKExtrapolatedTrack::Momentum (Double_t B = 0.5) const virtual
Definition at line 30 of file LKExtrapolatedTrack.cpp.
PositionAtHead()
TVector3 LKExtrapolatedTrack::PositionAtHead () const virtual
Position at head of helix.
Implements LKTracklet.
Definition at line 31 of file LKExtrapolatedTrack.cpp.
References fPoints, and GetNumPoints().
PositionAtTail()
TVector3 LKExtrapolatedTrack::PositionAtTail () const virtual
Position at tail of helix.
Implements LKTracklet.
Definition at line 36 of file LKExtrapolatedTrack.cpp.
References fPoints, and GetNumPoints().
Print()
void LKExtrapolatedTrack::Print (Option_t * option = "") const virtual
Definition at line 25 of file LKExtrapolatedTrack.cpp.
References e_info, fParentID, fPoints, and fTrackID.
RecoverHitArrayWithHitID()
int LKTracklet::RecoverHitArrayWithHitID (TClonesArray * hitArray) virtual inherited
Be cautious on using this method! This method assumes that hit array was used to create track in same run and event This method will recover hit-array of track, which is removed before end of LILAK run. The track store hit IDs. The method will use this information to recover hit array.
Definition at line 87 of file LKTracklet.cpp.
References LKHitArray::AddHit(), LKTracklet::fHitArray, LKTracklet::fHitIDArray, and LKTracklet::GetHitID().
RecoverHitArrayWithTrackID()
int LKTracklet::RecoverHitArrayWithTrackID (TClonesArray * hitArray) virtual inherited
Be cautious on using this method! This method assumes that hit array and track were cretaed in same run and event This method will recover hit-array of track, which is removed before end of LILAK run. The track ID is set in hit container. The method will use this information to recover hit array.
Definition at line 72 of file LKTracklet.cpp.
References LKHitArray::AddHit(), LKTracklet::fHitArray, and LKTracklet::fTrackID.
RemoveHit()
void LKTracklet::RemoveHit (LKHit * hit) virtual inherited
Definition at line 49 of file LKTracklet.cpp.
References LKTracklet::fHitArray, LKTracklet::fHitIDArray, LKTracklet::GetHitID(), and LKHitArray::RemoveHit().
SetFitStatus()
void LKTracklet::SetFitStatus (LKFitStatus value) inline inherited
Definition at line 28 of file LKTracklet.h.
References LKTracklet::fFitStatus.
SetIsBad()
void LKTracklet::SetIsBad () inline inherited
Definition at line 29 of file LKTracklet.h.
References LKTracklet::fFitStatus, and LKTracklet::kBad.
SetIsGenfitTrack()
void LKTracklet::SetIsGenfitTrack () inline inherited
Definition at line 33 of file LKTracklet.h.
References LKTracklet::fFitStatus, and LKTracklet::kGenfitTrack.
SetIsHelix()
void LKTracklet::SetIsHelix () inline inherited
Definition at line 32 of file LKTracklet.h.
References LKTracklet::fFitStatus, and LKTracklet::kHelix.
Referenced by LKHelixTrack::Fit(), and LKTracklet::FitHelix().
SetIsLine()
void LKTracklet::SetIsLine () inline inherited
Definition at line 30 of file LKTracklet.h.
References LKTracklet::fFitStatus, and LKTracklet::kLine.
Referenced by LKTracklet::FitLine(), and LKHelixTrack::FitPlane().
SetIsPlane()
void LKTracklet::SetIsPlane () inline inherited
Definition at line 31 of file LKTracklet.h.
References LKTracklet::fFitStatus, and LKTracklet::kPlane.
Referenced by LKHelixTrack::FitPlane(), and LKTracklet::FitPlane().
SetParentID() [1/2]
void LKTracklet::SetParentID (int val) inline inherited
Definition at line 76 of file LKTracklet.h.
References LKTracklet::fParentID.
SetParentID() [2/2]
void LKExtrapolatedTrack::SetParentID (Int_t id)
Definition at line 47 of file LKExtrapolatedTrack.cpp.
References fParentID.
SetPDG()
void LKTracklet::SetPDG (int val) inline inherited
Definition at line 77 of file LKTracklet.h.
References LKTracklet::fPDG.
SetTrackID() [1/2]
void LKTracklet::SetTrackID (int val) inline inherited
Definition at line 75 of file LKTracklet.h.
References LKTracklet::fTrackID.
Referenced by LKTracklet::AddHit(), and LKTracklet::FinalizeHits().
SetTrackID() [2/2]
void LKExtrapolatedTrack::SetTrackID (Int_t id)
Definition at line 48 of file LKExtrapolatedTrack.cpp.
References fTrackID.
SortHits()
void LKTracklet::SortHits (bool increasing = true) virtual inherited
Reimplemented in LKHelixTrack.
Definition at line 268 of file LKTracklet.cpp.
References LKTracklet::fHitArray, LKHit::GetPosition(), and next().
Referenced by LKTracklet::Continuity().
TrackLength()
Double_t LKExtrapolatedTrack::TrackLength () const virtual
Length of track calculated from head to tail.
Implements LKTracklet.
Definition at line 41 of file LKExtrapolatedTrack.cpp.
References fLengths, and GetNumPoints().
TrajectoryOnPlane() [1/5]
TGraphErrors * LKTracklet::TrajectoryOnPlane (LKDetectorPlane * plane, double scale = 1) virtual inherited
Definition at line 179 of file LKTracklet.cpp.
References LKDetectorPlane::GetAxis1(), LKDetectorPlane::GetAxis2(), and LKTracklet::TrajectoryOnPlane().
TrajectoryOnPlane() [2/5]
TGraphErrors * LKTracklet::TrajectoryOnPlane (LKVector3::Axis axis1, LKVector3::Axis axis2, bool(*)(TVector3 pos) fisout, double scale = 1) virtual inherited
Definition at line 160 of file LKTracklet.cpp.
References LKTracklet::FillTrajectory(), and LKTracklet::fTrajectoryOnPlane.
Referenced by LKTracklet::TrajectoryOnPlane(), and LKTracklet::TrajectoryOnPlane().
TrajectoryOnPlane() [3/5]
TGraphErrors * LKExtrapolatedTrack::TrajectoryOnPlane (LKVector3::Axis axis1, LKVector3::Axis axis2, bool(*)(TVector3 pos) fisout, Double_t scale = 1) virtual
Definition at line 218 of file LKExtrapolatedTrack.cpp.
References fPoints, LKTracklet::fTrajectoryOnPlane, GetNumPoints(), LKVector3::kZ, and SetPoint().
TrajectoryOnPlane() [4/5]
TGraphErrors * LKTracklet::TrajectoryOnPlane (LKVector3::Axis axis1, LKVector3::Axis axis2, double scale = 1) virtual inherited
Definition at line 173 of file LKTracklet.cpp.
References LKTracklet::TrajectoryOnPlane().
TrajectoryOnPlane() [5/5]
TGraphErrors * LKExtrapolatedTrack::TrajectoryOnPlane (LKVector3::Axis axis1, LKVector3::Axis axis2, Double_t scale = 1) virtual
Definition at line 198 of file LKExtrapolatedTrack.cpp.
References fPoints, LKTracklet::fTrajectoryOnPlane, GetNumPoints(), LKVector3::kZ, and SetPoint().
Member Data Documentation
fFitStatus
LKFitStatus LKTracklet::fFitStatus protected inherited
One of kBad, kHelix and kLine.
Definition at line 61 of file LKTracklet.h.
Referenced by LKHelixTrack::Clear(), LKHelixTrack::Copy(), LKTracklet::GetFitStatus(), LKTracklet::GetFitStatusString(), LKTracklet::IsBad(), LKTracklet::IsGenfitTrack(), LKTracklet::IsHelix(), LKTracklet::IsLine(), LKTracklet::IsPlane(), LKHelixTrack::Print(), LKTracklet::SetFitStatus(), LKTracklet::SetIsBad(), LKTracklet::SetIsGenfitTrack(), LKTracklet::SetIsHelix(), LKTracklet::SetIsLine(), and LKTracklet::SetIsPlane().
fHitArray
LKHitArray LKTracklet::fHitArray protected inherited
Definition at line 56 of file LKTracklet.h.
Referenced by LKTracklet::AddHit(), ClassImp(), LKTracklet::ClearHits(), LKHelixTrack::Continuity(), LKTracklet::Continuity(), LKHelixTrack::Copy(), LKLinearTrack::CopyFrom(), LKTracklet::FinalizeHits(), LKHelixTrack::Fit(), LKLinearTrack::Fit(), LKTracklet::FitHelix(), LKTracklet::FitLine(), LKHelixTrack::FitPlane(), LKTracklet::FitPlane(), LKTracklet::GetChargeSum(), LKTracklet::GetHit(), LKTracklet::GetHitArray(), LKTracklet::GetMean(), LKTracklet::IsHoldingHits(), LKHelixTrack::PerpLine(), LKHelixTrack::PerpPlane(), LKHelixTrack::Print(), LKLinearTrack::Print(), LKTracklet::RecoverHitArrayWithHitID(), LKTracklet::RecoverHitArrayWithTrackID(), LKTracklet::RemoveHit(), LKLinearTrack::SetLine(), LKHelixTrack::SortHits(), and LKTracklet::SortHits().
fHitIDArray
vector<int> LKTracklet::fHitIDArray protected inherited
Definition at line 57 of file LKTracklet.h.
Referenced by LKTracklet::AddHit(), ClassImp(), LKTracklet::ClearHits(), LKLinearTrack::CopyFrom(), LKTracklet::GetHitID(), LKTracklet::GetHitIDArray(), LKTracklet::GetNumHits(), LKTracklet::IsHoldingHits(), LKLinearTrack::Print(), LKTracklet::RecoverHitArrayWithHitID(), and LKTracklet::RemoveHit().
fLengths
vector<Double_t> LKExtrapolatedTrack::fLengths private
Definition at line 62 of file LKExtrapolatedTrack.h.
Referenced by AddPoint(), ExtrapolateByLength(), GetLengths(), and TrackLength().
fParentID
Int_t LKExtrapolatedTrack::fParentID private
Definition at line 58 of file LKExtrapolatedTrack.h.
Referenced by Clear(), GetParentID(), Print(), and SetParentID().
fPDG
int LKTracklet::fPDG = -1 protected inherited
Definition at line 54 of file LKTracklet.h.
Referenced by ClassImp(), LKLinearTrack::CopyFrom(), LKTracklet::GetPDG(), LKMCTrack::Print(), LKMCTrack::SetMCTrack(), LKTracklet::SetPDG(), and LKMCTrack::TrajectoryOnPlane().
fPoints
vector<TVector3> LKExtrapolatedTrack::fPoints private
Definition at line 61 of file LKExtrapolatedTrack.h.
Referenced by AddPoint(), Clear(), ExtrapolateByLength(), ExtrapolateHead(), ExtrapolateTail(), ExtrapolateTo(), GetNumPoints(), GetPoints(), PositionAtHead(), PositionAtTail(), Print(), TrajectoryOnPlane(), and TrajectoryOnPlane().
fTrackID
Int_t LKExtrapolatedTrack::fTrackID private
Definition at line 59 of file LKExtrapolatedTrack.h.
Referenced by Clear(), GetTrackID(), Print(), and SetTrackID().
fTrajectoryOnPlane
TGraphErrors* LKTracklet::fTrajectoryOnPlane = nullptr protected inherited
Definition at line 59 of file LKTracklet.h.
Referenced by LKMCTrack::TrajectoryOnPlane(), LKTracklet::TrajectoryOnPlane(), TrajectoryOnPlane(), and TrajectoryOnPlane().
The documentation for this class was generated from the following files:
LKExtrapolatedTrack.h
LKExtrapolatedTrack.cpp