lilak: LKParameter Class Reference
LKParameter Class Reference
#include <LKParameter.h>
Public Member Functions
bool CheckTypeAxis (int i=-1) const
bool CheckTypeBool (int i=-1) const
bool CheckTypeColor (int i=-1) const
bool CheckTypeDouble (int i=-1) const
bool CheckTypeInt (int i=-1) const
bool CheckTypeLong (int i=-1) const
bool CheckTypeString (int i=-1) const
bool CheckTypeV3 () const
virtual void Clear (Option_t *option="")
virtual Int_t Compare (const TObject *obj) const
axis_t GetAxis (int i=-1) const
Get parameter in LKVector3::Axis.
bool GetBool (int i=-1) const
Get parameter in bool.
int GetColor (int i=-1) const
Get parameter in Color_t.
TString GetComment () const
int GetCompare () const
double GetDouble (int i=-1) const
Get parameter in double.
TString GetGroup () const
TString GetGroup (int ith) const
int GetInt (int i=-1) const
Get parameter in int.
TString GetLine (TString option="c") const
Long64_t GetLong (int i=-1) const
Get parameter in long.
TString GetMainName () const
int GetN () const
TString GetRaw () const
double GetSize (int i=-1) const
TString GetString (int i=-1) const
Get parameter in TString.
int GetType () const
TString GetTypeHeader () const
TVector3 GetV3 () const
Get parameter in TVector3.
TString GetValue () const
std::vector< bool > GetVBool () const
std::vector< int > GetVColor () const
std::vector< double > GetVDouble () const
std::vector< int > GetVInt () const
std::vector< double > GetVSize () const
std::vector< TString > GetVString () const
std::vector< int > GetVWidth () const
int GetWidth (int i=-1) const
double GetX () const
double GetY () const
double GetZ () const
bool IsConditional () const
bool IsInputFile () const
bool IsLegacy () const
bool IsLineComment () const
bool IsMultiple () const
bool IsRewrite () const
virtual Bool_t IsSortable () const
bool IsStandard () const
bool IsTemporary () const
LKParameter ()
LKParameter (int parameterType)
LKParameter (TString name, TString raw, TString value="", TString comment="", int parameterType=0, int compare=-1)
void NotStandard ()
virtual void Print (Option_t *option="") const
void ResetType ()
void SetCompare (int compare)
void SetIsConditional ()
void SetIsInputFile ()
void SetIsLegacy ()
void SetIsLineComment ()
void SetIsMultiple ()
void SetIsRewrite ()
void SetIsStandard ()
void SetIsTemporary ()
void SetLineComment (TString comment)
void SetPar (TString name, TString raw, TString value, TString comment, int parameterType=1, int compare=-1)
void SetType (TString type)
void SetValue (TString value)
void SetValueAt (int i, bool value)
Set bool parameter at i.
void SetValueAt (int i, double value)
Set double parameter at i.
void SetValueAt (int i, int value)
Set int parameter at i.
void SetValueAt (int i, Long64_t value)
Set long parameter at i.
void SetValueAt (int i, TString value)
Set TString parameter at i.
virtual ~LKParameter ()
Private Member Functions
bool CheckFormulaValidity (TString formula, bool isInt=false) const
void ProcessTypeError (TString type, TString value) const
Private Attributes
TString fComment
int fCompare = 99
TString fGroup
group of parameter
TString fMainName
group of parameter
int fNumValues = 0
int fType = 1
TString fValue
configured value
std::vector< TString > fValueArray
Detailed Description
Definition at line 14 of file LKParameter.h.
Constructor & Destructor Documentation
LKParameter() [1/3]
LKParameter::LKParameter ()
Definition at line 9 of file LKParameter.cpp.
LKParameter() [2/3]
LKParameter::LKParameter (TString name, TString raw, TString value = "", TString comment = "", int parameterType = 0, int compare = -1)
Definition at line 19 of file LKParameter.cpp.
References SetPar().
LKParameter() [3/3]
LKParameter::LKParameter (int parameterType)
Definition at line 13 of file LKParameter.cpp.
References Clear(), and fType.
~LKParameter()
LKParameter::~LKParameter () virtual
Definition at line 24 of file LKParameter.cpp.
Member Function Documentation
CheckFormulaValidity()
bool LKParameter::CheckFormulaValidity (TString formula, bool isInt = false) const private
Definition at line 414 of file LKParameter.cpp.
Referenced by CheckTypeColor(), CheckTypeDouble(), CheckTypeInt(), CheckTypeLong(), GetColor(), GetDouble(), and GetInt().
CheckTypeAxis()
bool LKParameter::CheckTypeAxis (int i = -1) const
Definition at line 220 of file LKParameter.cpp.
References fValue, and fValueArray.
CheckTypeBool()
bool LKParameter::CheckTypeBool (int i = -1) const
Definition at line 170 of file LKParameter.cpp.
References fValue, and fValueArray.
CheckTypeColor()
bool LKParameter::CheckTypeColor (int i = -1) const
Definition at line 192 of file LKParameter.cpp.
References CheckFormulaValidity(), fValue, and fValueArray.
CheckTypeDouble()
bool LKParameter::CheckTypeDouble (int i = -1) const
Definition at line 179 of file LKParameter.cpp.
References CheckFormulaValidity(), fValue, and fValueArray.
Referenced by CheckTypeV3().
CheckTypeInt()
bool LKParameter::CheckTypeInt (int i = -1) const
Definition at line 150 of file LKParameter.cpp.
References CheckFormulaValidity(), fValue, and fValueArray.
CheckTypeLong()
bool LKParameter::CheckTypeLong (int i = -1) const
Definition at line 160 of file LKParameter.cpp.
References CheckFormulaValidity(), fValue, and fValueArray.
CheckTypeString()
bool LKParameter::CheckTypeString (int i = -1) const
Definition at line 190 of file LKParameter.cpp.
CheckTypeV3()
bool LKParameter::CheckTypeV3 () const
Definition at line 239 of file LKParameter.cpp.
References CheckTypeDouble().
Clear()
void LKParameter::Clear (Option_t * option = "") virtual
Definition at line 99 of file LKParameter.cpp.
References fComment, fGroup, fMainName, fNumValues, fValue, fValueArray, and SetIsStandard().
Referenced by LKParameter(), SetLineComment(), and SetPar().
Compare()
Int_t LKParameter::Compare (const TObject * obj) const virtual
Definition at line 116 of file LKParameter.cpp.
References fCompare, fGroup, GetCompare(), and GetGroup().
GetAxis()
axis_t LKParameter::GetAxis (int i = -1) const
Get parameter in LKVector3::Axis.
Definition at line 334 of file LKParameter.cpp.
References fValue, fValueArray, LKVector3::kI, LKVector3::kJ, LKVector3::kK, LKVector3::kMI, LKVector3::kMJ, LKVector3::kMK, LKVector3::kMX, LKVector3::kMY, LKVector3::kMZ, LKVector3::kNon, LKVector3::kX, LKVector3::kY, and LKVector3::kZ.
GetBool()
bool LKParameter::GetBool (int i = -1) const
Get parameter in bool.
Definition at line 270 of file LKParameter.cpp.
References fValue, fValueArray, and ProcessTypeError().
Referenced by GetVBool().
GetColor()
int LKParameter::GetColor (int i = -1) const
Get parameter in Color_t.
Definition at line 303 of file LKParameter.cpp.
References CheckFormulaValidity(), fValue, fValueArray, and ProcessTypeError().
GetComment()
TString LKParameter::GetComment () const inline
Definition at line 35 of file LKParameter.h.
References fComment.
Referenced by LKParameterContainer::AddParameterContainer(), and LKParameterContainer::CloneParameterContainer().
GetCompare()
int LKParameter::GetCompare () const inline
Definition at line 84 of file LKParameter.h.
References fCompare.
Referenced by Compare().
GetDouble()
double LKParameter::GetDouble (int i = -1) const
Get parameter in double.
Definition at line 283 of file LKParameter.cpp.
References CheckFormulaValidity(), fValue, fValueArray, and ProcessTypeError().
Referenced by GetSize(), GetV3(), GetVDouble(), GetX(), GetY(), and GetZ().
GetGroup() [1/2]
TString LKParameter::GetGroup () const inline
Definition at line 33 of file LKParameter.h.
References fGroup.
Referenced by Compare(), and LKParameterContainer::CreateGroupContainer().
GetGroup() [2/2]
TString LKParameter::GetGroup (int ith) const
Definition at line 420 of file LKParameter.cpp.
GetInt()
int LKParameter::GetInt (int i = -1) const
Get parameter in int.
Definition at line 247 of file LKParameter.cpp.
References CheckFormulaValidity(), fValue, fValueArray, and ProcessTypeError().
Referenced by GetVInt(), and GetWidth().
GetLine()
TString LKParameter::GetLine (TString option = "c") const
Definition at line 444 of file LKParameter.cpp.
References fComment, fValue, and IsLineComment().
Referenced by LKParameterContainer::CloneParameterContainer(), LKParameterContainer::FindPar(), LKParameterContainer::FindParFree(), Print(), LKParameterContainer::Print(), and LKG4RunManager::Run().
GetLong()
Long64_t LKParameter::GetLong (int i = -1) const
Get parameter in long.
Definition at line 259 of file LKParameter.cpp.
References fValue, fValueArray, and ProcessTypeError().
GetMainName()
TString LKParameter::GetMainName () const inline
Definition at line 34 of file LKParameter.h.
References fMainName.
GetN()
int LKParameter::GetN () const inline
Definition at line 38 of file LKParameter.h.
References fNumValues.
Referenced by GetVBool(), GetVDouble(), GetVInt(), and GetVString().
GetRaw()
TString LKParameter::GetRaw () const inline
Definition at line 36 of file LKParameter.h.
Referenced by LKParameterContainer::AddParameterContainer().
GetSize()
double LKParameter::GetSize (int i = -1) const inline
Definition at line 69 of file LKParameter.h.
References GetDouble().
GetString()
TString LKParameter::GetString (int i = -1) const
Get parameter in TString.
Definition at line 295 of file LKParameter.cpp.
References fValue, and fValueArray.
Referenced by GetVString().
GetType()
int LKParameter::GetType () const inline
Definition at line 39 of file LKParameter.h.
References fType.
Referenced by LKParameterContainer::AddPar(), and LKParameterContainer::AddParameterContainer().
GetTypeHeader()
TString LKParameter::GetTypeHeader () const inline
Definition at line 136 of file LKParameter.h.
References IsConditional(), IsInputFile(), and IsLineComment().
GetV3()
TVector3 LKParameter::GetV3 () const
Get parameter in TVector3.
Definition at line 355 of file LKParameter.cpp.
References GetDouble().
GetValue()
TString LKParameter::GetValue () const inline
Definition at line 37 of file LKParameter.h.
References fValue.
Referenced by LKParameterContainer::AddParameterContainer().
GetVBool()
std::vector< bool > LKParameter::GetVBool () const
Definition at line 360 of file LKParameter.cpp.
References GetBool(), and GetN().
GetVColor()
std::vector< int > LKParameter::GetVColor () const inline
Definition at line 80 of file LKParameter.h.
References GetVInt().
GetVDouble()
std::vector< double > LKParameter::GetVDouble () const
Definition at line 384 of file LKParameter.cpp.
References GetDouble(), and GetN().
Referenced by GetVSize().
GetVInt()
std::vector< int > LKParameter::GetVInt () const
Definition at line 372 of file LKParameter.cpp.
References GetInt(), and GetN().
Referenced by GetVColor(), and GetVWidth().
GetVSize()
std::vector< double > LKParameter::GetVSize () const inline
Definition at line 81 of file LKParameter.h.
References GetVDouble().
GetVString()
std::vector< TString > LKParameter::GetVString () const
Definition at line 396 of file LKParameter.cpp.
References GetN(), and GetString().
GetVWidth()
std::vector< int > LKParameter::GetVWidth () const inline
Definition at line 79 of file LKParameter.h.
References GetVInt().
GetWidth()
int LKParameter::GetWidth (int i = -1) const inline
Definition at line 68 of file LKParameter.h.
References GetInt().
GetX()
double LKParameter::GetX () const inline
Definition at line 70 of file LKParameter.h.
References GetDouble().
GetY()
double LKParameter::GetY () const inline
Definition at line 71 of file LKParameter.h.
References GetDouble().
GetZ()
double LKParameter::GetZ () const inline
Definition at line 72 of file LKParameter.h.
References GetDouble().
IsConditional()
bool LKParameter::IsConditional () const inline
Definition at line 133 of file LKParameter.h.
References fType.
Referenced by GetTypeHeader().
IsInputFile()
bool LKParameter::IsInputFile () const inline
Definition at line 132 of file LKParameter.h.
References fType.
Referenced by GetTypeHeader().
IsLegacy()
bool LKParameter::IsLegacy () const inline
Definition at line 128 of file LKParameter.h.
References fType.
IsLineComment()
bool LKParameter::IsLineComment () const inline
Definition at line 134 of file LKParameter.h.
References fType.
Referenced by LKParameterContainer::CloneParameterContainer(), GetLine(), and GetTypeHeader().
IsMultiple()
bool LKParameter::IsMultiple () const inline
Definition at line 130 of file LKParameter.h.
References fType.
IsRewrite()
bool LKParameter::IsRewrite () const inline
Definition at line 129 of file LKParameter.h.
References fType.
IsSortable()
virtual Bool_t LKParameter::IsSortable () const inline virtual
Definition at line 25 of file LKParameter.h.
IsStandard()
bool LKParameter::IsStandard () const inline
Definition at line 127 of file LKParameter.h.
References fType.
IsTemporary()
bool LKParameter::IsTemporary () const inline
Definition at line 131 of file LKParameter.h.
References fType.
Referenced by LKParameterContainer::CloneParameterContainer().
NotStandard()
void LKParameter::NotStandard () inline
Definition at line 103 of file LKParameter.h.
References fType.
Referenced by SetIsConditional(), SetIsInputFile(), SetIsLegacy(), SetIsLineComment(), SetIsMultiple(), SetIsRewrite(), SetIsStandard(), and SetIsTemporary().
Print()
void LKParameter::Print (Option_t * option = "") const virtual
Definition at line 111 of file LKParameter.cpp.
References e_cout, and GetLine().
ProcessTypeError()
void LKParameter::ProcessTypeError (TString type, TString value) const private
Definition at line 408 of file LKParameter.cpp.
References e_error.
Referenced by GetBool(), GetColor(), GetDouble(), GetInt(), and GetLong().
ResetType()
void LKParameter::ResetType () inline
Definition at line 104 of file LKParameter.h.
References fType.
SetCompare()
void LKParameter::SetCompare (int compare) inline
Definition at line 83 of file LKParameter.h.
References fCompare.
SetIsConditional()
void LKParameter::SetIsConditional () inline
Definition at line 124 of file LKParameter.h.
References fType, and NotStandard().
Referenced by LKParameterContainer::AddPar(), and SetType().
SetIsInputFile()
void LKParameter::SetIsInputFile () inline
Definition at line 123 of file LKParameter.h.
References fType, and NotStandard().
Referenced by SetType().
SetIsLegacy()
void LKParameter::SetIsLegacy () inline
Definition at line 119 of file LKParameter.h.
References fType, and NotStandard().
Referenced by SetType().
SetIsLineComment()
void LKParameter::SetIsLineComment () inline
Definition at line 125 of file LKParameter.h.
References fType, and NotStandard().
Referenced by SetLineComment(), and SetType().
SetIsMultiple()
void LKParameter::SetIsMultiple () inline
Definition at line 121 of file LKParameter.h.
References fType, and NotStandard().
Referenced by LKParameterContainer::AddPar(), and SetType().
SetIsRewrite()
void LKParameter::SetIsRewrite () inline
Definition at line 120 of file LKParameter.h.
References fType, and NotStandard().
Referenced by LKParameterContainer::AddPar(), and SetType().
SetIsStandard()
void LKParameter::SetIsStandard () inline
Definition at line 118 of file LKParameter.h.
References fType, and NotStandard().
Referenced by Clear(), and SetType().
SetIsTemporary()
void LKParameter::SetIsTemporary () inline
Definition at line 122 of file LKParameter.h.
References fType, and NotStandard().
Referenced by LKParameterContainer::AddPar(), and SetType().
SetLineComment()
void LKParameter::SetLineComment (TString comment)
Definition at line 28 of file LKParameter.cpp.
References Clear(), fComment, and SetIsLineComment().
SetPar()
void LKParameter::SetPar (TString name, TString raw, TString value, TString comment, int parameterType = 1, int compare = -1)
Definition at line 35 of file LKParameter.cpp.
References Clear(), fComment, fCompare, fGroup, fMainName, fType, fValue, and SetValue().
Referenced by LKParameter().
SetType()
void LKParameter::SetType (TString type) inline
Definition at line 106 of file LKParameter.h.
References SetIsConditional(), SetIsInputFile(), SetIsLegacy(), SetIsLineComment(), SetIsMultiple(), SetIsRewrite(), SetIsStandard(), and SetIsTemporary().
SetValue()
void LKParameter::SetValue (TString value)
Definition at line 61 of file LKParameter.cpp.
References fNumValues, fValue, and fValueArray.
Referenced by SetPar(), and SetValueAt().
SetValueAt() [1/5]
void LKParameter::SetValueAt (int i, bool value) inline
Set bool parameter at i.
Definition at line 55 of file LKParameter.h.
References SetValueAt().
Referenced by SetValueAt().
SetValueAt() [2/5]
void LKParameter::SetValueAt (int i, double value) inline
Set double parameter at i.
Definition at line 56 of file LKParameter.h.
References SetValueAt().
Referenced by SetValueAt().
SetValueAt() [3/5]
void LKParameter::SetValueAt (int i, int value) inline
Set int parameter at i.
Definition at line 53 of file LKParameter.h.
References SetValueAt().
Referenced by SetValueAt().
SetValueAt() [4/5]
void LKParameter::SetValueAt (int i, Long64_t value) inline
Set long parameter at i.
Definition at line 54 of file LKParameter.h.
References SetValueAt().
Referenced by SetValueAt().
SetValueAt() [5/5]
void LKParameter::SetValueAt (int i, TString value)
Set TString parameter at i.
Definition at line 75 of file LKParameter.cpp.
References fValueArray, and SetValue().
Member Data Documentation
fComment
TString LKParameter::fComment private
Definition at line 95 of file LKParameter.h.
Referenced by Clear(), GetComment(), GetLine(), SetLineComment(), and SetPar().
fCompare
int LKParameter::fCompare = 99 private
Definition at line 100 of file LKParameter.h.
Referenced by Compare(), GetCompare(), SetCompare(), and SetPar().
fGroup
TString LKParameter::fGroup private
group of parameter
Definition at line 91 of file LKParameter.h.
Referenced by Clear(), Compare(), GetGroup(), and SetPar().
fMainName
TString LKParameter::fMainName private
group of parameter
Definition at line 92 of file LKParameter.h.
Referenced by Clear(), GetMainName(), and SetPar().
fNumValues
int LKParameter::fNumValues = 0 private
Definition at line 96 of file LKParameter.h.
Referenced by Clear(), GetN(), and SetValue().
fType
int LKParameter::fType = 1 private
Definition at line 98 of file LKParameter.h.
Referenced by GetType(), IsConditional(), IsInputFile(), IsLegacy(), IsLineComment(), IsMultiple(), IsRewrite(), IsStandard(), IsTemporary(), LKParameter(), NotStandard(), ResetType(), SetIsConditional(), SetIsInputFile(), SetIsLegacy(), SetIsLineComment(), SetIsMultiple(), SetIsRewrite(), SetIsStandard(), SetIsTemporary(), and SetPar().
fValue
TString LKParameter::fValue private
configured value
Definition at line 94 of file LKParameter.h.
Referenced by CheckTypeAxis(), CheckTypeBool(), CheckTypeColor(), CheckTypeDouble(), CheckTypeInt(), CheckTypeLong(), Clear(), GetAxis(), GetBool(), GetColor(), GetDouble(), GetInt(), GetLine(), GetLong(), GetString(), GetValue(), SetPar(), and SetValue().
fValueArray
std::vector<TString> LKParameter::fValueArray private
Definition at line 97 of file LKParameter.h.
Referenced by CheckTypeAxis(), CheckTypeBool(), CheckTypeColor(), CheckTypeDouble(), CheckTypeInt(), CheckTypeLong(), Clear(), GetAxis(), GetBool(), GetColor(), GetDouble(), GetInt(), GetLong(), GetString(), SetValue(), and SetValueAt().
The documentation for this class was generated from the following files:
LKParameter.h
LKParameter.cpp