LILAK: LKGeoBoxStack Class Reference
LKGeoBoxStack Class Reference
#include <LKGeoBoxStack.h>
Public Member Functions
TMultiGraph * DrawStackGraph (axis_t a1=LKVector3::kNon, axis_t a2=LKVector3::kNon)
TH2D * DrawStackHist (TString name="", TString title="", axis_t a1=LKVector3::kNon, axis_t a2=LKVector3::kNon)
TH2Poly * DrawStackHistPoly (TString name="", TString title="", axis_t a1=LKVector3::kNon, axis_t a2=LKVector3::kNon)
Int_t FindBoxIndex (Double_t x, Double_t y, Double_t z) const
Int_t FindBoxIndex (TVector3 pos) const
LKGeoBox GetBox (Int_t idx) const
virtual TVector3 GetCenter () const
axis_t GetFaceAxis () const
Double_t GetFaceAxisCenter () const
Double_t GetFaceAxisDisplacement () const
Double_t GetFaceAxisMax () const
Double_t GetFaceAxisMin () const
Double_t GetLongAxisCenter () const
Double_t GetLongAxisDisplacement () const
Double_t GetLongAxisMax () const
Double_t GetLongAxisMin () const
axis_t GetStackAxis () const
Double_t GetStackAxisCenter () const
Double_t GetStackAxisDisplacement () const
Double_t GetStackAxisMax () const
Double_t GetStackAxisMin () const
LKGeoBoxStack ()
LKGeoBoxStack (Double_t x, Double_t y, Double_t z, Double_t dx, Double_t dy, Double_t dz, Int_t n, axis_t as, axis_t af=LKVector3::kZ)
virtual void Print (Option_t *option="") const
void SetBoxStack (Double_t x, Double_t y, Double_t z, Double_t dx, Double_t dy, Double_t dz, Int_t n, axis_t as, axis_t af=LKVector3::kZ)
virtual ~LKGeoBoxStack ()
Public Member Functions inherited from LKGeometry
Double_t GetRMS () const
LKGeometry ()
void SetRMS (Double_t val)
virtual ~LKGeometry ()
Protected Attributes
Double_t fdX
Double_t fdY
Double_t fdZ
axis_t fFaceAxis
Int_t fNumStacks
axis_t fStackAxis
Double_t fX
Double_t fY
Double_t fZ
Protected Attributes inherited from LKGeometry
Double_t fRMS = -1
Detailed Description
Definition at line 16 of file LKGeoBoxStack.h.
Constructor & Destructor Documentation
LKGeoBoxStack() [1/2]
LKGeoBoxStack::LKGeoBoxStack ()
LKGeoBoxStack() [2/2]
LKGeoBoxStack::LKGeoBoxStack (Double_t x, Double_t y, Double_t z, Double_t dx, Double_t dy, Double_t dz, Int_t n, axis_t as, axis_t af = LKVector3::kZ)
Definition at line 11 of file LKGeoBoxStack.cpp.
References SetBoxStack().
~LKGeoBoxStack()
virtual LKGeoBoxStack::~LKGeoBoxStack () inline virtual
Definition at line 24 of file LKGeoBoxStack.h.
Member Function Documentation
DrawStackGraph()
TMultiGraph * LKGeoBoxStack::DrawStackGraph (axis_t a1 = LKVector3::kNon, axis_t a2 = LKVector3::kNon)
Definition at line 72 of file LKGeoBoxStack.cpp.
References LKGeoBox::Draw2DBox(), fFaceAxis, fNumStacks, fStackAxis, GetBox(), LKVector3::IsNegative(), and LKVector3::kNon.
DrawStackHist()
TH2D * LKGeoBoxStack::DrawStackHist (TString name = "", TString title = "", axis_t a1 = LKVector3::kNon, axis_t a2 = LKVector3::kNon)
Definition at line 92 of file LKGeoBoxStack.cpp.
References LKVector3::At(), LKVector3::AxisName(), fdX, fdY, fdZ, fFaceAxis, fNumStacks, fStackAxis, fX, fY, fZ, GetStackAxisMax(), GetStackAxisMin(), LKVector3::IsNegative(), and LKVector3::kNon.
DrawStackHistPoly()
TH2Poly * LKGeoBoxStack::DrawStackHistPoly (TString name = "", TString title = "", axis_t a1 = LKVector3::kNon, axis_t a2 = LKVector3::kNon)
Definition at line 137 of file LKGeoBoxStack.cpp.
References LKVector3::AxisName(), fFaceAxis, fNumStacks, fStackAxis, GetBox(), LKGeoBox::GetFace(), LKVector3::IsNegative(), and LKVector3::kNon.
FindBoxIndex() [1/2]
Int_t LKGeoBoxStack::FindBoxIndex (Double_t x, Double_t y, Double_t z) const
Definition at line 171 of file LKGeoBoxStack.cpp.
References fNumStacks, and GetBox().
FindBoxIndex() [2/2]
Int_t LKGeoBoxStack::FindBoxIndex (TVector3 pos) const
Definition at line 166 of file LKGeoBoxStack.cpp.
References FindBoxIndex().
Referenced by FindBoxIndex().
GetBox()
LKGeoBox LKGeoBoxStack::GetBox (Int_t idx) const
Definition at line 63 of file LKGeoBoxStack.cpp.
References LKVector3::AddAt(), fdX, fdY, fdZ, fNumStacks, fStackAxis, fX, fY, fZ, and GetStackAxisDisplacement().
Referenced by DrawStackGraph(), DrawStackHistPoly(), and FindBoxIndex().
GetCenter()
TVector3 LKGeoBoxStack::GetCenter () const virtual
Definition at line 27 of file LKGeoBoxStack.cpp.
References fX, fY, and fZ.
GetFaceAxis()
axis_t LKGeoBoxStack::GetFaceAxis () const
Definition at line 45 of file LKGeoBoxStack.cpp.
References fFaceAxis.
GetFaceAxisCenter()
Double_t LKGeoBoxStack::GetFaceAxisCenter () const
Definition at line 56 of file LKGeoBoxStack.cpp.
References LKVector3::At(), fFaceAxis, fX, fY, and fZ.
Referenced by GetFaceAxisMax(), and GetFaceAxisMin().
GetFaceAxisDisplacement()
Double_t LKGeoBoxStack::GetFaceAxisDisplacement () const
Definition at line 60 of file LKGeoBoxStack.cpp.
References LKVector3::At(), fdX, fdY, fdZ, and fFaceAxis.
Referenced by GetFaceAxisMax(), and GetFaceAxisMin().
GetFaceAxisMax()
Double_t LKGeoBoxStack::GetFaceAxisMax () const
Definition at line 48 of file LKGeoBoxStack.cpp.
References GetFaceAxisCenter(), and GetFaceAxisDisplacement().
GetFaceAxisMin()
Double_t LKGeoBoxStack::GetFaceAxisMin () const
Definition at line 52 of file LKGeoBoxStack.cpp.
References GetFaceAxisCenter(), and GetFaceAxisDisplacement().
GetLongAxisCenter()
Double_t LKGeoBoxStack::GetLongAxisCenter () const
Definition at line 57 of file LKGeoBoxStack.cpp.
References LKVector3::At(), fFaceAxis, fStackAxis, fX, fY, and fZ.
Referenced by GetLongAxisMax(), and GetLongAxisMin().
GetLongAxisDisplacement()
Double_t LKGeoBoxStack::GetLongAxisDisplacement () const
Definition at line 61 of file LKGeoBoxStack.cpp.
References LKVector3::At(), fdX, fdY, fdZ, fFaceAxis, and fStackAxis.
Referenced by GetLongAxisMax(), and GetLongAxisMin().
GetLongAxisMax()
Double_t LKGeoBoxStack::GetLongAxisMax () const
Definition at line 49 of file LKGeoBoxStack.cpp.
References GetLongAxisCenter(), and GetLongAxisDisplacement().
GetLongAxisMin()
Double_t LKGeoBoxStack::GetLongAxisMin () const
Definition at line 53 of file LKGeoBoxStack.cpp.
References GetLongAxisCenter(), and GetLongAxisDisplacement().
GetStackAxis()
axis_t LKGeoBoxStack::GetStackAxis () const
Definition at line 44 of file LKGeoBoxStack.cpp.
References fStackAxis.
GetStackAxisCenter()
Double_t LKGeoBoxStack::GetStackAxisCenter () const
Definition at line 55 of file LKGeoBoxStack.cpp.
References LKVector3::At(), fStackAxis, fX, fY, and fZ.
Referenced by GetStackAxisMax(), and GetStackAxisMin().
GetStackAxisDisplacement()
Double_t LKGeoBoxStack::GetStackAxisDisplacement () const
Definition at line 59 of file LKGeoBoxStack.cpp.
References LKVector3::At(), fdX, fdY, fdZ, and fStackAxis.
Referenced by GetBox(), GetStackAxisMax(), and GetStackAxisMin().
GetStackAxisMax()
Double_t LKGeoBoxStack::GetStackAxisMax () const
Definition at line 47 of file LKGeoBoxStack.cpp.
References fNumStacks, GetStackAxisCenter(), and GetStackAxisDisplacement().
Referenced by DrawStackHist().
GetStackAxisMin()
Double_t LKGeoBoxStack::GetStackAxisMin () const
Definition at line 51 of file LKGeoBoxStack.cpp.
References fNumStacks, GetStackAxisCenter(), and GetStackAxisDisplacement().
Referenced by DrawStackHist().
Print()
void LKGeoBoxStack::Print (Option_t * option = "") const virtual
Definition at line 18 of file LKGeoBoxStack.cpp.
References e_cout, fdX, fdY, fdZ, fFaceAxis, fStackAxis, fX, fY, and fZ.
SetBoxStack()
void LKGeoBoxStack::SetBoxStack (Double_t x, Double_t y, Double_t z, Double_t dx, Double_t dy, Double_t dz, Int_t n, axis_t as, axis_t af = LKVector3::kZ)
Definition at line 29 of file LKGeoBoxStack.cpp.
References fdX, fdY, fdZ, fFaceAxis, fNumStacks, fStackAxis, fX, fY, and fZ.
Referenced by LKGeoBoxStack().
Member Data Documentation
fdX
Double_t LKGeoBoxStack::fdX protected
Definition at line 66 of file LKGeoBoxStack.h.
Referenced by DrawStackHist(), GetBox(), GetFaceAxisDisplacement(), GetLongAxisDisplacement(), GetStackAxisDisplacement(), Print(), and SetBoxStack().
fdY
Double_t LKGeoBoxStack::fdY protected
Definition at line 67 of file LKGeoBoxStack.h.
Referenced by DrawStackHist(), GetBox(), GetFaceAxisDisplacement(), GetLongAxisDisplacement(), GetStackAxisDisplacement(), Print(), and SetBoxStack().
fdZ
Double_t LKGeoBoxStack::fdZ protected
Definition at line 68 of file LKGeoBoxStack.h.
Referenced by DrawStackHist(), GetBox(), GetFaceAxisDisplacement(), GetLongAxisDisplacement(), GetStackAxisDisplacement(), Print(), and SetBoxStack().
fFaceAxis
axis_t LKGeoBoxStack::fFaceAxis protected
Definition at line 71 of file LKGeoBoxStack.h.
Referenced by DrawStackGraph(), DrawStackHist(), DrawStackHistPoly(), GetFaceAxis(), GetFaceAxisCenter(), GetFaceAxisDisplacement(), GetLongAxisCenter(), GetLongAxisDisplacement(), Print(), and SetBoxStack().
fNumStacks
Int_t LKGeoBoxStack::fNumStacks protected
Definition at line 69 of file LKGeoBoxStack.h.
Referenced by DrawStackGraph(), DrawStackHist(), DrawStackHistPoly(), FindBoxIndex(), GetBox(), GetStackAxisMax(), GetStackAxisMin(), and SetBoxStack().
fStackAxis
axis_t LKGeoBoxStack::fStackAxis protected
Definition at line 70 of file LKGeoBoxStack.h.
Referenced by DrawStackGraph(), DrawStackHist(), DrawStackHistPoly(), GetBox(), GetLongAxisCenter(), GetLongAxisDisplacement(), GetStackAxis(), GetStackAxisCenter(), GetStackAxisDisplacement(), Print(), and SetBoxStack().
fX
Double_t LKGeoBoxStack::fX protected
Definition at line 63 of file LKGeoBoxStack.h.
Referenced by DrawStackHist(), GetBox(), GetCenter(), GetFaceAxisCenter(), GetLongAxisCenter(), GetStackAxisCenter(), Print(), and SetBoxStack().
fY
Double_t LKGeoBoxStack::fY protected
Definition at line 64 of file LKGeoBoxStack.h.
Referenced by DrawStackHist(), GetBox(), GetCenter(), GetFaceAxisCenter(), GetLongAxisCenter(), GetStackAxisCenter(), Print(), and SetBoxStack().
fZ
Double_t LKGeoBoxStack::fZ protected
Definition at line 65 of file LKGeoBoxStack.h.
Referenced by DrawStackHist(), GetBox(), GetCenter(), GetFaceAxisCenter(), GetLongAxisCenter(), GetStackAxisCenter(), Print(), and SetBoxStack().
The documentation for this class was generated from the following files:
LKGeoBoxStack.h
LKGeoBoxStack.cpp