lilak: LKVertex Class Reference
LKVertex Class Reference
#include <LKVertex.h>
Public Member Functions
void AddTrack (LKTracklet *track)
virtual void Clear (Option_t *option="")
virtual void Copy (TObject &object) const
Int_t GetNumTracks () const
vector< LKTracklet * > * GetTrackArray ()
vector< Int_t > * GetTrackIDArray ()
LKVertex ()
virtual void Print (Option_t *option="at") const
virtual ~LKVertex ()
Public Member Functions inherited from LKHit
virtual void AddHit (LKHit *hit)
void AddTrackCand (Int_t id)
virtual void Clear (Option_t *option="")
virtual Int_t Compare (const TObject *obj) const
virtual void Copy (TObject &object) const
void CopyFrom (LKHit *hit)
virtual bool DrawByDefault ()
return true if to be displayed on eve.
bool FindTrackCand (Int_t id)
Double_t GetAlpha () const
Int_t GetChannelID () const
Double_t GetCharge () const
TVector3 GetCoSquaredMean () const
TVector3 GetCovariance () const
TVector3 GetDPosition () const
Double_t GetDX () const
Double_t GetDY () const
Double_t GetDZ () const
LKHitArray * GetHitArray ()
Int_t GetHitID () const
Int_t GetLayer () const
TVector3 GetMean () const
Int_t GetNumTrackCands ()
Int_t GetPadID () const
Double_t GetPedestal () const
TVector3 GetPosition () const
LKVector3 GetPosition (LKVector3::Axis ref) const
TVector3 GetPositionError () const
Int_t GetRow () const
Int_t GetSection () const
Double_t GetSortValue () const
TVector3 GetSquaredMean () const
TVector3 GetStdDev () const
Double_t GetTb () const
Int_t GetTrackCand (Int_t id)
vector< Int_t > * GetTrackCandArray ()
Int_t GetTrackID () const
TVector3 GetVariance () const
Double_t GetX () const
Double_t GetY () const
Double_t GetZ () const
virtual bool IsEveSet ()
virtual Bool_t IsSortable () const
LKHit ()
Temporary array for track ID candidates.
LKHit (Double_t x, Double_t y, Double_t z, Double_t q)
Double_t & operator[] (int i)
Double_t operator[] (int i) const
virtual void Print (Option_t *option="at") const
bool PropagateTrackCand ()
virtual void RemoveHit (LKHit *hit)
void RemoveTrackCand (Int_t trackID)
void SetAlpha (Double_t a)
void SetChannelID (Int_t id)
void SetCharge (Double_t charge)
void SetHitID (Int_t id)
void SetLayer (Int_t layer)
void SetPadID (Int_t id)
void SetPedestal (Double_t a)
void SetPosError (Double_t dx, Double_t dy, Double_t dz)
void SetPosError (TVector3 dpos)
void SetPosition (Double_t x, Double_t y, Double_t z)
void SetPosition (TVector3 pos)
void SetPositionError (Double_t dx, Double_t dy, Double_t dz)
void SetPositionError (TVector3 dpos)
void SetRow (Int_t row)
void SetSection (Int_t section)
void SetSortByCharge (bool sortEarlierIfSmaller)
void SetSortByDistanceTo (TVector3 point, bool sortEarlierIfCloser)
void SetSortByLayer (bool sortEarlierIfSmaller)
void SetSortByX (bool sortEarlierIfSmaller)
void SetSortByY (bool sortEarlierIfSmaller)
void SetSortByZ (bool sortEarlierIfSmaller)
void SetSortValue (Double_t val)
void SetTb (Double_t tb)
void SetTrackID (Int_t id)
void SetW (Double_t w)
Same as SetCharge.
void SetWeight (Double_t w)
void SetX (Double_t x)
void SetXError (Double_t dx)
void SetY (Double_t y)
void SetYError (Double_t dy)
void SetZ (Double_t z)
void SetZError (Double_t dz)
Double_t w () const
Double_t W () const
Double_t WeightPositionError () const
Double_t x () const
Double_t X () const
Double_t y () const
Double_t Y () const
Double_t z () const
Double_t Z () const
virtual ~LKHit ()
Public Member Functions inherited from LKContainer
virtual void Clear (Option_t *option="")
virtual TObject * Clone (const char *newname="") const
virtual void Copy (TObject &object) const
virtual bool DrawByDefault ()
return true if to be displayed on eve.
LKContainer ()
virtual ~LKContainer ()
Private Attributes
vector< LKTracklet * > fTrackArray
vector< Int_t > fTrackIDArray
Additional Inherited Members
Protected Attributes inherited from LKHit
Double_t fAlpha = -999
Use for polar angle.
Int_t fChannelID = -999
Double_t fDX = -999
Double_t fDY = -999
Double_t fDZ = -999
LKHitArray fHitArray
Temporary parameter for sorting. Sort earlier if smaller, latter if larger.
Int_t fHitID = -999
Int_t fLayer = -999
Int_t fPadID = -999
Double_t fPedestal = -999
Int_t fRow = -999
Int_t fSection = -999
Double_t fSortValue = 0
Double_t fTb = -999
vector< Int_t > fTrackCandArray
Temporary hit array.
Int_t fTrackID = -999
Double_t fW = -999
Double_t fX = -999
Double_t fY = -999
Double_t fZ = -999
Detailed Description
Definition at line 13 of file LKVertex.h.
Constructor & Destructor Documentation
LKVertex()
LKVertex::LKVertex ()
~LKVertex()
virtual LKVertex::~LKVertex () inline virtual
Definition at line 17 of file LKVertex.h.
References Clear().
Member Function Documentation
AddTrack()
void LKVertex::AddTrack (LKTracklet * track)
Definition at line 43 of file LKVertex.cpp.
References fTrackArray, fTrackIDArray, and LKTracklet::GetTrackID().
Clear()
void LKVertex::Clear (Option_t * option = "") virtual
Reimplemented from LKHit.
Definition at line 13 of file LKVertex.cpp.
References LKHit::Clear(), fTrackArray, and fTrackIDArray.
Referenced by ClassImp(), and ~LKVertex().
Copy()
void LKVertex::Copy (TObject & object) const virtual
Reimplemented from LKHit.
Definition at line 33 of file LKVertex.cpp.
References LKHit::Copy(), and fTrackArray.
GetNumTracks()
Int_t LKVertex::GetNumTracks () const inline
Definition at line 28 of file LKVertex.h.
References fTrackIDArray.
Referenced by Print().
GetTrackArray()
vector< LKTracklet * > * LKVertex::GetTrackArray () inline
Definition at line 26 of file LKVertex.h.
References fTrackArray.
GetTrackIDArray()
vector< Int_t > * LKVertex::GetTrackIDArray () inline
Definition at line 25 of file LKVertex.h.
References fTrackIDArray.
Print()
void LKVertex::Print (Option_t * option = "at") const virtual
Reimplemented from LKHit.
Definition at line 21 of file LKVertex.cpp.
References e_info, LKHit::fX, LKHit::fY, LKHit::fZ, and GetNumTracks().
Member Data Documentation
fTrackArray
vector<LKTracklet*> LKVertex::fTrackArray private
Definition at line 39 of file LKVertex.h.
Referenced by AddTrack(), Clear(), Copy(), and GetTrackArray().
fTrackIDArray
vector<Int_t> LKVertex::fTrackIDArray private
Definition at line 38 of file LKVertex.h.
Referenced by AddTrack(), Clear(), GetNumTracks(), and GetTrackIDArray().
The documentation for this class was generated from the following files:
LKVertex.h
LKVertex.cpp