lilak: LKPadInteractive Class Reference
LKPadInteractive Class Reference
#include <LKPadInteractive.h>
Public Member Functions
void AddInteractivePad (TVirtualPad *pad, TString option="")
virtual void ExecMouseClickEventOnPad (TVirtualPad *pad, double xOnClick, double yOnClick)
int GetPadInteractiveID () const
LKPadInteractive ()
void SetPadInteractiveID (int id)
virtual ~LKPadInteractive ()
Protected Attributes
int fPadInteractiveID = -1
Detailed Description
Definition at line 7 of file LKPadInteractive.h.
Constructor & Destructor Documentation
LKPadInteractive()
LKPadInteractive::LKPadInteractive () inline
Definition at line 10 of file LKPadInteractive.h.
~LKPadInteractive()
virtual LKPadInteractive::~LKPadInteractive () inline virtual
Definition at line 11 of file LKPadInteractive.h.
Member Function Documentation
AddInteractivePad()
void LKPadInteractive::AddInteractivePad (TVirtualPad * pad, TString option = "")
Definition at line 6 of file LKPadInteractive.cpp.
References LKPadInteractiveManager::GetManager().
Referenced by LKHTLineTracker::Draw(), LKEvePlane::GetCanvas(), SKSiArrayPlane::GetCanvas(), LKGETChannelViewer::Init(), LKDataViewer::InitCanvas(), SKDrawTodayTask::InitCanvas(), and LKChannelAnalyzer::SetPad().
ExecMouseClickEventOnPad()
virtual void LKPadInteractive::ExecMouseClickEventOnPad (TVirtualPad * pad, double xOnClick, double yOnClick) inline virtual
Reimplemented in LKEvePlane, LKGETChannelViewer, LKHTLineTracker, LKDataViewer, LKChannelAnalyzer, SKSiArrayPlane, SKDrawTodayTask, LKEvePlane, LKGETChannelViewer, and testa.
Definition at line 16 of file LKPadInteractive.h.
GetPadInteractiveID()
int LKPadInteractive::GetPadInteractiveID () const inline
Definition at line 14 of file LKPadInteractive.h.
References fPadInteractiveID.
SetPadInteractiveID()
void LKPadInteractive::SetPadInteractiveID (int id) inline
Definition at line 13 of file LKPadInteractive.h.
References fPadInteractiveID.
Member Data Documentation
fPadInteractiveID
int LKPadInteractive::fPadInteractiveID = -1 protected
Definition at line 21 of file LKPadInteractive.h.
Referenced by LKHTLineTracker::Draw(), GetPadInteractiveID(), and SetPadInteractiveID().
The documentation for this class was generated from the following files:
LKPadInteractive.h
LKPadInteractive.cpp