LILAK: LKEveTask Class Reference
LKEveTask Class Reference
#include <LKEveTask.h>
Public Member Functions
virtual void Add (TTask *task)
void AddPar (LKParameterContainer *par)
void AddPar (TString fname)
virtual void AddParameterContainer (LKParameterContainer *par)
virtual void AddParameterContainer (TString fname)
void ClickSelectedPlane ()
void ConfigureDetectorPlanes ()
void CreateParameterContainer ()
void DrawDetectorPlanes ()
void DrawEve3D ()
void DrawPadByPosition (Double_t x, Double_t y)
virtual bool EndOfRun ()
bool EndOfRunTask ()
bool EndOfRunTasks ()
void Exec (Option_t *)
LKParameterContainer * GetPar () const
LKParameterContainer * GetParameterContainer () const
Int_t GetRank () const
bool Init ()
bool InitTask ()
bool InitTasks ()
virtual bool IsEventTrigger ()
LKEveTask ()
virtual void Run (Long64_t numEvents=-1)
bool SelectHit (LKHit *hit)
bool SelectTrack (LKTracklet *track)
void SetEveLineAtt (TAttLine *el, TString branchName)
void SetEveMarkerAtt (TAttMarker *el, TString branchName)
void SetGraphAtt (TGraph *graph, TString branchName)
void SetGraphAtt (TGraph2D *graph, TString branchName)
void SetPar (LKParameterContainer *par)
virtual void SetParameterContainer (LKParameterContainer *par)
virtual void SetRank (Int_t rank)
void SetRun (LKRun *run)
virtual void SignalNextEvent ()
virtual ~LKEveTask ()
Protected Attributes
LKParameterContainer * fPar = nullptr
Int_t fRank = 0
LKRun * fRun = nullptr
Private Attributes
TPad * fCanvas3D = nullptr
TObjArray * fCvsDetectorPlaneArray = nullptr
LKDetectorSystem * fDetectorSystem = nullptr
Bool_t fDrawEve3D = true
Bool_t fDrawPlane = true
TObjArray * fEveEventManagerArray = nullptr
Double_t fEveScale = 1
TH3D * fFrame3D = nullptr
TClonesArray * fGraphHit3DArray = nullptr
TClonesArray * fGraphTrack3DArray = nullptr
vector< Int_t > fIgnHitPntIDs
vector< Int_t > fIgnMCIDs
vector< Int_t > fIgnPDGs
vector< Int_t > fIgnPntIDs
vector< Int_t > fIgnTrkIDs
int fNumBranches
int fNumSelectedBranches
vector< TString > fSelBranchNames
LKDetectorPlane * fSelectedPlane = nullptr
vector< Int_t > fSelHitPntIDs
vector< Int_t > fSelMCIDs
vector< Int_t > fSelPDGs
vector< Int_t > fSelPntIDs
vector< Int_t > fSelTrkIDs
Detailed Description
Definition at line 17 of file LKEveTask.h.
Constructor & Destructor Documentation
LKEveTask()
LKEveTask::LKEveTask ()
~LKEveTask()
virtual LKEveTask::~LKEveTask () inline virtual
Definition at line 21 of file LKEveTask.h.
Member Function Documentation
Add()
void LKTask::Add (TTask * task) virtual inherited
Definition at line 16 of file LKTask.cpp.
References LKGear::AddPar(), LKGear::fPar, LKGear::fRank, and LKTask::SetRank().
Referenced by LKRun::Add(), ConfigureDetectorPlanes(), DrawEve3D(), LKNoiseSubtractionTask::Exec(), TTHTTrackingTask::TransformAndSelectHits(), and httask::TransformAndSelectHits().
AddPar() [1/2]
void LKGear::AddPar (LKParameterContainer * par) inline inherited
Definition at line 27 of file LKGear.h.
References LKGear::AddParameterContainer().
Referenced by LKTask::Add(), LKRun::EndOfRun(), LKRun::Init(), LKG4RunManager::Initialize(), LAMPSTPC::LAMPSTPC(), LAMPSTPC::LAMPSTPC(), LKDetectorSystem::SetDetectorPar(), LKRun::SetEventTrigger(), LKG4RunManager::SetSensitiveDetector(), LKG4RunManager::SetVolume(), LKRun::StartOfRun(), TexAT2::TexAT2(), TexAT2::TexAT2(), and TTMicromegas::WriteCurrentChannel().
AddPar() [2/2]
void LKGear::AddPar (TString fname) inline inherited
Definition at line 28 of file LKGear.h.
References LKGear::AddParameterContainer().
AddParameterContainer() [1/2]
void LKGear::AddParameterContainer (LKParameterContainer * par) virtual inherited
Definition at line 14 of file LKGear.cpp.
References LKGear::AddParameterContainer(), and LKGear::fPar.
Referenced by LKGear::AddPar(), LKGear::AddPar(), LKGear::AddParameterContainer(), LHTpc::BuildDetectorPlane(), and LKRun::Init().
AddParameterContainer() [2/2]
void LKGear::AddParameterContainer (TString fname) virtual inherited
Definition at line 22 of file LKGear.cpp.
References LKGear::fPar.
ClickSelectedPlane()
void LKEveTask::ClickSelectedPlane ()
ConfigureDetectorPlanes()
void LKEveTask::ConfigureDetectorPlanes ()
Definition at line 432 of file LKEveTask.cpp.
References LKTask::Add(), cvs, fCvsDetectorPlaneArray, and fDetectorSystem.
Referenced by Init().
CreateParameterContainer()
void LKGear::CreateParameterContainer () inherited
Referenced by LKRun::AddDetector(), and LKRun::LKRun().
DrawDetectorPlanes()
void LKEveTask::DrawDetectorPlanes ()
Definition at line 359 of file LKEveTask.cpp.
References fDetectorSystem, fNumSelectedBranches, LKGear::fRun, fSelBranchNames, LKVector3::kNon, lk_info, and SelectTrack().
Referenced by Exec().
DrawEve3D()
void LKEveTask::DrawEve3D ()
Definition at line 97 of file LKEveTask.cpp.
References LKTask::Add(), LKVector3::At(), LKParameterContainer::CheckPar(), LKContainer::DrawByDefault(), fCanvas3D, fDetectorSystem, fEveEventManagerArray, fEveScale, fFrame3D, fGraphHit3DArray, fGraphTrack3DArray, fNumSelectedBranches, LKGear::fPar, LKGear::fRun, fSelBranchNames, fSelectedPlane, LKParameterContainer::GetParBool(), LKParameterContainer::GetParDouble(), LKWindowManager::GetWindowManager(), LKVector3::kX, LKVector3::kY, LKVector3::kZ, lk_error, lk_info, SelectHit(), SelectTrack(), SetEveLineAtt(), SetEveMarkerAtt(), SetGraphAtt(), SetPoint(), y2, z1, and z2.
Referenced by Exec().
DrawPadByPosition()
void LKEveTask::DrawPadByPosition (Double_t x, Double_t y)
EndOfRun()
bool LKTask::EndOfRun () virtual inherited
Reimplemented in LTEventPreviewTask, TTHitFindingTask, TTPulseAnalysisTask, LKRun, LKMFMConversionTask, LKDriftElectronTask, LKElectronicsTask, LKNoiseSubtractionTask, LKPulseExtractionTask, LKPulseShapeAnalysisTask, TTBeamSelectionTask, TTDrawBeamEnergyTask, TTDrawRawWaveformTask, TTEventSelectionTask, TTFindBeamTimingTask, TTGetPedestalTask, TTPID_FSivsFCsI, TTPID_MMvsFSi, TTPID_MMvsX6, TTPID_X6vsCsI, TTReadEventListTask, TTHTtBeamTrackingTask, TTEventPreviewTask, TTHitFindingHoughTask, TTHTBeamTrackingTask, TTHTTrackingTask, TTPulseAnalysisTask, TTPulseExtractionTask, and httask.
Definition at line 70 of file LKTask.cpp.
Referenced by LKTask::EndOfRunTask(), and LKTask::EndOfRunTasks().
EndOfRunTask()
bool LKTask::EndOfRunTask () inherited
Definition at line 58 of file LKTask.cpp.
References LKTask::EndOfRun(), and LKTask::EndOfRunTasks().
EndOfRunTasks()
bool LKTask::EndOfRunTasks () inherited
Definition at line 75 of file LKTask.cpp.
References LKTask::EndOfRun(), lk_info, and lk_warning.
Referenced by LKRun::EndOfRun(), and LKTask::EndOfRunTask().
Exec()
void LKEveTask::Exec (Option_t *)
Definition at line 91 of file LKEveTask.cpp.
References DrawDetectorPlanes(), DrawEve3D(), fDrawEve3D, and fDrawPlane.
GetPar()
LKParameterContainer * LKGear::GetPar () const inherited
Definition at line 33 of file LKGear.cpp.
References LKGear::fPar.
GetParameterContainer()
LKParameterContainer * LKGear::GetParameterContainer () const inherited
Definition at line 32 of file LKGear.cpp.
References LKGear::fPar.
Referenced by ClassImp(), LHElectronicsTask::Init(), and LHVertexFindingTask::Init().
GetRank()
Int_t LKGear::GetRank () const inherited
Definition at line 36 of file LKGear.cpp.
References LKGear::fRank.
Init()
bool LKEveTask::Init () virtual
Reimplemented from LKTask.
Definition at line 37 of file LKEveTask.cpp.
References LKParameterContainer::CheckPar(), ConfigureDetectorPlanes(), fDetectorSystem, fDrawEve3D, fDrawPlane, fIgnHitPntIDs, fIgnMCIDs, fIgnPDGs, fIgnPntIDs, fIgnTrkIDs, fNumBranches, fNumSelectedBranches, LKGear::fPar, LKGear::fRun, fSelBranchNames, fSelHitPntIDs, fSelMCIDs, fSelPDGs, fSelPntIDs, fSelTrkIDs, LKRun::GetBranchName(), and lk_error.
InitTask()
bool LKTask::InitTask () inherited
Definition at line 25 of file LKTask.cpp.
References LKTask::Init(), and LKTask::InitTasks().
InitTasks()
bool LKTask::InitTasks () inherited
Definition at line 42 of file LKTask.cpp.
References LKTask::Init(), lk_info, and lk_warning.
Referenced by LKRun::Init(), and LKTask::InitTask().
IsEventTrigger()
virtual bool LKTask::IsEventTrigger () inline virtual inherited
Reimplemented in LKMFMConversionTask.
Definition at line 32 of file LKTask.h.
Referenced by LKRun::Add().
Run()
virtual void LKTask::Run (Long64_t numEvents = -1) inline virtual inherited
Reimplemented in LKRun, and LKMFMConversionTask.
Definition at line 31 of file LKTask.h.
SelectHit()
bool LKEveTask::SelectHit (LKHit * hit)
Definition at line 462 of file LKEveTask.cpp.
References fIgnHitPntIDs, fSelHitPntIDs, LKHit::GetTrackID(), and LKHit::SetSortValue().
Referenced by DrawEve3D().
SelectTrack()
bool LKEveTask::SelectTrack (LKTracklet * track)
Definition at line 448 of file LKEveTask.cpp.
References fIgnPDGs, fIgnPntIDs, fIgnTrkIDs, fSelPDGs, fSelPntIDs, fSelTrkIDs, LKTracklet::GetParentID(), LKTracklet::GetPDG(), and LKTracklet::GetTrackID().
Referenced by DrawDetectorPlanes(), and DrawEve3D().
SetEveLineAtt()
void LKEveTask::SetEveLineAtt (TAttLine * el, TString branchName)
Definition at line 472 of file LKEveTask.cpp.
References LKParameterContainer::CheckPar(), and LKGear::fPar.
Referenced by DrawEve3D().
SetEveMarkerAtt()
void LKEveTask::SetEveMarkerAtt (TAttMarker * el, TString branchName)
Definition at line 487 of file LKEveTask.cpp.
References LKParameterContainer::CheckPar(), and LKGear::fPar.
Referenced by DrawEve3D().
SetGraphAtt() [1/2]
void LKEveTask::SetGraphAtt (TGraph * graph, TString branchName)
Definition at line 502 of file LKEveTask.cpp.
References LKParameterContainer::CheckPar(), and LKGear::fPar.
Referenced by DrawEve3D().
SetGraphAtt() [2/2]
void LKEveTask::SetGraphAtt (TGraph2D * graph, TString branchName)
Definition at line 530 of file LKEveTask.cpp.
References LKParameterContainer::CheckPar(), and LKGear::fPar.
SetPar()
void LKGear::SetPar (LKParameterContainer * par) inline inherited
Definition at line 26 of file LKGear.h.
References LKGear::SetParameterContainer().
Referenced by LKDetector::AddPlane(), LKRun::Init(), LKDetector::Init(), and LKMFMConversionTask::Init().
SetParameterContainer()
void LKGear::SetParameterContainer (LKParameterContainer * par) virtual inherited
Definition at line 10 of file LKGear.cpp.
References LKGear::fPar.
Referenced by ATTPC::BuildDetectorPlane(), and LKGear::SetPar().
SetRank()
void LKTask::SetRank (Int_t rank) virtual inherited
Reimplemented from LKGear.
Definition at line 91 of file LKTask.cpp.
References LKGear::fRank, and LKTask::SetRank().
Referenced by LKTask::Add(), LKRun::SetEventTrigger(), and LKTask::SetRank().
SetRun()
void LKGear::SetRun (LKRun * run) inline inherited
Definition at line 36 of file LKGear.h.
References LKGear::fRun, and run.
Referenced by LKRun::Add(), LKRun::AddDetector(), LKRun::Init(), LKDetectorSystem::SetDetector(), and LKRun::SetEventTrigger().
SignalNextEvent()
virtual void LKTask::SignalNextEvent () inline virtual inherited
Reimplemented in LKMFMConversionTask.
Definition at line 33 of file LKTask.h.
Member Data Documentation
fCanvas3D
TPad* LKEveTask::fCanvas3D = nullptr private
Definition at line 75 of file LKEveTask.h.
Referenced by DrawEve3D().
fCvsDetectorPlaneArray
TObjArray* LKEveTask::fCvsDetectorPlaneArray = nullptr private
Definition at line 64 of file LKEveTask.h.
Referenced by ConfigureDetectorPlanes().
fDetectorSystem
LKDetectorSystem* LKEveTask::fDetectorSystem = nullptr private
Definition at line 66 of file LKEveTask.h.
Referenced by ConfigureDetectorPlanes(), DrawDetectorPlanes(), DrawEve3D(), and Init().
fDrawEve3D
Bool_t LKEveTask::fDrawEve3D = true private
Definition at line 46 of file LKEveTask.h.
Referenced by Exec(), and Init().
fDrawPlane
Bool_t LKEveTask::fDrawPlane = true private
Definition at line 47 of file LKEveTask.h.
Referenced by Exec(), and Init().
fEveEventManagerArray
TObjArray* LKEveTask::fEveEventManagerArray = nullptr private
Definition at line 68 of file LKEveTask.h.
Referenced by DrawEve3D().
fEveScale
Double_t LKEveTask::fEveScale = 1 private
Definition at line 81 of file LKEveTask.h.
Referenced by DrawEve3D().
fFrame3D
TH3D* LKEveTask::fFrame3D = nullptr private
Definition at line 76 of file LKEveTask.h.
Referenced by DrawEve3D().
fGraphHit3DArray
TClonesArray* LKEveTask::fGraphHit3DArray = nullptr private
Definition at line 78 of file LKEveTask.h.
Referenced by DrawEve3D().
fGraphTrack3DArray
TClonesArray* LKEveTask::fGraphTrack3DArray = nullptr private
Definition at line 77 of file LKEveTask.h.
Referenced by DrawEve3D().
fIgnHitPntIDs
vector<Int_t> LKEveTask::fIgnHitPntIDs private
Definition at line 58 of file LKEveTask.h.
Referenced by Init(), and SelectHit().
fIgnMCIDs
vector<Int_t> LKEveTask::fIgnMCIDs private
Definition at line 56 of file LKEveTask.h.
Referenced by Init().
fIgnPDGs
vector<Int_t> LKEveTask::fIgnPDGs private
Definition at line 54 of file LKEveTask.h.
Referenced by Init(), and SelectTrack().
fIgnPntIDs
vector<Int_t> LKEveTask::fIgnPntIDs private
Definition at line 52 of file LKEveTask.h.
Referenced by Init(), and SelectTrack().
fIgnTrkIDs
vector<Int_t> LKEveTask::fIgnTrkIDs private
Definition at line 50 of file LKEveTask.h.
Referenced by Init(), and SelectTrack().
fNumBranches
int LKEveTask::fNumBranches private
Definition at line 61 of file LKEveTask.h.
Referenced by Init().
fNumSelectedBranches
int LKEveTask::fNumSelectedBranches private
Definition at line 62 of file LKEveTask.h.
Referenced by DrawDetectorPlanes(), DrawEve3D(), and Init().
fPar
LKParameterContainer* LKGear::fPar = nullptr protected inherited
Definition at line 39 of file LKGear.h.
Referenced by LKTask::Add(), LKRun::AddDetector(), LKGear::AddParameterContainer(), LKGear::AddParameterContainer(), LKDetector::AddPlane(), LHTpc::BuildDetectorPlane(), ATTPC::BuildDetectorPlane(), LHTpc::BuildGeometry(), ATTPC::BuildGeometry(), ClassImp(), ClassImp(), ClassImp(), ClassImp(), DrawEve3D(), LKPadPlane::DrawHist(), LKG4RunManager::EndOfRun(), LKPulseExtractionTask::EndOfRun(), LKDetectorPlane::FillDataToHist(), LKPadPlane::FillDataToHist(), LTPadPlane::GetChannelAnalyzer(), LKDetector::GetChannelAnalyzer(), LKDetectorPlane::GetChannelAnalyzer(), LKEvePlane::GetChannelAnalyzer(), LKGear::GetPar(), LKGear::GetParameterContainer(), ATMicromegas::Init(), AToMX::Init(), LTPadPlane::Init(), LKRun::Init(), LKDetector::Init(), LKEvePlane::Init(), LKMFMConversionTask::Init(), LKDriftElectronTask::Init(), Init(), LKGETChannelViewer::Init(), LKNoiseSubtractionTask::Init(), LKPulseExtractionTask::Init(), LHPSATask::Init(), TexAT2::Init(), TTMicromegas::Init(), TTHTBeamTrackingTask::Init(), TTHTTrackingTask::Init(), TTPulseExtractionTask::Init(), LHPadPlaneFan::Init(), LHPadPlaneRCut::Init(), LHPadPlaneYCut::Init(), ATTPC::Init(), ATTPC20RectanglePad::Init(), ATTPCHoneyCombPad::Init(), ATTPCRectanglePad::Init(), ATTPCStripPad::Init(), TTFrontPlane::Init(), LKRun::InitAndCollectParameters(), TexAT2::InitChannelAnalyzer(), LKG4RunManager::Initialize(), LKRun::Print(), LKRun::RegisterBranchA(), LKG4RunManager::Run(), LKDetectorPlane::SetDataFromBranch(), LKPadPlane::SetDataFromBranch(), LKDetectorSystem::SetDetectorPar(), SetEveLineAtt(), SetEveMarkerAtt(), LKRun::SetEventTrigger(), SetGraphAtt(), SetGraphAtt(), LKG4RunManager::SetOutputFile(), LKGear::SetParameterContainer(), TTMicromegas::WriteCurrentChannel(), and LKRun::WriteOutputFile().
fRank
Int_t LKGear::fRank = 0 protected inherited
Definition at line 41 of file LKGear.h.
Referenced by LKTask::Add(), LKDetector::AddPlane(), LKGear::GetRank(), LKDetectorSystem::SetDetector(), LKRun::SetEventTrigger(), LKGear::SetRank(), and LKTask::SetRank().
fRun
LKRun* LKGear::fRun = nullptr protected inherited
Definition at line 40 of file LKGear.h.
Referenced by LKDetector::AddPlane(), ClassImp(), ClassImp(), ClassImp(), LKEvePlane::ClickedControlEvent1(), LKEvePlane::ClickedControlEvent1(), LKEvePlane::ClickedControlEvent2(), DrawDetectorPlanes(), DrawEve3D(), LKPulseExtractionTask::EndOfRun(), TTPulseExtractionTask::EndOfRun(), LKGETChannelViewer::Exec(), LKPulseExtractionTask::Exec(), TTHitFindingHoughTask::Exec(), TTPulseExtractionTask::Exec(), TTMicromegas::FillDataToHist(), LTPadPlane::FillDataToHist(), LKEvePlane::FillDataToHistEventDisplay1(), LKEvePlane::GetHistControlEvent1(), LTPadPlane::Init(), LTEventPreviewTask::Init(), TTPulseAnalysisTask::Init(), LKEvePlane::Init(), LKMFMConversionTask::Init(), LKDriftElectronTask::Init(), Init(), LKGETChannelViewer::Init(), LKNoiseSubtractionTask::Init(), LKPulseExtractionTask::Init(), LKPulseShapeAnalysisTask::Init(), TTBeamSelectionTask::Init(), TTDrawBeamEnergyTask::Init(), TTDrawRawWaveformTask::Init(), TTEventSelectionTask::Init(), TTFindBeamTimingTask::Init(), TTGetPedestalTask::Init(), TTPID_FSivsFCsI::Init(), TTPID_MMvsFSi::Init(), TTPID_MMvsX6::Init(), TTPID_X6vsCsI::Init(), TTReadEventListTask::Init(), TTHTtBeamTrackingTask::Init(), TTEventNumberSelectionTask::Init(), TTEventPreviewTask::Init(), TTHitFindingHoughTask::Init(), TTHTBeamTrackingTask::Init(), TTHTTrackingTask::Init(), TTPulseExtractionTask::Init(), httask::Init(), LKMFMConversionTask::Run(), LKGETChannelViewer::SelectMenu(), LKDetectorPlane::SetDataFromBranch(), LKPadPlane::SetDataFromBranch(), TTMicromegas::SetDataFromBranch(), TTFrontPlane::SetDataFromBranch(), LKDetectorSystem::SetDetector(), LKEvePlane::SetPalette(), LKGear::SetRun(), LKDetector::SetRun(), LKMFMConversionTask::SignalNextEvent(), LKEvePlane::UpdateControlEvent1(), and LKEvePlane::UpdateControlEvent2().
fSelBranchNames
vector<TString> LKEveTask::fSelBranchNames private
Definition at line 59 of file LKEveTask.h.
Referenced by DrawDetectorPlanes(), DrawEve3D(), and Init().
fSelectedPlane
LKDetectorPlane* LKEveTask::fSelectedPlane = nullptr private
Definition at line 74 of file LKEveTask.h.
Referenced by DrawEve3D().
fSelHitPntIDs
vector<Int_t> LKEveTask::fSelHitPntIDs private
Definition at line 57 of file LKEveTask.h.
Referenced by Init(), and SelectHit().
fSelMCIDs
vector<Int_t> LKEveTask::fSelMCIDs private
Definition at line 55 of file LKEveTask.h.
Referenced by Init().
fSelPDGs
vector<Int_t> LKEveTask::fSelPDGs private
Definition at line 53 of file LKEveTask.h.
Referenced by Init(), and SelectTrack().
fSelPntIDs
vector<Int_t> LKEveTask::fSelPntIDs private
Definition at line 51 of file LKEveTask.h.
Referenced by Init(), and SelectTrack().
fSelTrkIDs
vector<Int_t> LKEveTask::fSelTrkIDs private
Definition at line 49 of file LKEveTask.h.
Referenced by Init(), and SelectTrack().
The documentation for this class was generated from the following files:
LKEveTask.h
LKEveTask.cpp