lilak: LKSiArrayPlane Class Reference
LKSiArrayPlane Class Reference
#include <LKSiArrayPlane.h>
Public Member Functions
virtual void ClickedEventDisplay2 (double xOnClick, double yOnClick)
virtual void FillDataToHistEventDisplay2 (Option_t *option="")
virtual LKPad * FindPad (int cobo, int asad, int aget, int chan)
TODO.
virtual int FindPadID (int cobo, int asad, int aget, int chan)
virtual int FindPadIDFromHistEventDisplay1Bin (int hbin)
virtual int FindZFromHistEventDisplay2Bin (int hbin)
virtual TPad * Get3DEventPad ()
If user wants to place 3D event display other than default canvas, this method should return corresponding TPad.
virtual TH1D * GetHistChannelBuffer ()
virtual TH2 * GetHistEventDisplay1 (Option_t *option="-1")
virtual TH2 * GetHistEventDisplay2 (Option_t *option="-1")
virtual bool Init ()
LKSiArrayPlane ()
LKSiArrayPlane (const char *name, const char *title)
virtual void UpdateChannelBuffer ()
virtual void UpdateEventDisplay1 ()
virtual void UpdateEventDisplay2 ()
virtual ~LKSiArrayPlane ()
Public Member Functions inherited from LKEvePlane
virtual void Clear (Option_t *option="")
virtual void Clear (Option_t *option="")
virtual void ClickedControlEvent1 (double xOnClick, double yOnClick)
virtual void ClickedControlEvent1 (double xOnClick, double yOnClick)
virtual void ClickedControlEvent1 (int selectedBin)
virtual void ClickedControlEvent1 (int selectedBin)
virtual void ClickedControlEvent2 (double xOnClick, double yOnClick)
virtual void ClickedControlEvent2 (double xOnClick, double yOnClick)
virtual void ClickedControlEvent2 (int selectedBin)
virtual void ClickedControlEvent2 (int selectedBin)
virtual void ClickedEventDisplay1 (double xOnClick, double yOnClick)
virtual void ClickedEventDisplay1 (double xOnClick, double yOnClick)
virtual void ClickedEventDisplay2 (double xOnClick, double yOnClick)
virtual void ClickedEventDisplay2 (double xOnClick, double yOnClick)
virtual void Draw (Option_t *option="")
Implementation recommanded for event display. Draw event display to the canvas.
virtual void Draw (Option_t *option="")
Implementation recommanded for event display. Draw event display to the canvas.
virtual void DrawFrame (Option_t *option="")
virtual void DrawFrame (Option_t *option="")
virtual void DrawHist (Option_t *option="")
virtual void DrawHist (Option_t *option="")
virtual void DriftElectronBack (int padID, double tb, TVector3 &posReco, double &driftLength)
virtual void DriftElectronBack (int padID, double tb, TVector3 &posReco, double &driftLength)
virtual void ExecMouseClickEventOnPad (TVirtualPad *pad, double xOnClick, double yOnClick)
virtual void ExecMouseClickEventOnPad (TVirtualPad *pad, double xOnClick, double yOnClick)
virtual void FillDataToHist (Option_t *option="")
Implementation recommanded. Fill data to histograms.
virtual void FillDataToHist (Option_t *option="")
Implementation recommanded. Fill data to histograms.
virtual void FillDataToHistEventDisplay1 (Option_t *option="")
virtual void FillDataToHistEventDisplay1 (Option_t *option="")
virtual void FillDataToHistEventDisplay2 (Option_t *option="")
virtual void FillDataToHistEventDisplay2 (Option_t *option="")
virtual int FindChannelID (double i, double j)
Implementation recommanded. Find channel using position.
virtual int FindChannelID (double i, double j)
Implementation recommanded. Find channel using position.
virtual int FindChannelID (int section, int layer, int row)
Implementation recommanded. Find channel using section, layer, row info.
virtual int FindChannelID (int section, int layer, int row)
Implementation recommanded. Find channel using section, layer, row info.
virtual LKPad * FindPad (int cobo, int asad, int aget, int chan)
TODO.
virtual LKPad * FindPad (int cobo, int asad, int aget, int chan)
TODO.
virtual int FindPadID (int cobo, int asad, int aget, int chan)
virtual int FindPadID (int cobo, int asad, int aget, int chan)
virtual int FindPadIDFromHistEventDisplay1Bin (int hbin)
virtual int FindPadIDFromHistEventDisplay1Bin (int hbin)
virtual int FindPadIDFromHistEventDisplay2Bin (int hbin)
virtual int FindPadIDFromHistEventDisplay2Bin (int hbin)
virtual TPad * Get3DEventPad ()
If user wants to place 3D event display other than default canvas, this method should return corresponding TPad.
virtual TPad * Get3DEventPad ()
If user wants to place 3D event display other than default canvas, this method should return corresponding TPad.
virtual axis_t GetAxis1 (int iPad=0) const
virtual axis_t GetAxis1 (int iPad=0) const
virtual axis_t GetAxis2 (int iPad=0) const
virtual axis_t GetAxis2 (int iPad=0) const
virtual TCanvas * GetCanvas (Option_t *option="")
Implementation recommanded for event display.
virtual TCanvas * GetCanvas (Option_t *option="")
Implementation recommanded for event display.
virtual LKChannelAnalyzer * GetChannelAnalyzer (int id=0)
virtual LKChannelAnalyzer * GetChannelAnalyzer (int id=0)
virtual TPad * GetCPad (int iPad)
For grabbing inner pads of canvas.
virtual TPad * GetCPad (int iPad)
For grabbing inner pads of canvas.
virtual TH2 * GetHist (Option_t *option="-1")
virtual TH2 * GetHist (Option_t *option="-1")
virtual TH1D * GetHistChannelBuffer ()
virtual TH1D * GetHistChannelBuffer ()
virtual TH2D * GetHistControlEvent1 ()
virtual TH2D * GetHistControlEvent1 ()
virtual TH2D * GetHistControlEvent2 ()
virtual TH2D * GetHistControlEvent2 ()
virtual TH2 * GetHistEventDisplay1 (Option_t *option="-1")
virtual TH2 * GetHistEventDisplay1 (Option_t *option="-1")
virtual TH2 * GetHistEventDisplay2 (Option_t *option="-1")
virtual TH2 * GetHistEventDisplay2 (Option_t *option="-1")
virtual int GetNumCPads ()
Get number of inner pads of canvas.
virtual int GetNumCPads ()
Get number of inner pads of canvas.
TPad * GetPadChannelBuffer ()
TPad * GetPadChannelBuffer ()
TPad * GetPadControlEvent1 ()
TPad * GetPadControlEvent1 ()
TPad * GetPadControlEvent2 ()
TPad * GetPadControlEvent2 ()
TPad * GetPadEventDisplay1 ()
TPad * GetPadEventDisplay1 ()
TPad * GetPadEventDisplay2 ()
TPad * GetPadEventDisplay2 ()
virtual TVector3 GlobalToLocalAxis (TVector3 posGlobal)
Implementation recommanded. Convert global position to local detector plane position TODO.
virtual TVector3 GlobalToLocalAxis (TVector3 posGlobal)
Implementation recommanded. Convert global position to local detector plane position TODO.
virtual bool Init ()
virtual bool Init ()
virtual bool IsInBoundary (double i, double j)
Implementation recommanded. Return if position (i,j) is inside the effective detector plane boundary TODO.
virtual bool IsInBoundary (double i, double j)
Implementation recommanded. Return if position (i,j) is inside the effective detector plane boundary TODO.
LKEvePlane ()
LKEvePlane ()
LKEvePlane (const char *name, const char *title)
LKEvePlane (const char *name, const char *title)
virtual TVector3 LocalToGlobalAxis (TVector3 posLocal)
Implementation recommanded. Convert local position to global detector plane position TODO.
virtual TVector3 LocalToGlobalAxis (TVector3 posLocal)
Implementation recommanded. Convert local position to global detector plane position TODO.
virtual double PadDisplacement () const
Return average pad displacement to each other.
virtual double PadDisplacement () const
Return average pad displacement to each other.
virtual void Print (Option_t *option="") const
virtual void Print (Option_t *option="") const
virtual bool SetDataFromBranch ()
Implementation recommanded. Set waveform and hit data from input tree branches to pads.
virtual bool SetDataFromBranch ()
Implementation recommanded. Set waveform and hit data from input tree branches to pads.
void SetPalette ()
void SetPalette ()
virtual void UpdateAll ()
virtual void UpdateAll ()
virtual void UpdateChannelBuffer ()
virtual void UpdateChannelBuffer ()
virtual void UpdateControlEvent1 ()
virtual void UpdateControlEvent1 ()
virtual void UpdateControlEvent2 ()
virtual void UpdateControlEvent2 ()
virtual void UpdateEventDisplay1 ()
virtual void UpdateEventDisplay1 ()
virtual void UpdateEventDisplay2 ()
virtual void UpdateEventDisplay2 ()
virtual void UpdateFill (bool updateHist=true)
virtual void UpdateFill (bool updateHist=true)
virtual void UpdateMenu ()
virtual void UpdateMenu ()
virtual ~LKEvePlane ()
virtual ~LKEvePlane ()
Public Member Functions inherited from LKDetectorPlane
void AddChannel (LKChannel *channel)
Add channel to channel array in detector plane. For interanl use.
void AddHit (LKHit *hit)
void AddPad (LKPad *pad)
Add pad to pad array in detector plane. For interanl use.
virtual void Clear (Option_t *option="")
virtual void Draw (Option_t *option="")
Implementation recommanded for event display. Draw event display to the canvas.
virtual void DrawFrame (Option_t *option="")
virtual void DrawHist (Option_t *option="")
virtual void DriftElectron (TVector3 posGlobal, TVector3 &posFinal, double &driftLength)
virtual double DriftElectronBack (double tb)
virtual void DriftElectronBack (int padID, double tb, TVector3 &posReco, double &driftLength)
virtual void DriftElectronBack (LKPad *pad, double tb, TVector3 &posReco, double &driftLength)
virtual void FillDataToHist ()
Implementation recommanded. Fill data to histograms.
void FillPlane (double i, double j, double tb, double charge, int trackID=-1)
Find pad corresponding to the position (i,j) and fill time-bin by amount of charge.
virtual int FindChannelID (double i, double j)
Implementation recommanded. Find channel using position.
virtual int FindChannelID (int section, int layer, int row)
Implementation recommanded. Find channel using section, layer, row info.
virtual int FindPadID (double i, double j)
virtual int FindPadID (int cobo, int asad, int aget, int chan)
virtual int FindPadID (int section, int layer, int row)
virtual TPad * Get3DEventPad ()
If user wants to place 3D event display other than default canvas, this method should return corresponding TPad.
virtual axis_t GetAxis1 (int iPad=0) const
virtual axis_t GetAxis2 (int iPad=0) const
virtual axis_t GetAxis3 () const
virtual axis_t GetAxisDrift () const
virtual TCanvas * GetCanvas (Option_t *option="")
Implementation recommanded for event display.
LKChannel * GetChannel (int idx)
virtual LKChannelAnalyzer * GetChannelAnalyzer (int id=0)
TObjArray * GetChannelArray ()
LKChannel * GetChannelFast (int idx)
virtual TPad * GetCPad (int iPad)
For grabbing inner pads of canvas.
virtual TH2 * GetHist (Option_t *option="-1")
int GetNChannels ()
virtual int GetNumCPads ()
Get number of inner pads of canvas.
int GetNumPads ()
LKPad * GetPad (double i, double j)
LKPad * GetPad (int cobo, int asad, int aget, int chan)
LKPad * GetPad (int padID)
LKPad * GetPad (int section, int layer, int row)
TObjArray * GetPadArray ()
LKPad * GetPadFast (int idx)
int GetPlaneID () const
double GetPosition () const
virtual TVector3 GetPositionError (int padID)
double GetTbToLength () const
virtual TVector3 GlobalToLocalAxis (TVector3 posGlobal)
Implementation recommanded. Convert global position to local detector plane position.
void GrabNeighborPads (vector< LKPad * > *pads, vector< LKPad * > *neighborPads)
For tracking use.
virtual bool Init ()
virtual bool IsInBoundary (double i, double j)
Implementation recommanded. Return if position (i,j) is inside the effective detector plane boundary.
LKDetectorPlane ()
LKDetectorPlane (const char *name, const char *title)
virtual TVector3 LocalToGlobalAxis (TVector3 posLocal)
virtual double PadDisplacement () const
Return average pad displacement to each other.
bool PadMapChecker ()
bool PadNeighborChecker ()
bool PadPositionChecker (bool checkCorners=true)
virtual void Print (Option_t *option="") const
void PullOutNeighborHits (double x, double y, int range, LKHitArray *neighborHits)
For tracking use.
void PullOutNeighborHits (double x, double y, int range, vector< LKHit * > *neighborHits)
For tracking use.
void PullOutNeighborHits (LKHitArray *hits, LKHitArray *neighborHits)
For tracking use.
void PullOutNeighborHits (TVector2 p, int range, vector< LKHit * > *neighborHits)
For tracking use.
void PullOutNeighborHits (vector< LKHit * > *hits, vector< LKHit * > *neighborHits)
For tracking use.
virtual LKHit * PullOutNextFreeHit ()
For tracking use.
virtual void ResetEvent ()
For tracking use.
virtual void ResetHitMap ()
For tracking use.
virtual bool SetDataFromBranch ()
Implementation recommanded. Set waveform and hit data from input tree branches to pads.
void SetDetector (LKDetector *detector)
void SetDetectorName (TString name)
void SetHitArray (TClonesArray *hitArray)
void SetPadArray (TClonesArray *padArray)
void SetPlaneID (int id)
virtual ~LKDetectorPlane ()
Public Member Functions inherited from LKGear
void AddPar (LKParameterContainer *par)
void AddPar (TString fname)
virtual void AddParameterContainer (LKParameterContainer *par)
virtual void AddParameterContainer (TString fname)
void CreateParameterContainer ()
LKParameterContainer * GetPar () const
LKParameterContainer * GetParameterContainer () const
Int_t GetRank () const
LKGear ()
void SetPar (LKParameterContainer *par)
virtual void SetParameterContainer (LKParameterContainer *par)
virtual void SetRank (Int_t rank)
void SetRun (LKRun *run)
virtual ~LKGear ()
Public Member Functions inherited from LKPadInteractive
void AddInteractivePad (TVirtualPad *pad, TString option="")
virtual void ExecMouseClickEventOnPad (TVirtualPad *pad, double xOnClick, double yOnClick)
int GetPadInteractiveID () const
LKPadInteractive ()
void SetPadInteractiveID (int id)
virtual ~LKPadInteractive ()
Protected Attributes
int fCurrentView = 1
LKParameterContainer fDetectorPar
TString fDetectorParName
vector< int > fDetNameArray
vector< vector< int > > fDetNameIDArray
double fDXPad = 4
double fDZPad = 4
int ****fMapCAACToChannelIndex int * fMapBin1ToPadID
< [cobo][asad][aget][chan] to pad-id mapping
TString fMappingFileName
int fNumAget = 4
int fNumAsad = 4
int fNumChan = 68
int fNumCobo = 6
int fNX = 64
int fNY = 512
int fNZ = 72
int fSelIZ = -1
double fThreshold = 300
bool fUsePixelSpace = false
double fX1
double fX2
double fY1
double fY2
double fZ1
double fZ2
Protected Attributes inherited from LKEvePlane
bool fAccumulateAllEvents = false
int fAccumulateChannel = 0
to accumulate channel waveform
Long64_t fAccumulateEvent1 = 0
first accumulated event id
Long64_t fAccumulateEvent2 = 0
last accumulated event id
Long64_t fAccumulateEvents = 0
to accumulate event in event display
int fBinCtrlAcmltCh
int fBinCtrlAcmltEv
int fBinCtrlChgMenu
int fBinCtrlCurr
int fBinCtrlDrawACh
int fBinCtrlE500
int fBinCtrlEngyMax
int fBinCtrlEngyMin
int fBinCtrlFillAEv
int fBinCtrlFitChan
int fBinCtrlFrst
int fBinCtrlLast
int fBinCtrlNe50
int fBinCtrlNext
int fBinCtrlPalette
int fBinCtrlPr50
int fBinCtrlPrev
int fBinCtrlSavePng
int fBinCtrlSaveRoo
int fBinDrawTrackGf
int fBinFillChACAAC
int fBinFillElectID
int fBinFillHitNHit
int fBinFillRawPrev
bool fBranchIsSet = false
TClonesArray * fChannelGraphArray = nullptr
array of accumulate channel graphs
Long64_t fCountChangeEvent = 0
int fCountChangeOther = 0
int fCountChannelGraph = 0
count number of accumulate channels
int fCountSaveFig = 0
int fCountSavePng = 0
int fCountSaveRoo = 0
int fCurrentMenu = 0
double fDXCanvas = 1200
double fDYCanvas = 700
int fEnergyMax = 1
0 : auto, 1; 4200, >2: fEnergyMax = maximum value
int fEnergyMin = -1
0 : auto, 1; -1
TString fEventDisplayDrawOption = "colz"
TString fFillOptionSelected = ""
bool fFitChannel = false
for finding energy using fChannelAnalyzer
TGraph * fGSelEventDisplay1 = nullptr
TGraph * fGSelEventDisplay2 = nullptr
TH1D * fHistChannelBuffer = nullptr
TH2D * fHistControlEvent1 = nullptr
TH2D * fHistControlEvent2 = nullptr
TH2 * fHistEventDisplay1 = nullptr
TH2 * fHistEventDisplay2 = nullptr
TClonesArray * fHitArray = nullptr
int fNumAccumulateChannels = 0
to accumulate channel waveform
axis_t fPadAxis1 [2] = {LKVector3::kNon, LKVector3::kNon}
axis_t fPadAxis2 [2] = {LKVector3::kNon, LKVector3::kNon}
TPad * fPadChannelBuffer = nullptr
TPad * fPadControlEvent1 = nullptr
TPad * fPadControlEvent2 = nullptr
TPad * fPadEventDisplay1 = nullptr
TPad * fPadEventDisplay2 = nullptr
bool fPaletteIsInverted = false
int fPaletteNumber = 0
TClonesArray * fRawDataArray = nullptr
bool fReturnDraw = false
TString fSavePath = "eve_data"
int fSelPadID = 0
Selected pad id by mouse click.
int fSelRawDataID = 0
Selected raw data by mouse click.
TClonesArray * fTrackArray = nullptr
double fYCCanvas = 230./700
const TString kFillAget = "aget"
const TString kFillAsad = "asad"
const TString kFillCAAC = "caac"
const TString kFillChan = "chan"
const TString kFillCobo = "cobo"
const TString kFillHits = "hit"
const TString kFillNHit = "nhits"
const TString kFillPrev = "preview"
const TString kFillRawD = "raw"
const TString kFillZero = ""
Protected Attributes inherited from LKDetectorPlane
axis_t fAxis1 = LKVector3::kNon
Axis-1 lying in plane. Must be set by input parameter.
axis_t fAxis2 = LKVector3::kNon
Axis-2 lying in plane. Must be set by input parameter.
axis_t fAxis3 = LKVector3::kNon
Axis-3 = Axis-1 x Axis-2 perpendicular to plane.
axis_t fAxisDrift = LKVector3::kNon
Axis perpendicular to plane, in electron drifting direction. Must be set by input parameter.
TCanvas * fCanvas = nullptr
LKChannelAnalyzer * fChannelAnalyzer = nullptr
TObjArray * fChannelArray = nullptr
TCanvas * fCvsChannelBuffer = nullptr
LKDetector * fDetector = nullptr
TString fDetName
int fFreePadIdx = 0
TGraph * fGraphChannelBoundary = nullptr
TGraph * fGraphChannelBoundaryNb [20] = {0}
TH2 * fH2Plane = nullptr
bool fHitDataIsSet = false
bool fPadDataIsSet = false
int fPlaneID = -1
Detector plane id.
double fPosition
Global position of pad plane center.
double fTbToLength = 1
time-bin (tb) to position conversion factor. Must be set by input parameter.
Protected Attributes inherited from LKGear
LKParameterContainer * fPar = nullptr
Int_t fRank = 0
LKRun * fRun = nullptr
Protected Attributes inherited from LKPadInteractive
int fPadInteractiveID = -1
Detailed Description
Definition at line 10 of file LKSiArrayPlane.h.
Constructor & Destructor Documentation
LKSiArrayPlane() [1/2]
LKSiArrayPlane::LKSiArrayPlane ()
LKSiArrayPlane() [2/2]
LKSiArrayPlane::LKSiArrayPlane (const char * name, const char * title)
Definition at line 15 of file LKSiArrayPlane.cpp.
~LKSiArrayPlane()
virtual LKSiArrayPlane::~LKSiArrayPlane () inline virtual
Definition at line 15 of file LKSiArrayPlane.h.
Member Function Documentation
ClickedEventDisplay2()
void LKSiArrayPlane::ClickedEventDisplay2 (double xOnClick, double yOnClick) virtual
Reimplemented from LKEvePlane.
Definition at line 381 of file LKSiArrayPlane.cpp.
References LKEvePlane::fAccumulateChannel, LKEvePlane::fBinCtrlAcmltCh, LKEvePlane::fBinCtrlDrawACh, LKEvePlane::fCountChannelGraph, LKEvePlane::fHistControlEvent2, LKEvePlane::fHistEventDisplay2, FindZFromHistEventDisplay2Bin(), fSelIZ, and UpdateChannelBuffer().
FillDataToHistEventDisplay2()
void LKSiArrayPlane::FillDataToHistEventDisplay2 (Option_t * option = "") virtual
Reimplemented from LKEvePlane.
Definition at line 293 of file LKSiArrayPlane.cpp.
References LKVector3::At(), LKEvePlane::DriftElectronBack(), LKEvePlane::fAccumulateEvents, LKDetectorPlane::fAxisDrift, LKDetectorPlane::fChannelAnalyzer, LKDetectorPlane::fChannelArray, fCurrentView, LKEvePlane::fFillOptionSelected, LKEvePlane::fHistEventDisplay2, LKEvePlane::fHitArray, LKEvePlane::fRawDataArray, LKGear::fRun, fThreshold, fUsePixelSpace, LKDetectorPlane::GetPosition(), and lk_info.
FindPad()
LKPad * LKSiArrayPlane::FindPad (int cobo, int asad, int aget, int chan) virtual
TODO.
Reimplemented from LKEvePlane.
Definition at line 237 of file LKSiArrayPlane.cpp.
References LKDetectorPlane::fChannelArray.
FindPadID()
int LKSiArrayPlane::FindPadID (int cobo, int asad, int aget, int chan) virtual
Reimplemented from LKEvePlane.
Definition at line 232 of file LKSiArrayPlane.cpp.
FindPadIDFromHistEventDisplay1Bin()
int LKSiArrayPlane::FindPadIDFromHistEventDisplay1Bin (int hbin) virtual
Reimplemented from LKEvePlane.
Definition at line 248 of file LKSiArrayPlane.cpp.
References fMapBin1ToPadID.
FindZFromHistEventDisplay2Bin()
int LKSiArrayPlane::FindZFromHistEventDisplay2Bin (int hbin) virtual
Definition at line 397 of file LKSiArrayPlane.cpp.
References LKEvePlane::fHistEventDisplay2.
Referenced by ClickedEventDisplay2().
Get3DEventPad()
TPad * LKSiArrayPlane::Get3DEventPad () virtual
If user wants to place 3D event display other than default canvas, this method should return corresponding TPad.
Reimplemented from LKEvePlane.
Definition at line 253 of file LKSiArrayPlane.cpp.
References fCurrentView, and LKEvePlane::GetPadEventDisplay2().
GetHistChannelBuffer()
TH1D * LKSiArrayPlane::GetHistChannelBuffer () virtual
Reimplemented from LKEvePlane.
Definition at line 216 of file LKSiArrayPlane.cpp.
References LKEvePlane::fHistChannelBuffer.
GetHistEventDisplay1()
TH2 * LKSiArrayPlane::GetHistEventDisplay1 (Option_t * option = "-1") virtual
Reimplemented from LKEvePlane.
Definition at line 152 of file LKSiArrayPlane.cpp.
References LKEvePlane::fHistEventDisplay1, fMapBin1ToPadID, fNX, fNZ, fUsePixelSpace, fX1, fX2, fZ1, and fZ2.
GetHistEventDisplay2()
TH2 * LKSiArrayPlane::GetHistEventDisplay2 (Option_t * option = "-1") virtual
Reimplemented from LKEvePlane.
Definition at line 185 of file LKSiArrayPlane.cpp.
References LKEvePlane::DriftElectronBack(), LKEvePlane::fEnergyMin, LKEvePlane::fHistEventDisplay2, fNY, fNZ, fUsePixelSpace, fZ1, fZ2, and y2.
Init()
bool LKSiArrayPlane::Init () virtual
Implementation recommanded. Init() method should implement pad information (id, position, neighbor) and add channel using AddChannel() or AddPad() method. All parameters should be configured such as axis-1,2,3, fPosition, fTbToLength from parameter container.
Reimplemented from LKEvePlane.
Definition at line 20 of file LKSiArrayPlane.cpp.
References LKDetectorPlane::AddChannel(), LKDetectorPlane::fChannelArray, fDetectorParName, LKDetectorPlane::fDetName, fDetNameArray, fDetNameIDArray, fMappingFileName, fNumAget, fNumAsad, fNumChan, fNumCobo, LKGear::fPar, LKEvePlane::Init(), lk_error, lk_info, and LKEvePlane::Print().
UpdateChannelBuffer()
void LKSiArrayPlane::UpdateChannelBuffer () virtual
Reimplemented from LKEvePlane.
Definition at line 404 of file LKSiArrayPlane.cpp.
References LKEvePlane::Draw(), LKDetectorPlane::fChannelArray, LKEvePlane::fChannelGraphArray, LKEvePlane::fCountChannelGraph, LKEvePlane::fGSelEventDisplay2, LKEvePlane::fHistChannelBuffer, fNX, fNZ, LKEvePlane::fPadChannelBuffer, LKEvePlane::fPadEventDisplay2, LKEvePlane::fPaletteNumber, LKEvePlane::fRawDataArray, fSelIZ, fUsePixelSpace, lk_info, SetPoint(), LKEvePlane::UpdateChannelBuffer(), x0, y0, y2, z1, and z2.
Referenced by ClickedEventDisplay2().
UpdateEventDisplay1()
void LKSiArrayPlane::UpdateEventDisplay1 () virtual
Reimplemented from LKEvePlane.
Definition at line 262 of file LKSiArrayPlane.cpp.
References LKEvePlane::fPadEventDisplay1, and LKEvePlane::UpdateEventDisplay1().
UpdateEventDisplay2()
void LKSiArrayPlane::UpdateEventDisplay2 () virtual
Reimplemented from LKEvePlane.
Definition at line 268 of file LKSiArrayPlane.cpp.
References LKEvePlane::Draw(), fCurrentView, LKEvePlane::fEnergyMax, LKEvePlane::fEnergyMin, LKEvePlane::fEventDisplayDrawOption, LKEvePlane::fHistEventDisplay2, and LKEvePlane::fPadEventDisplay2.
Member Data Documentation
fCurrentView
int LKSiArrayPlane::fCurrentView = 1 protected
Definition at line 67 of file LKSiArrayPlane.h.
Referenced by FillDataToHistEventDisplay2(), Get3DEventPad(), and UpdateEventDisplay2().
fDetectorPar
LKParameterContainer LKSiArrayPlane::fDetectorPar protected
Definition at line 72 of file LKSiArrayPlane.h.
fDetectorParName
TString LKSiArrayPlane::fDetectorParName protected
Definition at line 58 of file LKSiArrayPlane.h.
Referenced by Init().
fDetNameArray
vector<int> LKSiArrayPlane::fDetNameArray protected
Definition at line 73 of file LKSiArrayPlane.h.
Referenced by Init().
fDetNameIDArray
vector<vector<int> > LKSiArrayPlane::fDetNameIDArray protected
Definition at line 74 of file LKSiArrayPlane.h.
Referenced by Init().
fDXPad
double LKSiArrayPlane::fDXPad = 4 protected
Definition at line 55 of file LKSiArrayPlane.h.
fDZPad
double LKSiArrayPlane::fDZPad = 4 protected
Definition at line 54 of file LKSiArrayPlane.h.
fMapBin1ToPadID
int**** fMapCAACToChannelIndex int* LKSiArrayPlane::fMapBin1ToPadID protected
< [cobo][asad][aget][chan] to pad-id mapping
histogram bin to pad-id mapping
Definition at line 65 of file LKSiArrayPlane.h.
Referenced by FindPadIDFromHistEventDisplay1Bin(), and GetHistEventDisplay1().
fMappingFileName
TString LKSiArrayPlane::fMappingFileName protected
Definition at line 57 of file LKSiArrayPlane.h.
Referenced by Init().
fNumAget
int LKSiArrayPlane::fNumAget = 4 protected
Definition at line 61 of file LKSiArrayPlane.h.
Referenced by Init().
fNumAsad
int LKSiArrayPlane::fNumAsad = 4 protected
Definition at line 60 of file LKSiArrayPlane.h.
Referenced by Init().
fNumChan
int LKSiArrayPlane::fNumChan = 68 protected
Definition at line 62 of file LKSiArrayPlane.h.
Referenced by Init().
fNumCobo
int LKSiArrayPlane::fNumCobo = 6 protected
Definition at line 59 of file LKSiArrayPlane.h.
Referenced by Init().
fNX
int LKSiArrayPlane::fNX = 64 protected
Definition at line 45 of file LKSiArrayPlane.h.
Referenced by GetHistEventDisplay1(), and UpdateChannelBuffer().
fNY
int LKSiArrayPlane::fNY = 512 protected
Definition at line 48 of file LKSiArrayPlane.h.
Referenced by GetHistEventDisplay2().
fNZ
int LKSiArrayPlane::fNZ = 72 protected
Definition at line 51 of file LKSiArrayPlane.h.
Referenced by GetHistEventDisplay1(), GetHistEventDisplay2(), and UpdateChannelBuffer().
fSelIZ
int LKSiArrayPlane::fSelIZ = -1 protected
Definition at line 69 of file LKSiArrayPlane.h.
Referenced by ClickedEventDisplay2(), and UpdateChannelBuffer().
fThreshold
double LKSiArrayPlane::fThreshold = 300 protected
Definition at line 68 of file LKSiArrayPlane.h.
Referenced by FillDataToHistEventDisplay2().
fUsePixelSpace
bool LKSiArrayPlane::fUsePixelSpace = false protected
Definition at line 43 of file LKSiArrayPlane.h.
Referenced by FillDataToHistEventDisplay2(), GetHistEventDisplay1(), GetHistEventDisplay2(), and UpdateChannelBuffer().
fX1
double LKSiArrayPlane::fX1 protected
Definition at line 46 of file LKSiArrayPlane.h.
Referenced by GetHistEventDisplay1().
fX2
double LKSiArrayPlane::fX2 protected
Definition at line 47 of file LKSiArrayPlane.h.
Referenced by GetHistEventDisplay1().
fY1
double LKSiArrayPlane::fY1 protected
Definition at line 50 of file LKSiArrayPlane.h.
fY2
double LKSiArrayPlane::fY2 protected
Definition at line 49 of file LKSiArrayPlane.h.
fZ1
double LKSiArrayPlane::fZ1 protected
Definition at line 52 of file LKSiArrayPlane.h.
Referenced by GetHistEventDisplay1(), and GetHistEventDisplay2().
fZ2
double LKSiArrayPlane::fZ2 protected
Definition at line 53 of file LKSiArrayPlane.h.
Referenced by GetHistEventDisplay1(), and GetHistEventDisplay2().
The documentation for this class was generated from the following files:
LKSiArrayPlane.h
LKSiArrayPlane.cpp