lilak: LKPadInteractiveManager Class Reference
LKPadInteractiveManager Class Reference
#include <LKPadInteractiveManager.h>
Public Member Functions
void Add (LKPadInteractive *interactive)
void Add (LKPadInteractive *interactive, TVirtualPad *pad, TString option="")
LKPadInteractive * GetPadInteractive (int id)
LKPadInteractiveManager ()
virtual ~LKPadInteractiveManager ()
Static Public Member Functions
static LKPadInteractiveManager * GetManager ()
Get LKPadInteractiveManager static pointer.
static void MouseClickEventOnPad ()
Private Attributes
int fCountPadInteractives = fIndexPadInteractive0
const int fIndexPadInteractive0 = 1100
TObjArray * fPadInteractiveArray = nullptr
Static Private Attributes
static LKPadInteractiveManager * fInstance
Detailed Description
Definition at line 9 of file LKPadInteractiveManager.h.
Constructor & Destructor Documentation
LKPadInteractiveManager()
LKPadInteractiveManager::LKPadInteractiveManager ()
Definition at line 20 of file LKPadInteractiveManager.cpp.
References fInstance, and fPadInteractiveArray.
~LKPadInteractiveManager()
virtual LKPadInteractiveManager::~LKPadInteractiveManager () inline virtual
Definition at line 15 of file LKPadInteractiveManager.h.
Member Function Documentation
Add() [1/2]
void LKPadInteractiveManager::Add (LKPadInteractive * interactive)
Definition at line 26 of file LKPadInteractiveManager.cpp.
References Add(), fCountPadInteractives, and fPadInteractiveArray.
Referenced by Add(), and Add().
Add() [2/2]
void LKPadInteractiveManager::Add (LKPadInteractive * interactive, TVirtualPad * pad, TString option = "")
Definition at line 36 of file LKPadInteractiveManager.cpp.
References Add(), fCountPadInteractives, and fPadInteractiveArray.
GetManager()
static LKPadInteractiveManager * LKPadInteractiveManager::GetManager () static
Get LKPadInteractiveManager static pointer.
Referenced by LKPadInteractive::AddInteractivePad(), and MouseClickEventOnPad().
GetPadInteractive()
LKPadInteractive * LKPadInteractiveManager::GetPadInteractive (int id) inline
Definition at line 20 of file LKPadInteractiveManager.h.
References fIndexPadInteractive0, and fPadInteractiveArray.
Referenced by MouseClickEventOnPad().
MouseClickEventOnPad()
void LKPadInteractiveManager::MouseClickEventOnPad () static
Definition at line 51 of file LKPadInteractiveManager.cpp.
References GetManager(), and GetPadInteractive().
Member Data Documentation
fCountPadInteractives
int LKPadInteractiveManager::fCountPadInteractives = fIndexPadInteractive0 private
Definition at line 30 of file LKPadInteractiveManager.h.
Referenced by Add(), and Add().
fIndexPadInteractive0
const int LKPadInteractiveManager::fIndexPadInteractive0 = 1100 private
Definition at line 29 of file LKPadInteractiveManager.h.
Referenced by GetPadInteractive().
fInstance
LKPadInteractiveManager* LKPadInteractiveManager::fInstance static private
Definition at line 25 of file LKPadInteractiveManager.h.
Referenced by LKPadInteractiveManager().
fPadInteractiveArray
TObjArray* LKPadInteractiveManager::fPadInteractiveArray = nullptr private
Definition at line 27 of file LKPadInteractiveManager.h.
Referenced by Add(), Add(), GetPadInteractive(), and LKPadInteractiveManager().
The documentation for this class was generated from the following files:
LKPadInteractiveManager.h
LKPadInteractiveManager.cpp