LILAK: LKWindowManager Class Reference
LKWindowManager Class Reference
#include <LKWindowManager.h>
Public Member Functions
TCanvas * Canvas (const char *name)
TCanvas * Canvas (const char *name)
TCanvas * Canvas (const char *name)
TCanvas * Canvas (TString name="cvs_lilak", Int_t mode=0, Double_t value1=1, Double_t value2=-1, Double_t value3=-1)
TCanvas * CanvasDefault (TString name="cvs_lilak", Double_t ratio=1)
TCanvas * CanvasFull (const char *name)
TCanvas * CanvasFull (const char *name)
TCanvas * CanvasFull (const char *name)
TCanvas * CanvasFull (TString name="cvs_lilak", Double_t ratio=1, Double_t ratio2=-1)
TCanvas * CanvasR (const char *name, Int_t w=0, Int_t h=0, Int_t ww=0, Int_t wh=0, Double_t rw=0, Double_t rh=0)
TCanvas * CanvasR (const char *name, Int_t w=0, Int_t h=0, Int_t ww=0, Int_t wh=0, Double_t rw=0, Double_t rh=0)
TCanvas * CanvasR (const char *name, Int_t w=0, Int_t h=0, Int_t ww=0, Int_t wh=0, Double_t rw=0, Double_t rh=0)
TCanvas * CanvasResize (TString name, Int_t width0, Int_t height0, Double_t ratio=-1)
TCanvas * CanvasRH (const char *name, Double_t rh=0.5)
TCanvas * CanvasRH (const char *name, Double_t rh=0.5)
TCanvas * CanvasRH (const char *name, Double_t rh=0.5)
TCanvas * CanvasRW (const char *name, Double_t rw=0.4)
TCanvas * CanvasRW (const char *name, Double_t rw=0.4)
TCanvas * CanvasRW (const char *name, Double_t rw=0.4)
TCanvas * CanvasSquare (TString name="cvs_lilak", Double_t ratio=1)
void Clear (Option_t *option="")
void Clear (Option_t *option="")
void Clear (Option_t *option="")
void Clear (Option_t *option="")
TString ConfigureName (TString name)
void FixCanvasPosition ()
UInt_t GetDHFull () const
UInt_t GetDHFull () const
UInt_t GetDHFull () const
UInt_t GetDWFull () const
UInt_t GetDWFull () const
UInt_t GetDWFull () const
UInt_t GetHCurrentDisplay () const
Int_t GetHDisplay () const
Int_t GetHDisplay () const
Int_t GetHDisplay () const
UInt_t GetWCurrentDisplay () const
Int_t GetWDisplay () const
Int_t GetWDisplay () const
Int_t GetWDisplay () const
Int_t GetXCurrentDisplay () const
Int_t GetYCurrentDisplay () const
bool Init ()
bool Init ()
bool Init ()
bool Init ()
LKWindowManager ()
LKWindowManager ()
LKWindowManager ()
LKWindowManager ()
TCanvas * NewCanvas (TString name, TString title, Int_t x, Int_t y, Int_t width, Int_t height)
void Print (Option_t *option="") const
void Print (Option_t *option="") const
void Print (Option_t *option="") const
void Print (Option_t *option="") const
void SetDeadFrame (UInt_t left, UInt_t right, UInt_t bottom, UInt_t top)
void SetDeadFrame (UInt_t left, UInt_t right, UInt_t bottom, UInt_t top)
void SetDeadFrame (UInt_t left, UInt_t right, UInt_t bottom, UInt_t top)
void SetDeadFrame (UInt_t left, UInt_t right, UInt_t bottom, UInt_t top)
void SetDeadFrameBottom (UInt_t val)
void SetDeadFrameBottom (UInt_t val)
void SetDeadFrameBottom (UInt_t val)
void SetDeadFrameBottom (UInt_t val)
void SetDeadFrameLeft (UInt_t val)
void SetDeadFrameLeft (UInt_t val)
void SetDeadFrameLeft (UInt_t val)
void SetDeadFrameLeft (UInt_t val)
void SetDeadFrameRight (UInt_t val)
void SetDeadFrameRight (UInt_t val)
void SetDeadFrameRight (UInt_t val)
void SetDeadFrameRight (UInt_t val)
void SetDeadFrameTop (UInt_t val)
void SetDeadFrameTop (UInt_t val)
void SetDeadFrameTop (UInt_t val)
void SetDeadFrameTop (UInt_t val)
void SetDHCanvas (UInt_t hCanvas)
void SetDHCanvas (UInt_t hCanvas)
void SetDHCanvas (UInt_t hCanvas)
void SetDHSpacing (UInt_t dhCanvas)
void SetDHSpacing (UInt_t dhCanvas)
void SetDHSpacing (UInt_t dhCanvas)
void SetDWCanvas (UInt_t wCanvas)
void SetDWCanvas (UInt_t wCanvas)
void SetDWCanvas (UInt_t wCanvas)
void SetDWSpacing (UInt_t dwCanvas)
void SetDWSpacing (UInt_t dwCanvas)
void SetDWSpacing (UInt_t dwCanvas)
void SetGlobalScale (Double_t xScale, Double_t yScale)
void SetGlobalScale (Double_t xScale, Double_t yScale)
void SetGlobalScale (Double_t xScale, Double_t yScale)
void SetHCanvas (UInt_t hCanvas)
void SetHSpacing (UInt_t dhCanvas)
Double_t SetRatio (Double_t ratio, Double_t defaultValue=1)
void SetWCanvas (UInt_t wCanvas)
void SetWSpacing (UInt_t dwCanvas)
void UpdateNextCanvasPosition ()
virtual ~LKWindowManager ()
virtual ~LKWindowManager ()
virtual ~LKWindowManager ()
virtual ~LKWindowManager ()
Static Public Member Functions
static LKWindowManager * GetWindowManager ()
static LKWindowManager * GetWindowManager ()
static LKWindowManager * GetWindowManager ()
static LKWindowManager * GetWindowManager ()
Public Attributes
const Int_t kDefault = 0
const Int_t kFull = 1
const Int_t kResize = 3
const Int_t kSquare = 2
Private Member Functions
ClassDef (LKWindowManager, 1)
ClassDef (LKWindowManager, 1)
default height spacing of canvas
ClassDef (LKWindowManager, 1)
default height spacing of canvas
ClassDef (LKWindowManager, 1)
default height spacing of canvas
void ConfigureDisplay ()
void ConfigureDisplay ()
void ConfigureDisplay ()
void ConfigureDisplay ()
Private Attributes
int fCountCanvases = 0
UInt_t fDeadFrame [4] = {0}
height of current display
UInt_t fDeadFrameSize [4] = {25,25,80,50}
height of current display
Int_t fDHCanvas = 450
default width of canvas
UInt_t fDHFull = 0
width of current display
Int_t fDHSpacing = 25
default width spacing of canvas
Int_t fDWCanvas = 600
height position of next canvas
UInt_t fDWFull = 0
relative height position of current display from main display
Int_t fDWSpacing = 25
default height of canvas
bool fFixCanvasPosition = true
default height spacing of canvas
Double_t fGeneralResizeFactor = 1
height position of next canvas
Int_t fHCurrent = 0
width position of next canvas
UInt_t fHCurrentDisplay = 0
width of current display
Int_t fHDefault = fHDefaultOrigin
default width of canvas
Int_t fHDefaultOrigin = 500
default width of canvas assuming that width of the display is 1250
Int_t fHDisplay = -1
relative width position of current display from main display
Double_t fHGlobalScale = 1
default width spacing of canvas
Int_t fHSpacing = 25
default width spacing of canvas
Int_t fWCurrent = 0
height of the top bar
UInt_t fWCurrentDisplay = 0
relative height position of current display from main display
Int_t fWDefault = fWDefaultOrigin
default height of canvas assuming that width of the display is 1250
Int_t fWDefaultOrigin = 700
Int_t fWDisplay = -1
Double_t fWGlobalScale = 1
default height spacing of canvas
Int_t fWSpacing = 25
default height of canvas
Int_t fXCurrentCanvas = 0
Int_t fXCurrentDisplay = -1
Int_t fYCurrentCanvas = 0
width position of next canvas
Int_t fYCurrentDisplay = -1
relative width position of current display from main display
Static Private Attributes
static LKWindowManager * fInstance = nullptr
Detailed Description
Definition at line 15 of file LKWindowManager.h.
Constructor & Destructor Documentation
LKWindowManager() [1/4]
LKWindowManager::LKWindowManager ()
Definition at line 18 of file LKWindowManager.cpp.
References Init().
Referenced by GetWindowManager().
~LKWindowManager() [1/4]
virtual LKWindowManager::~LKWindowManager () inline virtual
Definition at line 19 of file LKWindowManager.h.
LKWindowManager() [2/4]
LKWindowManager::LKWindowManager ()
~LKWindowManager() [2/4]
virtual LKWindowManager::~LKWindowManager () inline virtual
Definition at line 22 of file macros_detectorplane/ejungwooA.h.
LKWindowManager() [3/4]
LKWindowManager::LKWindowManager ()
~LKWindowManager() [3/4]
virtual LKWindowManager::~LKWindowManager () inline virtual
Definition at line 22 of file macros_hough/ejungwooA.h.
LKWindowManager() [4/4]
LKWindowManager::LKWindowManager ()
~LKWindowManager() [4/4]
virtual LKWindowManager::~LKWindowManager () inline virtual
Definition at line 22 of file macros_psa/ejungwooA.h.
Member Function Documentation
Canvas() [1/4]
TCanvas * LKWindowManager::Canvas (const char * name) inline
Definition at line 68 of file macros_detectorplane/ejungwooA.h.
References CanvasR().
Canvas() [2/4]
TCanvas * LKWindowManager::Canvas (const char * name) inline
Definition at line 68 of file macros_hough/ejungwooA.h.
References CanvasR().
Canvas() [3/4]
TCanvas * LKWindowManager::Canvas (const char * name) inline
Definition at line 68 of file macros_psa/ejungwooA.h.
References CanvasR().
Canvas() [4/4]
TCanvas * LKWindowManager::Canvas (TString name = "cvs_lilak", Int_t mode = 0, Double_t value1 = 1, Double_t value2 = -1, Double_t value3 = -1)
mode = 0 (kDefault) : default canvas with fWDefault x fHDefault (600 x 450). mode = 1 (kFull) : full size canvas that fits in the current display. mode = 2 (kSquare) : square canvas. mode = 3 (kResize) : resize canvas from given w,h = (value1, value2) to show similar scale in the current display.
Definition at line 105 of file LKWindowManager.cpp.
References CanvasDefault(), CanvasFull(), CanvasResize(), CanvasSquare(), kDefault, kFull, and kResize.
CanvasDefault()
TCanvas * LKWindowManager::CanvasDefault (TString name = "cvs_lilak", Double_t ratio = 1)
Definition at line 151 of file LKWindowManager.cpp.
References cvs, fHDefault, fWDefault, fXCurrentCanvas, fYCurrentCanvas, NewCanvas(), SetRatio(), and UpdateNextCanvasPosition().
Referenced by Canvas().
CanvasFull() [1/4]
TCanvas * LKWindowManager::CanvasFull (const char * name) inline
Definition at line 71 of file macros_detectorplane/ejungwooA.h.
References CanvasR().
CanvasFull() [2/4]
TCanvas * LKWindowManager::CanvasFull (const char * name) inline
Definition at line 71 of file macros_hough/ejungwooA.h.
References CanvasR().
CanvasFull() [3/4]
TCanvas * LKWindowManager::CanvasFull (const char * name) inline
Definition at line 71 of file macros_psa/ejungwooA.h.
References CanvasR().
CanvasFull() [4/4]
TCanvas * LKWindowManager::CanvasFull (TString name = "cvs_lilak", Double_t ratio = 1, Double_t ratio2 = -1)
Definition at line 161 of file LKWindowManager.cpp.
References cvs, fHCurrentDisplay, fWCurrentDisplay, fXCurrentCanvas, fYCurrentCanvas, NewCanvas(), SetRatio(), and UpdateNextCanvasPosition().
Referenced by Canvas().
CanvasR() [1/3]
TCanvas * LKWindowManager::CanvasR (const char * name, Int_t w = 0, Int_t h = 0, Int_t ww = 0, Int_t wh = 0, Double_t rw = 0, Double_t rh = 0)
Parameters
w
w(x) position of the canvas in the display
h
h(y) position of the canvas in the display
ww
width of the canvas
wh
height of the canvas
rw
Ratio of canvas width relative to the full display size
If rw>0 and rh<=0, canvas size is (rw*fDWFull, rw*fDWFull*ww/wh) (fDWFull and fDHFull is the width and height of the current display)
If both rw and rh are >0, canvas size is (rw*fDWFull, rh*fDHFull)
rh
Ratio of canvas height relative to the full display size
If rw<=0 and rh>0, canvas size is (rh*fDHFull, rh*fDHFull*wh/ww) (fDWFull and fDHFull is the width and height of the current display)
If both rw and rh are >0, canvas size is (rw*fDWFull, rh*fDHFull)
Definition at line 212 of file macros_detectorplane/ejungwooA.h.
References cvs, fDHCanvas, fDHFull, fDHSpacing, fDWCanvas, fDWFull, fDWSpacing, fHCurrent, fHGlobalScale, fWCurrent, and fWGlobalScale.
Referenced by Canvas(), CanvasFull(), CanvasRH(), and CanvasRW().
CanvasR() [2/3]
TCanvas * LKWindowManager::CanvasR (const char * name, Int_t w = 0, Int_t h = 0, Int_t ww = 0, Int_t wh = 0, Double_t rw = 0, Double_t rh = 0)
Parameters
w
w(x) position of the canvas in the display
h
h(y) position of the canvas in the display
ww
width of the canvas
wh
height of the canvas
rw
Ratio of canvas width relative to the full display size
If rw>0 and rh<=0, canvas size is (rw*fDWFull, rw*fDWFull*ww/wh) (fDWFull and fDHFull is the width and height of the current display)
If both rw and rh are >0, canvas size is (rw*fDWFull, rh*fDHFull)
rh
Ratio of canvas height relative to the full display size
If rw<=0 and rh>0, canvas size is (rh*fDHFull, rh*fDHFull*wh/ww) (fDWFull and fDHFull is the width and height of the current display)
If both rw and rh are >0, canvas size is (rw*fDWFull, rh*fDHFull)
CanvasR() [3/3]
TCanvas * LKWindowManager::CanvasR (const char * name, Int_t w = 0, Int_t h = 0, Int_t ww = 0, Int_t wh = 0, Double_t rw = 0, Double_t rh = 0)
Parameters
w
w(x) position of the canvas in the display
h
h(y) position of the canvas in the display
ww
width of the canvas
wh
height of the canvas
rw
Ratio of canvas width relative to the full display size
If rw>0 and rh<=0, canvas size is (rw*fDWFull, rw*fDWFull*ww/wh) (fDWFull and fDHFull is the width and height of the current display)
If both rw and rh are >0, canvas size is (rw*fDWFull, rh*fDHFull)
rh
Ratio of canvas height relative to the full display size
If rw<=0 and rh>0, canvas size is (rh*fDHFull, rh*fDHFull*wh/ww) (fDWFull and fDHFull is the width and height of the current display)
If both rw and rh are >0, canvas size is (rw*fDWFull, rh*fDHFull)
CanvasResize()
TCanvas * LKWindowManager::CanvasResize (TString name, Int_t width0, Int_t height0, Double_t ratio = -1)
Definition at line 186 of file LKWindowManager.cpp.
References cvs, fGeneralResizeFactor, fHCurrentDisplay, fWCurrentDisplay, fXCurrentCanvas, fYCurrentCanvas, NewCanvas(), SetRatio(), and UpdateNextCanvasPosition().
Referenced by Canvas().
CanvasRH() [1/3]
TCanvas * LKWindowManager::CanvasRH (const char * name, Double_t rh = 0.5) inline
Definition at line 69 of file macros_detectorplane/ejungwooA.h.
References CanvasR().
CanvasRH() [2/3]
TCanvas * LKWindowManager::CanvasRH (const char * name, Double_t rh = 0.5) inline
Definition at line 69 of file macros_hough/ejungwooA.h.
References CanvasR().
CanvasRH() [3/3]
TCanvas * LKWindowManager::CanvasRH (const char * name, Double_t rh = 0.5) inline
Definition at line 69 of file macros_psa/ejungwooA.h.
References CanvasR().
CanvasRW() [1/3]
TCanvas * LKWindowManager::CanvasRW (const char * name, Double_t rw = 0.4) inline
Definition at line 70 of file macros_detectorplane/ejungwooA.h.
References CanvasR().
CanvasRW() [2/3]
TCanvas * LKWindowManager::CanvasRW (const char * name, Double_t rw = 0.4) inline
Definition at line 70 of file macros_hough/ejungwooA.h.
References CanvasR().
CanvasRW() [3/3]
TCanvas * LKWindowManager::CanvasRW (const char * name, Double_t rw = 0.4) inline
Definition at line 70 of file macros_psa/ejungwooA.h.
References CanvasR().
CanvasSquare()
TCanvas * LKWindowManager::CanvasSquare (TString name = "cvs_lilak", Double_t ratio = 1)
Definition at line 174 of file LKWindowManager.cpp.
References cvs, fHCurrentDisplay, fWCurrentDisplay, fXCurrentCanvas, fYCurrentCanvas, NewCanvas(), SetRatio(), and UpdateNextCanvasPosition().
Referenced by Canvas().
ClassDef() [1/4]
LKWindowManager::ClassDef (LKWindowManager , 1) private
ClassDef() [2/4]
LKWindowManager::ClassDef (LKWindowManager , 1) private
default height spacing of canvas
ClassDef() [3/4]
LKWindowManager::ClassDef (LKWindowManager , 1) private
default height spacing of canvas
ClassDef() [4/4]
LKWindowManager::ClassDef (LKWindowManager , 1) private
default height spacing of canvas
Clear() [1/4]
void LKWindowManager::Clear (Option_t * option = "")
Definition at line 33 of file LKWindowManager.cpp.
References fDeadFrameSize, fHCurrentDisplay, fHDefault, fHSpacing, fWCurrentDisplay, fWDefault, fWSpacing, fXCurrentCanvas, fXCurrentDisplay, fYCurrentCanvas, and fYCurrentDisplay.
Clear() [2/4]
void LKWindowManager::Clear (Option_t * option = "")
Clear() [3/4]
void LKWindowManager::Clear (Option_t * option = "")
Clear() [4/4]
void LKWindowManager::Clear (Option_t * option = "")
ConfigureDisplay() [1/4]
void LKWindowManager::ConfigureDisplay () private
Definition at line 70 of file LKWindowManager.cpp.
References e_info, fDeadFrameSize, fGeneralResizeFactor, fHCurrentDisplay, fHDefault, fHDefaultOrigin, fWCurrentDisplay, fWDefault, fWDefaultOrigin, fXCurrentCanvas, fXCurrentDisplay, fYCurrentCanvas, and fYCurrentDisplay.
Referenced by Init().
ConfigureDisplay() [2/4]
void LKWindowManager::ConfigureDisplay () private
ConfigureDisplay() [3/4]
void LKWindowManager::ConfigureDisplay () private
ConfigureDisplay() [4/4]
void LKWindowManager::ConfigureDisplay () private
ConfigureName()
TString LKWindowManager::ConfigureName (TString name)
Definition at line 133 of file LKWindowManager.cpp.
References fCountCanvases.
Referenced by NewCanvas().
FixCanvasPosition()
void LKWindowManager::FixCanvasPosition () inline
Definition at line 48 of file LKWindowManager.h.
References fFixCanvasPosition.
GetDHFull() [1/3]
UInt_t LKWindowManager::GetDHFull () const inline
Definition at line 32 of file macros_detectorplane/ejungwooA.h.
References fDHFull.
GetDHFull() [2/3]
UInt_t LKWindowManager::GetDHFull () const inline
Definition at line 32 of file macros_hough/ejungwooA.h.
References fDHFull.
GetDHFull() [3/3]
UInt_t LKWindowManager::GetDHFull () const inline
Definition at line 32 of file macros_psa/ejungwooA.h.
References fDHFull.
GetDWFull() [1/3]
UInt_t LKWindowManager::GetDWFull () const inline
Definition at line 31 of file macros_detectorplane/ejungwooA.h.
References fDWFull.
GetDWFull() [2/3]
UInt_t LKWindowManager::GetDWFull () const inline
Definition at line 31 of file macros_hough/ejungwooA.h.
References fDWFull.
GetDWFull() [3/3]
UInt_t LKWindowManager::GetDWFull () const inline
Definition at line 31 of file macros_psa/ejungwooA.h.
References fDWFull.
GetHCurrentDisplay()
UInt_t LKWindowManager::GetHCurrentDisplay () const inline
Definition at line 29 of file LKWindowManager.h.
References fHCurrentDisplay.
GetHDisplay() [1/3]
Int_t LKWindowManager::GetHDisplay () const inline
Definition at line 30 of file macros_detectorplane/ejungwooA.h.
References fHDisplay.
GetHDisplay() [2/3]
Int_t LKWindowManager::GetHDisplay () const inline
Definition at line 30 of file macros_hough/ejungwooA.h.
References fHDisplay.
GetHDisplay() [3/3]
Int_t LKWindowManager::GetHDisplay () const inline
Definition at line 30 of file macros_psa/ejungwooA.h.
References fHDisplay.
GetWCurrentDisplay()
UInt_t LKWindowManager::GetWCurrentDisplay () const inline
Definition at line 28 of file LKWindowManager.h.
References fWCurrentDisplay.
GetWDisplay() [1/3]
Int_t LKWindowManager::GetWDisplay () const inline
Definition at line 29 of file macros_detectorplane/ejungwooA.h.
References fWDisplay.
GetWDisplay() [2/3]
Int_t LKWindowManager::GetWDisplay () const inline
Definition at line 29 of file macros_hough/ejungwooA.h.
References fWDisplay.
GetWDisplay() [3/3]
Int_t LKWindowManager::GetWDisplay () const inline
Definition at line 29 of file macros_psa/ejungwooA.h.
References fWDisplay.
GetWindowManager() [1/4]
LKWindowManager * LKWindowManager::GetWindowManager () static
Definition at line 12 of file LKWindowManager.cpp.
References fInstance, and LKWindowManager().
Referenced by ejungwoo::Batch(), ejungwoo::Canvas(), ejungwoo::Canvas(), LKHTLineTracker::Draw(), draw_energy(), draw_padplane(), LKEveTask::DrawEve3D(), example_psa(), example_tool(), LKDetectorPlane::GetCanvas(), LKEvePlane::GetCanvas(), TTMicromegas::GetCanvas(), LKGETChannelViewer::Init(), run_eve(), test(), test_chana(), test_psa(), and httask::TransformAndSelectHits().
GetWindowManager() [2/4]
static LKWindowManager * LKWindowManager::GetWindowManager () static
GetWindowManager() [3/4]
static LKWindowManager * LKWindowManager::GetWindowManager () static
GetWindowManager() [4/4]
static LKWindowManager * LKWindowManager::GetWindowManager () static
GetXCurrentDisplay()
Int_t LKWindowManager::GetXCurrentDisplay () const inline
Definition at line 26 of file LKWindowManager.h.
References fXCurrentDisplay.
GetYCurrentDisplay()
Int_t LKWindowManager::GetYCurrentDisplay () const inline
Definition at line 27 of file LKWindowManager.h.
References fYCurrentDisplay.
Init() [1/4]
bool LKWindowManager::Init ()
Definition at line 23 of file LKWindowManager.cpp.
References ConfigureDisplay(), and e_info.
Referenced by LKWindowManager().
Init() [2/4]
bool LKWindowManager::Init ()
Init() [3/4]
bool LKWindowManager::Init ()
Init() [4/4]
bool LKWindowManager::Init ()
NewCanvas()
TCanvas * LKWindowManager::NewCanvas (TString name, TString title, Int_t x, Int_t y, Int_t width, Int_t height)
Definition at line 141 of file LKWindowManager.cpp.
References ConfigureName(), cvs, fCountCanvases, fXCurrentCanvas, and fYCurrentCanvas.
Referenced by CanvasDefault(), CanvasFull(), CanvasResize(), and CanvasSquare().
Print() [1/4]
void LKWindowManager::Print (Option_t * option = "") const
Definition at line 52 of file LKWindowManager.cpp.
References e_info, fDeadFrameSize, fHCurrentDisplay, fHDefault, fHSpacing, fWCurrentDisplay, fWDefault, fWSpacing, fXCurrentCanvas, fXCurrentDisplay, fYCurrentCanvas, and fYCurrentDisplay.
Print() [2/4]
void LKWindowManager::Print (Option_t * option = "") const
Print() [3/4]
void LKWindowManager::Print (Option_t * option = "") const
Print() [4/4]
void LKWindowManager::Print (Option_t * option = "") const
SetDeadFrame() [1/4]
void LKWindowManager::SetDeadFrame (UInt_t left, UInt_t right, UInt_t bottom, UInt_t top) inline
Definition at line 35 of file LKWindowManager.h.
References SetDeadFrameBottom(), SetDeadFrameLeft(), SetDeadFrameRight(), and SetDeadFrameTop().
SetDeadFrame() [2/4]
void LKWindowManager::SetDeadFrame (UInt_t left, UInt_t right, UInt_t bottom, UInt_t top) inline
Definition at line 51 of file macros_detectorplane/ejungwooA.h.
References SetDeadFrameBottom(), SetDeadFrameLeft(), SetDeadFrameRight(), and SetDeadFrameTop().
SetDeadFrame() [3/4]
void LKWindowManager::SetDeadFrame (UInt_t left, UInt_t right, UInt_t bottom, UInt_t top) inline
Definition at line 51 of file macros_hough/ejungwooA.h.
References SetDeadFrameBottom(), SetDeadFrameLeft(), SetDeadFrameRight(), and SetDeadFrameTop().
SetDeadFrame() [4/4]
void LKWindowManager::SetDeadFrame (UInt_t left, UInt_t right, UInt_t bottom, UInt_t top) inline
Definition at line 51 of file macros_psa/ejungwooA.h.
References SetDeadFrameBottom(), SetDeadFrameLeft(), SetDeadFrameRight(), and SetDeadFrameTop().
SetDeadFrameBottom() [1/4]
void LKWindowManager::SetDeadFrameBottom (UInt_t val)
Definition at line 94 of file LKWindowManager.cpp.
References fDeadFrameSize, and fWCurrentDisplay.
Referenced by SetDeadFrame().
SetDeadFrameBottom() [2/4]
void LKWindowManager::SetDeadFrameBottom (UInt_t val) inline
Definition at line 42 of file macros_detectorplane/ejungwooA.h.
References fDeadFrame.
SetDeadFrameBottom() [3/4]
void LKWindowManager::SetDeadFrameBottom (UInt_t val) inline
Definition at line 42 of file macros_hough/ejungwooA.h.
References fDeadFrame.
SetDeadFrameBottom() [4/4]
void LKWindowManager::SetDeadFrameBottom (UInt_t val) inline
Definition at line 42 of file macros_psa/ejungwooA.h.
References fDeadFrame.
SetDeadFrameLeft() [1/4]
void LKWindowManager::SetDeadFrameLeft (UInt_t val)
Definition at line 84 of file LKWindowManager.cpp.
References fDeadFrameSize, and fWCurrentDisplay.
Referenced by SetDeadFrame().
SetDeadFrameLeft() [2/4]
void LKWindowManager::SetDeadFrameLeft (UInt_t val) inline
Definition at line 34 of file macros_detectorplane/ejungwooA.h.
References fDeadFrame, and fWCurrent.
SetDeadFrameLeft() [3/4]
void LKWindowManager::SetDeadFrameLeft (UInt_t val) inline
Definition at line 34 of file macros_hough/ejungwooA.h.
References fDeadFrame, and fWCurrent.
SetDeadFrameLeft() [4/4]
void LKWindowManager::SetDeadFrameLeft (UInt_t val) inline
Definition at line 34 of file macros_psa/ejungwooA.h.
References fDeadFrame, and fWCurrent.
SetDeadFrameRight() [1/4]
void LKWindowManager::SetDeadFrameRight (UInt_t val)
Definition at line 89 of file LKWindowManager.cpp.
References fDeadFrameSize, and fWCurrentDisplay.
Referenced by SetDeadFrame().
SetDeadFrameRight() [2/4]
void LKWindowManager::SetDeadFrameRight (UInt_t val) inline
Definition at line 39 of file macros_detectorplane/ejungwooA.h.
References fDeadFrame.
SetDeadFrameRight() [3/4]
void LKWindowManager::SetDeadFrameRight (UInt_t val) inline
Definition at line 39 of file macros_hough/ejungwooA.h.
References fDeadFrame.
SetDeadFrameRight() [4/4]
void LKWindowManager::SetDeadFrameRight (UInt_t val) inline
Definition at line 39 of file macros_psa/ejungwooA.h.
References fDeadFrame.
SetDeadFrameTop() [1/4]
void LKWindowManager::SetDeadFrameTop (UInt_t val)
Definition at line 99 of file LKWindowManager.cpp.
References fDeadFrameSize, and fWCurrentDisplay.
Referenced by SetDeadFrame().
SetDeadFrameTop() [2/4]
void LKWindowManager::SetDeadFrameTop (UInt_t val) inline
Definition at line 45 of file macros_detectorplane/ejungwooA.h.
References fDeadFrame, and fHCurrent.
SetDeadFrameTop() [3/4]
void LKWindowManager::SetDeadFrameTop (UInt_t val) inline
Definition at line 45 of file macros_hough/ejungwooA.h.
References fDeadFrame, and fHCurrent.
SetDeadFrameTop() [4/4]
void LKWindowManager::SetDeadFrameTop (UInt_t val) inline
Definition at line 45 of file macros_psa/ejungwooA.h.
References fDeadFrame, and fHCurrent.
SetDHCanvas() [1/3]
void LKWindowManager::SetDHCanvas (UInt_t hCanvas) inline
Definition at line 59 of file macros_detectorplane/ejungwooA.h.
References fDHCanvas.
SetDHCanvas() [2/3]
void LKWindowManager::SetDHCanvas (UInt_t hCanvas) inline
Definition at line 59 of file macros_hough/ejungwooA.h.
References fDHCanvas.
SetDHCanvas() [3/3]
void LKWindowManager::SetDHCanvas (UInt_t hCanvas) inline
Definition at line 59 of file macros_psa/ejungwooA.h.
References fDHCanvas.
SetDHSpacing() [1/3]
void LKWindowManager::SetDHSpacing (UInt_t dhCanvas) inline
Definition at line 61 of file macros_detectorplane/ejungwooA.h.
References fDHSpacing.
SetDHSpacing() [2/3]
void LKWindowManager::SetDHSpacing (UInt_t dhCanvas) inline
Definition at line 61 of file macros_hough/ejungwooA.h.
References fDHSpacing.
SetDHSpacing() [3/3]
void LKWindowManager::SetDHSpacing (UInt_t dhCanvas) inline
Definition at line 61 of file macros_psa/ejungwooA.h.
References fDHSpacing.
SetDWCanvas() [1/3]
void LKWindowManager::SetDWCanvas (UInt_t wCanvas) inline
Definition at line 58 of file macros_detectorplane/ejungwooA.h.
References fDWCanvas.
SetDWCanvas() [2/3]
void LKWindowManager::SetDWCanvas (UInt_t wCanvas) inline
Definition at line 58 of file macros_hough/ejungwooA.h.
References fDWCanvas.
SetDWCanvas() [3/3]
void LKWindowManager::SetDWCanvas (UInt_t wCanvas) inline
Definition at line 58 of file macros_psa/ejungwooA.h.
References fDWCanvas.
SetDWSpacing() [1/3]
void LKWindowManager::SetDWSpacing (UInt_t dwCanvas) inline
Definition at line 60 of file macros_detectorplane/ejungwooA.h.
References fDWSpacing.
SetDWSpacing() [2/3]
void LKWindowManager::SetDWSpacing (UInt_t dwCanvas) inline
Definition at line 60 of file macros_hough/ejungwooA.h.
References fDWSpacing.
SetDWSpacing() [3/3]
void LKWindowManager::SetDWSpacing (UInt_t dwCanvas) inline
Definition at line 60 of file macros_psa/ejungwooA.h.
References fDWSpacing.
SetGlobalScale() [1/3]
void LKWindowManager::SetGlobalScale (Double_t xScale, Double_t yScale) inline
Definition at line 63 of file macros_detectorplane/ejungwooA.h.
References fHGlobalScale, and fWGlobalScale.
SetGlobalScale() [2/3]
void LKWindowManager::SetGlobalScale (Double_t xScale, Double_t yScale) inline
Definition at line 63 of file macros_hough/ejungwooA.h.
References fHGlobalScale, and fWGlobalScale.
SetGlobalScale() [3/3]
void LKWindowManager::SetGlobalScale (Double_t xScale, Double_t yScale) inline
Definition at line 63 of file macros_psa/ejungwooA.h.
References fHGlobalScale, and fWGlobalScale.
SetHCanvas()
void LKWindowManager::SetHCanvas (UInt_t hCanvas) inline
Definition at line 42 of file LKWindowManager.h.
References fGeneralResizeFactor, fHDefault, and fHDefaultOrigin.
SetHSpacing()
void LKWindowManager::SetHSpacing (UInt_t dhCanvas) inline
Definition at line 44 of file LKWindowManager.h.
References fHSpacing.
SetRatio()
Double_t LKWindowManager::SetRatio (Double_t ratio, Double_t defaultValue = 1)
Definition at line 123 of file LKWindowManager.cpp.
References e_warning.
Referenced by CanvasDefault(), CanvasFull(), CanvasResize(), and CanvasSquare().
SetWCanvas()
void LKWindowManager::SetWCanvas (UInt_t wCanvas) inline
Definition at line 41 of file LKWindowManager.h.
References fGeneralResizeFactor, fWDefault, and fWDefaultOrigin.
SetWSpacing()
void LKWindowManager::SetWSpacing (UInt_t dwCanvas) inline
Definition at line 43 of file LKWindowManager.h.
References fWSpacing.
UpdateNextCanvasPosition()
void LKWindowManager::UpdateNextCanvasPosition ()
Definition at line 115 of file LKWindowManager.cpp.
References fFixCanvasPosition, fHSpacing, fWSpacing, fXCurrentCanvas, and fYCurrentCanvas.
Referenced by CanvasDefault(), CanvasFull(), CanvasResize(), and CanvasSquare().
Member Data Documentation
fCountCanvases
int LKWindowManager::fCountCanvases = 0 private
Definition at line 75 of file LKWindowManager.h.
Referenced by ConfigureName(), and NewCanvas().
fDeadFrame
UInt_t LKWindowManager::fDeadFrame = {0} private
height of current display
Definition at line 107 of file macros_detectorplane/ejungwooA.h.
Referenced by SetDeadFrameBottom(), SetDeadFrameLeft(), SetDeadFrameRight(), and SetDeadFrameTop().
fDeadFrameSize
UInt_t LKWindowManager::fDeadFrameSize[4] = {25,25,80,50} private
height of current display
Definition at line 84 of file LKWindowManager.h.
Referenced by Clear(), ConfigureDisplay(), Print(), SetDeadFrameBottom(), SetDeadFrameLeft(), SetDeadFrameRight(), and SetDeadFrameTop().
fDHCanvas
Int_t LKWindowManager::fDHCanvas = 450 private
default width of canvas
Definition at line 113 of file macros_detectorplane/ejungwooA.h.
Referenced by CanvasR(), and SetDHCanvas().
fDHFull
UInt_t LKWindowManager::fDHFull = 0 private
width of current display
Definition at line 105 of file macros_detectorplane/ejungwooA.h.
Referenced by CanvasR(), and GetDHFull().
fDHSpacing
Int_t LKWindowManager::fDHSpacing = 25 private
default width spacing of canvas
Definition at line 116 of file macros_detectorplane/ejungwooA.h.
Referenced by CanvasR(), and SetDHSpacing().
fDWCanvas
Int_t LKWindowManager::fDWCanvas = 600 private
height position of next canvas
Definition at line 112 of file macros_detectorplane/ejungwooA.h.
Referenced by CanvasR(), and SetDWCanvas().
fDWFull
UInt_t LKWindowManager::fDWFull = 0 private
relative height position of current display from main display
Definition at line 104 of file macros_detectorplane/ejungwooA.h.
Referenced by CanvasR(), and GetDWFull().
fDWSpacing
Int_t LKWindowManager::fDWSpacing = 25 private
default height of canvas
Definition at line 115 of file macros_detectorplane/ejungwooA.h.
Referenced by CanvasR(), and SetDWSpacing().
fFixCanvasPosition
bool LKWindowManager::fFixCanvasPosition = true private
default height spacing of canvas
Definition at line 100 of file LKWindowManager.h.
Referenced by FixCanvasPosition(), and UpdateNextCanvasPosition().
fGeneralResizeFactor
Double_t LKWindowManager::fGeneralResizeFactor = 1 private
height position of next canvas
Definition at line 89 of file LKWindowManager.h.
Referenced by CanvasResize(), ConfigureDisplay(), SetHCanvas(), and SetWCanvas().
fHCurrent
Int_t LKWindowManager::fHCurrent = 0 private
width position of next canvas
Definition at line 110 of file macros_detectorplane/ejungwooA.h.
Referenced by CanvasR(), and SetDeadFrameTop().
fHCurrentDisplay
UInt_t LKWindowManager::fHCurrentDisplay = 0 private
width of current display
Definition at line 81 of file LKWindowManager.h.
Referenced by CanvasFull(), CanvasResize(), CanvasSquare(), Clear(), ConfigureDisplay(), GetHCurrentDisplay(), and Print().
fHDefault
Int_t LKWindowManager::fHDefault = fHDefaultOrigin private
default width of canvas
Definition at line 95 of file LKWindowManager.h.
Referenced by CanvasDefault(), Clear(), ConfigureDisplay(), Print(), and SetHCanvas().
fHDefaultOrigin
Int_t LKWindowManager::fHDefaultOrigin = 500 private
default width of canvas assuming that width of the display is 1250
Definition at line 92 of file LKWindowManager.h.
Referenced by ConfigureDisplay(), and SetHCanvas().
fHDisplay
Int_t LKWindowManager::fHDisplay = -1 private
relative width position of current display from main display
Definition at line 102 of file macros_detectorplane/ejungwooA.h.
Referenced by GetHDisplay().
fHGlobalScale
Double_t LKWindowManager::fHGlobalScale = 1 private
default width spacing of canvas
Definition at line 119 of file macros_detectorplane/ejungwooA.h.
Referenced by CanvasR(), and SetGlobalScale().
fHSpacing
Int_t LKWindowManager::fHSpacing = 25 private
default width spacing of canvas
Definition at line 98 of file LKWindowManager.h.
Referenced by Clear(), Print(), SetHSpacing(), and UpdateNextCanvasPosition().
fInstance
LKWindowManager * LKWindowManager::fInstance = nullptr static private
Definition at line 73 of file LKWindowManager.h.
Referenced by GetWindowManager().
fWCurrent
Int_t LKWindowManager::fWCurrent = 0 private
height of the top bar
Definition at line 109 of file macros_detectorplane/ejungwooA.h.
Referenced by CanvasR(), and SetDeadFrameLeft().
fWCurrentDisplay
UInt_t LKWindowManager::fWCurrentDisplay = 0 private
relative height position of current display from main display
Definition at line 80 of file LKWindowManager.h.
Referenced by CanvasFull(), CanvasResize(), CanvasSquare(), Clear(), ConfigureDisplay(), GetWCurrentDisplay(), Print(), SetDeadFrameBottom(), SetDeadFrameLeft(), SetDeadFrameRight(), and SetDeadFrameTop().
fWDefault
Int_t LKWindowManager::fWDefault = fWDefaultOrigin private
default height of canvas assuming that width of the display is 1250
Definition at line 94 of file LKWindowManager.h.
Referenced by CanvasDefault(), Clear(), ConfigureDisplay(), Print(), and SetWCanvas().
fWDefaultOrigin
Int_t LKWindowManager::fWDefaultOrigin = 700 private
Definition at line 91 of file LKWindowManager.h.
Referenced by ConfigureDisplay(), and SetWCanvas().
fWDisplay
Int_t LKWindowManager::fWDisplay = -1 private
Definition at line 101 of file macros_detectorplane/ejungwooA.h.
Referenced by GetWDisplay().
fWGlobalScale
Double_t LKWindowManager::fWGlobalScale = 1 private
default height spacing of canvas
Definition at line 118 of file macros_detectorplane/ejungwooA.h.
Referenced by CanvasR(), and SetGlobalScale().
fWSpacing
Int_t LKWindowManager::fWSpacing = 25 private
default height of canvas
Definition at line 97 of file LKWindowManager.h.
Referenced by Clear(), Print(), SetWSpacing(), and UpdateNextCanvasPosition().
fXCurrentCanvas
Int_t LKWindowManager::fXCurrentCanvas = 0 private
Definition at line 86 of file LKWindowManager.h.
Referenced by CanvasDefault(), CanvasFull(), CanvasResize(), CanvasSquare(), Clear(), ConfigureDisplay(), NewCanvas(), Print(), and UpdateNextCanvasPosition().
fXCurrentDisplay
Int_t LKWindowManager::fXCurrentDisplay = -1 private
Definition at line 77 of file LKWindowManager.h.
Referenced by Clear(), ConfigureDisplay(), GetXCurrentDisplay(), and Print().
fYCurrentCanvas
Int_t LKWindowManager::fYCurrentCanvas = 0 private
width position of next canvas
Definition at line 87 of file LKWindowManager.h.
Referenced by CanvasDefault(), CanvasFull(), CanvasResize(), CanvasSquare(), Clear(), ConfigureDisplay(), NewCanvas(), Print(), and UpdateNextCanvasPosition().
fYCurrentDisplay
Int_t LKWindowManager::fYCurrentDisplay = -1 private
relative width position of current display from main display
Definition at line 78 of file LKWindowManager.h.
Referenced by Clear(), ConfigureDisplay(), GetYCurrentDisplay(), and Print().
kDefault
const Int_t LKWindowManager::kDefault = 0
Definition at line 64 of file LKWindowManager.h.
Referenced by Canvas().
kFull
const Int_t LKWindowManager::kFull = 1
Definition at line 65 of file LKWindowManager.h.
Referenced by Canvas().
kResize
const Int_t LKWindowManager::kResize = 3
Definition at line 67 of file LKWindowManager.h.
Referenced by Canvas().
kSquare
const Int_t LKWindowManager::kSquare = 2
Definition at line 66 of file LKWindowManager.h.
The documentation for this class was generated from the following files:
LKWindowManager.h
macros_detectorplane/ejungwooA.h
macros_hough/ejungwooA.h
macros_psa/ejungwooA.h
LKWindowManager.cpp