lilak: LKChannelAnalyzer Class Reference
LKChannelAnalyzer Class Reference
LKChannelAnalyzer find and fit pulse signal from the given channel buffer using input pulse data. The main usage of LKChannelAnalyzer is to run Analyze() method. Analyze() method is combination of FindPeak(), FitPulse(), TestPulse(), FitAmplitude() which are, in principle, can be used independently as well. Read method descriptions for detail.
#include <LKChannelAnalyzer.h>
Public Member Functions
void Analyze (double *data, bool inverted=false)
void Analyze (int *data)
void Analyze (int *data, bool inverted=false)
void Analyze (TH1D *hist, bool inverted=false)
void AnalyzePulseFitting ()
void AnalyzeSigAtMaximum ()
void AnalyzeSigAtThreshold ()
void Clear (Option_t *option="")
void Clear (Option_t *option="")
void ClearGraphArray ()
double CollectTbAboveThresholdAndIntegrate (int tbHit)
void Draw (Option_t *option="")
double Error (double tb, double tb0=0, double amplitude=1)
double Error0 (double tb, double tb0=0, double amplitude=1)
double Eval (double tb, double tb0=0, double amplitude=1)
virtual void ExecMouseClickEventOnPad (TVirtualPad *pad, double xOnClick, double yOnClick)
TGraphErrors * FillGraphPulseFitting (TGraphErrors *graph, double tb0, double amplitude, double pedestal=0)
TGraphErrors * FillGraphSigAtMaximum (TGraphErrors *graph, double tb0, double amplitude, double pedestal=0)
TGraphErrors * FillGraphSigAtThreshold (TGraphErrors *graph, double tb0, double amplitude, double pedestal=0)
TGraph * FillPedestalGraph (TGraph *graph, double tb1=0, double tb2=512)
TGraphErrors * FillPulseGraph (TGraphErrors *graph, double tb0, double amplitude, double pedestal=0)
double FindAndSubtractPedestal (double *buffer)
bool FindPeak (double *buffer, int &tbPointer, int &tbStartOfPulse)
void FitAmplitude (double *buffer, double tbStartOfPulse, int &ndf, double &amplitude, double &chi2NDF)
bool FitPulse (double *buffer, int tbStartOfPulse, int tbPeak, double &tbHit, double &amplitude, double &squareSum, int &ndf, bool &isSaturated)
double GetA (int i) const
double GetAmplitude (int i) const
double * GetBuffer ()
double GetChi2NDF (int i) const
int GetDynamicRange () const
LKPulseFitParameter GetFitParameter (int i) const
TGraphErrors * GetGraphPulseFitting (double tb0, double amplitude, double pedestal=0)
TGraphErrors * GetGraphSigAtMaximum (double tb0, double amplitude, double pedestal=0)
TGraphErrors * GetGraphSigAtThreshold (double tb0, double amplitude, double pedestal=0)
LKHit * GetHit (int i)
TClonesArray * GetHitArray () const
double GetI (int i) const
double GetIntegral (int i) const
int GetIterMax () const
int GetNDF () const
double GetNDF (int i) const
int GetNumHits ()
int GetNumHits () const
int GetNumHits () const
int GetNumTbAcendingCut () const
int GetPedestal () const
TGraph * GetPedestalGraph (double tb1=0, double tb2=512)
LKPulse * GetPulse () const
LKPulse * GetPulse () const
TString GetPulseFileName () const
TGraphErrors * GetPulseGraph (double tb0, double amplitude, double pedestal=0)
double GetScaleTbStep () const
double GetT (int i) const
double GetTbHit (int i) const
int GetTbMax () const
int GetTbStart () const
int GetTbStartCut () const
double GetTbStepCut () const
int GetThreshold () const
int GetThresholdOneTbStep () const
double GetW (int i) const
double GetWidth (int i) const
bool Init ()
bool Init ()
LKChannelAnalyzer ()
LKChannelAnalyzer ()
void Print (Option_t *option="") const
void Print (Option_t *option="") const
void SetDataIsInverted (bool value=true)
void SetDynamicRange (int dynamicRange)
void SetHitArray (TClonesArray *hitArray)
void SetIterMax (int iterMax)
void SetNDFPulse (int nDFPulse)
void SetNumHits (int numHits)
void SetNumTbAcendingCut (int numAcendingCut)
void SetPad (TVirtualPad *pad, TH2D *hist=nullptr)
void SetPulse (const char *fileName)
void SetPulse (LKPulse *pulse)
void SetScaleTbStep (double scaleTbStep)
void SetSigAtMaximum ()
Set pulse function and related parameter from pulse data file created from LKPulseAnalyzer.
void SetSigAtThreshold ()
void SetTbMax (int tbMax)
void SetTbRange (int tbStart, int tbMax)
void SetTbStart (int tbStart)
void SetTbStartCut (int tbStartCut)
void SetTbStepCut (double value)
void SetThreshold (int threshold)
void SetThresholdOneStep (int oneStepThreshold)
void SubtractPulse (double *buffer, double tbHit, double amplitude)
subtract pulse distribution from adc
bool TestPulse (double *buffer, double tbHitPre, double amplitudePre, double tbHit, double amplitude)
virtual ~LKChannelAnalyzer ()
virtual ~LKChannelAnalyzer ()
Public Member Functions inherited from LKPadInteractive
void AddInteractivePad (TVirtualPad *pad, TString option="")
virtual void ExecMouseClickEventOnPad (TVirtualPad *pad, double xOnClick, double yOnClick)
int GetPadInteractiveID () const
LKPadInteractive ()
void SetPadInteractiveID (int id)
virtual ~LKPadInteractive ()
Public Attributes
TH2D * fHistFitPanel = nullptr
TVirtualPad * fPadFitPanel = nullptr
Private Member Functions
ClassDef (LKChannelAnalyzer, 1)
ClassDef (LKChannelAnalyzer, 1)
Private Attributes
int fAnalyzerMode = kSigAtMaximumMode
double fBuffer [512]
Copied buffer from data.
double fBufferOrigin [512]
Copied buffer from data.
const double fCVCut = 0.2
stdDev/mean cut for collecting samples used for calculating pedestal.
bool fDataIsInverted = false
int fDynamicRange = 4096
Dynamic range subtracted by pedestal of buffer.
int fDynamicRangeOriginal = 4096
Dynamic range of buffer. Used for recognizing saturation. Must be set with SetDynamicRange()
vector< LKPulseFitParameter > fFitParameterArray
Vector holding fit TB.
double fFloorRatio
[Pulse] Ratio regard to the full pulse height where pulse width was measured. Automatically set from pulse.
double fFWHM
[Pulse] Full Width Half Maximum of reference pulse. Automatically set from pulse.
TClonesArray * fGraphArray = nullptr
TH1D * fHistBuffer = nullptr
TH1D * fHistBufferIntegral = nullptr
TClonesArray * fHitArray
vector< int > fIntegralTbArray
int fIterMax = 15
[Pulse-fitting] Maximum iteration cut. Must be set with SetIterMax()
int fNDFFit = 0
[Pulse-fitting] Number of points to use. Related to fitting speed. Automatically set from pulse: fNDFFit = fWidthLeading + fFWHM/4. Can be set with Set SetNDFPulse()
int fNDFPulse
Int_t fNumGraphs = 0
int fNumHits = 0
Number of hits found after Analyze()
int fNumPedestalSamples = 0
int fNumPedestalSamplesM1 = 0
int fNumTbAcendingCut = 5
Peak will be recognize if number-of-TBs-acending >= fNumTbAcendingCut. Automatically set from pulse: fNumTbAcendingCut = int(fWidthLeading*2/3).Can be set with SetNumTbAcendingCut()
int fNumTbSample = 50
Least number of time-bins in pedestal sample regions.
int fNumTbSampleLast = 0
double fPedestal = 0
pedestal level of current channel
double fPedestalErrorRefSampleCut = 10
double fPedestalSample [20] = {0.}
LKPulse * fPulse = nullptr
Pulse pointer.
TString fPulseFileName
double fPulseRefTbMax
double fPulseRefTbMin
double fScaleTbStep = 0.5
[Pulse-fitting] (~0.2) Scale factor for choosing fit-TB-step for next TB candidate. Related to fitting speed and iteration #. Must be set with SetScaleTbStep()
double fStddevSample [20] = {0.}
int fTbMax = 512
Maximum TB in buffer. Must be set with SetTbMax()
int fTbSeparationWidth = 10
[Peak finding] Estimation of # of TB that can separate two different pulse. Automatically set from pulse: fTbSeparationWidth = fNDFFit.
int fTbStart = 1
Starting TB-position for analysis. Must be set with SetTbStart()
int fTbStartCut = -1
Pulse TB-position cannot be larger than fTbStartCut. Automatically set from pulse: fTbStartCut = fTbMax - fNDFFit. Can be set with SetTbStartCut()
double fTbStepCut = 0.01
[Pulse-fitting] Break from loop if fit-TB-step < fTbStepCut. Related to fitting speed and resolution. Can be set with SetTbStepCut().
int fTbStepIfFoundHit = 10
[Peak finding] TB-step after hit was found. Automatically set from pulse: fTbStepIfFoundHit = fNDFFit.
int fTbStepIfSaturated = 15
[Peak finding] TB-step after saturation was found. Automatically set from pulse: fTbStepIfSaturated = int(fWidth*1.2);
int fThreshold = 50
Threshold for recognizing pulse peak. Must be set with SetThreshold()
int fThresholdOneStep = 2
Threshold for counting number-of-TBs-acending (y-current > y-previous). Must be set with SetThresholdOneStep()
bool fUsedSample [20]
double fWidth
[Pulse] Width of the pulse. Automatically set from pulse.
double fWidthLeading
[Pulse] Width measured from leading edge to TB-at-peak. Automatically set from pulse.
double fWidthTrailing
[Pulse] Width measured from TB-at-peak to trailing edge. Automatically set from pulse.
const int kPulseFittingMode = 1
const int kSigAtMaximumMode = 2
const int kSigAtThresholdMode = 3
Additional Inherited Members
Protected Attributes inherited from LKPadInteractive
int fPadInteractiveID = -1
Detailed Description
LKChannelAnalyzer find and fit pulse signal from the given channel buffer using input pulse data. The main usage of LKChannelAnalyzer is to run Analyze() method. Analyze() method is combination of FindPeak(), FitPulse(), TestPulse(), FitAmplitude() which are, in principle, can be used independently as well. Read method descriptions for detail.
LKChannelAnalyzer should be initialized with pulse data file created from LKPulseAnalyzer. See LKPulseAnalyzer for pulse data file. Some parameters are set from pulse data file. Look for keyword "Automatically set". Some parameters must be set by user. Look for keyword "Must be set".
Critical parameters affecting the fitting speed and fit resolution are
Parameters
fNDFFit : Number of points to use. Related to fitting speed. Automatically set from pulse: fNDFFit = fWidthLeading + fFWHM/4. Can be set with Set SetNDFPulse()
fIterMax : Maximum iteration cut. Must be set with SetIterMax()
fTbStepCut : Break from loop if fit-TB-step < fTbStepCut. Related to fitting speed and resolution. Can be set with SetTbStepCut().
fScaleTbStep : (~0.2) Scale factor for choosing fit-TB-step for next TB candidate. Related to fitting speed and iteration #. Must be set with SetScaleTbStep()
The value of fit-TB-step is chosen by fScaleTbStep times inner parameter "slope".
Parameters
slope inner parameter defined as \((\chi^2_{i-1}/NDF_{i-1}-\chi^2_{i}/NDF_{i}) / (t_i-t_{i-1})\), where 'i' corresponds to the iteration count and t is the fitting TB-position. This parameter indicates how rapidly the chi-square value changes per unit TB. The program is designed to take larger TB-steps when the chi-square difference is big and smaller TB-steps when the chi-square difference is small. One can adjust the rate of change by modifying the variable fScaleTbStep. The value of slope can be access by using DEBUG_CHANA_FITPULSE macro in LKChannelanalyzer.h
These parameters depend on the experimental settings. Users should test the parameter dependence on the performance of LKChannelAnalyzer. For debugging the fitting process, you can utilize the following C++ macros. To activate them, macros (in LKChannelAnalyzer.h) should be comment-in, and lilak should be re-compiled.
Parameters
DEBUG_CHANA_FINDPEAK
DEBUG_CHANA_ANALYZE
DEBUG_CHANA_FITPULSE From this macro, users have access to following graphs, to check how inner parameters change : dGraph_it_tb, dGraph_it_tbStep, dGraph_it_chi2, dGraph_it_slope, dGraph_tb_chi2, dGraph_tb_slope, dGraph_it_slopeInv, dGraph_tb_slopeInv.
Example of using LKChannelAnalyzer:
{
    auto ana = LKChannelAnalyzer()
    ana -> SetPulse("pulse_data_created_from_LKPulseAnalyzer.root");
    ana -> SetTbMax(512);
    ana -> SetTbStart(0);
    ana -> SetDynamicRange(4096);
    ana -> SetThresholdOneStep(2);
    ana -> SetThreshold(100);
    ana -> SetIterMax(15);
    ana -> SetTbStepCut(0.01);
    ana -> SetScaleTbStep(0.2);
    for (...)
    {
        double* buffer = get_data_somehow;
        ana -> Analyze(buffer);
        auto numHits = ana -> GetNumHits();
        for (auto iHit=0; iHit<numHits; ++iHit) {
            auto tbHit = ana -> GetTbHit(iHit);
            auto amplitude = ana -> GetAmplitude(iHit);
            MyAnalysis();
        }
    }
}
Definition at line 7 of file macros/dummy_class_writter/output/LKChannelAnalyzer.h.
Constructor & Destructor Documentation
LKChannelAnalyzer() [1/2]
LKChannelAnalyzer::LKChannelAnalyzer ()
Definition at line 5 of file macros/dummy_class_writter/output/LKChannelAnalyzer.cpp.
~LKChannelAnalyzer() [1/2]
virtual LKChannelAnalyzer::~LKChannelAnalyzer () inline virtual
Definition at line 11 of file macros/dummy_class_writter/output/LKChannelAnalyzer.h.
LKChannelAnalyzer() [2/2]
LKChannelAnalyzer::LKChannelAnalyzer ()
~LKChannelAnalyzer() [2/2]
virtual LKChannelAnalyzer::~LKChannelAnalyzer () inline virtual
Definition at line 155 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Member Function Documentation
Analyze() [1/4]
void LKChannelAnalyzer::Analyze (double * data, bool inverted = false)
Definition at line 282 of file source/tool/pulse_analysis/LKChannelAnalyzer.cpp.
References AnalyzePulseFitting(), AnalyzeSigAtMaximum(), AnalyzeSigAtThreshold(), Clear(), fAnalyzerMode, fBuffer, fBufferOrigin, fDataIsInverted, fDynamicRangeOriginal, fFitParameterArray, FindAndSubtractPedestal(), fIntegralTbArray, fNumHits, fTbMax, kPulseFittingMode, kSigAtMaximumMode, and kSigAtThresholdMode.
Analyze() [2/4]
void LKChannelAnalyzer::Analyze (int * data)
Definition at line 35 of file macros/dummy_class_writter/output/LKChannelAnalyzer.cpp.
Referenced by Analyze(), and Analyze().
Analyze() [3/4]
void LKChannelAnalyzer::Analyze (int * data, bool inverted = false)
Definition at line 274 of file source/tool/pulse_analysis/LKChannelAnalyzer.cpp.
References Analyze(), and fTbMax.
Analyze() [4/4]
void LKChannelAnalyzer::Analyze (TH1D * hist, bool inverted = false)
Definition at line 265 of file source/tool/pulse_analysis/LKChannelAnalyzer.cpp.
References Analyze(), and fTbMax.
AnalyzePulseFitting()
void LKChannelAnalyzer::AnalyzePulseFitting ()
Definition at line 399 of file source/tool/pulse_analysis/LKChannelAnalyzer.cpp.
References CollectTbAboveThresholdAndIntegrate(), fBuffer, fFitParameterArray, FindPeak(), FitPulse(), fNDFFit, fPedestal, fTbMax, fTbStart, fTbStartCut, fTbStepIfFoundHit, fTbStepIfSaturated, fWidthLeading, lk_debug, SubtractPulse(), and TestPulse().
Referenced by Analyze().
AnalyzeSigAtMaximum()
void LKChannelAnalyzer::AnalyzeSigAtMaximum ()
Definition at line 330 of file source/tool/pulse_analysis/LKChannelAnalyzer.cpp.
References CollectTbAboveThresholdAndIntegrate(), fBuffer, fFitParameterArray, fPedestal, fTbMax, and fThreshold.
Referenced by Analyze().
AnalyzeSigAtThreshold()
void LKChannelAnalyzer::AnalyzeSigAtThreshold ()
Definition at line 350 of file source/tool/pulse_analysis/LKChannelAnalyzer.cpp.
References CollectTbAboveThresholdAndIntegrate(), fBuffer, fFitParameterArray, fPedestal, fTbMax, fTbSeparationWidth, and fThreshold.
Referenced by Analyze().
ClassDef() [1/2]
LKChannelAnalyzer::ClassDef (LKChannelAnalyzer , 1) private
ClassDef() [2/2]
LKChannelAnalyzer::ClassDef (LKChannelAnalyzer , 1) private
Clear() [1/2]
void LKChannelAnalyzer::Clear (Option_t * option = "")
Definition at line 18 of file macros/dummy_class_writter/output/LKChannelAnalyzer.cpp.
References Clear(), fHitArray, fNumHits, and fPulse.
Referenced by Analyze(), Clear(), ClearGraphArray(), and Draw().
Clear() [2/2]
void LKChannelAnalyzer::Clear (Option_t * option = "")
ClearGraphArray()
void LKChannelAnalyzer::ClearGraphArray () inline
Definition at line 272 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References Clear(), fGraphArray, and fNumGraphs.
CollectTbAboveThresholdAndIntegrate()
double LKChannelAnalyzer::CollectTbAboveThresholdAndIntegrate (int tbHit)
Definition at line 303 of file source/tool/pulse_analysis/LKChannelAnalyzer.cpp.
References fBuffer, fIntegralTbArray, fTbMax, and fThreshold.
Referenced by AnalyzePulseFitting(), AnalyzeSigAtMaximum(), and AnalyzeSigAtThreshold().
Draw()
void LKChannelAnalyzer::Draw (Option_t * option = "")
Definition at line 156 of file source/tool/pulse_analysis/LKChannelAnalyzer.cpp.
References Clear(), Draw(), fAnalyzerMode, fBufferOrigin, fHistBuffer, fHistBufferIntegral, fIntegralTbArray, fNumHits, fNumPedestalSamples, fNumPedestalSamplesM1, fNumTbSample, fNumTbSampleLast, fPedestal, fPedestalSample, fTbMax, fUsedSample, GetAmplitude(), GetPulseGraph(), GetTbHit(), kPulseFittingMode, kSigAtMaximumMode, kSigAtThresholdMode, and y.
Referenced by Draw().
Error()
double LKChannelAnalyzer::Error (double tb, double tb0 = 0, double amplitude = 1) inline
Definition at line 170 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References Error(), and fPulse.
Referenced by Error(), and FitAmplitude().
Error0()
double LKChannelAnalyzer::Error0 (double tb, double tb0 = 0, double amplitude = 1) inline
Definition at line 171 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References Error0(), and fPulse.
Referenced by Error0().
Eval()
double LKChannelAnalyzer::Eval (double tb, double tb0 = 0, double amplitude = 1) inline
Definition at line 169 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References Eval(), and fPulse.
Referenced by Eval(), FitAmplitude(), and SubtractPulse().
ExecMouseClickEventOnPad()
void LKChannelAnalyzer::ExecMouseClickEventOnPad (TVirtualPad * pad, double xOnClick, double yOnClick) virtual
Reimplemented from LKPadInteractive.
Definition at line 1039 of file source/tool/pulse_analysis/LKChannelAnalyzer.cpp.
FillGraphPulseFitting()
TGraphErrors * LKChannelAnalyzer::FillGraphPulseFitting (TGraphErrors * graph, double tb0, double amplitude, double pedestal = 0)
Definition at line 1059 of file source/tool/pulse_analysis/LKChannelAnalyzer.cpp.
References FillPulseGraph(), and fPulse.
Referenced by FillPulseGraph().
FillGraphSigAtMaximum()
TGraphErrors * LKChannelAnalyzer::FillGraphSigAtMaximum (TGraphErrors * graph, double tb0, double amplitude, double pedestal = 0)
Definition at line 1086 of file source/tool/pulse_analysis/LKChannelAnalyzer.cpp.
References SetPoint().
Referenced by FillPulseGraph(), GetGraphPulseFitting(), and GetGraphSigAtMaximum().
FillGraphSigAtThreshold()
TGraphErrors * LKChannelAnalyzer::FillGraphSigAtThreshold (TGraphErrors * graph, double tb0, double amplitude, double pedestal = 0)
Definition at line 1065 of file source/tool/pulse_analysis/LKChannelAnalyzer.cpp.
References fThreshold, and SetPoint().
Referenced by FillPulseGraph(), GetGraphPulseFitting(), and GetGraphSigAtThreshold().
FillPedestalGraph()
TGraph * LKChannelAnalyzer::FillPedestalGraph (TGraph * graph, double tb1 = 0, double tb2 = 512)
Definition at line 1127 of file source/tool/pulse_analysis/LKChannelAnalyzer.cpp.
References fPedestal, and SetPoint().
Referenced by GetPedestalGraph().
FillPulseGraph()
TGraphErrors * LKChannelAnalyzer::FillPulseGraph (TGraphErrors * graph, double tb0, double amplitude, double pedestal = 0)
Definition at line 249 of file source/tool/pulse_analysis/LKChannelAnalyzer.cpp.
References fAnalyzerMode, FillGraphPulseFitting(), FillGraphSigAtMaximum(), FillGraphSigAtThreshold(), kPulseFittingMode, kSigAtMaximumMode, and kSigAtThresholdMode.
Referenced by FillGraphPulseFitting(), and GetGraphPulseFitting().
FindAndSubtractPedestal()
double LKChannelAnalyzer::FindAndSubtractPedestal (double * buffer)
Find pedestal and subtract it from the buffer. Pedestal is estimated through following process
Divide tb-region by NUMBER_OF_PEDESTAL_TEST_REGIONS(6)
Calculate average-charge for each region.
Find two regions which has least value of average-charge difference.
Make charge-average-cut which is ~20% of charge-average of selected two regions.
For all regions, select which has average-charge that come in the average-charge-cut.
Pedestal is average-charge of select regions.
Definition at line 453 of file source/tool/pulse_analysis/LKChannelAnalyzer.cpp.
References fCVCut, fDynamicRange, fNumPedestalSamples, fNumPedestalSamplesM1, fNumTbSample, fNumTbSampleLast, fPedestal, fPedestalSample, fStddevSample, fTbMax, fUsedSample, and lk_debug.
Referenced by Analyze().
FindPeak()
bool LKChannelAnalyzer::FindPeak (double * buffer, int & tbPointer, int & tbStartOfPulse)
Find first peak from adc time-bucket starting from input tbCurrent tbCurrent and tbStart becomes time-bucket of the peak and starting point
Definition at line 610 of file source/tool/pulse_analysis/LKChannelAnalyzer.cpp.
References fFloorRatio, fNumTbAcendingCut, fPedestal, fTbMax, fThreshold, fThresholdOneStep, lk_debug, and SetPoint().
Referenced by AnalyzePulseFitting().
FitAmplitude()
void LKChannelAnalyzer::FitAmplitude (double * buffer, double tbStartOfPulse, int & ndf, double & amplitude, double & chi2NDF)
Perform least square fitting with the fixed parameter tbStart and ndf. Amplitude is calculated from weighted least chi-square fitting with waveform f(x) and weight w(x) = 1/(stddev(x)^2). Amplitude = (Sum_i y_i * w(x_i) * f(x_i)) / (Sum_i w(x_i) f^2(x_i)
Definition at line 881 of file source/tool/pulse_analysis/LKChannelAnalyzer.cpp.
References e_cout, Error(), Eval(), fDynamicRange, fNDFPulse, fPulse, fTbMax, and lk_debug.
Referenced by FitPulse().
FitPulse()
bool LKChannelAnalyzer::FitPulse (double * buffer, int tbStartOfPulse, int tbPeak, double & tbHit, double & amplitude, double & squareSum, int & ndf, bool & isSaturated)
Perform least square fitting with the the pulse around tbStart ~ tbPeak. This process is iteration based process using method LSFitPuse()
Definition at line 723 of file source/tool/pulse_analysis/LKChannelAnalyzer.cpp.
References LKTbIterationParameters::Add(), LKTbIterationParameters::fC1, fDynamicRange, FitAmplitude(), fIterMax, fNDFFit, fScaleTbStep, LKTbIterationParameters::fT1, fTbStartCut, fTbStepCut, lk_debug, LKTbIterationParameters::NextTb(), SetPoint(), LKTbIterationParameters::SetScaleTbStep(), LKTbIterationParameters::Slope(), and LKTbIterationParameters::TbStep().
Referenced by AnalyzePulseFitting().
GetA()
double LKChannelAnalyzer::GetA (int i) const inline
Definition at line 184 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References GetAmplitude().
GetAmplitude()
double LKChannelAnalyzer::GetAmplitude (int i) const inline
Definition at line 180 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References fFitParameterArray.
Referenced by Draw(), and GetA().
GetBuffer()
double * LKChannelAnalyzer::GetBuffer () inline
Definition at line 258 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References fBuffer.
Referenced by NextChannel().
GetChi2NDF()
double LKChannelAnalyzer::GetChi2NDF (int i) const inline
Definition at line 178 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References fFitParameterArray.
GetDynamicRange()
int LKChannelAnalyzer::GetDynamicRange () const inline
Definition at line 238 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References fDynamicRange.
GetFitParameter()
LKPulseFitParameter LKChannelAnalyzer::GetFitParameter (int i) const inline
Definition at line 174 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References fFitParameterArray.
GetGraphPulseFitting()
TGraphErrors * LKChannelAnalyzer::GetGraphPulseFitting (double tb0, double amplitude, double pedestal = 0)
Definition at line 1107 of file source/tool/pulse_analysis/LKChannelAnalyzer.cpp.
References fAnalyzerMode, fGraphArray, FillGraphSigAtMaximum(), FillGraphSigAtThreshold(), FillPulseGraph(), fNumGraphs, fPulse, kPulseFittingMode, kSigAtMaximumMode, and kSigAtThresholdMode.
Referenced by GetPulseGraph().
GetGraphSigAtMaximum()
TGraphErrors * LKChannelAnalyzer::GetGraphSigAtMaximum (double tb0, double amplitude, double pedestal = 0)
Definition at line 1099 of file source/tool/pulse_analysis/LKChannelAnalyzer.cpp.
References fGraphArray, FillGraphSigAtMaximum(), and fNumGraphs.
Referenced by GetPulseGraph().
GetGraphSigAtThreshold()
TGraphErrors * LKChannelAnalyzer::GetGraphSigAtThreshold (double tb0, double amplitude, double pedestal = 0)
Definition at line 1078 of file source/tool/pulse_analysis/LKChannelAnalyzer.cpp.
References fGraphArray, FillGraphSigAtThreshold(), and fNumGraphs.
Referenced by GetPulseGraph().
GetHit()
LKHit * LKChannelAnalyzer::GetHit (int i) inline
Definition at line 27 of file macros/dummy_class_writter/output/LKChannelAnalyzer.h.
References fHitArray.
GetHitArray()
TClonesArray * LKChannelAnalyzer::GetHitArray () const inline
Definition at line 19 of file macros/dummy_class_writter/output/LKChannelAnalyzer.h.
References fHitArray.
GetI()
double LKChannelAnalyzer::GetI (int i) const inline
Definition at line 183 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References GetIntegral().
GetIntegral()
double LKChannelAnalyzer::GetIntegral (int i) const inline
Definition at line 179 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References fFitParameterArray.
Referenced by GetI().
GetIterMax()
int LKChannelAnalyzer::GetIterMax () const inline
Definition at line 240 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References fIterMax.
GetNDF() [1/2]
int LKChannelAnalyzer::GetNDF () const inline
Definition at line 239 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References fNDFFit.
Referenced by SetPulse().
GetNDF() [2/2]
double LKChannelAnalyzer::GetNDF (int i) const inline
Definition at line 175 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References fFitParameterArray.
GetNumHits() [1/3]
int LKChannelAnalyzer::GetNumHits () inline
Definition at line 26 of file macros/dummy_class_writter/output/LKChannelAnalyzer.h.
References fNumHits.
GetNumHits() [2/3]
int LKChannelAnalyzer::GetNumHits () const inline
Definition at line 18 of file macros/dummy_class_writter/output/LKChannelAnalyzer.h.
References fNumHits.
Referenced by example_psa(), make_hist(), and LKFrameBuilder::WriteChannels().
GetNumHits() [3/3]
int LKChannelAnalyzer::GetNumHits () const inline
Definition at line 173 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References fNumHits.
GetNumTbAcendingCut()
int LKChannelAnalyzer::GetNumTbAcendingCut () const inline
Definition at line 236 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References fNumTbAcendingCut.
GetPedestal()
int LKChannelAnalyzer::GetPedestal () const inline
Definition at line 237 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References fPedestal.
GetPedestalGraph()
TGraph * LKChannelAnalyzer::GetPedestalGraph (double tb1 = 0, double tb2 = 512)
Definition at line 1119 of file source/tool/pulse_analysis/LKChannelAnalyzer.cpp.
References fGraphArray, FillPedestalGraph(), and fNumGraphs.
GetPulse() [1/2]
LKPulse * LKChannelAnalyzer::GetPulse () const inline
Definition at line 17 of file macros/dummy_class_writter/output/LKChannelAnalyzer.h.
References fPulse.
GetPulse() [2/2]
LKPulse * LKChannelAnalyzer::GetPulse () const inline
Definition at line 166 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References fPulse.
GetPulseFileName()
TString LKChannelAnalyzer::GetPulseFileName () const inline
Definition at line 167 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References fPulseFileName.
GetPulseGraph()
TGraphErrors * LKChannelAnalyzer::GetPulseGraph (double tb0, double amplitude, double pedestal = 0)
Definition at line 257 of file source/tool/pulse_analysis/LKChannelAnalyzer.cpp.
References fAnalyzerMode, GetGraphPulseFitting(), GetGraphSigAtMaximum(), GetGraphSigAtThreshold(), kPulseFittingMode, kSigAtMaximumMode, and kSigAtThresholdMode.
Referenced by Draw().
GetScaleTbStep()
double LKChannelAnalyzer::GetScaleTbStep () const inline
Definition at line 241 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References fScaleTbStep.
GetT()
double LKChannelAnalyzer::GetT (int i) const inline
Definition at line 181 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References GetTbHit().
GetTbHit()
double LKChannelAnalyzer::GetTbHit (int i) const inline
Definition at line 176 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References fFitParameterArray.
Referenced by Draw(), and GetT().
GetTbMax()
int LKChannelAnalyzer::GetTbMax () const inline
Definition at line 231 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References fTbMax.
GetTbStart()
int LKChannelAnalyzer::GetTbStart () const inline
Definition at line 232 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References fTbStart.
GetTbStartCut()
int LKChannelAnalyzer::GetTbStartCut () const inline
Definition at line 233 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References fTbStartCut.
GetTbStepCut()
double LKChannelAnalyzer::GetTbStepCut () const inline
Definition at line 242 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References fTbStepCut.
GetThreshold()
int LKChannelAnalyzer::GetThreshold () const inline
Definition at line 234 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References fThreshold.
GetThresholdOneTbStep()
int LKChannelAnalyzer::GetThresholdOneTbStep () const inline
Definition at line 235 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References fThresholdOneStep.
GetW()
double LKChannelAnalyzer::GetW (int i) const inline
Definition at line 182 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References GetWidth().
GetWidth()
double LKChannelAnalyzer::GetWidth (int i) const inline
Definition at line 177 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References fFitParameterArray.
Referenced by GetW(), and SetPulse().
Init() [1/2]
bool LKChannelAnalyzer::Init ()
Definition at line 10 of file macros/dummy_class_writter/output/LKChannelAnalyzer.cpp.
References e_info.
Referenced by SetPulse().
Init() [2/2]
bool LKChannelAnalyzer::Init ()
Print() [1/2]
void LKChannelAnalyzer::Print (Option_t * option = "") const
Definition at line 26 of file macros/dummy_class_writter/output/LKChannelAnalyzer.cpp.
References e_info, and fNumHits.
Print() [2/2]
void LKChannelAnalyzer::Print (Option_t * option = "") const
SetDataIsInverted()
void LKChannelAnalyzer::SetDataIsInverted (bool value = true) inline
Definition at line 256 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References fDataIsInverted.
SetDynamicRange()
void LKChannelAnalyzer::SetDynamicRange (int dynamicRange) inline
Definition at line 251 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References fDynamicRange.
SetHitArray()
void LKChannelAnalyzer::SetHitArray (TClonesArray * hitArray) inline
Definition at line 23 of file macros/dummy_class_writter/output/LKChannelAnalyzer.h.
References fHitArray.
SetIterMax()
void LKChannelAnalyzer::SetIterMax (int iterMax) inline
Definition at line 253 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References fIterMax.
SetNDFPulse()
void LKChannelAnalyzer::SetNDFPulse (int nDFPulse) inline
Definition at line 252 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References fNDFFit.
SetNumHits()
void LKChannelAnalyzer::SetNumHits (int numHits) inline
Definition at line 22 of file macros/dummy_class_writter/output/LKChannelAnalyzer.h.
References fNumHits.
SetNumTbAcendingCut()
void LKChannelAnalyzer::SetNumTbAcendingCut (int numAcendingCut) inline
Definition at line 250 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References fNumTbAcendingCut.
SetPad()
void LKChannelAnalyzer::SetPad (TVirtualPad * pad, TH2D * hist = nullptr)
Definition at line 1018 of file source/tool/pulse_analysis/LKChannelAnalyzer.cpp.
References LKPadInteractive::AddInteractivePad(), fHistFitPanel, and fPadFitPanel.
SetPulse() [1/2]
void LKChannelAnalyzer::SetPulse (const char * fileName)
Definition at line 21 of file source/tool/pulse_analysis/LKChannelAnalyzer.cpp.
References e_error, fAnalyzerMode, fDataIsInverted, fFloorRatio, fFWHM, fNDFFit, fNDFPulse, fNumTbAcendingCut, fPulse, fPulseFileName, fPulseRefTbMax, fPulseRefTbMin, fTbMax, fTbSeparationWidth, fTbStartCut, fTbStepIfFoundHit, fTbStepIfSaturated, fWidth, fWidthLeading, fWidthTrailing, GetNDF(), GetWidth(), Init(), LKPulse::IsGood(), and kPulseFittingMode.
SetPulse() [2/2]
void LKChannelAnalyzer::SetPulse (LKPulse * pulse) inline
Definition at line 21 of file macros/dummy_class_writter/output/LKChannelAnalyzer.h.
References fPulse.
SetScaleTbStep()
void LKChannelAnalyzer::SetScaleTbStep (double scaleTbStep) inline
Definition at line 254 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References fScaleTbStep.
SetSigAtMaximum()
void LKChannelAnalyzer::SetSigAtMaximum () inline
Set pulse function and related parameter from pulse data file created from LKPulseAnalyzer.
Definition at line 163 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References fAnalyzerMode, and kSigAtMaximumMode.
SetSigAtThreshold()
void LKChannelAnalyzer::SetSigAtThreshold () inline
Definition at line 164 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References fAnalyzerMode, and kSigAtThresholdMode.
SetTbMax()
void LKChannelAnalyzer::SetTbMax (int tbMax) inline
Definition at line 245 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References fTbMax.
SetTbRange()
void LKChannelAnalyzer::SetTbRange (int tbStart, int tbMax) inline
Definition at line 244 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References fTbMax, and fTbStart.
SetTbStart()
void LKChannelAnalyzer::SetTbStart (int tbStart) inline
Definition at line 246 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References fTbStart.
SetTbStartCut()
void LKChannelAnalyzer::SetTbStartCut (int tbStartCut) inline
Definition at line 247 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References fTbStartCut.
SetTbStepCut()
void LKChannelAnalyzer::SetTbStepCut (double value) inline
Definition at line 255 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References fTbStepCut.
SetThreshold()
void LKChannelAnalyzer::SetThreshold (int threshold) inline
Definition at line 248 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References fThreshold.
SetThresholdOneStep()
void LKChannelAnalyzer::SetThresholdOneStep (int oneStepThreshold) inline
Definition at line 249 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
References fThresholdOneStep.
SubtractPulse()
void LKChannelAnalyzer::SubtractPulse (double * buffer, double tbHit, double amplitude)
subtract pulse distribution from adc
Definition at line 1000 of file source/tool/pulse_analysis/LKChannelAnalyzer.cpp.
References Eval(), fPulse, fPulseRefTbMax, fPulseRefTbMin, and fTbMax.
Referenced by AnalyzePulseFitting().
TestPulse()
bool LKChannelAnalyzer::TestPulse (double * buffer, double tbHitPre, double amplitudePre, double tbHit, double amplitude)
Compare pulse with the previous pulse If the pulse is not distinguishable from the previous pulse, return false.
Definition at line 976 of file source/tool/pulse_analysis/LKChannelAnalyzer.cpp.
References fThreshold.
Referenced by AnalyzePulseFitting().
Member Data Documentation
fAnalyzerMode
int LKChannelAnalyzer::fAnalyzerMode = kSigAtMaximumMode private
Definition at line 286 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by Analyze(), Draw(), FillPulseGraph(), GetGraphPulseFitting(), GetPulseGraph(), SetPulse(), SetSigAtMaximum(), and SetSigAtThreshold().
fBuffer
double LKChannelAnalyzer::fBuffer[512] private
Copied buffer from data.
Definition at line 290 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by Analyze(), AnalyzePulseFitting(), AnalyzeSigAtMaximum(), AnalyzeSigAtThreshold(), CollectTbAboveThresholdAndIntegrate(), and GetBuffer().
fBufferOrigin
double LKChannelAnalyzer::fBufferOrigin[512] private
Copied buffer from data.
Definition at line 289 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by Analyze(), and Draw().
fCVCut
const double LKChannelAnalyzer::fCVCut = 0.2 private
stdDev/mean cut for collecting samples used for calculating pedestal.
Definition at line 305 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by FindAndSubtractPedestal().
fDataIsInverted
bool LKChannelAnalyzer::fDataIsInverted = false private
Definition at line 293 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by Analyze(), SetDataIsInverted(), and SetPulse().
fDynamicRange
int LKChannelAnalyzer::fDynamicRange = 4096 private
Dynamic range subtracted by pedestal of buffer.
Definition at line 315 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by FindAndSubtractPedestal(), FitAmplitude(), FitPulse(), GetDynamicRange(), and SetDynamicRange().
fDynamicRangeOriginal
int LKChannelAnalyzer::fDynamicRangeOriginal = 4096 private
Dynamic range of buffer. Used for recognizing saturation. Must be set with SetDynamicRange()
Definition at line 314 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by Analyze().
fFitParameterArray
vector<LKPulseFitParameter> LKChannelAnalyzer::fFitParameterArray private
Vector holding fit TB.
Definition at line 292 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by Analyze(), AnalyzePulseFitting(), AnalyzeSigAtMaximum(), AnalyzeSigAtThreshold(), GetAmplitude(), GetChi2NDF(), GetFitParameter(), GetIntegral(), GetNDF(), GetTbHit(), and GetWidth().
fFloorRatio
double LKChannelAnalyzer::fFloorRatio private
[Pulse] Ratio regard to the full pulse height where pulse width was measured. Automatically set from pulse.
Definition at line 332 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by FindPeak(), and SetPulse().
fFWHM
double LKChannelAnalyzer::fFWHM private
[Pulse] Full Width Half Maximum of reference pulse. Automatically set from pulse.
Definition at line 331 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by SetPulse().
fGraphArray
TClonesArray* LKChannelAnalyzer::fGraphArray = nullptr private
Definition at line 342 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by ClearGraphArray(), GetGraphPulseFitting(), GetGraphSigAtMaximum(), GetGraphSigAtThreshold(), and GetPedestalGraph().
fHistBuffer
TH1D* LKChannelAnalyzer::fHistBuffer = nullptr private
Definition at line 365 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by Draw().
fHistBufferIntegral
TH1D* LKChannelAnalyzer::fHistBufferIntegral = nullptr private
Definition at line 366 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by Draw().
fHistFitPanel
TH2D* LKChannelAnalyzer::fHistFitPanel = nullptr
Definition at line 280 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by SetPad().
fHitArray
TClonesArray* LKChannelAnalyzer::fHitArray private
Definition at line 33 of file macros/dummy_class_writter/output/LKChannelAnalyzer.h.
Referenced by Clear(), GetHit(), GetHitArray(), and SetHitArray().
fIntegralTbArray
vector<int> LKChannelAnalyzer::fIntegralTbArray private
Definition at line 367 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by Analyze(), CollectTbAboveThresholdAndIntegrate(), and Draw().
fIterMax
int LKChannelAnalyzer::fIterMax = 15 private
[Pulse-fitting] Maximum iteration cut. Must be set with SetIterMax()
Definition at line 327 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by FitPulse(), GetIterMax(), and SetIterMax().
fNDFFit
int LKChannelAnalyzer::fNDFFit = 0 private
[Pulse-fitting] Number of points to use. Related to fitting speed. Automatically set from pulse: fNDFFit = fWidthLeading + fFWHM/4. Can be set with Set SetNDFPulse()
Definition at line 326 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by AnalyzePulseFitting(), FitPulse(), GetNDF(), SetNDFPulse(), and SetPulse().
fNDFPulse
int LKChannelAnalyzer::fNDFPulse private
Definition at line 338 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by FitAmplitude(), and SetPulse().
fNumGraphs
Int_t LKChannelAnalyzer::fNumGraphs = 0 private
Definition at line 343 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by ClearGraphArray(), GetGraphPulseFitting(), GetGraphSigAtMaximum(), GetGraphSigAtThreshold(), and GetPedestalGraph().
fNumHits
int LKChannelAnalyzer::fNumHits = 0 private
Number of hits found after Analyze()
Definition at line 32 of file macros/dummy_class_writter/output/LKChannelAnalyzer.h.
Referenced by Analyze(), Clear(), Draw(), GetNumHits(), GetNumHits(), Print(), and SetNumHits().
fNumPedestalSamples
int LKChannelAnalyzer::fNumPedestalSamples = 0 private
Definition at line 297 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by Draw(), and FindAndSubtractPedestal().
fNumPedestalSamplesM1
int LKChannelAnalyzer::fNumPedestalSamplesM1 = 0 private
Definition at line 298 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by Draw(), and FindAndSubtractPedestal().
fNumTbAcendingCut
int LKChannelAnalyzer::fNumTbAcendingCut = 5 private
Peak will be recognize if number-of-TBs-acending >= fNumTbAcendingCut. Automatically set from pulse: fNumTbAcendingCut = int(fWidthLeading*2/3).Can be set with SetNumTbAcendingCut()
Definition at line 311 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by FindPeak(), GetNumTbAcendingCut(), SetNumTbAcendingCut(), and SetPulse().
fNumTbSample
int LKChannelAnalyzer::fNumTbSample = 50 private
Least number of time-bins in pedestal sample regions.
Definition at line 296 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by Draw(), and FindAndSubtractPedestal().
fNumTbSampleLast
int LKChannelAnalyzer::fNumTbSampleLast = 0 private
Definition at line 299 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by Draw(), and FindAndSubtractPedestal().
fPadFitPanel
TVirtualPad* LKChannelAnalyzer::fPadFitPanel = nullptr
Definition at line 279 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by SetPad().
fPedestal
double LKChannelAnalyzer::fPedestal = 0 private
pedestal level of current channel
Definition at line 303 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by AnalyzePulseFitting(), AnalyzeSigAtMaximum(), AnalyzeSigAtThreshold(), Draw(), FillPedestalGraph(), FindAndSubtractPedestal(), FindPeak(), and GetPedestal().
fPedestalErrorRefSampleCut
double LKChannelAnalyzer::fPedestalErrorRefSampleCut = 10 private
Definition at line 304 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
fPedestalSample
double LKChannelAnalyzer::fPedestalSample[20] = {0.} private
Definition at line 301 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by Draw(), and FindAndSubtractPedestal().
fPulse
LKPulse * LKChannelAnalyzer::fPulse = nullptr private
Pulse pointer.
Definition at line 31 of file macros/dummy_class_writter/output/LKChannelAnalyzer.h.
Referenced by Clear(), Error(), Error0(), Eval(), FillGraphPulseFitting(), FitAmplitude(), GetGraphPulseFitting(), GetPulse(), SetPulse(), SetPulse(), and SubtractPulse().
fPulseFileName
TString LKChannelAnalyzer::fPulseFileName private
Definition at line 340 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by GetPulseFileName(), and SetPulse().
fPulseRefTbMax
double LKChannelAnalyzer::fPulseRefTbMax private
Definition at line 337 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by SetPulse(), and SubtractPulse().
fPulseRefTbMin
double LKChannelAnalyzer::fPulseRefTbMin private
Definition at line 336 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by SetPulse(), and SubtractPulse().
fScaleTbStep
double LKChannelAnalyzer::fScaleTbStep = 0.5 private
[Pulse-fitting] (~0.2) Scale factor for choosing fit-TB-step for next TB candidate. Related to fitting speed and iteration #. Must be set with SetScaleTbStep()
Definition at line 329 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by FitPulse(), GetScaleTbStep(), and SetScaleTbStep().
fStddevSample
double LKChannelAnalyzer::fStddevSample[20] = {0.} private
Definition at line 302 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by FindAndSubtractPedestal().
fTbMax
int LKChannelAnalyzer::fTbMax = 512 private
Maximum TB in buffer. Must be set with SetTbMax()
Definition at line 308 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by Analyze(), Analyze(), Analyze(), AnalyzePulseFitting(), AnalyzeSigAtMaximum(), AnalyzeSigAtThreshold(), CollectTbAboveThresholdAndIntegrate(), Draw(), FindAndSubtractPedestal(), FindPeak(), FitAmplitude(), GetTbMax(), SetPulse(), SetTbMax(), SetTbRange(), and SubtractPulse().
fTbSeparationWidth
int LKChannelAnalyzer::fTbSeparationWidth = 10 private
[Peak finding] Estimation of # of TB that can separate two different pulse. Automatically set from pulse: fTbSeparationWidth = fNDFFit.
Definition at line 322 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by AnalyzeSigAtThreshold(), and SetPulse().
fTbStart
int LKChannelAnalyzer::fTbStart = 1 private
Starting TB-position for analysis. Must be set with SetTbStart()
Definition at line 309 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by AnalyzePulseFitting(), GetTbStart(), SetTbRange(), and SetTbStart().
fTbStartCut
int LKChannelAnalyzer::fTbStartCut = -1 private
Pulse TB-position cannot be larger than fTbStartCut. Automatically set from pulse: fTbStartCut = fTbMax - fNDFFit. Can be set with SetTbStartCut()
Definition at line 310 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by AnalyzePulseFitting(), FitPulse(), GetTbStartCut(), SetPulse(), and SetTbStartCut().
fTbStepCut
double LKChannelAnalyzer::fTbStepCut = 0.01 private
[Pulse-fitting] Break from loop if fit-TB-step < fTbStepCut. Related to fitting speed and resolution. Can be set with SetTbStepCut().
Definition at line 328 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by FitPulse(), GetTbStepCut(), and SetTbStepCut().
fTbStepIfFoundHit
int LKChannelAnalyzer::fTbStepIfFoundHit = 10 private
[Peak finding] TB-step after hit was found. Automatically set from pulse: fTbStepIfFoundHit = fNDFFit.
Definition at line 320 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by AnalyzePulseFitting(), and SetPulse().
fTbStepIfSaturated
int LKChannelAnalyzer::fTbStepIfSaturated = 15 private
[Peak finding] TB-step after saturation was found. Automatically set from pulse: fTbStepIfSaturated = int(fWidth*1.2);
Definition at line 321 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by AnalyzePulseFitting(), and SetPulse().
fThreshold
int LKChannelAnalyzer::fThreshold = 50 private
Threshold for recognizing pulse peak. Must be set with SetThreshold()
Definition at line 316 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by AnalyzeSigAtMaximum(), AnalyzeSigAtThreshold(), CollectTbAboveThresholdAndIntegrate(), FillGraphSigAtThreshold(), FindPeak(), GetThreshold(), SetThreshold(), and TestPulse().
fThresholdOneStep
int LKChannelAnalyzer::fThresholdOneStep = 2 private
Threshold for counting number-of-TBs-acending (y-current > y-previous). Must be set with SetThresholdOneStep()
Definition at line 317 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by FindPeak(), GetThresholdOneTbStep(), and SetThresholdOneStep().
fUsedSample
bool LKChannelAnalyzer::fUsedSample[20] private
Definition at line 300 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by Draw(), and FindAndSubtractPedestal().
fWidth
double LKChannelAnalyzer::fWidth private
[Pulse] Width of the pulse. Automatically set from pulse.
Definition at line 333 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by SetPulse().
fWidthLeading
double LKChannelAnalyzer::fWidthLeading private
[Pulse] Width measured from leading edge to TB-at-peak. Automatically set from pulse.
Definition at line 334 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by AnalyzePulseFitting(), and SetPulse().
fWidthTrailing
double LKChannelAnalyzer::fWidthTrailing private
[Pulse] Width measured from TB-at-peak to trailing edge. Automatically set from pulse.
Definition at line 335 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by SetPulse().
kPulseFittingMode
const int LKChannelAnalyzer::kPulseFittingMode = 1 private
Definition at line 283 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by Analyze(), Draw(), FillPulseGraph(), GetGraphPulseFitting(), GetPulseGraph(), and SetPulse().
kSigAtMaximumMode
const int LKChannelAnalyzer::kSigAtMaximumMode = 2 private
Definition at line 284 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by Analyze(), Draw(), FillPulseGraph(), GetGraphPulseFitting(), GetPulseGraph(), and SetSigAtMaximum().
kSigAtThresholdMode
const int LKChannelAnalyzer::kSigAtThresholdMode = 3 private
Definition at line 285 of file source/tool/pulse_analysis/LKChannelAnalyzer.h.
Referenced by Analyze(), Draw(), FillPulseGraph(), GetGraphPulseFitting(), GetPulseGraph(), and SetSigAtThreshold().
The documentation for this class was generated from the following files:
macros/dummy_class_writter/output/LKChannelAnalyzer.h
source/tool/pulse_analysis/LKChannelAnalyzer.h
macros/dummy_class_writter/output/LKChannelAnalyzer.cpp
source/tool/pulse_analysis/LKChannelAnalyzer.cpp