LILAK: LKHelixTrack Class Reference
LKHelixTrack Class Reference abstract
#include <LKHelixTrack.h>
Public Types
enum LKFitStatus : int {
kNone = -1 , kBad = 0 , kLine = 1 , kPlane = 2 ,
kHelix = 3 , kGenfitTrack = 4
}
Public Member Functions
virtual void AddHit (LKHit *hit)
Double_t AlphaAtPosition (TVector3 p) const
Double_t AlphaAtTravelLength (Double_t tlen) const
Angle alpha in change of length.
Double_t AngleFromCenterAxis () const
bool CheckExtrapolateToI (Double_t x) const
bool CheckExtrapolateToJ (Double_t z) const
virtual void Clear (Option_t *option="")
virtual void ClearHits ()
virtual double Continuity (double &totalLength, double &continuousLength, double distCut=25)
virtual double Continuity (double distCut=25)
virtual void Copy (TObject &object) const
Double_t CosDip () const
cos(dip)
TGraph * CrossSectionOnPlane (axis_t axis1, axis_t axis2, Double_t scale=1)
void DetermineParticleCharge (TVector3 vertex)
Double_t DipAngle () const
=artan(-fS/fR) (=0 on xz plane) : Angle between p and pt
TVector3 Direction (Double_t alpha) const
Direction at angle alpha.
virtual bool DoDrawOnDetectorPlane ()
virtual bool DrawByDefault ()
return true if to be displayed on eve.
virtual TVector3 ExtrapolateByLength (double l) const =0
Extrapolate by length (tail:0), returns extrapolated position.
virtual TVector3 ExtrapolateByLength (Double_t l) const
Extrapolate by length (tail:0), returns extrapolated position.
Double_t ExtrapolateByMap (TVector3 p, TVector3 &q, TVector3 &m) const
virtual TVector3 ExtrapolateByRatio (double r) const =0
Extrapolate by ratio (tail:0, head:1), returns extrapolated position.
virtual TVector3 ExtrapolateByRatio (Double_t r) const
Extrapolate by ratio (tail:0, head:1), returns extrapolated position.
virtual TVector3 ExtrapolateHead (double l) const =0
Extrapolate head of track about length, returns extrapolated position.
virtual TVector3 ExtrapolateHead (Double_t length) const
Extrapolate head of track about length, returns extrapolated position.
virtual TVector3 ExtrapolateTail (double l) const =0
Extrapolate tail of track about length, returns extrapolated position.
virtual TVector3 ExtrapolateTail (Double_t length) const
Extrapolate tail of track about length, returns extrapolated position.
virtual TVector3 ExtrapolateTo (TVector3 point) const
Extrapolate to POCA from point, returns extrapolated position.
Double_t ExtrapolateToAlpha (Double_t alpha) const
Double_t ExtrapolateToAlpha (Double_t alpha, TVector3 &pointOnHelix) const
bool ExtrapolateToI (Double_t x, Double_t alphaRef, TVector3 &pointOnHelix) const
bool ExtrapolateToI (Double_t x, TVector3 &pointOnHelix1, Double_t &alpha1, TVector3 &pointOnHelix2, Double_t &alpha2) const
bool ExtrapolateToJ (Double_t z, Double_t alphaRef, TVector3 &pointOnHelix) const
bool ExtrapolateToJ (Double_t z, TVector3 &pointOnHelix) const
bool ExtrapolateToJ (Double_t z, TVector3 &pointOnHelix1, Double_t &alpha1, TVector3 &pointOnHelix2, Double_t &alpha2) const
Double_t ExtrapolateToPointAlpha (TVector3 pointGiven, TVector3 &pointOnHelix, Double_t &alpha) const
Double_t ExtrapolateToPointK (TVector3 pointGiven, TVector3 &pointOnHelix, Double_t &alpha) const
void FillTrajectory (TGraphErrors *graphTrack, LKVector3::Axis axis1, LKVector3::Axis axis2)
void FillTrajectory (TGraphErrors *graphTrack, LKVector3::Axis axis1, LKVector3::Axis axis2, bool(*fisout)(TVector3 pos))
void FillTrajectory3D (TGraph2DErrors *graphTrack3D, LKVector3::Axis axis1, LKVector3::Axis axis2, LKVector3::Axis axis3)
void FillTrajectory3D (TGraph2DErrors *graphTrack3D, LKVector3::Axis axis1, LKVector3::Axis axis2, LKVector3::Axis axis3, bool(*fisout)(TVector3 pos))
virtual void FinalizeHits ()
virtual bool Fit ()
virtual LKGeoHelix FitHelix (LKVector3::Axis ref)
virtual LKGeoLine FitLine ()
virtual LKGeoPlane FitPlane ()
axis_t GetA () const
Double_t GetAlphaSlope () const
virtual TVector3 GetCenter () const
double GetChargeSum () const
std::vector< Double_t > * GetdEdxArray ()
Double_t GetdEdxWithCut (Double_t lowR, Double_t highR) const
LKTracklet::LKFitStatus GetFitStatus () const
TString GetFitStatusString () const
Int_t GetGenfitID () const
Double_t GetGenfitMomentum () const
Double_t GetH () const
Double_t GetHelixCenterI () const
Double_t GetHelixCenterJ () const
Double_t GetHelixRadius () const
LKHit * GetHit (int idx) const
LKHit * GetHit (Int_t idx) const
LKHitArray * GetHitArray ()
int GetHitID (int idx) const
Int_t GetHitID (Int_t idx) const
std::vector< int > * GetHitIDArray ()
Double_t GetI () const
Double_t GetJ () const
Double_t GetK () const
Double_t GetKInitial () const
LKVector3 GetLineDirection () const
If track is straight. (ONLY USED IN TRACK FINDING)
TVector3 GetMean () const
int GetNumHits () const
int GetParentID () const
int GetPDG () const
LKVector3 GetPlaneNormal () const
If track is straight. (ONLY USED IN TRACK FINDING)
Double_t GetR () const
TVector3 GetRandomPoint (Double_t sigma=0)
LKVector3::Axis GetReferenceAxis () const
Double_t GetRMS () const
Double_t GetRMSR () const
Double_t GetRMST () const
Double_t GetS () const
Double_t GetT () const
int GetTrackID () const
Int_t Helicity () const
Helicity of track +/-.
TVector3 HelicoidMap (TVector3 pos, Double_t alpha) const
Map pos to helicoid map coordinate.
TVector3 InterpolateByLength (Double_t r) const
TVector3 InterpolateByRatio (Double_t r) const
bool IsBad () const
bool IsGenfitTrack () const
bool IsHelix () const
bool IsHoldingHits ()
bool IsLine () const
bool IsPlane () const
Bool_t IsPositiveChargeParticle () const
Double_t KLengthInPeriod () const
y-length of track in one period
virtual Double_t LengthAt (TVector3 point) const
Length at POCA from point, where tail=0, head=TrackLength.
Double_t LengthInPeriod () const
Length of track in one period.
LKHelixTrack ()
LKHelixTrack (Int_t id)
TVector3 Map (TVector3 p) const
virtual TVector3 Momentum (double B=0.5) const =0
Momentum of track at head.
virtual TVector3 Momentum (Double_t B=0.5) const
Momentum of track (B = 0.5 by default)
LKVector3 PerpLine (TVector3 p) const
If track is straight. (ONLY USED IN TRACK FINDING)
LKVector3 PerpPlane (TVector3 p) const
If track is straight. (ONLY USED IN TRACK FINDING)
TVector3 PositionAtAlpha (Double_t alpha) const
Position at angle alpha [mm].
virtual TVector3 PositionAtHead () const
Position at head of helix.
virtual TVector3 PositionAtTail () const
Position at tail of helix.
virtual void Print (Option_t *option="") const
virtual int RecoverHitArrayWithHitID (TClonesArray *hitArray)
virtual int RecoverHitArrayWithTrackID (TClonesArray *hitArray)
virtual void RemoveHit (LKHit *hit)
void SetA (axis_t val)
void SetAlphaHead (Double_t alpha)
void SetAlphaSlope (Double_t s)
void SetAlphaTail (Double_t alpha)
void SetFitStatus (LKFitStatus value)
void SetGenfitID (Int_t idx)
void SetGenfitMomentum (Double_t p)
void SetH (Double_t val)
void SetHelix (Double_t i, Double_t j, Double_t r, Double_t s, Double_t k, Double_t t, Double_t h, axis_t a)
void SetHelixCenter (Double_t i, Double_t j)
void SetHelixRadius (Double_t r)
void SetI (Double_t val)
void SetIsBad ()
void SetIsGenfitTrack ()
void SetIsHelix ()
void SetIsLine ()
void SetIsPlane ()
void SetIsPositiveChargeParticle (Bool_t val)
Momentum reconstructed by genfit (if is set)
void SetJ (Double_t val)
void SetK (Double_t val)
void SetKInitial (Double_t k)
void SetLineDirection (TVector3 dir)
If track is straight. (ONLY USED IN TRACK FINDING)
void SetParentID (int val)
void SetPDG (int val)
void SetPlaneNormal (TVector3 norm)
If track is straight. (ONLY USED IN TRACK FINDING)
void SetR (Double_t val)
void SetReferenceAxis (LKVector3::Axis ref)
void SetRMS (Double_t val)
void SetRMSR (Double_t)
void SetRMST (Double_t)
void SetS (Double_t val)
void SetT (Double_t val)
void SetTrackID (int val)
virtual void SortHits (bool increasing=true)
void SortHitsByTimeOrder ()
virtual Double_t TrackLength () const
Length of track calculated from head to tail.
virtual TGraphErrors * TrajectoryOnPlane (LKDetectorPlane *plane, double scale=1)
virtual TGraphErrors * TrajectoryOnPlane (LKVector3::Axis axis1, LKVector3::Axis axis2, bool(*fisout)(TVector3 pos), double scale=1)
virtual TGraphErrors * TrajectoryOnPlane (LKVector3::Axis axis1, LKVector3::Axis axis2, double scale=1)
Double_t TravelLengthAtAlpha (Double_t alpha) const
Length of track in change of alpha.
virtual ~LKHelixTrack ()
Protected Attributes
axis_t fA = LKVector3::kZ
helix axis
LKFitStatus fFitStatus
One of kBad, kHelix and kLine.
Double_t fH = 0
Alpha angle at head.
LKHitArray fHitArray
vector< int > fHitIDArray
Double_t fI = 0
axis i-position
Double_t fJ = 0
axis j-position
Double_t fK = 0
k = fS * alpha + fK
int fParentID = -1
Vertex ID.
int fPDG = -1
Double_t fR = 0
Helix radius.
Double_t fRMS = -1
Double_t fRMSR = -1
Double_t fRMST = -1
Double_t fS = 0
k = fS * alpha + fK
Double_t fT = 0
Alpha angle at tail.
int fTrackID = -1
TGraphErrors * fTrajectoryOnPlane = nullptr
Private Attributes
std::vector< Double_t > fdEdxArray
dE/dx array;
Int_t fGenfitID
GENFIT Track ID.
Double_t fGenfitMomentum
Momentum reconstructed by GENFIT.
Bool_t fIsPositiveChargeParticle
Detailed Description
SpiRIT Helix Track Container.
All units in [mm], [ADC], [radian], [MeV].
Definition at line 20 of file LKHelixTrack.h.
Member Enumeration Documentation
LKFitStatus
enum LKTracklet::LKFitStatus : int inherited
Enumerator
kNone
kBad
kLine
kPlane
kHelix
kGenfitTrack
Definition at line 19 of file LKTracklet.h.
Constructor & Destructor Documentation
LKHelixTrack() [1/2]
LKHelixTrack::LKHelixTrack ()
LKHelixTrack() [2/2]
LKHelixTrack::LKHelixTrack (Int_t id)
Definition at line 22 of file LKHelixTrack.cpp.
References Clear(), and LKTracklet::fTrackID.
~LKHelixTrack()
virtual LKHelixTrack::~LKHelixTrack () inline virtual
Definition at line 32 of file LKHelixTrack.h.
Member Function Documentation
AddHit()
void LKTracklet::AddHit (LKHit * hit) virtual inherited
Definition at line 42 of file LKTracklet.cpp.
References LKHitArray::AddHit(), LKTracklet::fHitArray, LKTracklet::fHitIDArray, LKTracklet::fTrackID, LKHit::GetHitID(), and LKTracklet::SetTrackID().
AlphaAtPosition()
Double_t LKHelixTrack::AlphaAtPosition (TVector3 p) const
Extrapolate track due to alpha angle of the given point. Returns alpha;
Definition at line 851 of file LKHelixTrack.cpp.
References ExtrapolateToPointAlpha().
Referenced by ExtrapolateTo(), and LengthAt().
AlphaAtTravelLength()
Double_t LKGeoHelix::AlphaAtTravelLength (Double_t tlen) const inherited
Angle alpha in change of length.
Definition at line 87 of file LKGeoHelix.cpp.
References LKGeoHelix::CosDip(), and LKGeoHelix::fR.
Referenced by ExtrapolateHead(), and ExtrapolateTail().
AngleFromCenterAxis()
Double_t LKGeoHelix::AngleFromCenterAxis () const inherited
Definition at line 82 of file LKGeoHelix.cpp.
References LKGeoHelix::DipAngle().
CheckExtrapolateToI()
bool LKHelixTrack::CheckExtrapolateToI (Double_t x) const
Check feasibility of Extrapolation of track to zy-plane at x-position.
Definition at line 545 of file LKHelixTrack.cpp.
References LKGeoHelix::fI, and LKGeoHelix::fR.
Referenced by ExtrapolateToI(), and ExtrapolateToI().
CheckExtrapolateToJ()
bool LKHelixTrack::CheckExtrapolateToJ (Double_t z) const
Check feasibility of Extrapolation of track to xy-plane at z-position.
Definition at line 555 of file LKHelixTrack.cpp.
References LKGeoHelix::fJ, and LKGeoHelix::fR.
Referenced by ExtrapolateToJ(), and ExtrapolateToJ().
Clear()
void LKHelixTrack::Clear (Option_t * option = "") virtual
Reimplemented from LKTracklet.
Definition at line 28 of file LKHelixTrack.cpp.
References LKTracklet::Clear(), LKGeoHelix::fA, fdEdxArray, LKTracklet::fFitStatus, fGenfitID, fGenfitMomentum, LKGeoHelix::fH, LKGeoHelix::fI, fIsPositiveChargeParticle, LKGeoHelix::fJ, LKGeoHelix::fK, LKGeoHelix::fR, LKGeoHelix::fS, LKGeoHelix::fT, LKTracklet::kBad, and LKVector3::kZ.
Referenced by ClassImp(), and LKHelixTrack().
ClearHits()
void LKTracklet::ClearHits () virtual inherited
Definition at line 36 of file LKTracklet.cpp.
References LKHitArray::Clear(), LKTracklet::fHitArray, and LKTracklet::fHitIDArray.
Continuity() [1/2]
double LKHelixTrack::Continuity (double & totalLength, double & continuousLength, double distCut = 25) virtual
Check continuity of the track. Hit array must be filled. Returns ratio of the continuous region. (-1 if less than 2 hits)
If difference between "length from hits" is smaller than 20, (> pad-diagonal, < 2*pad-row) the region is considered to be connected.
The total length calculation is different from TrackLength(), because TrackLength() use only the head/tail alpha angle informatiotn but this method calculate length directly from the hit using Map(...) method.
Parameters
continuousLength calculated length of continuos region.
totalLength calculated total length of the track.
Reimplemented from LKTracklet.
Definition at line 884 of file LKHelixTrack.cpp.
References LKTracklet::fHitArray, LKHitArray::GetHit(), LKHitArray::GetNumHits(), LKHit::GetPosition(), Map(), and SortHits().
Continuity() [2/2]
virtual double LKTracklet::Continuity (double distCut = 25) inline virtual inherited
Definition at line 164 of file LKTracklet.h.
References LKTracklet::Continuity().
Referenced by LKTracklet::Continuity().
Copy()
void LKHelixTrack::Copy (TObject & object) const virtual
Reimplemented from LKContainer.
Definition at line 117 of file LKHelixTrack.cpp.
References LKGeoHelix::fA, LKTracklet::fFitStatus, fGenfitID, fGenfitMomentum, LKGeoHelix::fH, LKTracklet::fHitArray, LKGeoHelix::fI, fIsPositiveChargeParticle, LKGeoHelix::fJ, LKGeoHelix::fK, LKTracklet::fParentID, LKGeoHelix::fR, LKGeoHelix::fS, LKGeoHelix::fT, LKTracklet::fTrackID, LKHitArray::GetHit(), and LKHitArray::GetNumHits().
CosDip()
Double_t LKGeoHelix::CosDip () const inherited
cos(dip)
Definition at line 81 of file LKGeoHelix.cpp.
References LKGeoHelix::DipAngle().
Referenced by LKGeoHelix::AlphaAtTravelLength(), ExtrapolateByMap(), ExtrapolateToAlpha(), ExtrapolateToAlpha(), ExtrapolateToPointK(), LKGeoHelix::HelicoidMap(), LKGeoHelix::LengthInPeriod(), Momentum(), TrackLength(), and LKGeoHelix::TravelLengthAtAlpha().
CrossSectionOnPlane()
TGraph * LKHelixTrack::CrossSectionOnPlane (axis_t axis1, axis_t axis2, Double_t scale = 1)
Definition at line 950 of file LKHelixTrack.cpp.
References ExtrapolateByRatio(), LKGeoHelix::fA, LKGeoHelix::fI, LKGeoHelix::fJ, LKVector3::GetXYZ(), LKVector3::kZ, and SetPoint().
DetermineParticleCharge()
void LKHelixTrack::DetermineParticleCharge (TVector3 vertex)
Definition at line 395 of file LKHelixTrack.cpp.
References ExtrapolateToAlpha(), ExtrapolateToPointAlpha(), LKGeoHelix::fH, fIsPositiveChargeParticle, LKGeoHelix::fS, and LKGeoHelix::fT.
DipAngle()
Double_t LKGeoHelix::DipAngle () const inherited
=artan(-fS/fR) (=0 on xz plane) : Angle between p and pt
Definition at line 80 of file LKGeoHelix.cpp.
References LKGeoHelix::fR, and LKGeoHelix::fS.
Referenced by LKGeoHelix::AngleFromCenterAxis(), LKGeoHelix::CosDip(), ExtrapolateByMap(), LKGeoHelix::HelicoidMap(), and Print().
Direction()
TVector3 LKGeoHelix::Direction (Double_t alpha) const inherited
Direction at angle alpha.
Definition at line 93 of file LKGeoHelix.cpp.
References LKGeoHelix::fA, LKGeoHelix::fH, LKGeoHelix::fI, LKGeoHelix::fJ, LKGeoHelix::fR, LKGeoHelix::fT, LKVector3::GetXYZ(), LKGeoHelix::KLengthInPeriod(), LKGeoHelix::PositionAtAlpha(), and LKVector3::SetK().
Referenced by Momentum().
DoDrawOnDetectorPlane()
bool LKTracklet::DoDrawOnDetectorPlane () virtual inherited
Definition at line 155 of file LKTracklet.cpp.
DrawByDefault()
bool LKTracklet::DrawByDefault () virtual inherited
return true if to be displayed on eve.
Reimplemented from LKContainer.
Definition at line 116 of file LKTracklet.cpp.
ExtrapolateByLength() [1/2]
virtual TVector3 LKTracklet::ExtrapolateByLength (double l) const pure virtual inherited
Extrapolate by length (tail:0), returns extrapolated position.
ExtrapolateByLength() [2/2]
TVector3 LKHelixTrack::ExtrapolateByLength (Double_t l) const virtual
Extrapolate by length (tail:0), returns extrapolated position.
Definition at line 943 of file LKHelixTrack.cpp.
References InterpolateByLength().
ExtrapolateByMap()
Double_t LKHelixTrack::ExtrapolateByMap (TVector3 p, TVector3 & q, TVector3 & m) const
Extrapolate to cloesest position from p to helix by Mapping. Return length
Parameters
p input position
q position on helix.
m mapped position
Definition at line 860 of file LKHelixTrack.cpp.
References LKGeoHelix::CosDip(), LKGeoHelix::DipAngle(), ExtrapolateToAlpha(), ExtrapolateToPointAlpha(), LKGeoHelix::fA, LKGeoHelix::fH, LKGeoHelix::fI, LKGeoHelix::fJ, LKGeoHelix::fR, LKGeoHelix::fT, LKVector3::K(), and p2.
Referenced by Map().
ExtrapolateByRatio() [1/2]
virtual TVector3 LKTracklet::ExtrapolateByRatio (double r) const pure virtual inherited
Extrapolate by ratio (tail:0, head:1), returns extrapolated position.
Referenced by LKTracklet::FillTrajectory(), and LKTracklet::FillTrajectory3D().
ExtrapolateByRatio() [2/2]
TVector3 LKHelixTrack::ExtrapolateByRatio (Double_t r) const virtual
Extrapolate by ratio (tail:0, head:1), returns extrapolated position.
Definition at line 942 of file LKHelixTrack.cpp.
References InterpolateByRatio().
Referenced by CrossSectionOnPlane().
ExtrapolateHead() [1/2]
virtual TVector3 LKTracklet::ExtrapolateHead (double l) const pure virtual inherited
Extrapolate head of track about length, returns extrapolated position.
ExtrapolateHead() [2/2]
TVector3 LKHelixTrack::ExtrapolateHead (Double_t length) const virtual
Extrapolate head of track about length, returns extrapolated position.
Definition at line 800 of file LKHelixTrack.cpp.
References LKGeoHelix::AlphaAtTravelLength(), LKGeoHelix::fH, LKGeoHelix::fT, and LKGeoHelix::PositionAtAlpha().
ExtrapolateTail() [1/2]
virtual TVector3 LKTracklet::ExtrapolateTail (double l) const pure virtual inherited
Extrapolate tail of track about length, returns extrapolated position.
ExtrapolateTail() [2/2]
TVector3 LKHelixTrack::ExtrapolateTail (Double_t length) const virtual
Extrapolate tail of track about length, returns extrapolated position.
Definition at line 814 of file LKHelixTrack.cpp.
References LKGeoHelix::AlphaAtTravelLength(), LKGeoHelix::fH, LKGeoHelix::fT, and LKGeoHelix::PositionAtAlpha().
ExtrapolateTo()
TVector3 LKHelixTrack::ExtrapolateTo (TVector3 point) const virtual
Extrapolate to POCA from point, returns extrapolated position.
Implements LKTracklet.
Definition at line 933 of file LKHelixTrack.cpp.
References AlphaAtPosition(), and ExtrapolateToAlpha().
ExtrapolateToAlpha() [1/2]
Double_t LKHelixTrack::ExtrapolateToAlpha (Double_t alpha) const
Extrapolate track due to given alpha. Returns extrapolation length from the initial track reference position.
Definition at line 449 of file LKHelixTrack.cpp.
References LKGeoHelix::CosDip(), and LKGeoHelix::fR.
Referenced by DetermineParticleCharge(), ExtrapolateByMap(), ExtrapolateTo(), InterpolateByRatio(), and LengthAt().
ExtrapolateToAlpha() [2/2]
Double_t LKHelixTrack::ExtrapolateToAlpha (Double_t alpha, TVector3 & pointOnHelix) const
Extrapolate track due to given alpha. Returns extrapolation length from the initial track reference position.
Parameters
alpha given alpha.
pointOnHelix extrapolated position on the helix.
Definition at line 455 of file LKHelixTrack.cpp.
References LKGeoHelix::CosDip(), LKGeoHelix::fA, LKGeoHelix::fI, LKGeoHelix::fJ, LKGeoHelix::fK, LKGeoHelix::fR, LKGeoHelix::fS, LKVector3::GetXYZ(), and LKVector3::SetIJK().
ExtrapolateToI() [1/2]
bool LKHelixTrack::ExtrapolateToI (Double_t x, Double_t alphaRef, TVector3 & pointOnHelix) const
Extrapolate track to zy-plane at x-position. Returns true if extrapolation is possible, false if not.
Parameters
x x-position of zy-plane.
alphaRef reference position for extapolation
pointOnHelix extrapolated position on the helix close to alphaRef
Definition at line 703 of file LKHelixTrack.cpp.
References CheckExtrapolateToI(), LKGeoHelix::fI, LKGeoHelix::fJ, LKGeoHelix::fR, LKGeoHelix::PositionAtAlpha(), and z1.
ExtrapolateToI() [2/2]
bool LKHelixTrack::ExtrapolateToI (Double_t x, TVector3 & pointOnHelix1, Double_t & alpha1, TVector3 & pointOnHelix2, Double_t & alpha2) const
Extrapolate track to zy-plane at x-position. Returns true if extrapolation is possible, false if not.
Parameters
x x-position of zy-plane.
pointOnHelix1 extrapolated position on the helix close to fAlphaHead
alpha1 extrapolated alpha angle close to fAlphaHead
pointOnHelix2 extrapolated position on the helix close to fAlphaTail
alpha2 extrapolated alpha angle close to fAlphaTail
Definition at line 565 of file LKHelixTrack.cpp.
References CheckExtrapolateToI(), LKGeoHelix::fH, LKGeoHelix::fI, LKGeoHelix::fJ, LKGeoHelix::fR, LKGeoHelix::fT, and LKGeoHelix::PositionAtAlpha().
ExtrapolateToJ() [1/3]
bool LKHelixTrack::ExtrapolateToJ (Double_t z, Double_t alphaRef, TVector3 & pointOnHelix) const
Extrapolate track to xy-plane at z-position. Returns true if extrapolation is possible, false if not.
Parameters
z z-position of xy-plane
alphaRef reference position for extapolation
pointOnHelix extrapolated position on the helix close to alphaRef
Definition at line 742 of file LKHelixTrack.cpp.
References CheckExtrapolateToJ(), LKGeoHelix::fI, LKGeoHelix::fJ, LKGeoHelix::fR, and LKGeoHelix::PositionAtAlpha().
ExtrapolateToJ() [2/3]
bool LKHelixTrack::ExtrapolateToJ (Double_t z, TVector3 & pointOnHelix) const
Extrapolate track to xy-plane at z-position. Returns true if extrapolation is possible, false if not.
Parameters
z z-position of xy-plane.
pointOnHelix extrapolated position close to tracjectory.
Definition at line 781 of file LKHelixTrack.cpp.
References ExtrapolateToJ(), LKGeoHelix::fH, and LKGeoHelix::fT.
ExtrapolateToJ() [3/3]
bool LKHelixTrack::ExtrapolateToJ (Double_t z, TVector3 & pointOnHelix1, Double_t & alpha1, TVector3 & pointOnHelix2, Double_t & alpha2) const
Extrapolate track to xy-plane at z-position. Returns true if extrapolation is possible, false if not.
Parameters
z z-position of xy-plane.
pointOnHelix1 extrapolated position on the helix close to fAlphaHead
alpha1 extrapolated alpha angle close to fAlphaHead
pointOnHelix2 extrapolated position on the helix close to fAlphaTail
alpha2 extrapolated alpha angle close to fAlphaTail
Definition at line 634 of file LKHelixTrack.cpp.
References CheckExtrapolateToJ(), LKGeoHelix::fH, LKGeoHelix::fI, LKGeoHelix::fJ, LKGeoHelix::fR, LKGeoHelix::fT, and LKGeoHelix::PositionAtAlpha().
Referenced by ExtrapolateToJ().
ExtrapolateToPointAlpha()
Double_t LKHelixTrack::ExtrapolateToPointAlpha (TVector3 pointGiven, TVector3 & pointOnHelix, Double_t & alpha) const
Extrapolate track due to alpha angle of the given point. Returns extrapolation length from the initial track reference position.
Parameters
pointGiven given point.
pointOnHelix extrapolated position on the helix.
alpha extrapolated alpha angle.
Definition at line 466 of file LKHelixTrack.cpp.
References LKVector3::GetXYZ(), LKVector3::I(), LKVector3::J(), LKVector3::K(), LKVector3::SetIJK(), and LKVector3::SetK().
Referenced by AlphaAtPosition(), DetermineParticleCharge(), and ExtrapolateByMap().
ExtrapolateToPointK()
Double_t LKHelixTrack::ExtrapolateToPointK (TVector3 pointGiven, TVector3 & pointOnHelix, Double_t & alpha) const
Extrapolate track due to y-position of the given point. Returns extrapolation length from the initial track reference position.
Parameters
pointGiven given point.
pointOnHelix extrapolated position on the helix.
alpha extrapolated alpha angle.
Definition at line 532 of file LKHelixTrack.cpp.
References LKGeoHelix::CosDip(), LKGeoHelix::fA, LKGeoHelix::fI, LKGeoHelix::fJ, LKGeoHelix::fK, LKGeoHelix::fR, LKGeoHelix::fS, LKVector3::GetXYZ(), and LKVector3::K().
FillTrajectory() [1/2]
void LKTracklet::FillTrajectory (TGraphErrors * graphTrack, LKVector3::Axis axis1, LKVector3::Axis axis2) inherited
Definition at line 193 of file LKTracklet.cpp.
References LKTracklet::FillTrajectory().
FillTrajectory() [2/2]
void LKTracklet::FillTrajectory (TGraphErrors * graphTrack, LKVector3::Axis axis1, LKVector3::Axis axis2, bool(*)(TVector3 pos) fisout) inherited
Definition at line 184 of file LKTracklet.cpp.
References LKTracklet::ExtrapolateByRatio(), LKVector3::kZ, and SetPoint().
Referenced by LKTracklet::FillTrajectory(), and LKTracklet::TrajectoryOnPlane().
FillTrajectory3D() [1/2]
void LKTracklet::FillTrajectory3D (TGraph2DErrors * graphTrack3D, LKVector3::Axis axis1, LKVector3::Axis axis2, LKVector3::Axis axis3) inherited
Definition at line 208 of file LKTracklet.cpp.
References LKTracklet::FillTrajectory3D().
FillTrajectory3D() [2/2]
void LKTracklet::FillTrajectory3D (TGraph2DErrors * graphTrack3D, LKVector3::Axis axis1, LKVector3::Axis axis2, LKVector3::Axis axis3, bool(*)(TVector3 pos) fisout) inherited
Definition at line 199 of file LKTracklet.cpp.
References LKTracklet::ExtrapolateByRatio(), LKVector3::kZ, and SetPoint().
Referenced by LKTracklet::FillTrajectory3D().
FinalizeHits()
void LKTracklet::FinalizeHits () virtual inherited
Definition at line 62 of file LKTracklet.cpp.
References LKTracklet::fHitArray, LKTracklet::fTrackID, next(), and LKTracklet::SetTrackID().
Fit()
bool LKHelixTrack::Fit () virtual
Reimplemented from LKTracklet.
Definition at line 237 of file LKHelixTrack.cpp.
References LKGeoHelix::fA, LKTracklet::fHitArray, LKHitArray::FitHelix(), LKGeoHelix::SetHelix(), LKTracklet::SetIsHelix(), LKGeometry::SetRMS(), LKGeoHelix::SetRMSR(), and LKGeoHelix::SetRMST().
FitHelix()
LKGeoHelix LKTracklet::FitHelix (LKVector3::Axis ref) virtual inherited
Definition at line 260 of file LKTracklet.cpp.
References LKTracklet::fHitArray, LKHitArray::FitHelix(), LKGeometry::GetRMS(), and LKTracklet::SetIsHelix().
FitLine()
LKGeoLine LKTracklet::FitLine () virtual inherited
Definition at line 244 of file LKTracklet.cpp.
References LKTracklet::fHitArray, LKHitArray::FitLine(), LKGeometry::GetRMS(), and LKTracklet::SetIsLine().
FitPlane()
LKGeoPlane LKHelixTrack::FitPlane () virtual
Reimplemented from LKTracklet.
Definition at line 254 of file LKHelixTrack.cpp.
References LKTracklet::fHitArray, LKHitArray::FitLine(), LKHitArray::FitPlane(), LKTracklet::SetIsLine(), LKTracklet::SetIsPlane(), SetLineDirection(), SetPlaneNormal(), and LKGeometry::SetRMS().
GetA()
axis_t LKGeoHelix::GetA () const inherited
Definition at line 77 of file LKGeoHelix.cpp.
References LKGeoHelix::fA.
GetAlphaSlope()
Double_t LKHelixTrack::GetAlphaSlope () const
Definition at line 375 of file LKHelixTrack.cpp.
References LKGeoHelix::fS.
GetCenter()
TVector3 LKGeoHelix::GetCenter () const virtual inherited
Definition at line 21 of file LKGeoHelix.cpp.
References LKGeoHelix::fA, LKGeoHelix::fH, LKGeoHelix::fI, LKGeoHelix::fJ, LKGeoHelix::fK, LKGeoHelix::fS, LKGeoHelix::fT, and LKVector3::GetXYZ().
GetChargeSum()
double LKTracklet::GetChargeSum () const inline inherited
Definition at line 90 of file LKTracklet.h.
References LKTracklet::fHitArray, and LKHitArray::GetW().
GetdEdxArray()
std::vector< Double_t > * LKHelixTrack::GetdEdxArray ()
Definition at line 425 of file LKHelixTrack.cpp.
References fdEdxArray.
GetdEdxWithCut()
Double_t LKHelixTrack::GetdEdxWithCut (Double_t lowR, Double_t highR) const
Definition at line 426 of file LKHelixTrack.cpp.
References fdEdxArray.
Referenced by Print().
GetFitStatus()
LKTracklet::LKFitStatus LKTracklet::GetFitStatus () const inline inherited
Definition at line 35 of file LKTracklet.h.
References LKTracklet::fFitStatus.
GetFitStatusString()
TString LKTracklet::GetFitStatusString () const inline inherited
Definition at line 42 of file LKTracklet.h.
References LKTracklet::fFitStatus, LKTracklet::kBad, LKTracklet::kGenfitTrack, LKTracklet::kHelix, LKTracklet::kLine, and LKTracklet::kPlane.
Referenced by Print().
GetGenfitID()
Int_t LKHelixTrack::GetGenfitID () const
Definition at line 390 of file LKHelixTrack.cpp.
References fGenfitID.
GetGenfitMomentum()
Double_t LKHelixTrack::GetGenfitMomentum () const
Definition at line 393 of file LKHelixTrack.cpp.
References fGenfitMomentum.
GetH()
Double_t LKGeoHelix::GetH () const inherited
Definition at line 76 of file LKGeoHelix.cpp.
References LKGeoHelix::fH.
Referenced by TrackLength().
GetHelixCenterI()
Double_t LKHelixTrack::GetHelixCenterI () const
Definition at line 371 of file LKHelixTrack.cpp.
References LKGeoHelix::fI.
GetHelixCenterJ()
Double_t LKHelixTrack::GetHelixCenterJ () const
Definition at line 372 of file LKHelixTrack.cpp.
References LKGeoHelix::fJ.
GetHelixRadius()
Double_t LKHelixTrack::GetHelixRadius () const
Definition at line 373 of file LKHelixTrack.cpp.
References LKGeoHelix::fR.
GetHit() [1/2]
LKHit * LKTracklet::GetHit (int idx) const inline inherited
Definition at line 84 of file LKTracklet.h.
References LKTracklet::fHitArray, and LKHitArray::GetHit().
GetHit() [2/2]
LKHit * LKHelixTrack::GetHit (Int_t idx) const
GetHitArray()
LKHitArray * LKTracklet::GetHitArray () inline inherited
Definition at line 86 of file LKTracklet.h.
References LKTracklet::fHitArray.
Referenced by LKLinearTrack::CopyFrom(), TTHTTrackingTask::MakeTrack(), and TTHTtBeamTrackingTask::MakeTrack().
GetHitID() [1/2]
int LKTracklet::GetHitID (int idx) const inline inherited
Definition at line 85 of file LKTracklet.h.
References LKTracklet::fHitIDArray.
Referenced by LKTracklet::RecoverHitArrayWithHitID(), and LKTracklet::RemoveHit().
GetHitID() [2/2]
Int_t LKHelixTrack::GetHitID (Int_t idx) const
GetHitIDArray()
std::vector< int > * LKTracklet::GetHitIDArray () inline inherited
Definition at line 87 of file LKTracklet.h.
References LKTracklet::fHitIDArray.
Referenced by LKLinearTrack::CopyFrom().
GetI()
Double_t LKGeoHelix::GetI () const inherited
Definition at line 70 of file LKGeoHelix.cpp.
References LKGeoHelix::fI.
GetJ()
Double_t LKGeoHelix::GetJ () const inherited
Definition at line 71 of file LKGeoHelix.cpp.
References LKGeoHelix::fJ.
GetK()
Double_t LKGeoHelix::GetK () const inherited
Definition at line 74 of file LKGeoHelix.cpp.
References LKGeoHelix::fK.
GetKInitial()
Double_t LKHelixTrack::GetKInitial () const
Definition at line 374 of file LKHelixTrack.cpp.
References LKGeoHelix::fK.
GetLineDirection()
LKVector3 LKHelixTrack::GetLineDirection () const
If track is straight. (ONLY USED IN TRACK FINDING)
Definition at line 329 of file LKHelixTrack.cpp.
References LKGeoHelix::fA, LKGeoHelix::fI, LKGeoHelix::fJ, and LKGeoHelix::fR.
Referenced by PerpLine(), and Print().
GetMean()
TVector3 LKTracklet::GetMean () const inline inherited
Definition at line 89 of file LKTracklet.h.
References LKTracklet::fHitArray, and LKHitArray::GetMean().
GetNumHits()
int LKTracklet::GetNumHits () const inline inherited
Definition at line 83 of file LKTracklet.h.
References LKTracklet::fHitIDArray.
Referenced by LKLinearTrack::Print().
GetParentID()
int LKTracklet::GetParentID () const inline inherited
Definition at line 80 of file LKTracklet.h.
References LKTracklet::fParentID.
Referenced by LKLinearTrack::CopyFrom(), and LKEveTask::SelectTrack().
GetPDG()
int LKTracklet::GetPDG () const inline inherited
Definition at line 81 of file LKTracklet.h.
References LKTracklet::fPDG.
Referenced by LKLinearTrack::CopyFrom(), and LKEveTask::SelectTrack().
GetPlaneNormal()
LKVector3 LKHelixTrack::GetPlaneNormal () const
If track is straight. (ONLY USED IN TRACK FINDING)
Definition at line 353 of file LKHelixTrack.cpp.
References LKGeoHelix::fA, LKGeoHelix::fI, LKGeoHelix::fJ, and LKGeoHelix::fR.
Referenced by PerpPlane(), and Print().
GetR()
Double_t LKGeoHelix::GetR () const inherited
Definition at line 72 of file LKGeoHelix.cpp.
References LKGeoHelix::fR.
GetRandomPoint()
TVector3 LKGeoHelix::GetRandomPoint (Double_t sigma = 0) inherited
Definition at line 41 of file LKGeoHelix.cpp.
References LKGeoHelix::fH, LKGeoHelix::fR, LKGeoHelix::fT, and LKGeoHelix::PositionAtAlpha().
GetReferenceAxis()
LKVector3::Axis LKHelixTrack::GetReferenceAxis () const
Definition at line 377 of file LKHelixTrack.cpp.
References LKGeoHelix::fA.
GetRMS()
Double_t LKGeometry::GetRMS () const inline inherited
Definition at line 16 of file LKGeometry.h.
References LKGeometry::fRMS.
Referenced by LKTracklet::FitHelix(), LKTracklet::FitLine(), and LKTracklet::FitPlane().
GetRMSR()
Double_t LKGeoHelix::GetRMSR () const inherited
Definition at line 38 of file LKGeoHelix.cpp.
References LKGeoHelix::fRMSR.
GetRMST()
Double_t LKGeoHelix::GetRMST () const inherited
Definition at line 39 of file LKGeoHelix.cpp.
References LKGeoHelix::fRMST.
GetS()
Double_t LKGeoHelix::GetS () const inherited
Definition at line 73 of file LKGeoHelix.cpp.
References LKGeoHelix::fS.
GetT()
Double_t LKGeoHelix::GetT () const inherited
Definition at line 75 of file LKGeoHelix.cpp.
References LKGeoHelix::fT.
Referenced by TrackLength().
GetTrackID()
int LKTracklet::GetTrackID () const inline inherited
Definition at line 79 of file LKTracklet.h.
References LKTracklet::fTrackID.
Referenced by LKVertex::AddTrack(), LKLinearTrack::CopyFrom(), and LKEveTask::SelectTrack().
Helicity()
Int_t LKGeoHelix::Helicity () const inherited
Helicity of track +/-.
Todo:
TODO
Definition at line 79 of file LKGeoHelix.cpp.
References LKGeoHelix::fS.
HelicoidMap()
TVector3 LKGeoHelix::HelicoidMap (TVector3 pos, Double_t alpha) const inherited
Map pos to helicoid map coordinate.
Definition at line 109 of file LKGeoHelix.cpp.
References LKGeoHelix::CosDip(), LKGeoHelix::DipAngle(), LKGeoHelix::fA, LKGeoHelix::fH, LKGeoHelix::fI, LKGeoHelix::fJ, LKGeoHelix::fR, LKGeoHelix::fT, LKVector3::I(), LKVector3::J(), LKVector3::K(), LKGeoHelix::PositionAtAlpha(), and LKGeoHelix::TravelLengthAtAlpha().
Referenced by LKHitArray::FitHelix().
InterpolateByLength()
TVector3 LKHelixTrack::InterpolateByLength (Double_t r) const
Interpolate between head and tail of helix. Return interpolated position using length Interpolate when 0 < length < TrackLength(). Extrapolate when length < 0 or length > TrackLength().
Definition at line 836 of file LKHelixTrack.cpp.
References InterpolateByRatio(), and TrackLength().
Referenced by ExtrapolateByLength().
InterpolateByRatio()
TVector3 LKHelixTrack::InterpolateByRatio (Double_t r) const
Interpolate between head and tail of helix. Return interpolated position using ratio Interpolate when 0 < r < 1. Extrapolate when r < 0 or r > 1.
Definition at line 828 of file LKHelixTrack.cpp.
References ExtrapolateToAlpha(), LKGeoHelix::fH, and LKGeoHelix::fT.
Referenced by ExtrapolateByRatio(), and InterpolateByLength().
IsBad()
bool LKTracklet::IsBad () const inline inherited
Definition at line 36 of file LKTracklet.h.
References LKTracklet::fFitStatus, and LKTracklet::kBad.
IsGenfitTrack()
bool LKTracklet::IsGenfitTrack () const inline inherited
Definition at line 40 of file LKTracklet.h.
References LKTracklet::fFitStatus, and LKTracklet::kGenfitTrack.
Referenced by Momentum().
IsHelix()
bool LKTracklet::IsHelix () const inline inherited
Definition at line 39 of file LKTracklet.h.
References LKTracklet::fFitStatus, and LKTracklet::kHelix.
Referenced by Momentum().
IsHoldingHits()
bool LKTracklet::IsHoldingHits () inherited
Definition at line 107 of file LKTracklet.cpp.
References LKTracklet::fHitArray, LKTracklet::fHitIDArray, and LKHitArray::GetNumHits().
IsLine()
bool LKTracklet::IsLine () const inline inherited
Definition at line 37 of file LKTracklet.h.
References LKTracklet::fFitStatus, and LKTracklet::kLine.
IsPlane()
bool LKTracklet::IsPlane () const inline inherited
Definition at line 38 of file LKTracklet.h.
References LKTracklet::fFitStatus, and LKTracklet::kPlane.
IsPositiveChargeParticle()
Bool_t LKHelixTrack::IsPositiveChargeParticle () const
Definition at line 380 of file LKHelixTrack.cpp.
References fIsPositiveChargeParticle.
KLengthInPeriod()
Double_t LKGeoHelix::KLengthInPeriod () const inherited
y-length of track in one period
Definition at line 84 of file LKGeoHelix.cpp.
References LKGeoHelix::fS.
Referenced by LKGeoHelix::Direction().
LengthAt()
Double_t LKHelixTrack::LengthAt (TVector3 point) const virtual
Length at POCA from point, where tail=0, head=TrackLength.
Implements LKTracklet.
Definition at line 944 of file LKHelixTrack.cpp.
References AlphaAtPosition(), and ExtrapolateToAlpha().
LengthInPeriod()
Double_t LKGeoHelix::LengthInPeriod () const inherited
Length of track in one period.
Definition at line 83 of file LKGeoHelix.cpp.
References LKGeoHelix::CosDip(), and LKGeoHelix::fR.
Map()
TVector3 LKHelixTrack::Map (TVector3 p) const
Map and return position. Concept of this mapping is to strecth helix to straight line.
1st axis : radial axis
2nd axis : normal to 1st and 3rd axis
3nd axis : length along helix line
Definition at line 842 of file LKHelixTrack.cpp.
References ExtrapolateByMap().
Referenced by Continuity(), LKHitSortByIncreasingLength::operator()(), LKHitSortByDecreasingLength::operator()(), and SortHits().
Momentum() [1/2]
virtual TVector3 LKTracklet::Momentum (double B = 0.5) const pure virtual inherited
Momentum of track at head.
Momentum() [2/2]
TVector3 LKHelixTrack::Momentum (Double_t B = 0.5) const virtual
Momentum of track (B = 0.5 by default)
Definition at line 917 of file LKHelixTrack.cpp.
References LKGeoHelix::CosDip(), LKGeoHelix::Direction(), LKGeoHelix::fR, LKGeoHelix::fT, LKTracklet::IsGenfitTrack(), and LKTracklet::IsHelix().
Referenced by Print().
PerpLine()
LKVector3 LKHelixTrack::PerpLine (TVector3 p) const
If track is straight. (ONLY USED IN TRACK FINDING)
Definition at line 330 of file LKHelixTrack.cpp.
References LKGeoHelix::fA, LKTracklet::fHitArray, GetLineDirection(), and LKHitArray::GetMean().
PerpPlane()
LKVector3 LKHelixTrack::PerpPlane (TVector3 p) const
If track is straight. (ONLY USED IN TRACK FINDING)
Definition at line 354 of file LKHelixTrack.cpp.
References LKGeoHelix::fA, LKTracklet::fHitArray, LKHitArray::GetMean(), and GetPlaneNormal().
PositionAtAlpha()
TVector3 LKGeoHelix::PositionAtAlpha (Double_t alpha) const inherited
Position at angle alpha [mm].
Definition at line 89 of file LKGeoHelix.cpp.
References LKGeoHelix::fA, LKGeoHelix::fI, LKGeoHelix::fJ, LKGeoHelix::fK, LKGeoHelix::fR, LKGeoHelix::fS, and LKVector3::GetXYZ().
Referenced by LKGeoHelix::Direction(), ExtrapolateHead(), ExtrapolateTail(), ExtrapolateToI(), ExtrapolateToI(), ExtrapolateToJ(), ExtrapolateToJ(), LKGeoHelix::GetRandomPoint(), LKGeoHelix::HelicoidMap(), PositionAtHead(), and PositionAtTail().
PositionAtHead()
TVector3 LKHelixTrack::PositionAtHead () const virtual
Position at head of helix.
Implements LKTracklet.
Definition at line 929 of file LKHelixTrack.cpp.
References LKGeoHelix::fH, and LKGeoHelix::PositionAtAlpha().
PositionAtTail()
TVector3 LKHelixTrack::PositionAtTail () const virtual
Position at tail of helix.
Implements LKTracklet.
Definition at line 930 of file LKHelixTrack.cpp.
References LKGeoHelix::fT, and LKGeoHelix::PositionAtAlpha().
Print()
void LKHelixTrack::Print (Option_t * option = "") const virtual
Reimplemented from LKGeoHelix.
Definition at line 51 of file LKHelixTrack.cpp.
References LKGeoHelix::DipAngle(), e_cout, e_info, LKGeoHelix::fA, LKTracklet::fFitStatus, fGenfitMomentum, LKTracklet::fHitArray, LKGeoHelix::fI, LKGeoHelix::fJ, LKTracklet::fParentID, LKGeoHelix::fR, LKGeoHelix::fRMSR, LKGeoHelix::fRMST, LKTracklet::fTrackID, GetdEdxWithCut(), LKTracklet::GetFitStatusString(), GetLineDirection(), LKHitArray::GetMean(), LKHitArray::GetNumHits(), GetPlaneNormal(), LKHitArray::GetW(), LKTracklet::kGenfitTrack, LKTracklet::kHelix, LKTracklet::kLine, LKTracklet::kPlane, LKVector3::kX, LKVector3::kY, LKVector3::kZ, Momentum(), LKHitArray::PrintHits(), and TrackLength().
RecoverHitArrayWithHitID()
int LKTracklet::RecoverHitArrayWithHitID (TClonesArray * hitArray) virtual inherited
Be cautious on using this method! This method assumes that hit array was used to create track in same run and event This method will recover hit-array of track, which is removed before end of LILAK run. The track store hit IDs. The method will use this information to recover hit array.
Definition at line 87 of file LKTracklet.cpp.
References LKHitArray::AddHit(), LKTracklet::fHitArray, LKTracklet::fHitIDArray, and LKTracklet::GetHitID().
RecoverHitArrayWithTrackID()
int LKTracklet::RecoverHitArrayWithTrackID (TClonesArray * hitArray) virtual inherited
Be cautious on using this method! This method assumes that hit array and track were cretaed in same run and event This method will recover hit-array of track, which is removed before end of LILAK run. The track ID is set in hit container. The method will use this information to recover hit array.
Definition at line 72 of file LKTracklet.cpp.
References LKHitArray::AddHit(), LKTracklet::fHitArray, and LKTracklet::fTrackID.
RemoveHit()
void LKTracklet::RemoveHit (LKHit * hit) virtual inherited
Definition at line 49 of file LKTracklet.cpp.
References LKTracklet::fHitArray, LKTracklet::fHitIDArray, LKTracklet::GetHitID(), and LKHitArray::RemoveHit().
SetA()
void LKGeoHelix::SetA (axis_t val) inherited
Definition at line 68 of file LKGeoHelix.cpp.
References LKGeoHelix::fA.
Referenced by LKHitArray::FitHelix().
SetAlphaHead()
void LKHelixTrack::SetAlphaHead (Double_t alpha)
Definition at line 366 of file LKHelixTrack.cpp.
References LKGeoHelix::fH.
SetAlphaSlope()
void LKHelixTrack::SetAlphaSlope (Double_t s)
Definition at line 365 of file LKHelixTrack.cpp.
References LKGeoHelix::fS.
SetAlphaTail()
void LKHelixTrack::SetAlphaTail (Double_t alpha)
Definition at line 367 of file LKHelixTrack.cpp.
References LKGeoHelix::fT.
SetFitStatus()
void LKTracklet::SetFitStatus (LKFitStatus value) inline inherited
Definition at line 28 of file LKTracklet.h.
References LKTracklet::fFitStatus.
SetGenfitID()
void LKHelixTrack::SetGenfitID (Int_t idx)
GENFIT TRACK
If the track is fitted by GENFIT SUCCESSFULLY, SetIsGenfitTrack() is called and the methods
Definition at line 389 of file LKHelixTrack.cpp.
References fGenfitID.
SetGenfitMomentum()
void LKHelixTrack::SetGenfitMomentum (Double_t p)
Definition at line 392 of file LKHelixTrack.cpp.
References fGenfitMomentum.
SetH()
void LKGeoHelix::SetH (Double_t val) inherited
Definition at line 67 of file LKGeoHelix.cpp.
References LKGeoHelix::fH.
Referenced by LKHitArray::FitHelix().
SetHelix()
void LKGeoHelix::SetHelix (Double_t i, Double_t j, Double_t r, Double_t s, Double_t k, Double_t t, Double_t h, axis_t a) inherited
Definition at line 23 of file LKGeoHelix.cpp.
References LKGeoHelix::fA, LKGeoHelix::fH, LKGeoHelix::fI, LKGeoHelix::fJ, LKGeoHelix::fK, LKGeoHelix::fR, LKGeoHelix::fS, and LKGeoHelix::fT.
Referenced by Fit(), and LKGeoHelix::LKGeoHelix().
SetHelixCenter()
void LKHelixTrack::SetHelixCenter (Double_t i, Double_t j)
Definition at line 362 of file LKHelixTrack.cpp.
References LKGeoHelix::fI, and LKGeoHelix::fJ.
SetHelixRadius()
void LKHelixTrack::SetHelixRadius (Double_t r)
Definition at line 363 of file LKHelixTrack.cpp.
References LKGeoHelix::fR.
SetI()
void LKGeoHelix::SetI (Double_t val) inherited
Definition at line 61 of file LKGeoHelix.cpp.
References LKGeoHelix::fI.
Referenced by LKHitArray::FitHelix().
SetIsBad()
void LKTracklet::SetIsBad () inline inherited
Definition at line 29 of file LKTracklet.h.
References LKTracklet::fFitStatus, and LKTracklet::kBad.
SetIsGenfitTrack()
void LKTracklet::SetIsGenfitTrack () inline inherited
Definition at line 33 of file LKTracklet.h.
References LKTracklet::fFitStatus, and LKTracklet::kGenfitTrack.
SetIsHelix()
void LKTracklet::SetIsHelix () inline inherited
Definition at line 32 of file LKTracklet.h.
References LKTracklet::fFitStatus, and LKTracklet::kHelix.
Referenced by Fit(), and LKTracklet::FitHelix().
SetIsLine()
void LKTracklet::SetIsLine () inline inherited
Definition at line 30 of file LKTracklet.h.
References LKTracklet::fFitStatus, and LKTracklet::kLine.
Referenced by LKTracklet::FitLine(), and FitPlane().
SetIsPlane()
void LKTracklet::SetIsPlane () inline inherited
Definition at line 31 of file LKTracklet.h.
References LKTracklet::fFitStatus, and LKTracklet::kPlane.
Referenced by FitPlane(), and LKTracklet::FitPlane().
SetIsPositiveChargeParticle()
void LKHelixTrack::SetIsPositiveChargeParticle (Bool_t val)
Momentum reconstructed by genfit (if is set)
Definition at line 379 of file LKHelixTrack.cpp.
References fIsPositiveChargeParticle.
SetJ()
void LKGeoHelix::SetJ (Double_t val) inherited
Definition at line 62 of file LKGeoHelix.cpp.
References LKGeoHelix::fJ.
Referenced by LKHitArray::FitHelix().
SetK()
void LKGeoHelix::SetK (Double_t val) inherited
Definition at line 65 of file LKGeoHelix.cpp.
References LKGeoHelix::fK.
Referenced by LKHitArray::FitHelix().
SetKInitial()
void LKHelixTrack::SetKInitial (Double_t k)
Definition at line 364 of file LKHelixTrack.cpp.
References LKGeoHelix::fK.
SetLineDirection()
void LKHelixTrack::SetLineDirection (TVector3 dir)
If track is straight. (ONLY USED IN TRACK FINDING)
LINE
If the track is fitted to plane by FitLine(),
SetIsLine(), SetLineDirection is called
The direction vector is set to (fI, fJ, fR)
Only then methos GetLineDirection(), PerpLine(TVector3) can be used
These methods should not be used otherwise (such as, after the container is written)
Definition at line 328 of file LKHelixTrack.cpp.
References LKGeoHelix::fI, LKGeoHelix::fJ, and LKGeoHelix::fR.
Referenced by FitPlane().
SetParentID()
void LKTracklet::SetParentID (int val) inline inherited
Definition at line 76 of file LKTracklet.h.
References LKTracklet::fParentID.
SetPDG()
void LKTracklet::SetPDG (int val) inline inherited
Definition at line 77 of file LKTracklet.h.
References LKTracklet::fPDG.
SetPlaneNormal()
void LKHelixTrack::SetPlaneNormal (TVector3 norm)
If track is straight. (ONLY USED IN TRACK FINDING)
PLANE
If the track is fitted to plane by FitPlane(),
SetIsPlane(), SetPlaneNormal is called
The normal vector is set to (fI, fJ, fR)
Only then methos GetPlaneNormal(), PerpPlane(TVector3) can be used
These methods should not be used otherwise (such as, after the container is written)
Definition at line 352 of file LKHelixTrack.cpp.
References LKGeoHelix::fI, LKGeoHelix::fJ, and LKGeoHelix::fR.
Referenced by FitPlane().
SetR()
void LKGeoHelix::SetR (Double_t val) inherited
Definition at line 63 of file LKGeoHelix.cpp.
References LKGeoHelix::fR.
Referenced by LKHitArray::FitHelix().
SetReferenceAxis()
void LKHelixTrack::SetReferenceAxis (LKVector3::Axis ref)
Definition at line 368 of file LKHelixTrack.cpp.
References LKGeoHelix::fA.
SetRMS()
void LKGeometry::SetRMS (Double_t val) inline inherited
Definition at line 15 of file LKGeometry.h.
References LKGeometry::fRMS.
Referenced by LKHitArray::DrawFitCircle(), Fit(), LKHitArray::FitCircle(), LKHitArray::FitHelix(), LKHitArray::FitLine(), LKHitArray::FitPlane(), and FitPlane().
SetRMSR()
void LKGeoHelix::SetRMSR (Double_t val) inherited
Definition at line 36 of file LKGeoHelix.cpp.
References LKGeoHelix::fRMSR.
Referenced by Fit(), and LKHitArray::FitHelix().
SetRMST()
void LKGeoHelix::SetRMST (Double_t val) inherited
Definition at line 37 of file LKGeoHelix.cpp.
References LKGeoHelix::fRMST.
Referenced by Fit(), and LKHitArray::FitHelix().
SetS()
void LKGeoHelix::SetS (Double_t val) inherited
Definition at line 64 of file LKGeoHelix.cpp.
References LKGeoHelix::fS.
Referenced by LKHitArray::FitHelix().
SetT()
void LKGeoHelix::SetT (Double_t val) inherited
Definition at line 66 of file LKGeoHelix.cpp.
References LKGeoHelix::fT.
Referenced by LKHitArray::FitHelix().
SetTrackID()
void LKTracklet::SetTrackID (int val) inline inherited
Definition at line 75 of file LKTracklet.h.
References LKTracklet::fTrackID.
Referenced by LKTracklet::AddHit(), and LKTracklet::FinalizeHits().
SortHits()
void LKHelixTrack::SortHits (bool increasing = true) virtual
Reimplemented from LKTracklet.
Definition at line 275 of file LKHelixTrack.cpp.
References LKTracklet::fHitArray, LKHit::GetPosition(), Map(), and next().
Referenced by Continuity(), and SortHitsByTimeOrder().
SortHitsByTimeOrder()
void LKHelixTrack::SortHitsByTimeOrder ()
Definition at line 288 of file LKHelixTrack.cpp.
References fIsPositiveChargeParticle, and SortHits().
TrackLength()
Double_t LKHelixTrack::TrackLength () const virtual
Length of track calculated from head to tail.
Implements LKTracklet.
Definition at line 931 of file LKHelixTrack.cpp.
References LKGeoHelix::CosDip(), LKGeoHelix::fR, LKGeoHelix::GetH(), and LKGeoHelix::GetT().
Referenced by InterpolateByLength(), and Print().
TrajectoryOnPlane() [1/3]
TGraphErrors * LKTracklet::TrajectoryOnPlane (LKDetectorPlane * plane, double scale = 1) virtual inherited
Definition at line 179 of file LKTracklet.cpp.
References LKDetectorPlane::GetAxis1(), LKDetectorPlane::GetAxis2(), and LKTracklet::TrajectoryOnPlane().
TrajectoryOnPlane() [2/3]
TGraphErrors * LKTracklet::TrajectoryOnPlane (LKVector3::Axis axis1, LKVector3::Axis axis2, bool(*)(TVector3 pos) fisout, double scale = 1) virtual inherited
Definition at line 160 of file LKTracklet.cpp.
References LKTracklet::FillTrajectory(), and LKTracklet::fTrajectoryOnPlane.
Referenced by LKTracklet::TrajectoryOnPlane(), and LKTracklet::TrajectoryOnPlane().
TrajectoryOnPlane() [3/3]
TGraphErrors * LKTracklet::TrajectoryOnPlane (LKVector3::Axis axis1, LKVector3::Axis axis2, double scale = 1) virtual inherited
Definition at line 173 of file LKTracklet.cpp.
References LKTracklet::TrajectoryOnPlane().
TravelLengthAtAlpha()
Double_t LKGeoHelix::TravelLengthAtAlpha (Double_t alpha) const inherited
Length of track in change of alpha.
Definition at line 86 of file LKGeoHelix.cpp.
References LKGeoHelix::CosDip(), and LKGeoHelix::fR.
Referenced by LKGeoHelix::HelicoidMap().
Member Data Documentation
fA
axis_t LKGeoHelix::fA = LKVector3::kZ protected inherited
helix axis
Definition at line 27 of file LKGeoHelix.h.
Referenced by Clear(), Copy(), CrossSectionOnPlane(), LKGeoHelix::Direction(), ExtrapolateByMap(), ExtrapolateToAlpha(), ExtrapolateToPointK(), Fit(), LKGeoHelix::GetA(), LKGeoHelix::GetCenter(), GetLineDirection(), GetPlaneNormal(), GetReferenceAxis(), LKGeoHelix::HelicoidMap(), PerpLine(), PerpPlane(), LKGeoHelix::PositionAtAlpha(), Print(), LKGeoHelix::SetA(), LKGeoHelix::SetHelix(), and SetReferenceAxis().
fdEdxArray
std::vector<Double_t> LKHelixTrack::fdEdxArray private
dE/dx array;
Definition at line 27 of file LKHelixTrack.h.
Referenced by Clear(), GetdEdxArray(), and GetdEdxWithCut().
fFitStatus
LKFitStatus LKTracklet::fFitStatus protected inherited
One of kBad, kHelix and kLine.
Definition at line 61 of file LKTracklet.h.
Referenced by Clear(), Copy(), LKTracklet::GetFitStatus(), LKTracklet::GetFitStatusString(), LKTracklet::IsBad(), LKTracklet::IsGenfitTrack(), LKTracklet::IsHelix(), LKTracklet::IsLine(), LKTracklet::IsPlane(), Print(), LKTracklet::SetFitStatus(), LKTracklet::SetIsBad(), LKTracklet::SetIsGenfitTrack(), LKTracklet::SetIsHelix(), LKTracklet::SetIsLine(), and LKTracklet::SetIsPlane().
fGenfitID
Int_t LKHelixTrack::fGenfitID private
GENFIT Track ID.
Definition at line 23 of file LKHelixTrack.h.
Referenced by Clear(), Copy(), GetGenfitID(), and SetGenfitID().
fGenfitMomentum
Double_t LKHelixTrack::fGenfitMomentum private
Momentum reconstructed by GENFIT.
Definition at line 24 of file LKHelixTrack.h.
Referenced by Clear(), Copy(), GetGenfitMomentum(), Print(), and SetGenfitMomentum().
fH
Double_t LKGeoHelix::fH = 0 protected inherited
Alpha angle at head.
Definition at line 25 of file LKGeoHelix.h.
Referenced by Clear(), Copy(), DetermineParticleCharge(), LKGeoHelix::Direction(), ExtrapolateByMap(), ExtrapolateHead(), ExtrapolateTail(), ExtrapolateToI(), ExtrapolateToJ(), ExtrapolateToJ(), LKGeoHelix::GetCenter(), LKGeoHelix::GetH(), LKGeoHelix::GetRandomPoint(), LKGeoHelix::HelicoidMap(), InterpolateByRatio(), PositionAtHead(), SetAlphaHead(), LKGeoHelix::SetH(), and LKGeoHelix::SetHelix().
fHitArray
LKHitArray LKTracklet::fHitArray protected inherited
Definition at line 56 of file LKTracklet.h.
Referenced by LKTracklet::AddHit(), ClassImp(), LKTracklet::ClearHits(), Continuity(), LKTracklet::Continuity(), Copy(), LKLinearTrack::CopyFrom(), LKTracklet::FinalizeHits(), Fit(), LKLinearTrack::Fit(), LKTracklet::FitHelix(), LKTracklet::FitLine(), FitPlane(), LKTracklet::FitPlane(), LKTracklet::GetChargeSum(), LKTracklet::GetHit(), LKTracklet::GetHitArray(), LKTracklet::GetMean(), LKTracklet::IsHoldingHits(), PerpLine(), PerpPlane(), Print(), LKLinearTrack::Print(), LKTracklet::RecoverHitArrayWithHitID(), LKTracklet::RecoverHitArrayWithTrackID(), LKTracklet::RemoveHit(), LKLinearTrack::SetLine(), SortHits(), and LKTracklet::SortHits().
fHitIDArray
vector<int> LKTracklet::fHitIDArray protected inherited
Definition at line 57 of file LKTracklet.h.
Referenced by LKTracklet::AddHit(), ClassImp(), LKTracklet::ClearHits(), LKLinearTrack::CopyFrom(), LKTracklet::GetHitID(), LKTracklet::GetHitIDArray(), LKTracklet::GetNumHits(), LKTracklet::IsHoldingHits(), LKLinearTrack::Print(), LKTracklet::RecoverHitArrayWithHitID(), and LKTracklet::RemoveHit().
fI
Double_t LKGeoHelix::fI = 0 protected inherited
axis i-position
Definition at line 19 of file LKGeoHelix.h.
Referenced by CheckExtrapolateToI(), Clear(), Copy(), CrossSectionOnPlane(), LKGeoHelix::Direction(), ExtrapolateByMap(), ExtrapolateToAlpha(), ExtrapolateToI(), ExtrapolateToI(), ExtrapolateToJ(), ExtrapolateToJ(), ExtrapolateToPointK(), LKGeoHelix::GetCenter(), GetHelixCenterI(), LKGeoHelix::GetI(), GetLineDirection(), GetPlaneNormal(), LKGeoHelix::HelicoidMap(), LKGeoHelix::PositionAtAlpha(), Print(), LKGeoHelix::SetHelix(), SetHelixCenter(), LKGeoHelix::SetI(), SetLineDirection(), and SetPlaneNormal().
fIsPositiveChargeParticle
Bool_t LKHelixTrack::fIsPositiveChargeParticle private
Definition at line 26 of file LKHelixTrack.h.
Referenced by Clear(), Copy(), DetermineParticleCharge(), IsPositiveChargeParticle(), SetIsPositiveChargeParticle(), and SortHitsByTimeOrder().
fJ
Double_t LKGeoHelix::fJ = 0 protected inherited
axis j-position
Definition at line 20 of file LKGeoHelix.h.
Referenced by CheckExtrapolateToJ(), Clear(), Copy(), CrossSectionOnPlane(), LKGeoHelix::Direction(), ExtrapolateByMap(), ExtrapolateToAlpha(), ExtrapolateToI(), ExtrapolateToI(), ExtrapolateToJ(), ExtrapolateToJ(), ExtrapolateToPointK(), LKGeoHelix::GetCenter(), GetHelixCenterJ(), LKGeoHelix::GetJ(), GetLineDirection(), GetPlaneNormal(), LKGeoHelix::HelicoidMap(), LKGeoHelix::PositionAtAlpha(), Print(), LKGeoHelix::SetHelix(), SetHelixCenter(), LKGeoHelix::SetJ(), SetLineDirection(), and SetPlaneNormal().
fK
Double_t LKGeoHelix::fK = 0 protected inherited
k = fS * alpha + fK
Definition at line 23 of file LKGeoHelix.h.
Referenced by Clear(), Copy(), ExtrapolateToAlpha(), ExtrapolateToPointK(), LKGeoHelix::GetCenter(), LKGeoHelix::GetK(), GetKInitial(), LKGeoHelix::PositionAtAlpha(), LKGeoHelix::SetHelix(), LKGeoHelix::SetK(), and SetKInitial().
fParentID
int LKTracklet::fParentID = -1 protected inherited
Vertex ID.
Definition at line 53 of file LKTracklet.h.
Referenced by ClassImp(), Copy(), LKLinearTrack::CopyFrom(), LKTracklet::GetParentID(), Print(), LKMCTrack::Print(), LKMCTrack::SetMCTrack(), LKTracklet::SetParentID(), and LKMCTrack::TrajectoryOnPlane().
fPDG
int LKTracklet::fPDG = -1 protected inherited
Definition at line 54 of file LKTracklet.h.
Referenced by ClassImp(), LKLinearTrack::CopyFrom(), LKTracklet::GetPDG(), LKMCTrack::Print(), LKMCTrack::SetMCTrack(), LKTracklet::SetPDG(), and LKMCTrack::TrajectoryOnPlane().
fR
Double_t LKGeoHelix::fR = 0 protected inherited
Helix radius.
Definition at line 21 of file LKGeoHelix.h.
Referenced by LKGeoHelix::AlphaAtTravelLength(), CheckExtrapolateToI(), CheckExtrapolateToJ(), Clear(), Copy(), LKGeoHelix::DipAngle(), LKGeoHelix::Direction(), ExtrapolateByMap(), ExtrapolateToAlpha(), ExtrapolateToAlpha(), ExtrapolateToI(), ExtrapolateToI(), ExtrapolateToJ(), ExtrapolateToJ(), ExtrapolateToPointK(), GetHelixRadius(), GetLineDirection(), GetPlaneNormal(), LKGeoHelix::GetR(), LKGeoHelix::GetRandomPoint(), LKGeoHelix::HelicoidMap(), LKGeoHelix::LengthInPeriod(), Momentum(), LKGeoHelix::PositionAtAlpha(), Print(), LKGeoHelix::SetHelix(), SetHelixRadius(), SetLineDirection(), SetPlaneNormal(), LKGeoHelix::SetR(), TrackLength(), and LKGeoHelix::TravelLengthAtAlpha().
fRMS
Double_t LKGeometry::fRMS = -1 protected inherited
Definition at line 9 of file LKGeometry.h.
Referenced by LKLinearTrack::Fit(), LKGeometry::GetRMS(), and LKGeometry::SetRMS().
fRMSR
Double_t LKGeoHelix::fRMSR = -1 protected inherited
Definition at line 16 of file LKGeoHelix.h.
Referenced by LKGeoHelix::GetRMSR(), Print(), and LKGeoHelix::SetRMSR().
fRMST
Double_t LKGeoHelix::fRMST = -1 protected inherited
Definition at line 17 of file LKGeoHelix.h.
Referenced by LKGeoHelix::GetRMST(), Print(), and LKGeoHelix::SetRMST().
fS
Double_t LKGeoHelix::fS = 0 protected inherited
k = fS * alpha + fK
Definition at line 22 of file LKGeoHelix.h.
Referenced by Clear(), Copy(), DetermineParticleCharge(), LKGeoHelix::DipAngle(), ExtrapolateToAlpha(), ExtrapolateToPointK(), GetAlphaSlope(), LKGeoHelix::GetCenter(), LKGeoHelix::GetS(), LKGeoHelix::Helicity(), LKGeoHelix::KLengthInPeriod(), LKGeoHelix::PositionAtAlpha(), SetAlphaSlope(), LKGeoHelix::SetHelix(), and LKGeoHelix::SetS().
fT
Double_t LKGeoHelix::fT = 0 protected inherited
Alpha angle at tail.
Definition at line 24 of file LKGeoHelix.h.
Referenced by Clear(), Copy(), DetermineParticleCharge(), LKGeoHelix::Direction(), ExtrapolateByMap(), ExtrapolateHead(), ExtrapolateTail(), ExtrapolateToI(), ExtrapolateToJ(), ExtrapolateToJ(), LKGeoHelix::GetCenter(), LKGeoHelix::GetRandomPoint(), LKGeoHelix::GetT(), LKGeoHelix::HelicoidMap(), InterpolateByRatio(), Momentum(), PositionAtTail(), SetAlphaTail(), LKGeoHelix::SetHelix(), and LKGeoHelix::SetT().
fTrackID
int LKTracklet::fTrackID = -1 protected inherited
Definition at line 52 of file LKTracklet.h.
Referenced by LKTracklet::AddHit(), ClassImp(), Copy(), LKLinearTrack::CopyFrom(), LKTracklet::FinalizeHits(), LKTracklet::GetTrackID(), LKHelixTrack(), Print(), LKLinearTrack::Print(), LKMCTrack::Print(), LKTracklet::RecoverHitArrayWithTrackID(), LKMCTrack::SetMCTrack(), and LKTracklet::SetTrackID().
fTrajectoryOnPlane
TGraphErrors* LKTracklet::fTrajectoryOnPlane = nullptr protected inherited
Definition at line 59 of file LKTracklet.h.
Referenced by LKMCTrack::TrajectoryOnPlane(), LKTracklet::TrajectoryOnPlane(), LKExtrapolatedTrack::TrajectoryOnPlane(), and LKExtrapolatedTrack::TrajectoryOnPlane().
The documentation for this class was generated from the following files:
LKHelixTrack.h
LKHelixTrack.cpp