LILAK: LKEvePlane Class Reference
LKEvePlane Class Reference
#include <LKEvePlane.h>
Public Member Functions
void AddChannel (LKChannel *channel)
Add channel to channel array in detector plane. For interanl use.
void AddHit (LKHit *hit)
void AddInteractivePad (TVirtualPad *pad, TString option="")
void AddPad (LKPad *pad)
Add pad to pad array in detector plane. For interanl use.
void AddPar (LKParameterContainer *par)
void AddPar (TString fname)
virtual void AddParameterContainer (LKParameterContainer *par)
virtual void AddParameterContainer (TString fname)
virtual void Clear (Option_t *option="")
virtual void ClickedControlEvent1 (double xOnClick, double yOnClick)
virtual void ClickedControlEvent1 (int selectedBin)
virtual void ClickedControlEvent2 (double xOnClick, double yOnClick)
virtual void ClickedControlEvent2 (int selectedBin)
virtual void ClickedEventDisplay1 (double xOnClick, double yOnClick)
virtual void ClickedEventDisplay2 (double xOnClick, double yOnClick)
void CreateParameterContainer ()
virtual void Draw (Option_t *option="")
Implementation recommanded for event display. Draw event display to the canvas.
virtual void DrawFrame (Option_t *option="")
virtual void DrawHist (Option_t *option="")
virtual void DriftElectron (TVector3 posGlobal, TVector3 &posFinal, double &driftLength)
virtual double DriftElectronBack (double tb)
virtual void DriftElectronBack (int padID, double tb, TVector3 &posReco, double &driftLength)
virtual void DriftElectronBack (LKPad *pad, double tb, TVector3 &posReco, double &driftLength)
virtual void ExecMouseClickEventOnPad (TVirtualPad *pad, double xOnClick, double yOnClick)
virtual void FillDataToHist ()
Implementation recommanded. Fill data to histograms.
virtual void FillDataToHist (Option_t *option="")
Implementation recommanded. Fill data to histograms.
virtual void FillDataToHistEventDisplay1 (Option_t *option="")
virtual void FillDataToHistEventDisplay2 (Option_t *option="")
void FillPlane (double i, double j, double tb, double charge, int trackID=-1)
Find pad corresponding to the position (i,j) and fill time-bin by amount of charge.
virtual int FindChannelID (double i, double j)
Implementation recommanded. Find channel using position.
virtual int FindChannelID (int section, int layer, int row)
Implementation recommanded. Find channel using section, layer, row info.
virtual LKPad * FindPad (int cobo, int asad, int aget, int chan)
TODO.
virtual int FindPadID (double i, double j)
virtual int FindPadID (int cobo, int asad, int aget, int chan)
virtual int FindPadID (int section, int layer, int row)
virtual int FindPadIDFromHistEventDisplay1Bin (int hbin)
virtual int FindPadIDFromHistEventDisplay2Bin (int hbin)
virtual TPad * Get3DEventPad ()
If user wants to place 3D event display other than default canvas, this method should return corresponding TPad.
virtual axis_t GetAxis1 (int iPad=0) const
virtual axis_t GetAxis2 (int iPad=0) const
virtual axis_t GetAxis3 () const
virtual axis_t GetAxisDrift () const
virtual TCanvas * GetCanvas (Option_t *option="")
Implementation recommanded for event display.
LKChannel * GetChannel (int idx)
virtual LKChannelAnalyzer * GetChannelAnalyzer (int id=0)
TObjArray * GetChannelArray ()
LKChannel * GetChannelFast (int idx)
virtual TPad * GetCPad (int iPad)
For grabbing inner pads of canvas.
virtual TH2 * GetHist (Option_t *option="-1")
virtual TH1D * GetHistChannelBuffer ()
virtual TH2D * GetHistControlEvent1 ()
virtual TH2D * GetHistControlEvent2 ()
virtual TH2 * GetHistEventDisplay1 (Option_t *option="-1")
virtual TH2 * GetHistEventDisplay2 (Option_t *option="-1")
int GetNChannels ()
virtual int GetNumCPads ()
Get number of inner pads of canvas.
int GetNumPads ()
LKPad * GetPad (double i, double j)
LKPad * GetPad (int cobo, int asad, int aget, int chan)
LKPad * GetPad (int padID)
LKPad * GetPad (int section, int layer, int row)
TObjArray * GetPadArray ()
TPad * GetPadChannelBuffer ()
TPad * GetPadControlEvent1 ()
TPad * GetPadControlEvent2 ()
TPad * GetPadEventDisplay1 ()
TPad * GetPadEventDisplay2 ()
LKPad * GetPadFast (int idx)
int GetPadInteractiveID () const
LKParameterContainer * GetPar () const
LKParameterContainer * GetParameterContainer () const
int GetPlaneID () const
double GetPosition () const
Int_t GetRank () const
double GetTbToLength () const
virtual TVector3 GlobalToLocalAxis (TVector3 posGlobal)
Implementation recommanded. Convert global position to local detector plane position TODO.
void GrabNeighborPads (vector< LKPad * > *pads, vector< LKPad * > *neighborPads)
For tracking use.
virtual bool Init ()
virtual bool IsInBoundary (double i, double j)
Implementation recommanded. Return if position (i,j) is inside the effective detector plane boundary TODO.
LKEvePlane ()
LKEvePlane (const char *name, const char *title)
virtual TVector3 LocalToGlobalAxis (TVector3 posLocal)
Implementation recommanded. Convert local position to global detector plane position TODO.
virtual double PadDisplacement () const
Return average pad displacement to each other.
bool PadMapChecker ()
bool PadNeighborChecker ()
bool PadPositionChecker (bool checkCorners=true)
virtual void Print (Option_t *option="") const
void PullOutNeighborHits (double x, double y, int range, LKHitArray *neighborHits)
For tracking use.
void PullOutNeighborHits (double x, double y, int range, vector< LKHit * > *neighborHits)
For tracking use.
void PullOutNeighborHits (LKHitArray *hits, LKHitArray *neighborHits)
For tracking use.
void PullOutNeighborHits (TVector2 p, int range, vector< LKHit * > *neighborHits)
For tracking use.
void PullOutNeighborHits (vector< LKHit * > *hits, vector< LKHit * > *neighborHits)
For tracking use.
virtual LKHit * PullOutNextFreeHit ()
For tracking use.
virtual void ResetEvent ()
For tracking use.
virtual void ResetHitMap ()
For tracking use.
virtual bool SetDataFromBranch ()
Implementation recommanded. Set waveform and hit data from input tree branches to pads.
void SetDetector (LKDetector *detector)
void SetHitArray (TClonesArray *hitArray)
void SetPadArray (TClonesArray *padArray)
void SetPadInteractiveID (int id)
void SetPalette ()
void SetPar (LKParameterContainer *par)
virtual void SetParameterContainer (LKParameterContainer *par)
void SetPlaneID (int id)
virtual void SetRank (Int_t rank)
void SetRun (LKRun *run)
virtual void UpdateAll ()
virtual void UpdateChannelBuffer ()
virtual void UpdateControlEvent1 ()
virtual void UpdateControlEvent2 ()
virtual void UpdateEventDisplay1 ()
virtual void UpdateEventDisplay2 ()
virtual void UpdateFill (bool updateHist=true)
virtual void UpdateMenu ()
virtual ~LKEvePlane ()
Protected Attributes
bool fAccumulateAllEvents = false
int fAccumulateChannel = 0
to accumulate channel waveform
Long64_t fAccumulateEvent1 = 0
first accumulated event id
Long64_t fAccumulateEvent2 = 0
last accumulated event id
Long64_t fAccumulateEvents = 0
to accumulate event in event display
axis_t fAxis1 = LKVector3::kNon
Axis-1 lying in plane. Must be set by input parameter.
axis_t fAxis2 = LKVector3::kNon
Axis-2 lying in plane. Must be set by input parameter.
axis_t fAxis3 = LKVector3::kNon
Axis-3 = Axis-1 x Axis-2 perpendicular to plane.
axis_t fAxisDrift = LKVector3::kNon
Axis perpendicular to plane, in electron drifting direction. Must be set by input parameter.
int fBinCtrlAcmltCh
int fBinCtrlAcmltEv
int fBinCtrlChgMenu
int fBinCtrlCurr
int fBinCtrlDrawACh
int fBinCtrlE500
int fBinCtrlEngyMax
int fBinCtrlEngyMin
int fBinCtrlFillAEv
int fBinCtrlFitChan
int fBinCtrlFrst
int fBinCtrlLast
int fBinCtrlNe50
int fBinCtrlNext
int fBinCtrlPalette
int fBinCtrlPr50
int fBinCtrlPrev
int fBinCtrlSavePng
int fBinCtrlSaveRoo
int fBinDrawTrackGf
int fBinFillChACAAC
int fBinFillElectID
int fBinFillHitNHit
int fBinFillRawPrev
TCanvas * fCanvas = nullptr
LKChannelAnalyzer * fChannelAnalyzer = nullptr
TObjArray * fChannelArray = nullptr
TClonesArray * fChannelGraphArray = nullptr
array of accumulate channel graphs
Long64_t fCountChangeEvent = 0
int fCountChangeOther = 0
int fCountChannelGraph = 0
count number of accumulate channels
int fCountSaveFig = 0
int fCountSavePng = 0
int fCountSaveRoo = 0
int fCurrentMenu = 0
TCanvas * fCvsChannelBuffer = nullptr
LKDetector * fDetector = nullptr
double fDXCanvas = 1200
double fDYCanvas = 700
int fEnergyMax = 1
0 : auto, 1; 4200, >2: fEnergyMax = maximum value
int fEnergyMin = -1
0 : auto, 1; -1
TString fEventDisplayDrawOption = "colz"
TString fFillOptionSelected = "preview"
bool fFitChannel = false
for finding energy using fChannelAnalyzer
int fFreePadIdx = 0
TGraph * fGraphChannelBoundary = nullptr
TGraph * fGraphChannelBoundaryNb [20] = {0}
TGraph * fGSelEventDisplay1 = nullptr
TGraph * fGSelEventDisplay2 = nullptr
TH2 * fH2Plane = nullptr
TH1D * fHistChannelBuffer = nullptr
TH2D * fHistControlEvent1 = nullptr
TH2D * fHistControlEvent2 = nullptr
TH2 * fHistEventDisplay1 = nullptr
TH2 * fHistEventDisplay2 = nullptr
TClonesArray * fHitArray = nullptr
bool fHitDataIsSet = false
int fNumAccumulateChannels = 0
to accumulate channel waveform
axis_t fPadAxis1 [2] = {LKVector3::kNon, LKVector3::kNon}
axis_t fPadAxis2 [2] = {LKVector3::kNon, LKVector3::kNon}
TPad * fPadChannelBuffer = nullptr
TPad * fPadControlEvent1 = nullptr
TPad * fPadControlEvent2 = nullptr
bool fPadDataIsSet = false
TPad * fPadEventDisplay1 = nullptr
TPad * fPadEventDisplay2 = nullptr
int fPadInteractiveID = -1
bool fPaletteIsInverted = false
int fPaletteNumber = 0
LKParameterContainer * fPar = nullptr
int fPlaneID = -1
Detector plane id.
double fPosition
Global position of pad plane center.
Int_t fRank = 0
TClonesArray * fRawDataArray = nullptr
bool fReturnDraw = false
LKRun * fRun = nullptr
TString fSavePath = "eve_data"
int fSelPadID = 0
Selected pad id by mouse click.
int fSelRawDataID = 0
Selected raw data by mouse click.
double fTbToLength = 1
time-bin (tb) to position conversion factor. Must be set by input parameter.
TClonesArray * fTrackArray = nullptr
double fYCCanvas = 230./700
const TString kFillAget = "aget"
const TString kFillAsad = "asad"
const TString kFillCAAC = "caac"
const TString kFillChan = "chan"
const TString kFillCobo = "cobo"
const TString kFillHits = "hit"
const TString kFillNHit = "nhits"
const TString kFillPrev = "preview"
const TString kFillRawD = "raw"
const TString kFillZero = ""
Detailed Description
Definition at line 11 of file LKEvePlane.h.
Constructor & Destructor Documentation
LKEvePlane() [1/2]
LKEvePlane::LKEvePlane ()
LKEvePlane() [2/2]
LKEvePlane::LKEvePlane (const char * name, const char * title)
Definition at line 24 of file LKEvePlane.cpp.
References fGSelEventDisplay1, and fGSelEventDisplay2.
~LKEvePlane()
virtual LKEvePlane::~LKEvePlane () inline virtual
Definition at line 16 of file LKEvePlane.h.
Member Function Documentation
AddChannel()
void LKDetectorPlane::AddChannel (LKChannel * channel) inline inherited
Add channel to channel array in detector plane. For interanl use.
Definition at line 113 of file LKDetectorPlane.h.
References LKDetectorPlane::fChannelArray.
AddHit()
void LKDetectorPlane::AddHit (LKHit * hit) inherited
Definition at line 118 of file LKDetectorPlane.cpp.
References LKDetectorPlane::AddHit(), and LKDetectorPlane::GetPadFast().
Referenced by LKDetectorPlane::AddHit(), and LKDetectorPlane::SetHitArray().
AddInteractivePad()
void LKPadInteractive::AddInteractivePad (TVirtualPad * pad, TString option = "") inherited
Definition at line 6 of file LKPadInteractive.cpp.
References LKPadInteractiveManager::GetManager().
Referenced by LKHTLineTracker::Draw(), GetCanvas(), LKGETChannelViewer::Init(), and LKChannelAnalyzer::SetPad().
AddPad()
void LKDetectorPlane::AddPad (LKPad * pad) inline inherited
Add pad to pad array in detector plane. For interanl use.
Definition at line 114 of file LKDetectorPlane.h.
References LKDetectorPlane::fChannelArray.
AddPar() [1/2]
void LKGear::AddPar (LKParameterContainer * par) inline inherited
Definition at line 27 of file LKGear.h.
References LKGear::AddParameterContainer().
Referenced by LKTask::Add(), LKRun::EndOfRun(), LKRun::Init(), LKG4RunManager::Initialize(), LAMPSTPC::LAMPSTPC(), LAMPSTPC::LAMPSTPC(), LKDetectorSystem::SetDetectorPar(), LKRun::SetEventTrigger(), LKG4RunManager::SetSensitiveDetector(), LKG4RunManager::SetVolume(), LKRun::StartOfRun(), TexAT2::TexAT2(), TexAT2::TexAT2(), and TTMicromegas::WriteCurrentChannel().
AddPar() [2/2]
void LKGear::AddPar (TString fname) inline inherited
Definition at line 28 of file LKGear.h.
References LKGear::AddParameterContainer().
AddParameterContainer() [1/2]
void LKGear::AddParameterContainer (LKParameterContainer * par) virtual inherited
Definition at line 14 of file LKGear.cpp.
References LKGear::AddParameterContainer(), and LKGear::fPar.
Referenced by LKGear::AddPar(), LKGear::AddPar(), LKGear::AddParameterContainer(), LHTpc::BuildDetectorPlane(), and LKRun::Init().
AddParameterContainer() [2/2]
void LKGear::AddParameterContainer (TString fname) virtual inherited
Definition at line 22 of file LKGear.cpp.
References LKGear::fPar.
Clear()
void LKEvePlane::Clear (Option_t * option = "") virtual
Reimplemented from LKDetectorPlane.
Reimplemented in ATMicromegas, and LTPadPlane.
Definition at line 46 of file LKEvePlane.cpp.
References LKDetectorPlane::Clear().
Referenced by ATMicromegas::Clear(), and LTPadPlane::Clear().
ClickedControlEvent1() [1/2]
void LKEvePlane::ClickedControlEvent1 (double xOnClick, double yOnClick) virtual
Definition at line 1283 of file LKEvePlane.cpp.
References ClickedControlEvent1(), fHistControlEvent1, and LKGear::fRun.
Referenced by ClickedControlEvent1(), ClickedControlEvent2(), and ExecMouseClickEventOnPad().
ClickedControlEvent1() [2/2]
void LKEvePlane::ClickedControlEvent1 (int selectedBin) virtual
Definition at line 907 of file LKEvePlane.cpp.
References fAccumulateEvent2, fAccumulateEvents, fBinCtrlAcmltEv, fBinCtrlCurr, fBinCtrlE500, fBinCtrlFrst, fBinCtrlLast, fBinCtrlNe50, fBinCtrlNext, fBinCtrlPr50, fBinCtrlPrev, fHistControlEvent2, LKDetectorPlane::FillDataToHist(), fRawDataArray, LKGear::fRun, lk_error, lk_info, and SetDataFromBranch().
ClickedControlEvent2() [1/2]
void LKEvePlane::ClickedControlEvent2 (double xOnClick, double yOnClick) virtual
Definition at line 1295 of file LKEvePlane.cpp.
References ClickedControlEvent2(), and fHistControlEvent2.
Referenced by ClickedControlEvent2(), ClickedControlEvent2(), ExecMouseClickEventOnPad(), and UpdateFill().
ClickedControlEvent2() [2/2]
void LKEvePlane::ClickedControlEvent2 (int selectedBin) virtual
Definition at line 1010 of file LKEvePlane.cpp.
References ClickedControlEvent1(), ClickedControlEvent2(), Draw(), fAccumulateAllEvents, fAccumulateChannel, fAccumulateEvent1, fAccumulateEvent2, fAccumulateEvents, fBinCtrlAcmltCh, fBinCtrlAcmltEv, fBinCtrlChgMenu, fBinCtrlDrawACh, fBinCtrlEngyMax, fBinCtrlEngyMin, fBinCtrlFillAEv, fBinCtrlFitChan, fBinCtrlFrst, fBinCtrlLast, fBinCtrlPalette, fBinCtrlSavePng, fBinCtrlSaveRoo, fBinDrawTrackGf, fBinFillChACAAC, fBinFillElectID, fBinFillHitNHit, fBinFillRawPrev, LKDetectorPlane::fCanvas, LKDetectorPlane::fChannelArray, fCountChangeEvent, fCountChangeOther, fCountChannelGraph, fCountSavePng, fCountSaveRoo, fCurrentMenu, fEnergyMax, fEnergyMin, fFillOptionSelected, fFitChannel, fHistControlEvent2, fPaletteNumber, fRawDataArray, LKGear::fRun, fSavePath, fSelPadID, fSelRawDataID, LKRun::GetCurrentEventID(), kFillAget, kFillAsad, kFillCAAC, kFillChan, kFillCobo, kFillHits, kFillNHit, kFillPrev, kFillRawD, kFillZero, lk_info, lk_warning, SetPalette(), UpdateChannelBuffer(), UpdateEventDisplay1(), UpdateEventDisplay2(), UpdateFill(), and UpdateMenu().
ClickedEventDisplay1()
void LKEvePlane::ClickedEventDisplay1 (double xOnClick, double yOnClick) virtual
Reimplemented in LTPadPlane.
Definition at line 857 of file LKEvePlane.cpp.
References LKDetectorPlane::fChannelArray, fHistEventDisplay1, FindPadIDFromHistEventDisplay1Bin(), fSelPadID, lk_error, Print(), and UpdateChannelBuffer().
Referenced by ExecMouseClickEventOnPad().
ClickedEventDisplay2()
void LKEvePlane::ClickedEventDisplay2 (double xOnClick, double yOnClick) virtual
Reimplemented in ATMicromegas, and LTPadPlane.
Definition at line 882 of file LKEvePlane.cpp.
References LKDetectorPlane::fChannelArray, fHistEventDisplay2, FindPadIDFromHistEventDisplay2Bin(), fSelPadID, lk_error, Print(), and UpdateChannelBuffer().
Referenced by ExecMouseClickEventOnPad().
CreateParameterContainer()
void LKGear::CreateParameterContainer () inherited
Referenced by LKRun::AddDetector(), and LKRun::LKRun().
Draw()
void LKEvePlane::Draw (Option_t * option = "") virtual
Implementation recommanded for event display. Draw event display to the canvas.
Reimplemented from LKDetectorPlane.
Definition at line 97 of file LKEvePlane.cpp.
References fEventDisplayDrawOption, LKDetectorPlane::FillDataToHist(), fReturnDraw, GetCanvas(), GetHist(), SetDataFromBranch(), SetPalette(), and UpdateAll().
Referenced by ClickedControlEvent2(), DrawHist(), GetCanvas(), ATMicromegas::UpdateChannelBuffer(), UpdateChannelBuffer(), UpdateControlEvent1(), UpdateControlEvent2(), LTPadPlane::UpdateEventDisplay1(), UpdateEventDisplay1(), ATMicromegas::UpdateEventDisplay2(), LTPadPlane::UpdateEventDisplay2(), and UpdateEventDisplay2().
DrawFrame()
virtual void LKEvePlane::DrawFrame (Option_t * option = "") inline virtual
Reimplemented from LKDetectorPlane.
Definition at line 28 of file LKEvePlane.h.
DrawHist()
void LKEvePlane::DrawHist (Option_t * option = "") virtual
Reimplemented from LKDetectorPlane.
Definition at line 586 of file LKEvePlane.cpp.
References Draw(), LKDetectorPlane::FillDataToHist(), fPadEventDisplay1, GetCanvas(), and GetHist().
DriftElectron()
void LKDetectorPlane::DriftElectron (TVector3 posGlobal, TVector3 & posFinal, double & driftLength) virtual inherited
Implementation recommanded. Return position (x,y,z). x,y is pad position in pad plane. z is pad plane position of electron-drift-axis (for simulation)
Parameters
posGlobal[in] Given global position of the electron.
posFinal[in] Final position of electron after full drift (at the pad plane).
driftLength[out] Final drift length of the electron
Definition at line 679 of file LKDetectorPlane.cpp.
References LKVector3::At(), LKDetectorPlane::fAxis1, LKDetectorPlane::fAxis2, LKDetectorPlane::fAxis3, and LKDetectorPlane::fPosition.
DriftElectronBack() [1/3]
double LKDetectorPlane::DriftElectronBack (double tb) virtual inherited
Implementation recommanded. return drift length
Definition at line 708 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fPosition, and LKDetectorPlane::fTbToLength.
DriftElectronBack() [2/3]
void LKEvePlane::DriftElectronBack (int padID, double tb, TVector3 & posReco, double & driftLength) virtual
Reimplemented from LKDetectorPlane.
Definition at line 660 of file LKEvePlane.cpp.
References LKDetectorPlane::fAxis3, LKDetectorPlane::fAxisDrift, LKDetectorPlane::fChannelArray, LKDetectorPlane::fPosition, LKDetectorPlane::fTbToLength, LKVector3::GetXYZ(), LKVector3::SetI(), LKVector3::SetJ(), and LKVector3::SetK().
DriftElectronBack() [3/3]
void LKDetectorPlane::DriftElectronBack (LKPad * pad, double tb, TVector3 & posReco, double & driftLength) virtual inherited
Implementation recommanded. Set poseReco to global position using pad position, and time-bin tb. Pad position must be set from Init(). Conversion from time-bin (tb) to position in time-axis (post) is calculated by : post = fTbToLength * tb + fPosition [fTbToLength] is tb to position conversion factor with direction and [fPosition] is detector plane position in time-axis.
Parameters
pad[in] channel (pad)
tb[in] Time-bin
posReco[out] Reconstructed position of electron(?) before drift.
driftLength[out] Drift length of the electron from the reconstructed position.
Definition at line 689 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fAxis3, LKDetectorPlane::fAxisDrift, LKDetectorPlane::fPosition, LKDetectorPlane::fTbToLength, LKPad::GetI(), LKPad::GetJ(), LKVector3::GetXYZ(), LKVector3::SetI(), LKVector3::SetJ(), and LKVector3::SetK().
Referenced by LKDetectorPlane::DriftElectronBack().
ExecMouseClickEventOnPad()
void LKEvePlane::ExecMouseClickEventOnPad (TVirtualPad * pad, double xOnClick, double yOnClick) virtual
Reimplemented from LKPadInteractive.
Definition at line 849 of file LKEvePlane.cpp.
References ClickedControlEvent1(), ClickedControlEvent2(), ClickedEventDisplay1(), ClickedEventDisplay2(), fCountChangeEvent, fCountChangeOther, fPadControlEvent1, fPadControlEvent2, fPadEventDisplay1, and fPadEventDisplay2.
FillDataToHist() [1/2]
void LKDetectorPlane::FillDataToHist () virtual inherited
Implementation recommanded. Fill data to histograms.
Reimplemented in LKPadPlane, TTMicromegas, and TTFrontPlane.
Definition at line 136 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fChannelArray, LKDetectorPlane::fH2Plane, LKDetectorPlane::fHitDataIsSet, LKDetectorPlane::fPadDataIsSet, LKGear::fPar, LKDetectorPlane::GetHist(), LKPad::GetI(), LKPad::GetJ(), LKPad::GetLayer(), GETChannel::GetNumHits(), LKChannel::GetPadID(), LKPad::GetRow(), LKPad::GetSection(), lk_error, and lk_info.
Referenced by ClickedControlEvent1(), LKDetectorPlane::Draw(), Draw(), LKDetectorPlane::DrawHist(), DrawHist(), and UpdateFill().
FillDataToHist() [2/2]
void LKEvePlane::FillDataToHist (Option_t * option = "") virtual
Implementation recommanded. Fill data to histograms.
Reimplemented in LTPadPlane.
Definition at line 674 of file LKEvePlane.cpp.
References FillDataToHistEventDisplay1(), and FillDataToHistEventDisplay2().
FillDataToHistEventDisplay1()
void LKEvePlane::FillDataToHistEventDisplay1 (Option_t * option = "") virtual
Definition at line 680 of file LKEvePlane.cpp.
References fAccumulateEvent1, fAccumulateEvent2, fAccumulateEvents, LKDetectorPlane::fAxisDrift, LKDetectorPlane::fChannelArray, fEnergyMax, fFillOptionSelected, fHistEventDisplay1, fHitArray, fRawDataArray, LKGear::fRun, GETParameters::GetAget(), GETParameters::GetAsad(), GETParameters::GetChan(), GETParameters::GetCobo(), LKPad::GetI(), LKPad::GetJ(), LKPad::GetLayer(), GETChannel::GetNumHits(), LKChannel::GetPadID(), LKDetectorPlane::GetPosition(), LKPad::GetRow(), LKRun::GetRunName(), LKPad::GetSection(), lk_error, and lk_info.
Referenced by FillDataToHist().
FillDataToHistEventDisplay2()
virtual void LKEvePlane::FillDataToHistEventDisplay2 (Option_t * option = "") inline virtual
Reimplemented in ATMicromegas.
Definition at line 48 of file LKEvePlane.h.
Referenced by FillDataToHist().
FillPlane()
void LKDetectorPlane::FillPlane (double i, double j, double tb, double charge, int trackID = -1) inherited
Find pad corresponding to the position (i,j) and fill time-bin by amount of charge.
Definition at line 125 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fChannelArray, and LKDetectorPlane::FindPadID().
FindChannelID() [1/2]
virtual int LKEvePlane::FindChannelID (double i, double j) inline virtual
Implementation recommanded. Find channel using position.
Reimplemented from LKDetectorPlane.
Definition at line 38 of file LKEvePlane.h.
FindChannelID() [2/2]
virtual int LKEvePlane::FindChannelID (int section, int layer, int row) inline virtual
Implementation recommanded. Find channel using section, layer, row info.
Reimplemented from LKDetectorPlane.
Definition at line 39 of file LKEvePlane.h.
FindPad()
LKPad * LKEvePlane::FindPad (int cobo, int asad, int aget, int chan) virtual
TODO.
Reimplemented in ATMicromegas.
Definition at line 649 of file LKEvePlane.cpp.
References LKDetectorPlane::fChannelArray, and FindPadID().
Referenced by SetDataFromBranch().
FindPadID() [1/3]
virtual int LKDetectorPlane::FindPadID (double i, double j) inline virtual inherited
Reimplemented in LTPadPlane.
Definition at line 123 of file LKDetectorPlane.h.
References LKDetectorPlane::FindChannelID().
Referenced by LKDetectorPlane::FillPlane(), LKDetectorPlane::GetPad(), LKDetectorPlane::GetPad(), LKDetectorPlane::GetPad(), LKDetectorPlane::PadMapChecker(), LKDetectorPlane::PadPositionChecker(), LKDetectorPlane::PullOutNeighborHits(), and LKDetectorPlane::PullOutNeighborHits().
FindPadID() [2/3]
int LKEvePlane::FindPadID (int cobo, int asad, int aget, int chan) virtual
Reimplemented from LKDetectorPlane.
Reimplemented in ATMicromegas, and LTPadPlane.
Definition at line 643 of file LKEvePlane.cpp.
Referenced by FindPad(), and SetDataFromBranch().
FindPadID() [3/3]
virtual int LKDetectorPlane::FindPadID (int section, int layer, int row) inline virtual inherited
Reimplemented in LTPadPlane.
Definition at line 124 of file LKDetectorPlane.h.
References LKDetectorPlane::FindChannelID().
FindPadIDFromHistEventDisplay1Bin()
virtual int LKEvePlane::FindPadIDFromHistEventDisplay1Bin (int hbin) inline virtual
Reimplemented in ATMicromegas.
Definition at line 86 of file LKEvePlane.h.
Referenced by ClickedEventDisplay1().
FindPadIDFromHistEventDisplay2Bin()
virtual int LKEvePlane::FindPadIDFromHistEventDisplay2Bin (int hbin) inline virtual
Definition at line 87 of file LKEvePlane.h.
Referenced by ClickedEventDisplay2().
Get3DEventPad()
virtual TPad * LKEvePlane::Get3DEventPad () inline virtual
If user wants to place 3D event display other than default canvas, this method should return corresponding TPad.
Reimplemented from LKDetectorPlane.
Reimplemented in ATMicromegas.
Definition at line 57 of file LKEvePlane.h.
GetAxis1()
axis_t LKEvePlane::GetAxis1 (int iPad = 0) const virtual
Reimplemented from LKDetectorPlane.
Definition at line 79 of file LKEvePlane.cpp.
References LKDetectorPlane::fAxis1, fPadAxis1, and LKVector3::kNon.
GetAxis2()
axis_t LKEvePlane::GetAxis2 (int iPad = 0) const virtual
Reimplemented from LKDetectorPlane.
Definition at line 88 of file LKEvePlane.cpp.
References LKDetectorPlane::fAxis2, fPadAxis2, and LKVector3::kNon.
GetAxis3()
virtual axis_t LKDetectorPlane::GetAxis3 () const inline virtual inherited
Definition at line 62 of file LKDetectorPlane.h.
References LKDetectorPlane::fAxis3.
GetAxisDrift()
virtual axis_t LKDetectorPlane::GetAxisDrift () const inline virtual inherited
Definition at line 63 of file LKDetectorPlane.h.
References LKDetectorPlane::fAxisDrift.
GetCanvas()
TCanvas * LKEvePlane::GetCanvas (Option_t * option = "") virtual
Implementation recommanded for event display.
Reimplemented from LKDetectorPlane.
Definition at line 415 of file LKEvePlane.cpp.
References LKPadInteractive::AddInteractivePad(), Draw(), LKDetectorPlane::fCanvas, fDXCanvas, fDYCanvas, fPadChannelBuffer, fPadControlEvent1, fPadControlEvent2, fPadEventDisplay1, fPadEventDisplay2, fYCCanvas, LKWindowManager::GetWindowManager(), and y2.
Referenced by Draw(), DrawHist(), and GetCPad().
GetChannel()
LKChannel * LKDetectorPlane::GetChannel (int idx) inherited
Definition at line 47 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fChannelArray.
GetChannelAnalyzer()
LKChannelAnalyzer * LKEvePlane::GetChannelAnalyzer (int id = 0) virtual
Reimplemented from LKDetectorPlane.
Reimplemented in LTPadPlane.
Definition at line 33 of file LKEvePlane.cpp.
References LKDetectorPlane::fChannelAnalyzer, LKGear::fPar, and Print().
Referenced by Init().
GetChannelArray()
TObjArray * LKDetectorPlane::GetChannelArray () inline inherited
Definition at line 118 of file LKDetectorPlane.h.
References LKDetectorPlane::fChannelArray.
GetChannelFast()
LKChannel * LKDetectorPlane::GetChannelFast (int idx) inline inherited
Definition at line 126 of file LKDetectorPlane.h.
References LKDetectorPlane::fChannelArray.
GetCPad()
virtual TPad * LKEvePlane::GetCPad (int iPad) inline virtual
For grabbing inner pads of canvas.
Reimplemented from LKDetectorPlane.
Definition at line 31 of file LKEvePlane.h.
References GetCanvas().
GetHist()
TH2 * LKEvePlane::GetHist (Option_t * option = "-1") virtual
Reimplemented from LKDetectorPlane.
Definition at line 576 of file LKEvePlane.cpp.
References fHistEventDisplay1, GetHistChannelBuffer(), GetHistControlEvent1(), GetHistControlEvent2(), GetHistEventDisplay1(), and GetHistEventDisplay2().
Referenced by Draw(), DrawHist(), and LTPadPlane::GetHistSection().
GetHistChannelBuffer()
TH1D * LKEvePlane::GetHistChannelBuffer () virtual
Reimplemented in ATMicromegas.
Definition at line 486 of file LKEvePlane.cpp.
References fHistChannelBuffer.
Referenced by GetHist().
GetHistControlEvent1()
TH2D * LKEvePlane::GetHistControlEvent1 () virtual
Definition at line 503 of file LKEvePlane.cpp.
References fBinCtrlCurr, fBinCtrlE500, fBinCtrlFrst, fBinCtrlLast, fBinCtrlNe50, fBinCtrlNext, fBinCtrlPr50, fBinCtrlPrev, fHistControlEvent1, fPaletteNumber, LKGear::fRun, and LKRun::GetNumEvents().
Referenced by GetHist().
GetHistControlEvent2()
TH2D * LKEvePlane::GetHistControlEvent2 () virtual
Definition at line 552 of file LKEvePlane.cpp.
References fHistControlEvent2, fPaletteNumber, and UpdateMenu().
Referenced by GetHist().
GetHistEventDisplay1()
TH2 * LKEvePlane::GetHistEventDisplay1 (Option_t * option = "-1") virtual
Reimplemented in ATMicromegas, and LTPadPlane.
Definition at line 458 of file LKEvePlane.cpp.
References fHistEventDisplay1.
Referenced by GetHist().
GetHistEventDisplay2()
TH2 * LKEvePlane::GetHistEventDisplay2 (Option_t * option = "-1") virtual
Reimplemented in ATMicromegas, and LTPadPlane.
Definition at line 472 of file LKEvePlane.cpp.
References fHistEventDisplay2.
Referenced by GetHist().
GetNChannels()
int LKDetectorPlane::GetNChannels () inline inherited
Definition at line 116 of file LKDetectorPlane.h.
References LKDetectorPlane::fChannelArray.
Referenced by LKDetectorPlane::GetNumPads(), and LKPadPlane::GetNumPads().
GetNumCPads()
virtual int LKEvePlane::GetNumCPads () inline virtual
Get number of inner pads of canvas.
Reimplemented from LKDetectorPlane.
Definition at line 30 of file LKEvePlane.h.
GetNumPads()
int LKDetectorPlane::GetNumPads () inline inherited
Definition at line 117 of file LKDetectorPlane.h.
References LKDetectorPlane::GetNChannels().
GetPad() [1/4]
LKPad * LKDetectorPlane::GetPad (double i, double j) inherited
Definition at line 61 of file LKDetectorPlane.cpp.
References LKDetectorPlane::FindPadID(), and LKDetectorPlane::GetPad().
GetPad() [2/4]
LKPad * LKDetectorPlane::GetPad (int cobo, int asad, int aget, int chan) inherited
Definition at line 77 of file LKDetectorPlane.cpp.
References LKDetectorPlane::FindPadID(), and LKDetectorPlane::GetPad().
GetPad() [3/4]
LKPad * LKDetectorPlane::GetPad (int padID) inherited
Definition at line 54 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fChannelArray.
Referenced by LKDetectorPlane::DriftElectronBack(), LKDetectorPlane::GetPad(), LKDetectorPlane::GetPad(), LKDetectorPlane::GetPad(), and LTPadPlane::Init().
GetPad() [4/4]
LKPad * LKDetectorPlane::GetPad (int section, int layer, int row) inherited
Definition at line 69 of file LKDetectorPlane.cpp.
References LKDetectorPlane::FindPadID(), and LKDetectorPlane::GetPad().
GetPadArray()
TObjArray * LKDetectorPlane::GetPadArray () inherited
Definition at line 430 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fChannelArray.
GetPadChannelBuffer()
TPad * LKEvePlane::GetPadChannelBuffer () inline
Definition at line 52 of file LKEvePlane.h.
References fPadChannelBuffer.
GetPadControlEvent1()
TPad * LKEvePlane::GetPadControlEvent1 () inline
Definition at line 53 of file LKEvePlane.h.
References fPadControlEvent1.
GetPadControlEvent2()
TPad * LKEvePlane::GetPadControlEvent2 () inline
Definition at line 54 of file LKEvePlane.h.
References fPadControlEvent2.
GetPadEventDisplay1()
TPad * LKEvePlane::GetPadEventDisplay1 () inline
Definition at line 50 of file LKEvePlane.h.
References fPadEventDisplay1.
GetPadEventDisplay2()
TPad * LKEvePlane::GetPadEventDisplay2 () inline
Definition at line 51 of file LKEvePlane.h.
References fPadEventDisplay2.
Referenced by ATMicromegas::Get3DEventPad().
GetPadFast()
LKPad * LKDetectorPlane::GetPadFast (int idx) inline inherited
Definition at line 127 of file LKDetectorPlane.h.
References LKDetectorPlane::fChannelArray.
Referenced by LKDetectorPlane::AddHit(), LKDetectorPlane::SetHitArray(), and LKDetectorPlane::SetPadArray().
GetPadInteractiveID()
int LKPadInteractive::GetPadInteractiveID () const inline inherited
Definition at line 14 of file LKPadInteractive.h.
References LKPadInteractive::fPadInteractiveID.
GetPar()
LKParameterContainer * LKGear::GetPar () const inherited
Definition at line 33 of file LKGear.cpp.
References LKGear::fPar.
GetParameterContainer()
LKParameterContainer * LKGear::GetParameterContainer () const inherited
Definition at line 32 of file LKGear.cpp.
References LKGear::fPar.
Referenced by ClassImp(), LHElectronicsTask::Init(), and LHVertexFindingTask::Init().
GetPlaneID()
int LKDetectorPlane::GetPlaneID () const inline inherited
Definition at line 57 of file LKDetectorPlane.h.
References LKDetectorPlane::fPlaneID.
Referenced by LKDetectorPlane::SetPadArray(), and LKPadPlane::SetPadArray().
GetPosition()
double LKDetectorPlane::GetPosition () const inline inherited
Definition at line 65 of file LKDetectorPlane.h.
References LKDetectorPlane::fPosition.
Referenced by TTMicromegas::FillDataToHist(), TTFrontPlane::FillDataToHist(), FillDataToHistEventDisplay1(), ATMicromegas::FillDataToHistEventDisplay2(), ATTPCStripPad::Init(), LKDetectorPlane::PadNeighborChecker(), LKPadPlane::PadNeighborChecker(), LKDetectorPlane::PadPositionChecker(), and LKPadPlane::PadPositionChecker().
GetRank()
Int_t LKGear::GetRank () const inherited
Definition at line 36 of file LKGear.cpp.
References LKGear::fRank.
GetTbToLength()
double LKDetectorPlane::GetTbToLength () const inline inherited
Definition at line 64 of file LKDetectorPlane.h.
References LKDetectorPlane::fTbToLength.
GlobalToLocalAxis()
virtual TVector3 LKEvePlane::GlobalToLocalAxis (TVector3 posGlobal) inline virtual
Implementation recommanded. Convert global position to local detector plane position TODO.
Reimplemented from LKDetectorPlane.
Definition at line 35 of file LKEvePlane.h.
GrabNeighborPads()
void LKDetectorPlane::GrabNeighborPads (vector< LKPad * > * pads, vector< LKPad * > * neighborPads) inherited
For tracking use.
Definition at line 417 of file LKDetectorPlane.cpp.
Referenced by LKDetectorPlane::PullOutNeighborHits(), LKDetectorPlane::PullOutNeighborHits(), and LHPadPlaneFan::PullOutNeighborHitsIn().
Init()
bool LKEvePlane::Init () virtual
Implementation recommanded. Init() method should implement pad information (id, position, neighbor) and add channel using AddChannel() or AddPad() method. All parameters should be configured such as axis-1,2,3, fPosition, fTbToLength from parameter container.
Reimplemented from LKDetectorPlane.
Reimplemented in ATMicromegas, and LTPadPlane.
Definition at line 56 of file LKEvePlane.cpp.
References fChannelGraphArray, fHitArray, LKGear::fPar, LKDetectorPlane::fPosition, fRawDataArray, LKGear::fRun, fSavePath, LKDetectorPlane::fTbToLength, fTrackArray, GetChannelAnalyzer(), and SetPalette().
Referenced by ATMicromegas::Init(), and LTPadPlane::Init().
IsInBoundary()
virtual bool LKEvePlane::IsInBoundary (double i, double j) inline virtual
Implementation recommanded. Return if position (i,j) is inside the effective detector plane boundary TODO.
Reimplemented from LKDetectorPlane.
Reimplemented in LTPadPlane.
Definition at line 34 of file LKEvePlane.h.
LocalToGlobalAxis()
virtual TVector3 LKEvePlane::LocalToGlobalAxis (TVector3 posLocal) inline virtual
Implementation recommanded. Convert local position to global detector plane position TODO.
Reimplemented from LKDetectorPlane.
Definition at line 36 of file LKEvePlane.h.
PadDisplacement()
virtual double LKEvePlane::PadDisplacement () const inline virtual
Return average pad displacement to each other.
Reimplemented from LKDetectorPlane.
Reimplemented in LTPadPlane.
Definition at line 33 of file LKEvePlane.h.
PadMapChecker()
bool LKDetectorPlane::PadMapChecker () inherited
Self debugging tool. Result will be printed out. For each pad, check 1) section, layer, row map 2) cobo, aget, asad, chan map
Definition at line 432 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fChannelArray, LKDetectorPlane::FindPadID(), lk_info, and lk_warning.
PadNeighborChecker()
bool LKDetectorPlane::PadNeighborChecker () inherited
Self debugging tool. Result will be printed out. For each pad, check number of registered neighbor pads.
Definition at line 539 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fChannelArray, LKPad::GetI(), LKPad::GetJ(), LKChannel::GetPadID(), LKDetectorPlane::GetPosition(), and lk_info.
PadPositionChecker()
bool LKDetectorPlane::PadPositionChecker (bool checkCorners = true) inherited
Self debugging tool. Result will be printed out. For each pad, check if pad found from FindPadID() using pad position of itself matches.
Definition at line 487 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fChannelArray, LKDetectorPlane::FindPadID(), LKPad::GetPadCorners(), LKDetectorPlane::GetPosition(), lk_info, and lk_warning.
Print()
void LKEvePlane::Print (Option_t * option = "") const virtual
Reimplemented from LKDetectorPlane.
Reimplemented in ATMicromegas, and LTPadPlane.
Definition at line 51 of file LKEvePlane.cpp.
References lk_info.
Referenced by ClickedEventDisplay1(), ClickedEventDisplay2(), and GetChannelAnalyzer().
PullOutNeighborHits() [1/5]
void LKDetectorPlane::PullOutNeighborHits (double x, double y, int range, LKHitArray * neighborHits) inherited
For tracking use.
Definition at line 328 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fChannelArray, LKDetectorPlane::FindPadID(), and LKDetectorPlane::GrabNeighborPads().
PullOutNeighborHits() [2/5]
void LKDetectorPlane::PullOutNeighborHits (double x, double y, int range, vector< LKHit * > * neighborHits) inherited
For tracking use.
Definition at line 380 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fChannelArray, LKDetectorPlane::FindPadID(), and LKDetectorPlane::GrabNeighborPads().
PullOutNeighborHits() [3/5]
void LKDetectorPlane::PullOutNeighborHits (LKHitArray * hits, LKHitArray * neighborHits) inherited
For tracking use.
Definition at line 315 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fChannelArray.
PullOutNeighborHits() [4/5]
void LKDetectorPlane::PullOutNeighborHits (TVector2 p, int range, vector< LKHit * > * neighborHits) inherited
For tracking use.
Definition at line 375 of file LKDetectorPlane.cpp.
References LKDetectorPlane::PullOutNeighborHits().
PullOutNeighborHits() [5/5]
void LKDetectorPlane::PullOutNeighborHits (vector< LKHit * > * hits, vector< LKHit * > * neighborHits) inherited
For tracking use.
Definition at line 365 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fChannelArray.
Referenced by LKDetectorPlane::PullOutNeighborHits().
PullOutNextFreeHit()
LKHit * LKDetectorPlane::PullOutNextFreeHit () virtual inherited
For tracking use.
Reimplemented in LKPadPlane.
Definition at line 300 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fChannelArray, LKDetectorPlane::fFreePadIdx, and LKDetectorPlane::PullOutNextFreeHit().
Referenced by LKDetectorPlane::PullOutNextFreeHit(), and LHPadPlaneFan::PullOutNextFreeHitIn().
ResetEvent()
void LKDetectorPlane::ResetEvent () virtual inherited
For tracking use.
Reimplemented in LKPadPlane.
Definition at line 277 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fChannelArray, and LKDetectorPlane::fFreePadIdx.
ResetHitMap()
void LKDetectorPlane::ResetHitMap () virtual inherited
For tracking use.
Reimplemented in LKPadPlane, and LHPadPlaneFan.
Definition at line 288 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fChannelArray, and LKDetectorPlane::fFreePadIdx.
Referenced by LHPadPlaneFan::ResetHitMap().
SetDataFromBranch()
bool LKEvePlane::SetDataFromBranch () virtual
Implementation recommanded. Set waveform and hit data from input tree branches to pads.
Reimplemented from LKDetectorPlane.
Definition at line 599 of file LKEvePlane.cpp.
References LKDetectorPlane::fChannelArray, FindPad(), FindPadID(), fRawDataArray, fSelPadID, fSelRawDataID, lk_error, and next().
Referenced by ClickedControlEvent1(), and Draw().
SetDetector()
void LKDetectorPlane::SetDetector (LKDetector * detector) inline inherited
Definition at line 55 of file LKDetectorPlane.h.
References LKDetectorPlane::fDetector.
SetHitArray()
void LKDetectorPlane::SetHitArray (TClonesArray * hitArray) inherited
Definition at line 102 of file LKDetectorPlane.cpp.
References LKDetectorPlane::AddHit(), LKDetectorPlane::fHitDataIsSet, and LKDetectorPlane::GetPadFast().
Referenced by LKDetectorPlane::SetDataFromBranch().
SetPadArray()
void LKDetectorPlane::SetPadArray (TClonesArray * padArray) inherited
Definition at line 85 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fPadDataIsSet, LKDetectorPlane::fPlaneID, LKDetectorPlane::GetPadFast(), and LKDetectorPlane::GetPlaneID().
Referenced by LKDetectorPlane::SetDataFromBranch().
SetPadInteractiveID()
void LKPadInteractive::SetPadInteractiveID (int id) inline inherited
Definition at line 13 of file LKPadInteractive.h.
References LKPadInteractive::fPadInteractiveID.
SetPalette()
void LKEvePlane::SetPalette ()
Definition at line 1304 of file LKEvePlane.cpp.
References fBinCtrlPalette, fHistControlEvent1, fHistControlEvent2, fPaletteIsInverted, fPaletteNumber, LKGear::fRun, LKRun::GetNumEvents(), and SetPalette().
Referenced by ClickedControlEvent2(), Draw(), Init(), and SetPalette().
SetPar()
void LKGear::SetPar (LKParameterContainer * par) inline inherited
Definition at line 26 of file LKGear.h.
References LKGear::SetParameterContainer().
Referenced by LKDetector::AddPlane(), LKRun::Init(), LKDetector::Init(), and LKMFMConversionTask::Init().
SetParameterContainer()
void LKGear::SetParameterContainer (LKParameterContainer * par) virtual inherited
Definition at line 10 of file LKGear.cpp.
References LKGear::fPar.
Referenced by ATTPC::BuildDetectorPlane(), and LKGear::SetPar().
SetPlaneID()
void LKDetectorPlane::SetPlaneID (int id) inline inherited
Definition at line 56 of file LKDetectorPlane.h.
References LKDetectorPlane::fPlaneID.
Referenced by ATMicromegas::Init(), ATTPC20RectanglePad::Init(), ATTPCHoneyCombPad::Init(), ATTPCRectanglePad::Init(), and ATTPCStripPad::Init().
SetRank()
void LKGear::SetRank (Int_t rank) virtual inherited
Reimplemented in LKTask.
Definition at line 35 of file LKGear.cpp.
References LKGear::fRank.
Referenced by LKDetector::AddPlane(), and LKDetectorSystem::SetDetector().
SetRun()
void LKGear::SetRun (LKRun * run) inline inherited
Definition at line 36 of file LKGear.h.
References LKGear::fRun, and run.
Referenced by LKRun::Add(), LKRun::AddDetector(), LKRun::Init(), LKDetectorSystem::SetDetector(), and LKRun::SetEventTrigger().
UpdateAll()
void LKEvePlane::UpdateAll () virtual
Definition at line 118 of file LKEvePlane.cpp.
References UpdateChannelBuffer(), UpdateControlEvent1(), UpdateControlEvent2(), UpdateEventDisplay1(), and UpdateEventDisplay2().
Referenced by Draw().
UpdateChannelBuffer()
void LKEvePlane::UpdateChannelBuffer () virtual
Reimplemented in ATMicromegas.
Definition at line 167 of file LKEvePlane.cpp.
References Draw(), fAccumulateChannel, LKDetectorPlane::fChannelAnalyzer, LKDetectorPlane::fChannelArray, fChannelGraphArray, fCountChannelGraph, fEnergyMax, fFitChannel, fGSelEventDisplay1, fHistChannelBuffer, fPadChannelBuffer, fPadEventDisplay1, fPaletteNumber, fRawDataArray, fSelPadID, fSelRawDataID, lk_error, lk_info, SetPoint(), x0, y0, z0, z1, and z2.
Referenced by ClickedControlEvent2(), LTPadPlane::ClickedEventDisplay1(), ClickedEventDisplay1(), ClickedEventDisplay2(), UpdateAll(), and ATMicromegas::UpdateChannelBuffer().
UpdateControlEvent1()
void LKEvePlane::UpdateControlEvent1 () virtual
Definition at line 350 of file LKEvePlane.cpp.
References Draw(), fBinCtrlCurr, fBinCtrlNe50, fBinCtrlNext, fBinCtrlPr50, fBinCtrlPrev, fHistControlEvent1, fPadControlEvent1, and LKGear::fRun.
Referenced by UpdateAll().
UpdateControlEvent2()
void LKEvePlane::UpdateControlEvent2 () virtual
Definition at line 370 of file LKEvePlane.cpp.
References Draw(), fHistControlEvent2, fPadControlEvent2, and LKGear::fRun.
Referenced by UpdateAll().
UpdateEventDisplay1()
void LKEvePlane::UpdateEventDisplay1 () virtual
Reimplemented in ATMicromegas, and LTPadPlane.
Definition at line 127 of file LKEvePlane.cpp.
References Draw(), fEnergyMax, fEnergyMin, fEventDisplayDrawOption, fHistEventDisplay1, and fPadEventDisplay1.
Referenced by ClickedControlEvent2(), UpdateAll(), ATMicromegas::UpdateEventDisplay1(), and UpdateFill().
UpdateEventDisplay2()
void LKEvePlane::UpdateEventDisplay2 () virtual
Reimplemented in ATMicromegas, and LTPadPlane.
Definition at line 147 of file LKEvePlane.cpp.
References Draw(), fEnergyMax, fEnergyMin, fEventDisplayDrawOption, fHistEventDisplay2, and fPadEventDisplay2.
Referenced by ClickedControlEvent2(), UpdateAll(), and UpdateFill().
UpdateFill()
void LKEvePlane::UpdateFill (bool updateHist = true) virtual
Definition at line 1250 of file LKEvePlane.cpp.
References ClickedControlEvent2(), fBinCtrlEngyMax, fBinCtrlEngyMin, fBinFillChACAAC, fBinFillElectID, fBinFillHitNHit, fBinFillRawPrev, fEnergyMax, fEnergyMin, fFillOptionSelected, fHistControlEvent2, LKDetectorPlane::FillDataToHist(), kFillAget, kFillAsad, kFillCAAC, kFillChan, kFillCobo, kFillHits, kFillNHit, kFillPrev, kFillRawD, UpdateEventDisplay1(), and UpdateEventDisplay2().
Referenced by ClickedControlEvent2(), and UpdateMenu().
UpdateMenu()
void LKEvePlane::UpdateMenu () virtual
Definition at line 382 of file LKEvePlane.cpp.
References fAccumulateAllEvents, fAccumulateChannel, fAccumulateEvents, fBinCtrlAcmltCh, fBinCtrlAcmltEv, fBinCtrlChgMenu, fBinCtrlDrawACh, fBinCtrlEngyMax, fBinCtrlEngyMin, fBinCtrlFillAEv, fBinCtrlFitChan, fBinCtrlPalette, fBinCtrlSavePng, fBinCtrlSaveRoo, fBinFillChACAAC, fBinFillElectID, fBinFillHitNHit, fBinFillRawPrev, fCurrentMenu, fEnergyMax, fEnergyMin, fFitChannel, fHistControlEvent2, fPaletteNumber, and UpdateFill().
Referenced by ClickedControlEvent2(), and GetHistControlEvent2().
Member Data Documentation
fAccumulateAllEvents
bool LKEvePlane::fAccumulateAllEvents = false protected
Definition at line 168 of file LKEvePlane.h.
Referenced by ClickedControlEvent2(), and UpdateMenu().
fAccumulateChannel
int LKEvePlane::fAccumulateChannel = 0 protected
to accumulate channel waveform
Definition at line 173 of file LKEvePlane.h.
Referenced by ClickedControlEvent2(), ATMicromegas::ClickedEventDisplay2(), UpdateChannelBuffer(), and UpdateMenu().
fAccumulateEvent1
Long64_t LKEvePlane::fAccumulateEvent1 = 0 protected
first accumulated event id
Definition at line 170 of file LKEvePlane.h.
Referenced by ClickedControlEvent2(), LTPadPlane::FillDataToHist(), and FillDataToHistEventDisplay1().
fAccumulateEvent2
Long64_t LKEvePlane::fAccumulateEvent2 = 0 protected
last accumulated event id
Definition at line 171 of file LKEvePlane.h.
Referenced by ClickedControlEvent1(), ClickedControlEvent2(), LTPadPlane::FillDataToHist(), and FillDataToHistEventDisplay1().
fAccumulateEvents
Long64_t LKEvePlane::fAccumulateEvents = 0 protected
to accumulate event in event display
Definition at line 169 of file LKEvePlane.h.
Referenced by ClickedControlEvent1(), ClickedControlEvent2(), LTPadPlane::FillDataToHist(), FillDataToHistEventDisplay1(), ATMicromegas::FillDataToHistEventDisplay2(), and UpdateMenu().
fAxis1
axis_t LKDetectorPlane::fAxis1 = LKVector3::kNon protected inherited
Axis-1 lying in plane. Must be set by input parameter.
Definition at line 32 of file LKDetectorPlane.h.
Referenced by LKDetectorPlane::DriftElectron(), ATTPC20RectanglePad::FindPadID(), ATTPCHoneyCombPad::FindPadID(), ATTPCRectanglePad::FindPadID(), ATTPCStripPad::FindPadID(), LKDetectorPlane::GetAxis1(), GetAxis1(), ATTPC20RectanglePad::GetHist(), ATTPCHoneyCombPad::GetHist(), ATTPCRectanglePad::GetHist(), ATTPCStripPad::GetHist(), LTPadPlane::Init(), ATTPC20RectanglePad::Init(), ATTPCHoneyCombPad::Init(), ATTPCRectanglePad::Init(), ATTPCStripPad::Init(), and TTMicromegas::TTMicromegas().
fAxis2
axis_t LKDetectorPlane::fAxis2 = LKVector3::kNon protected inherited
Axis-2 lying in plane. Must be set by input parameter.
Definition at line 33 of file LKDetectorPlane.h.
Referenced by LKDetectorPlane::DriftElectron(), ATTPC20RectanglePad::FindPadID(), ATTPCHoneyCombPad::FindPadID(), ATTPCRectanglePad::FindPadID(), ATTPCStripPad::FindPadID(), LKDetectorPlane::GetAxis2(), GetAxis2(), ATTPC20RectanglePad::GetHist(), ATTPCHoneyCombPad::GetHist(), ATTPCRectanglePad::GetHist(), ATTPCStripPad::GetHist(), LTPadPlane::Init(), ATTPC20RectanglePad::Init(), ATTPCHoneyCombPad::Init(), ATTPCRectanglePad::Init(), ATTPCStripPad::Init(), and TTMicromegas::TTMicromegas().
fAxis3
axis_t LKDetectorPlane::fAxis3 = LKVector3::kNon protected inherited
Axis-3 = Axis-1 x Axis-2 perpendicular to plane.
Definition at line 34 of file LKDetectorPlane.h.
Referenced by LKDetectorPlane::DriftElectron(), DriftElectronBack(), LKDetectorPlane::DriftElectronBack(), LKDetectorPlane::GetAxis3(), and LTPadPlane::Init().
fAxisDrift
axis_t LKDetectorPlane::fAxisDrift = LKVector3::kNon protected inherited
Axis perpendicular to plane, in electron drifting direction. Must be set by input parameter.
Definition at line 35 of file LKDetectorPlane.h.
Referenced by DriftElectronBack(), LKDetectorPlane::DriftElectronBack(), FillDataToHistEventDisplay1(), ATMicromegas::FillDataToHistEventDisplay2(), LKDetectorPlane::GetAxisDrift(), and LTPadPlane::Init().
fBinCtrlAcmltCh
int LKEvePlane::fBinCtrlAcmltCh protected
Definition at line 115 of file LKEvePlane.h.
Referenced by ClickedControlEvent2(), ATMicromegas::ClickedEventDisplay2(), and UpdateMenu().
fBinCtrlAcmltEv
int LKEvePlane::fBinCtrlAcmltEv protected
Definition at line 117 of file LKEvePlane.h.
Referenced by ClickedControlEvent1(), ClickedControlEvent2(), and UpdateMenu().
fBinCtrlChgMenu
int LKEvePlane::fBinCtrlChgMenu protected
Definition at line 109 of file LKEvePlane.h.
Referenced by ClickedControlEvent2(), and UpdateMenu().
fBinCtrlCurr
int LKEvePlane::fBinCtrlCurr protected
Definition at line 143 of file LKEvePlane.h.
Referenced by ClickedControlEvent1(), GetHistControlEvent1(), and UpdateControlEvent1().
fBinCtrlDrawACh
int LKEvePlane::fBinCtrlDrawACh protected
Definition at line 114 of file LKEvePlane.h.
Referenced by ClickedControlEvent2(), ATMicromegas::ClickedEventDisplay2(), and UpdateMenu().
fBinCtrlE500
int LKEvePlane::fBinCtrlE500 protected
Definition at line 147 of file LKEvePlane.h.
Referenced by ClickedControlEvent1(), and GetHistControlEvent1().
fBinCtrlEngyMax
int LKEvePlane::fBinCtrlEngyMax protected
Definition at line 112 of file LKEvePlane.h.
Referenced by ClickedControlEvent2(), UpdateFill(), and UpdateMenu().
fBinCtrlEngyMin
int LKEvePlane::fBinCtrlEngyMin protected
Definition at line 111 of file LKEvePlane.h.
Referenced by ClickedControlEvent2(), UpdateFill(), and UpdateMenu().
fBinCtrlFillAEv
int LKEvePlane::fBinCtrlFillAEv protected
Definition at line 116 of file LKEvePlane.h.
Referenced by ClickedControlEvent2(), and UpdateMenu().
fBinCtrlFitChan
int LKEvePlane::fBinCtrlFitChan protected
Definition at line 113 of file LKEvePlane.h.
Referenced by ClickedControlEvent2(), and UpdateMenu().
fBinCtrlFrst
int LKEvePlane::fBinCtrlFrst protected
Definition at line 140 of file LKEvePlane.h.
Referenced by ClickedControlEvent1(), ClickedControlEvent2(), and GetHistControlEvent1().
fBinCtrlLast
int LKEvePlane::fBinCtrlLast protected
Definition at line 146 of file LKEvePlane.h.
Referenced by ClickedControlEvent1(), ClickedControlEvent2(), and GetHistControlEvent1().
fBinCtrlNe50
int LKEvePlane::fBinCtrlNe50 protected
Definition at line 145 of file LKEvePlane.h.
Referenced by ClickedControlEvent1(), GetHistControlEvent1(), and UpdateControlEvent1().
fBinCtrlNext
int LKEvePlane::fBinCtrlNext protected
Definition at line 144 of file LKEvePlane.h.
Referenced by ClickedControlEvent1(), GetHistControlEvent1(), and UpdateControlEvent1().
fBinCtrlPalette
int LKEvePlane::fBinCtrlPalette protected
Definition at line 124 of file LKEvePlane.h.
Referenced by ClickedControlEvent2(), SetPalette(), and UpdateMenu().
fBinCtrlPr50
int LKEvePlane::fBinCtrlPr50 protected
Definition at line 141 of file LKEvePlane.h.
Referenced by ClickedControlEvent1(), GetHistControlEvent1(), and UpdateControlEvent1().
fBinCtrlPrev
int LKEvePlane::fBinCtrlPrev protected
Definition at line 142 of file LKEvePlane.h.
Referenced by ClickedControlEvent1(), GetHistControlEvent1(), and UpdateControlEvent1().
fBinCtrlSavePng
int LKEvePlane::fBinCtrlSavePng protected
Definition at line 125 of file LKEvePlane.h.
Referenced by ClickedControlEvent2(), and UpdateMenu().
fBinCtrlSaveRoo
int LKEvePlane::fBinCtrlSaveRoo protected
Definition at line 126 of file LKEvePlane.h.
Referenced by ClickedControlEvent2(), and UpdateMenu().
fBinDrawTrackGf
int LKEvePlane::fBinDrawTrackGf protected
Definition at line 123 of file LKEvePlane.h.
Referenced by ClickedControlEvent2().
fBinFillChACAAC
int LKEvePlane::fBinFillChACAAC protected
Definition at line 120 of file LKEvePlane.h.
Referenced by ClickedControlEvent2(), UpdateFill(), and UpdateMenu().
fBinFillElectID
int LKEvePlane::fBinFillElectID protected
Definition at line 119 of file LKEvePlane.h.
Referenced by ClickedControlEvent2(), UpdateFill(), and UpdateMenu().
fBinFillHitNHit
int LKEvePlane::fBinFillHitNHit protected
Definition at line 122 of file LKEvePlane.h.
Referenced by ClickedControlEvent2(), UpdateFill(), and UpdateMenu().
fBinFillRawPrev
int LKEvePlane::fBinFillRawPrev protected
Definition at line 121 of file LKEvePlane.h.
Referenced by ClickedControlEvent2(), UpdateFill(), and UpdateMenu().
fCanvas
TCanvas* LKDetectorPlane::fCanvas = nullptr protected inherited
Definition at line 40 of file LKDetectorPlane.h.
Referenced by ClickedControlEvent2(), LKPadPlane::DrawHist(), LKDetectorPlane::DrawHist(), LKDetectorPlane::GetCanvas(), GetCanvas(), TTMicromegas::GetCanvas(), ATTPC20RectanglePad::GetCanvas(), ATTPCHoneyCombPad::GetCanvas(), ATTPCRectanglePad::GetCanvas(), ATTPCStripPad::GetCanvas(), TTFrontPlane::GetCanvas(), LHPadPlaneFan::GetCanvas(), LHPadPlaneRCut::GetCanvas(), LHPadPlaneYCut::GetCanvas(), TTMicromegas::GetCPad(), TTMicromegas::SelectAndDrawChannel(), and TTFrontPlane::SelectAndDrawChannel().
fChannelAnalyzer
LKChannelAnalyzer* LKDetectorPlane::fChannelAnalyzer = nullptr protected inherited
Definition at line 29 of file LKDetectorPlane.h.
Referenced by LTPadPlane::GetChannelAnalyzer(), LKDetectorPlane::GetChannelAnalyzer(), GetChannelAnalyzer(), LTPadPlane::Init(), and UpdateChannelBuffer().
fChannelArray
TObjArray* LKDetectorPlane::fChannelArray = nullptr protected inherited
Definition at line 39 of file LKDetectorPlane.h.
Referenced by LKDetectorPlane::AddChannel(), LHPadPlaneFan::AddPad(), LKDetectorPlane::AddPad(), LKDetectorPlane::Clear(), LKPadPlane::Clear(), ClickedControlEvent2(), LTPadPlane::ClickedEventDisplay1(), ClickedEventDisplay1(), ClickedEventDisplay2(), DriftElectronBack(), LKPadPlane::FillBufferIn(), LKDetectorPlane::FillDataToHist(), LKPadPlane::FillDataToHist(), LTPadPlane::FillDataToHist(), FillDataToHistEventDisplay1(), ATMicromegas::FillDataToHistEventDisplay2(), LKDetectorPlane::FillPlane(), ATMicromegas::FindPad(), FindPad(), LKDetectorPlane::GetChannel(), LKDetectorPlane::GetChannelArray(), LKDetectorPlane::GetChannelFast(), ATTPC20RectanglePad::GetHist(), ATTPCHoneyCombPad::GetHist(), ATTPCRectanglePad::GetHist(), ATTPCStripPad::GetHist(), LHPadPlaneFan::GetHist(), LHPadPlaneRCut::GetHist(), LHPadPlaneYCut::GetHist(), LTPadPlane::GetHistEventDisplay2(), LKDetectorPlane::GetNChannels(), LKDetectorPlane::GetPad(), LKPadPlane::GetPad(), LKDetectorPlane::GetPadArray(), LKPadPlane::GetPadArray(), LKDetectorPlane::GetPadFast(), LKPadPlane::GetPadFast(), ATMicromegas::Init(), LTPadPlane::Init(), LHPadPlaneFan::Init(), LHPadPlaneRCut::Init(), LHPadPlaneYCut::Init(), ATTPC20RectanglePad::Init(), ATTPCHoneyCombPad::Init(), ATTPCRectanglePad::Init(), ATTPCStripPad::Init(), LHPadPlaneRCut::NewPad(), LHPadPlaneYCut::NewPad(), LKDetectorPlane::PadMapChecker(), LKDetectorPlane::PadNeighborChecker(), LKPadPlane::PadNeighborChecker(), LKDetectorPlane::PadPositionChecker(), LKPadPlane::PadPositionChecker(), LKDetectorPlane::Print(), LKPadPlane::Print(), LKDetectorPlane::PullOutNeighborHits(), LKDetectorPlane::PullOutNeighborHits(), LKPadPlane::PullOutNeighborHits(), LKPadPlane::PullOutNeighborHits(), LKDetectorPlane::PullOutNeighborHits(), LKPadPlane::PullOutNeighborHits(), LKDetectorPlane::PullOutNeighborHits(), LKPadPlane::PullOutNeighborHits(), LHPadPlaneFan::PullOutNeighborHitsIn(), LKDetectorPlane::PullOutNextFreeHit(), LKPadPlane::PullOutNextFreeHit(), LHPadPlaneFan::PullOutNextFreeHitIn(), LKDetectorPlane::ResetEvent(), LKPadPlane::ResetEvent(), LKDetectorPlane::ResetHitMap(), LKPadPlane::ResetHitMap(), SetDataFromBranch(), ATMicromegas::UpdateChannelBuffer(), and UpdateChannelBuffer().
fChannelGraphArray
TClonesArray* LKEvePlane::fChannelGraphArray = nullptr protected
array of accumulate channel graphs
Definition at line 174 of file LKEvePlane.h.
Referenced by ATMicromegas::Init(), Init(), ATMicromegas::UpdateChannelBuffer(), and UpdateChannelBuffer().
fCountChangeEvent
Long64_t LKEvePlane::fCountChangeEvent = 0 protected
Definition at line 155 of file LKEvePlane.h.
Referenced by ClickedControlEvent2(), and ExecMouseClickEventOnPad().
fCountChangeOther
int LKEvePlane::fCountChangeOther = 0 protected
Definition at line 156 of file LKEvePlane.h.
Referenced by ClickedControlEvent2(), and ExecMouseClickEventOnPad().
fCountChannelGraph
int LKEvePlane::fCountChannelGraph = 0 protected
count number of accumulate channels
Definition at line 175 of file LKEvePlane.h.
Referenced by ClickedControlEvent2(), ATMicromegas::ClickedEventDisplay2(), ATMicromegas::UpdateChannelBuffer(), and UpdateChannelBuffer().
fCountSaveFig
int LKEvePlane::fCountSaveFig = 0 protected
Definition at line 157 of file LKEvePlane.h.
fCountSavePng
int LKEvePlane::fCountSavePng = 0 protected
Definition at line 151 of file LKEvePlane.h.
Referenced by ClickedControlEvent2().
fCountSaveRoo
int LKEvePlane::fCountSaveRoo = 0 protected
Definition at line 152 of file LKEvePlane.h.
Referenced by ClickedControlEvent2().
fCurrentMenu
int LKEvePlane::fCurrentMenu = 0 protected
Definition at line 149 of file LKEvePlane.h.
Referenced by ClickedControlEvent2(), and UpdateMenu().
fCvsChannelBuffer
TCanvas* LKDetectorPlane::fCvsChannelBuffer = nullptr protected inherited
Definition at line 42 of file LKDetectorPlane.h.
fDetector
LKDetector* LKDetectorPlane::fDetector = nullptr protected inherited
Definition at line 28 of file LKDetectorPlane.h.
Referenced by TTMicromegas::SelectAndDrawChannel(), TTFrontPlane::SelectAndDrawChannel(), and LKDetectorPlane::SetDetector().
fDXCanvas
double LKEvePlane::fDXCanvas = 1200 protected
Definition at line 177 of file LKEvePlane.h.
Referenced by GetCanvas().
fDYCanvas
double LKEvePlane::fDYCanvas = 700 protected
Definition at line 178 of file LKEvePlane.h.
Referenced by GetCanvas().
fEnergyMax
int LKEvePlane::fEnergyMax = 1 protected
0 : auto, 1; 4200, >2: fEnergyMax = maximum value
Definition at line 165 of file LKEvePlane.h.
Referenced by ClickedControlEvent2(), LTPadPlane::FillDataToHist(), FillDataToHistEventDisplay1(), UpdateChannelBuffer(), LTPadPlane::UpdateEventDisplay1(), UpdateEventDisplay1(), ATMicromegas::UpdateEventDisplay2(), LTPadPlane::UpdateEventDisplay2(), UpdateEventDisplay2(), UpdateFill(), and UpdateMenu().
fEnergyMin
int LKEvePlane::fEnergyMin = -1 protected
0 : auto, 1; -1
Definition at line 166 of file LKEvePlane.h.
Referenced by ClickedControlEvent2(), ATMicromegas::GetHistEventDisplay2(), LTPadPlane::UpdateEventDisplay1(), UpdateEventDisplay1(), ATMicromegas::UpdateEventDisplay2(), LTPadPlane::UpdateEventDisplay2(), UpdateEventDisplay2(), UpdateFill(), and UpdateMenu().
fEventDisplayDrawOption
TString LKEvePlane::fEventDisplayDrawOption = "colz" protected
Definition at line 181 of file LKEvePlane.h.
Referenced by Draw(), LTPadPlane::UpdateEventDisplay1(), UpdateEventDisplay1(), ATMicromegas::UpdateEventDisplay2(), LTPadPlane::UpdateEventDisplay2(), and UpdateEventDisplay2().
fFillOptionSelected
TString LKEvePlane::fFillOptionSelected = "preview" protected
Definition at line 128 of file LKEvePlane.h.
Referenced by ClickedControlEvent2(), LTPadPlane::FillDataToHist(), FillDataToHistEventDisplay1(), and UpdateFill().
fFitChannel
bool LKEvePlane::fFitChannel = false protected
for finding energy using fChannelAnalyzer
Definition at line 167 of file LKEvePlane.h.
Referenced by ClickedControlEvent2(), UpdateChannelBuffer(), and UpdateMenu().
fFreePadIdx
int LKDetectorPlane::fFreePadIdx = 0 protected inherited
Definition at line 45 of file LKDetectorPlane.h.
Referenced by LKDetectorPlane::PullOutNextFreeHit(), LKDetectorPlane::ResetEvent(), and LKDetectorPlane::ResetHitMap().
fGraphChannelBoundary
TGraph* LKDetectorPlane::fGraphChannelBoundary = nullptr protected inherited
Definition at line 43 of file LKDetectorPlane.h.
fGraphChannelBoundaryNb
TGraph* LKDetectorPlane::fGraphChannelBoundaryNb[20] = {0} protected inherited
Definition at line 44 of file LKDetectorPlane.h.
fGSelEventDisplay1
TGraph* LKEvePlane::fGSelEventDisplay1 = nullptr protected
Definition at line 106 of file LKEvePlane.h.
Referenced by LKEvePlane(), and UpdateChannelBuffer().
fGSelEventDisplay2
TGraph* LKEvePlane::fGSelEventDisplay2 = nullptr protected
Definition at line 107 of file LKEvePlane.h.
Referenced by LKEvePlane(), ATMicromegas::UpdateChannelBuffer(), and LTPadPlane::UpdateEventDisplay1().
fH2Plane
TH2* LKDetectorPlane::fH2Plane = nullptr protected inherited
Definition at line 41 of file LKDetectorPlane.h.
Referenced by LKDetectorPlane::FillDataToHist(), LKPadPlane::FillDataToHist(), ATTPC20RectanglePad::GetHist(), ATTPCHoneyCombPad::GetHist(), ATTPCRectanglePad::GetHist(), ATTPCStripPad::GetHist(), LHPadPlaneFan::GetHist(), LHPadPlaneRCut::GetHist(), and LHPadPlaneYCut::GetHist().
fHistChannelBuffer
TH1D* LKEvePlane::fHistChannelBuffer = nullptr protected
Definition at line 102 of file LKEvePlane.h.
Referenced by ATMicromegas::GetHistChannelBuffer(), GetHistChannelBuffer(), ATMicromegas::UpdateChannelBuffer(), and UpdateChannelBuffer().
fHistControlEvent1
TH2D* LKEvePlane::fHistControlEvent1 = nullptr protected
Definition at line 103 of file LKEvePlane.h.
Referenced by ClickedControlEvent1(), GetHistControlEvent1(), SetPalette(), and UpdateControlEvent1().
fHistControlEvent2
TH2D* LKEvePlane::fHistControlEvent2 = nullptr protected
Definition at line 104 of file LKEvePlane.h.
Referenced by ClickedControlEvent1(), ClickedControlEvent2(), ClickedControlEvent2(), ATMicromegas::ClickedEventDisplay2(), GetHistControlEvent2(), SetPalette(), UpdateControlEvent2(), UpdateFill(), and UpdateMenu().
fHistEventDisplay1
TH2* LKEvePlane::fHistEventDisplay1 = nullptr protected
Definition at line 100 of file LKEvePlane.h.
Referenced by LTPadPlane::ClickedEventDisplay1(), ClickedEventDisplay1(), LTPadPlane::ClickedEventDisplay2(), FillDataToHistEventDisplay1(), GetHist(), ATMicromegas::GetHistEventDisplay1(), GetHistEventDisplay1(), LTPadPlane::GetHistEventDisplay2(), LTPadPlane::UpdateEventDisplay1(), and UpdateEventDisplay1().
fHistEventDisplay2
TH2* LKEvePlane::fHistEventDisplay2 = nullptr protected
Definition at line 101 of file LKEvePlane.h.
Referenced by ATMicromegas::ClickedEventDisplay2(), ClickedEventDisplay2(), ATMicromegas::FillDataToHistEventDisplay2(), ATMicromegas::FindZFromHistEventDisplay2Bin(), ATMicromegas::GetHistEventDisplay2(), LTPadPlane::GetHistEventDisplay2(), GetHistEventDisplay2(), ATMicromegas::UpdateEventDisplay2(), LTPadPlane::UpdateEventDisplay2(), and UpdateEventDisplay2().
fHitArray
TClonesArray* LKEvePlane::fHitArray = nullptr protected
Definition at line 92 of file LKEvePlane.h.
Referenced by LTPadPlane::FillDataToHist(), FillDataToHistEventDisplay1(), ATMicromegas::FillDataToHistEventDisplay2(), LTPadPlane::Init(), and Init().
fHitDataIsSet
bool LKDetectorPlane::fHitDataIsSet = false protected inherited
Definition at line 48 of file LKDetectorPlane.h.
Referenced by LKDetectorPlane::FillDataToHist(), and LKDetectorPlane::SetHitArray().
fNumAccumulateChannels
int LKEvePlane::fNumAccumulateChannels = 0 protected
to accumulate channel waveform
Definition at line 172 of file LKEvePlane.h.
fPadAxis1
axis_t LKEvePlane::fPadAxis1[2] = {LKVector3::kNon, LKVector3::kNon} protected
Definition at line 185 of file LKEvePlane.h.
Referenced by LTPadPlane::ClickedEventDisplay2(), and GetAxis1().
fPadAxis2
axis_t LKEvePlane::fPadAxis2[2] = {LKVector3::kNon, LKVector3::kNon} protected
Definition at line 186 of file LKEvePlane.h.
Referenced by LTPadPlane::ClickedEventDisplay2(), and GetAxis2().
fPadChannelBuffer
TPad* LKEvePlane::fPadChannelBuffer = nullptr protected
Definition at line 96 of file LKEvePlane.h.
Referenced by GetCanvas(), GetPadChannelBuffer(), ATMicromegas::UpdateChannelBuffer(), and UpdateChannelBuffer().
fPadControlEvent1
TPad* LKEvePlane::fPadControlEvent1 = nullptr protected
Definition at line 97 of file LKEvePlane.h.
Referenced by ExecMouseClickEventOnPad(), GetCanvas(), GetPadControlEvent1(), and UpdateControlEvent1().
fPadControlEvent2
TPad* LKEvePlane::fPadControlEvent2 = nullptr protected
Definition at line 98 of file LKEvePlane.h.
Referenced by ExecMouseClickEventOnPad(), GetCanvas(), GetPadControlEvent2(), and UpdateControlEvent2().
fPadDataIsSet
bool LKDetectorPlane::fPadDataIsSet = false protected inherited
Definition at line 47 of file LKDetectorPlane.h.
Referenced by LKDetectorPlane::FillDataToHist(), and LKDetectorPlane::SetPadArray().
fPadEventDisplay1
TPad* LKEvePlane::fPadEventDisplay1 = nullptr protected
Definition at line 94 of file LKEvePlane.h.
Referenced by DrawHist(), ExecMouseClickEventOnPad(), GetCanvas(), GetPadEventDisplay1(), UpdateChannelBuffer(), ATMicromegas::UpdateEventDisplay1(), LTPadPlane::UpdateEventDisplay1(), and UpdateEventDisplay1().
fPadEventDisplay2
TPad* LKEvePlane::fPadEventDisplay2 = nullptr protected
Definition at line 95 of file LKEvePlane.h.
Referenced by ExecMouseClickEventOnPad(), GetCanvas(), GetPadEventDisplay2(), ATMicromegas::UpdateChannelBuffer(), LTPadPlane::UpdateEventDisplay1(), ATMicromegas::UpdateEventDisplay2(), LTPadPlane::UpdateEventDisplay2(), and UpdateEventDisplay2().
fPadInteractiveID
int LKPadInteractive::fPadInteractiveID = -1 protected inherited
Definition at line 21 of file LKPadInteractive.h.
Referenced by LKHTLineTracker::Draw(), LKPadInteractive::GetPadInteractiveID(), and LKPadInteractive::SetPadInteractiveID().
fPaletteIsInverted
bool LKEvePlane::fPaletteIsInverted = false protected
Definition at line 163 of file LKEvePlane.h.
Referenced by SetPalette().
fPaletteNumber
int LKEvePlane::fPaletteNumber = 0 protected
Definition at line 162 of file LKEvePlane.h.
Referenced by ClickedControlEvent2(), GetHistControlEvent1(), GetHistControlEvent2(), SetPalette(), ATMicromegas::UpdateChannelBuffer(), UpdateChannelBuffer(), and UpdateMenu().
fPar
LKParameterContainer* LKGear::fPar = nullptr protected inherited
Definition at line 39 of file LKGear.h.
Referenced by LKTask::Add(), LKRun::AddDetector(), LKGear::AddParameterContainer(), LKGear::AddParameterContainer(), LKDetector::AddPlane(), LHTpc::BuildDetectorPlane(), ATTPC::BuildDetectorPlane(), LHTpc::BuildGeometry(), ATTPC::BuildGeometry(), ClassImp(), ClassImp(), ClassImp(), ClassImp(), LKEveTask::DrawEve3D(), LKPadPlane::DrawHist(), LKG4RunManager::EndOfRun(), LKPulseExtractionTask::EndOfRun(), LKDetectorPlane::FillDataToHist(), LKPadPlane::FillDataToHist(), LTPadPlane::GetChannelAnalyzer(), LKDetector::GetChannelAnalyzer(), LKDetectorPlane::GetChannelAnalyzer(), GetChannelAnalyzer(), LKGear::GetPar(), LKGear::GetParameterContainer(), ATMicromegas::Init(), AToMX::Init(), LTPadPlane::Init(), LKRun::Init(), LKDetector::Init(), Init(), LKMFMConversionTask::Init(), LKDriftElectronTask::Init(), LKEveTask::Init(), LKGETChannelViewer::Init(), LKNoiseSubtractionTask::Init(), LKPulseExtractionTask::Init(), LHPSATask::Init(), TexAT2::Init(), TTMicromegas::Init(), TTHTBeamTrackingTask::Init(), TTHTTrackingTask::Init(), TTPulseExtractionTask::Init(), LHPadPlaneFan::Init(), LHPadPlaneRCut::Init(), LHPadPlaneYCut::Init(), ATTPC::Init(), ATTPC20RectanglePad::Init(), ATTPCHoneyCombPad::Init(), ATTPCRectanglePad::Init(), ATTPCStripPad::Init(), TTFrontPlane::Init(), LKRun::InitAndCollectParameters(), TexAT2::InitChannelAnalyzer(), LKG4RunManager::Initialize(), LKRun::Print(), LKRun::RegisterBranchA(), LKG4RunManager::Run(), LKDetectorPlane::SetDataFromBranch(), LKPadPlane::SetDataFromBranch(), LKDetectorSystem::SetDetectorPar(), LKEveTask::SetEveLineAtt(), LKEveTask::SetEveMarkerAtt(), LKRun::SetEventTrigger(), LKEveTask::SetGraphAtt(), LKEveTask::SetGraphAtt(), LKG4RunManager::SetOutputFile(), LKGear::SetParameterContainer(), TTMicromegas::WriteCurrentChannel(), and LKRun::WriteOutputFile().
fPlaneID
int LKDetectorPlane::fPlaneID = -1 protected inherited
Detector plane id.
Definition at line 31 of file LKDetectorPlane.h.
Referenced by LKDetectorPlane::GetCanvas(), ATTPC20RectanglePad::GetCanvas(), ATTPCHoneyCombPad::GetCanvas(), ATTPCRectanglePad::GetCanvas(), ATTPCStripPad::GetCanvas(), LHPadPlaneFan::GetCanvas(), LHPadPlaneRCut::GetCanvas(), LHPadPlaneYCut::GetCanvas(), LKDetectorPlane::GetPlaneID(), ATTPC20RectanglePad::Init(), ATTPCHoneyCombPad::Init(), ATTPCRectanglePad::Init(), ATTPCStripPad::Init(), LKDetectorPlane::SetPadArray(), LKPadPlane::SetPadArray(), and LKDetectorPlane::SetPlaneID().
fPosition
double LKDetectorPlane::fPosition protected inherited
Global position of pad plane center.
Definition at line 37 of file LKDetectorPlane.h.
Referenced by LKDetectorPlane::DriftElectron(), LKDetectorPlane::DriftElectronBack(), DriftElectronBack(), LKDetectorPlane::DriftElectronBack(), LKDetectorPlane::GetPosition(), ATMicromegas::Init(), LTPadPlane::Init(), and Init().
fRank
Int_t LKGear::fRank = 0 protected inherited
Definition at line 41 of file LKGear.h.
Referenced by LKTask::Add(), LKDetector::AddPlane(), LKGear::GetRank(), LKDetectorSystem::SetDetector(), LKRun::SetEventTrigger(), LKGear::SetRank(), and LKTask::SetRank().
fRawDataArray
TClonesArray* LKEvePlane::fRawDataArray = nullptr protected
Definition at line 90 of file LKEvePlane.h.
Referenced by ClickedControlEvent1(), ClickedControlEvent2(), LTPadPlane::FillDataToHist(), FillDataToHistEventDisplay1(), ATMicromegas::FillDataToHistEventDisplay2(), LTPadPlane::Init(), Init(), SetDataFromBranch(), ATMicromegas::UpdateChannelBuffer(), and UpdateChannelBuffer().
fReturnDraw
bool LKEvePlane::fReturnDraw = false protected
Definition at line 183 of file LKEvePlane.h.
Referenced by Draw().
fRun
LKRun* LKGear::fRun = nullptr protected inherited
Definition at line 40 of file LKGear.h.
Referenced by LKDetector::AddPlane(), ClassImp(), ClassImp(), ClassImp(), ClickedControlEvent1(), ClickedControlEvent1(), ClickedControlEvent2(), LKEveTask::DrawDetectorPlanes(), LKEveTask::DrawEve3D(), LKPulseExtractionTask::EndOfRun(), TTPulseExtractionTask::EndOfRun(), LKGETChannelViewer::Exec(), LKPulseExtractionTask::Exec(), TTHitFindingHoughTask::Exec(), TTPulseExtractionTask::Exec(), TTMicromegas::FillDataToHist(), LTPadPlane::FillDataToHist(), FillDataToHistEventDisplay1(), GetHistControlEvent1(), LTPadPlane::Init(), LTEventPreviewTask::Init(), TTPulseAnalysisTask::Init(), Init(), LKMFMConversionTask::Init(), LKDriftElectronTask::Init(), LKEveTask::Init(), LKGETChannelViewer::Init(), LKNoiseSubtractionTask::Init(), LKPulseExtractionTask::Init(), LKPulseShapeAnalysisTask::Init(), TTBeamSelectionTask::Init(), TTDrawBeamEnergyTask::Init(), TTDrawRawWaveformTask::Init(), TTEventSelectionTask::Init(), TTFindBeamTimingTask::Init(), TTGetPedestalTask::Init(), TTPID_FSivsFCsI::Init(), TTPID_MMvsFSi::Init(), TTPID_MMvsX6::Init(), TTPID_X6vsCsI::Init(), TTReadEventListTask::Init(), TTHTtBeamTrackingTask::Init(), TTEventNumberSelectionTask::Init(), TTEventPreviewTask::Init(), TTHitFindingHoughTask::Init(), TTHTBeamTrackingTask::Init(), TTHTTrackingTask::Init(), TTPulseExtractionTask::Init(), httask::Init(), LKMFMConversionTask::Run(), LKGETChannelViewer::SelectMenu(), LKDetectorPlane::SetDataFromBranch(), LKPadPlane::SetDataFromBranch(), TTMicromegas::SetDataFromBranch(), TTFrontPlane::SetDataFromBranch(), LKDetectorSystem::SetDetector(), SetPalette(), LKGear::SetRun(), LKDetector::SetRun(), LKMFMConversionTask::SignalNextEvent(), UpdateControlEvent1(), and UpdateControlEvent2().
fSavePath
TString LKEvePlane::fSavePath = "eve_data" protected
Definition at line 154 of file LKEvePlane.h.
Referenced by ClickedControlEvent2(), and Init().
fSelPadID
int LKEvePlane::fSelPadID = 0 protected
Selected pad id by mouse click.
Definition at line 159 of file LKEvePlane.h.
Referenced by ClickedControlEvent2(), LTPadPlane::ClickedEventDisplay1(), ClickedEventDisplay1(), ClickedEventDisplay2(), SetDataFromBranch(), and UpdateChannelBuffer().
fSelRawDataID
int LKEvePlane::fSelRawDataID = 0 protected
Selected raw data by mouse click.
Definition at line 160 of file LKEvePlane.h.
Referenced by ClickedControlEvent2(), SetDataFromBranch(), and UpdateChannelBuffer().
fTbToLength
double LKDetectorPlane::fTbToLength = 1 protected inherited
time-bin (tb) to position conversion factor. Must be set by input parameter.
Definition at line 36 of file LKDetectorPlane.h.
Referenced by LKDetectorPlane::DriftElectronBack(), DriftElectronBack(), LKDetectorPlane::DriftElectronBack(), LKDetectorPlane::GetTbToLength(), ATMicromegas::Init(), LTPadPlane::Init(), and Init().
fTrackArray
TClonesArray* LKEvePlane::fTrackArray = nullptr protected
Definition at line 91 of file LKEvePlane.h.
Referenced by LTPadPlane::Init(), and Init().
fYCCanvas
double LKEvePlane::fYCCanvas = 230./700 protected
Definition at line 179 of file LKEvePlane.h.
Referenced by GetCanvas().
kFillAget
const TString LKEvePlane::kFillAget = "aget" protected
Definition at line 132 of file LKEvePlane.h.
Referenced by ClickedControlEvent2(), and UpdateFill().
kFillAsad
const TString LKEvePlane::kFillAsad = "asad" protected
Definition at line 131 of file LKEvePlane.h.
Referenced by ClickedControlEvent2(), and UpdateFill().
kFillCAAC
const TString LKEvePlane::kFillCAAC = "caac" protected
Definition at line 134 of file LKEvePlane.h.
Referenced by ClickedControlEvent2(), and UpdateFill().
kFillChan
const TString LKEvePlane::kFillChan = "chan" protected
Definition at line 133 of file LKEvePlane.h.
Referenced by ClickedControlEvent2(), and UpdateFill().
kFillCobo
const TString LKEvePlane::kFillCobo = "cobo" protected
Definition at line 130 of file LKEvePlane.h.
Referenced by ClickedControlEvent2(), and UpdateFill().
kFillHits
const TString LKEvePlane::kFillHits = "hit" protected
Definition at line 137 of file LKEvePlane.h.
Referenced by ClickedControlEvent2(), and UpdateFill().
kFillNHit
const TString LKEvePlane::kFillNHit = "nhits" protected
Definition at line 138 of file LKEvePlane.h.
Referenced by ClickedControlEvent2(), and UpdateFill().
kFillPrev
const TString LKEvePlane::kFillPrev = "preview" protected
Definition at line 136 of file LKEvePlane.h.
Referenced by ClickedControlEvent2(), and UpdateFill().
kFillRawD
const TString LKEvePlane::kFillRawD = "raw" protected
Definition at line 135 of file LKEvePlane.h.
Referenced by ClickedControlEvent2(), and UpdateFill().
kFillZero
const TString LKEvePlane::kFillZero = "" protected
Definition at line 129 of file LKEvePlane.h.
Referenced by ClickedControlEvent2().
The documentation for this class was generated from the following files:
LKEvePlane.h
LKEvePlane.cpp