lilak: LKGeoCircle Class Reference
LKGeoCircle Class Reference
#include <LKGeoCircle.h>
Public Member Functions
TVector3 ClosestPointToCircle (Double_t x, Double_t y)
TGraph * DrawCircle (Int_t n=100, Double_t theta1=0, Double_t theta2=0)
virtual TVector3 GetCenter () const
Double_t GetR () const
Double_t GetRadius () const
TVector3 GetRandomPoint ()
Double_t GetX () const
Double_t GetY () const
Double_t GetZ () const
LKGeoCircle ()
LKGeoCircle (Double_t x, Double_t y, Double_t r)
Double_t Phi (Double_t x, Double_t y)
TVector3 PointAtPhi (Double_t phi)
virtual void Print (Option_t *option="") const
void SetCircle (Double_t x, Double_t y, Double_t r)
virtual ~LKGeoCircle ()
Public Member Functions inherited from LKGeometry
Double_t GetRMS () const
LKGeometry ()
void SetRMS (Double_t val)
virtual ~LKGeometry ()
Protected Attributes
Double_t fR = 0
Double_t fX = 0
Double_t fY = 0
Double_t fZ = 0
Protected Attributes inherited from LKGeometry
Double_t fRMS = -1
Detailed Description
Definition at line 10 of file LKGeoCircle.h.
Constructor & Destructor Documentation
LKGeoCircle() [1/2]
LKGeoCircle::LKGeoCircle ()
LKGeoCircle() [2/2]
LKGeoCircle::LKGeoCircle (Double_t x, Double_t y, Double_t r)
Definition at line 14 of file LKGeoCircle.cpp.
References SetCircle(), x, and y.
~LKGeoCircle()
virtual LKGeoCircle::~LKGeoCircle () inline virtual
Definition at line 15 of file LKGeoCircle.h.
Member Function Documentation
ClosestPointToCircle()
TVector3 LKGeoCircle::ClosestPointToCircle (Double_t x, Double_t y)
Definition at line 63 of file LKGeoCircle.cpp.
References Phi(), x, and y.
DrawCircle()
TGraph * LKGeoCircle::DrawCircle (Int_t n = 100, Double_t theta1 = 0, Double_t theta2 = 0)
Definition at line 45 of file LKGeoCircle.cpp.
References fR, fX, fY, and SetPoint().
Referenced by LKGeoSphere::DrawCircleXY(), LKGeoSphere::DrawCircleYZ(), LKGeoSphere::DrawCircleZX(), drawDefinition(), and LKHitArray::DrawFitCircle().
GetCenter()
TVector3 LKGeoCircle::GetCenter () const virtual
Definition at line 37 of file LKGeoCircle.cpp.
References fX, and fY.
GetR()
Double_t LKGeoCircle::GetR () const
Definition at line 42 of file LKGeoCircle.cpp.
References fR.
GetRadius()
Double_t LKGeoCircle::GetRadius () const
Definition at line 43 of file LKGeoCircle.cpp.
References fR.
GetRandomPoint()
TVector3 LKGeoCircle::GetRandomPoint ()
Definition at line 26 of file LKGeoCircle.cpp.
References fR, fX, fY, and fZ.
GetX()
Double_t LKGeoCircle::GetX () const
Definition at line 39 of file LKGeoCircle.cpp.
References fX.
GetY()
Double_t LKGeoCircle::GetY () const
Definition at line 40 of file LKGeoCircle.cpp.
References fY.
GetZ()
Double_t LKGeoCircle::GetZ () const
Definition at line 41 of file LKGeoCircle.cpp.
References fZ.
Phi()
Double_t LKGeoCircle::Phi (Double_t x, Double_t y)
Definition at line 74 of file LKGeoCircle.cpp.
References fX, fY, x, and y.
Referenced by ClosestPointToCircle().
PointAtPhi()
TVector3 LKGeoCircle::PointAtPhi (Double_t phi)
Definition at line 69 of file LKGeoCircle.cpp.
References fZ.
Print()
void LKGeoCircle::Print (Option_t * option = "") const virtual
Definition at line 32 of file LKGeoCircle.cpp.
References e_info, fR, fX, and fY.
SetCircle()
void LKGeoCircle::SetCircle (Double_t x, Double_t y, Double_t r)
Definition at line 19 of file LKGeoCircle.cpp.
References fR, fX, fY, x, and y.
Referenced by LKHitArray::DrawFitCircle(), LKHitArray::FitCircle(), and LKGeoCircle().
Member Data Documentation
fR
Double_t LKGeoCircle::fR = 0 protected
Definition at line 42 of file LKGeoCircle.h.
Referenced by DrawCircle(), GetR(), GetRadius(), GetRandomPoint(), Print(), and SetCircle().
fX
Double_t LKGeoCircle::fX = 0 protected
Definition at line 39 of file LKGeoCircle.h.
Referenced by DrawCircle(), GetCenter(), GetRandomPoint(), GetX(), Phi(), Print(), and SetCircle().
fY
Double_t LKGeoCircle::fY = 0 protected
Definition at line 40 of file LKGeoCircle.h.
Referenced by DrawCircle(), GetCenter(), GetRandomPoint(), GetY(), Phi(), Print(), and SetCircle().
fZ
Double_t LKGeoCircle::fZ = 0 protected
Definition at line 41 of file LKGeoCircle.h.
Referenced by GetRandomPoint(), GetZ(), and PointAtPhi().
The documentation for this class was generated from the following files:
LKGeoCircle.h
LKGeoCircle.cpp