lilak: LTHelixTrackFindingTask Class Reference
LTHelixTrackFindingTask Class Reference
#include <LTHelixTrackFindingTask.h>
Public Types
enum StepNo : int {
kStepInitArray , kStepNewTrack , kStepRemoveTrack , kStepInitTrack ,
kStepInitTrackAddHit , kStepContinuum , kStepContinuumAddHit , kStepExtrapolation ,
kStepExtrapolationAddHit , kStepConfirmation , kStepFinalizeTrack , kStepNextPhase ,
kStepEndEvent , kStepEndOfEvent
}
Public Member Functions
virtual void Exec (Option_t *)
bool ExecStep ()
bool ExecStepUptoTrackNum (Int_t numTracks)
LKHelixTrack * GetCurrentTrack () const
virtual bool Init ()
LTHelixTrackFindingTask ()
void SetHitBranchName (TString name)
void SetTrackletBranchName (TString name)
void SetTrackPersistency (bool val)
virtual ~LTHelixTrackFindingTask ()
Public Member Functions inherited from LKTask
virtual void Add (TTask *task)
virtual bool EndOfRun ()
bool EndOfRunTask ()
bool EndOfRunTasks ()
virtual bool Init ()
bool InitTask ()
bool InitTasks ()
virtual bool IsEventTrigger ()
LKTask ()
LKTask (const char *name, const char *title)
virtual void Run (Long64_t numEvents=-1)
virtual void RunOnline ()
virtual void SetRank (Int_t rank)
virtual void SignalNextEvent ()
virtual ~LKTask ()
Public Member Functions inherited from LKGear
void AddPar (LKParameterContainer *par)
void AddPar (TString fname)
virtual void AddParameterContainer (LKParameterContainer *par)
virtual void AddParameterContainer (TString fname)
void CreateParameterContainer ()
LKParameterContainer * GetPar () const
LKParameterContainer * GetParameterContainer () const
Int_t GetRank () const
LKGear ()
void SetPar (LKParameterContainer *par)
virtual void SetParameterContainer (LKParameterContainer *par)
virtual void SetRank (Int_t rank)
void SetRun (LKRun *run)
virtual ~LKGear ()
Private Member Functions
bool AutoBuildAtPosition (LKHelixTrack *track, TVector3 p, bool &tailToHead, Double_t &extrapolationLength, Double_t scale=1)
bool AutoBuildByExtrapolation (LKHelixTrack *track, bool &buildHead, Double_t &extrapolationLength)
bool BuildAndConfirmTrack (LKHelixTrack *track, bool &tailToHead)
bool CheckHitDistInAlphaIsLargerThanQuarterPi (LKHelixTrack *track, Double_t dLength)
int CheckParentTrackID (LKHit *hit)
double CheckTrackContinuity (LKHelixTrack *track)
bool CheckTrackQuality (LKHelixTrack *track)
double CorrelateHitWithTrack (LKHelixTrack *track, LKHit *hit, Double_t scale=1)
double CorrelateHitWithTrackCandidate (LKHelixTrack *track, LKHit *hit)
void ReturnBadHitsToPadPlane ()
int StepConfirmation ()
int StepContinuum ()
int StepContinuumAddHit ()
int StepEndEvent ()
int StepExtrapolation ()
int StepExtrapolationAddHit ()
int StepFinalizeTrack ()
int StepInitArray ()
int StepInitTrack ()
int StepInitTrackAddHit ()
int StepNewTrack ()
int StepNextPhase ()
int StepRemoveTrack ()
Private Attributes
LKHitArray * fBadHits = nullptr
TString fBranchNameHit = "Hit"
TString fBranchNameTracklet = "Tracklet"
LKHitArray * fCandHits = nullptr
LKHelixTrack * fCurrentTrack = nullptr
Double_t fCutdkInExpectedTrackPath = 4.
Int_t fCutMaxNumHitsInitTrack = 15
return hits if track has more than this number of hits within initialization stage
Double_t fCutMinHelixRadius = 30.
helix radius cut for initialization stage
Int_t fCutMinNumHitsFinalTrack = 15
remove track if track has smaller than this number of hits within initialization stage
Int_t fCutMinNumHitsInitTrack = 10
TCanvas * fCvsCurrentTrack = nullptr
Double_t fDefaultScale = 2.5
LKHitArray * fGoodHits = nullptr
TGraphErrors * fGraphCurrentTrackPoint = nullptr
TClonesArray * fHitArray = nullptr
Int_t fMinHitsToFitInitTrack = 7
try track fit if track has more than this number of hits in track
Int_t fNextStep = StepNo::kStepInitArray
Int_t fNumBadHits
Int_t fNumCandHits
Int_t fNumGoodHits
LKDetectorPlane * fPadPlane = nullptr
bool fPersistency = true
Int_t fPhaseIndex = 0
LKVector3::Axis fReferenceAxis = LKVector3::kZ
LKDetector * fTpc = nullptr
TClonesArray * fTrackArray = nullptr
Double_t fTrackHCutHL = 15.
Track height cut high limit.
Double_t fTrackHCutLL = 5.
Track height cut low limit.
LKHitArray * fTrackHits = nullptr
Double_t fTrackLengthCutScale = 2.5
track length cut for initialization stage is [this_var] * track -> GetRMSR()
Double_t fTrackWCutHL = 15.
Track width cut high limit.
Double_t fTrackWCutLL = 5.
Track width cut low limit.
Additional Inherited Members
Protected Attributes inherited from LKGear
LKParameterContainer * fPar = nullptr
Int_t fRank = 0
LKRun * fRun = nullptr
Detailed Description
Definition at line 20 of file LTHelixTrackFindingTask.h.
Member Enumeration Documentation
StepNo
enum LTHelixTrackFindingTask::StepNo : int
Enumerator
kStepInitArray
kStepNewTrack
kStepRemoveTrack
kStepInitTrack
kStepInitTrackAddHit
kStepContinuum
kStepContinuumAddHit
kStepExtrapolation
kStepExtrapolationAddHit
kStepConfirmation
kStepFinalizeTrack
kStepNextPhase
kStepEndEvent
kStepEndOfEvent
Definition at line 31 of file LTHelixTrackFindingTask.h.
Constructor & Destructor Documentation
LTHelixTrackFindingTask()
LTHelixTrackFindingTask::LTHelixTrackFindingTask () inline
Definition at line 23 of file LTHelixTrackFindingTask.h.
~LTHelixTrackFindingTask()
virtual LTHelixTrackFindingTask::~LTHelixTrackFindingTask () inline virtual
Definition at line 24 of file LTHelixTrackFindingTask.h.
Member Function Documentation
AutoBuildAtPosition()
bool LTHelixTrackFindingTask::AutoBuildAtPosition (LKHelixTrack * track, TVector3 p, bool & tailToHead, Double_t & extrapolationLength, Double_t scale = 1) private
Definition at line 782 of file LTHelixTrackFindingTask.cpp.
References CheckParentTrackID(), CorrelateHitWithTrack(), fBadHits, fCandHits, fNumCandHits, fPadPlane, fReferenceAxis, and p2.
Referenced by AutoBuildByExtrapolation().
AutoBuildByExtrapolation()
bool LTHelixTrackFindingTask::AutoBuildByExtrapolation (LKHelixTrack * track, bool & buildHead, Double_t & extrapolationLength) private
Definition at line 767 of file LTHelixTrackFindingTask.cpp.
References AutoBuildAtPosition(), and fCutMinNumHitsFinalTrack.
Referenced by BuildAndConfirmTrack(), and StepExtrapolationAddHit().
BuildAndConfirmTrack()
bool LTHelixTrackFindingTask::BuildAndConfirmTrack (LKHelixTrack * track, bool & tailToHead) private
Definition at line 718 of file LTHelixTrackFindingTask.cpp.
References AutoBuildByExtrapolation(), CorrelateHitWithTrack(), fCutMinNumHitsFinalTrack, and lk_debug.
Referenced by StepConfirmation().
CheckHitDistInAlphaIsLargerThanQuarterPi()
bool LTHelixTrackFindingTask::CheckHitDistInAlphaIsLargerThanQuarterPi (LKHelixTrack * track, Double_t dLength) private
Definition at line 918 of file LTHelixTrackFindingTask.cpp.
Referenced by CorrelateHitWithTrack().
CheckParentTrackID()
int LTHelixTrackFindingTask::CheckParentTrackID (LKHit * hit) private
Definition at line 837 of file LTHelixTrackFindingTask.cpp.
Referenced by AutoBuildAtPosition(), and StepContinuumAddHit().
CheckTrackContinuity()
double LTHelixTrackFindingTask::CheckTrackContinuity (LKHelixTrack * track) private
Definition at line 871 of file LTHelixTrackFindingTask.cpp.
References LKVector3::At(), fPadPlane, and fReferenceAxis.
CheckTrackQuality()
bool LTHelixTrackFindingTask::CheckTrackQuality (LKHelixTrack * track) private
Definition at line 855 of file LTHelixTrackFindingTask.cpp.
References fCutMinHelixRadius.
Referenced by StepExtrapolationAddHit().
CorrelateHitWithTrack()
double LTHelixTrackFindingTask::CorrelateHitWithTrack (LKHelixTrack * track, LKHit * hit, Double_t scale = 1) private
Definition at line 658 of file LTHelixTrackFindingTask.cpp.
References CheckHitDistInAlphaIsLargerThanQuarterPi(), fDefaultScale, fTrackHCutHL, fTrackHCutLL, fTrackWCutHL, and fTrackWCutLL.
Referenced by AutoBuildAtPosition(), BuildAndConfirmTrack(), StepContinuumAddHit(), and StepInitTrackAddHit().
CorrelateHitWithTrackCandidate()
double LTHelixTrackFindingTask::CorrelateHitWithTrackCandidate (LKHelixTrack * track, LKHit * hit) private
Definition at line 548 of file LTHelixTrackFindingTask.cpp.
References fCurrentTrack, fCutdkInExpectedTrackPath, fReferenceAxis, fTrackHCutHL, fTrackHCutLL, LKVector3::I(), LKVector3::J(), LKVector3::K(), lk_debug, and LKVector3::SetK().
Referenced by StepInitTrackAddHit().
Exec()
void LTHelixTrackFindingTask::Exec (Option_t *) virtual
Definition at line 37 of file LTHelixTrackFindingTask.cpp.
References ExecStep(), fNextStep, and kStepInitArray.
ExecStep()
bool LTHelixTrackFindingTask::ExecStep ()
Definition at line 46 of file LTHelixTrackFindingTask.cpp.
References DEBUG_STEP, fCurrentTrack, fNextStep, kStepConfirmation, kStepContinuum, kStepContinuumAddHit, kStepEndEvent, kStepEndOfEvent, kStepExtrapolation, kStepExtrapolationAddHit, kStepFinalizeTrack, kStepInitArray, kStepInitTrack, kStepInitTrackAddHit, kStepNewTrack, kStepNextPhase, kStepRemoveTrack, lk_debug, lk_strong, StepConfirmation(), StepContinuum(), StepContinuumAddHit(), StepEndEvent(), StepExtrapolation(), StepExtrapolationAddHit(), StepFinalizeTrack(), StepInitArray(), StepInitTrack(), StepInitTrackAddHit(), StepNewTrack(), StepNextPhase(), and StepRemoveTrack().
Referenced by Exec(), and ExecStepUptoTrackNum().
ExecStepUptoTrackNum()
bool LTHelixTrackFindingTask::ExecStepUptoTrackNum (Int_t numTracks)
Definition at line 88 of file LTHelixTrackFindingTask.cpp.
References ExecStep(), fNextStep, fTrackArray, kStepEndOfEvent, and kStepNewTrack.
GetCurrentTrack()
LKHelixTrack * LTHelixTrackFindingTask::GetCurrentTrack () const inline
Definition at line 52 of file LTHelixTrackFindingTask.h.
References fCurrentTrack.
Init()
virtual bool LTHelixTrackFindingTask::Init () virtual
Reimplemented from LKTask.
ReturnBadHitsToPadPlane()
void LTHelixTrackFindingTask::ReturnBadHitsToPadPlane () private
Definition at line 536 of file LTHelixTrackFindingTask.cpp.
References fBadHits, fNumBadHits, and fPadPlane.
Referenced by StepConfirmation(), StepExtrapolation(), StepExtrapolationAddHit(), StepNewTrack(), StepNextPhase(), and StepRemoveTrack().
SetHitBranchName()
void LTHelixTrackFindingTask::SetHitBranchName (TString name) inline
Definition at line 54 of file LTHelixTrackFindingTask.h.
References fBranchNameHit.
SetTrackletBranchName()
void LTHelixTrackFindingTask::SetTrackletBranchName (TString name) inline
Definition at line 55 of file LTHelixTrackFindingTask.h.
References fBranchNameTracklet.
SetTrackPersistency()
void LTHelixTrackFindingTask::SetTrackPersistency (bool val) inline
Definition at line 29 of file LTHelixTrackFindingTask.h.
References fPersistency.
StepConfirmation()
int LTHelixTrackFindingTask::StepConfirmation () private
Definition at line 428 of file LTHelixTrackFindingTask.cpp.
References BuildAndConfirmTrack(), fCurrentTrack, fReferenceAxis, LKVector3::K(), kStepFinalizeTrack, kStepRemoveTrack, lk_debug, and ReturnBadHitsToPadPlane().
Referenced by ExecStep().
StepContinuum()
int LTHelixTrackFindingTask::StepContinuum () private
Definition at line 322 of file LTHelixTrackFindingTask.cpp.
References fCandHits, fGoodHits, fNumCandHits, fPadPlane, fTrackHits, kStepContinuumAddHit, kStepExtrapolation, and lk_debug.
Referenced by ExecStep().
StepContinuumAddHit()
int LTHelixTrackFindingTask::StepContinuumAddHit () private
Definition at line 340 of file LTHelixTrackFindingTask.cpp.
References CheckParentTrackID(), CorrelateHitWithTrack(), fBadHits, fCandHits, fCurrentTrack, fGoodHits, fNumCandHits, kStepContinuum, and lk_debug.
Referenced by ExecStep().
StepEndEvent()
int LTHelixTrackFindingTask::StepEndEvent () private
Definition at line 516 of file LTHelixTrackFindingTask.cpp.
References fTrackArray, kStepEndOfEvent, and lk_info.
Referenced by ExecStep().
StepExtrapolation()
int LTHelixTrackFindingTask::StepExtrapolation () private
Definition at line 375 of file LTHelixTrackFindingTask.cpp.
References kStepExtrapolationAddHit, lk_debug, and ReturnBadHitsToPadPlane().
Referenced by ExecStep().
StepExtrapolationAddHit()
int LTHelixTrackFindingTask::StepExtrapolationAddHit () private
Definition at line 385 of file LTHelixTrackFindingTask.cpp.
References AutoBuildByExtrapolation(), CheckTrackQuality(), fCurrentTrack, kStepConfirmation, kStepRemoveTrack, lk_debug, and ReturnBadHitsToPadPlane().
Referenced by ExecStep().
StepFinalizeTrack()
int LTHelixTrackFindingTask::StepFinalizeTrack () private
Definition at line 473 of file LTHelixTrackFindingTask.cpp.
References fCurrentTrack, fGoodHits, fPadPlane, fTrackHits, and kStepNewTrack.
Referenced by ExecStep().
StepInitArray()
int LTHelixTrackFindingTask::StepInitArray () private
Definition at line 101 of file LTHelixTrackFindingTask.cpp.
References fBadHits, fCandHits, fCurrentTrack, fGoodHits, fHitArray, fPadPlane, fPhaseIndex, fTrackArray, fTrackHits, kStepNewTrack, and lk_debug.
Referenced by ExecStep().
StepInitTrack()
int LTHelixTrackFindingTask::StepInitTrack () private
Definition at line 206 of file LTHelixTrackFindingTask.cpp.
References fCandHits, fCurrentTrack, fGoodHits, fNumCandHits, fPadPlane, fTrackHits, kStepInitTrackAddHit, kStepRemoveTrack, and lk_debug.
Referenced by ExecStep().
StepInitTrackAddHit()
int LTHelixTrackFindingTask::StepInitTrackAddHit () private
Definition at line 232 of file LTHelixTrackFindingTask.cpp.
References CorrelateHitWithTrack(), CorrelateHitWithTrackCandidate(), fBadHits, fCandHits, fCurrentTrack, fCutMaxNumHitsInitTrack, fCutMinHelixRadius, fCutMinNumHitsInitTrack, fGoodHits, fMinHitsToFitInitTrack, fNumCandHits, fPadPlane, fTrackLengthCutScale, kStepContinuum, kStepInitTrack, kStepInitTrackAddHit, kStepRemoveTrack, and lk_debug.
Referenced by ExecStep().
StepNewTrack()
int LTHelixTrackFindingTask::StepNewTrack () private
Definition at line 126 of file LTHelixTrackFindingTask.cpp.
References fCandHits, fCurrentTrack, fGoodHits, fPadPlane, fReferenceAxis, fTrackArray, fTrackHits, kStepInitTrack, kStepNextPhase, lk_debug, and ReturnBadHitsToPadPlane().
Referenced by ExecStep().
StepNextPhase()
int LTHelixTrackFindingTask::StepNextPhase () private
Definition at line 490 of file LTHelixTrackFindingTask.cpp.
References fCandHits, fCutMaxNumHitsInitTrack, fGoodHits, fPadPlane, fPhaseIndex, fTrackHits, kStepEndEvent, kStepNewTrack, and ReturnBadHitsToPadPlane().
Referenced by ExecStep().
StepRemoveTrack()
int LTHelixTrackFindingTask::StepRemoveTrack () private
Definition at line 159 of file LTHelixTrackFindingTask.cpp.
References fCandHits, fCurrentTrack, fGoodHits, fPadPlane, fTrackArray, fTrackHits, kStepNewTrack, lk_debug, and ReturnBadHitsToPadPlane().
Referenced by ExecStep().
Member Data Documentation
fBadHits
LKHitArray* LTHelixTrackFindingTask::fBadHits = nullptr private
Definition at line 100 of file LTHelixTrackFindingTask.h.
Referenced by AutoBuildAtPosition(), ClassImp(), ReturnBadHitsToPadPlane(), StepContinuumAddHit(), StepInitArray(), and StepInitTrackAddHit().
fBranchNameHit
TString LTHelixTrackFindingTask::fBranchNameHit = "Hit" private
Definition at line 92 of file LTHelixTrackFindingTask.h.
Referenced by ClassImp(), and SetHitBranchName().
fBranchNameTracklet
TString LTHelixTrackFindingTask::fBranchNameTracklet = "Tracklet" private
Definition at line 93 of file LTHelixTrackFindingTask.h.
Referenced by SetTrackletBranchName().
fCandHits
LKHitArray* LTHelixTrackFindingTask::fCandHits = nullptr private
Definition at line 98 of file LTHelixTrackFindingTask.h.
Referenced by AutoBuildAtPosition(), ClassImp(), StepContinuum(), StepContinuumAddHit(), StepInitArray(), StepInitTrack(), StepInitTrackAddHit(), StepNewTrack(), StepNextPhase(), and StepRemoveTrack().
fCurrentTrack
LKHelixTrack* LTHelixTrackFindingTask::fCurrentTrack = nullptr private
Definition at line 119 of file LTHelixTrackFindingTask.h.
Referenced by CorrelateHitWithTrackCandidate(), ExecStep(), GetCurrentTrack(), StepConfirmation(), StepContinuumAddHit(), StepExtrapolationAddHit(), StepFinalizeTrack(), StepInitArray(), StepInitTrack(), StepInitTrackAddHit(), StepNewTrack(), and StepRemoveTrack().
fCutdkInExpectedTrackPath
Double_t LTHelixTrackFindingTask::fCutdkInExpectedTrackPath = 4. private
Definition at line 117 of file LTHelixTrackFindingTask.h.
Referenced by CorrelateHitWithTrackCandidate().
fCutMaxNumHitsInitTrack
Int_t LTHelixTrackFindingTask::fCutMaxNumHitsInitTrack = 15 private
return hits if track has more than this number of hits within initialization stage
Definition at line 113 of file LTHelixTrackFindingTask.h.
Referenced by StepInitTrackAddHit(), and StepNextPhase().
fCutMinHelixRadius
Double_t LTHelixTrackFindingTask::fCutMinHelixRadius = 30. private
helix radius cut for initialization stage
Definition at line 115 of file LTHelixTrackFindingTask.h.
Referenced by CheckTrackQuality(), and StepInitTrackAddHit().
fCutMinNumHitsFinalTrack
Int_t LTHelixTrackFindingTask::fCutMinNumHitsFinalTrack = 15 private
remove track if track has smaller than this number of hits within initialization stage
Definition at line 114 of file LTHelixTrackFindingTask.h.
Referenced by AutoBuildByExtrapolation(), and BuildAndConfirmTrack().
fCutMinNumHitsInitTrack
Int_t LTHelixTrackFindingTask::fCutMinNumHitsInitTrack = 10 private
Definition at line 112 of file LTHelixTrackFindingTask.h.
Referenced by StepInitTrackAddHit().
fCvsCurrentTrack
TCanvas* LTHelixTrackFindingTask::fCvsCurrentTrack = nullptr private
Definition at line 126 of file LTHelixTrackFindingTask.h.
fDefaultScale
Double_t LTHelixTrackFindingTask::fDefaultScale = 2.5 private
Definition at line 102 of file LTHelixTrackFindingTask.h.
Referenced by ClassImp(), and CorrelateHitWithTrack().
fGoodHits
LKHitArray* LTHelixTrackFindingTask::fGoodHits = nullptr private
Definition at line 99 of file LTHelixTrackFindingTask.h.
Referenced by ClassImp(), StepContinuum(), StepContinuumAddHit(), StepFinalizeTrack(), StepInitArray(), StepInitTrack(), StepInitTrackAddHit(), StepNewTrack(), StepNextPhase(), and StepRemoveTrack().
fGraphCurrentTrackPoint
TGraphErrors* LTHelixTrackFindingTask::fGraphCurrentTrackPoint = nullptr private
Definition at line 127 of file LTHelixTrackFindingTask.h.
fHitArray
TClonesArray* LTHelixTrackFindingTask::fHitArray = nullptr private
Definition at line 89 of file LTHelixTrackFindingTask.h.
Referenced by ClassImp(), and StepInitArray().
fMinHitsToFitInitTrack
Int_t LTHelixTrackFindingTask::fMinHitsToFitInitTrack = 7 private
try track fit if track has more than this number of hits in track
Definition at line 111 of file LTHelixTrackFindingTask.h.
Referenced by StepInitTrackAddHit().
fNextStep
Int_t LTHelixTrackFindingTask::fNextStep = StepNo::kStepInitArray private
Definition at line 121 of file LTHelixTrackFindingTask.h.
Referenced by ClassImp(), Exec(), ExecStep(), and ExecStepUptoTrackNum().
fNumBadHits
Int_t LTHelixTrackFindingTask::fNumBadHits private
Definition at line 124 of file LTHelixTrackFindingTask.h.
Referenced by ReturnBadHitsToPadPlane().
fNumCandHits
Int_t LTHelixTrackFindingTask::fNumCandHits private
Definition at line 122 of file LTHelixTrackFindingTask.h.
Referenced by AutoBuildAtPosition(), StepContinuum(), StepContinuumAddHit(), StepInitTrack(), and StepInitTrackAddHit().
fNumGoodHits
Int_t LTHelixTrackFindingTask::fNumGoodHits private
Definition at line 123 of file LTHelixTrackFindingTask.h.
fPadPlane
LKDetectorPlane* LTHelixTrackFindingTask::fPadPlane = nullptr private
Definition at line 88 of file LTHelixTrackFindingTask.h.
Referenced by AutoBuildAtPosition(), CheckTrackContinuity(), ClassImp(), ReturnBadHitsToPadPlane(), StepContinuum(), StepFinalizeTrack(), StepInitArray(), StepInitTrack(), StepInitTrackAddHit(), StepNewTrack(), StepNextPhase(), and StepRemoveTrack().
fPersistency
bool LTHelixTrackFindingTask::fPersistency = true private
Definition at line 95 of file LTHelixTrackFindingTask.h.
Referenced by SetTrackPersistency().
fPhaseIndex
Int_t LTHelixTrackFindingTask::fPhaseIndex = 0 private
Definition at line 109 of file LTHelixTrackFindingTask.h.
Referenced by StepInitArray(), and StepNextPhase().
fReferenceAxis
LKVector3::Axis LTHelixTrackFindingTask::fReferenceAxis = LKVector3::kZ private
Definition at line 107 of file LTHelixTrackFindingTask.h.
Referenced by AutoBuildAtPosition(), CheckTrackContinuity(), ClassImp(), CorrelateHitWithTrackCandidate(), StepConfirmation(), and StepNewTrack().
fTpc
LKDetector* LTHelixTrackFindingTask::fTpc = nullptr private
Definition at line 87 of file LTHelixTrackFindingTask.h.
fTrackArray
TClonesArray* LTHelixTrackFindingTask::fTrackArray = nullptr private
Definition at line 90 of file LTHelixTrackFindingTask.h.
Referenced by ClassImp(), ExecStepUptoTrackNum(), StepEndEvent(), StepInitArray(), StepNewTrack(), and StepRemoveTrack().
fTrackHCutHL
Double_t LTHelixTrackFindingTask::fTrackHCutHL = 15. private
Track height cut high limit.
Definition at line 106 of file LTHelixTrackFindingTask.h.
Referenced by ClassImp(), CorrelateHitWithTrack(), and CorrelateHitWithTrackCandidate().
fTrackHCutLL
Double_t LTHelixTrackFindingTask::fTrackHCutLL = 5. private
Track height cut low limit.
Definition at line 105 of file LTHelixTrackFindingTask.h.
Referenced by ClassImp(), CorrelateHitWithTrack(), and CorrelateHitWithTrackCandidate().
fTrackHits
LKHitArray* LTHelixTrackFindingTask::fTrackHits = nullptr private
Definition at line 97 of file LTHelixTrackFindingTask.h.
Referenced by ClassImp(), StepContinuum(), StepFinalizeTrack(), StepInitArray(), StepInitTrack(), StepNewTrack(), StepNextPhase(), and StepRemoveTrack().
fTrackLengthCutScale
Double_t LTHelixTrackFindingTask::fTrackLengthCutScale = 2.5 private
track length cut for initialization stage is [this_var] * track -> GetRMSR()
Definition at line 116 of file LTHelixTrackFindingTask.h.
Referenced by StepInitTrackAddHit().
fTrackWCutHL
Double_t LTHelixTrackFindingTask::fTrackWCutHL = 15. private
Track width cut high limit.
Definition at line 104 of file LTHelixTrackFindingTask.h.
Referenced by ClassImp(), and CorrelateHitWithTrack().
fTrackWCutLL
Double_t LTHelixTrackFindingTask::fTrackWCutLL = 5. private
Track width cut low limit.
Definition at line 103 of file LTHelixTrackFindingTask.h.
Referenced by ClassImp(), and CorrelateHitWithTrack().
The documentation for this class was generated from the following files:
LTHelixTrackFindingTask.h
LTHelixTrackFindingTask.cpp