lilak: LKLogger Class Reference
LKLogger Class Reference
lilak logger
#include <LKLogger.h>
Public Member Functions
LKLogger (const std::string &title, int line)
LKLogger (TString name, const std::string &title, int rank, int option)
template<class T >
LKLogger & operator<< (const T &v)
LKLogger & operator<< (std::ostream &(*f)(std::ostream &))
Detailed Description
lilak logger
Definition at line 105 of file LKLogger.h.
Constructor & Destructor Documentation
LKLogger() [1/2]
LKLogger::LKLogger (TString name, const std::string & title, int rank, int option)
Definition at line 76 of file LKLogger.cpp.
References LKLogManager::GetLogFile(), LKLogManager::LogToConsol(), LKLogManager::LogToFile(), LKLogManager::PrintCout(), LKLogManager::PrintCurrent(), LKLogManager::PrintError(), LKLogManager::PrintInfo(), LKLogManager::PrintList(), LKLogManager::PrintMessage(), LKLogManager::PrintPlane(), LKLogManager::PrintStrong(), LKLogManager::PrintTest(), LKLogManager::PrintWarn(), and LKLogManager::SetPrintCurrent().
LKLogger() [2/2]
LKLogger::LKLogger (const std::string & title, int line)
Definition at line 145 of file LKLogger.cpp.
References LKLogManager::GetLogFile(), LKLogManager::LogToConsol(), LKLogManager::LogToFile(), LKLogManager::PrintCurrent(), LKLogManager::PrintDebug(), LKLogManager::PrintMessage(), and LKLogManager::SetPrintCurrent().
Member Function Documentation
operator<<() [1/2]
template<class T > LKLogger & LKLogger::operator<< (const T & v) inline
Definition at line 111 of file LKLogger.h.
References LKLogManager::GetLogFile(), LKLogManager::LogToConsol(), LKLogManager::LogToFile(), LKLogManager::PrintCurrent(), and LKLogManager::PrintMessage().
operator<<() [2/2]
LKLogger & LKLogger::operator<< (std::ostream &(*)(std::ostream &) f) inline
Definition at line 121 of file LKLogger.h.
References LKLogManager::GetLogFile(), LKLogManager::LogToConsol(), LKLogManager::LogToFile(), LKLogManager::PrintCurrent(), and LKLogManager::PrintMessage().
The documentation for this class was generated from the following files:
LKLogger.h
LKLogger.cpp