lilak: SKSiArrayPlane Class Reference
SKSiArrayPlane Class Reference
#include <SKSiArrayPlane.h>
Public Member Functions
bool AddUserDrawings (TString label, int detID, int joID, TObjArray *userDrawingArray, int leastNDraw=1)
void ClearFiredFlags ()
virtual void ClickedControlDDPage (double xOnClick, double yOnClick)
virtual void ClickedEventDisplay1 (double xOnClick, double yOnClick)
virtual void ClickedEventDisplay2 (double xOnClick, double yOnClick)
virtual void ClickedJOSideDisplay (int jo)
virtual void ClickedUserDrawing (double xOnClick, double yOnClick)
void ExecMouseClickEventOnPad (TVirtualPad *pad, double xOnClick, double yOnClick)
void ExitEve ()
virtual void FillDataToHistEventDisplay1 (Option_t *option="")
int FindEPairDetectorID (int det)
virtual int FindPadID (int cobo, int asad, int aget, int chan)
virtual int FindPadIDFromHistEventDisplay1Bin (int hbin)
int FindSiChannelID (int cobo, int asad, int aget, int chan)
int FindSiDetectorID (int cobo, int asad, int aget, int chan)
void FireStrip (int det, int side, int strip, double energy)
virtual TPad * Get3DEventPad ()
If user wants to place 3D event display other than default canvas, this method should return corresponding TPad.
virtual TCanvas * GetCanvas (Option_t *option="")
Implementation recommanded for event display.
LKSiDetector * GetFiredDetector (int iFired)
virtual TH2 * GetHist (Option_t *option="")
virtual TH1D * GetHistChannelBuffer ()
virtual TH2 * GetHistControlDDPage (Option_t *option="-1")
virtual TH2 * GetHistEventDisplay1 (Option_t *option="-1")
virtual TH2 * GetHistEventDisplay2 (Option_t *option="-1")
virtual TH2 * GetHistUserDrawing (Option_t *option="-1")
int GetNumFiredDetectors ()
int GetNumSiDetectors () const
LKSiChannel * GetSiChannel (int cobo, int asad, int aget, int chan)
LKSiChannel * GetSiChannel (int idx)
LKSiDetector * GetSiDetector (int cobo, int asad, int aget, int chan)
LKSiDetector * GetSiDetector (int idx)
LKSiDetector * GetSiDetectorData (int idx)
virtual bool Init ()
virtual void Print (Option_t *option="") const
virtual bool SetDataFromBranch ()
Implementation recommanded. Set waveform and hit data from input tree branches to pads.
bool SetSiChannelData (LKSiChannel *siChannel, GETChannel *channel)
SKSiArrayPlane ()
SKSiArrayPlane (const char *name, const char *title)
virtual void UpdateAll ()
virtual void UpdateDataDisplays ()
virtual void UpdateEventDisplay1 ()
virtual void UpdateEventDisplay2 ()
virtual void UpdateJunctionOhmic ()
virtual void UpdateUserDrawing ()
virtual ~SKSiArrayPlane ()
Public Member Functions inherited from LKEvePlane
virtual void Clear (Option_t *option="")
virtual void Clear (Option_t *option="")
virtual void ClickedControlEvent1 (double xOnClick, double yOnClick)
virtual void ClickedControlEvent1 (double xOnClick, double yOnClick)
virtual void ClickedControlEvent1 (int selectedBin)
virtual void ClickedControlEvent1 (int selectedBin)
virtual void ClickedControlEvent2 (double xOnClick, double yOnClick)
virtual void ClickedControlEvent2 (double xOnClick, double yOnClick)
virtual void ClickedControlEvent2 (int selectedBin)
virtual void ClickedControlEvent2 (int selectedBin)
virtual void ClickedEventDisplay1 (double xOnClick, double yOnClick)
virtual void ClickedEventDisplay1 (double xOnClick, double yOnClick)
virtual void ClickedEventDisplay2 (double xOnClick, double yOnClick)
virtual void ClickedEventDisplay2 (double xOnClick, double yOnClick)
virtual void Draw (Option_t *option="")
Implementation recommanded for event display. Draw event display to the canvas.
virtual void Draw (Option_t *option="")
Implementation recommanded for event display. Draw event display to the canvas.
virtual void DrawFrame (Option_t *option="")
virtual void DrawFrame (Option_t *option="")
virtual void DrawHist (Option_t *option="")
virtual void DrawHist (Option_t *option="")
virtual void DriftElectronBack (int padID, double tb, TVector3 &posReco, double &driftLength)
virtual void DriftElectronBack (int padID, double tb, TVector3 &posReco, double &driftLength)
virtual void ExecMouseClickEventOnPad (TVirtualPad *pad, double xOnClick, double yOnClick)
virtual void ExecMouseClickEventOnPad (TVirtualPad *pad, double xOnClick, double yOnClick)
virtual void ExitEve ()
virtual void FillDataToHist (Option_t *option="")
Implementation recommanded. Fill data to histograms.
virtual void FillDataToHist (Option_t *option="")
Implementation recommanded. Fill data to histograms.
virtual void FillDataToHistEventDisplay1 (Option_t *option="")
virtual void FillDataToHistEventDisplay1 (Option_t *option="")
virtual void FillDataToHistEventDisplay2 (Option_t *option="")
virtual void FillDataToHistEventDisplay2 (Option_t *option="")
virtual int FindChannelID (double i, double j)
Implementation recommanded. Find channel using position.
virtual int FindChannelID (double i, double j)
Implementation recommanded. Find channel using position.
virtual int FindChannelID (int section, int layer, int row)
Implementation recommanded. Find channel using section, layer, row info.
virtual int FindChannelID (int section, int layer, int row)
Implementation recommanded. Find channel using section, layer, row info.
virtual LKPad * FindPad (int cobo, int asad, int aget, int chan)
TODO.
virtual LKPad * FindPad (int cobo, int asad, int aget, int chan)
TODO.
virtual int FindPadID (int cobo, int asad, int aget, int chan)
virtual int FindPadID (int cobo, int asad, int aget, int chan)
virtual int FindPadIDFromHistEventDisplay1Bin (int hbin)
virtual int FindPadIDFromHistEventDisplay1Bin (int hbin)
virtual int FindPadIDFromHistEventDisplay2Bin (int hbin)
virtual int FindPadIDFromHistEventDisplay2Bin (int hbin)
virtual TPad * Get3DEventPad ()
If user wants to place 3D event display other than default canvas, this method should return corresponding TPad.
virtual TPad * Get3DEventPad ()
If user wants to place 3D event display other than default canvas, this method should return corresponding TPad.
Long64_t GetAccumulateEvents () const
virtual axis_t GetAxis1 (int iPad=0) const
virtual axis_t GetAxis1 (int iPad=0) const
virtual axis_t GetAxis2 (int iPad=0) const
virtual axis_t GetAxis2 (int iPad=0) const
virtual TCanvas * GetCanvas (Option_t *option="")
Implementation recommanded for event display.
virtual TCanvas * GetCanvas (Option_t *option="")
Implementation recommanded for event display.
virtual LKChannelAnalyzer * GetChannelAnalyzer (int id=0)
virtual LKChannelAnalyzer * GetChannelAnalyzer (int id=0)
virtual TPad * GetCPad (int iPad)
For grabbing inner pads of canvas.
virtual TPad * GetCPad (int iPad)
For grabbing inner pads of canvas.
virtual TH2 * GetHist (Option_t *option="-1")
virtual TH2 * GetHist (Option_t *option="-1")
virtual TH1D * GetHistChannelBuffer ()
virtual TH1D * GetHistChannelBuffer ()
virtual TH2D * GetHistControlEvent1 ()
virtual TH2D * GetHistControlEvent1 ()
virtual TH2D * GetHistControlEvent2 ()
virtual TH2D * GetHistControlEvent2 ()
virtual TH2 * GetHistEventDisplay1 (Option_t *option="-1")
virtual TH2 * GetHistEventDisplay1 (Option_t *option="-1")
virtual TH2 * GetHistEventDisplay2 (Option_t *option="-1")
virtual TH2 * GetHistEventDisplay2 (Option_t *option="-1")
virtual int GetNumCPads ()
Get number of inner pads of canvas.
virtual int GetNumCPads ()
Get number of inner pads of canvas.
TPad * GetPadChannelBuffer ()
TPad * GetPadChannelBuffer ()
TPad * GetPadControlEvent1 ()
TPad * GetPadControlEvent1 ()
TPad * GetPadControlEvent2 ()
TPad * GetPadControlEvent2 ()
TPad * GetPadEventDisplay1 ()
TPad * GetPadEventDisplay1 ()
TPad * GetPadEventDisplay2 ()
TPad * GetPadEventDisplay2 ()
virtual TVector3 GlobalToLocalAxis (TVector3 posGlobal)
Implementation recommanded. Convert global position to local detector plane position TODO.
virtual TVector3 GlobalToLocalAxis (TVector3 posGlobal)
Implementation recommanded. Convert global position to local detector plane position TODO.
virtual bool Init ()
virtual bool Init ()
virtual bool IsInBoundary (double i, double j)
Implementation recommanded. Return if position (i,j) is inside the effective detector plane boundary TODO.
virtual bool IsInBoundary (double i, double j)
Implementation recommanded. Return if position (i,j) is inside the effective detector plane boundary TODO.
LKEvePlane ()
LKEvePlane ()
LKEvePlane (const char *name, const char *title)
LKEvePlane (const char *name, const char *title)
virtual TVector3 LocalToGlobalAxis (TVector3 posLocal)
Implementation recommanded. Convert local position to global detector plane position TODO.
virtual TVector3 LocalToGlobalAxis (TVector3 posLocal)
Implementation recommanded. Convert local position to global detector plane position TODO.
virtual double PadDisplacement () const
Return average pad displacement to each other.
virtual double PadDisplacement () const
Return average pad displacement to each other.
virtual void Print (Option_t *option="") const
virtual void Print (Option_t *option="") const
virtual bool SetDataFromBranch ()
Implementation recommanded. Set waveform and hit data from input tree branches to pads.
virtual bool SetDataFromBranch ()
Implementation recommanded. Set waveform and hit data from input tree branches to pads.
void SetPalette ()
void SetPalette ()
virtual void UpdateAll ()
virtual void UpdateAll ()
virtual void UpdateChannelBuffer ()
virtual void UpdateChannelBuffer ()
virtual void UpdateControlEvent1 ()
virtual void UpdateControlEvent1 ()
virtual void UpdateControlEvent2 ()
virtual void UpdateControlEvent2 ()
virtual void UpdateEventDisplay1 ()
virtual void UpdateEventDisplay1 ()
virtual void UpdateEventDisplay2 ()
virtual void UpdateEventDisplay2 ()
virtual void UpdateFill (bool updateHist=true)
virtual void UpdateFill (bool updateHist=true)
virtual void UpdateMenu ()
virtual void UpdateMenuControlEvent2 ()
virtual ~LKEvePlane ()
virtual ~LKEvePlane ()
Public Member Functions inherited from LKDetectorPlane
void AddChannel (LKChannel *channel)
Add channel to channel array in detector plane. For interanl use.
void AddHit (LKHit *hit)
void AddPad (LKPad *pad)
Add pad to pad array in detector plane. For interanl use.
virtual void Clear (Option_t *option="")
virtual void Draw (Option_t *option="")
Implementation recommanded for event display. Draw event display to the canvas.
virtual void DrawFrame (Option_t *option="")
virtual void DrawHist (Option_t *option="")
virtual void DriftElectron (TVector3 posGlobal, TVector3 &posFinal, double &driftLength)
virtual double DriftElectronBack (double tb)
virtual void DriftElectronBack (int padID, double tb, TVector3 &posReco, double &driftLength)
virtual void DriftElectronBack (LKPad *pad, double tb, TVector3 &posReco, double &driftLength)
virtual void FillDataToHist ()
Implementation recommanded. Fill data to histograms.
void FillPlane (double i, double j, double tb, double charge, int trackID=-1)
Find pad corresponding to the position (i,j) and fill time-bin by amount of charge.
virtual int FindChannelID (double i, double j)
Implementation recommanded. Find channel using position.
virtual int FindChannelID (int section, int layer, int row)
Implementation recommanded. Find channel using section, layer, row info.
virtual int FindPadID (double i, double j)
virtual int FindPadID (int cobo, int asad, int aget, int chan)
virtual int FindPadID (int section, int layer, int row)
virtual TPad * Get3DEventPad ()
If user wants to place 3D event display other than default canvas, this method should return corresponding TPad.
virtual axis_t GetAxis1 (int iPad=0) const
virtual axis_t GetAxis2 (int iPad=0) const
virtual axis_t GetAxis3 () const
virtual axis_t GetAxisDrift () const
virtual TCanvas * GetCanvas (Option_t *option="")
Implementation recommanded for event display.
LKChannel * GetChannel (int idx)
virtual LKChannelAnalyzer * GetChannelAnalyzer (int id=0)
TObjArray * GetChannelArray ()
LKChannel * GetChannelFast (int idx)
virtual TPad * GetCPad (int iPad)
For grabbing inner pads of canvas.
virtual TH2 * GetHist (Option_t *option="-1")
int GetNChannels ()
virtual int GetNumCPads ()
Get number of inner pads of canvas.
int GetNumPads ()
LKPad * GetPad (double i, double j)
LKPad * GetPad (int cobo, int asad, int aget, int chan)
LKPad * GetPad (int padID)
LKPad * GetPad (int section, int layer, int row)
TObjArray * GetPadArray ()
LKPad * GetPadFast (int idx)
int GetPlaneID () const
double GetPosition () const
virtual TVector3 GetPositionError (int padID)
double GetTbToLength () const
virtual TVector3 GlobalToLocalAxis (TVector3 posGlobal)
Implementation recommanded. Convert global position to local detector plane position.
void GrabNeighborPads (vector< LKPad * > *pads, vector< LKPad * > *neighborPads)
For tracking use.
virtual bool Init ()
bool IsActive () const
virtual bool IsInBoundary (double i, double j)
Implementation recommanded. Return if position (i,j) is inside the effective detector plane boundary.
LKDetectorPlane ()
LKDetectorPlane (const char *name, const char *title)
virtual TVector3 LocalToGlobalAxis (TVector3 posLocal)
virtual double PadDisplacement () const
Return average pad displacement to each other.
bool PadMapChecker ()
bool PadNeighborChecker ()
bool PadPositionChecker (bool checkCorners=true)
virtual void Print (Option_t *option="") const
void PullOutNeighborHits (double x, double y, int range, LKHitArray *neighborHits)
For tracking use.
void PullOutNeighborHits (double x, double y, int range, vector< LKHit * > *neighborHits)
For tracking use.
void PullOutNeighborHits (LKHitArray *hits, LKHitArray *neighborHits)
For tracking use.
void PullOutNeighborHits (TVector2 p, int range, vector< LKHit * > *neighborHits)
For tracking use.
void PullOutNeighborHits (vector< LKHit * > *hits, vector< LKHit * > *neighborHits)
For tracking use.
virtual LKHit * PullOutNextFreeHit ()
For tracking use.
virtual void ResetEvent ()
For tracking use.
virtual void ResetHitMap ()
For tracking use.
void SetActive (bool val)
virtual bool SetDataFromBranch ()
Implementation recommanded. Set waveform and hit data from input tree branches to pads.
void SetDetector (LKDetector *detector)
void SetDetectorName (TString name)
void SetHitArray (TClonesArray *hitArray)
void SetPadArray (TClonesArray *padArray)
void SetPlaneID (int id)
virtual ~LKDetectorPlane ()
Public Member Functions inherited from LKGear
void AddPar (LKParameterContainer *par)
void AddPar (TString fname)
virtual void AddParameterContainer (LKParameterContainer *par)
virtual void AddParameterContainer (TString fname)
void CreateParameterContainer ()
LKParameterContainer * GetPar () const
LKParameterContainer * GetParameterContainer () const
Int_t GetRank () const
LKGear ()
void SetAllowControlLogger (bool val)
void SetPar (LKParameterContainer *par)
virtual void SetParameterContainer (LKParameterContainer *par)
virtual void SetRank (Int_t rank)
void SetRun (LKRun *run)
virtual ~LKGear ()
Public Member Functions inherited from LKPadInteractive
void AddInteractivePad (TVirtualPad *pad, TString option="")
virtual void ExecMouseClickEventOnPad (TVirtualPad *pad, double xOnClick, double yOnClick)
int GetPadInteractiveID () const
LKPadInteractive ()
void SetPadInteractiveID (int id)
virtual ~LKPadInteractive ()
Protected Attributes
int fBinCtrlCurrPage
int fBinCtrlNextPage
int fBinCtrlPrevPage
TObjArray * fChannelArray = nullptr
double fCtrlLabelOffset = 0.10
int fCurrentView = 1
TObjArray * fDetectorArray = nullptr
TString fDetectorParName
LKParameterContainer fDetectorTypeArray
TH2 * fFrameEventDisplay1 = nullptr
TGraph * fGSelJOSideDisplay = nullptr
TH2D * fHistControlDDPage = nullptr
TH2 * fHistCtrlUserDrawing = nullptr
double fLayerYOffset = 0.05
double fLayerYScale = 100
int * fMapBinToDetector
histogram bin to pad-id mapping
int **** fMapCAACToChannelIndex
[cobo][asad][aget][chan] to channel-index mapping
int **** fMapCAACToDetectorIndex
[cobo][asad][aget][chan] to detector-index mapping
TString fMappingFileName
int fMaxDetectors = 40
int fMaxLayerIndex = -INT_MAX
double fMaxPhi = -DBL_MAX
double fMinPhi = DBL_MAX
int fNumAget = 4
int fNumAsad = 4
int fNumChan = 68
int fNumCobo = 6
int fNumDataDisplays = fNumDDX*fNumDDY
int fNumDDX = 2
int fNumDDY = 3
int fNumDrawingsInArray = 0
int fNumGoodDrawings = 0
int fNumSelUDGroup = 0
int fNumUDLabels = 0
int fNumUDPage = 0
int fNumUserDrawing = 0
TPad * fPadControlDDPage = nullptr
TPad * fPadCtrlUserDrawing = nullptr
TPad * fPadDataDisplayFull
TPad * fPadDataDisplaySmall [24]
TPad * fPadDataDisplayThree [3]
TPad * fPadDataDisplayTwo [2]
TPad * fPadJOSideDisplay [2]
LKParameterContainer fParUserDrawing
int fPrevEventID = -1
int fPrevEventID2 = -1
int fSelControlDDPage = 0
int fSelDetID = 0
int fSelJOID = -1
TObjArray * fSelUDArray = nullptr
int fSelUDArrayID = 0
int fSelUDBin = -1
int fSelUDLeastNDraw = 1
int fSelUDTab = 0
bool fSignalUDBinChange = true
bool fSignalUDTabChange = true
double fThreshold = 300
int fUDGoodIndex [10][16]
TObjArray * fUserDrawingArrayCollection = nullptr
int **** fUserDrawingArrayIndex
int **** fUserDrawingLeastNDraw
TString fUserDrawingName [4][7]
int kUpdateDataDisplays = 7
int kUpdateJunctionOhmic = 8
int kUpdateUserDrawing = 6
Protected Attributes inherited from LKEvePlane
bool fAccumulateAllEvents = false
int fAccumulateChannel = 0
to accumulate channel waveform
Long64_t fAccumulateEvent1 = 0
first accumulated event id
Long64_t fAccumulateEvent2 = 0
last accumulated event id
Long64_t fAccumulateEvents = 0
to accumulate event in event display
int fBinCtrlAcmltCh
int fBinCtrlAcmltEv
int fBinCtrlChgMenu
int fBinCtrlCurr = -1
int fBinCtrlDrawACh
int fBinCtrlE500
int fBinCtrlEngyMax
int fBinCtrlEngyMin
int fBinCtrlESkp = -1
int fBinCtrlExit = -1
int fBinCtrlFillAEv
int fBinCtrlFitChan
int fBinCtrlFrst = -1
int fBinCtrlLast = -1
int fBinCtrlNe50
int fBinCtrlNeJP = -1
int fBinCtrlNext = -1
int fBinCtrlPalette
int fBinCtrlPr50
int fBinCtrlPrev = -1
int fBinCtrlPrJP = -1
int fBinCtrlSavePng
int fBinCtrlSaveRoo
int fBinDrawTrackGf
int fBinFillChACAAC
int fBinFillElectID
int fBinFillHitNHit
int fBinFillRawPrev
bool fBranchIsSet = false
TClonesArray * fChannelGraphArray = nullptr
array of accumulate channel graphs
Long64_t fCountChangeEvent = 0
int fCountChangeOther = 0
int fCountChannelGraph = 0
count number of accumulate channels
int fCountSaveFig = 0
int fCountSavePng = 0
int fCountSaveRoo = 0
double fCtrlBinTextSize = 6.0
double fCtrlLabelSize = 0.18
int fCurrentMenu = 0
double fDXCanvas = 1200
double fDYCanvas = 700
int fEnergyMax = 1
0 : auto, 1; 4200, >2: fEnergyMax = maximum value
int fEnergyMin = -1
0 : auto, 1; -1
TString fEventDisplayDrawOption = "colz"
TString fFillOptionSelected = ""
bool fFitChannel = false
for finding energy using fChannelAnalyzer
TGraph * fGSelEventDisplay1 = nullptr
TGraph * fGSelEventDisplay2 = nullptr
TH1D * fHistChannelBuffer = nullptr
TH2D * fHistControlEvent1 = nullptr
TH2D * fHistControlEvent2 = nullptr
TH2 * fHistEventDisplay1 = nullptr
TH2 * fHistEventDisplay2 = nullptr
TClonesArray * fHitArray = nullptr
int fJumpEventSize = 2000
bool fJustFill = false
int fNumAccumulateChannels = 0
to accumulate channel waveform
int fNumMenus = 8
axis_t fPadAxis1 [2] = {LKVector3::kNon, LKVector3::kNon}
axis_t fPadAxis2 [2] = {LKVector3::kNon, LKVector3::kNon}
TPad * fPadChannelBuffer = nullptr
TPad * fPadControlEvent1 = nullptr
TPad * fPadControlEvent2 = nullptr
TPad * fPadEventDisplay1 = nullptr
TPad * fPadEventDisplay2 = nullptr
bool fPaletteIsInverted = false
int fPaletteNumber = 0
TClonesArray * fRawDataArray = nullptr
bool fReturnDraw = false
TString fSavePath = "eve_data"
int fSelPadID = 0
Selected pad id by mouse click.
int fSelRawDataID = 0
Selected raw data by mouse click.
int fSkipToEnergy = 500
TClonesArray * fTrackArray = nullptr
double fYCCanvas = 230./700
const TString kFillAget = "aget"
const TString kFillAsad = "asad"
const TString kFillCAAC = "caac"
const TString kFillChan = "chan"
const TString kFillCobo = "cobo"
const TString kFillHits = "hit"
const TString kFillNHit = "nhits"
const TString kFillPrev = "preview"
const TString kFillRawD = "raw"
const TString kFillZero = ""
int kUpdateChannelBuffer = 5
int kUpdateControlEvent1 = 3
int kUpdateControlEvent2 = 4
int kUpdateEventDisplay1 = 1
int kUpdateEventDisplay2 = 2
bool UpdateFlag [20]
Protected Attributes inherited from LKDetectorPlane
bool fActive = true
axis_t fAxis1 = LKVector3::kNon
Axis-1 lying in plane. Must be set by input parameter.
axis_t fAxis2 = LKVector3::kNon
Axis-2 lying in plane. Must be set by input parameter.
axis_t fAxis3 = LKVector3::kNon
Axis-3 = Axis-1 x Axis-2 perpendicular to plane.
axis_t fAxisDrift = LKVector3::kNon
Axis perpendicular to plane, in electron drifting direction. Must be set by input parameter.
TCanvas * fCanvas = nullptr
LKChannelAnalyzer * fChannelAnalyzer = nullptr
TObjArray * fChannelArray = nullptr
TCanvas * fCvsChannelBuffer = nullptr
LKDetector * fDetector = nullptr
TString fDetName
int fFreePadIdx = 0
TGraph * fGraphChannelBoundary = nullptr
TGraph * fGraphChannelBoundaryNb [20] = {0}
TH2 * fH2Plane = nullptr
bool fHitDataIsSet = false
bool fPadDataIsSet = false
int fPlaneID = -1
Detector plane id.
double fPosition
Global position of pad plane center.
double fTbToLength = 1
time-bin (tb) to position conversion factor. Must be set by input parameter.
Protected Attributes inherited from LKGear
bool fAllowControlLogger = true
LKParameterContainer * fPar = nullptr
Int_t fRank = 0
LKRun * fRun = nullptr
Protected Attributes inherited from LKPadInteractive
int fPadInteractiveID = -1
Private Attributes
LKParameterContainer * fArrayChannelDrawing = nullptr
LKParameterContainer * fArrayDetectorDrawing = nullptr
LKParameterContainer * fArrayEventDrawing = nullptr
LKParameterContainer * fArrayPairDrawing = nullptr
int fCountHistArray1 = 0
int fCountHistArray2 = 0
int fdEEPairMapping [40][2]
TClonesArray * fHistArray1 = nullptr
TClonesArray * fHistArray2 = nullptr
int fNumArrayChannelDrawing = 0
int fNumArrayDetectorDrawing = 0
int fNumArrayEventDrawing = 0
int fNumArrayPairDrawing = 0
TClonesArray * fSiChannelArray = nullptr
TClonesArray * fSiHitArray = nullptr
double fUserPhiScale = 1.
Detailed Description
Definition at line 12 of file SKSiArrayPlane.h.
Constructor & Destructor Documentation
SKSiArrayPlane() [1/2]
SKSiArrayPlane::SKSiArrayPlane ()
SKSiArrayPlane() [2/2]
SKSiArrayPlane::SKSiArrayPlane (const char * name, const char * title)
Definition at line 20 of file SKSiArrayPlane.cpp.
References fChannelArray, LKEvePlane::fCtrlBinTextSize, LKEvePlane::fCtrlLabelSize, fDetectorArray, fGSelJOSideDisplay, LKEvePlane::fPaletteNumber, and fUserDrawingArrayCollection.
~SKSiArrayPlane()
virtual SKSiArrayPlane::~SKSiArrayPlane () inline virtual
Definition at line 17 of file SKSiArrayPlane.h.
Member Function Documentation
AddUserDrawings()
bool SKSiArrayPlane::AddUserDrawings (TString label, int detID, int joID, TObjArray * userDrawingArray, int leastNDraw = 1)
Definition at line 460 of file SKSiArrayPlane.cpp.
References fMaxDetectors, fNumUDLabels, fSelUDBin, fUserDrawingArrayCollection, fUserDrawingArrayIndex, fUserDrawingLeastNDraw, fUserDrawingName, and lk_info.
ClearFiredFlags()
void SKSiArrayPlane::ClearFiredFlags ()
Definition at line 1580 of file SKSiArrayPlane.cpp.
References ClearFiredFlags(), and fDetectorArray.
Referenced by ClearFiredFlags().
ClickedControlDDPage()
void SKSiArrayPlane::ClickedControlDDPage (double xOnClick, double yOnClick) virtual
Definition at line 1397 of file SKSiArrayPlane.cpp.
References fHistControlDDPage, fHistCtrlUserDrawing, fSelControlDDPage, and UpdateDataDisplays().
Referenced by ExecMouseClickEventOnPad().
ClickedEventDisplay1()
void SKSiArrayPlane::ClickedEventDisplay1 (double xOnClick, double yOnClick) virtual
Reimplemented from LKEvePlane.
Definition at line 827 of file SKSiArrayPlane.cpp.
References fDetectorArray, LKEvePlane::fHistEventDisplay1, FindPadIDFromHistEventDisplay1Bin(), fSelDetID, fSignalUDBinChange, lk_error, Print(), UpdateJunctionOhmic(), and UpdateUserDrawing().
Referenced by ExecMouseClickEventOnPad().
ClickedEventDisplay2()
void SKSiArrayPlane::ClickedEventDisplay2 (double xOnClick, double yOnClick) virtual
Reimplemented from LKEvePlane.
Definition at line 1304 of file SKSiArrayPlane.cpp.
ClickedJOSideDisplay()
void SKSiArrayPlane::ClickedJOSideDisplay (int jo) virtual
Definition at line 799 of file SKSiArrayPlane.cpp.
References fDetectorArray, fGSelJOSideDisplay, fLayerYOffset, fLayerYScale, fSelDetID, fSelJOID, fSignalUDBinChange, SetPoint(), UpdateEventDisplay1(), UpdateJunctionOhmic(), and UpdateUserDrawing().
Referenced by ExecMouseClickEventOnPad().
ClickedUserDrawing()
void SKSiArrayPlane::ClickedUserDrawing (double xOnClick, double yOnClick) virtual
Definition at line 1415 of file SKSiArrayPlane.cpp.
References fHistCtrlUserDrawing, fNumUDLabels, fSelUDBin, fSelUDTab, fSignalUDBinChange, fSignalUDTabChange, fUserDrawingName, lk_info, and UpdateUserDrawing().
Referenced by ExecMouseClickEventOnPad().
ExecMouseClickEventOnPad()
void SKSiArrayPlane::ExecMouseClickEventOnPad (TVirtualPad * pad, double xOnClick, double yOnClick) virtual
Reimplemented from LKEvePlane.
Definition at line 787 of file SKSiArrayPlane.cpp.
References ClickedControlDDPage(), LKEvePlane::ClickedControlEvent1(), LKEvePlane::ClickedControlEvent2(), ClickedEventDisplay1(), ClickedJOSideDisplay(), ClickedUserDrawing(), LKEvePlane::fCountChangeOther, fPadControlDDPage, LKEvePlane::fPadControlEvent1, LKEvePlane::fPadControlEvent2, fPadCtrlUserDrawing, LKEvePlane::fPadEventDisplay1, fPadJOSideDisplay, fSignalUDBinChange, and LKEvePlane::UpdateFlag.
ExitEve()
void SKSiArrayPlane::ExitEve () virtual
Reimplemented from LKEvePlane.
Definition at line 1537 of file SKSiArrayPlane.cpp.
References e_info, LKGear::fRun, and fUserDrawingArrayCollection.
FillDataToHistEventDisplay1()
void SKSiArrayPlane::FillDataToHistEventDisplay1 (Option_t * option = "") virtual
Reimplemented from LKEvePlane.
Definition at line 1054 of file SKSiArrayPlane.cpp.
References LKDetectorPlane::AddChannel(), LKEvePlane::fAccumulateEvents, fCurrentView, fDetectorArray, LKEvePlane::fFillOptionSelected, LKEvePlane::fHitArray, fPrevEventID, LKEvePlane::fRawDataArray, LKGear::fRun, fSelDetID, fSiChannelArray, fSignalUDBinChange, fSiHitArray, GetSiChannel(), lk_error, lk_info, lk_warning, and strip.
FindEPairDetectorID()
int SKSiArrayPlane::FindEPairDetectorID (int det)
Definition at line 1528 of file SKSiArrayPlane.cpp.
References det, fdEEPairMapping, and GetSiDetector().
FindPadID()
int SKSiArrayPlane::FindPadID (int cobo, int asad, int aget, int chan) virtual
Reimplemented from LKEvePlane.
Definition at line 1448 of file SKSiArrayPlane.cpp.
References fMapCAACToChannelIndex.
Referenced by FindSiChannelID().
FindPadIDFromHistEventDisplay1Bin()
int SKSiArrayPlane::FindPadIDFromHistEventDisplay1Bin (int hbin) virtual
Reimplemented from LKEvePlane.
Definition at line 701 of file SKSiArrayPlane.cpp.
References fMapBinToDetector.
Referenced by ClickedEventDisplay1().
FindSiChannelID()
int SKSiArrayPlane::FindSiChannelID (int cobo, int asad, int aget, int chan) inline
Definition at line 55 of file SKSiArrayPlane.h.
References FindPadID().
Referenced by GetSiChannel().
FindSiDetectorID()
int SKSiArrayPlane::FindSiDetectorID (int cobo, int asad, int aget, int chan)
Definition at line 1508 of file SKSiArrayPlane.cpp.
References fMapCAACToDetectorIndex.
Referenced by GetSiDetector().
FireStrip()
void SKSiArrayPlane::FireStrip (int det, int side, int strip, double energy)
Definition at line 1574 of file SKSiArrayPlane.cpp.
References det, fDetectorArray, and strip.
Get3DEventPad()
TPad * SKSiArrayPlane::Get3DEventPad () virtual
If user wants to place 3D event display other than default canvas, this method should return corresponding TPad.
Reimplemented from LKEvePlane.
Definition at line 714 of file SKSiArrayPlane.cpp.
References fCurrentView, and LKEvePlane::GetPadEventDisplay2().
GetCanvas()
TCanvas * SKSiArrayPlane::GetCanvas (Option_t * option = "") virtual
Implementation recommanded for event display.
Reimplemented from LKEvePlane.
Definition at line 300 of file SKSiArrayPlane.cpp.
References LKPadInteractive::AddInteractivePad(), b1, b2, LKEvePlane::Draw(), LKDetectorPlane::fCanvas, LKEvePlane::fDXCanvas, LKEvePlane::fDYCanvas, fNumDDX, fNumDDY, fPadControlDDPage, LKEvePlane::fPadControlEvent1, LKEvePlane::fPadControlEvent2, fPadCtrlUserDrawing, fPadDataDisplayFull, fPadDataDisplaySmall, fPadDataDisplayThree, fPadDataDisplayTwo, LKEvePlane::fPadEventDisplay1, fPadJOSideDisplay, LKGear::fRun, LKRun::GetInputFile(), LKPainter::GetPainter(), and y2.
GetFiredDetector()
LKSiDetector * SKSiArrayPlane::GetFiredDetector (int iFired)
Definition at line 1603 of file SKSiArrayPlane.cpp.
References fDetectorArray.
GetHist()
TH2 * SKSiArrayPlane::GetHist (Option_t * option = "") virtual
Reimplemented from LKEvePlane.
Definition at line 396 of file SKSiArrayPlane.cpp.
References LKEvePlane::fHistEventDisplay1, LKEvePlane::GetHist(), GetHistControlDDPage(), and GetHistUserDrawing().
GetHistChannelBuffer()
TH1D * SKSiArrayPlane::GetHistChannelBuffer () virtual
Reimplemented from LKEvePlane.
Definition at line 674 of file SKSiArrayPlane.cpp.
References LKEvePlane::fHistChannelBuffer.
GetHistControlDDPage()
TH2 * SKSiArrayPlane::GetHistControlDDPage (Option_t * option = "-1") virtual
Definition at line 404 of file SKSiArrayPlane.cpp.
References LKEvePlane::fCtrlBinTextSize, LKEvePlane::fCtrlLabelSize, fHistControlDDPage, and LKEvePlane::fPaletteNumber.
Referenced by GetHist().
GetHistEventDisplay1()
TH2 * SKSiArrayPlane::GetHistEventDisplay1 (Option_t * option = "-1") virtual
Reimplemented from LKEvePlane.
Definition at line 621 of file SKSiArrayPlane.cpp.
References fDetectorArray, LKEvePlane::fHistEventDisplay1, fLayerYOffset, fLayerYScale, fMapBinToDetector, fMaxLayerIndex, fMaxPhi, fMinPhi, and fUserPhiScale.
GetHistEventDisplay2()
TH2 * SKSiArrayPlane::GetHistEventDisplay2 (Option_t * option = "-1") virtual
Reimplemented from LKEvePlane.
Definition at line 669 of file SKSiArrayPlane.cpp.
References LKEvePlane::fHistEventDisplay2.
GetHistUserDrawing()
TH2 * SKSiArrayPlane::GetHistUserDrawing (Option_t * option = "-1") virtual
Definition at line 435 of file SKSiArrayPlane.cpp.
References LKEvePlane::fCtrlBinTextSize, LKEvePlane::fCtrlLabelSize, fHistCtrlUserDrawing, LKEvePlane::fPaletteNumber, and UpdateUserDrawing().
Referenced by GetHist().
GetNumFiredDetectors()
int SKSiArrayPlane::GetNumFiredDetectors ()
Definition at line 1590 of file SKSiArrayPlane.cpp.
References fDetectorArray.
GetNumSiDetectors()
int SKSiArrayPlane::GetNumSiDetectors () const inline
Definition at line 45 of file SKSiArrayPlane.h.
References fDetectorArray.
GetSiChannel() [1/2]
LKSiChannel * SKSiArrayPlane::GetSiChannel (int cobo, int asad, int aget, int chan)
Definition at line 1462 of file SKSiArrayPlane.cpp.
References FindSiChannelID(), and GetSiChannel().
GetSiChannel() [2/2]
LKSiChannel * SKSiArrayPlane::GetSiChannel (int idx)
Definition at line 1453 of file SKSiArrayPlane.cpp.
References fChannelArray.
Referenced by FillDataToHistEventDisplay1(), GetSiChannel(), and SetSiChannelData().
GetSiDetector() [1/2]
LKSiDetector * SKSiArrayPlane::GetSiDetector (int cobo, int asad, int aget, int chan)
Definition at line 1520 of file SKSiArrayPlane.cpp.
References FindSiDetectorID(), and GetSiDetector().
GetSiDetector() [2/2]
LKSiDetector * SKSiArrayPlane::GetSiDetector (int idx)
Definition at line 1513 of file SKSiArrayPlane.cpp.
References fDetectorArray.
Referenced by FindEPairDetectorID(), and GetSiDetector().
GetSiDetectorData()
LKSiDetector * SKSiArrayPlane::GetSiDetectorData (int idx)
Init()
bool SKSiArrayPlane::Init () virtual
Implementation recommanded. Init() method should implement pad information (id, position, neighbor) and add channel using AddChannel() or AddPad() method. All parameters should be configured such as axis-1,2,3, fPosition, fTbToLength from parameter container.
Reimplemented from LKEvePlane.
Definition at line 34 of file SKSiArrayPlane.cpp.
References LKParameterContainer::AddPar(), LKParameterContainer::CheckPar(), fChannelArray, LKEvePlane::fCtrlBinTextSize, fdEEPairMapping, fDetectorArray, fDetectorParName, fDetectorTypeArray, LKDetectorPlane::fDetName, fLayerYOffset, fLayerYScale, fMapCAACToChannelIndex, fMapCAACToDetectorIndex, fMappingFileName, fMaxDetectors, fMaxLayerIndex, fMaxPhi, fMinPhi, fNumAget, fNumAsad, fNumChan, fNumCobo, LKGear::fPar, fUserDrawingArrayIndex, fUserDrawingLeastNDraw, fUserDrawingName, fUserPhiScale, LKParameterContainer::GetParIndex(), LKDetectorPlane::GetPosition(), LKEvePlane::Init(), lk_error, lk_info, and strip.
Print()
void SKSiArrayPlane::Print (Option_t * option = "") const virtual
Reimplemented from LKEvePlane.
Definition at line 288 of file SKSiArrayPlane.cpp.
References fDetectorArray, lk_info, and Print().
Referenced by ClickedEventDisplay1(), and Print().
SetDataFromBranch()
bool SKSiArrayPlane::SetDataFromBranch () virtual
Implementation recommanded. Set waveform and hit data from input tree branches to pads.
Reimplemented from LKEvePlane.
Definition at line 1006 of file SKSiArrayPlane.cpp.
References LKEvePlane::fBranchIsSet, LKEvePlane::fHitArray, LKEvePlane::fRawDataArray, LKGear::fRun, fSiChannelArray, fSiHitArray, and LKEvePlane::fTrackArray.
SetSiChannelData()
bool SKSiArrayPlane::SetSiChannelData (LKSiChannel * siChannel, GETChannel * channel)
Definition at line 1472 of file SKSiArrayPlane.cpp.
References GETChannel::GetBuffer(), LKChannel::GetEnergy(), LKChannel::GetNoiseScale(), LKChannel::GetPedestal(), GetSiChannel(), LKChannel::GetTime(), and strip.
UpdateAll()
void SKSiArrayPlane::UpdateAll () virtual
Reimplemented from LKEvePlane.
Definition at line 859 of file SKSiArrayPlane.cpp.
References LKEvePlane::UpdateControlEvent1(), LKEvePlane::UpdateControlEvent2(), UpdateDataDisplays(), UpdateEventDisplay1(), UpdateJunctionOhmic(), and UpdateUserDrawing().
UpdateDataDisplays()
void SKSiArrayPlane::UpdateDataDisplays () virtual
Definition at line 869 of file SKSiArrayPlane.cpp.
References LKEvePlane::Clear(), LKEvePlane::Draw(), LKDetectorPlane::fCanvas, fHistControlDDPage, fNumDataDisplays, fNumDDX, fNumDDY, fNumGoodDrawings, fPadControlDDPage, fPadDataDisplayFull, fPadDataDisplaySmall, fPadDataDisplayThree, fPadDataDisplayTwo, fSelControlDDPage, fSelUDArray, fSelUDLeastNDraw, fUDGoodIndex, kUpdateDataDisplays, and LKEvePlane::UpdateFlag.
Referenced by ClickedControlDDPage(), UpdateAll(), and UpdateUserDrawing().
UpdateEventDisplay1()
void SKSiArrayPlane::UpdateEventDisplay1 () virtual
Reimplemented from LKEvePlane.
Definition at line 723 of file SKSiArrayPlane.cpp.
References LKEvePlane::Clear(), LKEvePlane::Draw(), fDetectorArray, LKEvePlane::fEventDisplayDrawOption, LKEvePlane::fGSelEventDisplay1, LKEvePlane::fHistEventDisplay1, LKEvePlane::fPadEventDisplay1, fSelJOID, LKEvePlane::kUpdateEventDisplay1, lk_info, LKEvePlane::UpdateFlag, and UpdateUserDrawing().
Referenced by ClickedJOSideDisplay(), and UpdateAll().
UpdateEventDisplay2()
void SKSiArrayPlane::UpdateEventDisplay2 () virtual
Reimplemented from LKEvePlane.
Definition at line 1002 of file SKSiArrayPlane.cpp.
UpdateJunctionOhmic()
void SKSiArrayPlane::UpdateJunctionOhmic () virtual
Definition at line 933 of file SKSiArrayPlane.cpp.
References LKEvePlane::Draw(), LKEvePlane::fAccumulateEvents, fDetectorArray, LKEvePlane::fGSelEventDisplay1, fGSelJOSideDisplay, fLayerYOffset, fLayerYScale, LKEvePlane::fPadEventDisplay1, fPadJOSideDisplay, fSelDetID, fSelJOID, fUserPhiScale, kUpdateJunctionOhmic, lk_info, SetPoint(), and LKEvePlane::UpdateFlag.
Referenced by ClickedEventDisplay1(), ClickedJOSideDisplay(), and UpdateAll().
UpdateUserDrawing()
void SKSiArrayPlane::UpdateUserDrawing () virtual
Definition at line 539 of file SKSiArrayPlane.cpp.
References LKEvePlane::Draw(), fHistCtrlUserDrawing, fNumDataDisplays, fNumDrawingsInArray, fNumGoodDrawings, fNumSelUDGroup, fNumUDPage, fPadCtrlUserDrawing, fSelControlDDPage, fSelDetID, fSelJOID, fSelUDArray, fSelUDArrayID, fSelUDBin, fSelUDLeastNDraw, fSelUDTab, fSignalUDBinChange, fSignalUDTabChange, fUDGoodIndex, fUserDrawingArrayCollection, fUserDrawingArrayIndex, fUserDrawingLeastNDraw, fUserDrawingName, kUpdateUserDrawing, UpdateDataDisplays(), and LKEvePlane::UpdateFlag.
Referenced by ClickedEventDisplay1(), ClickedJOSideDisplay(), ClickedUserDrawing(), GetHistUserDrawing(), UpdateAll(), and UpdateEventDisplay1().
Member Data Documentation
fArrayChannelDrawing
LKParameterContainer* SKSiArrayPlane::fArrayChannelDrawing = nullptr private
Definition at line 187 of file SKSiArrayPlane.h.
fArrayDetectorDrawing
LKParameterContainer* SKSiArrayPlane::fArrayDetectorDrawing = nullptr private
Definition at line 189 of file SKSiArrayPlane.h.
fArrayEventDrawing
LKParameterContainer* SKSiArrayPlane::fArrayEventDrawing = nullptr private
Definition at line 190 of file SKSiArrayPlane.h.
fArrayPairDrawing
LKParameterContainer* SKSiArrayPlane::fArrayPairDrawing = nullptr private
Definition at line 188 of file SKSiArrayPlane.h.
fBinCtrlCurrPage
int SKSiArrayPlane::fBinCtrlCurrPage protected
Definition at line 137 of file SKSiArrayPlane.h.
fBinCtrlNextPage
int SKSiArrayPlane::fBinCtrlNextPage protected
Definition at line 138 of file SKSiArrayPlane.h.
fBinCtrlPrevPage
int SKSiArrayPlane::fBinCtrlPrevPage protected
Definition at line 136 of file SKSiArrayPlane.h.
fChannelArray
TObjArray* SKSiArrayPlane::fChannelArray = nullptr protected
Definition at line 116 of file SKSiArrayPlane.h.
Referenced by GetSiChannel(), Init(), and SKSiArrayPlane().
fCountHistArray1
int SKSiArrayPlane::fCountHistArray1 = 0 private
Definition at line 175 of file SKSiArrayPlane.h.
fCountHistArray2
int SKSiArrayPlane::fCountHistArray2 = 0 private
Definition at line 176 of file SKSiArrayPlane.h.
fCtrlLabelOffset
double SKSiArrayPlane::fCtrlLabelOffset = 0.10 protected
Definition at line 165 of file SKSiArrayPlane.h.
fCurrentView
int SKSiArrayPlane::fCurrentView = 1 protected
Definition at line 96 of file SKSiArrayPlane.h.
Referenced by FillDataToHistEventDisplay1(), and Get3DEventPad().
fdEEPairMapping
int SKSiArrayPlane::fdEEPairMapping[40][2] private
Definition at line 194 of file SKSiArrayPlane.h.
Referenced by FindEPairDetectorID(), and Init().
fDetectorArray
TObjArray* SKSiArrayPlane::fDetectorArray = nullptr protected
Definition at line 115 of file SKSiArrayPlane.h.
Referenced by ClearFiredFlags(), ClickedEventDisplay1(), ClickedJOSideDisplay(), FillDataToHistEventDisplay1(), FireStrip(), GetFiredDetector(), GetHistEventDisplay1(), GetNumFiredDetectors(), GetNumSiDetectors(), GetSiDetector(), Init(), Print(), SKSiArrayPlane(), UpdateEventDisplay1(), and UpdateJunctionOhmic().
fDetectorParName
TString SKSiArrayPlane::fDetectorParName protected
Definition at line 86 of file SKSiArrayPlane.h.
Referenced by Init().
fDetectorTypeArray
LKParameterContainer SKSiArrayPlane::fDetectorTypeArray protected
Definition at line 117 of file SKSiArrayPlane.h.
Referenced by Init().
fFrameEventDisplay1
TH2* SKSiArrayPlane::fFrameEventDisplay1 = nullptr protected
Definition at line 119 of file SKSiArrayPlane.h.
fGSelJOSideDisplay
TGraph* SKSiArrayPlane::fGSelJOSideDisplay = nullptr protected
Definition at line 167 of file SKSiArrayPlane.h.
Referenced by ClickedJOSideDisplay(), SKSiArrayPlane(), and UpdateJunctionOhmic().
fHistArray1
TClonesArray* SKSiArrayPlane::fHistArray1 = nullptr private
Definition at line 177 of file SKSiArrayPlane.h.
fHistArray2
TClonesArray* SKSiArrayPlane::fHistArray2 = nullptr private
Definition at line 178 of file SKSiArrayPlane.h.
fHistControlDDPage
TH2D* SKSiArrayPlane::fHistControlDDPage = nullptr protected
Definition at line 146 of file SKSiArrayPlane.h.
Referenced by ClickedControlDDPage(), GetHistControlDDPage(), and UpdateDataDisplays().
fHistCtrlUserDrawing
TH2* SKSiArrayPlane::fHistCtrlUserDrawing = nullptr protected
Definition at line 127 of file SKSiArrayPlane.h.
Referenced by ClickedControlDDPage(), ClickedUserDrawing(), GetHistUserDrawing(), and UpdateUserDrawing().
fLayerYOffset
double SKSiArrayPlane::fLayerYOffset = 0.05 protected
Definition at line 109 of file SKSiArrayPlane.h.
Referenced by ClickedJOSideDisplay(), GetHistEventDisplay1(), Init(), and UpdateJunctionOhmic().
fLayerYScale
double SKSiArrayPlane::fLayerYScale = 100 protected
If histogram bin size is smaller than 1, mouse click position might not be pointing inside the bin since position is returned as integer. This parameter will increase resolution of histogram bin.
Definition at line 108 of file SKSiArrayPlane.h.
Referenced by ClickedJOSideDisplay(), GetHistEventDisplay1(), Init(), and UpdateJunctionOhmic().
fMapBinToDetector
int* SKSiArrayPlane::fMapBinToDetector protected
histogram bin to pad-id mapping
Definition at line 94 of file SKSiArrayPlane.h.
Referenced by FindPadIDFromHistEventDisplay1Bin(), and GetHistEventDisplay1().
fMapCAACToChannelIndex
int**** SKSiArrayPlane::fMapCAACToChannelIndex protected
[cobo][asad][aget][chan] to channel-index mapping
Definition at line 92 of file SKSiArrayPlane.h.
Referenced by FindPadID(), and Init().
fMapCAACToDetectorIndex
int**** SKSiArrayPlane::fMapCAACToDetectorIndex protected
[cobo][asad][aget][chan] to detector-index mapping
Definition at line 93 of file SKSiArrayPlane.h.
Referenced by FindSiDetectorID(), and Init().
fMappingFileName
TString SKSiArrayPlane::fMappingFileName protected
Definition at line 85 of file SKSiArrayPlane.h.
Referenced by Init().
fMaxDetectors
int SKSiArrayPlane::fMaxDetectors = 40 protected
Definition at line 120 of file SKSiArrayPlane.h.
Referenced by AddUserDrawings(), and Init().
fMaxLayerIndex
int SKSiArrayPlane::fMaxLayerIndex = -INT_MAX protected
Definition at line 102 of file SKSiArrayPlane.h.
Referenced by GetHistEventDisplay1(), and Init().
fMaxPhi
double SKSiArrayPlane::fMaxPhi = -DBL_MAX protected
Definition at line 104 of file SKSiArrayPlane.h.
Referenced by GetHistEventDisplay1(), and Init().
fMinPhi
double SKSiArrayPlane::fMinPhi = DBL_MAX protected
Definition at line 103 of file SKSiArrayPlane.h.
Referenced by GetHistEventDisplay1(), and Init().
fNumAget
int SKSiArrayPlane::fNumAget = 4 protected
Definition at line 89 of file SKSiArrayPlane.h.
Referenced by Init().
fNumArrayChannelDrawing
int SKSiArrayPlane::fNumArrayChannelDrawing = 0 private
Definition at line 183 of file SKSiArrayPlane.h.
fNumArrayDetectorDrawing
int SKSiArrayPlane::fNumArrayDetectorDrawing = 0 private
Definition at line 184 of file SKSiArrayPlane.h.
fNumArrayEventDrawing
int SKSiArrayPlane::fNumArrayEventDrawing = 0 private
Definition at line 186 of file SKSiArrayPlane.h.
fNumArrayPairDrawing
int SKSiArrayPlane::fNumArrayPairDrawing = 0 private
Definition at line 185 of file SKSiArrayPlane.h.
fNumAsad
int SKSiArrayPlane::fNumAsad = 4 protected
Definition at line 88 of file SKSiArrayPlane.h.
Referenced by Init().
fNumChan
int SKSiArrayPlane::fNumChan = 68 protected
Definition at line 90 of file SKSiArrayPlane.h.
Referenced by Init().
fNumCobo
int SKSiArrayPlane::fNumCobo = 6 protected
Definition at line 87 of file SKSiArrayPlane.h.
Referenced by Init().
fNumDataDisplays
int SKSiArrayPlane::fNumDataDisplays = fNumDDX*fNumDDY protected
Definition at line 144 of file SKSiArrayPlane.h.
Referenced by UpdateDataDisplays(), and UpdateUserDrawing().
fNumDDX
int SKSiArrayPlane::fNumDDX = 2 protected
Definition at line 142 of file SKSiArrayPlane.h.
Referenced by GetCanvas(), and UpdateDataDisplays().
fNumDDY
int SKSiArrayPlane::fNumDDY = 3 protected
Definition at line 143 of file SKSiArrayPlane.h.
Referenced by GetCanvas(), and UpdateDataDisplays().
fNumDrawingsInArray
int SKSiArrayPlane::fNumDrawingsInArray = 0 protected
Definition at line 153 of file SKSiArrayPlane.h.
Referenced by UpdateUserDrawing().
fNumGoodDrawings
int SKSiArrayPlane::fNumGoodDrawings = 0 protected
Definition at line 154 of file SKSiArrayPlane.h.
Referenced by UpdateDataDisplays(), and UpdateUserDrawing().
fNumSelUDGroup
int SKSiArrayPlane::fNumSelUDGroup = 0 protected
Definition at line 158 of file SKSiArrayPlane.h.
Referenced by UpdateUserDrawing().
fNumUDLabels
int SKSiArrayPlane::fNumUDLabels = 0 protected
Definition at line 151 of file SKSiArrayPlane.h.
Referenced by AddUserDrawings(), and ClickedUserDrawing().
fNumUDPage
int SKSiArrayPlane::fNumUDPage = 0 protected
Definition at line 147 of file SKSiArrayPlane.h.
Referenced by UpdateUserDrawing().
fNumUserDrawing
int SKSiArrayPlane::fNumUserDrawing = 0 protected
Definition at line 128 of file SKSiArrayPlane.h.
fPadControlDDPage
TPad* SKSiArrayPlane::fPadControlDDPage = nullptr protected
Definition at line 135 of file SKSiArrayPlane.h.
Referenced by ExecMouseClickEventOnPad(), GetCanvas(), and UpdateDataDisplays().
fPadCtrlUserDrawing
TPad* SKSiArrayPlane::fPadCtrlUserDrawing = nullptr protected
Definition at line 126 of file SKSiArrayPlane.h.
Referenced by ExecMouseClickEventOnPad(), GetCanvas(), and UpdateUserDrawing().
fPadDataDisplayFull
TPad* SKSiArrayPlane::fPadDataDisplayFull protected
Definition at line 139 of file SKSiArrayPlane.h.
Referenced by GetCanvas(), and UpdateDataDisplays().
fPadDataDisplaySmall
TPad* SKSiArrayPlane::fPadDataDisplaySmall[24] protected
Definition at line 145 of file SKSiArrayPlane.h.
Referenced by GetCanvas(), and UpdateDataDisplays().
fPadDataDisplayThree
TPad* SKSiArrayPlane::fPadDataDisplayThree[3] protected
Definition at line 141 of file SKSiArrayPlane.h.
Referenced by GetCanvas(), and UpdateDataDisplays().
fPadDataDisplayTwo
TPad* SKSiArrayPlane::fPadDataDisplayTwo[2] protected
Definition at line 140 of file SKSiArrayPlane.h.
Referenced by GetCanvas(), and UpdateDataDisplays().
fPadJOSideDisplay
TPad* SKSiArrayPlane::fPadJOSideDisplay[2] protected
Definition at line 122 of file SKSiArrayPlane.h.
Referenced by ExecMouseClickEventOnPad(), GetCanvas(), and UpdateJunctionOhmic().
fParUserDrawing
LKParameterContainer SKSiArrayPlane::fParUserDrawing protected
Definition at line 129 of file SKSiArrayPlane.h.
fPrevEventID
int SKSiArrayPlane::fPrevEventID = -1 protected
Definition at line 112 of file SKSiArrayPlane.h.
Referenced by FillDataToHistEventDisplay1().
fPrevEventID2
int SKSiArrayPlane::fPrevEventID2 = -1 protected
Definition at line 113 of file SKSiArrayPlane.h.
fSelControlDDPage
int SKSiArrayPlane::fSelControlDDPage = 0 protected
Definition at line 162 of file SKSiArrayPlane.h.
Referenced by ClickedControlDDPage(), UpdateDataDisplays(), and UpdateUserDrawing().
fSelDetID
int SKSiArrayPlane::fSelDetID = 0 protected
Definition at line 99 of file SKSiArrayPlane.h.
Referenced by ClickedEventDisplay1(), ClickedJOSideDisplay(), FillDataToHistEventDisplay1(), UpdateJunctionOhmic(), and UpdateUserDrawing().
fSelJOID
int SKSiArrayPlane::fSelJOID = -1 protected
Definition at line 100 of file SKSiArrayPlane.h.
Referenced by ClickedJOSideDisplay(), UpdateEventDisplay1(), UpdateJunctionOhmic(), and UpdateUserDrawing().
fSelUDArray
TObjArray* SKSiArrayPlane::fSelUDArray = nullptr protected
Definition at line 159 of file SKSiArrayPlane.h.
Referenced by UpdateDataDisplays(), and UpdateUserDrawing().
fSelUDArrayID
int SKSiArrayPlane::fSelUDArrayID = 0 protected
Definition at line 155 of file SKSiArrayPlane.h.
Referenced by UpdateUserDrawing().
fSelUDBin
int SKSiArrayPlane::fSelUDBin = -1 protected
Definition at line 150 of file SKSiArrayPlane.h.
Referenced by AddUserDrawings(), ClickedUserDrawing(), and UpdateUserDrawing().
fSelUDLeastNDraw
int SKSiArrayPlane::fSelUDLeastNDraw = 1 protected
Definition at line 156 of file SKSiArrayPlane.h.
Referenced by UpdateDataDisplays(), and UpdateUserDrawing().
fSelUDTab
int SKSiArrayPlane::fSelUDTab = 0 protected
Definition at line 149 of file SKSiArrayPlane.h.
Referenced by ClickedUserDrawing(), and UpdateUserDrawing().
fSiChannelArray
TClonesArray* SKSiArrayPlane::fSiChannelArray = nullptr private
Definition at line 180 of file SKSiArrayPlane.h.
Referenced by FillDataToHistEventDisplay1(), and SetDataFromBranch().
fSignalUDBinChange
bool SKSiArrayPlane::fSignalUDBinChange = true protected
Definition at line 161 of file SKSiArrayPlane.h.
Referenced by ClickedEventDisplay1(), ClickedJOSideDisplay(), ClickedUserDrawing(), ExecMouseClickEventOnPad(), FillDataToHistEventDisplay1(), and UpdateUserDrawing().
fSignalUDTabChange
bool SKSiArrayPlane::fSignalUDTabChange = true protected
Definition at line 160 of file SKSiArrayPlane.h.
Referenced by ClickedUserDrawing(), and UpdateUserDrawing().
fSiHitArray
TClonesArray* SKSiArrayPlane::fSiHitArray = nullptr private
Definition at line 181 of file SKSiArrayPlane.h.
Referenced by FillDataToHistEventDisplay1(), and SetDataFromBranch().
fThreshold
double SKSiArrayPlane::fThreshold = 300 protected
Definition at line 97 of file SKSiArrayPlane.h.
fUDGoodIndex
int SKSiArrayPlane::fUDGoodIndex[10][16] protected
Definition at line 152 of file SKSiArrayPlane.h.
Referenced by UpdateDataDisplays(), and UpdateUserDrawing().
fUserDrawingArrayCollection
TObjArray* SKSiArrayPlane::fUserDrawingArrayCollection = nullptr protected
Definition at line 130 of file SKSiArrayPlane.h.
Referenced by AddUserDrawings(), ExitEve(), SKSiArrayPlane(), and UpdateUserDrawing().
fUserDrawingArrayIndex
int**** SKSiArrayPlane::fUserDrawingArrayIndex protected
Definition at line 131 of file SKSiArrayPlane.h.
Referenced by AddUserDrawings(), Init(), and UpdateUserDrawing().
fUserDrawingLeastNDraw
int**** SKSiArrayPlane::fUserDrawingLeastNDraw protected
Definition at line 132 of file SKSiArrayPlane.h.
Referenced by AddUserDrawings(), Init(), and UpdateUserDrawing().
fUserDrawingName
TString SKSiArrayPlane::fUserDrawingName[4][7] protected
Definition at line 133 of file SKSiArrayPlane.h.
Referenced by AddUserDrawings(), ClickedUserDrawing(), Init(), and UpdateUserDrawing().
fUserPhiScale
double SKSiArrayPlane::fUserPhiScale = 1. private
Definition at line 192 of file SKSiArrayPlane.h.
Referenced by GetHistEventDisplay1(), Init(), and UpdateJunctionOhmic().
kUpdateDataDisplays
int SKSiArrayPlane::kUpdateDataDisplays = 7 protected
Definition at line 171 of file SKSiArrayPlane.h.
Referenced by UpdateDataDisplays().
kUpdateJunctionOhmic
int SKSiArrayPlane::kUpdateJunctionOhmic = 8 protected
Definition at line 172 of file SKSiArrayPlane.h.
Referenced by UpdateJunctionOhmic().
kUpdateUserDrawing
int SKSiArrayPlane::kUpdateUserDrawing = 6 protected
Definition at line 170 of file SKSiArrayPlane.h.
Referenced by UpdateUserDrawing().
The documentation for this class was generated from the following files:
SKSiArrayPlane.h
SKSiArrayPlane.cpp