LILAK: Json::Value Class Reference
Json::Value Class Reference
Represents a JSON value.
#include <json.h>
Classes
class Comments
class CZString
union ValueHolder
Public Types
using ArrayIndex = Json::ArrayIndex
using const_iterator = ValueConstIterator
using Int = Json::Int
using Int64 = Json::Int64
using iterator = ValueIterator
using LargestInt = Json::LargestInt
using LargestUInt = Json::LargestUInt
using Members = std::vector< String >
typedef std::map< CZString, Value > ObjectValues
using UInt = Json::UInt
using UInt64 = Json::UInt64
using value_type = std::string
Public Member Functions
Value & append (const Value &value)
Append value to array at the end.
Value & append (Value &&value)
template<>
bool as () const
template<>
Int as () const
template<>
UInt as () const
template<>
Int64 as () const
template<>
UInt64 as () const
template<>
double as () const
template<>
String as () const
template<>
float as () const
template<>
const char * as () const
template<typename T >
T as () const JSONCPP_TEMPLATE_DELETE
The as<T> and is<T> member function templates and specializations.
bool asBool () const
const char * asCString () const
Embedded zeroes could cause you trouble!
double asDouble () const
float asFloat () const
Int asInt () const
Int64 asInt64 () const
LargestInt asLargestInt () const
LargestUInt asLargestUInt () const
String asString () const
Embedded zeroes are possible.
UInt asUInt () const
UInt64 asUInt64 () const
iterator begin ()
const_iterator begin () const
void clear ()
int compare (const Value &other) const
void copy (const Value &other)
copy everything.
void copyPayload (const Value &other)
copy values but leave comments and source offsets in place.
Value * demand (char const *begin, char const *end)
bool empty () const
Return true if empty array, empty object, or null; otherwise, false.
iterator end ()
const_iterator end () const
Value const * find (char const *begin, char const *end) const
Value get (ArrayIndex index, const Value &defaultValue) const
Value get (const char *begin, const char *end, const Value &defaultValue) const
Value get (const char *key, const Value &defaultValue) const
Value get (const String &key, const Value &defaultValue) const
String getComment (CommentPlacement placement) const
Include delimiters and embedded newlines.
Members getMemberNames () const
Return a list of the member names.
ptrdiff_t getOffsetLimit () const
ptrdiff_t getOffsetStart () const
bool getString (char const **begin, char const **end) const
bool hasComment (CommentPlacement placement) const
bool insert (ArrayIndex index, const Value &newValue)
Insert value in array at specific index.
bool insert (ArrayIndex index, Value &&newValue)
template<>
bool is () const
template<>
bool is () const
template<>
bool is () const
template<>
bool is () const
template<>
bool is () const
template<>
bool is () const
template<>
bool is () const
template<typename T >
bool is () const JSONCPP_TEMPLATE_DELETE
bool isArray () const
bool isBool () const
bool isConvertibleTo (ValueType other) const
bool isDouble () const
bool isInt () const
bool isInt64 () const
bool isIntegral () const
bool isMember (const char *begin, const char *end) const
Same as isMember(String const& key)const.
bool isMember (const char *key) const
bool isMember (const String &key) const
bool isNull () const
bool isNumeric () const
bool isObject () const
bool isString () const
bool isUInt () const
bool isUInt64 () const
bool isValidIndex (ArrayIndex index) const
Return true if index < size().
operator bool () const
Return !isNull()
bool operator!= (const Value &other) const
bool operator< (const Value &other) const
Compare payload only, not comments etc.
bool operator<= (const Value &other) const
Value & operator= (const Value &other)
Value & operator= (Value &&other) noexcept
bool operator== (const Value &other) const
bool operator> (const Value &other) const
bool operator>= (const Value &other) const
Value & operator[] (const char *key)
const Value & operator[] (const char *key) const
Value & operator[] (const StaticString &key)
Access an object value by name, create a null member if it does not exist.
Value & operator[] (const String &key)
const Value & operator[] (const String &key) const
bool removeIndex (ArrayIndex index, Value *removed)
Remove the indexed array element.
bool removeMember (const char *begin, const char *end, Value *removed)
Same as removeMember(String const& key, Value* removed)
void removeMember (const char *key)
Remove and return the named member.
bool removeMember (const char *key, Value *removed)
void removeMember (const String &key)
bool removeMember (String const &key, Value *removed)
Remove the named map member.
void resize (ArrayIndex newSize)
void setComment (const char *comment, CommentPlacement placement)
void setComment (const char *comment, size_t len, CommentPlacement placement)
Comments must be //... or /* ... *‍/.
void setComment (String comment, CommentPlacement placement)
Comments must be //... or /* ... *‍/.
void setOffsetLimit (ptrdiff_t limit)
void setOffsetStart (ptrdiff_t start)
ArrayIndex size () const
Number of values in array or object.
void swap (Value &other)
Swap everything.
void swapPayload (Value &other)
Swap values but leave comments and source offsets in place.
String toStyledString () const
ValueType type () const
Value (bool value)
Value (const char *begin, const char *end)
Copy all, incl zeroes.
Value (const char *value)
Copy til first 0. (NULL causes to seg-fault.)
Value (const StaticString &value)
Constructs a value from a static string.
Value (const String &value)
Value (const Value &other)
Value (double value)
Value (Int value)
Value (Int64 value)
Value (std::nullptr_t ptr)=delete
Value (UInt value)
Value (UInt64 value)
Value (Value &&other) noexcept
Value (ValueType type=nullValue)
Create a default Value of the given type.
~Value ()
Value & operator[] (ArrayIndex index)
Value & operator[] (int index)
const Value & operator[] (ArrayIndex index) const
const Value & operator[] (int index) const
Static Public Member Functions
static Value const & nullSingleton ()
Static Public Attributes
static constexpr UInt defaultRealPrecision = 17
Default precision for real value for string representation.
static constexpr Int maxInt = Int(UInt(-1) / 2)
Maximum signed int value that can be stored in a Json::Value.
static constexpr Int64 maxInt64 = Int64(UInt64(-1) / 2)
Maximum signed 64 bits int value that can be stored in a Json::Value.
static constexpr LargestInt maxLargestInt = LargestInt(LargestUInt(-1) / 2)
Maximum signed integer value that can be stored in a Json::Value.
static constexpr LargestUInt maxLargestUInt = LargestUInt(-1)
Maximum unsigned integer value that can be stored in a Json::Value.
static constexpr UInt maxUInt = UInt(-1)
Maximum unsigned int value that can be stored in a Json::Value.
static constexpr UInt64 maxUInt64 = UInt64(-1)
Maximum unsigned 64 bits int value that can be stored in a Json::Value.
static constexpr double maxUInt64AsDouble = 18446744073709551615.0
static constexpr Int minInt = Int(~(UInt(-1) / 2))
Minimum signed int value that can be stored in a Json::Value.
static constexpr Int64 minInt64 = Int64(~(UInt64(-1) / 2))
Minimum signed 64 bits int value that can be stored in a Json::Value.
static constexpr LargestInt minLargestInt
Minimum signed integer value that can be stored in a Json::Value.
static const Value & null = Value::nullSingleton()
static const Value & nullRef = Value::nullSingleton()
Private Member Functions
void dupMeta (const Value &other)
void dupPayload (const Value &other)
void initBasic (ValueType type, bool allocated=false)
bool isAllocated () const
void releasePayload ()
Value & resolveReference (const char *key)
Value & resolveReference (const char *key, const char *end)
void setIsAllocated (bool v)
void setType (ValueType v)
Private Attributes
struct {
unsigned int allocated_: 1
unsigned int value_type_: 8
} bits_
Comments comments_
ptrdiff_t limit_
ptrdiff_t start_
union Json::Value::ValueHolder value_
Friends
class ValueIteratorBase
Detailed Description
Represents a JSON value.
This class is a discriminated union wrapper that can represents a:
signed integer [range: Value::minInt - Value::maxInt]
unsigned integer (range: 0 - Value::maxUInt)
double
UTF-8 string
boolean
'null'
an ordered list of Value
collection of name/value pairs (javascript object)
The type of the held value is represented by a ValueType and can be obtained using type().
Values of an objectValue or arrayValue can be accessed using operator[]() methods. Non-const methods will automatically create the a nullValue element if it does not exist. The sequence of an arrayValue will be automatically resized and initialized with nullValue. resize() can be used to enlarge or truncate an arrayValue.
The get() methods can be used to obtain default value in the case the required element does not exist.
It is possible to iterate over the list of member keys of an object using the getMemberNames() method.
Note
Value string-length fit in size_t, but keys must be < 2^30. (The reason is an implementation detail.) A #CharReader will raise an exception if a bound is exceeded to avoid security holes in your app, but the Value API does not check bounds. That is the responsibility of the caller.
Definition at line 720 of file json.h.
Member Typedef Documentation
ArrayIndex
using Json::Value::ArrayIndex = Json::ArrayIndex
Definition at line 735 of file json.h.
const_iterator
using Json::Value::const_iterator = ValueConstIterator
Definition at line 726 of file json.h.
Int
using Json::Value::Int = Json::Int
Definition at line 728 of file json.h.
Int64
using Json::Value::Int64 = Json::Int64
Definition at line 731 of file json.h.
iterator
using Json::Value::iterator = ValueIterator
Definition at line 725 of file json.h.
LargestInt
using Json::Value::LargestInt = Json::LargestInt
Definition at line 733 of file json.h.
LargestUInt
using Json::Value::LargestUInt = Json::LargestUInt
Definition at line 734 of file json.h.
Members
using Json::Value::Members = std::vector<String>
Definition at line 724 of file json.h.
ObjectValues
typedef std::map<CZString, Value> Json::Value::ObjectValues
Definition at line 822 of file json.h.
UInt
using Json::Value::UInt = Json::UInt
Definition at line 727 of file json.h.
UInt64
using Json::Value::UInt64 = Json::UInt64
Definition at line 730 of file json.h.
value_type
using Json::Value::value_type = std::string
Definition at line 738 of file json.h.
Constructor & Destructor Documentation
Value() [1/14]
Json::Value::Value (ValueType type = nullValue)
Create a default Value of the given type.
This is a very useful constructor. To create an empty array, pass arrayValue. To create an empty object, pass objectValue. Another Value can then be set to this one by assignment. This is useful since clear() and resize() will not alter types.
Examples:
Json::Value null_value; // null
Json::Value arr_value(Json::arrayValue); // []
Json::Value obj_value(Json::objectValue); // {}
Definition at line 2773 of file jsoncpp.cpp.
References Json::arrayValue, Json::Value::ValueHolder::bool_, Json::booleanValue, initBasic(), Json::Value::ValueHolder::int_, Json::intValue, JSON_ASSERT_UNREACHABLE, Json::Value::ValueHolder::map_, Json::nullValue, Json::objectValue, Json::Value::ValueHolder::real_, Json::realValue, Json::Value::ValueHolder::string_, Json::stringValue, type(), Json::uintValue, and value_.
Value() [2/14]
Json::Value::Value (Int value)
Definition at line 2802 of file jsoncpp.cpp.
References initBasic(), Json::Value::ValueHolder::int_, Json::intValue, and value_.
Value() [3/14]
Json::Value::Value (UInt value)
Definition at line 2807 of file jsoncpp.cpp.
References initBasic(), Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
Value() [4/14]
Json::Value::Value (Int64 value)
Definition at line 2812 of file jsoncpp.cpp.
References initBasic(), Json::Value::ValueHolder::int_, Json::intValue, and value_.
Value() [5/14]
Json::Value::Value (UInt64 value)
Definition at line 2816 of file jsoncpp.cpp.
References initBasic(), Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
Value() [6/14]
Json::Value::Value (double value)
Definition at line 2822 of file jsoncpp.cpp.
References initBasic(), Json::Value::ValueHolder::real_, Json::realValue, and value_.
Value() [7/14]
Json::Value::Value (const char * value)
Copy til first 0. (NULL causes to seg-fault.)
Definition at line 2827 of file jsoncpp.cpp.
References Json::duplicateAndPrefixStringValue(), initBasic(), JSON_ASSERT_MESSAGE, Json::Value::ValueHolder::string_, Json::stringValue, and value_.
Value() [8/14]
Json::Value::Value (const char * begin, const char * end)
Copy all, incl zeroes.
Definition at line 2835 of file jsoncpp.cpp.
References begin(), Json::duplicateAndPrefixStringValue(), end(), initBasic(), Json::Value::ValueHolder::string_, Json::stringValue, and value_.
Value() [9/14]
Json::Value::Value (const StaticString & value)
Constructs a value from a static string.
Like other value string constructor but do not duplicate the string for internal storage. The given string must remain alive after the call to this constructor.
Note
This works only for null-terminated strings. (We cannot change the size of this class, so we have nowhere to store the length, which might be computed later for various operations.)
Example of usage:
static StaticString foo("some text");
Json::Value aValue(foo);
Definition at line 2847 of file jsoncpp.cpp.
References Json::StaticString::c_str(), initBasic(), Json::Value::ValueHolder::string_, Json::stringValue, and value_.
Value() [10/14]
Json::Value::Value (const String & value)
Definition at line 2841 of file jsoncpp.cpp.
References Json::duplicateAndPrefixStringValue(), initBasic(), Json::Value::ValueHolder::string_, Json::stringValue, and value_.
Value() [11/14]
Json::Value::Value (bool value)
Definition at line 2852 of file jsoncpp.cpp.
References Json::Value::ValueHolder::bool_, Json::booleanValue, initBasic(), and value_.
Value() [12/14]
Json::Value::Value (std::nullptr_t ptr) delete
References Json::operator!=(), Json::operator==(), and Json::swap().
Value() [13/14]
Json::Value::Value (const Value & other)
Definition at line 2857 of file jsoncpp.cpp.
References dupMeta(), and dupPayload().
Value() [14/14]
Json::Value::Value (Value && other) noexcept
Definition at line 2862 of file jsoncpp.cpp.
References initBasic(), Json::nullValue, and swap().
~Value()
Json::Value::~Value ()
Definition at line 2867 of file jsoncpp.cpp.
References releasePayload(), Json::Value::ValueHolder::uint_, and value_.
Member Function Documentation
append() [1/2]
Value & Json::Value::append (const Value & value)
Append value to array at the end.
Equivalent to jsonvalue[jsonvalue.size()] = value;
Definition at line 3552 of file jsoncpp.cpp.
References append().
Referenced by append().
append() [2/2]
Value & Json::Value::append (Value && value)
Definition at line 3554 of file jsoncpp.cpp.
References Json::arrayValue, JSON_ASSERT_MESSAGE, Json::Value::ValueHolder::map_, Json::nullValue, size(), type(), and value_.
as() [1/10]
template<> bool Json::Value::as () const inline
Definition at line 1184 of file json.h.
as() [2/10]
template<> Int Json::Value::as () const inline
Definition at line 1187 of file json.h.
as() [3/10]
template<> UInt Json::Value::as () const inline
Definition at line 1190 of file json.h.
as() [4/10]
template<> Int64 Json::Value::as () const inline
Definition at line 1194 of file json.h.
as() [5/10]
template<> UInt64 Json::Value::as () const inline
Definition at line 1197 of file json.h.
as() [6/10]
template<> double Json::Value::as () const inline
Definition at line 1201 of file json.h.
as() [7/10]
template<> String Json::Value::as () const inline
Definition at line 1204 of file json.h.
as() [8/10]
template<> float Json::Value::as () const inline
These as specializations are type conversions, and do not have a corresponding is.
Definition at line 1209 of file json.h.
as() [9/10]
template<> const char * Json::Value::as () const inline
Definition at line 1210 of file json.h.
as() [10/10]
template<typename T > T Json::Value::as () const
The as<T> and is<T> member function templates and specializations.
asBool()
bool Json::Value::asBool () const
Definition at line 3230 of file jsoncpp.cpp.
References Json::Value::ValueHolder::bool_, Json::booleanValue, Json::Value::ValueHolder::int_, Json::intValue, JSON_FAIL_MESSAGE, Json::nullValue, Json::Value::ValueHolder::real_, Json::realValue, type(), Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
Referenced by Json::CharReaderBuilder::newCharReader(), Json::StreamWriterBuilder::newStreamWriter(), Json::FastWriter::writeValue(), Json::StyledWriter::writeValue(), Json::StyledStreamWriter::writeValue(), and Json::BuiltStyledStreamWriter::writeValue().
asCString()
const char * Json::Value::asCString () const
Embedded zeroes could cause you trouble!
Definition at line 3016 of file jsoncpp.cpp.
References Json::decodePrefixedString(), isAllocated(), JSON_ASSERT_MESSAGE, Json::Value::ValueHolder::string_, Json::stringValue, type(), and value_.
asDouble()
double Json::Value::asDouble () const
Definition at line 3185 of file jsoncpp.cpp.
References Json::Value::ValueHolder::bool_, Json::booleanValue, Json::Value::ValueHolder::int_, Json::intValue, JSON_FAIL_MESSAGE, Json::nullValue, Json::Value::ValueHolder::real_, Json::realValue, type(), Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
Referenced by isConvertibleTo(), Json::FastWriter::writeValue(), Json::StyledWriter::writeValue(), Json::StyledStreamWriter::writeValue(), and Json::BuiltStyledStreamWriter::writeValue().
asFloat()
float Json::Value::asFloat () const
Definition at line 3207 of file jsoncpp.cpp.
References Json::Value::ValueHolder::bool_, Json::booleanValue, Json::Value::ValueHolder::int_, Json::intValue, JSON_FAIL_MESSAGE, Json::nullValue, Json::Value::ValueHolder::real_, Json::realValue, type(), Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
asInt()
Value::Int Json::Value::asInt () const
Definition at line 3080 of file jsoncpp.cpp.
References Json::Value::ValueHolder::bool_, Json::booleanValue, Json::InRange(), Json::Value::ValueHolder::int_, Json::intValue, isInt(), JSON_ASSERT_MESSAGE, JSON_FAIL_MESSAGE, maxInt, minInt, Json::nullValue, Json::Value::ValueHolder::real_, Json::realValue, type(), Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
Referenced by asLargestInt().
asInt64()
Value::Int64 Json::Value::asInt64 () const
Definition at line 3126 of file jsoncpp.cpp.
References Json::Value::ValueHolder::bool_, Json::booleanValue, Json::InRange(), Json::Value::ValueHolder::int_, Json::intValue, isInt64(), JSON_ASSERT_MESSAGE, JSON_FAIL_MESSAGE, maxInt64, minInt64, Json::nullValue, Json::Value::ValueHolder::real_, Json::realValue, type(), Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
Referenced by asLargestInt().
asLargestInt()
LargestInt Json::Value::asLargestInt () const
Definition at line 3169 of file jsoncpp.cpp.
References asInt(), and asInt64().
Referenced by Json::FastWriter::writeValue(), Json::StyledWriter::writeValue(), Json::StyledStreamWriter::writeValue(), and Json::BuiltStyledStreamWriter::writeValue().
asLargestUInt()
LargestUInt Json::Value::asLargestUInt () const
Definition at line 3177 of file jsoncpp.cpp.
References asUInt(), and asUInt64().
Referenced by Json::FastWriter::writeValue(), Json::StyledWriter::writeValue(), Json::StyledStreamWriter::writeValue(), and Json::BuiltStyledStreamWriter::writeValue().
asString()
String Json::Value::asString () const
Embedded zeroes are possible.
Definition at line 3054 of file jsoncpp.cpp.
References Json::Value::ValueHolder::bool_, Json::booleanValue, Json::decodePrefixedString(), Json::Value::ValueHolder::int_, Json::intValue, isAllocated(), JSON_FAIL_MESSAGE, Json::nullValue, Json::Value::ValueHolder::real_, Json::realValue, Json::Value::ValueHolder::string_, Json::stringValue, type(), Json::Value::ValueHolder::uint_, Json::uintValue, value_, and Json::valueToString().
Referenced by isConvertibleTo(), Json::StreamWriterBuilder::newStreamWriter(), Json::Reader::readObject(), and Json::OurReader::readObject().
asUInt()
Value::UInt Json::Value::asUInt () const
Definition at line 3102 of file jsoncpp.cpp.
References Json::Value::ValueHolder::bool_, Json::booleanValue, Json::InRange(), Json::Value::ValueHolder::int_, Json::intValue, isUInt(), JSON_ASSERT_MESSAGE, JSON_FAIL_MESSAGE, maxUInt, Json::nullValue, Json::Value::ValueHolder::real_, Json::realValue, type(), Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
Referenced by asLargestUInt(), Json::CharReaderBuilder::newCharReader(), and Json::StreamWriterBuilder::newStreamWriter().
asUInt64()
Value::UInt64 Json::Value::asUInt64 () const
Definition at line 3147 of file jsoncpp.cpp.
References Json::Value::ValueHolder::bool_, Json::booleanValue, Json::InRange(), Json::Value::ValueHolder::int_, Json::intValue, isUInt64(), JSON_ASSERT_MESSAGE, JSON_FAIL_MESSAGE, maxUInt64, Json::nullValue, Json::Value::ValueHolder::real_, Json::realValue, type(), Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
Referenced by asLargestUInt().
begin() [1/2]
Value::iterator Json::Value::begin ()
Definition at line 3898 of file jsoncpp.cpp.
References Json::arrayValue, Json::Value::ValueHolder::map_, Json::objectValue, type(), and value_.
begin() [2/2]
Value::const_iterator Json::Value::begin () const
Definition at line 3872 of file jsoncpp.cpp.
References Json::arrayValue, Json::Value::ValueHolder::map_, Json::objectValue, type(), and value_.
Referenced by demand(), find(), get(), getString(), isMember(), removeMember(), Json::CharReaderBuilder::validate(), Json::StreamWriterBuilder::validate(), and Value().
clear()
void Json::Value::clear ()
Remove all object members and array elements.
Precondition
type() is arrayValue, objectValue, or nullValue
Postcondition
type() is unchanged
Definition at line 3316 of file jsoncpp.cpp.
References Json::arrayValue, JSON_ASSERT_MESSAGE, limit_, Json::Value::ValueHolder::map_, Json::nullValue, Json::objectValue, start_, type(), and value_.
Referenced by resize().
compare()
int Json::Value::compare (const Value & other) const
Definition at line 2908 of file jsoncpp.cpp.
copy()
void Json::Value::copy (const Value & other)
copy everything.
Definition at line 2899 of file jsoncpp.cpp.
References copyPayload(), and dupMeta().
copyPayload()
void Json::Value::copyPayload (const Value & other)
copy values but leave comments and source offsets in place.
Definition at line 2887 of file jsoncpp.cpp.
References dupPayload(), and releasePayload().
Referenced by copy().
demand()
Value * Json::Value::demand (char const * begin, char const * end)
Most general and efficient version of object-mutators.
Note
As stated elsewhere, behavior is undefined if (end-begin) >= 2^30
Returns
non-zero, but JSON_ASSERT if this is neither object nor nullValue.
Definition at line 3521 of file jsoncpp.cpp.
References begin(), end(), JSON_ASSERT_MESSAGE, Json::nullValue, Json::objectValue, resolveReference(), and type().
dupMeta()
void Json::Value::dupMeta (const Value & other) private
Definition at line 3455 of file jsoncpp.cpp.
References comments_, limit_, and start_.
Referenced by copy(), and Value().
dupPayload()
void Json::Value::dupPayload (const Value & other) private
Definition at line 3402 of file jsoncpp.cpp.
References Json::arrayValue, Json::booleanValue, Json::decodePrefixedString(), Json::duplicateAndPrefixStringValue(), Json::intValue, isAllocated(), JSON_ASSERT_UNREACHABLE, Json::Value::ValueHolder::map_, Json::nullValue, Json::objectValue, Json::realValue, setIsAllocated(), setType(), Json::Value::ValueHolder::string_, Json::stringValue, type(), Json::uintValue, and value_.
Referenced by copyPayload(), and Value().
empty()
bool Json::Value::empty () const
Return true if empty array, empty object, or null; otherwise, false.
Definition at line 3308 of file jsoncpp.cpp.
References isArray(), isNull(), isObject(), and size().
Referenced by Json::StyledWriter::isMultilineArray(), Json::StyledStreamWriter::isMultilineArray(), Json::BuiltStyledStreamWriter::isMultilineArray(), Json::CharReaderBuilder::validate(), and Json::StreamWriterBuilder::validate().
end() [1/2]
Value::iterator Json::Value::end ()
Definition at line 3911 of file jsoncpp.cpp.
References Json::arrayValue, Json::Value::ValueHolder::map_, Json::objectValue, type(), and value_.
end() [2/2]
Value::const_iterator Json::Value::end () const
Definition at line 3885 of file jsoncpp.cpp.
References Json::arrayValue, Json::Value::ValueHolder::map_, Json::objectValue, type(), and value_.
Referenced by demand(), find(), get(), getString(), isMember(), removeMember(), resolveReference(), Json::CharReaderBuilder::validate(), Json::StreamWriterBuilder::validate(), and Value().
find()
Value const * Json::Value::find (char const * begin, char const * end) const
Most general and efficient version of isMember()const, get()const, and operator[]const
Note
As stated elsewhere, behavior is undefined if (end-begin) >= 2^30
Definition at line 3508 of file jsoncpp.cpp.
References begin(), end(), JSON_ASSERT_MESSAGE, Json::Value::ValueHolder::map_, Json::Value::CZString::noDuplication, Json::nullValue, Json::objectValue, type(), and value_.
Referenced by get(), isMember(), operator[](), and operator[]().
get() [1/4]
Value Json::Value::get (ArrayIndex index, const Value & defaultValue) const
If the array contains at least index+1 elements, returns the element value, otherwise returns defaultValue.
Definition at line 3501 of file jsoncpp.cpp.
References nullSingleton().
Referenced by get(), and get().
get() [2/4]
Value Json::Value::get (const char * begin, const char * end, const Value & defaultValue) const
Return the member named key if it exist, defaultValue otherwise.
Note
deep copy
key may contain embedded nulls.
Definition at line 3581 of file jsoncpp.cpp.
References begin(), end(), and find().
get() [3/4]
Value Json::Value::get (const char * key, const Value & defaultValue) const
Return the member named key if it exist, defaultValue otherwise.
Note
deep copy
Definition at line 3586 of file jsoncpp.cpp.
References get().
get() [4/4]
Value Json::Value::get (const String & key, const Value & defaultValue) const
Return the member named key if it exist, defaultValue otherwise.
Note
deep copy
Parameters
key may contain embedded nulls.
Definition at line 3589 of file jsoncpp.cpp.
References get().
getComment()
String Json::Value::getComment (CommentPlacement placement) const
Include delimiters and embedded newlines.
Definition at line 3850 of file jsoncpp.cpp.
References comments_, and Json::Value::Comments::get().
Referenced by Json::StyledWriter::writeCommentAfterValueOnSameLine(), Json::StyledStreamWriter::writeCommentAfterValueOnSameLine(), Json::BuiltStyledStreamWriter::writeCommentAfterValueOnSameLine(), Json::StyledWriter::writeCommentBeforeValue(), Json::StyledStreamWriter::writeCommentBeforeValue(), and Json::BuiltStyledStreamWriter::writeCommentBeforeValue().
getMemberNames()
Value::Members Json::Value::getMemberNames () const
Return a list of the member names.
If null, return an empty list.
Precondition
type() is objectValue or nullValue
Postcondition
if type() was nullValue, it remains nullValue
Definition at line 3659 of file jsoncpp.cpp.
References JSON_ASSERT_MESSAGE, Json::Value::ValueHolder::map_, Json::nullValue, Json::objectValue, type(), and value_.
Referenced by Json::FastWriter::writeValue(), Json::StyledWriter::writeValue(), Json::StyledStreamWriter::writeValue(), and Json::BuiltStyledStreamWriter::writeValue().
getOffsetLimit()
ptrdiff_t Json::Value::getOffsetLimit () const
Definition at line 3860 of file jsoncpp.cpp.
References limit_.
Referenced by Json::Reader::pushError(), and Json::Reader::pushError().
getOffsetStart()
ptrdiff_t Json::Value::getOffsetStart () const
Definition at line 3858 of file jsoncpp.cpp.
References start_.
Referenced by Json::Reader::pushError(), and Json::Reader::pushError().
getString()
bool Json::Value::getString (char const ** begin, char const ** end) const
Get raw char* of string-value.
Returns
false if !string. (Seg-fault if str or end are NULL.)
Definition at line 3042 of file jsoncpp.cpp.
References begin(), Json::decodePrefixedString(), end(), isAllocated(), Json::Value::ValueHolder::string_, Json::stringValue, type(), and value_.
Referenced by Json::FastWriter::writeValue(), Json::StyledWriter::writeValue(), Json::StyledStreamWriter::writeValue(), and Json::BuiltStyledStreamWriter::writeValue().
hasComment()
bool Json::Value::hasComment (CommentPlacement placement) const
Definition at line 3846 of file jsoncpp.cpp.
References comments_, and Json::Value::Comments::has().
Referenced by Json::StyledWriter::hasCommentForValue(), Json::StyledStreamWriter::hasCommentForValue(), Json::BuiltStyledStreamWriter::hasCommentForValue(), toStyledString(), Json::StyledWriter::writeCommentAfterValueOnSameLine(), Json::StyledStreamWriter::writeCommentAfterValueOnSameLine(), Json::BuiltStyledStreamWriter::writeCommentAfterValueOnSameLine(), Json::StyledWriter::writeCommentBeforeValue(), Json::StyledStreamWriter::writeCommentBeforeValue(), and Json::BuiltStyledStreamWriter::writeCommentBeforeValue().
initBasic()
void Json::Value::initBasic (ValueType type, bool allocated = false) private
Definition at line 3394 of file jsoncpp.cpp.
References comments_, limit_, setIsAllocated(), setType(), start_, and type().
Referenced by Value(), Value(), Value(), Value(), Value(), Value(), Value(), Value(), Value(), Value(), Value(), and Value().
insert() [1/2]
bool Json::Value::insert (ArrayIndex index, const Value & newValue)
Insert value in array at specific index.
Definition at line 3563 of file jsoncpp.cpp.
References insert().
Referenced by insert().
insert() [2/2]
bool Json::Value::insert (ArrayIndex index, Value && newValue)
Definition at line 3567 of file jsoncpp.cpp.
References Json::arrayValue, JSON_ASSERT_MESSAGE, Json::nullValue, size(), and type().
is() [1/8]
template<> bool Json::Value::is () const inline
Definition at line 1185 of file json.h.
is() [2/8]
template<> bool Json::Value::is () const inline
Definition at line 1188 of file json.h.
is() [3/8]
template<> bool Json::Value::is () const inline
Definition at line 1191 of file json.h.
is() [4/8]
template<> bool Json::Value::is () const inline
Definition at line 1195 of file json.h.
is() [5/8]
template<> bool Json::Value::is () const inline
Definition at line 1198 of file json.h.
is() [6/8]
template<> bool Json::Value::is () const inline
Definition at line 1202 of file json.h.
is() [7/8]
template<> bool Json::Value::is () const inline
Definition at line 1205 of file json.h.
is() [8/8]
template<typename T > bool Json::Value::is () const
isAllocated()
bool Json::Value::isAllocated () const inline private
Definition at line 1125 of file json.h.
Referenced by asCString(), asString(), dupPayload(), getString(), operator<(), operator==(), and releasePayload().
isArray()
bool Json::Value::isArray () const
Definition at line 3796 of file jsoncpp.cpp.
References Json::arrayValue, and type().
Referenced by empty(), Json::StyledWriter::isMultilineArray(), Json::StyledStreamWriter::isMultilineArray(), Json::BuiltStyledStreamWriter::isMultilineArray(), Json::Path::make(), Json::Reader::parse(), Json::OurReader::parse(), Json::Path::resolve(), and Json::Path::resolve().
isBool()
bool Json::Value::isBool () const
Definition at line 3682 of file jsoncpp.cpp.
References Json::booleanValue, and type().
isConvertibleTo()
bool Json::Value::isConvertibleTo (ValueType other) const
Definition at line 3251 of file jsoncpp.cpp.
References Json::arrayValue, asDouble(), asString(), Json::Value::ValueHolder::bool_, Json::booleanValue, Json::InRange(), Json::intValue, isInt(), isNumeric(), isUInt(), JSON_ASSERT_UNREACHABLE, Json::Value::ValueHolder::map_, maxInt, maxUInt, minInt, Json::nullValue, Json::objectValue, Json::Value::ValueHolder::real_, Json::realValue, Json::stringValue, type(), Json::uintValue, and value_.
isDouble()
bool Json::Value::isDouble () const
Definition at line 3788 of file jsoncpp.cpp.
References Json::intValue, Json::realValue, type(), and Json::uintValue.
Referenced by isNumeric().
isInt()
bool Json::Value::isInt () const
Definition at line 3684 of file jsoncpp.cpp.
References Json::Value::ValueHolder::int_, Json::intValue, Json::IsIntegral(), maxInt, minInt, Json::Value::ValueHolder::real_, Json::realValue, type(), Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
Referenced by asInt(), and isConvertibleTo().
isInt64()
bool Json::Value::isInt64 () const
Definition at line 3726 of file jsoncpp.cpp.
References Json::intValue, Json::IsIntegral(), maxInt64, minInt64, Json::Value::ValueHolder::real_, Json::realValue, type(), Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
Referenced by asInt64().
isIntegral()
bool Json::Value::isIntegral () const
Definition at line 3766 of file jsoncpp.cpp.
References Json::intValue, Json::IsIntegral(), maxUInt, maxUInt64AsDouble, minInt, minInt64, Json::Value::ValueHolder::real_, Json::realValue, type(), Json::uintValue, and value_.
isMember() [1/3]
bool Json::Value::isMember (const char * begin, const char * end) const
Same as isMember(String const& key)const.
Definition at line 3648 of file jsoncpp.cpp.
References begin(), end(), and find().
isMember() [2/3]
bool Json::Value::isMember (const char * key) const
Return true if the object has a member named key.
Note
'key' must be null-terminated.
Definition at line 3652 of file jsoncpp.cpp.
References isMember().
Referenced by isMember(), and isMember().
isMember() [3/3]
bool Json::Value::isMember (const String & key) const
Return true if the object has a member named key.
Parameters
key may contain embedded nulls.
Definition at line 3655 of file jsoncpp.cpp.
References isMember().
isNull()
bool Json::Value::isNull () const
Definition at line 3680 of file jsoncpp.cpp.
References Json::nullValue, and type().
Referenced by empty(), and operator bool().
isNumeric()
bool Json::Value::isNumeric () const
Definition at line 3792 of file jsoncpp.cpp.
References isDouble().
Referenced by isConvertibleTo().
isObject()
bool Json::Value::isObject () const
Definition at line 3798 of file jsoncpp.cpp.
References Json::objectValue, and type().
Referenced by empty(), Json::StyledWriter::isMultilineArray(), Json::StyledStreamWriter::isMultilineArray(), Json::BuiltStyledStreamWriter::isMultilineArray(), Json::Path::make(), Json::Reader::parse(), Json::OurReader::parse(), Json::Path::resolve(), and Json::Path::resolve().
isString()
bool Json::Value::isString () const
Definition at line 3794 of file jsoncpp.cpp.
References Json::stringValue, and type().
isUInt()
bool Json::Value::isUInt () const
Definition at line 3703 of file jsoncpp.cpp.
References Json::Value::ValueHolder::int_, Json::intValue, Json::IsIntegral(), maxUInt, Json::Value::ValueHolder::real_, Json::realValue, type(), Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
Referenced by asUInt(), and isConvertibleTo().
isUInt64()
bool Json::Value::isUInt64 () const
Definition at line 3746 of file jsoncpp.cpp.
References Json::Value::ValueHolder::int_, Json::intValue, Json::IsIntegral(), maxUInt64AsDouble, Json::Value::ValueHolder::real_, Json::realValue, type(), Json::uintValue, and value_.
Referenced by asUInt64().
isValidIndex()
bool Json::Value::isValidIndex (ArrayIndex index) const
Return true if index < size().
Definition at line 3506 of file jsoncpp.cpp.
References size().
Referenced by Json::Path::resolve(), and Json::Path::resolve().
nullSingleton()
Value const & Json::Value::nullSingleton () static
Definition at line 2496 of file jsoncpp.cpp.
Referenced by get(), operator[](), operator[](), operator[](), operator[](), Json::Path::resolve(), Json::Path::resolve(), resolveReference(), and resolveReference().
operator bool()
Json::Value::operator bool () const explicit
Return !isNull()
Definition at line 3314 of file jsoncpp.cpp.
References isNull().
operator!=()
bool Json::Value::operator!= (const Value & other) const
Definition at line 3014 of file jsoncpp.cpp.
operator<()
bool Json::Value::operator< (const Value & other) const
Compare payload only, not comments etc.
Definition at line 2916 of file jsoncpp.cpp.
References Json::arrayValue, Json::Value::ValueHolder::bool_, Json::booleanValue, Json::decodePrefixedString(), Json::Value::ValueHolder::int_, Json::intValue, isAllocated(), JSON_ASSERT, JSON_ASSERT_UNREACHABLE, Json::Value::ValueHolder::map_, Json::nullValue, Json::objectValue, Json::Value::ValueHolder::real_, Json::realValue, Json::Value::ValueHolder::string_, Json::stringValue, type(), Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
operator<=()
bool Json::Value::operator<= (const Value & other) const
Definition at line 2966 of file jsoncpp.cpp.
operator=() [1/2]
Value & Json::Value::operator= (const Value & other)
Note
Overwrite existing comments. To preserve comments, use swapPayload().
Definition at line 2872 of file jsoncpp.cpp.
References swap().
operator=() [2/2]
Value & Json::Value::operator= (Value && other) noexcept
Definition at line 2877 of file jsoncpp.cpp.
References swap().
operator==()
bool Json::Value::operator== (const Value & other) const
Definition at line 2972 of file jsoncpp.cpp.
References Json::arrayValue, Json::Value::ValueHolder::bool_, Json::booleanValue, Json::decodePrefixedString(), Json::Value::ValueHolder::int_, Json::intValue, isAllocated(), JSON_ASSERT, JSON_ASSERT_UNREACHABLE, Json::Value::ValueHolder::map_, Json::nullValue, Json::objectValue, Json::Value::ValueHolder::real_, Json::realValue, Json::Value::ValueHolder::string_, Json::stringValue, type(), Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
operator>()
bool Json::Value::operator> (const Value & other) const
Definition at line 2970 of file jsoncpp.cpp.
operator>=()
bool Json::Value::operator>= (const Value & other) const
Definition at line 2968 of file jsoncpp.cpp.
operator[]() [1/9]
Value & Json::Value::operator[] (ArrayIndex index)
Access an array element (zero based index). If the array contains less than index element, then null value are inserted in the array so that its size is index+1. (You may need to say 'value[0u]' to get your compiler to distinguish this from the operator[] which takes a string.)
Definition at line 3351 of file jsoncpp.cpp.
References Json::arrayValue, JSON_ASSERT_MESSAGE, Json::Value::ValueHolder::map_, nullSingleton(), Json::nullValue, type(), and value_.
operator[]() [2/9]
const Value & Json::Value::operator[] (ArrayIndex index) const
Access an array element (zero based index). (You may need to say 'value[0u]' to get your compiler to distinguish this from the operator[] which takes a string.)
Definition at line 3374 of file jsoncpp.cpp.
References Json::arrayValue, JSON_ASSERT_MESSAGE, Json::Value::ValueHolder::map_, nullSingleton(), Json::nullValue, type(), and value_.
operator[]() [3/9]
Value & Json::Value::operator[] (const char * key)
Access an object value by name, create a null member if it does not exist.
Note
Because of our implementation, keys are limited to 2^30 -1 chars. Exceeding that will cause an exception.
Definition at line 3540 of file jsoncpp.cpp.
References resolveReference().
operator[]() [4/9]
const Value & Json::Value::operator[] (const char * key) const
Access an object value by name, returns null if there is no member with that name.
Definition at line 3527 of file jsoncpp.cpp.
References find(), and nullSingleton().
operator[]() [5/9]
Value & Json::Value::operator[] (const StaticString & key)
Access an object value by name, create a null member if it does not exist.
If the object has no entry for that name, then the member name used to store the new entry is not duplicated. Example of use:
Json::Value object;
static const StaticString code("code");
object[code] = 1234;
Definition at line 3548 of file jsoncpp.cpp.
References Json::StaticString::c_str(), and resolveReference().
operator[]() [6/9]
Value & Json::Value::operator[] (const String & key)
Access an object value by name, create a null member if it does not exist.
Parameters
key may contain embedded nulls.
Definition at line 3544 of file jsoncpp.cpp.
References resolveReference().
operator[]() [7/9]
Value const & Json::Value::operator[] (const String & key) const
Access an object value by name, returns null if there is no member with that name.
Parameters
key may contain embedded nulls.
Definition at line 3533 of file jsoncpp.cpp.
References find(), and nullSingleton().
operator[]() [8/9]
Value & Json::Value::operator[] (int index)
Definition at line 3367 of file jsoncpp.cpp.
References JSON_ASSERT_MESSAGE.
operator[]() [9/9]
const Value & Json::Value::operator[] (int index) const
Definition at line 3387 of file jsoncpp.cpp.
References JSON_ASSERT_MESSAGE.
releasePayload()
void Json::Value::releasePayload () private
Definition at line 3434 of file jsoncpp.cpp.
References Json::arrayValue, Json::booleanValue, Json::intValue, isAllocated(), JSON_ASSERT_UNREACHABLE, Json::Value::ValueHolder::map_, Json::nullValue, Json::objectValue, Json::realValue, Json::releasePrefixedStringValue(), Json::Value::ValueHolder::string_, Json::stringValue, type(), Json::uintValue, and value_.
Referenced by copyPayload(), and ~Value().
removeIndex()
bool Json::Value::removeIndex (ArrayIndex index, Value * removed)
Remove the indexed array element.
O(n) expensive operations. Update 'removed' iff removed.
Returns
true if removed (no exceptions)
Definition at line 3624 of file jsoncpp.cpp.
References Json::arrayValue, Json::Value::ValueHolder::map_, size(), type(), and value_.
removeMember() [1/5]
bool Json::Value::removeMember (const char * begin, const char * end, Value * removed)
Same as removeMember(String const& key, Value* removed)
Definition at line 3593 of file jsoncpp.cpp.
References begin(), end(), Json::Value::ValueHolder::map_, Json::Value::CZString::noDuplication, Json::objectValue, type(), and value_.
removeMember() [2/5]
void Json::Value::removeMember (const char * key)
Remove and return the named member.
Do nothing if it did not exist.
Precondition
type() is objectValue or nullValue
Postcondition
type() is unchanged
Definition at line 3613 of file jsoncpp.cpp.
References JSON_ASSERT_MESSAGE, Json::Value::ValueHolder::map_, Json::Value::CZString::noDuplication, Json::nullValue, Json::objectValue, type(), and value_.
Referenced by removeMember(), removeMember(), and removeMember().
removeMember() [3/5]
bool Json::Value::removeMember (const char * key, Value * removed)
Same as removeMember(const char* begin, const char* end, Value* removed), but 'key' is null-terminated.
Definition at line 3607 of file jsoncpp.cpp.
References removeMember().
removeMember() [4/5]
void Json::Value::removeMember (const String & key)
Same as removeMember(const char*)
Parameters
key may contain embedded nulls.
Definition at line 3622 of file jsoncpp.cpp.
References removeMember().
removeMember() [5/5]
bool Json::Value::removeMember (String const & key, Value * removed)
Remove the named map member.
Update 'removed' iff removed.
Parameters
key may contain embedded nulls.
Returns
true iff removed (no exceptions)
Definition at line 3610 of file jsoncpp.cpp.
References removeMember().
resize()
void Json::Value::resize (ArrayIndex newSize)
Resize the array to newSize elements. New elements are initialized to null. May only be called on nullValue or arrayValue.
Precondition
type() is arrayValue or nullValue
Postcondition
type() is arrayValue
Definition at line 3332 of file jsoncpp.cpp.
References Json::arrayValue, clear(), JSON_ASSERT, JSON_ASSERT_MESSAGE, Json::Value::ValueHolder::map_, Json::nullValue, size(), type(), and value_.
resolveReference() [1/2]
Value & Json::Value::resolveReference (const char * key) private
Definition at line 3464 of file jsoncpp.cpp.
References JSON_ASSERT_MESSAGE, Json::Value::ValueHolder::map_, Json::Value::CZString::noDuplication, nullSingleton(), Json::nullValue, Json::objectValue, type(), and value_.
Referenced by demand(), operator[](), operator[](), and operator[]().
resolveReference() [2/2]
Value & Json::Value::resolveReference (const char * key, const char * end) private
Definition at line 3483 of file jsoncpp.cpp.
References Json::Value::CZString::duplicateOnCopy, end(), JSON_ASSERT_MESSAGE, Json::Value::ValueHolder::map_, nullSingleton(), Json::nullValue, Json::objectValue, type(), and value_.
setComment() [1/3]
void Json::Value::setComment (const char * comment, CommentPlacement placement) inline
Deprecated:
Always pass len.
Definition at line 1093 of file json.h.
Referenced by Json::Reader::addComment(), Json::OurReader::addComment(), Json::Reader::parse(), Json::OurReader::parse(), Json::Reader::readValue(), and Json::OurReader::readValue().
setComment() [2/3]
void Json::Value::setComment (const char * comment, size_t len, CommentPlacement placement) inline
Comments must be //... or /* ... *‍/.
Definition at line 1097 of file json.h.
setComment() [3/3]
void Json::Value::setComment (String comment, CommentPlacement placement)
Comments must be //... or /* ... *‍/.
Definition at line 3834 of file jsoncpp.cpp.
References comments_, JSON_ASSERT, JSON_ASSERT_MESSAGE, and Json::Value::Comments::set().
setIsAllocated()
void Json::Value::setIsAllocated (bool v) inline private
Definition at line 1126 of file json.h.
Referenced by dupPayload(), and initBasic().
setOffsetLimit()
void Json::Value::setOffsetLimit (ptrdiff_t limit)
Definition at line 3856 of file jsoncpp.cpp.
References limit_.
Referenced by Json::Reader::decodeDouble(), Json::OurReader::decodeDouble(), Json::Reader::decodeNumber(), Json::OurReader::decodeNumber(), Json::Reader::decodeString(), Json::OurReader::decodeString(), Json::Reader::readValue(), and Json::OurReader::readValue().
setOffsetStart()
void Json::Value::setOffsetStart (ptrdiff_t start)
Definition at line 3854 of file jsoncpp.cpp.
References start_.
Referenced by Json::Reader::decodeDouble(), Json::OurReader::decodeDouble(), Json::Reader::decodeNumber(), Json::OurReader::decodeNumber(), Json::Reader::decodeString(), Json::OurReader::decodeString(), Json::Reader::readArray(), Json::OurReader::readArray(), Json::Reader::readObject(), Json::OurReader::readObject(), Json::Reader::readValue(), and Json::OurReader::readValue().
setType()
void Json::Value::setType (ValueType v) inline private
Definition at line 1122 of file json.h.
Referenced by dupPayload(), and initBasic().
size()
ArrayIndex Json::Value::size () const
Number of values in array or object.
Definition at line 3285 of file jsoncpp.cpp.
References Json::arrayValue, Json::booleanValue, Json::intValue, JSON_ASSERT_UNREACHABLE, Json::Value::ValueHolder::map_, Json::nullValue, Json::objectValue, Json::realValue, Json::stringValue, type(), Json::uintValue, and value_.
Referenced by append(), empty(), insert(), Json::StyledWriter::isMultilineArray(), Json::StyledStreamWriter::isMultilineArray(), Json::BuiltStyledStreamWriter::isMultilineArray(), isValidIndex(), removeIndex(), resize(), Json::StyledWriter::writeArrayValue(), Json::StyledStreamWriter::writeArrayValue(), Json::BuiltStyledStreamWriter::writeArrayValue(), and Json::FastWriter::writeValue().
swap()
void Json::Value::swap (Value & other)
Swap everything.
Definition at line 2892 of file jsoncpp.cpp.
References comments_, limit_, start_, and swapPayload().
Referenced by operator=(), operator=(), Json::swap(), and Value().
swapPayload()
void Json::Value::swapPayload (Value & other)
Swap values but leave comments and source offsets in place.
Definition at line 2882 of file jsoncpp.cpp.
References bits_, and value_.
Referenced by Json::Reader::decodeDouble(), Json::OurReader::decodeDouble(), Json::Reader::decodeNumber(), Json::OurReader::decodeNumber(), Json::Reader::decodeString(), Json::OurReader::decodeString(), Json::Reader::readArray(), Json::OurReader::readArray(), Json::Reader::readObject(), Json::OurReader::readObject(), Json::Reader::readValue(), Json::OurReader::readValue(), and swap().
toStyledString()
String Json::Value::toStyledString () const
Definition at line 3862 of file jsoncpp.cpp.
References Json::commentBefore, hasComment(), and Json::writeString().
type()
ValueType Json::Value::type () const
Definition at line 2904 of file jsoncpp.cpp.
References bits_.
Referenced by append(), asBool(), asCString(), asDouble(), asFloat(), asInt(), asInt64(), asString(), asUInt(), asUInt64(), begin(), begin(), clear(), demand(), dupPayload(), end(), end(), find(), getMemberNames(), getString(), initBasic(), insert(), isArray(), isBool(), isConvertibleTo(), isDouble(), isInt(), isInt64(), isIntegral(), isNull(), isObject(), isString(), isUInt(), isUInt64(), operator<(), operator==(), operator[](), operator[](), releasePayload(), removeIndex(), removeMember(), removeMember(), resize(), resolveReference(), resolveReference(), size(), Value(), Json::FastWriter::writeValue(), Json::StyledWriter::writeValue(), Json::StyledStreamWriter::writeValue(), and Json::BuiltStyledStreamWriter::writeValue().
Friends And Related Symbol Documentation
ValueIteratorBase
friend class ValueIteratorBase friend
Definition at line 721 of file json.h.
Member Data Documentation
allocated_
unsigned int Json::Value::allocated_
Definition at line 1158 of file json.h.
[struct]
struct { ... } Json::Value::bits_
Referenced by swapPayload(), and type().
comments_
Comments Json::Value::comments_ private
Definition at line 1176 of file json.h.
Referenced by dupMeta(), getComment(), hasComment(), initBasic(), setComment(), and swap().
defaultRealPrecision
constexpr UInt Json::Value::defaultRealPrecision = 17 static constexpr
Default precision for real value for string representation.
Definition at line 773 of file json.h.
limit_
ptrdiff_t Json::Value::limit_ private
Definition at line 1181 of file json.h.
Referenced by clear(), dupMeta(), getOffsetLimit(), initBasic(), setOffsetLimit(), and swap().
maxInt
constexpr Int Json::Value::maxInt = Int(UInt(-1) / 2) static constexpr
Maximum signed int value that can be stored in a Json::Value.
Definition at line 760 of file json.h.
Referenced by asInt(), Json::Reader::decodeNumber(), Json::duplicateAndPrefixStringValue(), Json::duplicateStringValue(), isConvertibleTo(), and isInt().
maxInt64
constexpr Int64 Json::Value::maxInt64 = Int64(UInt64(-1) / 2) static constexpr
Maximum signed 64 bits int value that can be stored in a Json::Value.
Definition at line 768 of file json.h.
Referenced by asInt64(), and isInt64().
maxLargestInt
constexpr LargestInt Json::Value::maxLargestInt = LargestInt(LargestUInt(-1) / 2) static constexpr
Maximum signed integer value that can be stored in a Json::Value.
Definition at line 753 of file json.h.
Referenced by Json::Reader::decodeNumber(), Json::OurReader::decodeNumber(), and Json::valueToString().
maxLargestUInt
constexpr LargestUInt Json::Value::maxLargestUInt = LargestUInt(-1) static constexpr
Maximum unsigned integer value that can be stored in a Json::Value.
Definition at line 755 of file json.h.
Referenced by Json::Reader::decodeNumber(), and Json::OurReader::decodeNumber().
maxUInt
constexpr UInt Json::Value::maxUInt = UInt(-1) static constexpr
Maximum unsigned int value that can be stored in a Json::Value.
Definition at line 762 of file json.h.
Referenced by asUInt(), isConvertibleTo(), isIntegral(), and isUInt().
maxUInt64
constexpr UInt64 Json::Value::maxUInt64 = UInt64(-1) static constexpr
Maximum unsigned 64 bits int value that can be stored in a Json::Value.
Definition at line 770 of file json.h.
Referenced by asUInt64().
maxUInt64AsDouble
constexpr double Json::Value::maxUInt64AsDouble = 18446744073709551615.0 static constexpr
Definition at line 777 of file json.h.
Referenced by isIntegral(), and isUInt64().
minInt
constexpr Int Json::Value::minInt = Int(~(UInt(-1) / 2)) static constexpr
Minimum signed int value that can be stored in a Json::Value.
Definition at line 758 of file json.h.
Referenced by asInt(), isConvertibleTo(), isInt(), and isIntegral().
minInt64
constexpr Int64 Json::Value::minInt64 = Int64(~(UInt64(-1) / 2)) static constexpr
Minimum signed 64 bits int value that can be stored in a Json::Value.
Definition at line 766 of file json.h.
Referenced by asInt64(), isInt64(), and isIntegral().
minLargestInt
constexpr LargestInt Json::Value::minLargestInt static constexpr
Initial value:
=
      LargestInt(~(LargestUInt(-1) / 2))
Minimum signed integer value that can be stored in a Json::Value.
Definition at line 750 of file json.h.
Referenced by Json::Reader::decodeNumber(), Json::OurReader::decodeNumber(), and Json::valueToString().
null
Value const & Json::Value::null = Value::nullSingleton() static
Definition at line 742 of file json.h.
nullRef
Value const & Json::Value::nullRef = Value::nullSingleton() static
Definition at line 743 of file json.h.
start_
ptrdiff_t Json::Value::start_ private
Definition at line 1180 of file json.h.
Referenced by clear(), dupMeta(), getOffsetStart(), initBasic(), setOffsetStart(), and swap().
value_
union Json::Value::ValueHolder Json::Value::value_ private
Referenced by append(), asBool(), asCString(), asDouble(), asFloat(), asInt(), asInt64(), asString(), asUInt(), asUInt64(), begin(), begin(), clear(), dupPayload(), end(), end(), find(), getMemberNames(), getString(), isConvertibleTo(), isInt(), isInt64(), isIntegral(), isUInt(), isUInt64(), operator<(), operator==(), operator[](), operator[](), releasePayload(), removeIndex(), removeMember(), removeMember(), resize(), resolveReference(), resolveReference(), size(), swapPayload(), Value(), Value(), Value(), Value(), Value(), Value(), Value(), Value(), Value(), Value(), Value(), and ~Value().
value_type_
unsigned int Json::Value::value_type_
Definition at line 1156 of file json.h.
The documentation for this class was generated from the following files:
json.h
jsoncpp.cpp