LILAK: LKGeoPlaneBox Class Reference
LKGeoPlaneBox Class Reference
#include <LKGeoPlaneBox.h>
Public Member Functions
virtual TVector3 ClosestPointOnPlane (TVector3 pos) const
virtual Double_t DistanceToPlane (Double_t x, Double_t y, Double_t z) const
virtual Double_t DistanceToPlane (TVector3 pos) const
Double_t GetA () const
Double_t GetB () const
Double_t GetC () const
TVector3 GetCenter () const
LKGeoLine GetCrossSectionLine (LKGeoPlaneBox plane2) const
LKGeoLine GetCrossSectionLine (LKGeoPlaneWithCenter plane2) const
Double_t GetD () const
LKGeo2DBox GetFace () const
TVector3 GetNormal () const
Double_t GetRMS () const
TVector3 GetVectorU () const
TVector3 GetVectorV () const
Double_t GetX () const
Double_t GetX (Double_t y, Double_t z) const
Double_t GetY () const
Double_t GetY (Double_t z, Double_t x) const
Double_t GetZ () const
Double_t GetZ (Double_t x, Double_t y) const
int Intersection (LKGeoLine line, TVector3 &intersection)
LKGeoPlaneBox ()
LKGeoPlaneBox (Double_t x, Double_t y, Double_t z, Double_t xn, Double_t yn, Double_t zn)
LKGeoPlaneBox (TVector3 pos, TVector3 nnn)
void Print (Option_t *option="") const
void SetPlane (Double_t a, Double_t b, Double_t c, Double_t d)
virtual void SetPlane (Double_t x, Double_t y, Double_t z, Double_t xn, Double_t yn, Double_t zn)
virtual void SetPlane (TVector3 pos, TVector3 nnn)
void SetRMS (Double_t val)
virtual ~LKGeoPlaneBox ()
Protected Attributes
Double_t fA = 0
Double_t fB = 0
Double_t fC = 0
Double_t fD = 0
Double_t fRMS = -1
Double_t fX = 0
Double_t fX1 = 0
Double_t fX2 = 0
Double_t fY = 0
Double_t fY1 = 0
Double_t fY2 = 0
Double_t fZ = 0
Double_t fZ1 = 0
Double_t fZ2 = 0
Detailed Description
Definition at line 9 of file LKGeoPlaneBox.h.
Constructor & Destructor Documentation
LKGeoPlaneBox() [1/3]
LKGeoPlaneBox::LKGeoPlaneBox ()
LKGeoPlaneBox() [2/3]
LKGeoPlaneBox::LKGeoPlaneBox (TVector3 pos, TVector3 nnn)
Definition at line 31 of file LKGeoPlaneBox.cpp.
References SetPlane().
LKGeoPlaneBox() [3/3]
LKGeoPlaneBox::LKGeoPlaneBox (Double_t x, Double_t y, Double_t z, Double_t xn, Double_t yn, Double_t zn)
Definition at line 13 of file LKGeoPlaneBox.cpp.
References SetPlane().
~LKGeoPlaneBox()
virtual LKGeoPlaneBox::~LKGeoPlaneBox () inline virtual
Definition at line 15 of file LKGeoPlaneBox.h.
Member Function Documentation
ClosestPointOnPlane()
TVector3 LKGeoPlane::ClosestPointOnPlane (TVector3 pos) const virtual inherited
Definition at line 59 of file LKGeoPlane.cpp.
References LKGeoPlane::fA, LKGeoPlane::fB, and LKGeoPlane::fC.
Referenced by LKGeoPlane::DistanceToPlane().
DistanceToPlane() [1/2]
Double_t LKGeoPlane::DistanceToPlane (Double_t x, Double_t y, Double_t z) const virtual inherited
Definition at line 67 of file LKGeoPlane.cpp.
References LKGeoPlane::DistanceToPlane().
Referenced by LKGeoPlane::DistanceToPlane().
DistanceToPlane() [2/2]
Double_t LKGeoPlane::DistanceToPlane (TVector3 pos) const virtual inherited
Definition at line 72 of file LKGeoPlane.cpp.
References LKGeoPlane::ClosestPointOnPlane().
GetA()
Double_t LKGeoPlane::GetA () const inherited
Definition at line 49 of file LKGeoPlane.cpp.
References LKGeoPlane::fA.
Referenced by GetCrossSectionLine(), and LKGeoPlaneWithCenter::GetCrossSectionLine().
GetB()
Double_t LKGeoPlane::GetB () const inherited
Definition at line 50 of file LKGeoPlane.cpp.
References LKGeoPlane::fB.
Referenced by GetCrossSectionLine(), and LKGeoPlaneWithCenter::GetCrossSectionLine().
GetC()
Double_t LKGeoPlane::GetC () const inherited
Definition at line 51 of file LKGeoPlane.cpp.
References LKGeoPlane::fC.
Referenced by GetCrossSectionLine(), and LKGeoPlaneWithCenter::GetCrossSectionLine().
GetCenter()
TVector3 LKGeoPlaneBox::GetCenter () const
Definition at line 54 of file LKGeoPlaneBox.cpp.
References LKGeoPlaneWithCenter::fX, LKGeoPlaneWithCenter::fY, and LKGeoPlaneWithCenter::fZ.
Referenced by Print().
GetCrossSectionLine() [1/2]
LKGeoLine LKGeoPlaneBox::GetCrossSectionLine (LKGeoPlaneBox plane2) const
Definition at line 84 of file LKGeoPlaneBox.cpp.
References LKGeoPlane::GetA(), LKGeoPlane::GetB(), LKGeoPlane::GetC(), LKGeoPlane::GetD(), LKGeoPlane::GetNormal(), GetX(), GetY(), GetZ(), and lk_debug.
GetCrossSectionLine() [2/2]
LKGeoLine LKGeoPlaneWithCenter::GetCrossSectionLine (LKGeoPlaneWithCenter plane2) const inherited
Definition at line 79 of file LKGeoPlaneWithCenter.cpp.
References LKGeoPlane::GetA(), LKGeoPlane::GetB(), LKGeoPlane::GetC(), LKGeoPlane::GetD(), LKGeoPlane::GetNormal(), LKGeoPlaneWithCenter::GetX(), LKGeoPlaneWithCenter::GetY(), and LKGeoPlaneWithCenter::GetZ().
Referenced by LKLinearTrack::Create3DTrack(), DrawEvent(), httask::MakeTrack(), and TTHTtBeamTrackingTask::MakeTrack().
GetD()
Double_t LKGeoPlane::GetD () const inherited
Definition at line 52 of file LKGeoPlane.cpp.
References LKGeoPlane::fD.
Referenced by LKGeoLine::GetCrossingPoint(), GetCrossSectionLine(), and LKGeoPlaneWithCenter::GetCrossSectionLine().
GetFace()
LKGeo2DBox LKGeoPlaneBox::GetFace () const
GetNormal()
TVector3 LKGeoPlane::GetNormal () const inherited
Definition at line 53 of file LKGeoPlane.cpp.
References LKGeoPlane::fA, LKGeoPlane::fB, and LKGeoPlane::fC.
Referenced by LKGeoLine::GetCrossingPoint(), GetCrossSectionLine(), LKGeoPlaneWithCenter::GetCrossSectionLine(), LKGeoPlaneWithCenter::GetVectorV(), LKGeoPlaneWithCenter::Print(), and Print().
GetRMS()
Double_t LKGeometry::GetRMS () const inline inherited
Definition at line 16 of file LKGeometry.h.
References LKGeometry::fRMS.
Referenced by LKTracklet::FitHelix(), LKTracklet::FitLine(), and LKTracklet::FitPlane().
GetVectorU()
TVector3 LKGeoPlaneWithCenter::GetVectorU () const inherited
Definition at line 60 of file LKGeoPlaneWithCenter.cpp.
References LKGeoPlane::fA, LKGeoPlane::fB, LKGeoPlane::fC, LKGeoPlaneWithCenter::fX, LKGeoPlaneWithCenter::fY, LKGeoPlaneWithCenter::fZ, LKGeoPlane::GetX(), LKGeoPlane::GetY(), and LKGeoPlane::GetZ().
Referenced by LKGeoPlaneWithCenter::GetVectorV(), LKGeoPlaneWithCenter::Print(), and Print().
GetVectorV()
TVector3 LKGeoPlaneWithCenter::GetVectorV () const inherited
Definition at line 74 of file LKGeoPlaneWithCenter.cpp.
References LKGeoPlane::GetNormal(), and LKGeoPlaneWithCenter::GetVectorU().
Referenced by LKGeoPlaneWithCenter::Print(), and Print().
GetX() [1/2]
Double_t LKGeoPlaneBox::GetX () const
Definition at line 56 of file LKGeoPlaneBox.cpp.
References LKGeoPlaneWithCenter::fX.
Referenced by GetCrossSectionLine().
GetX() [2/2]
Double_t LKGeoPlane::GetX (Double_t y, Double_t z) const inherited
Definition at line 55 of file LKGeoPlane.cpp.
References LKGeoPlane::fA, LKGeoPlane::fB, LKGeoPlane::fC, and LKGeoPlane::fD.
Referenced by LKGeoPlaneWithCenter::GetVectorU().
GetY() [1/2]
Double_t LKGeoPlaneBox::GetY () const
Definition at line 57 of file LKGeoPlaneBox.cpp.
References LKGeoPlaneWithCenter::fY.
Referenced by GetCrossSectionLine().
GetY() [2/2]
Double_t LKGeoPlane::GetY (Double_t z, Double_t x) const inherited
Definition at line 56 of file LKGeoPlane.cpp.
References LKGeoPlane::fA, LKGeoPlane::fB, LKGeoPlane::fC, and LKGeoPlane::fD.
Referenced by LKGeoPlaneWithCenter::GetVectorU().
GetZ() [1/2]
Double_t LKGeoPlaneBox::GetZ () const
Definition at line 58 of file LKGeoPlaneBox.cpp.
References LKGeoPlaneWithCenter::fZ.
Referenced by GetCrossSectionLine().
GetZ() [2/2]
Double_t LKGeoPlane::GetZ (Double_t x, Double_t y) const inherited
Definition at line 57 of file LKGeoPlane.cpp.
References LKGeoPlane::fA, LKGeoPlane::fB, LKGeoPlane::fC, and LKGeoPlane::fD.
Referenced by LKGeoPlaneWithCenter::GetVectorU().
Intersection()
int LKGeoPlaneWithCenter::Intersection (LKGeoLine line, TVector3 & intersection) inherited
Definition at line 115 of file LKGeoPlaneWithCenter.cpp.
References LKGeoLine::Direction(), LKGeoPlane::fA, LKGeoPlane::fB, LKGeoPlane::fC, LKGeoPlane::fD, LKGeoLine::GetPoint1(), and z1.
Print()
void LKGeoPlaneBox::Print (Option_t * option = "") const
Definition at line 18 of file LKGeoPlaneBox.cpp.
References e_info, GetCenter(), LKGeoPlane::GetNormal(), LKGeoPlaneWithCenter::GetVectorU(), and LKGeoPlaneWithCenter::GetVectorV().
SetPlane() [1/3]
void LKGeoPlane::SetPlane (Double_t a, Double_t b, Double_t c, Double_t d) inherited
Definition at line 40 of file LKGeoPlane.cpp.
References LKGeoPlane::fA, LKGeoPlane::fB, LKGeoPlane::fC, and LKGeoPlane::fD.
SetPlane() [2/3]
void LKGeoPlaneBox::SetPlane (Double_t x, Double_t y, Double_t z, Double_t xn, Double_t yn, Double_t zn) virtual
Reimplemented from LKGeoPlaneWithCenter.
Definition at line 49 of file LKGeoPlaneBox.cpp.
References SetPlane().
SetPlane() [3/3]
void LKGeoPlaneBox::SetPlane (TVector3 pos, TVector3 nnn) virtual
Reimplemented from LKGeoPlaneWithCenter.
Definition at line 36 of file LKGeoPlaneBox.cpp.
References LKGeoPlane::fA, LKGeoPlane::fB, LKGeoPlane::fC, LKGeoPlane::fD, LKGeoPlaneWithCenter::fX, LKGeoPlaneWithCenter::fY, and LKGeoPlaneWithCenter::fZ.
Referenced by LKGeoPlaneBox(), LKGeoPlaneBox(), and SetPlane().
SetRMS()
void LKGeometry::SetRMS (Double_t val) inline inherited
Definition at line 15 of file LKGeometry.h.
References LKGeometry::fRMS.
Referenced by LKHitArray::DrawFitCircle(), LKHelixTrack::Fit(), LKHitArray::FitCircle(), LKHitArray::FitHelix(), LKHitArray::FitLine(), LKHitArray::FitPlane(), and LKHelixTrack::FitPlane().
Member Data Documentation
fA
Double_t LKGeoPlane::fA = 0 protected inherited
Definition at line 41 of file LKGeoPlane.h.
Referenced by LKGeoPlane::ClosestPointOnPlane(), LKGeoPlane::GetA(), LKGeoPlane::GetNormal(), LKGeoPlaneWithCenter::GetVectorU(), LKGeoPlane::GetX(), LKGeoPlane::GetY(), LKGeoPlane::GetZ(), LKGeoPlaneWithCenter::Intersection(), LKGeoPlane::SetPlane(), LKGeoPlane::SetPlane(), LKGeoPlaneWithCenter::SetPlane(), and SetPlane().
fB
Double_t LKGeoPlane::fB = 0 protected inherited
Definition at line 42 of file LKGeoPlane.h.
Referenced by LKGeoPlane::ClosestPointOnPlane(), LKGeoPlane::GetB(), LKGeoPlane::GetNormal(), LKGeoPlaneWithCenter::GetVectorU(), LKGeoPlane::GetX(), LKGeoPlane::GetY(), LKGeoPlane::GetZ(), LKGeoPlaneWithCenter::Intersection(), LKGeoPlane::SetPlane(), LKGeoPlane::SetPlane(), LKGeoPlaneWithCenter::SetPlane(), and SetPlane().
fC
Double_t LKGeoPlane::fC = 0 protected inherited
Definition at line 43 of file LKGeoPlane.h.
Referenced by LKGeoPlane::ClosestPointOnPlane(), LKGeoPlane::GetC(), LKGeoPlane::GetNormal(), LKGeoPlaneWithCenter::GetVectorU(), LKGeoPlane::GetX(), LKGeoPlane::GetY(), LKGeoPlane::GetZ(), LKGeoPlaneWithCenter::Intersection(), LKGeoPlane::SetPlane(), LKGeoPlane::SetPlane(), LKGeoPlaneWithCenter::SetPlane(), and SetPlane().
fD
Double_t LKGeoPlane::fD = 0 protected inherited
Definition at line 44 of file LKGeoPlane.h.
Referenced by LKGeoPlane::GetD(), LKGeoPlane::GetX(), LKGeoPlane::GetY(), LKGeoPlane::GetZ(), LKGeoPlaneWithCenter::Intersection(), LKGeoPlane::SetPlane(), LKGeoPlane::SetPlane(), LKGeoPlaneWithCenter::SetPlane(), and SetPlane().
fRMS
Double_t LKGeometry::fRMS = -1 protected inherited
Definition at line 9 of file LKGeometry.h.
Referenced by LKLinearTrack::Fit(), LKGeometry::GetRMS(), and LKGeometry::SetRMS().
fX
Double_t LKGeoPlaneWithCenter::fX = 0 protected inherited
Definition at line 44 of file LKGeoPlaneWithCenter.h.
Referenced by LKGeoPlaneWithCenter::GetCenter(), GetCenter(), LKGeoPlaneWithCenter::GetVectorU(), LKGeoPlaneWithCenter::GetX(), GetX(), LKGeoPlaneWithCenter::SetPlane(), and SetPlane().
fX1
Double_t LKGeoPlaneBox::fX1 = 0 protected
Definition at line 35 of file LKGeoPlaneBox.h.
fX2
Double_t LKGeoPlaneBox::fX2 = 0 protected
Definition at line 39 of file LKGeoPlaneBox.h.
fY
Double_t LKGeoPlaneWithCenter::fY = 0 protected inherited
Definition at line 45 of file LKGeoPlaneWithCenter.h.
Referenced by LKGeoPlaneWithCenter::GetCenter(), GetCenter(), LKGeoPlaneWithCenter::GetVectorU(), LKGeoPlaneWithCenter::GetY(), GetY(), LKGeoPlaneWithCenter::SetPlane(), and SetPlane().
fY1
Double_t LKGeoPlaneBox::fY1 = 0 protected
Definition at line 36 of file LKGeoPlaneBox.h.
fY2
Double_t LKGeoPlaneBox::fY2 = 0 protected
Definition at line 40 of file LKGeoPlaneBox.h.
fZ
Double_t LKGeoPlaneWithCenter::fZ = 0 protected inherited
Definition at line 46 of file LKGeoPlaneWithCenter.h.
Referenced by LKGeoPlaneWithCenter::GetCenter(), GetCenter(), LKGeoPlaneWithCenter::GetVectorU(), LKGeoPlaneWithCenter::GetZ(), GetZ(), LKGeoPlaneWithCenter::SetPlane(), and SetPlane().
fZ1
Double_t LKGeoPlaneBox::fZ1 = 0 protected
Definition at line 37 of file LKGeoPlaneBox.h.
fZ2
Double_t LKGeoPlaneBox::fZ2 = 0 protected
Definition at line 41 of file LKGeoPlaneBox.h.
The documentation for this class was generated from the following files:
LKGeoPlaneBox.h
LKGeoPlaneBox.cpp