lilak: ejungwoo::Binning Class Reference
ejungwoo::Binning Class Reference
#include <ejungwooA.h>
Public Member Functions
Binning * Add (Binning *binning2)
Binning * Add (Binning *binning2)
Binning * Add (Binning *binning2)
Binning ()
Binning ()
Binning ()
Binning (Binning *binning1, Binning *binning2)
Binning (Binning *binning1, Binning *binning2)
Binning (Binning *binning1, Binning *binning2)
Binning (Binning *binning1, Binning *binning2, Binning *binning3)
Binning (Binning binning1, Binning binning2)
Binning (Binning binning1, Binning binning2)
Binning (Binning binning1, Binning binning2)
Binning (int numBins, double x1, double x2)
Binning (int numBins, double x1, double x2)
Binning (int numBins, double x1, double x2)
Binning (TString name, TString title, TString selection, int numBins, double x1, double x2)
Binning (TString name, TString title, TString selection, int numBins, double x1, double x2)
Binning (TString name, TString title, TString selection, int numBins, double x1, double x2)
TString GetSelection (int dim=1)
TString GetSelection (int dim=1)
TString GetSelection (int dim=1)
TH1D * NewHist (TString name="", TString title="")
TH1D * NewHist (TString name="", TString title="")
TH1D * NewHist (TString name="", TString title="")
TH2D * NewHist2 (TString name="", TString title="")
TH2D * NewHist2 (TString name="", TString title="")
TH2D * NewHist2 (TString name="", TString title="")
TH3D * NewHist3 (TString name="", TString title="")
double NX ()
Binning * operator() (TString name, TString title)
Binning * operator() (TString name, TString title)
Binning * operator() (TString name, TString title)
Binning * operator* (Binning binning2)
Binning * operator* (Binning binning2)
Binning * operator* (Binning binning2)
Binning * operator* (TString nameTitle)
Binning * operator* (TString nameTitle)
Binning * operator* (TString nameTitle)
void Set (Binning binning, int iAxis=0)
void Set (Binning binning, int iAxis=0)
void Set (Binning binning, int iAxis=0)
void Set (TString name, TString title, TString selection, int numBins, double x1, double x2, int iAxis=0)
void Set (TString name, TString title, TString selection, int numBins, double x1, double x2, int iAxis=0)
void Set (TString name, TString title, TString selection, int numBins, double x1, double x2, int iAxis=0)
void SetBinning (int numBins, double x1, double x2, int iAxis=0)
void SetBinning (int numBins, double x1, double x2, int iAxis=0)
void SetBinning (int numBins, double x1, double x2, int iAxis=0)
void SetMainTitle (TString title)
void SetMainTitle (TString title)
void SetMainTitle (TString title)
void SetNameMainTitle (TString name, TString title)
void SetNameMainTitle (TString name, TString title)
void SetNameMainTitle (TString name, TString title)
void SetNameTitle (TString name, TString title, int iAxis=0)
void SetNameTitle (TString name, TString title, int iAxis=0)
void SetNameTitle (TString name, TString title, int iAxis=0)
void SetNameTitleSelection (TString name, TString title, TString selection, int iAxis=0)
void SetNameTitleSelection (TString name, TString title, TString selection, int iAxis=0)
void SetNameTitleSelection (TString name, TString title, TString selection, int iAxis=0)
void SetSelection (TString selection, int iAxis=0)
void SetSelection (TString selection, int iAxis=0)
void SetSelection (TString selection, int iAxis=0)
double X1 ()
double X2 ()
Public Attributes
TString fAxisTitle [3]
TH1D * fHist = nullptr
TH2D * fHist2 = nullptr
TH2Poly * fHist2Poly = nullptr
TH3D * fHist3 = nullptr
TString fMainTitle
double fMax [3] = {100,100,100}
double fMin [3] = {0,0,0}
TString fName
int fNumBins [3] = {100,100,100}
TString fSelection [3]
Detailed Description
Definition at line 322 of file macros_detectorplane/ejungwooA.h.
Constructor & Destructor Documentation
Binning() [1/16]
ejungwoo::Binning::Binning () inline
Definition at line 336 of file macros_detectorplane/ejungwooA.h.
Referenced by Add(), and operator*().
Binning() [2/16]
ejungwoo::Binning::Binning (int numBins, double x1, double x2) inline
Definition at line 337 of file macros_detectorplane/ejungwooA.h.
References SetBinning().
Binning() [3/16]
ejungwoo::Binning::Binning (TString name, TString title, TString selection, int numBins, double x1, double x2) inline
Definition at line 338 of file macros_detectorplane/ejungwooA.h.
References Set().
Binning() [4/16]
ejungwoo::Binning::Binning (Binning binning1, Binning binning2) inline
Definition at line 341 of file macros_detectorplane/ejungwooA.h.
References Set().
Binning() [5/16]
ejungwoo::Binning::Binning (Binning * binning1, Binning * binning2) inline
Definition at line 345 of file macros_detectorplane/ejungwooA.h.
References Set().
Binning() [6/16]
ejungwoo::Binning::Binning () inline
Definition at line 338 of file macros_hough/ejungwooA.h.
Binning() [7/16]
ejungwoo::Binning::Binning (int numBins, double x1, double x2) inline
Definition at line 339 of file macros_hough/ejungwooA.h.
References SetBinning().
Binning() [8/16]
ejungwoo::Binning::Binning (TString name, TString title, TString selection, int numBins, double x1, double x2) inline
Definition at line 340 of file macros_hough/ejungwooA.h.
References Set().
Binning() [9/16]
ejungwoo::Binning::Binning (Binning binning1, Binning binning2) inline
Definition at line 343 of file macros_hough/ejungwooA.h.
References Set().
Binning() [10/16]
ejungwoo::Binning::Binning (Binning * binning1, Binning * binning2) inline
Definition at line 347 of file macros_hough/ejungwooA.h.
References Set().
Binning() [11/16]
ejungwoo::Binning::Binning (Binning * binning1, Binning * binning2, Binning * binning3) inline
Definition at line 351 of file macros_hough/ejungwooA.h.
References Set().
Binning() [12/16]
ejungwoo::Binning::Binning () inline
Definition at line 336 of file macros_psa/ejungwooA.h.
Binning() [13/16]
ejungwoo::Binning::Binning (int numBins, double x1, double x2) inline
Definition at line 337 of file macros_psa/ejungwooA.h.
References SetBinning().
Binning() [14/16]
ejungwoo::Binning::Binning (TString name, TString title, TString selection, int numBins, double x1, double x2) inline
Definition at line 338 of file macros_psa/ejungwooA.h.
References Set().
Binning() [15/16]
ejungwoo::Binning::Binning (Binning binning1, Binning binning2) inline
Definition at line 341 of file macros_psa/ejungwooA.h.
References Set().
Binning() [16/16]
ejungwoo::Binning::Binning (Binning * binning1, Binning * binning2) inline
Definition at line 345 of file macros_psa/ejungwooA.h.
References Set().
Member Function Documentation
Add() [1/3]
Binning * ejungwoo::Binning::Add (Binning * binning2) inline
Definition at line 419 of file macros_detectorplane/ejungwooA.h.
References Binning().
Referenced by drawHit().
Add() [2/3]
Binning * ejungwoo::Binning::Add (Binning * binning2) inline
Definition at line 440 of file macros_hough/ejungwooA.h.
References Binning().
Add() [3/3]
Binning * ejungwoo::Binning::Add (Binning * binning2) inline
Definition at line 419 of file macros_psa/ejungwooA.h.
References Binning().
GetSelection() [1/3]
TString ejungwoo::Binning::GetSelection (int dim = 1) inline
Definition at line 391 of file macros_detectorplane/ejungwooA.h.
References fSelection.
GetSelection() [2/3]
TString ejungwoo::Binning::GetSelection (int dim = 1) inline
Definition at line 402 of file macros_hough/ejungwooA.h.
References fSelection.
GetSelection() [3/3]
TString ejungwoo::Binning::GetSelection (int dim = 1) inline
Definition at line 391 of file macros_psa/ejungwooA.h.
References fSelection.
NewHist() [1/3]
TH1D * ejungwoo::Binning::NewHist (TString name = "", TString title = "") inline
Definition at line 399 of file macros_detectorplane/ejungwooA.h.
References fAxisTitle, fHist, fMainTitle, fMax, fMin, fName, and fNumBins.
NewHist() [2/3]
TH1D * ejungwoo::Binning::NewHist (TString name = "", TString title = "") inline
Definition at line 410 of file macros_hough/ejungwooA.h.
References fAxisTitle, fHist, fMainTitle, fMax, fMin, fName, and fNumBins.
NewHist() [3/3]
TH1D * ejungwoo::Binning::NewHist (TString name = "", TString title = "") inline
Definition at line 399 of file macros_psa/ejungwooA.h.
References fAxisTitle, fHist, fMainTitle, fMax, fMin, fName, and fNumBins.
NewHist2() [1/3]
TH2D * ejungwoo::Binning::NewHist2 (TString name = "", TString title = "") inline
Definition at line 409 of file macros_detectorplane/ejungwooA.h.
References fAxisTitle, fHist2, fMainTitle, fMax, fMin, fName, and fNumBins.
NewHist2() [2/3]
TH2D * ejungwoo::Binning::NewHist2 (TString name = "", TString title = "") inline
Definition at line 420 of file macros_hough/ejungwooA.h.
References fAxisTitle, fHist2, fMainTitle, fMax, fMin, fName, and fNumBins.
NewHist2() [3/3]
TH2D * ejungwoo::Binning::NewHist2 (TString name = "", TString title = "") inline
Definition at line 409 of file macros_psa/ejungwooA.h.
References fAxisTitle, fHist2, fMainTitle, fMax, fMin, fName, and fNumBins.
NewHist3()
TH3D * ejungwoo::Binning::NewHist3 (TString name = "", TString title = "") inline
Definition at line 430 of file macros_hough/ejungwooA.h.
References fAxisTitle, fHist3, fMainTitle, fMax, fMin, fName, and fNumBins.
NX()
double ejungwoo::Binning::NX () inline
Definition at line 357 of file macros_hough/ejungwooA.h.
References fNumBins.
operator()() [1/3]
Binning * ejungwoo::Binning::operator() (TString name, TString title) inline
Definition at line 427 of file macros_detectorplane/ejungwooA.h.
References fMainTitle, and fName.
operator()() [2/3]
Binning * ejungwoo::Binning::operator() (TString name, TString title) inline
Definition at line 448 of file macros_hough/ejungwooA.h.
References fMainTitle, and fName.
operator()() [3/3]
Binning * ejungwoo::Binning::operator() (TString name, TString title) inline
Definition at line 427 of file macros_psa/ejungwooA.h.
References fMainTitle, and fName.
operator*() [1/6]
Binning * ejungwoo::Binning::operator* (Binning binning2) inline
Definition at line 423 of file macros_detectorplane/ejungwooA.h.
References Binning(), fAxisTitle, fMax, fMin, fName, fNumBins, and fSelection.
operator*() [2/6]
Binning * ejungwoo::Binning::operator* (Binning binning2) inline
Definition at line 444 of file macros_hough/ejungwooA.h.
References Binning(), fAxisTitle, fMax, fMin, fName, fNumBins, and fSelection.
operator*() [3/6]
Binning * ejungwoo::Binning::operator* (Binning binning2) inline
Definition at line 423 of file macros_psa/ejungwooA.h.
References Binning(), fAxisTitle, fMax, fMin, fName, fNumBins, and fSelection.
operator*() [4/6]
Binning * ejungwoo::Binning::operator* (TString nameTitle) inline
Definition at line 433 of file macros_detectorplane/ejungwooA.h.
References fMainTitle, and fName.
operator*() [5/6]
Binning * ejungwoo::Binning::operator* (TString nameTitle) inline
Definition at line 454 of file macros_hough/ejungwooA.h.
References fMainTitle, and fName.
operator*() [6/6]
Binning * ejungwoo::Binning::operator* (TString nameTitle) inline
Definition at line 433 of file macros_psa/ejungwooA.h.
References fMainTitle, and fName.
Set() [1/6]
void ejungwoo::Binning::Set (Binning binning, int iAxis = 0) inline
Definition at line 352 of file macros_detectorplane/ejungwooA.h.
References fAxisTitle, fMax, fMin, fName, fNumBins, fSelection, and Set().
Referenced by Binning(), Binning(), Binning(), Binning(), and Set().
Set() [2/6]
void ejungwoo::Binning::Set (Binning binning, int iAxis = 0) inline
Definition at line 363 of file macros_hough/ejungwooA.h.
References Set().
Set() [3/6]
void ejungwoo::Binning::Set (Binning binning, int iAxis = 0) inline
Definition at line 352 of file macros_psa/ejungwooA.h.
References Set().
Set() [4/6]
void ejungwoo::Binning::Set (TString name, TString title, TString selection, int numBins, double x1, double x2, int iAxis = 0) inline
Definition at line 355 of file macros_detectorplane/ejungwooA.h.
References SetBinning(), and SetNameTitleSelection().
Set() [5/6]
void ejungwoo::Binning::Set (TString name, TString title, TString selection, int numBins, double x1, double x2, int iAxis = 0) inline
Definition at line 366 of file macros_hough/ejungwooA.h.
References SetBinning(), and SetNameTitleSelection().
Set() [6/6]
void ejungwoo::Binning::Set (TString name, TString title, TString selection, int numBins, double x1, double x2, int iAxis = 0) inline
Definition at line 355 of file macros_psa/ejungwooA.h.
References SetBinning(), and SetNameTitleSelection().
SetBinning() [1/3]
void ejungwoo::Binning::SetBinning (int numBins, double x1, double x2, int iAxis = 0) inline
Definition at line 385 of file macros_detectorplane/ejungwooA.h.
References fMax, fMin, and fNumBins.
Referenced by Binning(), and Set().
SetBinning() [2/3]
void ejungwoo::Binning::SetBinning (int numBins, double x1, double x2, int iAxis = 0) inline
Definition at line 396 of file macros_hough/ejungwooA.h.
References fMax, fMin, and fNumBins.
SetBinning() [3/3]
void ejungwoo::Binning::SetBinning (int numBins, double x1, double x2, int iAxis = 0) inline
Definition at line 385 of file macros_psa/ejungwooA.h.
References fMax, fMin, and fNumBins.
SetMainTitle() [1/3]
void ejungwoo::Binning::SetMainTitle (TString title) inline
Definition at line 350 of file macros_detectorplane/ejungwooA.h.
References fMainTitle.
SetMainTitle() [2/3]
void ejungwoo::Binning::SetMainTitle (TString title) inline
Definition at line 361 of file macros_hough/ejungwooA.h.
References fMainTitle.
SetMainTitle() [3/3]
void ejungwoo::Binning::SetMainTitle (TString title) inline
Definition at line 350 of file macros_psa/ejungwooA.h.
References fMainTitle.
SetNameMainTitle() [1/3]
void ejungwoo::Binning::SetNameMainTitle (TString name, TString title) inline
Definition at line 351 of file macros_detectorplane/ejungwooA.h.
References fMainTitle, and fName.
SetNameMainTitle() [2/3]
void ejungwoo::Binning::SetNameMainTitle (TString name, TString title) inline
Definition at line 362 of file macros_hough/ejungwooA.h.
References fMainTitle, and fName.
SetNameMainTitle() [3/3]
void ejungwoo::Binning::SetNameMainTitle (TString name, TString title) inline
Definition at line 351 of file macros_psa/ejungwooA.h.
References fMainTitle, and fName.
SetNameTitle() [1/3]
void ejungwoo::Binning::SetNameTitle (TString name, TString title, int iAxis = 0) inline
Definition at line 363 of file macros_detectorplane/ejungwooA.h.
References fAxisTitle, fMainTitle, and fName.
Referenced by SetNameTitleSelection().
SetNameTitle() [2/3]
void ejungwoo::Binning::SetNameTitle (TString name, TString title, int iAxis = 0) inline
Definition at line 374 of file macros_hough/ejungwooA.h.
References fAxisTitle, fMainTitle, and fName.
SetNameTitle() [3/3]
void ejungwoo::Binning::SetNameTitle (TString name, TString title, int iAxis = 0) inline
Definition at line 363 of file macros_psa/ejungwooA.h.
References fAxisTitle, fMainTitle, and fName.
SetNameTitleSelection() [1/3]
void ejungwoo::Binning::SetNameTitleSelection (TString name, TString title, TString selection, int iAxis = 0) inline
Definition at line 359 of file macros_detectorplane/ejungwooA.h.
References SetNameTitle(), and SetSelection().
Referenced by Set().
SetNameTitleSelection() [2/3]
void ejungwoo::Binning::SetNameTitleSelection (TString name, TString title, TString selection, int iAxis = 0) inline
Definition at line 370 of file macros_hough/ejungwooA.h.
References SetNameTitle(), and SetSelection().
SetNameTitleSelection() [3/3]
void ejungwoo::Binning::SetNameTitleSelection (TString name, TString title, TString selection, int iAxis = 0) inline
Definition at line 359 of file macros_psa/ejungwooA.h.
References SetNameTitle(), and SetSelection().
SetSelection() [1/3]
void ejungwoo::Binning::SetSelection (TString selection, int iAxis = 0) inline
Definition at line 382 of file macros_detectorplane/ejungwooA.h.
References fSelection.
Referenced by SetNameTitleSelection().
SetSelection() [2/3]
void ejungwoo::Binning::SetSelection (TString selection, int iAxis = 0) inline
Definition at line 393 of file macros_hough/ejungwooA.h.
References fSelection.
SetSelection() [3/3]
void ejungwoo::Binning::SetSelection (TString selection, int iAxis = 0) inline
Definition at line 382 of file macros_psa/ejungwooA.h.
References fSelection.
X1()
double ejungwoo::Binning::X1 () inline
Definition at line 358 of file macros_hough/ejungwooA.h.
References fMin.
Referenced by DrawEvent().
X2()
double ejungwoo::Binning::X2 () inline
Definition at line 359 of file macros_hough/ejungwooA.h.
References fMax.
Referenced by DrawEvent().
Member Data Documentation
fAxisTitle
TString ejungwoo::Binning::fAxisTitle
Definition at line 328 of file macros_detectorplane/ejungwooA.h.
Referenced by NewHist(), NewHist2(), NewHist3(), operator*(), Set(), and SetNameTitle().
fHist
TH1D * ejungwoo::Binning::fHist = nullptr
Definition at line 332 of file macros_detectorplane/ejungwooA.h.
Referenced by NewHist().
fHist2
TH2D * ejungwoo::Binning::fHist2 = nullptr
Definition at line 333 of file macros_detectorplane/ejungwooA.h.
Referenced by NewHist2().
fHist2Poly
TH2Poly * ejungwoo::Binning::fHist2Poly = nullptr
Definition at line 334 of file macros_detectorplane/ejungwooA.h.
fHist3
TH3D* ejungwoo::Binning::fHist3 = nullptr
Definition at line 335 of file macros_hough/ejungwooA.h.
Referenced by NewHist3().
fMainTitle
TString ejungwoo::Binning::fMainTitle
Definition at line 327 of file macros_detectorplane/ejungwooA.h.
Referenced by NewHist(), NewHist2(), NewHist3(), operator()(), operator*(), SetMainTitle(), SetNameMainTitle(), and SetNameTitle().
fMax
double ejungwoo::Binning::fMax = {100,100,100}
Definition at line 331 of file macros_detectorplane/ejungwooA.h.
Referenced by DrawEvent(), NewHist(), NewHist2(), NewHist3(), operator*(), Set(), SetBinning(), and X2().
fMin
double ejungwoo::Binning::fMin = {0,0,0}
Definition at line 330 of file macros_detectorplane/ejungwooA.h.
Referenced by DrawEvent(), NewHist(), NewHist2(), NewHist3(), operator*(), Set(), SetBinning(), and X1().
fName
TString ejungwoo::Binning::fName
Definition at line 325 of file macros_detectorplane/ejungwooA.h.
Referenced by NewHist(), NewHist2(), NewHist3(), operator()(), operator*(), operator*(), Set(), SetNameMainTitle(), and SetNameTitle().
fNumBins
int ejungwoo::Binning::fNumBins = {100,100,100}
Definition at line 329 of file macros_detectorplane/ejungwooA.h.
Referenced by NewHist(), NewHist2(), NewHist3(), NX(), operator*(), Set(), and SetBinning().
fSelection
TString ejungwoo::Binning::fSelection
Definition at line 326 of file macros_detectorplane/ejungwooA.h.
Referenced by GetSelection(), operator*(), Set(), and SetSelection().
The documentation for this class was generated from the following files:
macros_detectorplane/ejungwooA.h
macros_hough/ejungwooA.h
macros_psa/ejungwooA.h