lilak: Json::Path Class Reference
Json::Path Class Reference
Experimental and untested: represents a "path" to access a node.
#include <json.h>
Public Member Functions
Value & make (Value &root) const
Path (const String &path, const PathArgument &a1=PathArgument(), const PathArgument &a2=PathArgument(), const PathArgument &a3=PathArgument(), const PathArgument &a4=PathArgument(), const PathArgument &a5=PathArgument())
const Value & resolve (const Value &root) const
Value resolve (const Value &root, const Value &defaultValue) const
Private Types
using Args = std::vector< PathArgument >
using InArgs = std::vector< const PathArgument * >
Private Member Functions
void addPathInArg (const String &path, const InArgs &in, InArgs::const_iterator &itInArg, PathArgument::Kind kind)
void makePath (const String &path, const InArgs &in)
Static Private Member Functions
static void invalidPath (const String &path, int location)
Private Attributes
Args args_
Detailed Description
Experimental and untested: represents a "path" to access a node.
Syntax:
"." => root node
".[n]" => elements at index 'n' of root node (an array value)
".name" => member named 'name' of root node (an object value)
".name1.name2.name3"
".[0][1][2].name1[3]"
".%" => member name is provided as parameter
".[%]" => index is provided as parameter
Definition at line 1244 of file json.h.
Member Typedef Documentation
Args
using Json::Path::Args = std::vector<PathArgument> private
Definition at line 1260 of file json.h.
InArgs
using Json::Path::InArgs = std::vector<const PathArgument*> private
Definition at line 1259 of file json.h.
Constructor & Destructor Documentation
Path()
Json::Path::Path (const String & path, const PathArgument & a1 = PathArgument(), const PathArgument & a2 = PathArgument(), const PathArgument & a3 = PathArgument(), const PathArgument & a4 = PathArgument(), const PathArgument & a5 = PathArgument())
Definition at line 3939 of file jsoncpp.cpp.
References makePath().
Member Function Documentation
addPathInArg()
void Json::Path::addPathInArg (const String & path, const InArgs & in, InArgs::const_iterator & itInArg, PathArgument::Kind kind) private
Definition at line 3983 of file jsoncpp.cpp.
References args_.
Referenced by makePath().
invalidPath()
void Json::Path::invalidPath (const String & path, int location) static private
Definition at line 3995 of file jsoncpp.cpp.
Referenced by makePath().
make()
Value & Json::Path::make (Value & root) const
Creates the "path" to access the specified node and returns a reference on the node.
Definition at line 4042 of file jsoncpp.cpp.
References args_, Json::Value::isArray(), Json::Value::isObject(), Json::PathArgument::kindIndex, and Json::PathArgument::kindKey.
makePath()
void Json::Path::makePath (const String & path, const InArgs & in) private
Definition at line 3952 of file jsoncpp.cpp.
References addPathInArg(), args_, invalidPath(), Json::PathArgument::kindIndex, and Json::PathArgument::kindKey.
Referenced by Path().
resolve() [1/2]
const Value & Json::Path::resolve (const Value & root) const
Definition at line 3999 of file jsoncpp.cpp.
References args_, Json::Value::isArray(), Json::Value::isObject(), Json::Value::isValidIndex(), Json::PathArgument::kindIndex, Json::PathArgument::kindKey, and Json::Value::nullSingleton().
resolve() [2/2]
Value Json::Path::resolve (const Value & root, const Value & defaultValue) const
Definition at line 4024 of file jsoncpp.cpp.
References args_, Json::Value::isArray(), Json::Value::isObject(), Json::Value::isValidIndex(), Json::PathArgument::kindIndex, Json::PathArgument::kindKey, and Json::Value::nullSingleton().
Member Data Documentation
args_
Args Json::Path::args_ private
Definition at line 1267 of file json.h.
Referenced by addPathInArg(), make(), makePath(), resolve(), and resolve().
The documentation for this class was generated from the following files:
json.h
jsoncpp.cpp