lilak: LKGeoBox Class Reference
LKGeoBox Class Reference
#include <LKGeoBox.h>
Public Member Functions
virtual void Clear (Option_t *option="")
virtual void Copy (LKGeoBox *box) const
TGraph * Draw2DBox (axis_t axis1=LKVector3::kX, axis_t axis2=LKVector3::kY)
TVector3 GetCenter () const
TVector3 GetCorner (Int_t idx) const
TVector3 GetCorner (Int_t xpm, Int_t ypm, Int_t zpm) const
pm should be 1(high) or -1(low)
bool GetCrossingPoints (LKGeoLine line, TVector3 &point1, TVector3 &point2) const
Double_t GetdX () const
Double_t GetdY () const
Double_t GetdZ () const
LKGeoLine GetEdge (Int_t idx) const
LKGeoLine GetEdge (Int_t idxCorner1, Int_t idxCorner2) const
LKGeoLine GetEdge (Int_t xpm, Int_t ypm, Int_t zpm) const
pm of edge axis is 0 while the other two should be 1(high) or -1(low)
LKGeo2DBox GetFace (axis_t xaxis, axis_t yaxis) const
LKGeoPlaneWithCenter GetPlane (axis_t xaxis, axis_t yaxis) const
LKGeoPlaneWithCenter GetPlane (Int_t axis) const
bool IsInside (Double_t x, Double_t y, Double_t z) const
bool IsInside (TVector3 pos) const
LKGeoBox ()
LKGeoBox (Double_t xc, Double_t yc, Double_t zc, Double_t dx, Double_t dy, Double_t dz)
LKGeoBox (TVector3 center, TVector3 length)
virtual void Print (Option_t *option="") const
virtual void SetBox (Double_t xc, Double_t yc, Double_t zc, Double_t dx, Double_t dy, Double_t dz)
virtual void SetBox (TVector3 center, TVector3 length)
bool TestPointInsidePlane (int iPlane, TVector3 point) const
virtual ~LKGeoBox ()
Public Member Functions inherited from LKGeoRotated
virtual void Clear (Option_t *option="")
virtual TVector3 GetCenter () const
TRotation GetRotation () const
TVector3 InvRotate (TVector3 pos) const
LKGeoRotated ()
TVector3 Rotate (TVector3 pos) const
void SetRotation (TRotation rot)
virtual ~LKGeoRotated ()
Public Member Functions inherited from LKGeometry
Double_t GetRMS () const
LKGeometry ()
void SetRMS (Double_t val)
virtual ~LKGeometry ()
Protected Attributes
Double_t fdX
Double_t fdY
Double_t fdZ
Double_t fX
Double_t fY
Double_t fZ
Protected Attributes inherited from LKGeoRotated
TRotation fRotation
Protected Attributes inherited from LKGeometry
Double_t fRMS = -1
Detailed Description
Definition at line 14 of file LKGeoBox.h.
Constructor & Destructor Documentation
LKGeoBox() [1/3]
LKGeoBox::LKGeoBox ()
LKGeoBox() [2/3]
LKGeoBox::LKGeoBox (Double_t xc, Double_t yc, Double_t zc, Double_t dx, Double_t dy, Double_t dz)
Definition at line 14 of file LKGeoBox.cpp.
References SetBox().
LKGeoBox() [3/3]
LKGeoBox::LKGeoBox (TVector3 center, TVector3 length)
Definition at line 19 of file LKGeoBox.cpp.
References SetBox().
~LKGeoBox()
virtual LKGeoBox::~LKGeoBox () inline virtual
Definition at line 20 of file LKGeoBox.h.
Member Function Documentation
Clear()
void LKGeoBox::Clear (Option_t * option = "") virtual
Reimplemented from LKGeoRotated.
Definition at line 58 of file LKGeoBox.cpp.
References LKGeoRotated::Clear(), fdX, fdY, fdZ, fX, fY, and fZ.
Copy()
void LKGeoBox::Copy (LKGeoBox * box) const virtual
Definition at line 53 of file LKGeoBox.cpp.
References fdX, fdY, fdZ, fX, fY, fZ, and SetBox().
Draw2DBox()
TGraph * LKGeoBox::Draw2DBox (axis_t axis1 = LKVector3::kX, axis_t axis2 = LKVector3::kY)
Definition at line 242 of file LKGeoBox.cpp.
References LKGeo2DBox::DrawGraph(), and GetFace().
Referenced by LKGeoBoxStack::DrawStackGraph().
GetCenter()
TVector3 LKGeoBox::GetCenter () const virtual
Reimplemented from LKGeoRotated.
Definition at line 89 of file LKGeoBox.cpp.
References fX, fY, and fZ.
GetCorner() [1/2]
TVector3 LKGeoBox::GetCorner (Int_t idx) const
Definition at line 95 of file LKGeoBox.cpp.
References fdX, fdY, fdZ, fX, fY, and fZ.
Referenced by GetEdge(), GetEdge(), GetEdge(), GetFace(), GetPlane(), and TestPointInsidePlane().
GetCorner() [2/2]
TVector3 LKGeoBox::GetCorner (Int_t xpm, Int_t ypm, Int_t zpm) const
pm should be 1(high) or -1(low)
Definition at line 108 of file LKGeoBox.cpp.
References fdX, fdY, fdZ, fX, fY, and fZ.
GetCrossingPoints()
bool LKGeoBox::GetCrossingPoints (LKGeoLine line, TVector3 & point1, TVector3 & point2) const
Definition at line 208 of file LKGeoBox.cpp.
References GetPlane(), and TestPointInsidePlane().
Referenced by LKHTTrackingTask::Exec(), and TTHTTrackingTask::MakeTrack().
GetdX()
Double_t LKGeoBox::GetdX () const
Definition at line 91 of file LKGeoBox.cpp.
References fdX.
GetdY()
Double_t LKGeoBox::GetdY () const
Definition at line 92 of file LKGeoBox.cpp.
References fdY.
GetdZ()
Double_t LKGeoBox::GetdZ () const
Definition at line 93 of file LKGeoBox.cpp.
References fdZ.
GetEdge() [1/3]
LKGeoLine LKGeoBox::GetEdge (Int_t idx) const
Definition at line 116 of file LKGeoBox.cpp.
References c1, and GetCorner().
GetEdge() [2/3]
LKGeoLine LKGeoBox::GetEdge (Int_t idxCorner1, Int_t idxCorner2) const
Definition at line 123 of file LKGeoBox.cpp.
References GetCorner().
GetEdge() [3/3]
LKGeoLine LKGeoBox::GetEdge (Int_t xpm, Int_t ypm, Int_t zpm) const
pm of edge axis is 0 while the other two should be 1(high) or -1(low)
Definition at line 128 of file LKGeoBox.cpp.
References GetCorner().
GetFace()
LKGeo2DBox LKGeoBox::GetFace (axis_t xaxis, axis_t yaxis) const
Definition at line 137 of file LKGeoBox.cpp.
References GetCorner().
Referenced by LKGeoBoxStack::DrawStackHistPoly().
GetPlane() [1/2]
LKGeoPlaneWithCenter LKGeoBox::GetPlane (axis_t xaxis, axis_t yaxis) const
Definition at line 153 of file LKGeoBox.cpp.
References GetPlane().
Referenced by GetCrossingPoints(), and GetPlane().
GetPlane() [2/2]
LKGeoPlaneWithCenter LKGeoBox::GetPlane (Int_t axis) const
+X = 0 -X = 1 +Y = 2 -Y = 3 +Z = 4 -Z = 5
Definition at line 159 of file LKGeoBox.cpp.
References GetCorner(), LKVector3::GetXYZ(), LKVector3::kMX, LKVector3::kMY, LKVector3::kMZ, LKVector3::kX, LKVector3::kY, LKVector3::kZ, and LKVector3::SetAt().
IsInside() [1/2]
bool LKGeoBox::IsInside (Double_t x, Double_t y, Double_t z) const
Definition at line 252 of file LKGeoBox.cpp.
References fdX, fdY, fdZ, fX, fY, fZ, and x.
IsInside() [2/2]
bool LKGeoBox::IsInside (TVector3 pos) const
Definition at line 247 of file LKGeoBox.cpp.
References IsInside().
Referenced by IsInside().
Print()
void LKGeoBox::Print (Option_t * option = "") const virtual
Definition at line 24 of file LKGeoBox.cpp.
References e_cout, fdX, fdY, fdZ, fX, fY, and fZ.
SetBox() [1/2]
void LKGeoBox::SetBox (Double_t xc, Double_t yc, Double_t zc, Double_t dx, Double_t dy, Double_t dz) virtual
Definition at line 69 of file LKGeoBox.cpp.
References fdX, fdY, fdZ, fX, fY, and fZ.
Referenced by Copy(), LKGeoBox(), and LKGeoBox().
SetBox() [2/2]
void LKGeoBox::SetBox (TVector3 center, TVector3 length) virtual
Definition at line 79 of file LKGeoBox.cpp.
References fdX, fdY, fdZ, fX, fY, and fZ.
TestPointInsidePlane()
bool LKGeoBox::TestPointInsidePlane (int iPlane, TVector3 point) const
Definition at line 178 of file LKGeoBox.cpp.
References GetCorner().
Referenced by GetCrossingPoints().
Member Data Documentation
fdX
Double_t LKGeoBox::fdX protected
Definition at line 65 of file LKGeoBox.h.
Referenced by Clear(), Copy(), GetCorner(), GetCorner(), GetdX(), IsInside(), Print(), SetBox(), and SetBox().
fdY
Double_t LKGeoBox::fdY protected
Definition at line 66 of file LKGeoBox.h.
Referenced by Clear(), Copy(), GetCorner(), GetCorner(), GetdY(), IsInside(), Print(), SetBox(), and SetBox().
fdZ
Double_t LKGeoBox::fdZ protected
Definition at line 67 of file LKGeoBox.h.
Referenced by Clear(), Copy(), GetCorner(), GetCorner(), GetdZ(), IsInside(), Print(), SetBox(), and SetBox().
fX
Double_t LKGeoBox::fX protected
Definition at line 62 of file LKGeoBox.h.
Referenced by Clear(), Copy(), GetCenter(), GetCorner(), GetCorner(), IsInside(), Print(), SetBox(), and SetBox().
fY
Double_t LKGeoBox::fY protected
Definition at line 63 of file LKGeoBox.h.
Referenced by Clear(), Copy(), GetCenter(), GetCorner(), GetCorner(), IsInside(), Print(), SetBox(), and SetBox().
fZ
Double_t LKGeoBox::fZ protected
Definition at line 64 of file LKGeoBox.h.
Referenced by Clear(), Copy(), GetCenter(), GetCorner(), GetCorner(), IsInside(), Print(), SetBox(), and SetBox().
The documentation for this class was generated from the following files:
LKGeoBox.h
LKGeoBox.cpp