lilak: LKHTWeightingFunction Class Reference
LKHTWeightingFunction Class Reference
#include <LKHTLineTracker.h>
Public Member Functions
virtual double EvalFromDistance (double distance, double error, double pointWeight)
virtual double EvalFromPoints (LKImagePoint *imagePoint, LKParamPointRT *paramPoint)
LKHTWeightingFunction ()
~LKHTWeightingFunction ()
Detailed Description
Definition at line 21 of file LKHTLineTracker.h.
Constructor & Destructor Documentation
LKHTWeightingFunction()
LKHTWeightingFunction::LKHTWeightingFunction () inline
Definition at line 24 of file LKHTLineTracker.h.
~LKHTWeightingFunction()
LKHTWeightingFunction::~LKHTWeightingFunction () inline
Definition at line 27 of file LKHTLineTracker.h.
Member Function Documentation
EvalFromDistance()
virtual double LKHTWeightingFunction::EvalFromDistance (double distance, double error, double pointWeight) inline virtual
Reimplemented in LKHoughWFConst, LKHoughWFLinear, and LKHoughWFInverse.
Definition at line 33 of file LKHTLineTracker.h.
Referenced by EvalFromPoints().
EvalFromPoints()
virtual double LKHTWeightingFunction::EvalFromPoints (LKImagePoint * imagePoint, LKParamPointRT * paramPoint) inline virtual
Reimplemented in LKHoughWFGivenWeight, and LKHoughWFConst.
Definition at line 28 of file LKHTLineTracker.h.
References error(), EvalFromDistance(), and LKImagePoint::fWeightHT.
The documentation for this class was generated from the following file:
LKHTLineTracker.h