LILAK: LHPadPlaneYCut Class Reference
LHPadPlaneYCut Class Reference
#include <LHPadPlaneYCut.h>
Public Member Functions
void AddChannel (LKChannel *channel)
Add channel to channel array in detector plane. For interanl use.
void AddHit (LKHit *hit)
void AddHit (LKTpcHit *hit)
void AddPad (LKPad *pad)
Add pad to pad array in detector plane. For interanl use.
void AddPar (LKParameterContainer *par)
void AddPar (TString fname)
virtual void AddParameterContainer (LKParameterContainer *par)
virtual void AddParameterContainer (TString fname)
virtual void Clear (Option_t *option="")
void CreateParameterContainer ()
virtual void Draw (Option_t *option="")
Implementation recommanded for event display. Draw event display to the canvas.
virtual void DrawFrame (Option_t *option="")
virtual void DrawHist ()
virtual void DrawHist (Option_t *option="")
virtual void DriftElectron (TVector3 posGlobal, TVector3 &posFinal, double &driftLength)
virtual TVector3 DriftElectron (TVector3 xGlobal)
return (x,y,l). l : electron-drift-length
virtual double DriftElectronBack (double tb)
virtual void DriftElectronBack (int padID, double tb, TVector3 &posReco, double &driftLength)
virtual void DriftElectronBack (LKPad *pad, double tb, TVector3 &posReco, double &driftLength)
void FillBufferIn (Double_t i, Double_t j, Double_t tb, Double_t val, Int_t trackID=-1)
void FillDataToHist ()
Implementation recommanded. Fill data to histograms.
void FillPlane (double i, double j, double tb, double charge, int trackID=-1)
Find pad corresponding to the position (i,j) and fill time-bin by amount of charge.
virtual int FindChannelID (double i, double j)
Implementation recommanded. Find channel using position.
virtual Int_t FindChannelID (Double_t i, Double_t j)
virtual int FindChannelID (int section, int layer, int row)
Implementation recommanded. Find channel using section, layer, row info.
virtual Int_t FindChannelID (Int_t section, Int_t layer, Int_t row)
virtual int FindPadID (double i, double j)
virtual Int_t FindPadID (Double_t i, Double_t j)
virtual int FindPadID (int cobo, int asad, int aget, int chan)
virtual int FindPadID (int section, int layer, int row)
virtual Int_t FindPadID (Int_t section, Int_t row, Int_t layer)
virtual TPad * Get3DEventPad ()
If user wants to place 3D event display other than default canvas, this method should return corresponding TPad.
virtual axis_t GetAxis1 (int iPad=0) const
virtual axis_t GetAxis2 (int iPad=0) const
virtual axis_t GetAxis3 () const
virtual axis_t GetAxisDrift () const
virtual TCanvas * GetCanvas (Option_t *optiont="")
Implementation recommanded for event display.
LKChannel * GetChannel (int idx)
virtual LKChannelAnalyzer * GetChannelAnalyzer (int id=0)
TObjArray * GetChannelArray ()
LKChannel * GetChannelFast (int idx)
virtual TPad * GetCPad (int iPad)
For grabbing inner pads of canvas.
virtual TH2 * GetHist (Option_t *option="-1")
int GetNChannels ()
virtual int GetNumCPads ()
Get number of inner pads of canvas.
Int_t GetNumLayer () const
Int_t GetNumPads ()
LKPad * GetPad (double i, double j)
LKPad * GetPad (Double_t i, Double_t j)
LKPad * GetPad (int cobo, int asad, int aget, int chan)
LKPad * GetPad (int padID)
LKPad * GetPad (int section, int layer, int row)
LKPad * GetPad (Int_t padID)
LKPad * GetPad (Int_t section, Int_t layer, Int_t row)
TObjArray * GetPadArray ()
double GetPadCenterYBoundAtX (double x)
double GetPadCutBoundaryXAtY (double y)
double GetPadCutBoundaryYAtX (double x)
LKPad * GetPadFast (int idx)
LKPad * GetPadFast (Int_t padID)
Double_t GetPadGap () const
Double_t GetPadHeight () const
Double_t GetPadRSpacing () const
Double_t GetPadWidth () const
Double_t GetPadXSpacing () const
LKParameterContainer * GetPar () const
LKParameterContainer * GetParameterContainer () const
int GetPlaneID () const
double GetPosition () const
Int_t GetRank () const
Double_t GetRMax () const
Double_t GetRMin () const
double GetTbToLength () const
virtual TVector3 GlobalToLocalAxis (TVector3 posGlobal)
Implementation recommanded. Convert global position to local detector plane position.
void GrabNeighborPads (vector< LKPad * > *pads, vector< LKPad * > *neighborPads)
virtual bool Init ()
virtual bool IsInBoundary (double i, double j)
Implementation recommanded. Return if position (i,j) is inside the effective detector plane boundary.
virtual bool IsInBoundary (Double_t i, Double_t j)
LHPadPlaneYCut ()
virtual TVector3 LocalToGlobalAxis (TVector3 posLocal)
virtual Double_t PadDisplacement () const
Return average pad displacement to each other.
bool PadMapChecker ()
bool PadNeighborChecker ()
bool PadPositionChecker (bool checkCorners=true)
virtual void Print (Option_t *option="") const
void PullOutNeighborHits (double x, double y, int range, LKHitArray *neighborHits)
For tracking use.
void PullOutNeighborHits (double x, double y, int range, vector< LKHit * > *neighborHits)
For tracking use.
void PullOutNeighborHits (Double_t x, Double_t y, Int_t range, LKHitArray *neighborHits)
void PullOutNeighborHits (Double_t x, Double_t y, Int_t range, vector< LKTpcHit * > *neighborHits)
void PullOutNeighborHits (LKHitArray *hits, LKHitArray *neighborHits)
void PullOutNeighborHits (TVector2 p, int range, vector< LKHit * > *neighborHits)
For tracking use.
void PullOutNeighborHits (TVector2 p, Int_t range, vector< LKTpcHit * > *neighborHits)
void PullOutNeighborHits (vector< LKHit * > *hits, vector< LKHit * > *neighborHits)
For tracking use.
void PullOutNeighborHits (vector< LKTpcHit * > *hits, vector< LKTpcHit * > *neighborHits)
virtual LKTpcHit * PullOutNextFreeHit ()
For tracking use.
virtual void ResetEvent ()
For tracking use.
virtual void ResetHitMap ()
For tracking use.
virtual bool SetDataFromBranch ()
Implementation recommanded. Set waveform and hit data from input tree branches to pads.
void SetDetector (LKDetector *detector)
void SetHitArray (TClonesArray *hitArray)
void SetPadArray (TClonesArray *padArray)
void SetPar (LKParameterContainer *par)
virtual void SetParameterContainer (LKParameterContainer *par)
void SetPlaneID (int id)
virtual void SetRank (Int_t rank)
void SetRun (LKRun *run)
virtual TVector3 TbToGlobalPosition (LKPad *pad, int tb)
virtual ~LHPadPlaneYCut ()
Protected Attributes
axis_t fAxis1 = LKVector3::kNon
Axis-1 lying in plane. Must be set by input parameter.
axis_t fAxis2 = LKVector3::kNon
Axis-2 lying in plane. Must be set by input parameter.
axis_t fAxis3 = LKVector3::kNon
Axis-3 = Axis-1 x Axis-2 perpendicular to plane.
axis_t fAxisDrift = LKVector3::kNon
Axis perpendicular to plane, in electron drifting direction. Must be set by input parameter.
TCanvas * fCanvas = nullptr
LKChannelAnalyzer * fChannelAnalyzer = nullptr
TObjArray * fChannelArray = nullptr
TCanvas * fCvsChannelBuffer = nullptr
LKDetector * fDetector = nullptr
Int_t fEFieldAxis = -1
bool fFilledHit = false
bool fFilledPad = false
Int_t fFreePadIdx = 0
TGraph * fGraphChannelBoundary = nullptr
TGraph * fGraphChannelBoundaryNb [20] = {0}
TH2 * fH2Plane = nullptr
bool fHitDataIsSet = false
bool fPadDataIsSet = false
LKParameterContainer * fPar = nullptr
int fPlaneID = -1
Detector plane id.
double fPosition
Global position of pad plane center.
Int_t fRank = 0
LKRun * fRun = nullptr
double fTbToLength = 1
time-bin (tb) to position conversion factor. Must be set by input parameter.
Private Member Functions
virtual void ClickedAtPosition (Double_t x, Double_t y)
Int_t FindSection (Double_t i, Double_t j)
LKPad * NewPad (Int_t s, Int_t r, Int_t l)
void SetNeighborPads (LKPad *pad0, LKPad *pad1)
Private Attributes
Double_t fCosPiNo4 [8]
const Bool_t fDoCutSideBoundary = true
const Bool_t fDoCutTopBoundary = true
TF1 * fFuncXRightBound = nullptr
TF1 * fFuncXRightBoundInverse = nullptr
int fNumHalfRowsInLayer [50] = {0}
Int_t fNumLayers = 42
int fNumPadsDownToLayer [50] = {0}
in single section
int fNumSkippedHalfRows [50] = {0}
Double_t fPadGap = 0.5
Double_t fPadHeight = 10.
Double_t fPadWidth = 3.
Double_t fRadiusLayer0 = 110.
Double_t fRMax = 510.
Double_t fRMin = 100.
Double_t fRSpacing
Double_t fRTopCut = 506.
Double_t fSinPiNo4 [8]
Double_t fTanPi1o8
Double_t fTanPi3o8
Double_t fTanPi5o8
Double_t fTanPi7o8
Double_t fXSpacing
Detailed Description
Definition at line 7 of file LHPadPlaneYCut.h.
Constructor & Destructor Documentation
LHPadPlaneYCut()
LHPadPlaneYCut::LHPadPlaneYCut ()
~LHPadPlaneYCut()
virtual LHPadPlaneYCut::~LHPadPlaneYCut () inline virtual
Definition at line 11 of file LHPadPlaneYCut.h.
Member Function Documentation
AddChannel()
void LKDetectorPlane::AddChannel (LKChannel * channel) inline inherited
Add channel to channel array in detector plane. For interanl use.
Definition at line 113 of file LKDetectorPlane.h.
References LKDetectorPlane::fChannelArray.
AddHit() [1/2]
void LKDetectorPlane::AddHit (LKHit * hit) inherited
Definition at line 118 of file LKDetectorPlane.cpp.
References LKDetectorPlane::AddHit(), and LKDetectorPlane::GetPadFast().
Referenced by LKDetectorPlane::AddHit(), and LKDetectorPlane::SetHitArray().
AddHit() [2/2]
void LKPadPlane::AddHit (LKTpcHit * hit) inherited
Definition at line 101 of file LKPadPlane.cpp.
References LKPadPlane::AddHit(), and LKPadPlane::GetPadFast().
Referenced by LKPadPlane::AddHit(), and LKPadPlane::SetHitArray().
AddPad()
void LKDetectorPlane::AddPad (LKPad * pad) inline inherited
Add pad to pad array in detector plane. For interanl use.
Definition at line 114 of file LKDetectorPlane.h.
References LKDetectorPlane::fChannelArray.
AddPar() [1/2]
void LKGear::AddPar (LKParameterContainer * par) inline inherited
Definition at line 27 of file LKGear.h.
References LKGear::AddParameterContainer().
Referenced by LKTask::Add(), LKRun::EndOfRun(), LKRun::Init(), LKG4RunManager::Initialize(), LAMPSTPC::LAMPSTPC(), LAMPSTPC::LAMPSTPC(), LKDetectorSystem::SetDetectorPar(), LKRun::SetEventTrigger(), LKG4RunManager::SetSensitiveDetector(), LKG4RunManager::SetVolume(), LKRun::StartOfRun(), TexAT2::TexAT2(), TexAT2::TexAT2(), and TTMicromegas::WriteCurrentChannel().
AddPar() [2/2]
void LKGear::AddPar (TString fname) inline inherited
Definition at line 28 of file LKGear.h.
References LKGear::AddParameterContainer().
AddParameterContainer() [1/2]
void LKGear::AddParameterContainer (LKParameterContainer * par) virtual inherited
Definition at line 14 of file LKGear.cpp.
References LKGear::AddParameterContainer(), and LKGear::fPar.
Referenced by LKGear::AddPar(), LKGear::AddPar(), LKGear::AddParameterContainer(), LHTpc::BuildDetectorPlane(), and LKRun::Init().
AddParameterContainer() [2/2]
void LKGear::AddParameterContainer (TString fname) virtual inherited
Definition at line 22 of file LKGear.cpp.
References LKGear::fPar.
Clear()
void LKPadPlane::Clear (Option_t * option = "") virtual inherited
Reimplemented from LKDetectorPlane.
Reimplemented in TTFrontPlane.
Definition at line 228 of file LKPadPlane.cpp.
References LKPadPlane::Clear(), LKDetectorPlane::fChannelArray, LKPadPlane::fFilledHit, and LKPadPlane::fFilledPad.
Referenced by LKPadPlane::Clear(), TTFrontPlane::Clear(), LKPadPlane::DrawHist(), and LKPadPlane::SetDataFromBranch().
ClickedAtPosition()
void LKPadPlane::ClickedAtPosition (Double_t x, Double_t y) private virtual inherited
Definition at line 615 of file LKPadPlane.cpp.
CreateParameterContainer()
void LKGear::CreateParameterContainer () inherited
Referenced by LKRun::AddDetector(), and LKRun::LKRun().
Draw()
void LKDetectorPlane::Draw (Option_t * option = "") virtual inherited
Implementation recommanded for event display. Draw event display to the canvas.
Reimplemented in LKEvePlane, TTMicromegas, TTFrontPlane, ATTPC20RectanglePad, ATTPCHoneyCombPad, ATTPCRectanglePad, and ATTPCStripPad.
Definition at line 660 of file LKDetectorPlane.cpp.
References LKDetectorPlane::Clear(), cvs, LKDetectorPlane::Draw(), LKDetectorPlane::DrawFrame(), LKDetectorPlane::FillDataToHist(), LKDetectorPlane::GetCanvas(), LKDetectorPlane::GetHist(), and LKDetectorPlane::SetDataFromBranch().
Referenced by LKDetectorPlane::Draw(), LHPadPlaneFan::DrawFrame(), LHPadPlaneRCut::DrawFrame(), LKPadPlane::DrawHist(), and LKDetectorPlane::DrawHist().
DrawFrame()
void LHPadPlaneYCut::DrawFrame (Option_t * option = "") virtual
Reimplemented from LKDetectorPlane.
Definition at line 325 of file LHPadPlaneYCut.cpp.
DrawHist() [1/2]
void LKPadPlane::DrawHist () virtual inherited
Definition at line 285 of file LKPadPlane.cpp.
References LKParameterContainer::CheckPar(), LKPadPlane::Clear(), LKDetectorPlane::Draw(), LKDetectorPlane::DrawFrame(), LKDetectorPlane::fCanvas, LKPadPlane::FillDataToHist(), LKGear::fPar, LKDetectorPlane::GetHist(), and LKParameterContainer::GetParDouble().
DrawHist() [2/2]
void LKDetectorPlane::DrawHist (Option_t * option = "") virtual inherited
Reimplemented in LKEvePlane.
Definition at line 635 of file LKDetectorPlane.cpp.
References LKDetectorPlane::Clear(), LKDetectorPlane::Draw(), LKDetectorPlane::DrawFrame(), LKDetectorPlane::fCanvas, LKDetectorPlane::FillDataToHist(), LKDetectorPlane::GetCanvas(), and LKDetectorPlane::GetHist().
DriftElectron() [1/2]
void LKDetectorPlane::DriftElectron (TVector3 posGlobal, TVector3 & posFinal, double & driftLength) virtual inherited
Implementation recommanded. Return position (x,y,z). x,y is pad position in pad plane. z is pad plane position of electron-drift-axis (for simulation)
Parameters
posGlobal[in] Given global position of the electron.
posFinal[in] Final position of electron after full drift (at the pad plane).
driftLength[out] Final drift length of the electron
Definition at line 679 of file LKDetectorPlane.cpp.
References LKVector3::At(), LKDetectorPlane::fAxis1, LKDetectorPlane::fAxis2, LKDetectorPlane::fAxis3, and LKDetectorPlane::fPosition.
DriftElectron() [2/2]
TVector3 LKPadPlane::DriftElectron (TVector3 xGlobal) virtual inherited
return (x,y,l). l : electron-drift-length
Definition at line 707 of file LKPadPlane.cpp.
References LKDetectorPlane::GlobalToLocalAxis().
DriftElectronBack() [1/3]
double LKDetectorPlane::DriftElectronBack (double tb) virtual inherited
Implementation recommanded. return drift length
Definition at line 708 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fPosition, and LKDetectorPlane::fTbToLength.
DriftElectronBack() [2/3]
void LKDetectorPlane::DriftElectronBack (int padID, double tb, TVector3 & posReco, double & driftLength) virtual inherited
Reimplemented in LKEvePlane.
Definition at line 702 of file LKDetectorPlane.cpp.
References LKDetectorPlane::DriftElectronBack(), and LKDetectorPlane::GetPad().
DriftElectronBack() [3/3]
void LKDetectorPlane::DriftElectronBack (LKPad * pad, double tb, TVector3 & posReco, double & driftLength) virtual inherited
Implementation recommanded. Set poseReco to global position using pad position, and time-bin tb. Pad position must be set from Init(). Conversion from time-bin (tb) to position in time-axis (post) is calculated by : post = fTbToLength * tb + fPosition [fTbToLength] is tb to position conversion factor with direction and [fPosition] is detector plane position in time-axis.
Parameters
pad[in] channel (pad)
tb[in] Time-bin
posReco[out] Reconstructed position of electron(?) before drift.
driftLength[out] Drift length of the electron from the reconstructed position.
Definition at line 689 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fAxis3, LKDetectorPlane::fAxisDrift, LKDetectorPlane::fPosition, LKDetectorPlane::fTbToLength, LKPad::GetI(), LKPad::GetJ(), LKVector3::GetXYZ(), LKVector3::SetI(), LKVector3::SetJ(), and LKVector3::SetK().
Referenced by LKDetectorPlane::DriftElectronBack().
FillBufferIn()
void LKPadPlane::FillBufferIn (Double_t i, Double_t j, Double_t tb, Double_t val, Int_t trackID = -1) inherited
Definition at line 108 of file LKPadPlane.cpp.
References LKDetectorPlane::fChannelArray, LKPadPlane::FillBufferIn(), and LKPadPlane::FindPadID().
Referenced by LKPadPlane::FillBufferIn().
FillDataToHist()
void LKPadPlane::FillDataToHist () virtual inherited
Implementation recommanded. Fill data to histograms.
Reimplemented from LKDetectorPlane.
Reimplemented in TTFrontPlane.
Definition at line 119 of file LKPadPlane.cpp.
References LKDetectorPlane::fChannelArray, LKPadPlane::fFilledHit, LKPadPlane::fFilledPad, LKDetectorPlane::fH2Plane, LKGear::fPar, LKDetectorPlane::GetHist(), LKPad::GetI(), LKPad::GetJ(), LKPad::GetLayer(), GETChannel::GetNumHits(), LKChannel::GetPadID(), LKPad::GetRow(), LKPad::GetSection(), lk_error, and lk_info.
Referenced by LKPadPlane::DrawHist().
FillPlane()
void LKDetectorPlane::FillPlane (double i, double j, double tb, double charge, int trackID = -1) inherited
Find pad corresponding to the position (i,j) and fill time-bin by amount of charge.
Definition at line 125 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fChannelArray, and LKDetectorPlane::FindPadID().
FindChannelID() [1/4]
virtual int LKDetectorPlane::FindChannelID (double i, double j) inline virtual inherited
Implementation recommanded. Find channel using position.
Reimplemented in LKEvePlane.
Definition at line 121 of file LKDetectorPlane.h.
Referenced by LKDetectorPlane::FindPadID(), and LKDetectorPlane::FindPadID().
FindChannelID() [2/4]
virtual Int_t LKPadPlane::FindChannelID (Double_t i, Double_t j) inline virtual inherited
Reimplemented in TTFrontPlane.
Definition at line 45 of file LKPadPlane.h.
Referenced by LKPadPlane::FindPadID(), and LKPadPlane::FindPadID().
FindChannelID() [3/4]
virtual int LKDetectorPlane::FindChannelID (int section, int layer, int row) inline virtual inherited
Implementation recommanded. Find channel using section, layer, row info.
Reimplemented in LKEvePlane.
Definition at line 122 of file LKDetectorPlane.h.
FindChannelID() [4/4]
virtual Int_t LKPadPlane::FindChannelID (Int_t section, Int_t layer, Int_t row) inline virtual inherited
Reimplemented in TTFrontPlane.
Definition at line 46 of file LKPadPlane.h.
FindPadID() [1/5]
virtual int LKDetectorPlane::FindPadID (double i, double j) inline virtual inherited
Reimplemented in LTPadPlane.
Definition at line 123 of file LKDetectorPlane.h.
References LKDetectorPlane::FindChannelID().
Referenced by LKDetectorPlane::FillPlane(), LKDetectorPlane::GetPad(), LKDetectorPlane::GetPad(), LKDetectorPlane::GetPad(), LKDetectorPlane::PadMapChecker(), LKDetectorPlane::PadPositionChecker(), LKDetectorPlane::PullOutNeighborHits(), and LKDetectorPlane::PullOutNeighborHits().
FindPadID() [2/5]
Int_t LHPadPlaneYCut::FindPadID (Double_t i, Double_t j) virtual
Reimplemented from LKPadPlane.
Definition at line 210 of file LHPadPlaneYCut.cpp.
References fCosPiNo4, FindPadID(), FindSection(), fNumHalfRowsInLayer, fNumLayers, fNumSkippedHalfRows, fPadGap, fPadHeight, fPadWidth, fRadiusLayer0, fRSpacing, fSinPiNo4, and fXSpacing.
Referenced by FindPadID().
FindPadID() [3/5]
virtual int LKDetectorPlane::FindPadID (int cobo, int asad, int aget, int chan) inline virtual inherited
Reimplemented in ATMicromegas, LTPadPlane, and LKEvePlane.
Definition at line 125 of file LKDetectorPlane.h.
FindPadID() [4/5]
virtual int LKDetectorPlane::FindPadID (int section, int layer, int row) inline virtual inherited
Reimplemented in LTPadPlane.
Definition at line 124 of file LKDetectorPlane.h.
References LKDetectorPlane::FindChannelID().
FindPadID() [5/5]
Int_t LHPadPlaneYCut::FindPadID (Int_t section, Int_t row, Int_t layer) virtual
Reimplemented from LKPadPlane.
Definition at line 200 of file LHPadPlaneYCut.cpp.
References fNumHalfRowsInLayer, fNumLayers, and fNumPadsDownToLayer.
FindSection()
Int_t LHPadPlaneYCut::FindSection (Double_t i, Double_t j) private
Definition at line 352 of file LHPadPlaneYCut.cpp.
References fTanPi1o8, fTanPi3o8, fTanPi5o8, and fTanPi7o8.
Referenced by FindPadID().
Get3DEventPad()
virtual TPad * LKDetectorPlane::Get3DEventPad () inline virtual inherited
If user wants to place 3D event display other than default canvas, this method should return corresponding TPad.
Reimplemented in ATMicromegas, and LKEvePlane.
Definition at line 82 of file LKDetectorPlane.h.
GetAxis1()
virtual axis_t LKDetectorPlane::GetAxis1 (int iPad = 0) const inline virtual inherited
Reimplemented in LKEvePlane.
Definition at line 60 of file LKDetectorPlane.h.
References LKDetectorPlane::fAxis1.
Referenced by LKTracklet::TrajectoryOnPlane().
GetAxis2()
virtual axis_t LKDetectorPlane::GetAxis2 (int iPad = 0) const inline virtual inherited
Reimplemented in LKEvePlane.
Definition at line 61 of file LKDetectorPlane.h.
References LKDetectorPlane::fAxis2.
Referenced by LKTracklet::TrajectoryOnPlane().
GetAxis3()
virtual axis_t LKDetectorPlane::GetAxis3 () const inline virtual inherited
Definition at line 62 of file LKDetectorPlane.h.
References LKDetectorPlane::fAxis3.
GetAxisDrift()
virtual axis_t LKDetectorPlane::GetAxisDrift () const inline virtual inherited
Definition at line 63 of file LKDetectorPlane.h.
References LKDetectorPlane::fAxisDrift.
GetCanvas()
TCanvas * LHPadPlaneYCut::GetCanvas (Option_t * option = "") virtual
Implementation recommanded for event display.
Reimplemented from LKDetectorPlane.
Definition at line 329 of file LHPadPlaneYCut.cpp.
References LKDetectorPlane::fCanvas, and LKDetectorPlane::fPlaneID.
GetChannel()
LKChannel * LKDetectorPlane::GetChannel (int idx) inherited
Definition at line 47 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fChannelArray.
GetChannelAnalyzer()
LKChannelAnalyzer * LKDetectorPlane::GetChannelAnalyzer (int id = 0) virtual inherited
Reimplemented in LTPadPlane, and LKEvePlane.
Definition at line 714 of file LKDetectorPlane.cpp.
References LKParameterContainer::CheckPar(), LKDetectorPlane::fChannelAnalyzer, LKGear::fPar, and LKDetectorPlane::Print().
Referenced by TTMicromegas::SelectAndDrawChannel(), and TTFrontPlane::SelectAndDrawChannel().
GetChannelArray()
TObjArray * LKDetectorPlane::GetChannelArray () inline inherited
Definition at line 118 of file LKDetectorPlane.h.
References LKDetectorPlane::fChannelArray.
GetChannelFast()
LKChannel * LKDetectorPlane::GetChannelFast (int idx) inline inherited
Definition at line 126 of file LKDetectorPlane.h.
References LKDetectorPlane::fChannelArray.
GetCPad()
virtual TPad * LKDetectorPlane::GetCPad (int iPad) inline virtual inherited
For grabbing inner pads of canvas.
Reimplemented in LKEvePlane, and TTMicromegas.
Definition at line 81 of file LKDetectorPlane.h.
References LKDetectorPlane::GetCanvas().
GetHist()
TH2 * LHPadPlaneYCut::GetHist (Option_t * option = "-1") virtual
Reimplemented from LKDetectorPlane.
Definition at line 262 of file LHPadPlaneYCut.cpp.
References LKDetectorPlane::fChannelArray, LKDetectorPlane::fH2Plane, and fRTopCut.
GetNChannels()
int LKDetectorPlane::GetNChannels () inline inherited
Definition at line 116 of file LKDetectorPlane.h.
References LKDetectorPlane::fChannelArray.
Referenced by LKDetectorPlane::GetNumPads(), and LKPadPlane::GetNumPads().
GetNumCPads()
virtual int LKDetectorPlane::GetNumCPads () inline virtual inherited
Get number of inner pads of canvas.
Reimplemented in LKEvePlane, and TTMicromegas.
Definition at line 80 of file LKDetectorPlane.h.
GetNumLayer()
Int_t LHPadPlaneYCut::GetNumLayer () const inline
Definition at line 72 of file LHPadPlaneYCut.h.
References fNumLayers.
GetNumPads()
Int_t LKPadPlane::GetNumPads () inherited
Definition at line 226 of file LKPadPlane.cpp.
References LKDetectorPlane::GetNChannels().
GetPad() [1/7]
LKPad * LKDetectorPlane::GetPad (double i, double j) inherited
Definition at line 61 of file LKDetectorPlane.cpp.
References LKDetectorPlane::FindPadID(), and LKDetectorPlane::GetPad().
GetPad() [2/7]
LKPad * LKPadPlane::GetPad (Double_t i, Double_t j) inherited
Definition at line 50 of file LKPadPlane.cpp.
References LKPadPlane::FindPadID(), and LKPadPlane::GetPad().
GetPad() [3/7]
LKPad * LKDetectorPlane::GetPad (int cobo, int asad, int aget, int chan) inherited
Definition at line 77 of file LKDetectorPlane.cpp.
References LKDetectorPlane::FindPadID(), and LKDetectorPlane::GetPad().
GetPad() [4/7]
LKPad * LKDetectorPlane::GetPad (int padID) inherited
Definition at line 54 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fChannelArray.
Referenced by LKDetectorPlane::DriftElectronBack(), LKDetectorPlane::GetPad(), LKDetectorPlane::GetPad(), LKDetectorPlane::GetPad(), and LTPadPlane::Init().
GetPad() [5/7]
LKPad * LKDetectorPlane::GetPad (int section, int layer, int row) inherited
Definition at line 69 of file LKDetectorPlane.cpp.
References LKDetectorPlane::FindPadID(), and LKDetectorPlane::GetPad().
GetPad() [6/7]
LKPad * LKPadPlane::GetPad (Int_t padID) inherited
Definition at line 41 of file LKPadPlane.cpp.
References LKDetectorPlane::fChannelArray.
Referenced by LKPadPlane::GetPad(), LKPadPlane::GetPad(), and Init().
GetPad() [7/7]
LKPad * LKPadPlane::GetPad (Int_t section, Int_t layer, Int_t row) inherited
Definition at line 59 of file LKPadPlane.cpp.
References LKPadPlane::FindPadID(), and LKPadPlane::GetPad().
GetPadArray()
TObjArray * LKPadPlane::GetPadArray () inherited
Definition at line 465 of file LKPadPlane.cpp.
References LKDetectorPlane::fChannelArray.
GetPadCenterYBoundAtX()
double LHPadPlaneYCut::GetPadCenterYBoundAtX (double x) inline
Definition at line 65 of file LHPadPlaneYCut.h.
References fTanPi3o8.
Referenced by Init().
GetPadCutBoundaryXAtY()
double LHPadPlaneYCut::GetPadCutBoundaryXAtY (double y) inline
Definition at line 64 of file LHPadPlaneYCut.h.
References fTanPi3o8.
Referenced by Init().
GetPadCutBoundaryYAtX()
double LHPadPlaneYCut::GetPadCutBoundaryYAtX (double x) inline
Definition at line 63 of file LHPadPlaneYCut.h.
References fTanPi3o8.
Referenced by Init().
GetPadFast() [1/2]
LKPad * LKDetectorPlane::GetPadFast (int idx) inline inherited
Definition at line 127 of file LKDetectorPlane.h.
References LKDetectorPlane::fChannelArray.
Referenced by LKDetectorPlane::AddHit(), LKDetectorPlane::SetHitArray(), and LKDetectorPlane::SetPadArray().
GetPadFast() [2/2]
LKPad * LKPadPlane::GetPadFast (Int_t padID) inherited
Definition at line 39 of file LKPadPlane.cpp.
References LKDetectorPlane::fChannelArray.
Referenced by LKPadPlane::AddHit(), LKPadPlane::SetHitArray(), and LKPadPlane::SetPadArray().
GetPadGap()
Double_t LHPadPlaneYCut::GetPadGap () const inline
Definition at line 69 of file LHPadPlaneYCut.h.
References fPadGap.
GetPadHeight()
Double_t LHPadPlaneYCut::GetPadHeight () const inline
Definition at line 71 of file LHPadPlaneYCut.h.
References fPadHeight.
GetPadRSpacing()
Double_t LHPadPlaneYCut::GetPadRSpacing () const inline
Definition at line 74 of file LHPadPlaneYCut.h.
References fRSpacing.
GetPadWidth()
Double_t LHPadPlaneYCut::GetPadWidth () const inline
Definition at line 70 of file LHPadPlaneYCut.h.
References fPadWidth.
GetPadXSpacing()
Double_t LHPadPlaneYCut::GetPadXSpacing () const inline
Definition at line 73 of file LHPadPlaneYCut.h.
References fXSpacing.
GetPar()
LKParameterContainer * LKGear::GetPar () const inherited
Definition at line 33 of file LKGear.cpp.
References LKGear::fPar.
GetParameterContainer()
LKParameterContainer * LKGear::GetParameterContainer () const inherited
Definition at line 32 of file LKGear.cpp.
References LKGear::fPar.
Referenced by ClassImp(), LHElectronicsTask::Init(), and LHVertexFindingTask::Init().
GetPlaneID()
int LKDetectorPlane::GetPlaneID () const inline inherited
Definition at line 57 of file LKDetectorPlane.h.
References LKDetectorPlane::fPlaneID.
Referenced by LKDetectorPlane::SetPadArray(), and LKPadPlane::SetPadArray().
GetPosition()
double LKDetectorPlane::GetPosition () const inline inherited
Definition at line 65 of file LKDetectorPlane.h.
References LKDetectorPlane::fPosition.
Referenced by TTMicromegas::FillDataToHist(), TTFrontPlane::FillDataToHist(), LKEvePlane::FillDataToHistEventDisplay1(), ATMicromegas::FillDataToHistEventDisplay2(), ATTPCStripPad::Init(), LKDetectorPlane::PadNeighborChecker(), LKPadPlane::PadNeighborChecker(), LKDetectorPlane::PadPositionChecker(), and LKPadPlane::PadPositionChecker().
GetRank()
Int_t LKGear::GetRank () const inherited
Definition at line 36 of file LKGear.cpp.
References LKGear::fRank.
GetRMax()
Double_t LHPadPlaneYCut::GetRMax () const inline
Definition at line 68 of file LHPadPlaneYCut.h.
References fRMax.
GetRMin()
Double_t LHPadPlaneYCut::GetRMin () const inline
Definition at line 67 of file LHPadPlaneYCut.h.
References fRMin.
GetTbToLength()
double LKDetectorPlane::GetTbToLength () const inline inherited
Definition at line 64 of file LKDetectorPlane.h.
References LKDetectorPlane::fTbToLength.
GlobalToLocalAxis()
virtual TVector3 LKDetectorPlane::GlobalToLocalAxis (TVector3 posGlobal) inline virtual inherited
Implementation recommanded. Convert global position to local detector plane position.
Reimplemented in LKEvePlane.
Definition at line 86 of file LKDetectorPlane.h.
Referenced by LKPadPlane::DriftElectron().
GrabNeighborPads()
void LKPadPlane::GrabNeighborPads (vector< LKPad * > * pads, vector< LKPad * > * neighborPads) inherited
Definition at line 452 of file LKPadPlane.cpp.
Referenced by LKPadPlane::PullOutNeighborHits(), and LKPadPlane::PullOutNeighborHits().
Init()
bool LHPadPlaneYCut::Init () virtual
Implementation recommanded. Init() method should implement pad information (id, position, neighbor) and add channel using AddChannel() or AddPad() method. All parameters should be configured such as axis-1,2,3, fPosition, fTbToLength from parameter container.
Reimplemented from LKDetectorPlane.
Definition at line 22 of file LHPadPlaneYCut.cpp.
References LKDetectorPlane::fChannelArray, fCosPiNo4, fDoCutSideBoundary, fDoCutTopBoundary, fNumHalfRowsInLayer, fNumLayers, fNumPadsDownToLayer, fNumSkippedHalfRows, fPadGap, fPadHeight, fPadWidth, LKGear::fPar, fRadiusLayer0, fRMax, fRMin, fRSpacing, fRTopCut, fSinPiNo4, fTanPi1o8, fTanPi3o8, fTanPi5o8, fTanPi7o8, fXSpacing, LKPadPlane::GetPad(), GetPadCenterYBoundAtX(), GetPadCutBoundaryXAtY(), GetPadCutBoundaryYAtX(), NewPad(), and SetNeighborPads().
IsInBoundary() [1/2]
virtual bool LKDetectorPlane::IsInBoundary (double i, double j) inline virtual inherited
Implementation recommanded. Return if position (i,j) is inside the effective detector plane boundary.
Reimplemented in LTPadPlane, and LKEvePlane.
Definition at line 85 of file LKDetectorPlane.h.
IsInBoundary() [2/2]
bool LHPadPlaneYCut::IsInBoundary (Double_t i, Double_t j) virtual
Definition at line 253 of file LHPadPlaneYCut.cpp.
References fRMax.
LocalToGlobalAxis()
virtual TVector3 LKDetectorPlane::LocalToGlobalAxis (TVector3 posLocal) inline virtual inherited
Implementation recommanded. Convert local position to global detector plane position
Reimplemented in LKEvePlane.
Definition at line 87 of file LKDetectorPlane.h.
NewPad()
LKPad * LHPadPlaneYCut::NewPad (Int_t s, Int_t r, Int_t l) private
Definition at line 338 of file LHPadPlaneYCut.cpp.
References LKDetectorPlane::fChannelArray.
Referenced by Init().
PadDisplacement()
Double_t LHPadPlaneYCut::PadDisplacement () const virtual
Return average pad displacement to each other.
Reimplemented from LKDetectorPlane.
Definition at line 248 of file LHPadPlaneYCut.cpp.
References fRSpacing, and fXSpacing.
PadMapChecker()
bool LKDetectorPlane::PadMapChecker () inherited
Self debugging tool. Result will be printed out. For each pad, check 1) section, layer, row map 2) cobo, aget, asad, chan map
Definition at line 432 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fChannelArray, LKDetectorPlane::FindPadID(), lk_info, and lk_warning.
PadNeighborChecker()
bool LKPadPlane::PadNeighborChecker () inherited
Definition at line 519 of file LKPadPlane.cpp.
References LKDetectorPlane::fChannelArray, LKPad::GetI(), LKPad::GetJ(), LKChannel::GetPadID(), LKDetectorPlane::GetPosition(), and lk_info.
PadPositionChecker()
bool LKPadPlane::PadPositionChecker (bool checkCorners = true) inherited
Definition at line 467 of file LKPadPlane.cpp.
References LKDetectorPlane::fChannelArray, LKPadPlane::FindPadID(), LKPad::GetPadCorners(), LKDetectorPlane::GetPosition(), lk_info, and lk_warning.
Print()
void LKPadPlane::Print (Option_t * option = "") const virtual inherited
Reimplemented from LKDetectorPlane.
Reimplemented in TTFrontPlane.
Definition at line 20 of file LKPadPlane.cpp.
References LKDetectorPlane::fChannelArray, iChannel, and lk_info.
PullOutNeighborHits() [1/9]
void LKDetectorPlane::PullOutNeighborHits (double x, double y, int range, LKHitArray * neighborHits) inherited
For tracking use.
Definition at line 328 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fChannelArray, LKDetectorPlane::FindPadID(), and LKDetectorPlane::GrabNeighborPads().
PullOutNeighborHits() [2/9]
void LKDetectorPlane::PullOutNeighborHits (double x, double y, int range, vector< LKHit * > * neighborHits) inherited
For tracking use.
Definition at line 380 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fChannelArray, LKDetectorPlane::FindPadID(), and LKDetectorPlane::GrabNeighborPads().
PullOutNeighborHits() [3/9]
void LKPadPlane::PullOutNeighborHits (Double_t x, Double_t y, Int_t range, LKHitArray * neighborHits) inherited
Definition at line 363 of file LKPadPlane.cpp.
References LKDetectorPlane::fChannelArray, LKPadPlane::FindPadID(), and LKPadPlane::GrabNeighborPads().
PullOutNeighborHits() [4/9]
void LKPadPlane::PullOutNeighborHits (Double_t x, Double_t y, Int_t range, vector< LKTpcHit * > * neighborHits) inherited
Definition at line 415 of file LKPadPlane.cpp.
References LKDetectorPlane::fChannelArray, LKPadPlane::FindPadID(), and LKPadPlane::GrabNeighborPads().
PullOutNeighborHits() [5/9]
void LKPadPlane::PullOutNeighborHits (LKHitArray * hits, LKHitArray * neighborHits) inherited
Definition at line 350 of file LKPadPlane.cpp.
References LKDetectorPlane::fChannelArray.
PullOutNeighborHits() [6/9]
void LKDetectorPlane::PullOutNeighborHits (TVector2 p, int range, vector< LKHit * > * neighborHits) inherited
For tracking use.
Definition at line 375 of file LKDetectorPlane.cpp.
References LKDetectorPlane::PullOutNeighborHits().
PullOutNeighborHits() [7/9]
void LKPadPlane::PullOutNeighborHits (TVector2 p, Int_t range, vector< LKTpcHit * > * neighborHits) inherited
Definition at line 410 of file LKPadPlane.cpp.
References LKPadPlane::PullOutNeighborHits().
PullOutNeighborHits() [8/9]
void LKDetectorPlane::PullOutNeighborHits (vector< LKHit * > * hits, vector< LKHit * > * neighborHits) inherited
For tracking use.
Definition at line 365 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fChannelArray.
Referenced by LKDetectorPlane::PullOutNeighborHits().
PullOutNeighborHits() [9/9]
void LKPadPlane::PullOutNeighborHits (vector< LKTpcHit * > * hits, vector< LKTpcHit * > * neighborHits) inherited
Definition at line 400 of file LKPadPlane.cpp.
References LKDetectorPlane::fChannelArray.
Referenced by LKPadPlane::PullOutNeighborHits().
PullOutNextFreeHit()
LKTpcHit * LKPadPlane::PullOutNextFreeHit () virtual inherited
For tracking use.
Reimplemented from LKDetectorPlane.
Definition at line 335 of file LKPadPlane.cpp.
References LKDetectorPlane::fChannelArray, LKPadPlane::fFreePadIdx, and LKPadPlane::PullOutNextFreeHit().
Referenced by LKPadPlane::PullOutNextFreeHit().
ResetEvent()
void LKPadPlane::ResetEvent () virtual inherited
For tracking use.
Reimplemented from LKDetectorPlane.
Definition at line 312 of file LKPadPlane.cpp.
References LKDetectorPlane::fChannelArray, and LKPadPlane::fFreePadIdx.
ResetHitMap()
void LKPadPlane::ResetHitMap () virtual inherited
For tracking use.
Reimplemented from LKDetectorPlane.
Definition at line 323 of file LKPadPlane.cpp.
References LKDetectorPlane::fChannelArray, and LKPadPlane::fFreePadIdx.
SetDataFromBranch()
bool LKPadPlane::SetDataFromBranch () virtual inherited
Implementation recommanded. Set waveform and hit data from input tree branches to pads.
Reimplemented from LKDetectorPlane.
Reimplemented in TTFrontPlane.
Definition at line 240 of file LKPadPlane.cpp.
References LKPadPlane::Clear(), LKGear::fPar, LKGear::fRun, lk_cout, lk_debug, lk_error, lk_info, lk_warning, LKPadPlane::SetHitArray(), and LKPadPlane::SetPadArray().
SetDetector()
void LKDetectorPlane::SetDetector (LKDetector * detector) inline inherited
Definition at line 55 of file LKDetectorPlane.h.
References LKDetectorPlane::fDetector.
SetHitArray()
void LKPadPlane::SetHitArray (TClonesArray * hitArray) inherited
Definition at line 85 of file LKPadPlane.cpp.
References LKPadPlane::AddHit(), LKPadPlane::fFilledHit, and LKPadPlane::GetPadFast().
Referenced by LKPadPlane::SetDataFromBranch().
SetNeighborPads()
void LHPadPlaneYCut::SetNeighborPads (LKPad * pad0, LKPad * pad1) private
Definition at line 346 of file LHPadPlaneYCut.cpp.
Referenced by Init().
SetPadArray()
void LKPadPlane::SetPadArray (TClonesArray * padArray) inherited
Definition at line 68 of file LKPadPlane.cpp.
References LKPadPlane::fFilledPad, LKDetectorPlane::fPlaneID, LKPadPlane::GetPadFast(), and LKDetectorPlane::GetPlaneID().
Referenced by LKPadPlane::SetDataFromBranch().
SetPar()
void LKGear::SetPar (LKParameterContainer * par) inline inherited
Definition at line 26 of file LKGear.h.
References LKGear::SetParameterContainer().
Referenced by LKDetector::AddPlane(), LKRun::Init(), LKDetector::Init(), and LKMFMConversionTask::Init().
SetParameterContainer()
void LKGear::SetParameterContainer (LKParameterContainer * par) virtual inherited
Definition at line 10 of file LKGear.cpp.
References LKGear::fPar.
Referenced by ATTPC::BuildDetectorPlane(), and LKGear::SetPar().
SetPlaneID()
void LKDetectorPlane::SetPlaneID (int id) inline inherited
Definition at line 56 of file LKDetectorPlane.h.
References LKDetectorPlane::fPlaneID.
Referenced by ATMicromegas::Init(), ATTPC20RectanglePad::Init(), ATTPCHoneyCombPad::Init(), ATTPCRectanglePad::Init(), and ATTPCStripPad::Init().
SetRank()
void LKGear::SetRank (Int_t rank) virtual inherited
Reimplemented in LKTask.
Definition at line 35 of file LKGear.cpp.
References LKGear::fRank.
Referenced by LKDetector::AddPlane(), and LKDetectorSystem::SetDetector().
SetRun()
void LKGear::SetRun (LKRun * run) inline inherited
Definition at line 36 of file LKGear.h.
References LKGear::fRun, and run.
Referenced by LKRun::Add(), LKRun::AddDetector(), LKRun::Init(), LKDetectorSystem::SetDetector(), and LKRun::SetEventTrigger().
TbToGlobalPosition()
TVector3 LKPadPlane::TbToGlobalPosition (LKPad * pad, int tb) virtual inherited
Definition at line 714 of file LKPadPlane.cpp.
Member Data Documentation
fAxis1
axis_t LKDetectorPlane::fAxis1 = LKVector3::kNon protected inherited
Axis-1 lying in plane. Must be set by input parameter.
Definition at line 32 of file LKDetectorPlane.h.
Referenced by LKDetectorPlane::DriftElectron(), ATTPC20RectanglePad::FindPadID(), ATTPCHoneyCombPad::FindPadID(), ATTPCRectanglePad::FindPadID(), ATTPCStripPad::FindPadID(), LKDetectorPlane::GetAxis1(), LKEvePlane::GetAxis1(), ATTPC20RectanglePad::GetHist(), ATTPCHoneyCombPad::GetHist(), ATTPCRectanglePad::GetHist(), ATTPCStripPad::GetHist(), LTPadPlane::Init(), ATTPC20RectanglePad::Init(), ATTPCHoneyCombPad::Init(), ATTPCRectanglePad::Init(), ATTPCStripPad::Init(), and TTMicromegas::TTMicromegas().
fAxis2
axis_t LKDetectorPlane::fAxis2 = LKVector3::kNon protected inherited
Axis-2 lying in plane. Must be set by input parameter.
Definition at line 33 of file LKDetectorPlane.h.
Referenced by LKDetectorPlane::DriftElectron(), ATTPC20RectanglePad::FindPadID(), ATTPCHoneyCombPad::FindPadID(), ATTPCRectanglePad::FindPadID(), ATTPCStripPad::FindPadID(), LKDetectorPlane::GetAxis2(), LKEvePlane::GetAxis2(), ATTPC20RectanglePad::GetHist(), ATTPCHoneyCombPad::GetHist(), ATTPCRectanglePad::GetHist(), ATTPCStripPad::GetHist(), LTPadPlane::Init(), ATTPC20RectanglePad::Init(), ATTPCHoneyCombPad::Init(), ATTPCRectanglePad::Init(), ATTPCStripPad::Init(), and TTMicromegas::TTMicromegas().
fAxis3
axis_t LKDetectorPlane::fAxis3 = LKVector3::kNon protected inherited
Axis-3 = Axis-1 x Axis-2 perpendicular to plane.
Definition at line 34 of file LKDetectorPlane.h.
Referenced by LKDetectorPlane::DriftElectron(), LKEvePlane::DriftElectronBack(), LKDetectorPlane::DriftElectronBack(), LKDetectorPlane::GetAxis3(), and LTPadPlane::Init().
fAxisDrift
axis_t LKDetectorPlane::fAxisDrift = LKVector3::kNon protected inherited
Axis perpendicular to plane, in electron drifting direction. Must be set by input parameter.
Definition at line 35 of file LKDetectorPlane.h.
Referenced by LKEvePlane::DriftElectronBack(), LKDetectorPlane::DriftElectronBack(), LKEvePlane::FillDataToHistEventDisplay1(), ATMicromegas::FillDataToHistEventDisplay2(), LKDetectorPlane::GetAxisDrift(), and LTPadPlane::Init().
fCanvas
TCanvas* LKDetectorPlane::fCanvas = nullptr protected inherited
Definition at line 40 of file LKDetectorPlane.h.
Referenced by LKEvePlane::ClickedControlEvent2(), LKPadPlane::DrawHist(), LKDetectorPlane::DrawHist(), LKDetectorPlane::GetCanvas(), LKEvePlane::GetCanvas(), TTMicromegas::GetCanvas(), ATTPC20RectanglePad::GetCanvas(), ATTPCHoneyCombPad::GetCanvas(), ATTPCRectanglePad::GetCanvas(), ATTPCStripPad::GetCanvas(), TTFrontPlane::GetCanvas(), LHPadPlaneFan::GetCanvas(), LHPadPlaneRCut::GetCanvas(), GetCanvas(), TTMicromegas::GetCPad(), TTMicromegas::SelectAndDrawChannel(), and TTFrontPlane::SelectAndDrawChannel().
fChannelAnalyzer
LKChannelAnalyzer* LKDetectorPlane::fChannelAnalyzer = nullptr protected inherited
Definition at line 29 of file LKDetectorPlane.h.
Referenced by LTPadPlane::GetChannelAnalyzer(), LKDetectorPlane::GetChannelAnalyzer(), LKEvePlane::GetChannelAnalyzer(), LTPadPlane::Init(), and LKEvePlane::UpdateChannelBuffer().
fChannelArray
TObjArray* LKDetectorPlane::fChannelArray = nullptr protected inherited
Definition at line 39 of file LKDetectorPlane.h.
Referenced by LKDetectorPlane::AddChannel(), LHPadPlaneFan::AddPad(), LKDetectorPlane::AddPad(), LKDetectorPlane::Clear(), LKPadPlane::Clear(), LKEvePlane::ClickedControlEvent2(), LTPadPlane::ClickedEventDisplay1(), LKEvePlane::ClickedEventDisplay1(), LKEvePlane::ClickedEventDisplay2(), LKEvePlane::DriftElectronBack(), LKPadPlane::FillBufferIn(), LKDetectorPlane::FillDataToHist(), LKPadPlane::FillDataToHist(), LTPadPlane::FillDataToHist(), LKEvePlane::FillDataToHistEventDisplay1(), ATMicromegas::FillDataToHistEventDisplay2(), LKDetectorPlane::FillPlane(), ATMicromegas::FindPad(), LKEvePlane::FindPad(), LKDetectorPlane::GetChannel(), LKDetectorPlane::GetChannelArray(), LKDetectorPlane::GetChannelFast(), ATTPC20RectanglePad::GetHist(), ATTPCHoneyCombPad::GetHist(), ATTPCRectanglePad::GetHist(), ATTPCStripPad::GetHist(), LHPadPlaneFan::GetHist(), LHPadPlaneRCut::GetHist(), GetHist(), LTPadPlane::GetHistEventDisplay2(), LKDetectorPlane::GetNChannels(), LKDetectorPlane::GetPad(), LKPadPlane::GetPad(), LKDetectorPlane::GetPadArray(), LKPadPlane::GetPadArray(), LKDetectorPlane::GetPadFast(), LKPadPlane::GetPadFast(), ATMicromegas::Init(), LTPadPlane::Init(), LHPadPlaneFan::Init(), LHPadPlaneRCut::Init(), Init(), ATTPC20RectanglePad::Init(), ATTPCHoneyCombPad::Init(), ATTPCRectanglePad::Init(), ATTPCStripPad::Init(), LHPadPlaneRCut::NewPad(), NewPad(), LKDetectorPlane::PadMapChecker(), LKDetectorPlane::PadNeighborChecker(), LKPadPlane::PadNeighborChecker(), LKDetectorPlane::PadPositionChecker(), LKPadPlane::PadPositionChecker(), LKDetectorPlane::Print(), LKPadPlane::Print(), LKDetectorPlane::PullOutNeighborHits(), LKDetectorPlane::PullOutNeighborHits(), LKPadPlane::PullOutNeighborHits(), LKPadPlane::PullOutNeighborHits(), LKDetectorPlane::PullOutNeighborHits(), LKPadPlane::PullOutNeighborHits(), LKDetectorPlane::PullOutNeighborHits(), LKPadPlane::PullOutNeighborHits(), LHPadPlaneFan::PullOutNeighborHitsIn(), LKDetectorPlane::PullOutNextFreeHit(), LKPadPlane::PullOutNextFreeHit(), LHPadPlaneFan::PullOutNextFreeHitIn(), LKDetectorPlane::ResetEvent(), LKPadPlane::ResetEvent(), LKDetectorPlane::ResetHitMap(), LKPadPlane::ResetHitMap(), LKEvePlane::SetDataFromBranch(), ATMicromegas::UpdateChannelBuffer(), and LKEvePlane::UpdateChannelBuffer().
fCosPiNo4
Double_t LHPadPlaneYCut::fCosPiNo4[8] private
Definition at line 49 of file LHPadPlaneYCut.h.
Referenced by FindPadID(), and Init().
fCvsChannelBuffer
TCanvas* LKPadPlane::fCvsChannelBuffer = nullptr protected inherited
Definition at line 104 of file LKPadPlane.h.
fDetector
LKDetector* LKDetectorPlane::fDetector = nullptr protected inherited
Definition at line 28 of file LKDetectorPlane.h.
Referenced by TTMicromegas::SelectAndDrawChannel(), TTFrontPlane::SelectAndDrawChannel(), and LKDetectorPlane::SetDetector().
fDoCutSideBoundary
const Bool_t LHPadPlaneYCut::fDoCutSideBoundary = true private
Definition at line 60 of file LHPadPlaneYCut.h.
Referenced by Init().
fDoCutTopBoundary
const Bool_t LHPadPlaneYCut::fDoCutTopBoundary = true private
Definition at line 59 of file LHPadPlaneYCut.h.
Referenced by Init().
fEFieldAxis
Int_t LKPadPlane::fEFieldAxis = -1 protected inherited
Definition at line 98 of file LKPadPlane.h.
fFilledHit
bool LKPadPlane::fFilledHit = false protected inherited
Definition at line 102 of file LKPadPlane.h.
Referenced by LKPadPlane::Clear(), LKPadPlane::FillDataToHist(), and LKPadPlane::SetHitArray().
fFilledPad
bool LKPadPlane::fFilledPad = false protected inherited
Definition at line 101 of file LKPadPlane.h.
Referenced by LKPadPlane::Clear(), LKPadPlane::FillDataToHist(), and LKPadPlane::SetPadArray().
fFreePadIdx
Int_t LKPadPlane::fFreePadIdx = 0 protected inherited
Definition at line 99 of file LKPadPlane.h.
Referenced by LKPadPlane::PullOutNextFreeHit(), LKPadPlane::ResetEvent(), and LKPadPlane::ResetHitMap().
fFuncXRightBound
TF1* LHPadPlaneYCut::fFuncXRightBound = nullptr private
Definition at line 33 of file LHPadPlaneYCut.h.
fFuncXRightBoundInverse
TF1* LHPadPlaneYCut::fFuncXRightBoundInverse = nullptr private
Definition at line 34 of file LHPadPlaneYCut.h.
fGraphChannelBoundary
TGraph* LKPadPlane::fGraphChannelBoundary = nullptr protected inherited
Definition at line 105 of file LKPadPlane.h.
fGraphChannelBoundaryNb
TGraph* LKPadPlane::fGraphChannelBoundaryNb[20] = {0} protected inherited
Definition at line 106 of file LKPadPlane.h.
fH2Plane
TH2* LKDetectorPlane::fH2Plane = nullptr protected inherited
Definition at line 41 of file LKDetectorPlane.h.
Referenced by LKDetectorPlane::FillDataToHist(), LKPadPlane::FillDataToHist(), ATTPC20RectanglePad::GetHist(), ATTPCHoneyCombPad::GetHist(), ATTPCRectanglePad::GetHist(), ATTPCStripPad::GetHist(), LHPadPlaneFan::GetHist(), LHPadPlaneRCut::GetHist(), and GetHist().
fHitDataIsSet
bool LKDetectorPlane::fHitDataIsSet = false protected inherited
Definition at line 48 of file LKDetectorPlane.h.
Referenced by LKDetectorPlane::FillDataToHist(), and LKDetectorPlane::SetHitArray().
fNumHalfRowsInLayer
int LHPadPlaneYCut::fNumHalfRowsInLayer[50] = {0} private
Definition at line 52 of file LHPadPlaneYCut.h.
Referenced by FindPadID(), FindPadID(), and Init().
fNumLayers
Int_t LHPadPlaneYCut::fNumLayers = 42 private
Definition at line 43 of file LHPadPlaneYCut.h.
Referenced by FindPadID(), FindPadID(), GetNumLayer(), and Init().
fNumPadsDownToLayer
int LHPadPlaneYCut::fNumPadsDownToLayer[50] = {0} private
in single section
Definition at line 53 of file LHPadPlaneYCut.h.
Referenced by FindPadID(), and Init().
fNumSkippedHalfRows
int LHPadPlaneYCut::fNumSkippedHalfRows[50] = {0} private
Definition at line 54 of file LHPadPlaneYCut.h.
Referenced by FindPadID(), and Init().
fPadDataIsSet
bool LKDetectorPlane::fPadDataIsSet = false protected inherited
Definition at line 47 of file LKDetectorPlane.h.
Referenced by LKDetectorPlane::FillDataToHist(), and LKDetectorPlane::SetPadArray().
fPadGap
Double_t LHPadPlaneYCut::fPadGap = 0.5 private
Definition at line 38 of file LHPadPlaneYCut.h.
Referenced by FindPadID(), GetPadGap(), and Init().
fPadHeight
Double_t LHPadPlaneYCut::fPadHeight = 10. private
Definition at line 40 of file LHPadPlaneYCut.h.
Referenced by FindPadID(), GetPadHeight(), and Init().
fPadWidth
Double_t LHPadPlaneYCut::fPadWidth = 3. private
Definition at line 39 of file LHPadPlaneYCut.h.
Referenced by FindPadID(), GetPadWidth(), and Init().
fPar
LKParameterContainer* LKGear::fPar = nullptr protected inherited
Definition at line 39 of file LKGear.h.
Referenced by LKTask::Add(), LKRun::AddDetector(), LKGear::AddParameterContainer(), LKGear::AddParameterContainer(), LKDetector::AddPlane(), LHTpc::BuildDetectorPlane(), ATTPC::BuildDetectorPlane(), LHTpc::BuildGeometry(), ATTPC::BuildGeometry(), ClassImp(), ClassImp(), ClassImp(), ClassImp(), LKEveTask::DrawEve3D(), LKPadPlane::DrawHist(), LKG4RunManager::EndOfRun(), LKPulseExtractionTask::EndOfRun(), LKDetectorPlane::FillDataToHist(), LKPadPlane::FillDataToHist(), LTPadPlane::GetChannelAnalyzer(), LKDetector::GetChannelAnalyzer(), LKDetectorPlane::GetChannelAnalyzer(), LKEvePlane::GetChannelAnalyzer(), LKGear::GetPar(), LKGear::GetParameterContainer(), ATMicromegas::Init(), AToMX::Init(), LTPadPlane::Init(), LKRun::Init(), LKDetector::Init(), LKEvePlane::Init(), LKMFMConversionTask::Init(), LKDriftElectronTask::Init(), LKEveTask::Init(), LKGETChannelViewer::Init(), LKNoiseSubtractionTask::Init(), LKPulseExtractionTask::Init(), LHPSATask::Init(), TexAT2::Init(), TTMicromegas::Init(), TTHTBeamTrackingTask::Init(), TTHTTrackingTask::Init(), TTPulseExtractionTask::Init(), LHPadPlaneFan::Init(), LHPadPlaneRCut::Init(), Init(), ATTPC::Init(), ATTPC20RectanglePad::Init(), ATTPCHoneyCombPad::Init(), ATTPCRectanglePad::Init(), ATTPCStripPad::Init(), TTFrontPlane::Init(), LKRun::InitAndCollectParameters(), TexAT2::InitChannelAnalyzer(), LKG4RunManager::Initialize(), LKRun::Print(), LKRun::RegisterBranchA(), LKG4RunManager::Run(), LKDetectorPlane::SetDataFromBranch(), LKPadPlane::SetDataFromBranch(), LKDetectorSystem::SetDetectorPar(), LKEveTask::SetEveLineAtt(), LKEveTask::SetEveMarkerAtt(), LKRun::SetEventTrigger(), LKEveTask::SetGraphAtt(), LKEveTask::SetGraphAtt(), LKG4RunManager::SetOutputFile(), LKGear::SetParameterContainer(), TTMicromegas::WriteCurrentChannel(), and LKRun::WriteOutputFile().
fPlaneID
int LKDetectorPlane::fPlaneID = -1 protected inherited
Detector plane id.
Definition at line 31 of file LKDetectorPlane.h.
Referenced by LKDetectorPlane::GetCanvas(), ATTPC20RectanglePad::GetCanvas(), ATTPCHoneyCombPad::GetCanvas(), ATTPCRectanglePad::GetCanvas(), ATTPCStripPad::GetCanvas(), LHPadPlaneFan::GetCanvas(), LHPadPlaneRCut::GetCanvas(), GetCanvas(), LKDetectorPlane::GetPlaneID(), ATTPC20RectanglePad::Init(), ATTPCHoneyCombPad::Init(), ATTPCRectanglePad::Init(), ATTPCStripPad::Init(), LKDetectorPlane::SetPadArray(), LKPadPlane::SetPadArray(), and LKDetectorPlane::SetPlaneID().
fPosition
double LKDetectorPlane::fPosition protected inherited
Global position of pad plane center.
Definition at line 37 of file LKDetectorPlane.h.
Referenced by LKDetectorPlane::DriftElectron(), LKDetectorPlane::DriftElectronBack(), LKEvePlane::DriftElectronBack(), LKDetectorPlane::DriftElectronBack(), LKDetectorPlane::GetPosition(), ATMicromegas::Init(), LTPadPlane::Init(), and LKEvePlane::Init().
fRadiusLayer0
Double_t LHPadPlaneYCut::fRadiusLayer0 = 110. private
Definition at line 41 of file LHPadPlaneYCut.h.
Referenced by FindPadID(), and Init().
fRank
Int_t LKGear::fRank = 0 protected inherited
Definition at line 41 of file LKGear.h.
Referenced by LKTask::Add(), LKDetector::AddPlane(), LKGear::GetRank(), LKDetectorSystem::SetDetector(), LKRun::SetEventTrigger(), LKGear::SetRank(), and LKTask::SetRank().
fRMax
Double_t LHPadPlaneYCut::fRMax = 510. private
Definition at line 37 of file LHPadPlaneYCut.h.
Referenced by GetRMax(), Init(), and IsInBoundary().
fRMin
Double_t LHPadPlaneYCut::fRMin = 100. private
Definition at line 36 of file LHPadPlaneYCut.h.
Referenced by GetRMin(), and Init().
fRSpacing
Double_t LHPadPlaneYCut::fRSpacing private
Definition at line 57 of file LHPadPlaneYCut.h.
Referenced by FindPadID(), GetPadRSpacing(), Init(), and PadDisplacement().
fRTopCut
Double_t LHPadPlaneYCut::fRTopCut = 506. private
Definition at line 42 of file LHPadPlaneYCut.h.
Referenced by GetHist(), and Init().
fRun
LKRun* LKGear::fRun = nullptr protected inherited
Definition at line 40 of file LKGear.h.
Referenced by LKDetector::AddPlane(), ClassImp(), ClassImp(), ClassImp(), LKEvePlane::ClickedControlEvent1(), LKEvePlane::ClickedControlEvent1(), LKEvePlane::ClickedControlEvent2(), LKEveTask::DrawDetectorPlanes(), LKEveTask::DrawEve3D(), LKPulseExtractionTask::EndOfRun(), TTPulseExtractionTask::EndOfRun(), LKGETChannelViewer::Exec(), LKPulseExtractionTask::Exec(), TTHitFindingHoughTask::Exec(), TTPulseExtractionTask::Exec(), TTMicromegas::FillDataToHist(), LTPadPlane::FillDataToHist(), LKEvePlane::FillDataToHistEventDisplay1(), LKEvePlane::GetHistControlEvent1(), LTPadPlane::Init(), LTEventPreviewTask::Init(), TTPulseAnalysisTask::Init(), LKEvePlane::Init(), LKMFMConversionTask::Init(), LKDriftElectronTask::Init(), LKEveTask::Init(), LKGETChannelViewer::Init(), LKNoiseSubtractionTask::Init(), LKPulseExtractionTask::Init(), LKPulseShapeAnalysisTask::Init(), TTBeamSelectionTask::Init(), TTDrawBeamEnergyTask::Init(), TTDrawRawWaveformTask::Init(), TTEventSelectionTask::Init(), TTFindBeamTimingTask::Init(), TTGetPedestalTask::Init(), TTPID_FSivsFCsI::Init(), TTPID_MMvsFSi::Init(), TTPID_MMvsX6::Init(), TTPID_X6vsCsI::Init(), TTReadEventListTask::Init(), TTHTtBeamTrackingTask::Init(), TTEventNumberSelectionTask::Init(), TTEventPreviewTask::Init(), TTHitFindingHoughTask::Init(), TTHTBeamTrackingTask::Init(), TTHTTrackingTask::Init(), TTPulseExtractionTask::Init(), httask::Init(), LKMFMConversionTask::Run(), LKGETChannelViewer::SelectMenu(), LKDetectorPlane::SetDataFromBranch(), LKPadPlane::SetDataFromBranch(), TTMicromegas::SetDataFromBranch(), TTFrontPlane::SetDataFromBranch(), LKDetectorSystem::SetDetector(), LKEvePlane::SetPalette(), LKGear::SetRun(), LKDetector::SetRun(), LKMFMConversionTask::SignalNextEvent(), LKEvePlane::UpdateControlEvent1(), and LKEvePlane::UpdateControlEvent2().
fSinPiNo4
Double_t LHPadPlaneYCut::fSinPiNo4[8] private
Definition at line 50 of file LHPadPlaneYCut.h.
Referenced by FindPadID(), and Init().
fTanPi1o8
Double_t LHPadPlaneYCut::fTanPi1o8 private
Definition at line 45 of file LHPadPlaneYCut.h.
Referenced by FindSection(), and Init().
fTanPi3o8
Double_t LHPadPlaneYCut::fTanPi3o8 private
Definition at line 46 of file LHPadPlaneYCut.h.
Referenced by FindSection(), GetPadCenterYBoundAtX(), GetPadCutBoundaryXAtY(), GetPadCutBoundaryYAtX(), and Init().
fTanPi5o8
Double_t LHPadPlaneYCut::fTanPi5o8 private
Definition at line 47 of file LHPadPlaneYCut.h.
Referenced by FindSection(), and Init().
fTanPi7o8
Double_t LHPadPlaneYCut::fTanPi7o8 private
Definition at line 48 of file LHPadPlaneYCut.h.
Referenced by FindSection(), and Init().
fTbToLength
double LKDetectorPlane::fTbToLength = 1 protected inherited
time-bin (tb) to position conversion factor. Must be set by input parameter.
Definition at line 36 of file LKDetectorPlane.h.
Referenced by LKDetectorPlane::DriftElectronBack(), LKEvePlane::DriftElectronBack(), LKDetectorPlane::DriftElectronBack(), LKDetectorPlane::GetTbToLength(), ATMicromegas::Init(), LTPadPlane::Init(), and LKEvePlane::Init().
fXSpacing
Double_t LHPadPlaneYCut::fXSpacing private
Definition at line 56 of file LHPadPlaneYCut.h.
Referenced by FindPadID(), GetPadXSpacing(), Init(), and PadDisplacement().
The documentation for this class was generated from the following files:
LHPadPlaneYCut.h
LHPadPlaneYCut.cpp