lilak: LKBufferI Class Reference
LKBufferI Class Reference
#include <LKBufferI.h>
Public Member Functions
double CalculateGroupFluctuation (int numGroups=8, int tb2=512)
Divide 0-tb2 into numGroups. Calculate std-dev of group means.
void Clear (Option_t *option="")
void Copy (TObject &object) const
void Draw (Option_t *option="")
void Fill (int tb, int value)
virtual void FillGraph (TGraph *graph)
virtual void FillHist (TH1 *hist)
int * GetArray ()
virtual TGraph * GetGraph ()
void GetGroupMeanStdDev (int numGroups, int tb2, double *pedestalGroup, double *stddevGroup)
Divide 0-tb2 into numGroups. Evaluate pedestal(mean) and std-dev of each group.
virtual TH1D * GetHist (TString name="")
double GetScale (double *buffer)
return [scale] where [scale] is fit parameter of fArray = [scale] x buffer.
double GetScale (int *buffer)
return [scale] where [scale] is fit parameter of fArray = [scale] x buffer.
double Integral (double pedestal=0., bool invert=false)
bool IsEmpty () const
LKBufferI ()
void Print (Option_t *option="") const
void SetArray (const double *buffer)
void SetArray (const int *buffer)
void SetArray (const unsigned int *buffer)
void SetArray (std::vector< unsigned int > buffer)
void SetBuffer (LKBufferI buffer)
void SubtractArray (double *buffer)
void SubtractArray (double *buffer, double scale)
void SubtractArray (int *buffer)
void SubtractArray (int *buffer, double scale)
virtual ~LKBufferI ()
Protected Member Functions
ClassDef (LKBufferI, 1)
Protected Attributes
int fArray [512]
bool fEmpty = true
TGraph * fGraph = nullptr
TH1D * fHist = nullptr
Detailed Description
Definition at line 8 of file LKBufferI.h.
Constructor & Destructor Documentation
LKBufferI()
LKBufferI::LKBufferI ()
Definition at line 7 of file LKBufferI.cpp.
References Clear().
~LKBufferI()
virtual LKBufferI::~LKBufferI () inline virtual
Definition at line 12 of file LKBufferI.h.
Member Function Documentation
CalculateGroupFluctuation()
double LKBufferI::CalculateGroupFluctuation (int numGroups = 8, int tb2 = 512)
Divide 0-tb2 into numGroups. Calculate std-dev of group means.
Definition at line 108 of file LKBufferI.cpp.
References GetGroupMeanStdDev().
Referenced by GETChannel::CalculateGroupFluctuation().
ClassDef()
LKBufferI::ClassDef (LKBufferI , 1) protected
Clear()
void LKBufferI::Clear (Option_t * option = "")
Definition at line 12 of file LKBufferI.cpp.
References fArray, and fEmpty.
Referenced by ClassImp(), GETChannel::Clear(), and LKBufferI().
Copy()
void LKBufferI::Copy (TObject & object) const
Definition at line 18 of file LKBufferI.cpp.
References fArray.
Draw()
void LKBufferI::Draw (Option_t * option = "")
Definition at line 36 of file LKBufferI.cpp.
References Draw(), and GetHist().
Referenced by Draw().
Fill()
void LKBufferI::Fill (int tb, int value) inline
Definition at line 32 of file LKBufferI.h.
References fArray.
Referenced by LKPad::FillBufferRawSig().
FillGraph()
void LKBufferI::FillGraph (TGraph * graph) virtual
Definition at line 67 of file LKBufferI.cpp.
References fArray, and SetPoint().
Referenced by GETChannel::FillGraph(), and GetGraph().
FillHist()
void LKBufferI::FillHist (TH1 * hist) virtual
Definition at line 51 of file LKBufferI.cpp.
References fArray.
Referenced by GETChannel::FillHist(), GetHist(), and LKPad::SetHist().
GetArray()
int * LKBufferI::GetArray () inline
Definition at line 34 of file LKBufferI.h.
References fArray.
Referenced by LKPad::GetArrayRawSig(), LKPad::GetArrayShaped(), GETChannel::GetBufferArray(), GETChannel::GetWaveformY(), and SetBuffer().
GetGraph()
TGraph * LKBufferI::GetGraph () virtual
Definition at line 58 of file LKBufferI.cpp.
References fGraph, and FillGraph().
GetGroupMeanStdDev()
void LKBufferI::GetGroupMeanStdDev (int numGroups, int tb2, double * pedestalGroup, double * stddevGroup)
Divide 0-tb2 into numGroups. Evaluate pedestal(mean) and std-dev of each group.
Definition at line 127 of file LKBufferI.cpp.
References fArray.
Referenced by CalculateGroupFluctuation(), and GETChannel::GetGroupMeanStdDev().
GetHist()
TH1D * LKBufferI::GetHist (TString name = "") virtual
Definition at line 41 of file LKBufferI.cpp.
References fHist, and FillHist().
Referenced by Draw(), GETChannel::GetHist(), and LKSiChannel::GetHist().
GetScale() [1/2]
double LKBufferI::GetScale (double * buffer)
return [scale] where [scale] is fit parameter of fArray = [scale] x buffer.
Definition at line 94 of file LKBufferI.cpp.
References fArray.
GetScale() [2/2]
double LKBufferI::GetScale (int * buffer)
return [scale] where [scale] is fit parameter of fArray = [scale] x buffer.
Definition at line 80 of file LKBufferI.cpp.
References fArray.
Referenced by GETChannel::GetScale(), and GETChannel::GetScale().
Integral()
double LKBufferI::Integral (double pedestal = 0., bool invert = false)
Definition at line 156 of file LKBufferI.cpp.
References fArray.
Referenced by GETChannel::GetIntegral(), and LKSiChannel::GetIntegral().
IsEmpty()
bool LKBufferI::IsEmpty () const inline
Definition at line 23 of file LKBufferI.h.
References fEmpty.
Referenced by SetBuffer().
Print()
void LKBufferI::Print (Option_t * option = "") const
Definition at line 24 of file LKBufferI.cpp.
References e_cout, e_info, fArray, and fEmpty.
Referenced by GETChannel::Print(), and LKPad::Print().
SetArray() [1/4]
void LKBufferI::SetArray (const double * buffer) inline
Definition at line 28 of file LKBufferI.h.
References fArray, and fEmpty.
SetArray() [2/4]
void LKBufferI::SetArray (const int * buffer) inline
Definition at line 27 of file LKBufferI.h.
References fArray, and fEmpty.
Referenced by LKPad::SetBufferRawSig(), LKPad::SetBufferShaped(), GETChannel::SetWaveformY(), GETChannel::SetWaveformY(), and GETChannel::SetWaveformY().
SetArray() [3/4]
void LKBufferI::SetArray (const unsigned int * buffer) inline
Definition at line 29 of file LKBufferI.h.
References fArray, and fEmpty.
SetArray() [4/4]
void LKBufferI::SetArray (std::vector< unsigned int > buffer) inline
Definition at line 30 of file LKBufferI.h.
References fArray, and fEmpty.
SetBuffer()
void LKBufferI::SetBuffer (LKBufferI buffer)
Definition at line 74 of file LKBufferI.cpp.
References fArray, fEmpty, GetArray(), and IsEmpty().
Referenced by GETChannel::SetBuffer(), LKPad::SetBufferRawSig(), and LKPad::SetBufferShaped().
SubtractArray() [1/4]
void LKBufferI::SubtractArray (double * buffer) inline
Definition at line 38 of file LKBufferI.h.
References fArray.
SubtractArray() [2/4]
void LKBufferI::SubtractArray (double * buffer, double scale) inline
Definition at line 40 of file LKBufferI.h.
References fArray.
SubtractArray() [3/4]
void LKBufferI::SubtractArray (int * buffer) inline
Definition at line 37 of file LKBufferI.h.
References fArray.
Referenced by GETChannel::SubtractArray(), GETChannel::SubtractArray(), GETChannel::SubtractArray(), and GETChannel::SubtractArray().
SubtractArray() [4/4]
void LKBufferI::SubtractArray (int * buffer, double scale) inline
Definition at line 39 of file LKBufferI.h.
References fArray.
Member Data Documentation
fArray
int LKBufferI::fArray[512] protected
Definition at line 49 of file LKBufferI.h.
Referenced by Clear(), Copy(), Fill(), FillGraph(), FillHist(), GetArray(), GetGroupMeanStdDev(), GetScale(), GetScale(), Integral(), Print(), SetArray(), SetArray(), SetArray(), SetArray(), SetBuffer(), SubtractArray(), SubtractArray(), SubtractArray(), and SubtractArray().
fEmpty
bool LKBufferI::fEmpty = true protected
Definition at line 48 of file LKBufferI.h.
Referenced by Clear(), IsEmpty(), Print(), SetArray(), SetArray(), SetArray(), SetArray(), and SetBuffer().
fGraph
TGraph* LKBufferI::fGraph = nullptr protected
Definition at line 52 of file LKBufferI.h.
Referenced by GetGraph().
fHist
TH1D* LKBufferI::fHist = nullptr protected
Definition at line 51 of file LKBufferI.h.
Referenced by GetHist().
The documentation for this class was generated from the following files:
LKBufferI.h
LKBufferI.cpp