lilak: LKTracklet Class Reference
LKTracklet Class Reference abstract
#include <LKTracklet.h>
Public Types
enum LKFitStatus : int {
kNone = -1 , kBad = 0 , kLine = 1 , kPlane = 2 ,
kHelix = 3 , kGenfitTrack = 4
}
Public Member Functions
virtual void AddHit (LKHit *hit)
virtual void Clear (Option_t *option="")
virtual void ClearHits ()
virtual double Continuity (double &totalLength, double &continuousLength, double distCut=25)
virtual double Continuity (double distCut=25)
virtual bool DoDrawOnDetectorPlane ()
virtual bool DrawByDefault ()
return true if to be displayed on eve.
virtual TVector3 ExtrapolateByLength (double l) const =0
Extrapolate by length (tail:0), returns extrapolated position.
virtual TVector3 ExtrapolateByRatio (double r) const =0
Extrapolate by ratio (tail:0, head:1), returns extrapolated position.
virtual TVector3 ExtrapolateHead (double l) const =0
Extrapolate head of track about length, returns extrapolated position.
virtual TVector3 ExtrapolateTail (double l) const =0
Extrapolate tail of track about length, returns extrapolated position.
virtual TVector3 ExtrapolateTo (TVector3 point) const =0
Extrapolate to POCA from point, returns extrapolated position.
virtual void FillTrajectory (TGraphErrors *graphTrack, LKVector3::Axis axis1, LKVector3::Axis axis2)
virtual void FillTrajectory (TGraphErrors *graphTrack, LKVector3::Axis axis1, LKVector3::Axis axis2, bool(*fisout)(TVector3 pos))
virtual void FillTrajectory3D (TGraph2DErrors *graphTrack3D, LKVector3::Axis axis1, LKVector3::Axis axis2, LKVector3::Axis axis3)
virtual void FillTrajectory3D (TGraph2DErrors *graphTrack3D, LKVector3::Axis axis1, LKVector3::Axis axis2, LKVector3::Axis axis3, bool(*fisout)(TVector3 pos))
virtual void FinalizeHits ()
virtual bool Fit ()
virtual LKGeoHelix FitHelix (LKVector3::Axis ref)
virtual LKGeoLine FitLine ()
virtual LKGeoPlane FitPlane ()
double GetChargeSum () const
LKTracklet::LKFitStatus GetFitStatus () const
TString GetFitStatusString () const
LKHit * GetHit (int idx) const
LKHitArray * GetHitArray ()
int GetHitID (int idx) const
std::vector< int > * GetHitIDArray ()
TVector3 GetMean () const
int GetNumHits () const
int GetParentID () const
int GetPDG () const
int GetTrackID () const
bool IsBad () const
bool IsGenfitTrack () const
bool IsHelix () const
bool IsHoldingHits ()
bool IsLine () const
bool IsPlane () const
virtual double LengthAt (TVector3 point) const =0
Length at POCA from point, where tail=0, head=TrackLength.
LKTracklet ()
virtual TVector3 Momentum (double B=0.5) const =0
Momentum of track at head.
virtual TVector3 PositionAtHead () const =0
Position at head of helix.
virtual TVector3 PositionAtTail () const =0
Position at tail of helix.
virtual int RecoverHitArrayWithHitID (TClonesArray *hitArray)
virtual int RecoverHitArrayWithTrackID (TClonesArray *hitArray)
virtual void RemoveHit (LKHit *hit)
void SetFitStatus (LKFitStatus value)
void SetIsBad ()
void SetIsGenfitTrack ()
void SetIsHelix ()
void SetIsLine ()
void SetIsPlane ()
void SetParentID (int val)
void SetPDG (int val)
void SetTrackID (int val)
virtual void SortHits (bool increasing=true)
virtual double TrackLength () const =0
Length of track calculated from head to tail.
virtual TGraphErrors * TrajectoryOnPlane (LKDetectorPlane *plane, double scale=1)
virtual TGraphErrors * TrajectoryOnPlane (LKVector3::Axis axis1, LKVector3::Axis axis2, bool(*fisout)(TVector3 pos), double scale=1)
virtual TGraphErrors * TrajectoryOnPlane (LKVector3::Axis axis1, LKVector3::Axis axis2, double scale=1)
virtual ~LKTracklet ()
Public Member Functions inherited from LKContainer
virtual void Clear (Option_t *option="")
virtual TObject * Clone (const char *newname="") const
virtual void Copy (TObject &object) const
virtual bool DrawByDefault ()
return true if to be displayed on eve.
LKContainer ()
virtual ~LKContainer ()
Protected Attributes
LKFitStatus fFitStatus
One of kBad, kHelix and kLine.
LKHitArray fHitArray
vector< int > fHitIDArray
int fParentID = -1
Vertex ID.
int fPDG = -1
int fTrackID = -1
TGraphErrors * fTrajectoryOnPlane = nullptr
Detailed Description
Definition at line 16 of file LKTracklet.h.
Member Enumeration Documentation
LKFitStatus
enum LKTracklet::LKFitStatus : int
Enumerator
kNone
kBad
kLine
kPlane
kHelix
kGenfitTrack
Definition at line 19 of file LKTracklet.h.
Constructor & Destructor Documentation
LKTracklet()
LKTracklet::LKTracklet () inline
Definition at line 64 of file LKTracklet.h.
~LKTracklet()
virtual LKTracklet::~LKTracklet () inline virtual
Definition at line 65 of file LKTracklet.h.
Member Function Documentation
AddHit()
void LKTracklet::AddHit (LKHit * hit) virtual
Definition at line 42 of file LKTracklet.cpp.
References LKHitArray::AddHit(), fHitArray, fHitIDArray, fTrackID, LKHit::GetHitID(), and SetTrackID().
Clear()
virtual void LKTracklet::Clear (Option_t * option = "") virtual
Reimplemented from LKContainer.
Reimplemented in LKExtrapolatedTrack, LKHelixTrack, LKLinearTrack, and LKMCTrack.
Referenced by LKExtrapolatedTrack::Clear(), LKHelixTrack::Clear(), LKLinearTrack::Clear(), and LKMCTrack::Clear().
ClearHits()
void LKTracklet::ClearHits () virtual
Definition at line 36 of file LKTracklet.cpp.
References LKHitArray::Clear(), fHitArray, and fHitIDArray.
Continuity() [1/2]
double LKTracklet::Continuity (double & totalLength, double & continuousLength, double distCut = 25) virtual
Check continuity of the track. Hit array must be filled. Returns ratio of the continuous region. (-1 if less than 2 hits)
If difference between "length from hits" is smaller than distCut, (> pad-diagonal, < 2*pad-row) the region is considered to be connected.
The total length calculation is different from TrackLength(), because TrackLength() use only the head/tail alpha angle information but this method calculate length directly from the hit using Map(...) method.
Parameters
continuousLength calculated length of continuos region.
totalLength calculated total length of the track.
Reimplemented in LKHelixTrack.
Definition at line 213 of file LKTracklet.cpp.
References fHitArray, LKHitArray::GetHit(), LKHitArray::GetNumHits(), LKHit::GetPosition(), and SortHits().
Continuity() [2/2]
virtual double LKTracklet::Continuity (double distCut = 25) inline virtual
Definition at line 164 of file LKTracklet.h.
References Continuity().
Referenced by Continuity().
DoDrawOnDetectorPlane()
bool LKTracklet::DoDrawOnDetectorPlane () virtual
Definition at line 154 of file LKTracklet.cpp.
DrawByDefault()
bool LKTracklet::DrawByDefault () virtual
return true if to be displayed on eve.
Reimplemented from LKContainer.
Definition at line 116 of file LKTracklet.cpp.
ExtrapolateByLength()
virtual TVector3 LKTracklet::ExtrapolateByLength (double l) const pure virtual
Extrapolate by length (tail:0), returns extrapolated position.
ExtrapolateByRatio()
virtual TVector3 LKTracklet::ExtrapolateByRatio (double r) const pure virtual
Extrapolate by ratio (tail:0, head:1), returns extrapolated position.
Referenced by FillTrajectory(), and FillTrajectory3D().
ExtrapolateHead()
virtual TVector3 LKTracklet::ExtrapolateHead (double l) const pure virtual
Extrapolate head of track about length, returns extrapolated position.
ExtrapolateTail()
virtual TVector3 LKTracklet::ExtrapolateTail (double l) const pure virtual
Extrapolate tail of track about length, returns extrapolated position.
ExtrapolateTo()
virtual TVector3 LKTracklet::ExtrapolateTo (TVector3 point) const pure virtual
Extrapolate to POCA from point, returns extrapolated position.
Implemented in LKHelixTrack, LKLinearTrack, LKMCTrack, and LKExtrapolatedTrack.
FillTrajectory() [1/2]
void LKTracklet::FillTrajectory (TGraphErrors * graphTrack, LKVector3::Axis axis1, LKVector3::Axis axis2) virtual
Definition at line 192 of file LKTracklet.cpp.
References FillTrajectory().
FillTrajectory() [2/2]
void LKTracklet::FillTrajectory (TGraphErrors * graphTrack, LKVector3::Axis axis1, LKVector3::Axis axis2, bool(*)(TVector3 pos) fisout) virtual
Reimplemented in LKLinearTrack.
Definition at line 183 of file LKTracklet.cpp.
References ExtrapolateByRatio(), LKVector3::kZ, and SetPoint().
Referenced by FillTrajectory(), and TrajectoryOnPlane().
FillTrajectory3D() [1/2]
void LKTracklet::FillTrajectory3D (TGraph2DErrors * graphTrack3D, LKVector3::Axis axis1, LKVector3::Axis axis2, LKVector3::Axis axis3) virtual
Definition at line 207 of file LKTracklet.cpp.
References FillTrajectory3D().
FillTrajectory3D() [2/2]
void LKTracklet::FillTrajectory3D (TGraph2DErrors * graphTrack3D, LKVector3::Axis axis1, LKVector3::Axis axis2, LKVector3::Axis axis3, bool(*)(TVector3 pos) fisout) virtual
Reimplemented in LKLinearTrack.
Definition at line 198 of file LKTracklet.cpp.
References ExtrapolateByRatio(), LKVector3::kZ, and SetPoint().
Referenced by FillTrajectory3D().
FinalizeHits()
void LKTracklet::FinalizeHits () virtual
Definition at line 62 of file LKTracklet.cpp.
References fHitArray, fTrackID, next(), and SetTrackID().
Fit()
virtual bool LKTracklet::Fit () inline virtual
Reimplemented in LKHelixTrack, and LKLinearTrack.
Definition at line 110 of file LKTracklet.h.
FitHelix()
LKGeoHelix LKTracklet::FitHelix (LKVector3::Axis ref) virtual
Definition at line 259 of file LKTracklet.cpp.
References fHitArray, LKHitArray::FitHelix(), LKGeometry::GetRMS(), and SetIsHelix().
FitLine()
LKGeoLine LKTracklet::FitLine () virtual
Definition at line 243 of file LKTracklet.cpp.
References fHitArray, LKHitArray::FitLine(), LKGeometry::GetRMS(), and SetIsLine().
FitPlane()
LKGeoPlane LKTracklet::FitPlane () virtual
Reimplemented in LKHelixTrack.
Definition at line 251 of file LKTracklet.cpp.
References fHitArray, LKHitArray::FitPlane(), LKGeometry::GetRMS(), and SetIsPlane().
GetChargeSum()
double LKTracklet::GetChargeSum () const inline
Definition at line 90 of file LKTracklet.h.
References fHitArray, and LKHitArray::GetW().
GetFitStatus()
LKTracklet::LKFitStatus LKTracklet::GetFitStatus () const inline
Definition at line 35 of file LKTracklet.h.
References fFitStatus.
GetFitStatusString()
TString LKTracklet::GetFitStatusString () const inline
Definition at line 42 of file LKTracklet.h.
References fFitStatus, kBad, kGenfitTrack, kHelix, kLine, and kPlane.
Referenced by LKHelixTrack::Print().
GetHit()
LKHit * LKTracklet::GetHit (int idx) const inline
Definition at line 84 of file LKTracklet.h.
References fHitArray, and LKHitArray::GetHit().
GetHitArray()
LKHitArray * LKTracklet::GetHitArray () inline
Definition at line 86 of file LKTracklet.h.
References fHitArray.
Referenced by LKLinearTrack::CopyFrom(), TTHTTrackingTask::MakeTrack(), and TTHTtBeamTrackingTask::MakeTrack().
GetHitID()
int LKTracklet::GetHitID (int idx) const inline
Definition at line 85 of file LKTracklet.h.
References fHitIDArray.
Referenced by RecoverHitArrayWithHitID(), and RemoveHit().
GetHitIDArray()
std::vector< int > * LKTracklet::GetHitIDArray () inline
Definition at line 87 of file LKTracklet.h.
References fHitIDArray.
Referenced by LKLinearTrack::CopyFrom().
GetMean()
TVector3 LKTracklet::GetMean () const inline
Definition at line 89 of file LKTracklet.h.
References fHitArray, and LKHitArray::GetMean().
GetNumHits()
int LKTracklet::GetNumHits () const inline
Definition at line 83 of file LKTracklet.h.
References fHitIDArray.
Referenced by LKLinearTrack::Print().
GetParentID()
int LKTracklet::GetParentID () const inline
Definition at line 80 of file LKTracklet.h.
References fParentID.
Referenced by LKLinearTrack::CopyFrom(), and LKEveTask::SelectTrack().
GetPDG()
int LKTracklet::GetPDG () const inline
Definition at line 81 of file LKTracklet.h.
References fPDG.
Referenced by LKLinearTrack::CopyFrom(), and LKEveTask::SelectTrack().
GetTrackID()
int LKTracklet::GetTrackID () const inline
Definition at line 79 of file LKTracklet.h.
References fTrackID.
Referenced by LKVertex::AddTrack(), LKLinearTrack::CopyFrom(), and LKEveTask::SelectTrack().
IsBad()
bool LKTracklet::IsBad () const inline
Definition at line 36 of file LKTracklet.h.
References fFitStatus, and kBad.
IsGenfitTrack()
bool LKTracklet::IsGenfitTrack () const inline
Definition at line 40 of file LKTracklet.h.
References fFitStatus, and kGenfitTrack.
Referenced by LKHelixTrack::Momentum().
IsHelix()
bool LKTracklet::IsHelix () const inline
Definition at line 39 of file LKTracklet.h.
References fFitStatus, and kHelix.
Referenced by LKHelixTrack::Momentum().
IsHoldingHits()
bool LKTracklet::IsHoldingHits ()
Definition at line 107 of file LKTracklet.cpp.
References fHitArray, fHitIDArray, and LKHitArray::GetNumHits().
IsLine()
bool LKTracklet::IsLine () const inline
Definition at line 37 of file LKTracklet.h.
References fFitStatus, and kLine.
IsPlane()
bool LKTracklet::IsPlane () const inline
Definition at line 38 of file LKTracklet.h.
References fFitStatus, and kPlane.
LengthAt()
virtual double LKTracklet::LengthAt (TVector3 point) const pure virtual
Length at POCA from point, where tail=0, head=TrackLength.
Implemented in LKHelixTrack, LKLinearTrack, LKMCTrack, and LKExtrapolatedTrack.
Momentum()
virtual TVector3 LKTracklet::Momentum (double B = 0.5) const pure virtual
Momentum of track at head.
PositionAtHead()
virtual TVector3 LKTracklet::PositionAtHead () const pure virtual
Position at head of helix.
Implemented in LKExtrapolatedTrack, LKHelixTrack, LKLinearTrack, and LKMCTrack.
PositionAtTail()
virtual TVector3 LKTracklet::PositionAtTail () const pure virtual
Position at tail of helix.
Implemented in LKExtrapolatedTrack, LKHelixTrack, LKLinearTrack, and LKMCTrack.
RecoverHitArrayWithHitID()
int LKTracklet::RecoverHitArrayWithHitID (TClonesArray * hitArray) virtual
Be cautious on using this method! This method assumes that hit array was used to create track in same run and event This method will recover hit-array of track, which is removed before end of LILAK run. The track store hit IDs. The method will use this information to recover hit array.
Definition at line 87 of file LKTracklet.cpp.
References LKHitArray::AddHit(), fHitArray, fHitIDArray, and GetHitID().
RecoverHitArrayWithTrackID()
int LKTracklet::RecoverHitArrayWithTrackID (TClonesArray * hitArray) virtual
Be cautious on using this method! This method assumes that hit array and track were cretaed in same run and event This method will recover hit-array of track, which is removed before end of LILAK run. The track ID is set in hit container. The method will use this information to recover hit array.
Definition at line 72 of file LKTracklet.cpp.
References LKHitArray::AddHit(), fHitArray, and fTrackID.
RemoveHit()
void LKTracklet::RemoveHit (LKHit * hit) virtual
Definition at line 49 of file LKTracklet.cpp.
References fHitArray, fHitIDArray, GetHitID(), and LKHitArray::RemoveHit().
SetFitStatus()
void LKTracklet::SetFitStatus (LKFitStatus value) inline
Definition at line 28 of file LKTracklet.h.
References fFitStatus.
SetIsBad()
void LKTracklet::SetIsBad () inline
Definition at line 29 of file LKTracklet.h.
References fFitStatus, and kBad.
SetIsGenfitTrack()
void LKTracklet::SetIsGenfitTrack () inline
Definition at line 33 of file LKTracklet.h.
References fFitStatus, and kGenfitTrack.
SetIsHelix()
void LKTracklet::SetIsHelix () inline
Definition at line 32 of file LKTracklet.h.
References fFitStatus, and kHelix.
Referenced by LKHelixTrack::Fit(), and FitHelix().
SetIsLine()
void LKTracklet::SetIsLine () inline
Definition at line 30 of file LKTracklet.h.
References fFitStatus, and kLine.
Referenced by FitLine(), and LKHelixTrack::FitPlane().
SetIsPlane()
void LKTracklet::SetIsPlane () inline
Definition at line 31 of file LKTracklet.h.
References fFitStatus, and kPlane.
Referenced by LKHelixTrack::FitPlane(), and FitPlane().
SetParentID()
void LKTracklet::SetParentID (int val) inline
Definition at line 76 of file LKTracklet.h.
References fParentID.
SetPDG()
void LKTracklet::SetPDG (int val) inline
Definition at line 77 of file LKTracklet.h.
References fPDG.
SetTrackID()
void LKTracklet::SetTrackID (int val) inline
Definition at line 75 of file LKTracklet.h.
References fTrackID.
Referenced by AddHit(), and FinalizeHits().
SortHits()
void LKTracklet::SortHits (bool increasing = true) virtual
Reimplemented in LKHelixTrack.
Definition at line 267 of file LKTracklet.cpp.
References fHitArray, LKHit::GetPosition(), and next().
Referenced by Continuity().
TrackLength()
virtual double LKTracklet::TrackLength () const pure virtual
Length of track calculated from head to tail.
Implemented in LKExtrapolatedTrack, LKHelixTrack, LKLinearTrack, and LKMCTrack.
TrajectoryOnPlane() [1/3]
TGraphErrors * LKTracklet::TrajectoryOnPlane (LKDetectorPlane * plane, double scale = 1) virtual
Definition at line 178 of file LKTracklet.cpp.
References LKDetectorPlane::GetAxis1(), LKDetectorPlane::GetAxis2(), and TrajectoryOnPlane().
TrajectoryOnPlane() [2/3]
TGraphErrors * LKTracklet::TrajectoryOnPlane (LKVector3::Axis axis1, LKVector3::Axis axis2, bool(*)(TVector3 pos) fisout, double scale = 1) virtual
Definition at line 159 of file LKTracklet.cpp.
References FillTrajectory(), and fTrajectoryOnPlane.
Referenced by TrajectoryOnPlane(), and TrajectoryOnPlane().
TrajectoryOnPlane() [3/3]
TGraphErrors * LKTracklet::TrajectoryOnPlane (LKVector3::Axis axis1, LKVector3::Axis axis2, double scale = 1) virtual
Definition at line 172 of file LKTracklet.cpp.
References TrajectoryOnPlane().
Member Data Documentation
fFitStatus
LKFitStatus LKTracklet::fFitStatus protected
One of kBad, kHelix and kLine.
Definition at line 61 of file LKTracklet.h.
Referenced by LKHelixTrack::Clear(), LKHelixTrack::Copy(), GetFitStatus(), GetFitStatusString(), IsBad(), IsGenfitTrack(), IsHelix(), IsLine(), IsPlane(), LKHelixTrack::Print(), SetFitStatus(), SetIsBad(), SetIsGenfitTrack(), SetIsHelix(), SetIsLine(), and SetIsPlane().
fHitArray
LKHitArray LKTracklet::fHitArray protected
Definition at line 56 of file LKTracklet.h.
Referenced by AddHit(), ClassImp(), ClearHits(), LKHelixTrack::Continuity(), Continuity(), LKHelixTrack::Copy(), LKLinearTrack::CopyFrom(), FinalizeHits(), LKHelixTrack::Fit(), LKLinearTrack::Fit(), FitHelix(), FitLine(), LKHelixTrack::FitPlane(), FitPlane(), GetChargeSum(), GetHit(), GetHitArray(), GetMean(), IsHoldingHits(), LKHelixTrack::PerpLine(), LKHelixTrack::PerpPlane(), LKHelixTrack::Print(), LKLinearTrack::Print(), RecoverHitArrayWithHitID(), RecoverHitArrayWithTrackID(), RemoveHit(), LKLinearTrack::SetLine(), LKHelixTrack::SortHits(), and SortHits().
fHitIDArray
vector<int> LKTracklet::fHitIDArray protected
Definition at line 57 of file LKTracklet.h.
Referenced by AddHit(), ClassImp(), ClearHits(), LKLinearTrack::CopyFrom(), GetHitID(), GetHitIDArray(), GetNumHits(), IsHoldingHits(), LKLinearTrack::Print(), RecoverHitArrayWithHitID(), and RemoveHit().
fParentID
int LKTracklet::fParentID = -1 protected
Vertex ID.
Definition at line 53 of file LKTracklet.h.
Referenced by ClassImp(), LKHelixTrack::Copy(), LKLinearTrack::CopyFrom(), GetParentID(), LKHelixTrack::Print(), LKMCTrack::Print(), LKMCTrack::SetMCTrack(), SetParentID(), and LKMCTrack::TrajectoryOnPlane().
fPDG
int LKTracklet::fPDG = -1 protected
Definition at line 54 of file LKTracklet.h.
Referenced by ClassImp(), LKLinearTrack::CopyFrom(), GetPDG(), LKMCTrack::Print(), LKMCTrack::SetMCTrack(), SetPDG(), and LKMCTrack::TrajectoryOnPlane().
fTrackID
int LKTracklet::fTrackID = -1 protected
Definition at line 52 of file LKTracklet.h.
Referenced by AddHit(), ClassImp(), LKHelixTrack::Copy(), LKLinearTrack::CopyFrom(), FinalizeHits(), GetTrackID(), LKHelixTrack::LKHelixTrack(), LKHelixTrack::Print(), LKLinearTrack::Print(), LKMCTrack::Print(), RecoverHitArrayWithTrackID(), LKMCTrack::SetMCTrack(), and SetTrackID().
fTrajectoryOnPlane
TGraphErrors* LKTracklet::fTrajectoryOnPlane = nullptr protected
Definition at line 59 of file LKTracklet.h.
Referenced by LKMCTrack::TrajectoryOnPlane(), TrajectoryOnPlane(), LKExtrapolatedTrack::TrajectoryOnPlane(), and LKExtrapolatedTrack::TrajectoryOnPlane().
The documentation for this class was generated from the following files:
LKTracklet.h
LKTracklet.cpp