lilak: LKGeoLine Class Reference
LKGeoLine Class Reference
#include <LKGeoLine.h>
Public Member Functions
void ClosestPointOnLine (Double_t x, Double_t y, Double_t z, Double_t &x0, Double_t &y0, Double_t &z0) const
TVector3 ClosestPointOnLine (TVector3 pos) const
TVector3 Direction () const
1 to 2
Double_t DistanceToLine (Double_t x, Double_t y, Double_t z) const
Double_t DistanceToLine (TVector3 pos) const
TArrow * DrawArrowXY (Double_t asize=0.02)
TArrow * DrawArrowXZ (Double_t asize=0.02)
TArrow * DrawArrowYZ (Double_t asize=0.02)
TArrow * DrawArrowZX (Double_t asize=0.02)
TArrow * DrawArrowZY (Double_t asize=0.02)
virtual TVector3 GetCenter () const
TVector3 GetCrossingPoint (LKGeoPlaneWithCenter plane2) const
TGraph2D * GetGraphXYZ ()
TGraph2D * GetGraphZXY ()
TVector3 GetPoint1 () const
TVector3 GetPoint2 () const
TVector3 GetPointAtT (double t) const
TVector3 GetPointAtX (double x) const
TVector3 GetPointAtY (double y) const
TVector3 GetPointAtZ (double z) const
Double_t GetT () const
Double_t GetX1 () const
Double_t GetX2 () const
Double_t GetY1 () const
Double_t GetY2 () const
Double_t GetZ1 () const
Double_t GetZ2 () const
Double_t Length () const
Double_t Length (Double_t x, Double_t y, Double_t z) const
Double_t Length (TVector3 position) const
LKGeoLine ()
LKGeoLine (Double_t x1, Double_t y1, Double_t z1, Double_t x2, Double_t y2, Double_t z2)
LKGeoLine (TVector3 pos1, TVector3 pos2)
void Print (Option_t *option="") const
virtual void SetLine (Double_t x1, Double_t y1, Double_t z1, Double_t x2, Double_t y2, Double_t z2)
virtual void SetLine (LKGeoLine *line)
virtual void SetLine (TVector3 pos1, TVector3 pos2)
bool SetRange (LKGeoBox *box)
virtual ~LKGeoLine ()
Public Member Functions inherited from LKGeometry
Double_t GetRMS () const
LKGeometry ()
void SetRMS (Double_t val)
virtual ~LKGeometry ()
Protected Attributes
Double_t fX1 = 0
Double_t fX2 = 0
Double_t fY1 = 0
Double_t fY2 = 0
Double_t fZ1 = 0
Double_t fZ2 = 0
Protected Attributes inherited from LKGeometry
Double_t fRMS = -1
Detailed Description
(x-x1)/v_x = (y-y1)/v_y = (z-z1)/v_z = t
Definition at line 18 of file LKGeoLine.h.
Constructor & Destructor Documentation
LKGeoLine() [1/3]
LKGeoLine::LKGeoLine ()
LKGeoLine() [2/3]
LKGeoLine::LKGeoLine (Double_t x1, Double_t y1, Double_t z1, Double_t x2, Double_t y2, Double_t z2)
Definition at line 12 of file LKGeoLine.cpp.
References SetLine(), y2, z1, and z2.
LKGeoLine() [3/3]
LKGeoLine::LKGeoLine (TVector3 pos1, TVector3 pos2)
Definition at line 17 of file LKGeoLine.cpp.
References SetLine().
~LKGeoLine()
virtual LKGeoLine::~LKGeoLine () inline virtual
Definition at line 24 of file LKGeoLine.h.
Member Function Documentation
ClosestPointOnLine() [1/2]
void LKGeoLine::ClosestPointOnLine (Double_t x, Double_t y, Double_t z, Double_t & x0, Double_t & y0, Double_t & z0) const
Definition at line 116 of file LKGeoLine.cpp.
References ClosestPointOnLine(), x0, y0, and z0.
Referenced by ClosestPointOnLine(), DistanceToLine(), DistanceToLine(), LKLinearTrack::ExtrapolateTo(), LKExtrapolatedTrack::ExtrapolateTo(), LKLinearTrack::Fit(), and LKLinearTrack::SetLine().
ClosestPointOnLine() [2/2]
TVector3 LKGeoLine::ClosestPointOnLine (TVector3 pos) const
Definition at line 125 of file LKGeoLine.cpp.
References Direction(), fX1, fY1, and fZ1.
Direction()
TVector3 LKGeoLine::Direction () const
1 to 2
Definition at line 95 of file LKGeoLine.cpp.
References fX1, fX2, fY1, fY2, fZ1, and fZ2.
Referenced by ClosestPointOnLine(), LKLinearTrack::Create3DTrack(), GetCrossingPoint(), GetPointAtT(), GetT(), LKGeoPlaneWithCenter::Intersection(), LKLinearTrack::Momentum(), and Print().
DistanceToLine() [1/2]
Double_t LKGeoLine::DistanceToLine (Double_t x, Double_t y, Double_t z) const
Definition at line 185 of file LKGeoLine.cpp.
References ClosestPointOnLine(), x0, y0, and z0.
DistanceToLine() [2/2]
Double_t LKGeoLine::DistanceToLine (TVector3 pos) const
Definition at line 194 of file LKGeoLine.cpp.
References ClosestPointOnLine(), x0, y0, and z0.
DrawArrowXY()
TArrow * LKGeoLine::DrawArrowXY (Double_t asize = 0.02)
Definition at line 213 of file LKGeoLine.cpp.
References fX1, fX2, fY1, and fY2.
Referenced by LKVector3::ArrowXY(), LKHitArray::DrawFitCircle(), and odr_fitter_and_weight().
DrawArrowXZ()
TArrow * LKGeoLine::DrawArrowXZ (Double_t asize = 0.02)
Definition at line 217 of file LKGeoLine.cpp.
References fX1, fX2, fZ1, and fZ2.
DrawArrowYZ()
TArrow * LKGeoLine::DrawArrowYZ (Double_t asize = 0.02)
Definition at line 214 of file LKGeoLine.cpp.
References fY1, fY2, fZ1, and fZ2.
Referenced by LKVector3::ArrowYZ().
DrawArrowZX()
TArrow * LKGeoLine::DrawArrowZX (Double_t asize = 0.02)
Definition at line 216 of file LKGeoLine.cpp.
References fX1, fX2, fZ1, and fZ2.
Referenced by LKVector3::ArrowZX().
DrawArrowZY()
TArrow * LKGeoLine::DrawArrowZY (Double_t asize = 0.02)
Definition at line 215 of file LKGeoLine.cpp.
References fY1, fY2, fZ1, and fZ2.
GetCenter()
TVector3 LKGeoLine::GetCenter () const virtual
Definition at line 31 of file LKGeoLine.cpp.
References fX1, fX2, fY1, fY2, fZ1, and fZ2.
GetCrossingPoint()
TVector3 LKGeoLine::GetCrossingPoint (LKGeoPlaneWithCenter plane2) const
Definition at line 79 of file LKGeoLine.cpp.
References Direction(), LKGeoPlane::GetD(), LKGeoPlane::GetNormal(), GetPoint1(), and GetPointAtT().
Referenced by GetPointAtX(), GetPointAtY(), and GetPointAtZ().
GetGraphXYZ()
TGraph2D * LKGeoLine::GetGraphXYZ ()
Definition at line 219 of file LKGeoLine.cpp.
References fX1, fX2, fY1, fY2, fZ1, fZ2, and SetPoint().
GetGraphZXY()
TGraph2D * LKGeoLine::GetGraphZXY ()
Definition at line 227 of file LKGeoLine.cpp.
References fX1, fX2, fY1, fY2, fZ1, fZ2, and SetPoint().
Referenced by DrawEvent().
GetPoint1()
TVector3 LKGeoLine::GetPoint1 () const
Definition at line 76 of file LKGeoLine.cpp.
References fX1, fY1, and fZ1.
Referenced by GetCrossingPoint(), LKGeoPlaneWithCenter::Intersection(), and LKLinearTrack::PositionAtTail().
GetPoint2()
TVector3 LKGeoLine::GetPoint2 () const
Definition at line 77 of file LKGeoLine.cpp.
References fX2, fY2, and fZ2.
Referenced by LKLinearTrack::PositionAtHead().
GetPointAtT()
TVector3 LKGeoLine::GetPointAtT (double t) const
Definition at line 90 of file LKGeoLine.cpp.
References Direction(), fX1, fY1, and fZ1.
Referenced by GetCrossingPoint().
GetPointAtX()
TVector3 LKGeoLine::GetPointAtX (double x) const
Definition at line 87 of file LKGeoLine.cpp.
References GetCrossingPoint().
Referenced by LKLinearTrack::Create3DTrack(), DrawEvent(), and httask::MakeTrack().
GetPointAtY()
TVector3 LKGeoLine::GetPointAtY (double y) const
Definition at line 88 of file LKGeoLine.cpp.
References GetCrossingPoint().
Referenced by LKLinearTrack::Create3DTrack().
GetPointAtZ()
TVector3 LKGeoLine::GetPointAtZ (double z) const
Definition at line 89 of file LKGeoLine.cpp.
References GetCrossingPoint().
Referenced by LKLinearTrack::Create3DTrack(), and TTHTtBeamTrackingTask::MakeTrack().
GetT()
Double_t LKGeoLine::GetT () const
Definition at line 69 of file LKGeoLine.cpp.
References Direction(), fX1, fX2, fY1, fY2, fZ1, and fZ2.
GetX1()
Double_t LKGeoLine::GetX1 () const
Definition at line 63 of file LKGeoLine.cpp.
References fX1.
Referenced by LKLinearTrack::CopyFrom(), LKLinearTrack::Create3DTrack(), and SetLine().
GetX2()
Double_t LKGeoLine::GetX2 () const
Definition at line 66 of file LKGeoLine.cpp.
References fX2.
Referenced by LKLinearTrack::CopyFrom(), LKLinearTrack::Create3DTrack(), and SetLine().
GetY1()
Double_t LKGeoLine::GetY1 () const
Definition at line 64 of file LKGeoLine.cpp.
References fY1.
Referenced by LKLinearTrack::CopyFrom(), LKLinearTrack::Create3DTrack(), and SetLine().
GetY2()
Double_t LKGeoLine::GetY2 () const
Definition at line 67 of file LKGeoLine.cpp.
References fY2.
Referenced by LKLinearTrack::CopyFrom(), LKLinearTrack::Create3DTrack(), and SetLine().
GetZ1()
Double_t LKGeoLine::GetZ1 () const
Definition at line 65 of file LKGeoLine.cpp.
References fZ1.
Referenced by LKLinearTrack::CopyFrom(), and SetLine().
GetZ2()
Double_t LKGeoLine::GetZ2 () const
Definition at line 68 of file LKGeoLine.cpp.
References fZ2.
Referenced by LKLinearTrack::CopyFrom(), and SetLine().
Length() [1/3]
Double_t LKGeoLine::Length () const
Definition at line 114 of file LKGeoLine.cpp.
References fX1, fX2, fY1, fY2, fZ1, and fZ2.
Referenced by LKLinearTrack::Fit(), Length(), LKLinearTrack::SetLine(), and LKLinearTrack::TrackLength().
Length() [2/3]
Double_t LKGeoLine::Length (Double_t x, Double_t y, Double_t z) const
Definition at line 101 of file LKGeoLine.cpp.
References fX1, fX2, fY1, fY2, fZ1, and fZ2.
Length() [3/3]
Double_t LKGeoLine::Length (TVector3 position) const
Definition at line 113 of file LKGeoLine.cpp.
References Length().
Print()
void LKGeoLine::Print (Option_t * option = "") const
Definition at line 22 of file LKGeoLine.cpp.
References Direction(), e_info, fX1, fX2, fY1, fY2, fZ1, and fZ2.
SetLine() [1/3]
void LKGeoLine::SetLine (Double_t x1, Double_t y1, Double_t z1, Double_t x2, Double_t y2, Double_t z2) virtual
Reimplemented in LKLinearTrack.
Definition at line 33 of file LKGeoLine.cpp.
References fX1, fX2, fY1, fY2, fZ1, fZ2, y2, z1, and z2.
Referenced by DrawEvent(), LKHitArray::FitLine(), LKGeoLine(), LKGeoLine(), LKLinearTrack::SetLine(), SetRange(), and LKLinearTrack::SetTrack().
SetLine() [2/3]
void LKGeoLine::SetLine (LKGeoLine * line) virtual
Reimplemented in LKLinearTrack.
Definition at line 53 of file LKGeoLine.cpp.
References fX1, fX2, fY1, fY2, fZ1, fZ2, GetX1(), GetX2(), GetY1(), GetY2(), GetZ1(), and GetZ2().
SetLine() [3/3]
void LKGeoLine::SetLine (TVector3 pos1, TVector3 pos2) virtual
Reimplemented in LKLinearTrack.
Definition at line 43 of file LKGeoLine.cpp.
References fX1, fX2, fY1, fY2, fZ1, and fZ2.
SetRange()
bool LKGeoLine::SetRange (LKGeoBox * box)
Definition at line 203 of file LKGeoLine.cpp.
References fX1, fX2, fY1, fY2, fZ1, fZ2, and SetLine().
Referenced by odr_fitter_and_weight().
Member Data Documentation
fX1
Double_t LKGeoLine::fX1 = 0 protected
Definition at line 85 of file LKGeoLine.h.
Referenced by LKLinearTrack::Clear(), ClosestPointOnLine(), LKLinearTrack::CopyFrom(), Direction(), DrawArrowXY(), DrawArrowXZ(), DrawArrowZX(), GetCenter(), GetGraphXYZ(), GetGraphZXY(), GetPoint1(), GetPointAtT(), GetT(), GetX1(), Length(), Length(), LKLinearTrack::Print(), Print(), LKLinearTrack::ProjectionOnPlane(), LKLinearTrack::SetLine(), SetLine(), SetLine(), SetLine(), and SetRange().
fX2
Double_t LKGeoLine::fX2 = 0 protected
Definition at line 89 of file LKGeoLine.h.
Referenced by LKLinearTrack::Clear(), LKLinearTrack::CopyFrom(), Direction(), DrawArrowXY(), DrawArrowXZ(), DrawArrowZX(), GetCenter(), GetGraphXYZ(), GetGraphZXY(), GetPoint2(), GetT(), GetX2(), Length(), Length(), LKLinearTrack::Print(), Print(), LKLinearTrack::ProjectionOnPlane(), LKLinearTrack::SetLine(), SetLine(), SetLine(), SetLine(), and SetRange().
fY1
Double_t LKGeoLine::fY1 = 0 protected
Definition at line 86 of file LKGeoLine.h.
Referenced by LKLinearTrack::Clear(), ClosestPointOnLine(), LKLinearTrack::CopyFrom(), Direction(), DrawArrowXY(), DrawArrowYZ(), DrawArrowZY(), GetCenter(), GetGraphXYZ(), GetGraphZXY(), GetPoint1(), GetPointAtT(), GetT(), GetY1(), Length(), Length(), LKLinearTrack::Print(), Print(), LKLinearTrack::ProjectionOnPlane(), LKLinearTrack::SetLine(), SetLine(), SetLine(), SetLine(), and SetRange().
fY2
Double_t LKGeoLine::fY2 = 0 protected
Definition at line 90 of file LKGeoLine.h.
Referenced by LKLinearTrack::Clear(), LKLinearTrack::CopyFrom(), Direction(), DrawArrowXY(), DrawArrowYZ(), DrawArrowZY(), GetCenter(), GetGraphXYZ(), GetGraphZXY(), GetPoint2(), GetT(), GetY2(), Length(), Length(), LKLinearTrack::Print(), Print(), LKLinearTrack::ProjectionOnPlane(), LKLinearTrack::SetLine(), SetLine(), SetLine(), SetLine(), and SetRange().
fZ1
Double_t LKGeoLine::fZ1 = 0 protected
Definition at line 87 of file LKGeoLine.h.
Referenced by LKLinearTrack::Clear(), ClosestPointOnLine(), LKLinearTrack::CopyFrom(), Direction(), DrawArrowXZ(), DrawArrowYZ(), DrawArrowZX(), DrawArrowZY(), GetCenter(), GetGraphXYZ(), GetGraphZXY(), GetPoint1(), GetPointAtT(), GetT(), GetZ1(), Length(), Length(), LKLinearTrack::Print(), Print(), LKLinearTrack::ProjectionOnPlane(), LKLinearTrack::SetLine(), SetLine(), SetLine(), SetLine(), and SetRange().
fZ2
Double_t LKGeoLine::fZ2 = 0 protected
Definition at line 91 of file LKGeoLine.h.
Referenced by LKLinearTrack::Clear(), LKLinearTrack::CopyFrom(), Direction(), DrawArrowXZ(), DrawArrowYZ(), DrawArrowZX(), DrawArrowZY(), GetCenter(), GetGraphXYZ(), GetGraphZXY(), GetPoint2(), GetT(), GetZ2(), Length(), Length(), LKLinearTrack::Print(), Print(), LKLinearTrack::ProjectionOnPlane(), LKLinearTrack::SetLine(), SetLine(), SetLine(), SetLine(), and SetRange().
The documentation for this class was generated from the following files:
LKGeoLine.h
LKGeoLine.cpp