LILAK: LHPadPlaneFan Class Reference
LHPadPlaneFan Class Reference
#include <LHPadPlaneFan.h>
Public Member Functions
void AddChannel (LKChannel *channel)
Add channel to channel array in detector plane. For interanl use.
void AddHit (LKHit *hit)
void AddPad (LKPad *pad)
Add pad to pad array in detector plane. For interanl use.
void AddPar (LKParameterContainer *par)
void AddPar (TString fname)
virtual void AddParameterContainer (LKParameterContainer *par)
virtual void AddParameterContainer (TString fname)
virtual void Clear (Option_t *option="")
void CreateParameterContainer ()
virtual void Draw (Option_t *option="")
Implementation recommanded for event display. Draw event display to the canvas.
virtual void DrawFrame (Option_t *option="")
virtual void DrawHist (Option_t *option="")
virtual void DriftElectron (TVector3 posGlobal, TVector3 &posFinal, double &driftLength)
virtual double DriftElectronBack (double tb)
virtual void DriftElectronBack (int padID, double tb, TVector3 &posReco, double &driftLength)
virtual void DriftElectronBack (LKPad *pad, double tb, TVector3 &posReco, double &driftLength)
virtual void FillDataToHist ()
Implementation recommanded. Fill data to histograms.
void FillPlane (double i, double j, double tb, double charge, int trackID=-1)
Find pad corresponding to the position (i,j) and fill time-bin by amount of charge.
virtual int FindChannelID (double i, double j)
Implementation recommanded. Find channel using position.
virtual int FindChannelID (int section, int layer, int row)
Implementation recommanded. Find channel using section, layer, row info.
virtual int FindPadID (double i, double j)
virtual Int_t FindPadID (Double_t i, Double_t j)
virtual int FindPadID (int cobo, int asad, int aget, int chan)
virtual int FindPadID (int section, int layer, int row)
virtual Int_t FindPadID (Int_t section, Int_t row, Int_t layer)
virtual TPad * Get3DEventPad ()
If user wants to place 3D event display other than default canvas, this method should return corresponding TPad.
virtual axis_t GetAxis1 (int iPad=0) const
virtual axis_t GetAxis2 (int iPad=0) const
virtual axis_t GetAxis3 () const
virtual axis_t GetAxisDrift () const
virtual TCanvas * GetCanvas (Option_t *optiont="")
Implementation recommanded for event display.
LKChannel * GetChannel (int idx)
virtual LKChannelAnalyzer * GetChannelAnalyzer (int id=0)
TObjArray * GetChannelArray ()
LKChannel * GetChannelFast (int idx)
virtual TPad * GetCPad (int iPad)
For grabbing inner pads of canvas.
virtual TH2 * GetHist (Option_t *option="-1")
TObjArray * GetInPadArray ()
Int_t GetLayerDiv (Int_t idx)
int GetNChannels ()
Int_t GetNLayerDivision ()
virtual int GetNumCPads ()
Get number of inner pads of canvas.
int GetNumPads ()
LKPad * GetPad (double i, double j)
LKPad * GetPad (int cobo, int asad, int aget, int chan)
LKPad * GetPad (int padID)
LKPad * GetPad (int section, int layer, int row)
TObjArray * GetPadArray ()
LKPad * GetPadFast (int idx)
LKParameterContainer * GetPar () const
LKParameterContainer * GetParameterContainer () const
int GetPlaneID () const
double GetPosition () const
Int_t GetRank () const
Double_t GetRDiv (Int_t idx)
double GetTbToLength () const
virtual TVector3 GlobalToLocalAxis (TVector3 posGlobal)
Implementation recommanded. Convert global position to local detector plane position.
void GrabNeighborPads (vector< LKPad * > *pads, vector< LKPad * > *neighborPads)
For tracking use.
virtual bool Init ()
virtual bool IsInBoundary (double i, double j)
Implementation recommanded. Return if position (i,j) is inside the effective detector plane boundary.
virtual bool IsInBoundary (Double_t i, Double_t j)
LHPadPlaneFan ()
virtual TVector3 LocalToGlobalAxis (TVector3 posLocal)
virtual Double_t PadDisplacement () const
Return average pad displacement to each other.
bool PadMapChecker ()
bool PadNeighborChecker ()
bool PadPositionChecker (bool checkCorners=true)
virtual void Print (Option_t *option="") const
void PullOutNeighborHits (double x, double y, int range, LKHitArray *neighborHits)
For tracking use.
void PullOutNeighborHits (double x, double y, int range, vector< LKHit * > *neighborHits)
For tracking use.
void PullOutNeighborHits (LKHitArray *hits, LKHitArray *neighborHits)
For tracking use.
void PullOutNeighborHits (TVector2 p, int range, vector< LKHit * > *neighborHits)
For tracking use.
void PullOutNeighborHits (vector< LKHit * > *hits, vector< LKHit * > *neighborHits)
For tracking use.
void PullOutNeighborHitsIn (LKTpcHits *hits, LKTpcHits *nbHits)
void PullOutNeighborHitsIn (TVector3 p, Int_t range, LKTpcHits *nbHits)
virtual LKHit * PullOutNextFreeHit ()
For tracking use.
LKHit * PullOutNextFreeHitIn ()
virtual void ResetEvent ()
For tracking use.
virtual void ResetHitMap ()
For tracking use.
virtual bool SetDataFromBranch ()
Implementation recommanded. Set waveform and hit data from input tree branches to pads.
void SetDetector (LKDetector *detector)
void SetHitArray (TClonesArray *hitArray)
void SetPadArray (TClonesArray *padArray)
void SetPar (LKParameterContainer *par)
virtual void SetParameterContainer (LKParameterContainer *par)
void SetPlaneID (int id)
virtual void SetRank (Int_t rank)
void SetRun (LKRun *run)
virtual ~LHPadPlaneFan ()
Protected Attributes
axis_t fAxis1 = LKVector3::kNon
Axis-1 lying in plane. Must be set by input parameter.
axis_t fAxis2 = LKVector3::kNon
Axis-2 lying in plane. Must be set by input parameter.
axis_t fAxis3 = LKVector3::kNon
Axis-3 = Axis-1 x Axis-2 perpendicular to plane.
axis_t fAxisDrift = LKVector3::kNon
Axis perpendicular to plane, in electron drifting direction. Must be set by input parameter.
TCanvas * fCanvas = nullptr
LKChannelAnalyzer * fChannelAnalyzer = nullptr
TObjArray * fChannelArray = nullptr
TCanvas * fCvsChannelBuffer = nullptr
LKDetector * fDetector = nullptr
int fFreePadIdx = 0
TGraph * fGraphChannelBoundary = nullptr
TGraph * fGraphChannelBoundaryNb [20] = {0}
TH2 * fH2Plane = nullptr
bool fHitDataIsSet = false
bool fPadDataIsSet = false
LKParameterContainer * fPar = nullptr
int fPlaneID = -1
Detector plane id.
double fPosition
Global position of pad plane center.
Int_t fRank = 0
LKRun * fRun = nullptr
double fTbToLength = 1
time-bin (tb) to position conversion factor. Must be set by input parameter.
Private Member Functions
void AddPad (Int_t section, Int_t layer, Int_t row, Double_t i, Double_t j, bool innerTrackerPad)
Int_t FindDivisionIndex (Double_t r)
Int_t FindDivisionIndex (Int_t layer)
Int_t FindSection (Double_t i, Double_t j)
void MapPad (LKPad *pad)
Private Attributes
Double_t * fArcLength
Double_t fCosPiNo4 [8]
Int_t fFreeInPadIdx = 0
TF1 * fFuncXRightBound = nullptr
Int_t fInDivisionIndex = 0
TObjArray * fInPadArray = nullptr
std::vector< Int_t > fLayerDivI
std::vector< Int_t > fNHalfRowsInLayer
Int_t fNLayerDivision = 0
Int_t * fNLayers
Int_t fNLayersTotal = 0
std::map< std::vector< Int_t >, Int_t > fPadMap
Double_t * fRadius
std::vector< Double_t > fRDivI
Double_t fRMax = 0
Double_t fRMin = 0
Double_t fSinPiNo4 [8]
Double_t fTanPi1o8
Double_t fTanPi3o8
Double_t fTanPi5o8
Double_t fTanPi7o8
Detailed Description
Definition at line 10 of file LHPadPlaneFan.h.
Constructor & Destructor Documentation
LHPadPlaneFan()
LHPadPlaneFan::LHPadPlaneFan ()
~LHPadPlaneFan()
virtual LHPadPlaneFan::~LHPadPlaneFan () inline virtual
Definition at line 14 of file LHPadPlaneFan.h.
Member Function Documentation
AddChannel()
void LKDetectorPlane::AddChannel (LKChannel * channel) inline inherited
Add channel to channel array in detector plane. For interanl use.
Definition at line 113 of file LKDetectorPlane.h.
References LKDetectorPlane::fChannelArray.
AddHit()
void LKDetectorPlane::AddHit (LKHit * hit) inherited
Definition at line 118 of file LKDetectorPlane.cpp.
References LKDetectorPlane::AddHit(), and LKDetectorPlane::GetPadFast().
Referenced by LKDetectorPlane::AddHit(), and LKDetectorPlane::SetHitArray().
AddPad() [1/2]
void LHPadPlaneFan::AddPad (Int_t section, Int_t layer, Int_t row, Double_t i, Double_t j, bool innerTrackerPad = false) private
Definition at line 481 of file LHPadPlaneFan.cpp.
References LKDetectorPlane::fChannelArray, and fInPadArray.
Referenced by Init().
AddPad() [2/2]
void LKDetectorPlane::AddPad (LKPad * pad) inline inherited
Add pad to pad array in detector plane. For interanl use.
Definition at line 114 of file LKDetectorPlane.h.
References LKDetectorPlane::fChannelArray.
AddPar() [1/2]
void LKGear::AddPar (LKParameterContainer * par) inline inherited
Definition at line 27 of file LKGear.h.
References LKGear::AddParameterContainer().
Referenced by LKTask::Add(), LKRun::EndOfRun(), LKRun::Init(), LKG4RunManager::Initialize(), LAMPSTPC::LAMPSTPC(), LAMPSTPC::LAMPSTPC(), LKDetectorSystem::SetDetectorPar(), LKRun::SetEventTrigger(), LKG4RunManager::SetSensitiveDetector(), LKG4RunManager::SetVolume(), LKRun::StartOfRun(), TexAT2::TexAT2(), TexAT2::TexAT2(), and TTMicromegas::WriteCurrentChannel().
AddPar() [2/2]
void LKGear::AddPar (TString fname) inline inherited
Definition at line 28 of file LKGear.h.
References LKGear::AddParameterContainer().
AddParameterContainer() [1/2]
void LKGear::AddParameterContainer (LKParameterContainer * par) virtual inherited
Definition at line 14 of file LKGear.cpp.
References LKGear::AddParameterContainer(), and LKGear::fPar.
Referenced by LKGear::AddPar(), LKGear::AddPar(), LKGear::AddParameterContainer(), LHTpc::BuildDetectorPlane(), and LKRun::Init().
AddParameterContainer() [2/2]
void LKGear::AddParameterContainer (TString fname) virtual inherited
Definition at line 22 of file LKGear.cpp.
References LKGear::fPar.
Clear()
void LKDetectorPlane::Clear (Option_t * option = "") virtual inherited
Reimplemented in ATMicromegas, LTPadPlane, LKEvePlane, LKPadPlane, TTMicromegas, and TTFrontPlane.
Definition at line 19 of file LKDetectorPlane.cpp.
References LKDetectorPlane::Clear(), and LKDetectorPlane::fChannelArray.
Referenced by LKDetectorPlane::Clear(), LKEvePlane::Clear(), TTMicromegas::Clear(), LKDetectorPlane::Draw(), LKDetectorPlane::DrawHist(), and LKDetectorPlane::SetDataFromBranch().
CreateParameterContainer()
void LKGear::CreateParameterContainer () inherited
Referenced by LKRun::AddDetector(), and LKRun::LKRun().
Draw()
void LKDetectorPlane::Draw (Option_t * option = "") virtual inherited
Implementation recommanded for event display. Draw event display to the canvas.
Reimplemented in LKEvePlane, TTMicromegas, TTFrontPlane, ATTPC20RectanglePad, ATTPCHoneyCombPad, ATTPCRectanglePad, and ATTPCStripPad.
Definition at line 660 of file LKDetectorPlane.cpp.
References LKDetectorPlane::Clear(), cvs, LKDetectorPlane::Draw(), LKDetectorPlane::DrawFrame(), LKDetectorPlane::FillDataToHist(), LKDetectorPlane::GetCanvas(), LKDetectorPlane::GetHist(), and LKDetectorPlane::SetDataFromBranch().
Referenced by LKDetectorPlane::Draw(), DrawFrame(), LHPadPlaneRCut::DrawFrame(), LKPadPlane::DrawHist(), and LKDetectorPlane::DrawHist().
DrawFrame()
void LHPadPlaneFan::DrawFrame (Option_t * option = "") virtual
Reimplemented from LKDetectorPlane.
Definition at line 416 of file LHPadPlaneFan.cpp.
References LKDetectorPlane::Draw(), fNLayerDivision, fRDivI, fRMax, and fRMin.
DrawHist()
void LKDetectorPlane::DrawHist (Option_t * option = "") virtual inherited
Reimplemented in LKEvePlane.
Definition at line 635 of file LKDetectorPlane.cpp.
References LKDetectorPlane::Clear(), LKDetectorPlane::Draw(), LKDetectorPlane::DrawFrame(), LKDetectorPlane::fCanvas, LKDetectorPlane::FillDataToHist(), LKDetectorPlane::GetCanvas(), and LKDetectorPlane::GetHist().
DriftElectron()
void LKDetectorPlane::DriftElectron (TVector3 posGlobal, TVector3 & posFinal, double & driftLength) virtual inherited
Implementation recommanded. Return position (x,y,z). x,y is pad position in pad plane. z is pad plane position of electron-drift-axis (for simulation)
Parameters
posGlobal[in] Given global position of the electron.
posFinal[in] Final position of electron after full drift (at the pad plane).
driftLength[out] Final drift length of the electron
Definition at line 679 of file LKDetectorPlane.cpp.
References LKVector3::At(), LKDetectorPlane::fAxis1, LKDetectorPlane::fAxis2, LKDetectorPlane::fAxis3, and LKDetectorPlane::fPosition.
DriftElectronBack() [1/3]
double LKDetectorPlane::DriftElectronBack (double tb) virtual inherited
Implementation recommanded. return drift length
Definition at line 708 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fPosition, and LKDetectorPlane::fTbToLength.
DriftElectronBack() [2/3]
void LKDetectorPlane::DriftElectronBack (int padID, double tb, TVector3 & posReco, double & driftLength) virtual inherited
Reimplemented in LKEvePlane.
Definition at line 702 of file LKDetectorPlane.cpp.
References LKDetectorPlane::DriftElectronBack(), and LKDetectorPlane::GetPad().
DriftElectronBack() [3/3]
void LKDetectorPlane::DriftElectronBack (LKPad * pad, double tb, TVector3 & posReco, double & driftLength) virtual inherited
Implementation recommanded. Set poseReco to global position using pad position, and time-bin tb. Pad position must be set from Init(). Conversion from time-bin (tb) to position in time-axis (post) is calculated by : post = fTbToLength * tb + fPosition [fTbToLength] is tb to position conversion factor with direction and [fPosition] is detector plane position in time-axis.
Parameters
pad[in] channel (pad)
tb[in] Time-bin
posReco[out] Reconstructed position of electron(?) before drift.
driftLength[out] Drift length of the electron from the reconstructed position.
Definition at line 689 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fAxis3, LKDetectorPlane::fAxisDrift, LKDetectorPlane::fPosition, LKDetectorPlane::fTbToLength, LKPad::GetI(), LKPad::GetJ(), LKVector3::GetXYZ(), LKVector3::SetI(), LKVector3::SetJ(), and LKVector3::SetK().
Referenced by LKDetectorPlane::DriftElectronBack().
FillDataToHist()
void LKDetectorPlane::FillDataToHist () virtual inherited
Implementation recommanded. Fill data to histograms.
Reimplemented in LKPadPlane, TTMicromegas, and TTFrontPlane.
Definition at line 136 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fChannelArray, LKDetectorPlane::fH2Plane, LKDetectorPlane::fHitDataIsSet, LKDetectorPlane::fPadDataIsSet, LKGear::fPar, LKDetectorPlane::GetHist(), LKPad::GetI(), LKPad::GetJ(), LKPad::GetLayer(), GETChannel::GetNumHits(), LKChannel::GetPadID(), LKPad::GetRow(), LKPad::GetSection(), lk_error, and lk_info.
Referenced by LKEvePlane::ClickedControlEvent1(), LKDetectorPlane::Draw(), LKEvePlane::Draw(), LKDetectorPlane::DrawHist(), LKEvePlane::DrawHist(), and LKEvePlane::UpdateFill().
FillPlane()
void LKDetectorPlane::FillPlane (double i, double j, double tb, double charge, int trackID = -1) inherited
Find pad corresponding to the position (i,j) and fill time-bin by amount of charge.
Definition at line 125 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fChannelArray, and LKDetectorPlane::FindPadID().
FindChannelID() [1/2]
virtual int LKDetectorPlane::FindChannelID (double i, double j) inline virtual inherited
Implementation recommanded. Find channel using position.
Reimplemented in LKEvePlane.
Definition at line 121 of file LKDetectorPlane.h.
Referenced by LKDetectorPlane::FindPadID(), and LKDetectorPlane::FindPadID().
FindChannelID() [2/2]
virtual int LKDetectorPlane::FindChannelID (int section, int layer, int row) inline virtual inherited
Implementation recommanded. Find channel using section, layer, row info.
Reimplemented in LKEvePlane.
Definition at line 122 of file LKDetectorPlane.h.
FindDivisionIndex() [1/2]
Int_t LHPadPlaneFan::FindDivisionIndex (Double_t r) private
Definition at line 534 of file LHPadPlaneFan.cpp.
References fNLayerDivision, and fRDivI.
FindDivisionIndex() [2/2]
Int_t LHPadPlaneFan::FindDivisionIndex (Int_t layer) private
Definition at line 524 of file LHPadPlaneFan.cpp.
References fLayerDivI, and fNLayerDivision.
Referenced by FindPadID(), GetHist(), Init(), PullOutNeighborHitsIn(), and PullOutNeighborHitsIn().
FindPadID() [1/5]
virtual int LKDetectorPlane::FindPadID (double i, double j) inline virtual inherited
Reimplemented in LTPadPlane.
Definition at line 123 of file LKDetectorPlane.h.
References LKDetectorPlane::FindChannelID().
Referenced by LKDetectorPlane::FillPlane(), LKDetectorPlane::GetPad(), LKDetectorPlane::GetPad(), LKDetectorPlane::GetPad(), LKDetectorPlane::PadMapChecker(), LKDetectorPlane::PadPositionChecker(), LKDetectorPlane::PullOutNeighborHits(), and LKDetectorPlane::PullOutNeighborHits().
FindPadID() [2/5]
Int_t LHPadPlaneFan::FindPadID (Double_t i, Double_t j) virtual
Definition at line 246 of file LHPadPlaneFan.cpp.
References fArcLength, fCosPiNo4, FindDivisionIndex(), FindSection(), fLayerDivI, fNHalfRowsInLayer, fNLayersTotal, fPadMap, fRadius, fRDivI, and fSinPiNo4.
Referenced by PullOutNeighborHitsIn().
FindPadID() [3/5]
virtual int LKDetectorPlane::FindPadID (int cobo, int asad, int aget, int chan) inline virtual inherited
Reimplemented in ATMicromegas, LTPadPlane, and LKEvePlane.
Definition at line 125 of file LKDetectorPlane.h.
FindPadID() [4/5]
virtual int LKDetectorPlane::FindPadID (int section, int layer, int row) inline virtual inherited
Reimplemented in LTPadPlane.
Definition at line 124 of file LKDetectorPlane.h.
References LKDetectorPlane::FindChannelID().
FindPadID() [5/5]
Int_t LHPadPlaneFan::FindPadID (Int_t section, Int_t row, Int_t layer) virtual
Definition at line 228 of file LHPadPlaneFan.cpp.
References fNHalfRowsInLayer, fNLayersTotal, and fPadMap.
FindSection()
Int_t LHPadPlaneFan::FindSection (Double_t i, Double_t j) private
Definition at line 501 of file LHPadPlaneFan.cpp.
References fTanPi1o8, fTanPi3o8, fTanPi5o8, and fTanPi7o8.
Referenced by FindPadID().
Get3DEventPad()
virtual TPad * LKDetectorPlane::Get3DEventPad () inline virtual inherited
If user wants to place 3D event display other than default canvas, this method should return corresponding TPad.
Reimplemented in ATMicromegas, and LKEvePlane.
Definition at line 82 of file LKDetectorPlane.h.
GetAxis1()
virtual axis_t LKDetectorPlane::GetAxis1 (int iPad = 0) const inline virtual inherited
Reimplemented in LKEvePlane.
Definition at line 60 of file LKDetectorPlane.h.
References LKDetectorPlane::fAxis1.
Referenced by LKTracklet::TrajectoryOnPlane().
GetAxis2()
virtual axis_t LKDetectorPlane::GetAxis2 (int iPad = 0) const inline virtual inherited
Reimplemented in LKEvePlane.
Definition at line 61 of file LKDetectorPlane.h.
References LKDetectorPlane::fAxis2.
Referenced by LKTracklet::TrajectoryOnPlane().
GetAxis3()
virtual axis_t LKDetectorPlane::GetAxis3 () const inline virtual inherited
Definition at line 62 of file LKDetectorPlane.h.
References LKDetectorPlane::fAxis3.
GetAxisDrift()
virtual axis_t LKDetectorPlane::GetAxisDrift () const inline virtual inherited
Definition at line 63 of file LKDetectorPlane.h.
References LKDetectorPlane::fAxisDrift.
GetCanvas()
TCanvas * LHPadPlaneFan::GetCanvas (Option_t * option = "") virtual
Implementation recommanded for event display.
Reimplemented from LKDetectorPlane.
Definition at line 472 of file LHPadPlaneFan.cpp.
References LKDetectorPlane::fCanvas, and LKDetectorPlane::fPlaneID.
GetChannel()
LKChannel * LKDetectorPlane::GetChannel (int idx) inherited
Definition at line 47 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fChannelArray.
GetChannelAnalyzer()
LKChannelAnalyzer * LKDetectorPlane::GetChannelAnalyzer (int id = 0) virtual inherited
Reimplemented in LTPadPlane, and LKEvePlane.
Definition at line 714 of file LKDetectorPlane.cpp.
References LKParameterContainer::CheckPar(), LKDetectorPlane::fChannelAnalyzer, LKGear::fPar, and LKDetectorPlane::Print().
Referenced by TTMicromegas::SelectAndDrawChannel(), and TTFrontPlane::SelectAndDrawChannel().
GetChannelArray()
TObjArray * LKDetectorPlane::GetChannelArray () inline inherited
Definition at line 118 of file LKDetectorPlane.h.
References LKDetectorPlane::fChannelArray.
GetChannelFast()
LKChannel * LKDetectorPlane::GetChannelFast (int idx) inline inherited
Definition at line 126 of file LKDetectorPlane.h.
References LKDetectorPlane::fChannelArray.
GetCPad()
virtual TPad * LKDetectorPlane::GetCPad (int iPad) inline virtual inherited
For grabbing inner pads of canvas.
Reimplemented in LKEvePlane, and TTMicromegas.
Definition at line 81 of file LKDetectorPlane.h.
References LKDetectorPlane::GetCanvas().
GetHist()
TH2 * LHPadPlaneFan::GetHist (Option_t * option = "-1") virtual
Reimplemented from LKDetectorPlane.
Definition at line 308 of file LHPadPlaneFan.cpp.
References fArcLength, LKDetectorPlane::fChannelArray, LKDetectorPlane::fH2Plane, FindDivisionIndex(), fLayerDivI, fRadius, and fRDivI.
GetInPadArray()
TObjArray * LHPadPlaneFan::GetInPadArray ()
Definition at line 551 of file LHPadPlaneFan.cpp.
References fInPadArray.
GetLayerDiv()
Int_t LHPadPlaneFan::GetLayerDiv (Int_t idx)
Definition at line 622 of file LHPadPlaneFan.cpp.
References fLayerDivI.
GetNChannels()
int LKDetectorPlane::GetNChannels () inline inherited
Definition at line 116 of file LKDetectorPlane.h.
References LKDetectorPlane::fChannelArray.
Referenced by LKDetectorPlane::GetNumPads(), and LKPadPlane::GetNumPads().
GetNLayerDivision()
Int_t LHPadPlaneFan::GetNLayerDivision ()
Definition at line 621 of file LHPadPlaneFan.cpp.
References fNLayerDivision.
GetNumCPads()
virtual int LKDetectorPlane::GetNumCPads () inline virtual inherited
Get number of inner pads of canvas.
Reimplemented in LKEvePlane, and TTMicromegas.
Definition at line 80 of file LKDetectorPlane.h.
GetNumPads()
int LKDetectorPlane::GetNumPads () inline inherited
Definition at line 117 of file LKDetectorPlane.h.
References LKDetectorPlane::GetNChannels().
GetPad() [1/4]
LKPad * LKDetectorPlane::GetPad (double i, double j) inherited
Definition at line 61 of file LKDetectorPlane.cpp.
References LKDetectorPlane::FindPadID(), and LKDetectorPlane::GetPad().
GetPad() [2/4]
LKPad * LKDetectorPlane::GetPad (int cobo, int asad, int aget, int chan) inherited
Definition at line 77 of file LKDetectorPlane.cpp.
References LKDetectorPlane::FindPadID(), and LKDetectorPlane::GetPad().
GetPad() [3/4]
LKPad * LKDetectorPlane::GetPad (int padID) inherited
Definition at line 54 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fChannelArray.
Referenced by LKDetectorPlane::DriftElectronBack(), LKDetectorPlane::GetPad(), LKDetectorPlane::GetPad(), LKDetectorPlane::GetPad(), and LTPadPlane::Init().
GetPad() [4/4]
LKPad * LKDetectorPlane::GetPad (int section, int layer, int row) inherited
Definition at line 69 of file LKDetectorPlane.cpp.
References LKDetectorPlane::FindPadID(), and LKDetectorPlane::GetPad().
GetPadArray()
TObjArray * LKDetectorPlane::GetPadArray () inherited
Definition at line 430 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fChannelArray.
GetPadFast()
LKPad * LKDetectorPlane::GetPadFast (int idx) inline inherited
Definition at line 127 of file LKDetectorPlane.h.
References LKDetectorPlane::fChannelArray.
Referenced by LKDetectorPlane::AddHit(), LKDetectorPlane::SetHitArray(), and LKDetectorPlane::SetPadArray().
GetPar()
LKParameterContainer * LKGear::GetPar () const inherited
Definition at line 33 of file LKGear.cpp.
References LKGear::fPar.
GetParameterContainer()
LKParameterContainer * LKGear::GetParameterContainer () const inherited
Definition at line 32 of file LKGear.cpp.
References LKGear::fPar.
Referenced by ClassImp(), LHElectronicsTask::Init(), and LHVertexFindingTask::Init().
GetPlaneID()
int LKDetectorPlane::GetPlaneID () const inline inherited
Definition at line 57 of file LKDetectorPlane.h.
References LKDetectorPlane::fPlaneID.
Referenced by LKDetectorPlane::SetPadArray(), and LKPadPlane::SetPadArray().
GetPosition()
double LKDetectorPlane::GetPosition () const inline inherited
Definition at line 65 of file LKDetectorPlane.h.
References LKDetectorPlane::fPosition.
Referenced by TTMicromegas::FillDataToHist(), TTFrontPlane::FillDataToHist(), LKEvePlane::FillDataToHistEventDisplay1(), ATMicromegas::FillDataToHistEventDisplay2(), ATTPCStripPad::Init(), LKDetectorPlane::PadNeighborChecker(), LKPadPlane::PadNeighborChecker(), LKDetectorPlane::PadPositionChecker(), and LKPadPlane::PadPositionChecker().
GetRank()
Int_t LKGear::GetRank () const inherited
Definition at line 36 of file LKGear.cpp.
References LKGear::fRank.
GetRDiv()
Double_t LHPadPlaneFan::GetRDiv (Int_t idx)
Definition at line 623 of file LHPadPlaneFan.cpp.
References fRDivI.
GetTbToLength()
double LKDetectorPlane::GetTbToLength () const inline inherited
Definition at line 64 of file LKDetectorPlane.h.
References LKDetectorPlane::fTbToLength.
GlobalToLocalAxis()
virtual TVector3 LKDetectorPlane::GlobalToLocalAxis (TVector3 posGlobal) inline virtual inherited
Implementation recommanded. Convert global position to local detector plane position.
Reimplemented in LKEvePlane.
Definition at line 86 of file LKDetectorPlane.h.
Referenced by LKPadPlane::DriftElectron().
GrabNeighborPads()
void LKDetectorPlane::GrabNeighborPads (vector< LKPad * > * pads, vector< LKPad * > * neighborPads) inherited
For tracking use.
Definition at line 417 of file LKDetectorPlane.cpp.
Referenced by LKDetectorPlane::PullOutNeighborHits(), LKDetectorPlane::PullOutNeighborHits(), and PullOutNeighborHitsIn().
Init()
bool LHPadPlaneFan::Init () virtual
Implementation recommanded. Init() method should implement pad information (id, position, neighbor) and add channel using AddChannel() or AddPad() method. All parameters should be configured such as axis-1,2,3, fPosition, fTbToLength from parameter container.
Reimplemented from LKDetectorPlane.
Definition at line 22 of file LHPadPlaneFan.cpp.
References AddPad(), fArcLength, LKDetectorPlane::fChannelArray, fCosPiNo4, fFuncXRightBound, FindDivisionIndex(), fInDivisionIndex, fInPadArray, fLayerDivI, fNHalfRowsInLayer, fNLayerDivision, fNLayers, fNLayersTotal, fPadMap, LKGear::fPar, fRadius, fRDivI, fRMax, fRMin, fSinPiNo4, fTanPi1o8, fTanPi3o8, fTanPi5o8, fTanPi7o8, and MapPad().
IsInBoundary() [1/2]
virtual bool LKDetectorPlane::IsInBoundary (double i, double j) inline virtual inherited
Implementation recommanded. Return if position (i,j) is inside the effective detector plane boundary.
Reimplemented in LTPadPlane, and LKEvePlane.
Definition at line 85 of file LKDetectorPlane.h.
IsInBoundary() [2/2]
bool LHPadPlaneFan::IsInBoundary (Double_t i, Double_t j) virtual
Definition at line 299 of file LHPadPlaneFan.cpp.
References fRMax.
LocalToGlobalAxis()
virtual TVector3 LKDetectorPlane::LocalToGlobalAxis (TVector3 posLocal) inline virtual inherited
Implementation recommanded. Convert local position to global detector plane position
Reimplemented in LKEvePlane.
Definition at line 87 of file LKDetectorPlane.h.
MapPad()
void LHPadPlaneFan::MapPad (LKPad * pad) private
Definition at line 492 of file LHPadPlaneFan.cpp.
References fPadMap, and LKChannel::GetPadID().
Referenced by Init().
PadDisplacement()
Double_t LHPadPlaneFan::PadDisplacement () const virtual
Return average pad displacement to each other.
Reimplemented from LKDetectorPlane.
Definition at line 286 of file LHPadPlaneFan.cpp.
References fArcLength, fNLayerDivision, and fRadius.
PadMapChecker()
bool LKDetectorPlane::PadMapChecker () inherited
Self debugging tool. Result will be printed out. For each pad, check 1) section, layer, row map 2) cobo, aget, asad, chan map
Definition at line 432 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fChannelArray, LKDetectorPlane::FindPadID(), lk_info, and lk_warning.
PadNeighborChecker()
bool LKDetectorPlane::PadNeighborChecker () inherited
Self debugging tool. Result will be printed out. For each pad, check number of registered neighbor pads.
Definition at line 539 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fChannelArray, LKPad::GetI(), LKPad::GetJ(), LKChannel::GetPadID(), LKDetectorPlane::GetPosition(), and lk_info.
PadPositionChecker()
bool LKDetectorPlane::PadPositionChecker (bool checkCorners = true) inherited
Self debugging tool. Result will be printed out. For each pad, check if pad found from FindPadID() using pad position of itself matches.
Definition at line 487 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fChannelArray, LKDetectorPlane::FindPadID(), LKPad::GetPadCorners(), LKDetectorPlane::GetPosition(), lk_info, and lk_warning.
Print()
void LKDetectorPlane::Print (Option_t * option = "") const virtual inherited
Reimplemented in ATMicromegas, LTPadPlane, LKEvePlane, LKPadPlane, TTMicromegas, and TTFrontPlane.
Definition at line 28 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fChannelArray, iChannel, and lk_info.
Referenced by LKDetectorPlane::GetChannelAnalyzer().
PullOutNeighborHits() [1/5]
void LKDetectorPlane::PullOutNeighborHits (double x, double y, int range, LKHitArray * neighborHits) inherited
For tracking use.
Definition at line 328 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fChannelArray, LKDetectorPlane::FindPadID(), and LKDetectorPlane::GrabNeighborPads().
PullOutNeighborHits() [2/5]
void LKDetectorPlane::PullOutNeighborHits (double x, double y, int range, vector< LKHit * > * neighborHits) inherited
For tracking use.
Definition at line 380 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fChannelArray, LKDetectorPlane::FindPadID(), and LKDetectorPlane::GrabNeighborPads().
PullOutNeighborHits() [3/5]
void LKDetectorPlane::PullOutNeighborHits (LKHitArray * hits, LKHitArray * neighborHits) inherited
For tracking use.
Definition at line 315 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fChannelArray.
PullOutNeighborHits() [4/5]
void LKDetectorPlane::PullOutNeighborHits (TVector2 p, int range, vector< LKHit * > * neighborHits) inherited
For tracking use.
Definition at line 375 of file LKDetectorPlane.cpp.
References LKDetectorPlane::PullOutNeighborHits().
PullOutNeighborHits() [5/5]
void LKDetectorPlane::PullOutNeighborHits (vector< LKHit * > * hits, vector< LKHit * > * neighborHits) inherited
For tracking use.
Definition at line 365 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fChannelArray.
Referenced by LKDetectorPlane::PullOutNeighborHits().
PullOutNeighborHitsIn() [1/2]
void LHPadPlaneFan::PullOutNeighborHitsIn (LKTpcHits * hits, LKTpcHits * nbHits)
Definition at line 568 of file LHPadPlaneFan.cpp.
References LKDetectorPlane::fChannelArray, FindDivisionIndex(), fInDivisionIndex, and LKPad::GetLayer().
PullOutNeighborHitsIn() [2/2]
void LHPadPlaneFan::PullOutNeighborHitsIn (TVector3 p, Int_t range, LKTpcHits * nbHits)
Definition at line 582 of file LHPadPlaneFan.cpp.
References FindDivisionIndex(), fInDivisionIndex, FindPadID(), fInPadArray, LKPad::GetLayer(), and LKDetectorPlane::GrabNeighborPads().
PullOutNextFreeHit()
LKHit * LKDetectorPlane::PullOutNextFreeHit () virtual inherited
For tracking use.
Reimplemented in LKPadPlane.
Definition at line 300 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fChannelArray, LKDetectorPlane::fFreePadIdx, and LKDetectorPlane::PullOutNextFreeHit().
Referenced by LKDetectorPlane::PullOutNextFreeHit(), and PullOutNextFreeHitIn().
PullOutNextFreeHitIn()
LKTpcHit * LHPadPlaneFan::PullOutNextFreeHitIn ()
Definition at line 553 of file LHPadPlaneFan.cpp.
References LKDetectorPlane::fChannelArray, fFreeInPadIdx, fInPadArray, LKDetectorPlane::PullOutNextFreeHit(), and PullOutNextFreeHitIn().
Referenced by PullOutNextFreeHitIn().
ResetEvent()
void LKDetectorPlane::ResetEvent () virtual inherited
For tracking use.
Reimplemented in LKPadPlane.
Definition at line 277 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fChannelArray, and LKDetectorPlane::fFreePadIdx.
ResetHitMap()
void LHPadPlaneFan::ResetHitMap () virtual
For tracking use.
Reimplemented from LKDetectorPlane.
Definition at line 544 of file LHPadPlaneFan.cpp.
References fFreeInPadIdx, and LKDetectorPlane::ResetHitMap().
SetDataFromBranch()
bool LKDetectorPlane::SetDataFromBranch () virtual inherited
Implementation recommanded. Set waveform and hit data from input tree branches to pads.
Reimplemented in LKEvePlane, LKPadPlane, TTMicromegas, and TTFrontPlane.
Definition at line 233 of file LKDetectorPlane.cpp.
References LKDetectorPlane::Clear(), LKGear::fPar, LKGear::fRun, lk_cout, lk_error, lk_info, lk_warning, LKDetectorPlane::SetHitArray(), and LKDetectorPlane::SetPadArray().
Referenced by LKDetectorPlane::Draw().
SetDetector()
void LKDetectorPlane::SetDetector (LKDetector * detector) inline inherited
Definition at line 55 of file LKDetectorPlane.h.
References LKDetectorPlane::fDetector.
SetHitArray()
void LKDetectorPlane::SetHitArray (TClonesArray * hitArray) inherited
Definition at line 102 of file LKDetectorPlane.cpp.
References LKDetectorPlane::AddHit(), LKDetectorPlane::fHitDataIsSet, and LKDetectorPlane::GetPadFast().
Referenced by LKDetectorPlane::SetDataFromBranch().
SetPadArray()
void LKDetectorPlane::SetPadArray (TClonesArray * padArray) inherited
Definition at line 85 of file LKDetectorPlane.cpp.
References LKDetectorPlane::fPadDataIsSet, LKDetectorPlane::fPlaneID, LKDetectorPlane::GetPadFast(), and LKDetectorPlane::GetPlaneID().
Referenced by LKDetectorPlane::SetDataFromBranch().
SetPar()
void LKGear::SetPar (LKParameterContainer * par) inline inherited
Definition at line 26 of file LKGear.h.
References LKGear::SetParameterContainer().
Referenced by LKDetector::AddPlane(), LKRun::Init(), LKDetector::Init(), and LKMFMConversionTask::Init().
SetParameterContainer()
void LKGear::SetParameterContainer (LKParameterContainer * par) virtual inherited
Definition at line 10 of file LKGear.cpp.
References LKGear::fPar.
Referenced by ATTPC::BuildDetectorPlane(), and LKGear::SetPar().
SetPlaneID()
void LKDetectorPlane::SetPlaneID (int id) inline inherited
Definition at line 56 of file LKDetectorPlane.h.
References LKDetectorPlane::fPlaneID.
Referenced by ATMicromegas::Init(), ATTPC20RectanglePad::Init(), ATTPCHoneyCombPad::Init(), ATTPCRectanglePad::Init(), and ATTPCStripPad::Init().
SetRank()
void LKGear::SetRank (Int_t rank) virtual inherited
Reimplemented in LKTask.
Definition at line 35 of file LKGear.cpp.
References LKGear::fRank.
Referenced by LKDetector::AddPlane(), and LKDetectorSystem::SetDetector().
SetRun()
void LKGear::SetRun (LKRun * run) inline inherited
Definition at line 36 of file LKGear.h.
References LKGear::fRun, and run.
Referenced by LKRun::Add(), LKRun::AddDetector(), LKRun::Init(), LKDetectorSystem::SetDetector(), and LKRun::SetEventTrigger().
Member Data Documentation
fArcLength
Double_t* LHPadPlaneFan::fArcLength private
Definition at line 56 of file LHPadPlaneFan.h.
Referenced by FindPadID(), GetHist(), Init(), and PadDisplacement().
fAxis1
axis_t LKDetectorPlane::fAxis1 = LKVector3::kNon protected inherited
Axis-1 lying in plane. Must be set by input parameter.
Definition at line 32 of file LKDetectorPlane.h.
Referenced by LKDetectorPlane::DriftElectron(), ATTPC20RectanglePad::FindPadID(), ATTPCHoneyCombPad::FindPadID(), ATTPCRectanglePad::FindPadID(), ATTPCStripPad::FindPadID(), LKDetectorPlane::GetAxis1(), LKEvePlane::GetAxis1(), ATTPC20RectanglePad::GetHist(), ATTPCHoneyCombPad::GetHist(), ATTPCRectanglePad::GetHist(), ATTPCStripPad::GetHist(), LTPadPlane::Init(), ATTPC20RectanglePad::Init(), ATTPCHoneyCombPad::Init(), ATTPCRectanglePad::Init(), ATTPCStripPad::Init(), and TTMicromegas::TTMicromegas().
fAxis2
axis_t LKDetectorPlane::fAxis2 = LKVector3::kNon protected inherited
Axis-2 lying in plane. Must be set by input parameter.
Definition at line 33 of file LKDetectorPlane.h.
Referenced by LKDetectorPlane::DriftElectron(), ATTPC20RectanglePad::FindPadID(), ATTPCHoneyCombPad::FindPadID(), ATTPCRectanglePad::FindPadID(), ATTPCStripPad::FindPadID(), LKDetectorPlane::GetAxis2(), LKEvePlane::GetAxis2(), ATTPC20RectanglePad::GetHist(), ATTPCHoneyCombPad::GetHist(), ATTPCRectanglePad::GetHist(), ATTPCStripPad::GetHist(), LTPadPlane::Init(), ATTPC20RectanglePad::Init(), ATTPCHoneyCombPad::Init(), ATTPCRectanglePad::Init(), ATTPCStripPad::Init(), and TTMicromegas::TTMicromegas().
fAxis3
axis_t LKDetectorPlane::fAxis3 = LKVector3::kNon protected inherited
Axis-3 = Axis-1 x Axis-2 perpendicular to plane.
Definition at line 34 of file LKDetectorPlane.h.
Referenced by LKDetectorPlane::DriftElectron(), LKEvePlane::DriftElectronBack(), LKDetectorPlane::DriftElectronBack(), LKDetectorPlane::GetAxis3(), and LTPadPlane::Init().
fAxisDrift
axis_t LKDetectorPlane::fAxisDrift = LKVector3::kNon protected inherited
Axis perpendicular to plane, in electron drifting direction. Must be set by input parameter.
Definition at line 35 of file LKDetectorPlane.h.
Referenced by LKEvePlane::DriftElectronBack(), LKDetectorPlane::DriftElectronBack(), LKEvePlane::FillDataToHistEventDisplay1(), ATMicromegas::FillDataToHistEventDisplay2(), LKDetectorPlane::GetAxisDrift(), and LTPadPlane::Init().
fCanvas
TCanvas* LKDetectorPlane::fCanvas = nullptr protected inherited
Definition at line 40 of file LKDetectorPlane.h.
Referenced by LKEvePlane::ClickedControlEvent2(), LKPadPlane::DrawHist(), LKDetectorPlane::DrawHist(), LKDetectorPlane::GetCanvas(), LKEvePlane::GetCanvas(), TTMicromegas::GetCanvas(), ATTPC20RectanglePad::GetCanvas(), ATTPCHoneyCombPad::GetCanvas(), ATTPCRectanglePad::GetCanvas(), ATTPCStripPad::GetCanvas(), TTFrontPlane::GetCanvas(), GetCanvas(), LHPadPlaneRCut::GetCanvas(), LHPadPlaneYCut::GetCanvas(), TTMicromegas::GetCPad(), TTMicromegas::SelectAndDrawChannel(), and TTFrontPlane::SelectAndDrawChannel().
fChannelAnalyzer
LKChannelAnalyzer* LKDetectorPlane::fChannelAnalyzer = nullptr protected inherited
Definition at line 29 of file LKDetectorPlane.h.
Referenced by LTPadPlane::GetChannelAnalyzer(), LKDetectorPlane::GetChannelAnalyzer(), LKEvePlane::GetChannelAnalyzer(), LTPadPlane::Init(), and LKEvePlane::UpdateChannelBuffer().
fChannelArray
TObjArray* LKDetectorPlane::fChannelArray = nullptr protected inherited
Definition at line 39 of file LKDetectorPlane.h.
Referenced by LKDetectorPlane::AddChannel(), AddPad(), LKDetectorPlane::AddPad(), LKDetectorPlane::Clear(), LKPadPlane::Clear(), LKEvePlane::ClickedControlEvent2(), LTPadPlane::ClickedEventDisplay1(), LKEvePlane::ClickedEventDisplay1(), LKEvePlane::ClickedEventDisplay2(), LKEvePlane::DriftElectronBack(), LKPadPlane::FillBufferIn(), LKDetectorPlane::FillDataToHist(), LKPadPlane::FillDataToHist(), LTPadPlane::FillDataToHist(), LKEvePlane::FillDataToHistEventDisplay1(), ATMicromegas::FillDataToHistEventDisplay2(), LKDetectorPlane::FillPlane(), ATMicromegas::FindPad(), LKEvePlane::FindPad(), LKDetectorPlane::GetChannel(), LKDetectorPlane::GetChannelArray(), LKDetectorPlane::GetChannelFast(), ATTPC20RectanglePad::GetHist(), ATTPCHoneyCombPad::GetHist(), ATTPCRectanglePad::GetHist(), ATTPCStripPad::GetHist(), GetHist(), LHPadPlaneRCut::GetHist(), LHPadPlaneYCut::GetHist(), LTPadPlane::GetHistEventDisplay2(), LKDetectorPlane::GetNChannels(), LKDetectorPlane::GetPad(), LKPadPlane::GetPad(), LKDetectorPlane::GetPadArray(), LKPadPlane::GetPadArray(), LKDetectorPlane::GetPadFast(), LKPadPlane::GetPadFast(), ATMicromegas::Init(), LTPadPlane::Init(), Init(), LHPadPlaneRCut::Init(), LHPadPlaneYCut::Init(), ATTPC20RectanglePad::Init(), ATTPCHoneyCombPad::Init(), ATTPCRectanglePad::Init(), ATTPCStripPad::Init(), LHPadPlaneRCut::NewPad(), LHPadPlaneYCut::NewPad(), LKDetectorPlane::PadMapChecker(), LKDetectorPlane::PadNeighborChecker(), LKPadPlane::PadNeighborChecker(), LKDetectorPlane::PadPositionChecker(), LKPadPlane::PadPositionChecker(), LKDetectorPlane::Print(), LKPadPlane::Print(), LKDetectorPlane::PullOutNeighborHits(), LKDetectorPlane::PullOutNeighborHits(), LKPadPlane::PullOutNeighborHits(), LKPadPlane::PullOutNeighborHits(), LKDetectorPlane::PullOutNeighborHits(), LKPadPlane::PullOutNeighborHits(), LKDetectorPlane::PullOutNeighborHits(), LKPadPlane::PullOutNeighborHits(), PullOutNeighborHitsIn(), LKDetectorPlane::PullOutNextFreeHit(), LKPadPlane::PullOutNextFreeHit(), PullOutNextFreeHitIn(), LKDetectorPlane::ResetEvent(), LKPadPlane::ResetEvent(), LKDetectorPlane::ResetHitMap(), LKPadPlane::ResetHitMap(), LKEvePlane::SetDataFromBranch(), ATMicromegas::UpdateChannelBuffer(), and LKEvePlane::UpdateChannelBuffer().
fCosPiNo4
Double_t LHPadPlaneFan::fCosPiNo4[8] private
Definition at line 64 of file LHPadPlaneFan.h.
Referenced by FindPadID(), and Init().
fCvsChannelBuffer
TCanvas* LKDetectorPlane::fCvsChannelBuffer = nullptr protected inherited
Definition at line 42 of file LKDetectorPlane.h.
fDetector
LKDetector* LKDetectorPlane::fDetector = nullptr protected inherited
Definition at line 28 of file LKDetectorPlane.h.
Referenced by TTMicromegas::SelectAndDrawChannel(), TTFrontPlane::SelectAndDrawChannel(), and LKDetectorPlane::SetDetector().
fFreeInPadIdx
Int_t LHPadPlaneFan::fFreeInPadIdx = 0 private
Definition at line 78 of file LHPadPlaneFan.h.
Referenced by PullOutNextFreeHitIn(), and ResetHitMap().
fFreePadIdx
int LKDetectorPlane::fFreePadIdx = 0 protected inherited
Definition at line 45 of file LKDetectorPlane.h.
Referenced by LKDetectorPlane::PullOutNextFreeHit(), LKDetectorPlane::ResetEvent(), and LKDetectorPlane::ResetHitMap().
fFuncXRightBound
TF1* LHPadPlaneFan::fFuncXRightBound = nullptr private
Definition at line 49 of file LHPadPlaneFan.h.
Referenced by Init().
fGraphChannelBoundary
TGraph* LKDetectorPlane::fGraphChannelBoundary = nullptr protected inherited
Definition at line 43 of file LKDetectorPlane.h.
fGraphChannelBoundaryNb
TGraph* LKDetectorPlane::fGraphChannelBoundaryNb[20] = {0} protected inherited
Definition at line 44 of file LKDetectorPlane.h.
fH2Plane
TH2* LKDetectorPlane::fH2Plane = nullptr protected inherited
Definition at line 41 of file LKDetectorPlane.h.
Referenced by LKDetectorPlane::FillDataToHist(), LKPadPlane::FillDataToHist(), ATTPC20RectanglePad::GetHist(), ATTPCHoneyCombPad::GetHist(), ATTPCRectanglePad::GetHist(), ATTPCStripPad::GetHist(), GetHist(), LHPadPlaneRCut::GetHist(), and LHPadPlaneYCut::GetHist().
fHitDataIsSet
bool LKDetectorPlane::fHitDataIsSet = false protected inherited
Definition at line 48 of file LKDetectorPlane.h.
Referenced by LKDetectorPlane::FillDataToHist(), and LKDetectorPlane::SetHitArray().
fInDivisionIndex
Int_t LHPadPlaneFan::fInDivisionIndex = 0 private
Definition at line 75 of file LHPadPlaneFan.h.
Referenced by Init(), PullOutNeighborHitsIn(), and PullOutNeighborHitsIn().
fInPadArray
TObjArray* LHPadPlaneFan::fInPadArray = nullptr private
Definition at line 76 of file LHPadPlaneFan.h.
Referenced by AddPad(), GetInPadArray(), Init(), PullOutNeighborHitsIn(), and PullOutNextFreeHitIn().
fLayerDivI
std::vector<Int_t> LHPadPlaneFan::fLayerDivI private
Definition at line 70 of file LHPadPlaneFan.h.
Referenced by FindDivisionIndex(), FindPadID(), GetHist(), GetLayerDiv(), and Init().
fNHalfRowsInLayer
std::vector<Int_t> LHPadPlaneFan::fNHalfRowsInLayer private
Definition at line 67 of file LHPadPlaneFan.h.
Referenced by FindPadID(), FindPadID(), and Init().
fNLayerDivision
Int_t LHPadPlaneFan::fNLayerDivision = 0 private
Definition at line 54 of file LHPadPlaneFan.h.
Referenced by DrawFrame(), FindDivisionIndex(), FindDivisionIndex(), GetNLayerDivision(), Init(), and PadDisplacement().
fNLayers
Int_t* LHPadPlaneFan::fNLayers private
Definition at line 58 of file LHPadPlaneFan.h.
Referenced by Init().
fNLayersTotal
Int_t LHPadPlaneFan::fNLayersTotal = 0 private
Definition at line 68 of file LHPadPlaneFan.h.
Referenced by FindPadID(), FindPadID(), and Init().
fPadDataIsSet
bool LKDetectorPlane::fPadDataIsSet = false protected inherited
Definition at line 47 of file LKDetectorPlane.h.
Referenced by LKDetectorPlane::FillDataToHist(), and LKDetectorPlane::SetPadArray().
fPadMap
std::map<std::vector<Int_t>, Int_t> LHPadPlaneFan::fPadMap private
Definition at line 73 of file LHPadPlaneFan.h.
Referenced by FindPadID(), FindPadID(), Init(), and MapPad().
fPar
LKParameterContainer* LKGear::fPar = nullptr protected inherited
Definition at line 39 of file LKGear.h.
Referenced by LKTask::Add(), LKRun::AddDetector(), LKGear::AddParameterContainer(), LKGear::AddParameterContainer(), LKDetector::AddPlane(), LHTpc::BuildDetectorPlane(), ATTPC::BuildDetectorPlane(), LHTpc::BuildGeometry(), ATTPC::BuildGeometry(), ClassImp(), ClassImp(), ClassImp(), ClassImp(), LKEveTask::DrawEve3D(), LKPadPlane::DrawHist(), LKG4RunManager::EndOfRun(), LKPulseExtractionTask::EndOfRun(), LKDetectorPlane::FillDataToHist(), LKPadPlane::FillDataToHist(), LTPadPlane::GetChannelAnalyzer(), LKDetector::GetChannelAnalyzer(), LKDetectorPlane::GetChannelAnalyzer(), LKEvePlane::GetChannelAnalyzer(), LKGear::GetPar(), LKGear::GetParameterContainer(), ATMicromegas::Init(), AToMX::Init(), LTPadPlane::Init(), LKRun::Init(), LKDetector::Init(), LKEvePlane::Init(), LKMFMConversionTask::Init(), LKDriftElectronTask::Init(), LKEveTask::Init(), LKGETChannelViewer::Init(), LKNoiseSubtractionTask::Init(), LKPulseExtractionTask::Init(), LHPSATask::Init(), TexAT2::Init(), TTMicromegas::Init(), TTHTBeamTrackingTask::Init(), TTHTTrackingTask::Init(), TTPulseExtractionTask::Init(), Init(), LHPadPlaneRCut::Init(), LHPadPlaneYCut::Init(), ATTPC::Init(), ATTPC20RectanglePad::Init(), ATTPCHoneyCombPad::Init(), ATTPCRectanglePad::Init(), ATTPCStripPad::Init(), TTFrontPlane::Init(), LKRun::InitAndCollectParameters(), TexAT2::InitChannelAnalyzer(), LKG4RunManager::Initialize(), LKRun::Print(), LKRun::RegisterBranchA(), LKG4RunManager::Run(), LKDetectorPlane::SetDataFromBranch(), LKPadPlane::SetDataFromBranch(), LKDetectorSystem::SetDetectorPar(), LKEveTask::SetEveLineAtt(), LKEveTask::SetEveMarkerAtt(), LKRun::SetEventTrigger(), LKEveTask::SetGraphAtt(), LKEveTask::SetGraphAtt(), LKG4RunManager::SetOutputFile(), LKGear::SetParameterContainer(), TTMicromegas::WriteCurrentChannel(), and LKRun::WriteOutputFile().
fPlaneID
int LKDetectorPlane::fPlaneID = -1 protected inherited
Detector plane id.
Definition at line 31 of file LKDetectorPlane.h.
Referenced by LKDetectorPlane::GetCanvas(), ATTPC20RectanglePad::GetCanvas(), ATTPCHoneyCombPad::GetCanvas(), ATTPCRectanglePad::GetCanvas(), ATTPCStripPad::GetCanvas(), GetCanvas(), LHPadPlaneRCut::GetCanvas(), LHPadPlaneYCut::GetCanvas(), LKDetectorPlane::GetPlaneID(), ATTPC20RectanglePad::Init(), ATTPCHoneyCombPad::Init(), ATTPCRectanglePad::Init(), ATTPCStripPad::Init(), LKDetectorPlane::SetPadArray(), LKPadPlane::SetPadArray(), and LKDetectorPlane::SetPlaneID().
fPosition
double LKDetectorPlane::fPosition protected inherited
Global position of pad plane center.
Definition at line 37 of file LKDetectorPlane.h.
Referenced by LKDetectorPlane::DriftElectron(), LKDetectorPlane::DriftElectronBack(), LKEvePlane::DriftElectronBack(), LKDetectorPlane::DriftElectronBack(), LKDetectorPlane::GetPosition(), ATMicromegas::Init(), LTPadPlane::Init(), and LKEvePlane::Init().
fRadius
Double_t* LHPadPlaneFan::fRadius private
Definition at line 57 of file LHPadPlaneFan.h.
Referenced by FindPadID(), GetHist(), Init(), and PadDisplacement().
fRank
Int_t LKGear::fRank = 0 protected inherited
Definition at line 41 of file LKGear.h.
Referenced by LKTask::Add(), LKDetector::AddPlane(), LKGear::GetRank(), LKDetectorSystem::SetDetector(), LKRun::SetEventTrigger(), LKGear::SetRank(), and LKTask::SetRank().
fRDivI
std::vector<Double_t> LHPadPlaneFan::fRDivI private
Definition at line 71 of file LHPadPlaneFan.h.
Referenced by DrawFrame(), FindDivisionIndex(), FindPadID(), GetHist(), GetRDiv(), and Init().
fRMax
Double_t LHPadPlaneFan::fRMax = 0 private
Definition at line 52 of file LHPadPlaneFan.h.
Referenced by DrawFrame(), Init(), and IsInBoundary().
fRMin
Double_t LHPadPlaneFan::fRMin = 0 private
Definition at line 51 of file LHPadPlaneFan.h.
Referenced by DrawFrame(), and Init().
fRun
LKRun* LKGear::fRun = nullptr protected inherited
Definition at line 40 of file LKGear.h.
Referenced by LKDetector::AddPlane(), ClassImp(), ClassImp(), ClassImp(), LKEvePlane::ClickedControlEvent1(), LKEvePlane::ClickedControlEvent1(), LKEvePlane::ClickedControlEvent2(), LKEveTask::DrawDetectorPlanes(), LKEveTask::DrawEve3D(), LKPulseExtractionTask::EndOfRun(), TTPulseExtractionTask::EndOfRun(), LKGETChannelViewer::Exec(), LKPulseExtractionTask::Exec(), TTHitFindingHoughTask::Exec(), TTPulseExtractionTask::Exec(), TTMicromegas::FillDataToHist(), LTPadPlane::FillDataToHist(), LKEvePlane::FillDataToHistEventDisplay1(), LKEvePlane::GetHistControlEvent1(), LTPadPlane::Init(), LTEventPreviewTask::Init(), TTPulseAnalysisTask::Init(), LKEvePlane::Init(), LKMFMConversionTask::Init(), LKDriftElectronTask::Init(), LKEveTask::Init(), LKGETChannelViewer::Init(), LKNoiseSubtractionTask::Init(), LKPulseExtractionTask::Init(), LKPulseShapeAnalysisTask::Init(), TTBeamSelectionTask::Init(), TTDrawBeamEnergyTask::Init(), TTDrawRawWaveformTask::Init(), TTEventSelectionTask::Init(), TTFindBeamTimingTask::Init(), TTGetPedestalTask::Init(), TTPID_FSivsFCsI::Init(), TTPID_MMvsFSi::Init(), TTPID_MMvsX6::Init(), TTPID_X6vsCsI::Init(), TTReadEventListTask::Init(), TTHTtBeamTrackingTask::Init(), TTEventNumberSelectionTask::Init(), TTEventPreviewTask::Init(), TTHitFindingHoughTask::Init(), TTHTBeamTrackingTask::Init(), TTHTTrackingTask::Init(), TTPulseExtractionTask::Init(), httask::Init(), LKMFMConversionTask::Run(), LKGETChannelViewer::SelectMenu(), LKDetectorPlane::SetDataFromBranch(), LKPadPlane::SetDataFromBranch(), TTMicromegas::SetDataFromBranch(), TTFrontPlane::SetDataFromBranch(), LKDetectorSystem::SetDetector(), LKEvePlane::SetPalette(), LKGear::SetRun(), LKDetector::SetRun(), LKMFMConversionTask::SignalNextEvent(), LKEvePlane::UpdateControlEvent1(), and LKEvePlane::UpdateControlEvent2().
fSinPiNo4
Double_t LHPadPlaneFan::fSinPiNo4[8] private
Definition at line 65 of file LHPadPlaneFan.h.
Referenced by FindPadID(), and Init().
fTanPi1o8
Double_t LHPadPlaneFan::fTanPi1o8 private
Definition at line 60 of file LHPadPlaneFan.h.
Referenced by FindSection(), and Init().
fTanPi3o8
Double_t LHPadPlaneFan::fTanPi3o8 private
Definition at line 61 of file LHPadPlaneFan.h.
Referenced by FindSection(), and Init().
fTanPi5o8
Double_t LHPadPlaneFan::fTanPi5o8 private
Definition at line 62 of file LHPadPlaneFan.h.
Referenced by FindSection(), and Init().
fTanPi7o8
Double_t LHPadPlaneFan::fTanPi7o8 private
Definition at line 63 of file LHPadPlaneFan.h.
Referenced by FindSection(), and Init().
fTbToLength
double LKDetectorPlane::fTbToLength = 1 protected inherited
time-bin (tb) to position conversion factor. Must be set by input parameter.
Definition at line 36 of file LKDetectorPlane.h.
Referenced by LKDetectorPlane::DriftElectronBack(), LKEvePlane::DriftElectronBack(), LKDetectorPlane::DriftElectronBack(), LKDetectorPlane::GetTbToLength(), ATMicromegas::Init(), LTPadPlane::Init(), and LKEvePlane::Init().
The documentation for this class was generated from the following files:
LHPadPlaneFan.h
LHPadPlaneFan.cpp