lilak: GETChannel Class Reference
GETChannel Class Reference
#include <GETChannel.h>
Public Member Functions
void AddHit (LKHit *hit)
double CalculateGroupFluctuation (int numGroups=8, int tb2=512)
virtual void Clear (Option_t *option="")
void ClearHits ()
virtual void Copy (TObject &object) const
virtual void Draw (Option_t *option="")
void FillGraph (TGraph *graph)
void FillHist (TH1 *hist)
LKBufferI GetBuffer ()
int * GetBufferArray ()
GETChannel ()
void GetGroupMeanStdDev (int numGroups, int tb2, double *pedestalGroup, double *stddevGroup)
TH1D * GetHist (TString name="")
LKHit * GetHit (int idx)
LKHitArray * GetHitArray ()
TGraph * GetHitGraph ()
int GetNumHits () const
double GetScale (double *buffer)
double GetScale (int *buffer)
int * GetWaveformY ()
virtual void Print (Option_t *option="") const
void PullOutHits (LKHitArray *hits)
void PullOutHits (vector< LKHit * > *hits)
LKHit * PullOutNextFreeHit ()
void SetBuffer (LKBufferI buffer)
void SetWaveformY (const int *array)
void SetWaveformY (const unsigned int *array)
void SetWaveformY (std::vector< unsigned int > array)
void SubtractArray (double *buffer)
void SubtractArray (double *buffer, double scale)
void SubtractArray (int *buffer)
void SubtractArray (int *buffer, double scale)
virtual ~GETChannel ()
Public Member Functions inherited from LKChannel
virtual void Clear (Option_t *option="")
virtual void Copy (TObject &obj) const
int GetChannelID () const
double GetEnergy () const
double GetNoiseScale () const
int GetPadID () const
double GetPedestal () const
double GetTime () const
LKChannel ()
virtual void Print (Option_t *option="") const
void SetChannelID (int value)
void SetEnergy (double value)
void SetNoiseScale (double value)
void SetPadID (int value)
void SetPedestal (double value)
void SetTime (double value)
virtual ~LKChannel ()
Public Member Functions inherited from LKContainer
virtual void Clear (Option_t *option="")
virtual void Copy (TObject &object) const
virtual bool DrawByDefault ()
return true if to be displayed on eve.
LKContainer ()
virtual ~LKContainer ()
Public Member Functions inherited from GETParameters
virtual void ClearParameters ()
int GetAget () const
int GetAsad () const
int GetCAAC () const
int GetChan () const
int GetCobo () const
int GetDecayNo () const
int GetDetType () const
int GetFrameNo () const
GETParameters ()
virtual void PrintParameters (TString option="") const
void SetAget (int aget)
void SetAsad (int asad)
void SetChan (int chan)
void SetCobo (int cobo)
void SetDecayNo (int id)
void SetDetType (int id)
void SetFrameNo (int id)
virtual ~GETParameters ()
Protected Member Functions
ClassDef (GETChannel, 4)
Protected Attributes
LKBufferI fBufferRawSig
TGraph * fGraphHit
LKHitArray fHitArray
Protected Attributes inherited from LKChannel
int fChannelID = -1
double fEnergy = -1
double fNoiseScale = -1
int fPadID = -1
double fPedestal = -1
double fTime = -1
Protected Attributes inherited from GETParameters
int fAget = -1
int fAsad = -1
int fChan = -1
int fCobo = -1
int fDecayNo = -1
int fDetType = -1
int fFrameNo = -1
Detailed Description
Raw event data from GET
Definition at line 22 of file GETChannel.h.
Constructor & Destructor Documentation
GETChannel()
GETChannel::GETChannel ()
Definition at line 5 of file GETChannel.cpp.
References Clear().
~GETChannel()
virtual GETChannel::~GETChannel () inline virtual
Definition at line 26 of file GETChannel.h.
Member Function Documentation
AddHit()
void GETChannel::AddHit (LKHit * hit) inline
Definition at line 52 of file GETChannel.h.
References LKHitArray::AddHit(), and fHitArray.
Referenced by PullOutHits().
CalculateGroupFluctuation()
double GETChannel::CalculateGroupFluctuation (int numGroups = 8, int tb2 = 512) inline
Definition at line 68 of file GETChannel.h.
References LKBufferI::CalculateGroupFluctuation(), and fBufferRawSig.
ClassDef()
GETChannel::ClassDef (GETChannel , 4) protected
Clear()
void GETChannel::Clear (Option_t * option = "") virtual
Reimplemented from LKChannel.
Reimplemented in LKPad.
Definition at line 10 of file GETChannel.cpp.
References LKBufferI::Clear(), LKChannel::Clear(), LKHitArray::Clear(), GETParameters::ClearParameters(), fBufferRawSig, and fHitArray.
Referenced by ClassImp(), and GETChannel().
ClearHits()
void GETChannel::ClearHits () inline
Definition at line 55 of file GETChannel.h.
References LKHitArray::Clear(), and fHitArray.
Copy()
void GETChannel::Copy (TObject & object) const virtual
Reimplemented from LKChannel.
Definition at line 18 of file GETChannel.cpp.
References LKChannel::Copy(), GETParameters::fAget, GETParameters::fAsad, fBufferRawSig, GETParameters::fChan, GETParameters::fCobo, and GETParameters::fDetType.
Draw()
void GETChannel::Draw (Option_t * option = "") virtual
Reimplemented in LKPad.
Definition at line 40 of file GETChannel.cpp.
References Draw(), GetHist(), and GetHitGraph().
Referenced by Draw().
FillGraph()
void GETChannel::FillGraph (TGraph * graph)
Definition at line 62 of file GETChannel.cpp.
References fBufferRawSig, and LKBufferI::FillGraph().
FillHist()
void GETChannel::FillHist (TH1 * hist)
Definition at line 55 of file GETChannel.cpp.
References GETParameters::fAget, GETParameters::fAsad, fBufferRawSig, GETParameters::fChan, GETParameters::fCobo, and LKBufferI::FillHist().
GetBuffer()
LKBufferI GETChannel::GetBuffer () inline
Definition at line 43 of file GETChannel.h.
References fBufferRawSig.
GetBufferArray()
int * GETChannel::GetBufferArray () inline
Definition at line 42 of file GETChannel.h.
References fBufferRawSig, and LKBufferI::GetArray().
GetGroupMeanStdDev()
void GETChannel::GetGroupMeanStdDev (int numGroups, int tb2, double * pedestalGroup, double * stddevGroup) inline
Definition at line 69 of file GETChannel.h.
References fBufferRawSig, and LKBufferI::GetGroupMeanStdDev().
GetHist()
TH1D * GETChannel::GetHist (TString name = "")
Definition at line 46 of file GETChannel.cpp.
References GETParameters::fAget, GETParameters::fAsad, fBufferRawSig, GETParameters::fChan, GETParameters::fCobo, GETParameters::GetCAAC(), and LKBufferI::GetHist().
Referenced by Draw().
GetHit()
LKHit * GETChannel::GetHit (int idx) inline
Definition at line 54 of file GETChannel.h.
References fHitArray, and LKHitArray::GetHit().
GetHitArray()
LKHitArray * GETChannel::GetHitArray () inline
Definition at line 51 of file GETChannel.h.
References fHitArray.
GetHitGraph()
TGraph * GETChannel::GetHitGraph ()
Definition at line 68 of file GETChannel.cpp.
References LKChannel::fEnergy, fGraphHit, LKChannel::fPedestal, LKChannel::fTime, and SetPoint().
Referenced by Draw().
GetNumHits()
int GETChannel::GetNumHits () const inline
Definition at line 53 of file GETChannel.h.
References fHitArray, and LKHitArray::GetNumHits().
Referenced by LKDetectorPlane::FillDataToHist(), LKPadPlane::FillDataToHist(), LTPadPlane::FillDataToHist(), and LKEvePlane::FillDataToHistEventDisplay1().
GetScale() [1/2]
double GETChannel::GetScale (double * buffer) inline
Definition at line 67 of file GETChannel.h.
References fBufferRawSig, and LKBufferI::GetScale().
GetScale() [2/2]
double GETChannel::GetScale (int * buffer) inline
Definition at line 66 of file GETChannel.h.
References fBufferRawSig, and LKBufferI::GetScale().
GetWaveformY()
int * GETChannel::GetWaveformY () inline
Definition at line 41 of file GETChannel.h.
References fBufferRawSig, and LKBufferI::GetArray().
Print()
void GETChannel::Print (Option_t * option = "") const virtual
Reimplemented from LKChannel.
Reimplemented in LKPad.
Definition at line 30 of file GETChannel.cpp.
References e_info, fBufferRawSig, fHitArray, LKHitArray::Print(), LKBufferI::Print(), LKChannel::Print(), and GETParameters::PrintParameters().
Referenced by LKPad::Print().
PullOutHits() [1/2]
void GETChannel::PullOutHits (LKHitArray * hits)
Definition at line 99 of file GETChannel.cpp.
References AddHit(), LKHitArray::Clear(), fHitArray, LKHitArray::GetHit(), and LKHitArray::GetNumHits().
PullOutHits() [2/2]
void GETChannel::PullOutHits (vector< LKHit * > * hits)
Definition at line 111 of file GETChannel.cpp.
References LKHitArray::Clear(), fHitArray, LKHitArray::GetHit(), and LKHitArray::GetNumHits().
PullOutNextFreeHit()
LKHit * GETChannel::PullOutNextFreeHit ()
Definition at line 82 of file GETChannel.cpp.
References fHitArray, LKHitArray::GetHit(), LKHitArray::GetNumHits(), and LKHitArray::RemoveHit().
SetBuffer()
void GETChannel::SetBuffer (LKBufferI buffer) inline
Definition at line 48 of file GETChannel.h.
References fBufferRawSig, and LKBufferI::SetBuffer().
SetWaveformY() [1/3]
void GETChannel::SetWaveformY (const int * array) inline
Definition at line 45 of file GETChannel.h.
References fBufferRawSig, and LKBufferI::SetArray().
SetWaveformY() [2/3]
void GETChannel::SetWaveformY (const unsigned int * array) inline
Definition at line 46 of file GETChannel.h.
References fBufferRawSig, and LKBufferI::SetArray().
SetWaveformY() [3/3]
void GETChannel::SetWaveformY (std::vector< unsigned int > array) inline
Definition at line 47 of file GETChannel.h.
References fBufferRawSig, and LKBufferI::SetArray().
SubtractArray() [1/4]
void GETChannel::SubtractArray (double * buffer) inline
Definition at line 62 of file GETChannel.h.
References fBufferRawSig, and LKBufferI::SubtractArray().
SubtractArray() [2/4]
void GETChannel::SubtractArray (double * buffer, double scale) inline
Definition at line 64 of file GETChannel.h.
References fBufferRawSig, and LKBufferI::SubtractArray().
SubtractArray() [3/4]
void GETChannel::SubtractArray (int * buffer) inline
Definition at line 61 of file GETChannel.h.
References fBufferRawSig, and LKBufferI::SubtractArray().
SubtractArray() [4/4]
void GETChannel::SubtractArray (int * buffer, double scale) inline
Definition at line 63 of file GETChannel.h.
References fBufferRawSig, and LKBufferI::SubtractArray().
Member Data Documentation
fBufferRawSig
LKBufferI GETChannel::fBufferRawSig protected
Definition at line 72 of file GETChannel.h.
Referenced by CalculateGroupFluctuation(), Clear(), Copy(), LKPad::FillBufferRawSig(), FillGraph(), FillHist(), LKPad::GetArrayRawSig(), GetBuffer(), GetBufferArray(), LKPad::GetBufferRawSig(), GetGroupMeanStdDev(), GetHist(), GetScale(), GetScale(), GetWaveformY(), Print(), SetBuffer(), LKPad::SetBufferRawSig(), LKPad::SetBufferRawSig(), LKPad::SetHist(), SetWaveformY(), SetWaveformY(), SetWaveformY(), SubtractArray(), SubtractArray(), SubtractArray(), and SubtractArray().
fGraphHit
TGraph* GETChannel::fGraphHit protected
Definition at line 75 of file GETChannel.h.
Referenced by GetHitGraph().
fHitArray
LKHitArray GETChannel::fHitArray protected
Definition at line 74 of file GETChannel.h.
Referenced by AddHit(), Clear(), ClearHits(), GetHit(), GetHitArray(), GetNumHits(), Print(), PullOutHits(), PullOutHits(), and PullOutNextFreeHit().
The documentation for this class was generated from the following files:
GETChannel.h
GETChannel.cpp