LILAK: LKTpcHit Class Reference
LKTpcHit Class Reference
#include <LKTpcHit.h>
Public Member Functions
void AddHit (LKHit *hit)
void AddTpcHit (LKTpcHit *hit)
virtual void Clear (Option_t *option="")
virtual void Copy (TObject &object) const
void CopyFrom (LKTpcHit const *hit)
Int_t GetLayer () const
Int_t GetPadID () const
virtual TF1 * GetPulseFunction (Option_t *option="")
Int_t GetRow () const
Int_t GetSection () const
Double_t GetTb () const
LKTpcHit ()
virtual void Print (Option_t *option="at") const
virtual void PrintTpcHit () const
void SetLayer (Int_t layer)
void SetPadID (Int_t id)
void SetRow (Int_t row)
void SetSection (Int_t section)
void SetSortByLayer (bool sortEarlierIfSmaller)
void SetTb (Double_t tb)
virtual ~LKTpcHit ()
Public Member Functions inherited from LKHit
virtual void AddHit (LKHit *hit)
void AddTrackCand (Int_t id)
virtual void Clear (Option_t *option="")
virtual Int_t Compare (const TObject *obj) const
virtual void Copy (TObject &object) const
void CopyFrom (LKHit *hit)
Double_t GetAlpha () const
Double_t GetCharge () const
TVector3 GetCoSquaredMean () const
TVector3 GetCovariance () const
TVector3 GetDPosition () const
Double_t GetDX () const
Double_t GetDY () const
Double_t GetDZ () const
LKHitArray * GetHitArray ()
Int_t GetHitID () const
TVector3 GetMean () const
Int_t GetNumHits () const
Int_t GetNumTrackCands ()
Double_t GetSortValue () const
TVector3 GetSquaredMean () const
TVector3 GetStdDev () const
vector< Int_t > * GetTrackCandArray ()
Int_t GetTrackID () const
TVector3 GetVariance () const
Double_t GetX () const
Double_t GetY () const
Double_t GetZ () const
virtual Bool_t IsSortable () const
LKHit ()
LKHit (Double_t x, Double_t y, Double_t z, Double_t q)
virtual void Print (Option_t *option="at") const
virtual void RemoveHit (LKHit *hit)
void RemoveTrackCand (Int_t trackID)
void SetAlpha (Double_t a)
void SetCharge (Double_t charge)
void SetDPosition (TVector3 dpos)
void SetDX (Double_t dx)
void SetDY (Double_t dy)
void SetDZ (Double_t dz)
void SetHitID (Int_t id)
void SetSortByCharge (bool sortEarlierIfSmaller)
void SetSortByDistanceTo (TVector3 point, bool sortEarlierIfCloser)
void SetSortByX (bool sortEarlierIfSmaller)
void SetSortByY (bool sortEarlierIfSmaller)
void SetSortByZ (bool sortEarlierIfSmaller)
void SetSortValue (Double_t val)
void SetTrackID (Int_t id)
void SetX (Double_t x)
void SetY (Double_t y)
void SetZ (Double_t z)
virtual ~LKHit ()
Public Member Functions inherited from LKWPoint
virtual void Clear (Option_t *option="")
virtual void Copy (TObject &object) const
TVector3 GetPosition () const
LKVector3 GetPosition (LKVector3::Axis ref) const
LKWPoint ()
LKWPoint (Double_t x, Double_t y, Double_t z, Double_t w=1)
Double_t & operator[] (int i)
Double_t operator[] (int i) const
virtual void Print (Option_t *option="") const
void Set (Double_t x, Double_t y, Double_t z, Double_t w=1)
void SetPosition (Double_t x, Double_t y, Double_t z)
void SetPosition (TVector3 pos)
void SetW (Double_t w)
Double_t w () const
Double_t W () const
Double_t x () const
Double_t X () const
Double_t y () const
Double_t Y () const
Double_t z () const
Double_t Z () const
Public Member Functions inherited from LKContainer
virtual void Clear (Option_t *option="")
virtual void Copy (TObject &object) const
LKContainer ()
virtual ~LKContainer ()
Protected Attributes
Int_t fLayer = -999
Int_t fPadID = -1
Int_t fRow = -999
Int_t fSection = -999
Double_t fTb = -1
Protected Attributes inherited from LKHit
Double_t fAlpha = -999
Double_t fDX = -999
Double_t fDY = -999
Double_t fDZ = -999
LKHitArray fHitArray
sort earlier if smaller, latter if larger
Int_t fHitID = -1
Double_t fSortValue = 0
vector< Int_t > fTrackCandArray
Int_t fTrackID = -1
Protected Attributes inherited from LKWPoint
Double_t fW
Double_t fX
Double_t fY
Double_t fZ
Detailed Description
Definition at line 17 of file LKTpcHit.h.
Constructor & Destructor Documentation
LKTpcHit()
LKTpcHit::LKTpcHit () inline
Definition at line 27 of file LKTpcHit.h.
References Clear().
~LKTpcHit()
virtual LKTpcHit::~LKTpcHit () inline virtual
Definition at line 28 of file LKTpcHit.h.
Member Function Documentation
AddHit()
void LKTpcHit::AddHit (LKHit * hit) virtual
Reimplemented from LKHit.
Definition at line 100 of file LKTpcHit.cpp.
References AddTpcHit().
AddTpcHit()
void LKTpcHit::AddTpcHit (LKTpcHit * hit)
Definition at line 105 of file LKTpcHit.cpp.
References LKHit::AddHit(), fTb, LKWPoint::fW, LKHit::GetCharge(), and GetTb().
Referenced by AddHit().
Clear()
virtual void LKTpcHit::Clear (Option_t * option = "") virtual
Reimplemented from LKHit.
Referenced by LKTpcHit().
Copy()
void LKTpcHit::Copy (TObject & object) const virtual
Reimplemented from LKHit.
Definition at line 77 of file LKTpcHit.cpp.
References LKHit::fAlpha, LKHit::fHitID, fLayer, fPadID, fRow, fSection, LKHit::fSortValue, fTb, LKHit::fTrackID, LKWPoint::fW, LKWPoint::fX, LKWPoint::fY, and LKWPoint::fZ.
CopyFrom()
void LKTpcHit::CopyFrom (LKTpcHit const * hit)
Definition at line 57 of file LKTpcHit.cpp.
References LKHit::fAlpha, LKHit::fHitID, fLayer, fPadID, fRow, fSection, LKHit::fSortValue, fTb, LKHit::fTrackID, LKWPoint::fW, LKWPoint::fX, LKWPoint::fY, LKWPoint::fZ, LKHit::GetAlpha(), LKHit::GetCharge(), LKHit::GetHitID(), GetLayer(), GetPadID(), GetRow(), GetSection(), LKHit::GetSortValue(), GetTb(), LKHit::GetTrackID(), LKHit::GetX(), LKHit::GetY(), and LKHit::GetZ().
GetLayer()
Int_t LKTpcHit::GetLayer () const
Definition at line 129 of file LKTpcHit.cpp.
References fLayer.
Referenced by CopyFrom().
GetPadID()
Int_t LKTpcHit::GetPadID () const
Definition at line 126 of file LKTpcHit.cpp.
References fPadID.
Referenced by CopyFrom().
GetPulseFunction()
TF1 * LKTpcHit::GetPulseFunction (Option_t * option = "") virtual
Definition at line 112 of file LKTpcHit.cpp.
References fTb, LKWPoint::fW, GetPulseFunction(), and LKPulseGenerator::GetPulseGenerator().
Referenced by GetPulseFunction().
GetRow()
Int_t LKTpcHit::GetRow () const
Definition at line 128 of file LKTpcHit.cpp.
References fRow.
Referenced by CopyFrom().
GetSection()
Int_t LKTpcHit::GetSection () const
Definition at line 127 of file LKTpcHit.cpp.
References fSection.
Referenced by CopyFrom().
GetTb()
Double_t LKTpcHit::GetTb () const
Definition at line 130 of file LKTpcHit.cpp.
References fTb.
Referenced by AddTpcHit(), and CopyFrom().
Print()
void LKTpcHit::Print (Option_t * option = "at") const virtual
Reimplemented from LKHit.
Definition at line 25 of file LKTpcHit.cpp.
References e_info, LKHit::fHitID, fLayer, fPadID, fRow, fSection, fTb, LKHit::fTrackID, LKWPoint::fW, LKWPoint::fX, LKWPoint::fY, and LKWPoint::fZ.
PrintTpcHit()
void LKTpcHit::PrintTpcHit () const virtual
Definition at line 34 of file LKTpcHit.cpp.
References e_info, LKHit::fHitID, fLayer, fPadID, fRow, fSection, fTb, LKHit::fTrackID, LKWPoint::fW, LKWPoint::fX, LKWPoint::fY, and LKWPoint::fZ.
SetLayer()
void LKTpcHit::SetLayer (Int_t layer)
Definition at line 123 of file LKTpcHit.cpp.
References fLayer.
SetPadID()
void LKTpcHit::SetPadID (Int_t id)
Definition at line 120 of file LKTpcHit.cpp.
References fPadID.
SetRow()
void LKTpcHit::SetRow (Int_t row)
Definition at line 122 of file LKTpcHit.cpp.
References fRow.
SetSection()
void LKTpcHit::SetSection (Int_t section)
Definition at line 121 of file LKTpcHit.cpp.
References fSection.
SetSortByLayer()
void LKTpcHit::SetSortByLayer (bool sortEarlierIfSmaller)
Definition at line 132 of file LKTpcHit.cpp.
References fLayer, and LKHit::fSortValue.
SetTb()
void LKTpcHit::SetTb (Double_t tb)
Definition at line 124 of file LKTpcHit.cpp.
References fTb.
Member Data Documentation
fLayer
Int_t LKTpcHit::fLayer = -999 protected
Definition at line 23 of file LKTpcHit.h.
Referenced by ClassImp(), Copy(), CopyFrom(), GetLayer(), Print(), PrintTpcHit(), SetLayer(), and SetSortByLayer().
fPadID
Int_t LKTpcHit::fPadID = -1 protected
Definition at line 20 of file LKTpcHit.h.
Referenced by ClassImp(), Copy(), CopyFrom(), GetPadID(), Print(), PrintTpcHit(), and SetPadID().
fRow
Int_t LKTpcHit::fRow = -999 protected
Definition at line 22 of file LKTpcHit.h.
Referenced by ClassImp(), Copy(), CopyFrom(), GetRow(), Print(), PrintTpcHit(), and SetRow().
fSection
Int_t LKTpcHit::fSection = -999 protected
Definition at line 21 of file LKTpcHit.h.
Referenced by ClassImp(), Copy(), CopyFrom(), GetSection(), Print(), PrintTpcHit(), and SetSection().
fTb
Double_t LKTpcHit::fTb = -1 protected
Definition at line 24 of file LKTpcHit.h.
Referenced by AddTpcHit(), ClassImp(), Copy(), CopyFrom(), GetPulseFunction(), GetTb(), Print(), PrintTpcHit(), and SetTb().
The documentation for this class was generated from the following files:
LKTpcHit.h
LKTpcHit.cpp