LILAK: LKMCTrack Class Reference
LKMCTrack Class Reference abstract
#include <LKMCTrack.h>
Public Types
enum LKFitStatus : int {
kNone = -1 , kBad = 0 , kLine = 1 , kPlane = 2 ,
kHelix = 3 , kGenfitTrack = 4
}
Public Member Functions
virtual void AddHit (LKHit *hit)
void AddStep (LKMCStep *hit)
void AddVertex (Int_t detectorID, Int_t processID, Double_t vx, Double_t vy, Double_t vz, Double_t px, Double_t py, Double_t pz, Double_t energy)
virtual void Clear (Option_t *option="")
virtual void ClearHits ()
virtual double Continuity (double &totalLength, double &continuousLength, double distCut=25)
virtual double Continuity (double distCut=25)
virtual void Copy (TObject &object) const
virtual bool DoDrawOnDetectorPlane ()
virtual bool DrawByDefault ()
return true if to be displayed on eve.
virtual TVector3 ExtrapolateByLength (double l) const =0
Extrapolate by length (tail:0), returns extrapolated position.
virtual TVector3 ExtrapolateByLength (Double_t l) const
virtual TVector3 ExtrapolateByRatio (double r) const =0
Extrapolate by ratio (tail:0, head:1), returns extrapolated position.
virtual TVector3 ExtrapolateByRatio (Double_t r) const
virtual TVector3 ExtrapolateHead (double l) const =0
Extrapolate head of track about length, returns extrapolated position.
virtual TVector3 ExtrapolateHead (Double_t l) const
virtual TVector3 ExtrapolateTail (double l) const =0
Extrapolate tail of track about length, returns extrapolated position.
virtual TVector3 ExtrapolateTail (Double_t l) const
virtual TVector3 ExtrapolateTo (TVector3 point) const
Extrapolate to POCA from point, returns extrapolated position.
void FillTrajectory (TGraphErrors *graphTrack, LKVector3::Axis axis1, LKVector3::Axis axis2)
void FillTrajectory (TGraphErrors *graphTrack, LKVector3::Axis axis1, LKVector3::Axis axis2, bool(*fisout)(TVector3 pos))
void FillTrajectory3D (TGraph2DErrors *graphTrack3D, LKVector3::Axis axis1, LKVector3::Axis axis2, LKVector3::Axis axis3)
void FillTrajectory3D (TGraph2DErrors *graphTrack3D, LKVector3::Axis axis1, LKVector3::Axis axis2, LKVector3::Axis axis3, bool(*fisout)(TVector3 pos))
virtual void FinalizeHits ()
virtual bool Fit ()
virtual LKGeoHelix FitHelix (LKVector3::Axis ref)
virtual LKGeoLine FitLine ()
virtual LKGeoPlane FitPlane ()
double GetChargeSum () const
Int_t GetDetectorID (Int_t idx=0) const
Double_t GetEnergy (Int_t idx=0) const
LKTracklet::LKFitStatus GetFitStatus () const
TString GetFitStatusString () const
LKHit * GetHit (int idx) const
LKHitArray * GetHitArray ()
int GetHitID (int idx) const
std::vector< int > * GetHitIDArray ()
TVector3 GetMean () const
TVector3 GetMomentum (Int_t idx=0) const
int GetNumHits () const
Int_t GetNumVertices () const
int GetParentID () const
int GetPDG () const
Int_t GetPrimaryDetectorID () const
TVector3 GetPrimaryPosition () const
Int_t GetPrimaryVolumeID () const
Double_t GetPX (Int_t idx=0) const
Double_t GetPY (Int_t idx=0) const
Double_t GetPZ (Int_t idx=0) const
Int_t GetStatusID (Int_t idx=0) const
vector< LKMCStep * > * GetStepArray ()
int GetTrackID () const
TVector3 GetVertex (Int_t idx=0) const
Int_t GetVolumeID (Int_t idx=0) const
Double_t GetVX (Int_t idx=0) const
Double_t GetVY (Int_t idx=0) const
Double_t GetVZ (Int_t idx=0) const
bool IsBad () const
bool IsGenfitTrack () const
bool IsHelix () const
bool IsHoldingHits ()
bool IsLine () const
bool IsPlane () const
virtual Double_t LengthAt (TVector3 point) const
Length at POCA from point, where tail=0, head=TrackLength.
LKMCTrack ()
virtual TVector3 Momentum (double B=0.5) const =0
Momentum of track at head.
virtual TVector3 Momentum (Double_t B=0.5) const
virtual TVector3 PositionAtHead () const
Position at head of helix.
virtual TVector3 PositionAtTail () const
Position at tail of helix.
virtual void Print (Option_t *option="") const
virtual int RecoverHitArrayWithHitID (TClonesArray *hitArray)
virtual int RecoverHitArrayWithTrackID (TClonesArray *hitArray)
virtual void RemoveHit (LKHit *hit)
void SetDetectorID (Int_t id)
void SetEnergy (Double_t val)
void SetFitStatus (LKFitStatus value)
void SetIsBad ()
void SetIsGenfitTrack ()
void SetIsHelix ()
void SetIsLine ()
void SetIsPlane ()
void SetMCTrack (Int_t trackID, Int_t parentID, Int_t pdg, Int_t detectorID, Int_t processID, Double_t vx, Double_t vy, Double_t vz, Double_t px, Double_t py, Double_t pz, Double_t energy)
void SetParentID (int val)
void SetPDG (int val)
void SetPX (Double_t val)
void SetPY (Double_t val)
void SetPZ (Double_t val)
void SetStatusID (Int_t id)
void SetTrackID (int val)
void SetVolumeID (Int_t id)
void SetVX (Double_t val)
void SetVY (Double_t val)
void SetVZ (Double_t val)
virtual void SortHits (bool increasing=true)
virtual Double_t TrackLength () const
Length of track calculated from head to tail.
virtual TGraphErrors * TrajectoryOnPlane (axis_t axis1, axis_t axis2, bool(*fisout)(TVector3 pos), Double_t scale=1)
virtual TGraphErrors * TrajectoryOnPlane (LKDetectorPlane *plane, double scale=1)
virtual TGraphErrors * TrajectoryOnPlane (LKVector3::Axis axis1, LKVector3::Axis axis2, bool(*fisout)(TVector3 pos), double scale=1)
virtual TGraphErrors * TrajectoryOnPlane (LKVector3::Axis axis1, LKVector3::Axis axis2, double scale=1)
virtual ~LKMCTrack ()
Protected Attributes
vector< Double_t > fEnergy
LKFitStatus fFitStatus
One of kBad, kHelix and kLine.
LKHitArray fHitArray
vector< int > fHitIDArray
int fParentID = -1
Vertex ID.
int fPDG = -1
vector< Double_t > fPX
vector< Double_t > fPY
vector< Double_t > fPZ
vector< Int_t > fStatusID
vector< LKMCStep * > fStepArray
int fTrackID = -1
TGraphErrors * fTrajectoryOnPlane = nullptr
vector< Int_t > fVolumeID
detector ID (= copyNo)
vector< Double_t > fVX
vector< Double_t > fVY
vector< Double_t > fVZ
Detailed Description
Eve naming concept : mc_pnm:tid(pid)[mom]{dnm;nvx}
pnm: particle name or PDG encoding number
tid: track id
pid: parent id
mom: momentum value in MeV/c
dnm: detector name or detector id
nvx: number of vertex
Definition at line 27 of file LKMCTrack.h.
Member Enumeration Documentation
LKFitStatus
enum LKTracklet::LKFitStatus : int inherited
Enumerator
kNone
kBad
kLine
kPlane
kHelix
kGenfitTrack
Definition at line 19 of file LKTracklet.h.
Constructor & Destructor Documentation
LKMCTrack()
LKMCTrack::LKMCTrack ()
~LKMCTrack()
virtual LKMCTrack::~LKMCTrack () inline virtual
Definition at line 31 of file LKMCTrack.h.
Member Function Documentation
AddHit()
void LKTracklet::AddHit (LKHit * hit) virtual inherited
Definition at line 42 of file LKTracklet.cpp.
References LKHitArray::AddHit(), LKTracklet::fHitArray, LKTracklet::fHitIDArray, LKTracklet::fTrackID, LKHit::GetHitID(), and LKTracklet::SetTrackID().
AddStep()
void LKMCTrack::AddStep (LKMCStep * hit)
Definition at line 142 of file LKMCTrack.cpp.
References fStepArray.
AddVertex()
void LKMCTrack::AddVertex (Int_t detectorID, Int_t processID, Double_t vx, Double_t vy, Double_t vz, Double_t px, Double_t py, Double_t pz, Double_t energy)
Definition at line 108 of file LKMCTrack.cpp.
References fEnergy, fPX, fPY, fPZ, fStatusID, fVolumeID, fVX, fVY, and fVZ.
Clear()
void LKMCTrack::Clear (Option_t * option = "") virtual
Reimplemented from LKTracklet.
Definition at line 20 of file LKMCTrack.cpp.
References LKTracklet::Clear(), fEnergy, fPX, fPY, fPZ, fStatusID, fVolumeID, fVX, fVY, and fVZ.
Referenced by ClassImp().
ClearHits()
void LKTracklet::ClearHits () virtual inherited
Definition at line 36 of file LKTracklet.cpp.
References LKHitArray::Clear(), LKTracklet::fHitArray, and LKTracklet::fHitIDArray.
Continuity() [1/2]
double LKTracklet::Continuity (double & totalLength, double & continuousLength, double distCut = 25) virtual inherited
Check continuity of the track. Hit array must be filled. Returns ratio of the continuous region. (-1 if less than 2 hits)
If difference between "length from hits" is smaller than distCut, (> pad-diagonal, < 2*pad-row) the region is considered to be connected.
The total length calculation is different from TrackLength(), because TrackLength() use only the head/tail alpha angle information but this method calculate length directly from the hit using Map(...) method.
Parameters
continuousLength calculated length of continuos region.
totalLength calculated total length of the track.
Reimplemented in LKHelixTrack.
Definition at line 214 of file LKTracklet.cpp.
References LKTracklet::fHitArray, LKHitArray::GetHit(), LKHitArray::GetNumHits(), LKHit::GetPosition(), and LKTracklet::SortHits().
Continuity() [2/2]
virtual double LKTracklet::Continuity (double distCut = 25) inline virtual inherited
Definition at line 164 of file LKTracklet.h.
References LKTracklet::Continuity().
Referenced by LKTracklet::Continuity().
Copy()
void LKContainer::Copy (TObject & object) const virtual inherited
Reimplemented in LKChannel, LKHoughPointRT, LKImagePoint, LKEventHeader, LKMCTagged, LKHit, LKVertex, LKWPoint, GETChannel, LKHelixTrack, LKImagePoint, TTBeamHeader, TTChannelCalibrationData, and TTEventHeader.
Definition at line 16 of file LKContainer.cpp.
Referenced by LKChannel::Copy(), LKHoughPointRT::Copy(), LKImagePoint::Copy(), LKEventHeader::Copy(), LKMCTagged::Copy(), LKHit::Copy(), LKWPoint::Copy(), TTBeamHeader::Copy(), TTChannelCalibrationData::Copy(), and TTEventHeader::Copy().
DoDrawOnDetectorPlane()
bool LKTracklet::DoDrawOnDetectorPlane () virtual inherited
Definition at line 155 of file LKTracklet.cpp.
DrawByDefault()
bool LKTracklet::DrawByDefault () virtual inherited
return true if to be displayed on eve.
Reimplemented from LKContainer.
Definition at line 116 of file LKTracklet.cpp.
ExtrapolateByLength() [1/2]
virtual TVector3 LKTracklet::ExtrapolateByLength (double l) const pure virtual inherited
Extrapolate by length (tail:0), returns extrapolated position.
ExtrapolateByLength() [2/2]
TVector3 LKMCTrack::ExtrapolateByLength (Double_t l) const virtual
Definition at line 169 of file LKMCTrack.cpp.
ExtrapolateByRatio() [1/2]
virtual TVector3 LKTracklet::ExtrapolateByRatio (double r) const pure virtual inherited
Extrapolate by ratio (tail:0, head:1), returns extrapolated position.
Referenced by LKTracklet::FillTrajectory(), and LKTracklet::FillTrajectory3D().
ExtrapolateByRatio() [2/2]
TVector3 LKMCTrack::ExtrapolateByRatio (Double_t r) const virtual
Definition at line 168 of file LKMCTrack.cpp.
ExtrapolateHead() [1/2]
virtual TVector3 LKTracklet::ExtrapolateHead (double l) const pure virtual inherited
Extrapolate head of track about length, returns extrapolated position.
ExtrapolateHead() [2/2]
TVector3 LKMCTrack::ExtrapolateHead (Double_t l) const virtual
Definition at line 166 of file LKMCTrack.cpp.
ExtrapolateTail() [1/2]
virtual TVector3 LKTracklet::ExtrapolateTail (double l) const pure virtual inherited
Extrapolate tail of track about length, returns extrapolated position.
ExtrapolateTail() [2/2]
TVector3 LKMCTrack::ExtrapolateTail (Double_t l) const virtual
Definition at line 167 of file LKMCTrack.cpp.
ExtrapolateTo()
TVector3 LKMCTrack::ExtrapolateTo (TVector3 point) const virtual
Extrapolate to POCA from point, returns extrapolated position.
Implements LKTracklet.
Definition at line 165 of file LKMCTrack.cpp.
FillTrajectory() [1/2]
void LKTracklet::FillTrajectory (TGraphErrors * graphTrack, LKVector3::Axis axis1, LKVector3::Axis axis2) inherited
Definition at line 193 of file LKTracklet.cpp.
References LKTracklet::FillTrajectory().
FillTrajectory() [2/2]
void LKTracklet::FillTrajectory (TGraphErrors * graphTrack, LKVector3::Axis axis1, LKVector3::Axis axis2, bool(*)(TVector3 pos) fisout) inherited
Definition at line 184 of file LKTracklet.cpp.
References LKTracklet::ExtrapolateByRatio(), LKVector3::kZ, and SetPoint().
Referenced by LKTracklet::FillTrajectory(), and LKTracklet::TrajectoryOnPlane().
FillTrajectory3D() [1/2]
void LKTracklet::FillTrajectory3D (TGraph2DErrors * graphTrack3D, LKVector3::Axis axis1, LKVector3::Axis axis2, LKVector3::Axis axis3) inherited
Definition at line 208 of file LKTracklet.cpp.
References LKTracklet::FillTrajectory3D().
FillTrajectory3D() [2/2]
void LKTracklet::FillTrajectory3D (TGraph2DErrors * graphTrack3D, LKVector3::Axis axis1, LKVector3::Axis axis2, LKVector3::Axis axis3, bool(*)(TVector3 pos) fisout) inherited
Definition at line 199 of file LKTracklet.cpp.
References LKTracklet::ExtrapolateByRatio(), LKVector3::kZ, and SetPoint().
Referenced by LKTracklet::FillTrajectory3D().
FinalizeHits()
void LKTracklet::FinalizeHits () virtual inherited
Definition at line 62 of file LKTracklet.cpp.
References LKTracklet::fHitArray, LKTracklet::fTrackID, next(), and LKTracklet::SetTrackID().
Fit()
virtual bool LKTracklet::Fit () inline virtual inherited
Reimplemented in LKHelixTrack, and LKLinearTrack.
Definition at line 110 of file LKTracklet.h.
FitHelix()
LKGeoHelix LKTracklet::FitHelix (LKVector3::Axis ref) virtual inherited
Definition at line 260 of file LKTracklet.cpp.
References LKTracklet::fHitArray, LKHitArray::FitHelix(), LKGeometry::GetRMS(), and LKTracklet::SetIsHelix().
FitLine()
LKGeoLine LKTracklet::FitLine () virtual inherited
Definition at line 244 of file LKTracklet.cpp.
References LKTracklet::fHitArray, LKHitArray::FitLine(), LKGeometry::GetRMS(), and LKTracklet::SetIsLine().
FitPlane()
LKGeoPlane LKTracklet::FitPlane () virtual inherited
Reimplemented in LKHelixTrack.
Definition at line 252 of file LKTracklet.cpp.
References LKTracklet::fHitArray, LKHitArray::FitPlane(), LKGeometry::GetRMS(), and LKTracklet::SetIsPlane().
GetChargeSum()
double LKTracklet::GetChargeSum () const inline inherited
Definition at line 90 of file LKTracklet.h.
References LKTracklet::fHitArray, and LKHitArray::GetW().
GetDetectorID()
Int_t LKMCTrack::GetDetectorID (Int_t idx = 0) const
Definition at line 124 of file LKMCTrack.cpp.
References fVolumeID.
Referenced by GetVolumeID().
GetEnergy()
Double_t LKMCTrack::GetEnergy (Int_t idx = 0) const
Definition at line 136 of file LKMCTrack.cpp.
References fEnergy.
GetFitStatus()
LKTracklet::LKFitStatus LKTracklet::GetFitStatus () const inline inherited
Definition at line 35 of file LKTracklet.h.
References LKTracklet::fFitStatus.
GetFitStatusString()
TString LKTracklet::GetFitStatusString () const inline inherited
Definition at line 42 of file LKTracklet.h.
References LKTracklet::fFitStatus, LKTracklet::kBad, LKTracklet::kGenfitTrack, LKTracklet::kHelix, LKTracklet::kLine, and LKTracklet::kPlane.
Referenced by LKHelixTrack::Print().
GetHit()
LKHit * LKTracklet::GetHit (int idx) const inline inherited
Definition at line 84 of file LKTracklet.h.
References LKTracklet::fHitArray, and LKHitArray::GetHit().
GetHitArray()
LKHitArray * LKTracklet::GetHitArray () inline inherited
Definition at line 86 of file LKTracklet.h.
References LKTracklet::fHitArray.
Referenced by LKLinearTrack::CopyFrom(), TTHTTrackingTask::MakeTrack(), and TTHTtBeamTrackingTask::MakeTrack().
GetHitID()
int LKTracklet::GetHitID (int idx) const inline inherited
Definition at line 85 of file LKTracklet.h.
References LKTracklet::fHitIDArray.
Referenced by LKTracklet::RecoverHitArrayWithHitID(), and LKTracklet::RemoveHit().
GetHitIDArray()
std::vector< int > * LKTracklet::GetHitIDArray () inline inherited
Definition at line 87 of file LKTracklet.h.
References LKTracklet::fHitIDArray.
Referenced by LKLinearTrack::CopyFrom().
GetMean()
TVector3 LKTracklet::GetMean () const inline inherited
Definition at line 89 of file LKTracklet.h.
References LKTracklet::fHitArray, and LKHitArray::GetMean().
GetMomentum()
TVector3 LKMCTrack::GetMomentum (Int_t idx = 0) const
Definition at line 130 of file LKMCTrack.cpp.
References fPX, fPY, and fPZ.
Referenced by Momentum(), PositionAtHead(), and TrajectoryOnPlane().
GetNumHits()
int LKTracklet::GetNumHits () const inline inherited
Definition at line 83 of file LKTracklet.h.
References LKTracklet::fHitIDArray.
Referenced by LKLinearTrack::Print().
GetNumVertices()
Int_t LKMCTrack::GetNumVertices () const
Definition at line 121 of file LKMCTrack.cpp.
References fPX.
GetParentID()
int LKTracklet::GetParentID () const inline inherited
Definition at line 80 of file LKTracklet.h.
References LKTracklet::fParentID.
Referenced by LKLinearTrack::CopyFrom(), and LKEveTask::SelectTrack().
GetPDG()
int LKTracklet::GetPDG () const inline inherited
Definition at line 81 of file LKTracklet.h.
References LKTracklet::fPDG.
Referenced by LKLinearTrack::CopyFrom(), and LKEveTask::SelectTrack().
GetPrimaryDetectorID()
Int_t LKMCTrack::GetPrimaryDetectorID () const
Definition at line 140 of file LKMCTrack.cpp.
References GetPrimaryVolumeID().
GetPrimaryPosition()
TVector3 LKMCTrack::GetPrimaryPosition () const
Definition at line 138 of file LKMCTrack.cpp.
References fVX, fVY, and fVZ.
Referenced by PositionAtHead(), PositionAtTail(), and TrajectoryOnPlane().
GetPrimaryVolumeID()
Int_t LKMCTrack::GetPrimaryVolumeID () const
Definition at line 139 of file LKMCTrack.cpp.
References fVolumeID.
Referenced by GetPrimaryDetectorID().
GetPX()
Double_t LKMCTrack::GetPX (Int_t idx = 0) const
Definition at line 127 of file LKMCTrack.cpp.
References fPX.
GetPY()
Double_t LKMCTrack::GetPY (Int_t idx = 0) const
Definition at line 128 of file LKMCTrack.cpp.
References fPY.
GetPZ()
Double_t LKMCTrack::GetPZ (Int_t idx = 0) const
Definition at line 129 of file LKMCTrack.cpp.
References fPZ.
GetStatusID()
Int_t LKMCTrack::GetStatusID (Int_t idx = 0) const
Definition at line 123 of file LKMCTrack.cpp.
References fStatusID.
GetStepArray()
vector< LKMCStep * > * LKMCTrack::GetStepArray ()
Definition at line 143 of file LKMCTrack.cpp.
References fStepArray.
GetTrackID()
int LKTracklet::GetTrackID () const inline inherited
Definition at line 79 of file LKTracklet.h.
References LKTracklet::fTrackID.
Referenced by LKVertex::AddTrack(), LKLinearTrack::CopyFrom(), and LKEveTask::SelectTrack().
GetVertex()
TVector3 LKMCTrack::GetVertex (Int_t idx = 0) const
Definition at line 135 of file LKMCTrack.cpp.
References fVX, fVY, and fVZ.
GetVolumeID()
Int_t LKMCTrack::GetVolumeID (Int_t idx = 0) const
Definition at line 125 of file LKMCTrack.cpp.
References GetDetectorID().
GetVX()
Double_t LKMCTrack::GetVX (Int_t idx = 0) const
Definition at line 132 of file LKMCTrack.cpp.
References fVX.
GetVY()
Double_t LKMCTrack::GetVY (Int_t idx = 0) const
Definition at line 133 of file LKMCTrack.cpp.
References fVY.
GetVZ()
Double_t LKMCTrack::GetVZ (Int_t idx = 0) const
Definition at line 134 of file LKMCTrack.cpp.
References fVZ.
IsBad()
bool LKTracklet::IsBad () const inline inherited
Definition at line 36 of file LKTracklet.h.
References LKTracklet::fFitStatus, and LKTracklet::kBad.
IsGenfitTrack()
bool LKTracklet::IsGenfitTrack () const inline inherited
Definition at line 40 of file LKTracklet.h.
References LKTracklet::fFitStatus, and LKTracklet::kGenfitTrack.
Referenced by LKHelixTrack::Momentum().
IsHelix()
bool LKTracklet::IsHelix () const inline inherited
Definition at line 39 of file LKTracklet.h.
References LKTracklet::fFitStatus, and LKTracklet::kHelix.
Referenced by LKHelixTrack::Momentum().
IsHoldingHits()
bool LKTracklet::IsHoldingHits () inherited
Definition at line 107 of file LKTracklet.cpp.
References LKTracklet::fHitArray, LKTracklet::fHitIDArray, and LKHitArray::GetNumHits().
IsLine()
bool LKTracklet::IsLine () const inline inherited
Definition at line 37 of file LKTracklet.h.
References LKTracklet::fFitStatus, and LKTracklet::kLine.
IsPlane()
bool LKTracklet::IsPlane () const inline inherited
Definition at line 38 of file LKTracklet.h.
References LKTracklet::fFitStatus, and LKTracklet::kPlane.
LengthAt()
Double_t LKMCTrack::LengthAt (TVector3 point) const virtual
Length at POCA from point, where tail=0, head=TrackLength.
Implements LKTracklet.
Definition at line 170 of file LKMCTrack.cpp.
Momentum() [1/2]
virtual TVector3 LKTracklet::Momentum (double B = 0.5) const pure virtual inherited
Momentum of track at head.
Momentum() [2/2]
TVector3 LKMCTrack::Momentum (Double_t B = 0.5) const virtual
Definition at line 145 of file LKMCTrack.cpp.
References GetMomentum().
PositionAtHead()
TVector3 LKMCTrack::PositionAtHead () const virtual
Position at head of helix.
Implements LKTracklet.
Definition at line 146 of file LKMCTrack.cpp.
References GetMomentum(), and GetPrimaryPosition().
PositionAtTail()
TVector3 LKMCTrack::PositionAtTail () const virtual
Position at tail of helix.
Implements LKTracklet.
Definition at line 147 of file LKMCTrack.cpp.
References GetPrimaryPosition().
Print()
void LKMCTrack::Print (Option_t * option = "") const virtual
Definition at line 45 of file LKMCTrack.cpp.
References e_info, fEnergy, LKTracklet::fParentID, LKTracklet::fPDG, fPX, fPY, fPZ, fStatusID, LKTracklet::fTrackID, fVolumeID, fVX, fVY, and fVZ.
RecoverHitArrayWithHitID()
int LKTracklet::RecoverHitArrayWithHitID (TClonesArray * hitArray) virtual inherited
Be cautious on using this method! This method assumes that hit array was used to create track in same run and event This method will recover hit-array of track, which is removed before end of LILAK run. The track store hit IDs. The method will use this information to recover hit array.
Definition at line 87 of file LKTracklet.cpp.
References LKHitArray::AddHit(), LKTracklet::fHitArray, LKTracklet::fHitIDArray, and LKTracklet::GetHitID().
RecoverHitArrayWithTrackID()
int LKTracklet::RecoverHitArrayWithTrackID (TClonesArray * hitArray) virtual inherited
Be cautious on using this method! This method assumes that hit array and track were cretaed in same run and event This method will recover hit-array of track, which is removed before end of LILAK run. The track ID is set in hit container. The method will use this information to recover hit array.
Definition at line 72 of file LKTracklet.cpp.
References LKHitArray::AddHit(), LKTracklet::fHitArray, and LKTracklet::fTrackID.
RemoveHit()
void LKTracklet::RemoveHit (LKHit * hit) virtual inherited
Definition at line 49 of file LKTracklet.cpp.
References LKTracklet::fHitArray, LKTracklet::fHitIDArray, LKTracklet::GetHitID(), and LKHitArray::RemoveHit().
SetDetectorID()
void LKMCTrack::SetDetectorID (Int_t id)
Definition at line 90 of file LKMCTrack.cpp.
References SetVolumeID().
SetEnergy()
void LKMCTrack::SetEnergy (Double_t val)
Definition at line 87 of file LKMCTrack.cpp.
References fEnergy.
SetFitStatus()
void LKTracklet::SetFitStatus (LKFitStatus value) inline inherited
Definition at line 28 of file LKTracklet.h.
References LKTracklet::fFitStatus.
SetIsBad()
void LKTracklet::SetIsBad () inline inherited
Definition at line 29 of file LKTracklet.h.
References LKTracklet::fFitStatus, and LKTracklet::kBad.
SetIsGenfitTrack()
void LKTracklet::SetIsGenfitTrack () inline inherited
Definition at line 33 of file LKTracklet.h.
References LKTracklet::fFitStatus, and LKTracklet::kGenfitTrack.
SetIsHelix()
void LKTracklet::SetIsHelix () inline inherited
Definition at line 32 of file LKTracklet.h.
References LKTracklet::fFitStatus, and LKTracklet::kHelix.
Referenced by LKHelixTrack::Fit(), and LKTracklet::FitHelix().
SetIsLine()
void LKTracklet::SetIsLine () inline inherited
Definition at line 30 of file LKTracklet.h.
References LKTracklet::fFitStatus, and LKTracklet::kLine.
Referenced by LKTracklet::FitLine(), and LKHelixTrack::FitPlane().
SetIsPlane()
void LKTracklet::SetIsPlane () inline inherited
Definition at line 31 of file LKTracklet.h.
References LKTracklet::fFitStatus, and LKTracklet::kPlane.
Referenced by LKHelixTrack::FitPlane(), and LKTracklet::FitPlane().
SetMCTrack()
void LKMCTrack::SetMCTrack (Int_t trackID, Int_t parentID, Int_t pdg, Int_t detectorID, Int_t processID, Double_t vx, Double_t vy, Double_t vz, Double_t px, Double_t py, Double_t pz, Double_t energy)
Definition at line 92 of file LKMCTrack.cpp.
References fEnergy, LKTracklet::fParentID, LKTracklet::fPDG, fPX, fPY, fPZ, fStatusID, LKTracklet::fTrackID, fVolumeID, fVX, fVY, and fVZ.
SetParentID()
void LKTracklet::SetParentID (int val) inline inherited
Definition at line 76 of file LKTracklet.h.
References LKTracklet::fParentID.
SetPDG()
void LKTracklet::SetPDG (int val) inline inherited
Definition at line 77 of file LKTracklet.h.
References LKTracklet::fPDG.
SetPX()
void LKMCTrack::SetPX (Double_t val)
Definition at line 81 of file LKMCTrack.cpp.
References fPX.
SetPY()
void LKMCTrack::SetPY (Double_t val)
Definition at line 82 of file LKMCTrack.cpp.
References fPY.
SetPZ()
void LKMCTrack::SetPZ (Double_t val)
Definition at line 83 of file LKMCTrack.cpp.
References fPZ.
SetStatusID()
void LKMCTrack::SetStatusID (Int_t id)
Definition at line 89 of file LKMCTrack.cpp.
References fStatusID.
SetTrackID()
void LKTracklet::SetTrackID (int val) inline inherited
Definition at line 75 of file LKTracklet.h.
References LKTracklet::fTrackID.
Referenced by LKTracklet::AddHit(), and LKTracklet::FinalizeHits().
SetVolumeID()
void LKMCTrack::SetVolumeID (Int_t id)
Definition at line 88 of file LKMCTrack.cpp.
References fVolumeID.
Referenced by SetDetectorID().
SetVX()
void LKMCTrack::SetVX (Double_t val)
Definition at line 84 of file LKMCTrack.cpp.
References fVX.
SetVY()
void LKMCTrack::SetVY (Double_t val)
Definition at line 85 of file LKMCTrack.cpp.
References fVY.
SetVZ()
void LKMCTrack::SetVZ (Double_t val)
Definition at line 86 of file LKMCTrack.cpp.
References fVZ.
SortHits()
void LKTracklet::SortHits (bool increasing = true) virtual inherited
Reimplemented in LKHelixTrack.
Definition at line 268 of file LKTracklet.cpp.
References LKTracklet::fHitArray, LKHit::GetPosition(), and next().
Referenced by LKTracklet::Continuity().
TrackLength()
Double_t LKMCTrack::TrackLength () const virtual
Length of track calculated from head to tail.
Implements LKTracklet.
Definition at line 148 of file LKMCTrack.cpp.
References fVX, fVY, and fVZ.
TrajectoryOnPlane() [1/4]
TGraphErrors * LKMCTrack::TrajectoryOnPlane (axis_t axis1, axis_t axis2, bool(*)(TVector3 pos) fisout, Double_t scale = 1) virtual
Definition at line 257 of file LKMCTrack.cpp.
References LKTracklet::fParentID, LKTracklet::fPDG, fPX, LKTracklet::fTrajectoryOnPlane, fVX, fVY, fVZ, GetMomentum(), GetPrimaryPosition(), and SetPoint().
TrajectoryOnPlane() [2/4]
TGraphErrors * LKTracklet::TrajectoryOnPlane (LKDetectorPlane * plane, double scale = 1) virtual inherited
Definition at line 179 of file LKTracklet.cpp.
References LKDetectorPlane::GetAxis1(), LKDetectorPlane::GetAxis2(), and LKTracklet::TrajectoryOnPlane().
TrajectoryOnPlane() [3/4]
TGraphErrors * LKTracklet::TrajectoryOnPlane (LKVector3::Axis axis1, LKVector3::Axis axis2, bool(*)(TVector3 pos) fisout, double scale = 1) virtual inherited
Definition at line 160 of file LKTracklet.cpp.
References LKTracklet::FillTrajectory(), and LKTracklet::fTrajectoryOnPlane.
Referenced by LKTracklet::TrajectoryOnPlane(), and LKTracklet::TrajectoryOnPlane().
TrajectoryOnPlane() [4/4]
TGraphErrors * LKTracklet::TrajectoryOnPlane (LKVector3::Axis axis1, LKVector3::Axis axis2, double scale = 1) virtual inherited
Definition at line 173 of file LKTracklet.cpp.
References LKTracklet::TrajectoryOnPlane().
Member Data Documentation
fEnergy
vector<Double_t> LKMCTrack::fEnergy protected
Definition at line 109 of file LKMCTrack.h.
Referenced by AddVertex(), Clear(), GetEnergy(), Print(), SetEnergy(), and SetMCTrack().
fFitStatus
LKFitStatus LKTracklet::fFitStatus protected inherited
One of kBad, kHelix and kLine.
Definition at line 61 of file LKTracklet.h.
Referenced by LKHelixTrack::Clear(), LKHelixTrack::Copy(), LKTracklet::GetFitStatus(), LKTracklet::GetFitStatusString(), LKTracklet::IsBad(), LKTracklet::IsGenfitTrack(), LKTracklet::IsHelix(), LKTracklet::IsLine(), LKTracklet::IsPlane(), LKHelixTrack::Print(), LKTracklet::SetFitStatus(), LKTracklet::SetIsBad(), LKTracklet::SetIsGenfitTrack(), LKTracklet::SetIsHelix(), LKTracklet::SetIsLine(), and LKTracklet::SetIsPlane().
fHitArray
LKHitArray LKTracklet::fHitArray protected inherited
Definition at line 56 of file LKTracklet.h.
Referenced by LKTracklet::AddHit(), ClassImp(), LKTracklet::ClearHits(), LKHelixTrack::Continuity(), LKTracklet::Continuity(), LKHelixTrack::Copy(), LKLinearTrack::CopyFrom(), LKTracklet::FinalizeHits(), LKHelixTrack::Fit(), LKLinearTrack::Fit(), LKTracklet::FitHelix(), LKTracklet::FitLine(), LKHelixTrack::FitPlane(), LKTracklet::FitPlane(), LKTracklet::GetChargeSum(), LKTracklet::GetHit(), LKTracklet::GetHitArray(), LKTracklet::GetMean(), LKTracklet::IsHoldingHits(), LKHelixTrack::PerpLine(), LKHelixTrack::PerpPlane(), LKHelixTrack::Print(), LKLinearTrack::Print(), LKTracklet::RecoverHitArrayWithHitID(), LKTracklet::RecoverHitArrayWithTrackID(), LKTracklet::RemoveHit(), LKLinearTrack::SetLine(), LKHelixTrack::SortHits(), and LKTracklet::SortHits().
fHitIDArray
vector<int> LKTracklet::fHitIDArray protected inherited
Definition at line 57 of file LKTracklet.h.
Referenced by LKTracklet::AddHit(), ClassImp(), LKTracklet::ClearHits(), LKLinearTrack::CopyFrom(), LKTracklet::GetHitID(), LKTracklet::GetHitIDArray(), LKTracklet::GetNumHits(), LKTracklet::IsHoldingHits(), LKLinearTrack::Print(), LKTracklet::RecoverHitArrayWithHitID(), and LKTracklet::RemoveHit().
fParentID
int LKTracklet::fParentID = -1 protected inherited
Vertex ID.
Definition at line 53 of file LKTracklet.h.
Referenced by ClassImp(), LKHelixTrack::Copy(), LKLinearTrack::CopyFrom(), LKTracklet::GetParentID(), LKHelixTrack::Print(), Print(), SetMCTrack(), LKTracklet::SetParentID(), and TrajectoryOnPlane().
fPDG
int LKTracklet::fPDG = -1 protected inherited
Definition at line 54 of file LKTracklet.h.
Referenced by ClassImp(), LKLinearTrack::CopyFrom(), LKTracklet::GetPDG(), Print(), SetMCTrack(), LKTracklet::SetPDG(), and TrajectoryOnPlane().
fPX
vector<Double_t> LKMCTrack::fPX protected
Definition at line 103 of file LKMCTrack.h.
Referenced by AddVertex(), Clear(), GetMomentum(), GetNumVertices(), GetPX(), Print(), SetMCTrack(), SetPX(), and TrajectoryOnPlane().
fPY
vector<Double_t> LKMCTrack::fPY protected
Definition at line 104 of file LKMCTrack.h.
Referenced by AddVertex(), Clear(), GetMomentum(), GetPY(), Print(), SetMCTrack(), and SetPY().
fPZ
vector<Double_t> LKMCTrack::fPZ protected
Definition at line 105 of file LKMCTrack.h.
Referenced by AddVertex(), Clear(), GetMomentum(), GetPZ(), Print(), SetMCTrack(), and SetPZ().
fStatusID
vector<Int_t> LKMCTrack::fStatusID protected
Definition at line 101 of file LKMCTrack.h.
Referenced by AddVertex(), Clear(), GetStatusID(), Print(), SetMCTrack(), and SetStatusID().
fStepArray
vector<LKMCStep *> LKMCTrack::fStepArray protected
Definition at line 111 of file LKMCTrack.h.
Referenced by AddStep(), and GetStepArray().
fTrackID
int LKTracklet::fTrackID = -1 protected inherited
Definition at line 52 of file LKTracklet.h.
Referenced by LKTracklet::AddHit(), ClassImp(), LKHelixTrack::Copy(), LKLinearTrack::CopyFrom(), LKTracklet::FinalizeHits(), LKTracklet::GetTrackID(), LKHelixTrack::LKHelixTrack(), LKHelixTrack::Print(), LKLinearTrack::Print(), Print(), LKTracklet::RecoverHitArrayWithTrackID(), SetMCTrack(), and LKTracklet::SetTrackID().
fTrajectoryOnPlane
TGraphErrors* LKTracklet::fTrajectoryOnPlane = nullptr protected inherited
Definition at line 59 of file LKTracklet.h.
Referenced by TrajectoryOnPlane(), LKTracklet::TrajectoryOnPlane(), LKExtrapolatedTrack::TrajectoryOnPlane(), and LKExtrapolatedTrack::TrajectoryOnPlane().
fVolumeID
vector<Int_t> LKMCTrack::fVolumeID protected
detector ID (= copyNo)
Definition at line 102 of file LKMCTrack.h.
Referenced by AddVertex(), Clear(), GetDetectorID(), GetPrimaryVolumeID(), Print(), SetMCTrack(), and SetVolumeID().
fVX
vector<Double_t> LKMCTrack::fVX protected
Definition at line 106 of file LKMCTrack.h.
Referenced by AddVertex(), Clear(), GetPrimaryPosition(), GetVertex(), GetVX(), Print(), SetMCTrack(), SetVX(), TrackLength(), and TrajectoryOnPlane().
fVY
vector<Double_t> LKMCTrack::fVY protected
Definition at line 107 of file LKMCTrack.h.
Referenced by AddVertex(), Clear(), GetPrimaryPosition(), GetVertex(), GetVY(), Print(), SetMCTrack(), SetVY(), TrackLength(), and TrajectoryOnPlane().
fVZ
vector<Double_t> LKMCTrack::fVZ protected
Definition at line 108 of file LKMCTrack.h.
Referenced by AddVertex(), Clear(), GetPrimaryPosition(), GetVertex(), GetVZ(), Print(), SetMCTrack(), SetVZ(), TrackLength(), and TrajectoryOnPlane().
The documentation for this class was generated from the following files:
LKMCTrack.h
LKMCTrack.cpp