lilak: LKTpc Class Reference
LKTpc Class Reference abstract
#include <LKTpc.h>
Public Member Functions
LKPadPlane * GetDriftPlane (Double_t x, Double_t y, Double_t z)
virtual LKPadPlane * GetDriftPlane (TVector3 pos)=0
TVector3 GetEField (Double_t x, Double_t y, Double_t z)
virtual TVector3 GetEField (TVector3 pos)=0
virtual LKVector3::Axis GetEFieldAxis ()=0
virtual LKPadPlane * GetPadPlane (Int_t idx=0)
LKTpc ()
LKTpc (const char *name, const char *title)
virtual ~LKTpc ()
Public Member Functions inherited from LKDetector
void AddPlane (LKDetectorPlane *plane, Int_t planeID=0)
TGeoVolume * CreateGeoTop (TString name="TOP")
void FinishGeometry ()
virtual LKChannelAnalyzer * GetChannelAnalyzer (int id=0)
LKDetectorPlane * GetDetectorPlane (Int_t idx=0)
virtual bool GetEffectiveDimension (Double_t &x1, Double_t &y1, Double_t &z1, Double_t &x2, Double_t &y2, Double_t &z2)
TGeoManager * GetGeoManager ()
Int_t GetNumPlanes ()
LKDetectorSystem * GetParent ()
virtual bool Init ()
virtual bool IsInBoundary (Double_t x, Double_t y, Double_t z)
LKDetector ()
LKDetector (const char *name, const char *title)
virtual void Print (Option_t *option="") const
void SetGeoManager (TGeoManager *)
void SetParent (LKDetectorSystem *system)
void SetRun (LKRun *run)
void SetTransparency (Int_t transparency)
virtual ~LKDetector ()
Public Member Functions inherited from LKGear
void AddPar (LKParameterContainer *par)
void AddPar (TString fname)
virtual void AddParameterContainer (LKParameterContainer *par)
virtual void AddParameterContainer (TString fname)
void CreateParameterContainer ()
LKParameterContainer * GetPar () const
LKParameterContainer * GetParameterContainer () const
Int_t GetRank () const
LKGear ()
void SetAllowControlLogger (bool val)
void SetPar (LKParameterContainer *par)
virtual void SetParameterContainer (LKParameterContainer *par)
virtual void SetRank (Int_t rank)
void SetRun (LKRun *run)
virtual ~LKGear ()
Additional Inherited Members
Protected Member Functions inherited from LKDetector
virtual bool BuildDetectorPlane ()
virtual bool BuildGeometry ()
Protected Attributes inherited from LKDetector
LKChannelAnalyzer * fChannelAnalyzer0 = nullptr
TObjArray * fDetectorPlaneArray
TGeoManager * fGeoManager = nullptr
Int_t fNumPlanes = 0
int fNX
int fNY
int fNZ
LKDetectorSystem * fParent = nullptr
bool fUsePixelSpace
double fX1
double fX2
double fY1
double fY2
double fZ1
double fZ2
Protected Attributes inherited from LKGear
bool fAllowControlLogger = true
LKParameterContainer * fPar = nullptr
Int_t fRank = 0
LKRun * fRun = nullptr
Detailed Description
Definition at line 10 of file LKTpc.h.
Constructor & Destructor Documentation
LKTpc() [1/2]
LKTpc::LKTpc ()
LKTpc() [2/2]
LKTpc::LKTpc (const char * name, const char * title)
Definition at line 13 of file LKTpc.cpp.
~LKTpc()
virtual LKTpc::~LKTpc () inline virtual
Definition at line 15 of file LKTpc.h.
Member Function Documentation
GetDriftPlane() [1/2]
LKPadPlane * LKTpc::GetDriftPlane (Double_t x, Double_t y, Double_t z)
Definition at line 21 of file LKTpc.cpp.
References GetDriftPlane(), x, and y.
Referenced by GetDriftPlane().
GetDriftPlane() [2/2]
virtual LKPadPlane * LKTpc::GetDriftPlane (TVector3 pos) pure virtual
GetEField() [1/2]
TVector3 LKTpc::GetEField (Double_t x, Double_t y, Double_t z)
Definition at line 20 of file LKTpc.cpp.
References GetEField(), x, and y.
Referenced by GetEField().
GetEField() [2/2]
virtual TVector3 LKTpc::GetEField (TVector3 pos) pure virtual
GetEFieldAxis()
virtual LKVector3::Axis LKTpc::GetEFieldAxis () pure virtual
GetPadPlane()
LKPadPlane * LKTpc::GetPadPlane (Int_t idx = 0) virtual
Definition at line 18 of file LKTpc.cpp.
References LKDetector::GetDetectorPlane().
The documentation for this class was generated from the following files:
LKTpc.h
LKTpc.cpp