lilak: ATTPC20RectanglePad Class Reference
ATTPC20RectanglePad Class Reference
#include <ATTPC20RectanglePad.h>
Public Member Functions
ATTPC20RectanglePad ()
virtual void Draw (Option_t *option="colz")
Implementation recommanded for event display. Draw event display to the canvas.
virtual void DrawFrame (Option_t *option="")
virtual Int_t FindPadID (Double_t i, Double_t j)
virtual Int_t FindPadID (Int_t section, Int_t row, Int_t layer)
virtual TCanvas * GetCanvas (Option_t *option="")
Implementation recommanded for event display.
virtual TH2 * GetHist (Option_t *option="")
virtual double GetPadGap () const
virtual double GetPadHeight () const
virtual double GetPadWidth () const
virtual bool Init ()
virtual bool IsInBoundary (Double_t i, Double_t j)
virtual Double_t PadDisplacement () const
Return average pad displacement to each other.
virtual ~ATTPC20RectanglePad ()
Public Member Functions inherited from LKPadPlane
void AddHit (LKTpcHit *hit)
virtual void Clear (Option_t *option="")
virtual void DrawHist ()
virtual TVector3 DriftElectron (TVector3 xGlobal)
return (x,y,l). l : electron-drift-length
void FillBufferIn (Double_t i, Double_t j, Double_t tb, Double_t val, Int_t trackID=-1)
void FillDataToHist ()
Implementation recommanded. Fill data to histograms.
virtual Int_t FindChannelID (Double_t i, Double_t j)
virtual Int_t FindChannelID (Int_t section, Int_t layer, Int_t row)
virtual Int_t FindPadID (Double_t i, Double_t j)
virtual Int_t FindPadID (Int_t section, Int_t layer, Int_t row)
Int_t GetNumPads ()
LKPad * GetPad (Double_t i, Double_t j)
LKPad * GetPad (Int_t padID)
LKPad * GetPad (Int_t section, Int_t layer, Int_t row)
TObjArray * GetPadArray ()
LKPad * GetPadFast (Int_t padID)
void GrabNeighborPads (vector< LKPad * > *pads, vector< LKPad * > *neighborPads)
LKPadPlane ()
LKPadPlane (const char *name, const char *title)
Double_t PadDisplacement () const
Return average pad displacement to each other.
bool PadNeighborChecker ()
bool PadPositionChecker (bool checkCorners=true)
virtual void Print (Option_t *option="") const
void PullOutNeighborHits (Double_t x, Double_t y, Int_t range, LKHitArray *neighborHits)
void PullOutNeighborHits (Double_t x, Double_t y, Int_t range, vector< LKTpcHit * > *neighborHits)
void PullOutNeighborHits (LKHitArray *hits, LKHitArray *neighborHits)
void PullOutNeighborHits (TVector2 p, Int_t range, vector< LKTpcHit * > *neighborHits)
void PullOutNeighborHits (vector< LKTpcHit * > *hits, vector< LKTpcHit * > *neighborHits)
virtual LKTpcHit * PullOutNextFreeHit ()
For tracking use.
virtual void ResetEvent ()
For tracking use.
virtual void ResetHitMap ()
For tracking use.
virtual bool SetDataFromBranch ()
Implementation recommanded. Set waveform and hit data from input tree branches to pads.
void SetHitArray (TClonesArray *hitArray)
void SetPadArray (TClonesArray *padArray)
virtual TVector3 TbToGlobalPosition (LKPad *pad, int tb)
virtual ~LKPadPlane ()
Public Member Functions inherited from LKDetectorPlane
void AddChannel (LKChannel *channel)
Add channel to channel array in detector plane. For interanl use.
void AddHit (LKHit *hit)
void AddPad (LKPad *pad)
Add pad to pad array in detector plane. For interanl use.
virtual void Clear (Option_t *option="")
virtual void Draw (Option_t *option="")
Implementation recommanded for event display. Draw event display to the canvas.
virtual void DrawFrame (Option_t *option="")
virtual void DrawHist (Option_t *option="")
virtual void DriftElectron (TVector3 posGlobal, TVector3 &posFinal, double &driftLength)
virtual double DriftElectronBack (double tb)
virtual void DriftElectronBack (int padID, double tb, TVector3 &posReco, double &driftLength)
virtual void DriftElectronBack (LKPad *pad, double tb, TVector3 &posReco, double &driftLength)
virtual void FillDataToHist ()
Implementation recommanded. Fill data to histograms.
void FillPlane (double i, double j, double tb, double charge, int trackID=-1)
Find pad corresponding to the position (i,j) and fill time-bin by amount of charge.
virtual int FindChannelID (double i, double j)
Implementation recommanded. Find channel using position.
virtual int FindChannelID (int section, int layer, int row)
Implementation recommanded. Find channel using section, layer, row info.
virtual int FindPadID (double i, double j)
virtual int FindPadID (int cobo, int asad, int aget, int chan)
virtual int FindPadID (int section, int layer, int row)
virtual TPad * Get3DEventPad ()
If user wants to place 3D event display other than default canvas, this method should return corresponding TPad.
virtual axis_t GetAxis1 (int iPad=0) const
virtual axis_t GetAxis2 (int iPad=0) const
virtual axis_t GetAxis3 () const
virtual axis_t GetAxisDrift () const
virtual TCanvas * GetCanvas (Option_t *option="")
Implementation recommanded for event display.
LKChannel * GetChannel (int idx)
virtual LKChannelAnalyzer * GetChannelAnalyzer (int id=0)
TObjArray * GetChannelArray ()
LKChannel * GetChannelFast (int idx)
virtual TPad * GetCPad (int iPad)
For grabbing inner pads of canvas.
virtual TH2 * GetHist (Option_t *option="-1")
int GetNChannels ()
virtual int GetNumCPads ()
Get number of inner pads of canvas.
int GetNumPads ()
LKPad * GetPad (double i, double j)
LKPad * GetPad (int cobo, int asad, int aget, int chan)
LKPad * GetPad (int padID)
LKPad * GetPad (int section, int layer, int row)
TObjArray * GetPadArray ()
LKPad * GetPadFast (int idx)
int GetPlaneID () const
double GetPosition () const
virtual TVector3 GetPositionError (int padID)
double GetTbToLength () const
virtual TVector3 GlobalToLocalAxis (TVector3 posGlobal)
Implementation recommanded. Convert global position to local detector plane position.
void GrabNeighborPads (vector< LKPad * > *pads, vector< LKPad * > *neighborPads)
For tracking use.
virtual bool Init ()
bool IsActive () const
virtual bool IsInBoundary (double i, double j)
Implementation recommanded. Return if position (i,j) is inside the effective detector plane boundary.
LKDetectorPlane ()
LKDetectorPlane (const char *name, const char *title)
virtual TVector3 LocalToGlobalAxis (TVector3 posLocal)
virtual double PadDisplacement () const
Return average pad displacement to each other.
bool PadMapChecker ()
bool PadNeighborChecker ()
bool PadPositionChecker (bool checkCorners=true)
virtual void Print (Option_t *option="") const
void PullOutNeighborHits (double x, double y, int range, LKHitArray *neighborHits)
For tracking use.
void PullOutNeighborHits (double x, double y, int range, vector< LKHit * > *neighborHits)
For tracking use.
void PullOutNeighborHits (LKHitArray *hits, LKHitArray *neighborHits)
For tracking use.
void PullOutNeighborHits (TVector2 p, int range, vector< LKHit * > *neighborHits)
For tracking use.
void PullOutNeighborHits (vector< LKHit * > *hits, vector< LKHit * > *neighborHits)
For tracking use.
virtual LKHit * PullOutNextFreeHit ()
For tracking use.
virtual void ResetEvent ()
For tracking use.
virtual void ResetHitMap ()
For tracking use.
void SetActive (bool val)
virtual bool SetDataFromBranch ()
Implementation recommanded. Set waveform and hit data from input tree branches to pads.
void SetDetector (LKDetector *detector)
void SetDetectorName (TString name)
void SetHitArray (TClonesArray *hitArray)
void SetPadArray (TClonesArray *padArray)
void SetPlaneID (int id)
virtual ~LKDetectorPlane ()
Public Member Functions inherited from LKGear
void AddPar (LKParameterContainer *par)
void AddPar (TString fname)
virtual void AddParameterContainer (LKParameterContainer *par)
virtual void AddParameterContainer (TString fname)
void CreateParameterContainer ()
LKParameterContainer * GetPar () const
LKParameterContainer * GetParameterContainer () const
Int_t GetRank () const
LKGear ()
void SetAllowControlLogger (bool val)
void SetPar (LKParameterContainer *par)
virtual void SetParameterContainer (LKParameterContainer *par)
virtual void SetRank (Int_t rank)
void SetRun (LKRun *run)
virtual ~LKGear ()
Private Member Functions
Int_t FindSection (Double_t i, Double_t j)
std::vector< Int_t > PadNeighborIndex (Int_t layer, Int_t Row, Int_t PadID)
Private Attributes
Int_t ColumnNum = 32
Double_t fBasePadPos = 200.
Int_t fNPadsTotal = 0
std::vector< Int_t > fNRowsInLayer [1]
Int_t fNumSections = 1
Double_t fPadGap = 0.5
Double_t fPadHeight = 5.5
std::map< std::vector< Int_t >, Int_t > fPadMap
Double_t fPadWidth = 5.5
Int_t RowNum = 32
Additional Inherited Members
Protected Attributes inherited from LKPadPlane
TCanvas * fCvsChannelBuffer = nullptr
Int_t fEFieldAxis = -1
bool fFilledHit = false
bool fFilledPad = false
Int_t fFreePadIdx = 0
TGraph * fGraphChannelBoundary = nullptr
TGraph * fGraphChannelBoundaryNb [20] = {0}
Protected Attributes inherited from LKDetectorPlane
bool fActive = true
axis_t fAxis1 = LKVector3::kNon
Axis-1 lying in plane. Must be set by input parameter.
axis_t fAxis2 = LKVector3::kNon
Axis-2 lying in plane. Must be set by input parameter.
axis_t fAxis3 = LKVector3::kNon
Axis-3 = Axis-1 x Axis-2 perpendicular to plane.
axis_t fAxisDrift = LKVector3::kNon
Axis perpendicular to plane, in electron drifting direction. Must be set by input parameter.
TCanvas * fCanvas = nullptr
LKChannelAnalyzer * fChannelAnalyzer = nullptr
TObjArray * fChannelArray = nullptr
TCanvas * fCvsChannelBuffer = nullptr
LKDetector * fDetector = nullptr
TString fDetName
int fFreePadIdx = 0
TGraph * fGraphChannelBoundary = nullptr
TGraph * fGraphChannelBoundaryNb [20] = {0}
TH2 * fH2Plane = nullptr
bool fHitDataIsSet = false
bool fPadDataIsSet = false
int fPlaneID = -1
Detector plane id.
double fPosition
Global position of pad plane center.
double fTbToLength = 1
time-bin (tb) to position conversion factor. Must be set by input parameter.
Protected Attributes inherited from LKGear
bool fAllowControlLogger = true
LKParameterContainer * fPar = nullptr
Int_t fRank = 0
LKRun * fRun = nullptr
Detailed Description
Definition at line 12 of file ATTPC20RectanglePad.h.
Constructor & Destructor Documentation
ATTPC20RectanglePad()
ATTPC20RectanglePad::ATTPC20RectanglePad ()
~ATTPC20RectanglePad()
virtual ATTPC20RectanglePad::~ATTPC20RectanglePad () inline virtual
Definition at line 16 of file ATTPC20RectanglePad.h.
Member Function Documentation
Draw()
void ATTPC20RectanglePad::Draw (Option_t * option = "colz") virtual
Implementation recommanded for event display. Draw event display to the canvas.
Reimplemented from LKDetectorPlane.
Definition at line 19 of file ATTPC20RectanglePad.cpp.
References Draw(), DrawFrame(), GetCanvas(), and GetHist().
Referenced by Draw().
DrawFrame()
void ATTPC20RectanglePad::DrawFrame (Option_t * option = "") virtual
Reimplemented from LKDetectorPlane.
Definition at line 218 of file ATTPC20RectanglePad.cpp.
Referenced by Draw().
FindPadID() [1/2]
Int_t ATTPC20RectanglePad::FindPadID (Double_t i, Double_t j) virtual
Reimplemented from LKPadPlane.
Definition at line 124 of file ATTPC20RectanglePad.cpp.
References LKDetectorPlane::fAxis1, LKDetectorPlane::fAxis2, FindSection(), fNRowsInLayer, fPadGap, fPadHeight, fPadMap, fPadWidth, LKVector3::I(), and LKVector3::J().
FindPadID() [2/2]
Int_t ATTPC20RectanglePad::FindPadID (Int_t section, Int_t row, Int_t layer) virtual
Reimplemented from LKPadPlane.
Definition at line 101 of file ATTPC20RectanglePad.cpp.
References fNRowsInLayer, fNumSections, and fPadMap.
FindSection()
Int_t ATTPC20RectanglePad::FindSection (Double_t i, Double_t j) private
Definition at line 232 of file ATTPC20RectanglePad.cpp.
References fBasePadPos, fPadGap, fPadHeight, and fPadWidth.
Referenced by FindPadID().
GetCanvas()
TCanvas * ATTPC20RectanglePad::GetCanvas (Option_t * option = "") virtual
Implementation recommanded for event display.
Reimplemented from LKDetectorPlane.
Definition at line 222 of file ATTPC20RectanglePad.cpp.
References LKDetectorPlane::fCanvas, and LKDetectorPlane::fPlaneID.
Referenced by Draw().
GetHist()
TH2 * ATTPC20RectanglePad::GetHist (Option_t * option = "") virtual
Reimplemented from LKDetectorPlane.
Definition at line 179 of file ATTPC20RectanglePad.cpp.
References LKVector3::AxisName(), LKDetectorPlane::fAxis1, LKDetectorPlane::fAxis2, LKDetectorPlane::fChannelArray, LKDetectorPlane::fH2Plane, fPadHeight, fPadWidth, and x.
Referenced by Draw().
GetPadGap()
virtual double ATTPC20RectanglePad::GetPadGap () const inline virtual
Definition at line 37 of file ATTPC20RectanglePad.h.
References fPadGap.
Referenced by ATTPC::BuildGeometry(), and ATTPCDetectorConstruction::Construct().
GetPadHeight()
virtual double ATTPC20RectanglePad::GetPadHeight () const inline virtual
Definition at line 36 of file ATTPC20RectanglePad.h.
References fPadHeight.
Referenced by ATTPC::BuildGeometry(), and ATTPCDetectorConstruction::Construct().
GetPadWidth()
virtual double ATTPC20RectanglePad::GetPadWidth () const inline virtual
Definition at line 35 of file ATTPC20RectanglePad.h.
References fPadWidth.
Referenced by ATTPC::BuildGeometry(), and ATTPCDetectorConstruction::Construct().
Init()
bool ATTPC20RectanglePad::Init () virtual
Implementation recommanded. Init() method should implement pad information (id, position, neighbor) and add channel using AddChannel() or AddPad() method. All parameters should be configured such as axis-1,2,3, fPosition, fTbToLength from parameter container.
Reimplemented from LKDetectorPlane.
Definition at line 27 of file ATTPC20RectanglePad.cpp.
References ColumnNum, LKDetectorPlane::fAxis1, LKDetectorPlane::fAxis2, LKDetectorPlane::fChannelArray, fNPadsTotal, fNRowsInLayer, fPadGap, fPadHeight, fPadMap, fPadWidth, LKGear::fPar, LKDetectorPlane::fPlaneID, PadNeighborIndex(), RowNum, and LKDetectorPlane::SetPlaneID().
IsInBoundary()
bool ATTPC20RectanglePad::IsInBoundary (Double_t i, Double_t j) virtual
Definition at line 171 of file ATTPC20RectanglePad.cpp.
References fBasePadPos, fPadGap, fPadHeight, and fPadWidth.
PadDisplacement()
Double_t ATTPC20RectanglePad::PadDisplacement () const virtual
Return average pad displacement to each other.
Reimplemented from LKDetectorPlane.
Definition at line 158 of file ATTPC20RectanglePad.cpp.
References fPadHeight, and fPadWidth.
PadNeighborIndex()
std::vector< Int_t > ATTPC20RectanglePad::PadNeighborIndex (Int_t layer, Int_t Row, Int_t PadID) private
Definition at line 242 of file ATTPC20RectanglePad.cpp.
References RowNum.
Referenced by Init().
Member Data Documentation
ColumnNum
Int_t ATTPC20RectanglePad::ColumnNum = 32 private
Definition at line 46 of file ATTPC20RectanglePad.h.
Referenced by Init().
fBasePadPos
Double_t ATTPC20RectanglePad::fBasePadPos = 200. private
Definition at line 50 of file ATTPC20RectanglePad.h.
Referenced by FindSection(), and IsInBoundary().
fNPadsTotal
Int_t ATTPC20RectanglePad::fNPadsTotal = 0 private
Definition at line 55 of file ATTPC20RectanglePad.h.
Referenced by Init().
fNRowsInLayer
std::vector<Int_t> ATTPC20RectanglePad::fNRowsInLayer[1] private
Definition at line 52 of file ATTPC20RectanglePad.h.
Referenced by FindPadID(), FindPadID(), and Init().
fNumSections
Int_t ATTPC20RectanglePad::fNumSections = 1 private
Definition at line 44 of file ATTPC20RectanglePad.h.
Referenced by FindPadID().
fPadGap
Double_t ATTPC20RectanglePad::fPadGap = 0.5 private
Definition at line 49 of file ATTPC20RectanglePad.h.
Referenced by FindPadID(), FindSection(), GetPadGap(), Init(), and IsInBoundary().
fPadHeight
Double_t ATTPC20RectanglePad::fPadHeight = 5.5 private
Definition at line 48 of file ATTPC20RectanglePad.h.
Referenced by FindPadID(), FindSection(), GetHist(), GetPadHeight(), Init(), IsInBoundary(), and PadDisplacement().
fPadMap
std::map<std::vector<Int_t>, Int_t> ATTPC20RectanglePad::fPadMap private
Definition at line 53 of file ATTPC20RectanglePad.h.
Referenced by FindPadID(), FindPadID(), and Init().
fPadWidth
Double_t ATTPC20RectanglePad::fPadWidth = 5.5 private
Definition at line 47 of file ATTPC20RectanglePad.h.
Referenced by FindPadID(), FindSection(), GetHist(), GetPadWidth(), Init(), IsInBoundary(), and PadDisplacement().
RowNum
Int_t ATTPC20RectanglePad::RowNum = 32 private
Definition at line 45 of file ATTPC20RectanglePad.h.
Referenced by Init(), and PadNeighborIndex().
The documentation for this class was generated from the following files:
ATTPC20RectanglePad.h
ATTPC20RectanglePad.cpp