LILAK: LKChannelBuffer Class Reference
LKChannelBuffer Class Reference
#include <LKChannelBuffer.h>
Public Member Functions
double CalculateGroupFluctuation (int numGroups=8, int tb2=512)
void Clear (Option_t *option="")
virtual void Copy (TObject &obj) const
void Draw (Option_t *option="")
virtual bool DrawByDefault ()
return true if to be displayed on eve.
void FillHist (TH1D *hist)
double * GetBuffer ()
int GetChannelID () const
double GetEnergy () const
void GetGroupMeanStdDev (int numGroups, int tb2, double *pedestalGroup, double *stddevGroup)
TH1D * GetHist (TString name="")
double GetNoiseScale () const
int GetPadID () const
double GetPedestal () const
double GetScale (double *buffer)
double GetTime () const
LKChannelBuffer ()
virtual void Print (Option_t *option="") const
void SetBuffer (double *buffer)
void SetBuffer (int *buffer)
void SetChannelID (int value)
void SetEnergy (double value)
void SetNoiseScale (double value)
void SetPadID (int value)
void SetPedestal (double value)
void SetTime (double value)
void SubtractBuffer (double *buffer)
void SubtractBuffer (double *buffer, double scale)
virtual ~LKChannelBuffer ()
Protected Attributes
int fChannelID = -1
double fEnergy = -1
double fNoiseScale = -1
int fPadID = -1
double fPedestal = -1
double fTime = -1
Private Member Functions
ClassDef (LKChannelBuffer, 1)
Private Attributes
double fBuffer [512]
TH1D * fHist = nullptr
Detailed Description
Definition at line 7 of file LKChannelBuffer.h.
Constructor & Destructor Documentation
LKChannelBuffer()
LKChannelBuffer::LKChannelBuffer ()
Definition at line 5 of file LKChannelBuffer.cpp.
References Clear().
~LKChannelBuffer()
virtual LKChannelBuffer::~LKChannelBuffer () inline virtual
Definition at line 11 of file LKChannelBuffer.h.
Member Function Documentation
CalculateGroupFluctuation()
double LKChannelBuffer::CalculateGroupFluctuation (int numGroups = 8, int tb2 = 512)
Definition at line 81 of file LKChannelBuffer.cpp.
References GetGroupMeanStdDev().
ClassDef()
LKChannelBuffer::ClassDef (LKChannelBuffer , 1) private
Clear()
void LKChannelBuffer::Clear (Option_t * option = "") virtual
Reimplemented from LKChannel.
Definition at line 10 of file LKChannelBuffer.cpp.
References LKChannel::Clear(), fBuffer, LKChannel::fChannelID, LKChannel::fEnergy, LKChannel::fNoiseScale, LKChannel::fPedestal, and LKChannel::fTime.
Referenced by LKChannelBuffer().
Copy()
void LKChannel::Copy (TObject & obj) const virtual inherited
Reimplemented from LKContainer.
Reimplemented in GETChannel.
Definition at line 24 of file LKChannel.cpp.
References LKContainer::Copy(), LKChannel::fChannelID, LKChannel::fEnergy, LKChannel::fNoiseScale, LKChannel::fPadID, LKChannel::fPedestal, and LKChannel::fTime.
Referenced by GETChannel::Copy().
Draw()
void LKChannelBuffer::Draw (Option_t * option = "")
Definition at line 23 of file LKChannelBuffer.cpp.
References Draw(), and GetHist().
Referenced by Draw().
DrawByDefault()
virtual bool LKContainer::DrawByDefault () inline virtual inherited
return true if to be displayed on eve.
Reimplemented in LKHit, and LKTracklet.
Definition at line 18 of file LKContainer.h.
Referenced by LKEveTask::DrawEve3D().
FillHist()
void LKChannelBuffer::FillHist (TH1D * hist)
Definition at line 38 of file LKChannelBuffer.cpp.
References fBuffer.
Referenced by GetHist().
GetBuffer()
double * LKChannelBuffer::GetBuffer () inline
Definition at line 25 of file LKChannelBuffer.h.
References fBuffer.
GetChannelID()
int LKChannel::GetChannelID () const inline inherited
Definition at line 27 of file LKChannel.h.
References LKChannel::fChannelID.
Referenced by LKPad::SetPad().
GetEnergy()
double LKChannel::GetEnergy () const inline inherited
Definition at line 30 of file LKChannel.h.
References LKChannel::fEnergy.
Referenced by LKPad::CopyPadData(), and LKPad::SetPad().
GetGroupMeanStdDev()
void LKChannelBuffer::GetGroupMeanStdDev (int numGroups, int tb2, double * pedestalGroup, double * stddevGroup)
Definition at line 100 of file LKChannelBuffer.cpp.
References fBuffer.
Referenced by CalculateGroupFluctuation().
GetHist()
TH1D * LKChannelBuffer::GetHist (TString name = "")
Definition at line 28 of file LKChannelBuffer.cpp.
References fHist, and FillHist().
Referenced by Draw().
GetNoiseScale()
double LKChannel::GetNoiseScale () const inline inherited
Definition at line 32 of file LKChannel.h.
References LKChannel::fNoiseScale.
Referenced by LKPad::CopyPadData(), and LKPad::SetPad().
GetPadID()
int LKChannel::GetPadID () const inline inherited
Definition at line 28 of file LKChannel.h.
References LKChannel::fPadID.
Referenced by LKDetectorPlane::FillDataToHist(), LKPadPlane::FillDataToHist(), LTPadPlane::FillDataToHist(), LKEvePlane::FillDataToHistEventDisplay1(), LHPadPlaneFan::MapPad(), LKDetectorPlane::PadNeighborChecker(), LKPadPlane::PadNeighborChecker(), and LKPad::SetPad().
GetPedestal()
double LKChannel::GetPedestal () const inline inherited
Definition at line 31 of file LKChannel.h.
References LKChannel::fPedestal.
Referenced by LKPad::CopyPadData(), and LKPad::SetPad().
GetScale()
double LKChannelBuffer::GetScale (double * buffer)
Definition at line 67 of file LKChannelBuffer.cpp.
References fBuffer.
GetTime()
double LKChannel::GetTime () const inline inherited
Definition at line 29 of file LKChannel.h.
References LKChannel::fTime.
Referenced by LKPad::CopyPadData(), and LKPad::SetPad().
Print()
void LKChannel::Print (Option_t * option = "") const virtual inherited
Reimplemented in GETChannel, and LKPad.
Definition at line 36 of file LKChannel.cpp.
References e_info, LKChannel::fChannelID, LKChannel::fEnergy, LKChannel::fNoiseScale, LKChannel::fPadID, LKChannel::fPedestal, and LKChannel::fTime.
Referenced by GETChannel::Print().
SetBuffer() [1/2]
void LKChannelBuffer::SetBuffer (double * buffer)
Definition at line 44 of file LKChannelBuffer.cpp.
References fBuffer.
SetBuffer() [2/2]
void LKChannelBuffer::SetBuffer (int * buffer)
Definition at line 49 of file LKChannelBuffer.cpp.
References fBuffer.
SetChannelID()
void LKChannel::SetChannelID (int value) inline inherited
Definition at line 20 of file LKChannel.h.
References LKChannel::fChannelID.
SetEnergy()
void LKChannel::SetEnergy (double value) inline inherited
Definition at line 23 of file LKChannel.h.
References LKChannel::fEnergy.
SetNoiseScale()
void LKChannel::SetNoiseScale (double value) inline inherited
Definition at line 25 of file LKChannel.h.
References LKChannel::fNoiseScale.
SetPadID()
void LKChannel::SetPadID (int value) inline inherited
Definition at line 21 of file LKChannel.h.
References LKChannel::fPadID.
SetPedestal()
void LKChannel::SetPedestal (double value) inline inherited
Definition at line 24 of file LKChannel.h.
References LKChannel::fPedestal.
SetTime()
void LKChannel::SetTime (double value) inline inherited
Definition at line 22 of file LKChannel.h.
References LKChannel::fTime.
SubtractBuffer() [1/2]
void LKChannelBuffer::SubtractBuffer (double * buffer)
Definition at line 55 of file LKChannelBuffer.cpp.
References fBuffer.
SubtractBuffer() [2/2]
void LKChannelBuffer::SubtractBuffer (double * buffer, double scale)
Definition at line 61 of file LKChannelBuffer.cpp.
References fBuffer.
Member Data Documentation
fBuffer
double LKChannelBuffer::fBuffer[512] private
Definition at line 32 of file LKChannelBuffer.h.
Referenced by Clear(), FillHist(), GetBuffer(), GetGroupMeanStdDev(), GetScale(), SetBuffer(), SetBuffer(), SubtractBuffer(), and SubtractBuffer().
fChannelID
int LKChannel::fChannelID = -1 protected inherited
Definition at line 35 of file LKChannel.h.
Referenced by LKChannel::Clear(), Clear(), LKChannel::Copy(), LKChannel::GetChannelID(), LKPad::GetHist(), LKChannel::Print(), LKChannel::SetChannelID(), LKPad::SetHist(), and LKPad::SetPad().
fEnergy
double LKChannel::fEnergy = -1 protected inherited
Definition at line 38 of file LKChannel.h.
Referenced by LKChannel::Clear(), Clear(), LKChannel::Copy(), LKPad::CopyPadData(), LKChannel::GetEnergy(), GETChannel::GetHitGraph(), LKChannel::Print(), LKChannel::SetEnergy(), and LKPad::SetPad().
fHist
TH1D* LKChannelBuffer::fHist = nullptr private
Definition at line 34 of file LKChannelBuffer.h.
Referenced by GetHist().
fNoiseScale
double LKChannel::fNoiseScale = -1 protected inherited
Definition at line 40 of file LKChannel.h.
Referenced by LKChannel::Clear(), Clear(), LKChannel::Copy(), LKPad::CopyPadData(), LKChannel::GetNoiseScale(), LKChannel::Print(), LKChannel::SetNoiseScale(), and LKPad::SetPad().
fPadID
int LKChannel::fPadID = -1 protected inherited
Definition at line 36 of file LKChannel.h.
Referenced by LKChannel::Clear(), LKChannel::Copy(), LKChannel::GetPadID(), LKChannel::Print(), LKPad::SetPad(), and LKChannel::SetPadID().
fPedestal
double LKChannel::fPedestal = -1 protected inherited
Definition at line 39 of file LKChannel.h.
Referenced by LKChannel::Clear(), Clear(), LKChannel::Copy(), LKPad::CopyPadData(), GETChannel::GetHitGraph(), LKChannel::GetPedestal(), LKChannel::Print(), LKPad::SetPad(), and LKChannel::SetPedestal().
fTime
double LKChannel::fTime = -1 protected inherited
Definition at line 37 of file LKChannel.h.
Referenced by LKChannel::Clear(), Clear(), LKChannel::Copy(), LKPad::CopyPadData(), GETChannel::GetHitGraph(), LKChannel::GetTime(), LKChannel::Print(), LKPad::SetPad(), and LKChannel::SetTime().
The documentation for this class was generated from the following files:
LKChannelBuffer.h
LKChannelBuffer.cpp