lilak: LKContainer Class Reference
LKContainer Class Reference
#include <LKContainer.h>
Public Member Functions
virtual void Clear (Option_t *option="")
virtual TObject * Clone (const char *newname="") const
virtual void Copy (TObject &object) const
virtual bool DrawByDefault ()
return true if to be displayed on eve.
LKContainer ()
virtual ~LKContainer ()
Detailed Description
Definition at line 9 of file LKContainer.h.
Constructor & Destructor Documentation
LKContainer()
LKContainer::LKContainer ()
Definition at line 3 of file LKContainer.cpp.
~LKContainer()
LKContainer::~LKContainer () virtual
Definition at line 7 of file LKContainer.cpp.
Member Function Documentation
Clear()
void LKContainer::Clear (Option_t * option = "") virtual
Reimplemented in LKHoughPointRT, LKImagePoint, LKSiLR, LKEventHeader, LKMCTagged, LKHit, LKMCStep, LKVertex, LKWPoint, GETChannel, LKChannel, LKPad, LKSiChannel, LKSiDetector, LKExtrapolatedTrack, LKHelixTrack, LKLinearTrack, LKMCTrack, LKTracklet, LKImagePoint, SKSiHit, LKSiLR, TTBeamHeader, TTChannelCalibrationData, and TTEventHeader.
Definition at line 11 of file LKContainer.cpp.
Referenced by ClassImp(), LKHoughPointRT::Clear(), LKImagePoint::Clear(), LKSiLR::Clear(), LKEventHeader::Clear(), LKMCTagged::Clear(), LKWPoint::Clear(), LKChannel::Clear(), LKSiDetector::Clear(), TTBeamHeader::Clear(), TTChannelCalibrationData::Clear(), and TTEventHeader::Clear().
Clone()
TObject * LKContainer::Clone (const char * newname = "") const virtual
Reimplemented in GETChannel, LKChannel, LKSiChannel, and LKSiDetector.
Definition at line 21 of file LKContainer.cpp.
Referenced by LKChannel::Clone().
Copy()
void LKContainer::Copy (TObject & object) const virtual
Reimplemented in LKChannel, LKSiLR, LKHoughPointRT, LKImagePoint, LKSiLR, LKEventHeader, LKMCTagged, LKHit, LKVertex, LKWPoint, GETChannel, LKSiChannel, LKSiDetector, LKHelixTrack, LKImagePoint, TTBeamHeader, TTChannelCalibrationData, and TTEventHeader.
Definition at line 16 of file LKContainer.cpp.
Referenced by LKChannel::Copy(), LKHoughPointRT::Copy(), LKImagePoint::Copy(), LKSiLR::Copy(), LKEventHeader::Copy(), LKMCTagged::Copy(), LKHit::Copy(), LKWPoint::Copy(), TTBeamHeader::Copy(), TTChannelCalibrationData::Copy(), and TTEventHeader::Copy().
DrawByDefault()
virtual bool LKContainer::DrawByDefault () inline virtual
return true if to be displayed on eve.
Reimplemented in LKHit, and LKTracklet.
Definition at line 20 of file LKContainer.h.
Referenced by LKEveTask::DrawEve3D().
The documentation for this class was generated from the following files:
LKContainer.h
LKContainer.cpp