LILAK: LTPadPlane Class Reference
LTPadPlane Class Reference
#include <LTPadPlane.h>
Public Member Functions
void Clear (Option_t *option="")
void CreateHistograms ()
void Draw (Option_t *option="")
Implementation recommanded for event display. Draw event display to the canvas.
virtual void DrawFrame (Option_t *option="")
virtual void FillDataToHist ()
Implementation recommanded. Fill data to histograms.
virtual Int_t FindPadID (Double_t i, Double_t j)
Int_t FindPadID (Int_t cobo, Int_t aget, Int_t asad, Int_t chan)
virtual Int_t FindPadID (Int_t section, Int_t layer, Int_t row)
virtual TCanvas * GetCanvas (Option_t *optiont="")
Implementation recommanded for event display.
LKChannelAnalyzer * GetChannelAnalyzer (int i=0)
int GetElectronicsID (int cobo, int aget, int asad, int channelID)
TH2 * GetHist (Int_t selectSection)
virtual TH2 * GetHist (Option_t *option="-1")
Int_t GetNumLayer () const
double GetPadCenterYBoundAtX (double x)
double GetPadCutBoundaryXAtR (double r)
double GetPadCutBoundaryYAtX (double x)
LKPad * GetPadFromEleID (Int_t cobo, Int_t aget, Int_t asad, Int_t chan)
Double_t GetPadGap () const
Double_t GetPadHeight () const
Double_t GetPadRSpacing () const
Double_t GetPadWidth () const
Double_t GetPadXSpacing () const
Double_t GetRMax () const
Double_t GetRMin () const
void GetSectionParameters (Int_t section, Double_t &t1, Double_t &t2, Double_t &xmin, Double_t &xmax, Double_t &ymin, Double_t &ymax)
virtual bool Init ()
virtual bool IsInBoundary (Double_t i, Double_t j)
LTPadPlane ()
virtual Double_t PadDisplacement () const
Return average pad displacement to each other.
void SelectAndDrawChannel (Int_t bin, Double_t x, Double_t y)
virtual bool SetDataFromBranch ()
Implementation recommanded. Set waveform and hit data from input tree branches to pads.
void ZoomInWindow (Int_t bin, Double_t x, Double_t y)
virtual ~LTPadPlane ()
Public Member Functions inherited from LKDetectorPlane
void AddChannel (LKChannel *channel)
Add channel to channel array in detector plane. For interanl use.
void AddHit (LKHit *hit)
void AddPad (LKPad *pad)
Add pad to pad array in detector plane. For interanl use.
virtual void Clear (Option_t *option="")
virtual void Draw (Option_t *option="")
Implementation recommanded for event display. Draw event display to the canvas.
virtual void DrawFrame (Option_t *option="")
virtual void DrawHist ()
virtual void DriftElectron (TVector3 posGlobal, TVector3 &posFinal, double &driftLength)
virtual void DriftElectronBack (LKPad *pad, double tb, TVector3 &posReco, double &driftLength)
void FillBufferIn (double i, double j, double tb, double charge, int trackID=-1)
Find pad corresponding to the position (i,j) and fill time-bin by amount of charge.
virtual void FillDataToHist ()
Implementation recommanded. Fill data to histograms.
virtual int FindChannelID (double i, double j)
Implementation recommanded. Find channel using position.
virtual int FindChannelID (int section, int layer, int row)
Implementation recommanded. Find channel using section, layer, row info.
virtual int FindPadID (double i, double j)
virtual int FindPadID (int cobo, int aget, int asad, int chan)
virtual int FindPadID (int section, int layer, int row)
axis_t GetAxis1 () const
axis_t GetAxis2 () const
axis_t GetAxis3 () const
axis_t GetAxisDrift () const
virtual TCanvas * GetCanvas (Option_t *option="")
Implementation recommanded for event display.
LKChannel * GetChannel (int idx)
virtual LKChannelAnalyzer * GetChannelAnalyzer (int id=0)
TObjArray * GetChannelArray ()
LKChannel * GetChannelFast (int idx)
virtual TPad * GetCPad (int iPad)
For grabbing inner pads of canvas.
virtual TH2 * GetHist (Option_t *option="-1")
int GetNChannels ()
virtual int GetNumCPads ()
Get number of inner pads of canvas.
int GetNumPads ()
LKPad * GetPad (double i, double j)
LKPad * GetPad (int padID)
LKPad * GetPad (int section, int layer, int row)
TObjArray * GetPadArray ()
LKPad * GetPadFast (int idx)
int GetPlaneID () const
double GetPosition () const
double GetTbToLength () const
virtual TVector3 GlobalToLocalAxis (TVector3 posGlobal)
Implementation recommanded. Convert global position to local detector plane position.
void GrabNeighborPads (vector< LKPad * > *pads, vector< LKPad * > *neighborPads)
For tracking use.
virtual bool Init ()
virtual bool IsInBoundary (double i, double j)
Implementation recommanded. Return if position (i,j) is inside the effective detector plane boundary.
LKDetectorPlane ()
LKDetectorPlane (const char *name, const char *title)
virtual TVector3 LocalToGlobalAxis (TVector3 posLocal)
virtual double PadDisplacement () const
Return average pad displacement to each other.
bool PadMapChecker ()
bool PadNeighborChecker ()
bool PadPositionChecker (bool checkCorners=true)
virtual void Print (Option_t *option="") const
void PullOutNeighborHits (double x, double y, int range, LKHitArray *neighborHits)
For tracking use.
void PullOutNeighborHits (double x, double y, int range, vector< LKHit * > *neighborHits)
For tracking use.
void PullOutNeighborHits (LKHitArray *hits, LKHitArray *neighborHits)
For tracking use.
void PullOutNeighborHits (TVector2 p, int range, vector< LKHit * > *neighborHits)
For tracking use.
void PullOutNeighborHits (vector< LKHit * > *hits, vector< LKHit * > *neighborHits)
For tracking use.
virtual LKHit * PullOutNextFreeHit ()
For tracking use.
virtual void ResetEvent ()
For tracking use.
virtual void ResetHitMap ()
For tracking use.
virtual bool SetDataFromBranch ()
Implementation recommanded. Set waveform and hit data from input tree branches to pads.
void SetDetector (LKDetector *detector)
void SetHitArray (TClonesArray *hitArray)
void SetPadArray (TClonesArray *padArray)
void SetPlaneID (int id)
virtual ~LKDetectorPlane ()
Public Member Functions inherited from LKGear
void AddPar (LKParameterContainer *par)
void AddPar (TString fname)
virtual void AddParameterContainer (LKParameterContainer *par)
virtual void AddParameterContainer (TString fname)
void CreateParameterContainer ()
LKParameterContainer * GetPar () const
LKParameterContainer * GetParameterContainer () const
Int_t GetRank () const
LKGear ()
void SetPar (LKParameterContainer *par)
virtual void SetParameterContainer (LKParameterContainer *par)
virtual void SetRank (Int_t rank)
void SetRun (LKRun *run)
virtual ~LKGear ()
Static Public Member Functions
static LTPadPlane * GetPlane ()
static void MouseClickEvent1 ()
static void MouseClickEvent2 ()
Static Public Attributes
static LTPadPlane * fInstance
Private Member Functions
int ConvHP (int bin)
int ConvPH (int bin)
Int_t FindSection (Double_t i, Double_t j)
LKPad * NewPad (Int_t section, Int_t layer, Int_t row)
void SetNeighborPads (LKPad *pad0, LKPad *pad1)
Private Attributes
Int_t fBinNumberSideView
Int_t fBinNumberTopView
TClonesArray * fBufferArray = nullptr
LKChannelAnalyzer * fChannelAnalyzer = nullptr
Double_t fCosPiNo4 [8]
Double_t fDCX = -1.5
Displacement of pad cut line in x-axis.
const Bool_t fDoCutSideBoundary = true
const Bool_t fDoCutTopBoundary = true
TString fFillType = "Buffer"
TH2Poly * fFramePadPlane = nullptr
TF1 * fFuncXRightBound = nullptr
TF1 * fFuncXRightBoundInverse = nullptr
TGraph * fGraphPadBoundary = nullptr
TGraph * fGraphPadBoundaryNb [10]
TGraph * fGraphSectionBoundary1 = nullptr
TGraph * fGraphSectionBoundary2 = nullptr
TH1D * fHistChannel1 = nullptr
TH1D * fHistChannel2 = nullptr
TH2Poly * fHistPadPlane = nullptr
TH2Poly * fHistPadPlaneSection [8]
TH2D * fHistSideView = nullptr
TH2D * fHistTopView = nullptr
TH2D * fHistWaveform = nullptr
Double_t fHistZMin = 0.1
TClonesArray * fHitArray = nullptr
int **** fMapCAACToPadID
int **** fMapSLRPToPadID
Int_t fMaxWaveformY = 4100
int fNumHalfRowsInLayer [50] = {0}
int fNumHalfRowsInLayerInput [42] = {12,13,14,16,17,18,19,20,21,22,24,25,26,27,28,29,31,32,33,34,35,36,37,39,40,41,42,43,44,45,47,48,49,50,51,52,53,55,40,23,13,5}
Int_t fNumLayers = 42
int fNumPadsDownToLayer [50] = {0}
in single section
int fNumSkippedHalfRows [50] = {0}
Int_t fNumTbs = 512
Double_t fPadGap = 0.0
Double_t fPadHeight = 10.5
Double_t fPadWidth = 3.5
TVector2 fPosSectionCorner [8][4]
Double_t fRadiusLayer0 = fRMin + 0.5*fPadHeight
Double_t fRMax = 545-41.5
Double_t fRMin = 105.
Double_t fRSpacing
Double_t fRTopCut = fRMax
LKPad * fSelectedPad = nullptr
int fSelectedSection = 0
Double_t fSinPiNo4 [8]
int fStartRowFrom [42] = {0}
Double_t fTanPi1o8
Double_t fTanPi3o8
Double_t fTanPi5o8
Double_t fTanPi7o8
bool fUseChannel1 = true
Double_t fXMax = +550
Double_t fXMin = -550
Double_t fXSpacing
Double_t fYMax = +550
Double_t fYMin = -550
Int_t fZBins = 512
Double_t fZMax = 1350
Double_t fZMin = -350
Additional Inherited Members
Protected Attributes inherited from LKDetectorPlane
axis_t fAxis1 = LKVector3::kNon
Axis-1 lying in plane. Must be set by input parameter.
axis_t fAxis2 = LKVector3::kNon
Axis-2 lying in plane. Must be set by input parameter.
axis_t fAxis3 = LKVector3::kNon
Axis-3 = Axis-1 x Axis-2 perpendicular to plane.
axis_t fAxisDrift = LKVector3::kNon
Axis perpendicular to plane, in electron drifting direction. Must be set by input parameter.
TCanvas * fCanvas = nullptr
LKChannelAnalyzer * fChannelAnalyzer = nullptr
TObjArray * fChannelArray = nullptr
TCanvas * fCvsChannelBuffer = nullptr
LKDetector * fDetector = nullptr
int fFreePadIdx = 0
TGraph * fGraphChannelBoundary = nullptr
TGraph * fGraphChannelBoundaryNb [20] = {0}
TH2 * fH2Plane = nullptr
bool fHitDataIsSet = false
bool fPadDataIsSet = false
int fPlaneID = -1
Detector plane id.
double fPosition
Global position of pad plane center.
double fTbToLength = 1
time-bin (tb) to position conversion factor. Must be set by input parameter.
Protected Attributes inherited from LKGear
LKParameterContainer * fPar = nullptr
Int_t fRank = 0
LKRun * fRun = nullptr
Detailed Description
Definition at line 8 of file LTPadPlane.h.
Constructor & Destructor Documentation
LTPadPlane()
LTPadPlane::LTPadPlane ()
Definition at line 25 of file LTPadPlane.cpp.
References LKDetectorPlane::fAxis1, LKDetectorPlane::fAxis2, fInstance, LKVector3::kX, and LKVector3::kY.
~LTPadPlane()
virtual LTPadPlane::~LTPadPlane () inline virtual
Definition at line 12 of file LTPadPlane.h.
Member Function Documentation
Clear()
void LTPadPlane::Clear (Option_t * option = "") virtual
Reimplemented from LKDetectorPlane.
Definition at line 703 of file LTPadPlane.cpp.
References LKDetectorPlane::Clear(), fHistPadPlane, fHistPadPlaneSection, fHistSideView, and fHistTopView.
Referenced by FillDataToHist().
ConvHP()
int LTPadPlane::ConvHP (int bin) inline private
Definition at line 143 of file LTPadPlane.h.
ConvPH()
int LTPadPlane::ConvPH (int bin) inline private
Definition at line 144 of file LTPadPlane.h.
CreateHistograms()
void LTPadPlane::CreateHistograms ()
Definition at line 472 of file LTPadPlane.cpp.
References fBinNumberSideView, fBinNumberTopView, LKDetectorPlane::fChannelArray, fFramePadPlane, fGraphPadBoundary, fGraphPadBoundaryNb, fGraphSectionBoundary1, fGraphSectionBoundary2, fHistChannel1, fHistChannel2, fHistPadPlane, fHistPadPlaneSection, fHistSideView, fHistTopView, fHistWaveform, fHistZMin, fMaxWaveformY, fNumLayers, fNumTbs, LKGear::fPar, fPosSectionCorner, fXMax, fXMin, fYMax, fYMin, fZBins, fZMax, fZMin, GetSectionParameters(), t1, and t2.
Referenced by Draw(), GetHist(), and GetHist().
Draw()
void LTPadPlane::Draw (Option_t * option = "") virtual
Implementation recommanded for event display. Draw event display to the canvas.
Reimplemented from LKDetectorPlane.
Definition at line 888 of file LTPadPlane.cpp.
References CreateHistograms(), cvs, Draw(), fFramePadPlane, fHistPadPlane, fHistPadPlaneSection, fHistSideView, fHistWaveform, fHistZMin, FillDataToHist(), LKGear::fPar, fSelectedSection, and GetCanvas().
Referenced by Draw(), GetCanvas(), SelectAndDrawChannel(), and ZoomInWindow().
DrawFrame()
void LTPadPlane::DrawFrame (Option_t * option = "") virtual
Reimplemented from LKDetectorPlane.
Definition at line 621 of file LTPadPlane.cpp.
FillDataToHist()
void LTPadPlane::FillDataToHist () virtual
Implementation recommanded. Fill data to histograms.
Reimplemented from LKDetectorPlane.
Definition at line 719 of file LTPadPlane.cpp.
References LKDetectorPlane::AddHit(), Clear(), fBufferArray, fFillType, fHistPadPlane, fHistPadPlaneSection, fHistSideView, fHistTopView, fHistWaveform, fHitArray, FindPadID(), fNumTbs, LKGear::fPar, LKDetectorPlane::GetPad(), iChannel, lk_error, lk_info, and lk_warning.
Referenced by Draw().
FindPadID() [1/3]
Int_t LTPadPlane::FindPadID (Double_t i, Double_t j) virtual
Definition at line 390 of file LTPadPlane.cpp.
References fCosPiNo4, FindPadID(), FindSection(), fNumHalfRowsInLayer, fNumLayers, fNumSkippedHalfRows, fPadGap, fPadHeight, fPadWidth, fRadiusLayer0, fRSpacing, fSinPiNo4, and fXSpacing.
Referenced by FillDataToHist(), FindPadID(), GetPadFromEleID(), and Init().
FindPadID() [2/3]
Int_t LTPadPlane::FindPadID (Int_t cobo, Int_t aget, Int_t asad, Int_t chan)
Definition at line 383 of file LTPadPlane.cpp.
References fMapCAACToPadID.
FindPadID() [3/3]
Int_t LTPadPlane::FindPadID (Int_t section, Int_t layer, Int_t row) virtual
Definition at line 373 of file LTPadPlane.cpp.
References fNumHalfRowsInLayer, fNumLayers, and fNumPadsDownToLayer.
FindSection()
Int_t LTPadPlane::FindSection (Double_t i, Double_t j) private
Definition at line 671 of file LTPadPlane.cpp.
References fTanPi1o8, fTanPi3o8, fTanPi5o8, and fTanPi7o8.
Referenced by FindPadID(), and ZoomInWindow().
GetCanvas()
TCanvas * LTPadPlane::GetCanvas (Option_t * option = "") virtual
Implementation recommanded for event display.
Reimplemented from LKDetectorPlane.
Definition at line 625 of file LTPadPlane.cpp.
References Draw(), LKDetectorPlane::fCanvas, and LKWindowManager::GetWindowManager().
Referenced by Draw(), MouseClickEvent1(), MouseClickEvent2(), SelectAndDrawChannel(), and ZoomInWindow().
GetChannelAnalyzer()
LKChannelAnalyzer * LTPadPlane::GetChannelAnalyzer (int i = 0) virtual
Reimplemented from LKDetectorPlane.
Definition at line 1146 of file LTPadPlane.cpp.
References LKParameterContainer::CheckPar(), fChannelAnalyzer, LKGear::fPar, and LKDetectorPlane::Print().
Referenced by Init().
GetElectronicsID()
int LTPadPlane::GetElectronicsID (int cobo, int aget, int asad, int channelID) inline
Definition at line 35 of file LTPadPlane.h.
Referenced by Init().
GetHist() [1/2]
TH2 * LTPadPlane::GetHist (Int_t selectSection)
Definition at line 612 of file LTPadPlane.cpp.
References CreateHistograms(), fHistPadPlane, and fHistPadPlaneSection.
GetHist() [2/2]
TH2 * LTPadPlane::GetHist (Option_t * option = "-1") virtual
Reimplemented from LKDetectorPlane.
Definition at line 601 of file LTPadPlane.cpp.
References CreateHistograms(), and GetHist().
Referenced by GetHist().
GetNumLayer()
Int_t LTPadPlane::GetNumLayer () const inline
Definition at line 158 of file LTPadPlane.h.
References fNumLayers.
GetPadCenterYBoundAtX()
double LTPadPlane::GetPadCenterYBoundAtX (double x) inline
Definition at line 151 of file LTPadPlane.h.
References fTanPi3o8.
GetPadCutBoundaryXAtR()
double LTPadPlane::GetPadCutBoundaryXAtR (double r) inline
Definition at line 150 of file LTPadPlane.h.
References fDCX, and fTanPi3o8.
Referenced by Init().
GetPadCutBoundaryYAtX()
double LTPadPlane::GetPadCutBoundaryYAtX (double x) inline
Definition at line 149 of file LTPadPlane.h.
References fDCX, and fTanPi3o8.
Referenced by Init().
GetPadFromEleID()
LKPad * LTPadPlane::GetPadFromEleID (Int_t cobo, Int_t aget, Int_t asad, Int_t chan)
Definition at line 428 of file LTPadPlane.cpp.
References FindPadID(), and LKDetectorPlane::GetPad().
GetPadGap()
Double_t LTPadPlane::GetPadGap () const inline
Definition at line 155 of file LTPadPlane.h.
References fPadGap.
GetPadHeight()
Double_t LTPadPlane::GetPadHeight () const inline
Definition at line 157 of file LTPadPlane.h.
References fPadHeight.
GetPadRSpacing()
Double_t LTPadPlane::GetPadRSpacing () const inline
Definition at line 160 of file LTPadPlane.h.
References fRSpacing.
GetPadWidth()
Double_t LTPadPlane::GetPadWidth () const inline
Definition at line 156 of file LTPadPlane.h.
References fPadWidth.
GetPadXSpacing()
Double_t LTPadPlane::GetPadXSpacing () const inline
Definition at line 159 of file LTPadPlane.h.
References fXSpacing.
GetPlane()
static LTPadPlane * LTPadPlane::GetPlane () static
Referenced by MouseClickEvent1(), and MouseClickEvent2().
GetRMax()
Double_t LTPadPlane::GetRMax () const inline
Definition at line 154 of file LTPadPlane.h.
References fRMax.
GetRMin()
Double_t LTPadPlane::GetRMin () const inline
Definition at line 153 of file LTPadPlane.h.
References fRMin.
GetSectionParameters()
void LTPadPlane::GetSectionParameters (Int_t section, Double_t & t1, Double_t & t2, Double_t & xmin, Double_t & xmax, Double_t & ymin, Double_t & ymax)
Definition at line 451 of file LTPadPlane.cpp.
References fPosSectionCorner, and y2.
Referenced by CreateHistograms(), and ZoomInWindow().
Init()
bool LTPadPlane::Init () virtual
Implementation recommanded. Init() method should implement pad information (id, position, neighbor) and add channel using AddChannel() or AddPad() method. All parameters should be configured such as axis-1,2,3, fPosition, fTbToLength from parameter container.
Reimplemented from LKDetectorPlane.
Definition at line 34 of file LTPadPlane.cpp.
References LKDetectorPlane::fAxis1, LKDetectorPlane::fAxis2, LKDetectorPlane::fAxis3, LKDetectorPlane::fAxisDrift, fChannelAnalyzer, LKDetectorPlane::fChannelArray, fCosPiNo4, fDoCutSideBoundary, fDoCutTopBoundary, FindPadID(), fMapCAACToPadID, fMapSLRPToPadID, fNumHalfRowsInLayer, fNumHalfRowsInLayerInput, fNumLayers, fNumPadsDownToLayer, fNumSkippedHalfRows, fPadGap, fPadHeight, fPadWidth, LKGear::fPar, LKDetectorPlane::fPosition, fPosSectionCorner, fRadiusLayer0, fRMax, fRMin, fRSpacing, fRTopCut, fSinPiNo4, fStartRowFrom, fTanPi1o8, fTanPi3o8, fTanPi5o8, fTanPi7o8, LKDetectorPlane::fTbToLength, fXSpacing, GetChannelAnalyzer(), GetElectronicsID(), LKDetectorPlane::GetPad(), GetPadCutBoundaryXAtR(), GetPadCutBoundaryYAtX(), LKVector3::kX, LKVector3::kY, LKVector3::kZ, lk_info, NewPad(), SetDataFromBranch(), SetNeighborPads(), and y2.
IsInBoundary()
bool LTPadPlane::IsInBoundary (Double_t i, Double_t j) virtual
Definition at line 442 of file LTPadPlane.cpp.
References fRMax.
MouseClickEvent1()
void LTPadPlane::MouseClickEvent1 () static
Definition at line 928 of file LTPadPlane.cpp.
References GetCanvas(), GetPlane(), and ZoomInWindow().
MouseClickEvent2()
void LTPadPlane::MouseClickEvent2 () static
Definition at line 970 of file LTPadPlane.cpp.
References GetCanvas(), GetPlane(), and SelectAndDrawChannel().
NewPad()
LKPad * LTPadPlane::NewPad (Int_t section, Int_t layer, Int_t row) private
Definition at line 655 of file LTPadPlane.cpp.
References LKDetectorPlane::fChannelArray.
Referenced by Init().
PadDisplacement()
Double_t LTPadPlane::PadDisplacement () const virtual
Return average pad displacement to each other.
Reimplemented from LKDetectorPlane.
Definition at line 437 of file LTPadPlane.cpp.
References fRSpacing, and fXSpacing.
SelectAndDrawChannel()
void LTPadPlane::SelectAndDrawChannel (Int_t bin, Double_t x, Double_t y)
Definition at line 1068 of file LTPadPlane.cpp.
References Draw(), fChannelAnalyzer, fGraphPadBoundary, fGraphPadBoundaryNb, fHistChannel1, fHistChannel2, fHistPadPlane, fNumTbs, fSelectedPad, fUseChannel1, GetCanvas(), LKPad::GetI(), LKPad::GetJ(), LKDetectorPlane::GetPad(), lk_error, LKDetectorPlane::Print(), SetPoint(), x0, z0, z1, and z2.
Referenced by MouseClickEvent2().
SetDataFromBranch()
bool LTPadPlane::SetDataFromBranch () virtual
Implementation recommanded. Set waveform and hit data from input tree branches to pads.
Reimplemented from LKDetectorPlane.
Definition at line 694 of file LTPadPlane.cpp.
References fBufferArray, fHitArray, and LKGear::fRun.
Referenced by Init().
SetNeighborPads()
void LTPadPlane::SetNeighborPads (LKPad * pad0, LKPad * pad1) private
Definition at line 665 of file LTPadPlane.cpp.
Referenced by Init().
ZoomInWindow()
void LTPadPlane::ZoomInWindow (Int_t bin, Double_t x, Double_t y)
Definition at line 1012 of file LTPadPlane.cpp.
References cvs, Draw(), fBinNumberSideView, fBinNumberTopView, fGraphSectionBoundary1, fGraphSectionBoundary2, fHistPadPlaneSection, fHistSideView, fHistTopView, fHistZMin, FindSection(), LKGear::fPar, fPosSectionCorner, fSelectedSection, fXMax, fXMin, fYMax, fYMin, GetCanvas(), GetSectionParameters(), SetPoint(), t1, and t2.
Referenced by MouseClickEvent1().
Member Data Documentation
fBinNumberSideView
Int_t LTPadPlane::fBinNumberSideView private
Definition at line 92 of file LTPadPlane.h.
Referenced by CreateHistograms(), and ZoomInWindow().
fBinNumberTopView
Int_t LTPadPlane::fBinNumberTopView private
Definition at line 91 of file LTPadPlane.h.
Referenced by CreateHistograms(), and ZoomInWindow().
fBufferArray
TClonesArray* LTPadPlane::fBufferArray = nullptr private
Definition at line 136 of file LTPadPlane.h.
Referenced by FillDataToHist(), and SetDataFromBranch().
fChannelAnalyzer
LKChannelAnalyzer* LTPadPlane::fChannelAnalyzer = nullptr private
Definition at line 146 of file LTPadPlane.h.
Referenced by GetChannelAnalyzer(), Init(), and SelectAndDrawChannel().
fCosPiNo4
Double_t LTPadPlane::fCosPiNo4[8] private
Definition at line 98 of file LTPadPlane.h.
Referenced by FindPadID(), and Init().
fDCX
Double_t LTPadPlane::fDCX = -1.5 private
Displacement of pad cut line in x-axis.
Definition at line 109 of file LTPadPlane.h.
Referenced by GetPadCutBoundaryXAtR(), and GetPadCutBoundaryYAtX().
fDoCutSideBoundary
const Bool_t LTPadPlane::fDoCutSideBoundary = true private
Definition at line 113 of file LTPadPlane.h.
Referenced by Init().
fDoCutTopBoundary
const Bool_t LTPadPlane::fDoCutTopBoundary = true private
Definition at line 112 of file LTPadPlane.h.
Referenced by Init().
fFillType
TString LTPadPlane::fFillType = "Buffer" private
Definition at line 139 of file LTPadPlane.h.
Referenced by FillDataToHist().
fFramePadPlane
TH2Poly* LTPadPlane::fFramePadPlane = nullptr private
Definition at line 121 of file LTPadPlane.h.
Referenced by CreateHistograms(), and Draw().
fFuncXRightBound
TF1* LTPadPlane::fFuncXRightBound = nullptr private
Definition at line 59 of file LTPadPlane.h.
fFuncXRightBoundInverse
TF1* LTPadPlane::fFuncXRightBoundInverse = nullptr private
Definition at line 60 of file LTPadPlane.h.
fGraphPadBoundary
TGraph* LTPadPlane::fGraphPadBoundary = nullptr private
Definition at line 131 of file LTPadPlane.h.
Referenced by CreateHistograms(), and SelectAndDrawChannel().
fGraphPadBoundaryNb
TGraph* LTPadPlane::fGraphPadBoundaryNb[10] private
Definition at line 132 of file LTPadPlane.h.
Referenced by CreateHistograms(), and SelectAndDrawChannel().
fGraphSectionBoundary1
TGraph* LTPadPlane::fGraphSectionBoundary1 = nullptr private
Definition at line 129 of file LTPadPlane.h.
Referenced by CreateHistograms(), and ZoomInWindow().
fGraphSectionBoundary2
TGraph* LTPadPlane::fGraphSectionBoundary2 = nullptr private
Definition at line 130 of file LTPadPlane.h.
Referenced by CreateHistograms(), and ZoomInWindow().
fHistChannel1
TH1D* LTPadPlane::fHistChannel1 = nullptr private
Definition at line 127 of file LTPadPlane.h.
Referenced by CreateHistograms(), and SelectAndDrawChannel().
fHistChannel2
TH1D* LTPadPlane::fHistChannel2 = nullptr private
Definition at line 128 of file LTPadPlane.h.
Referenced by CreateHistograms(), and SelectAndDrawChannel().
fHistPadPlane
TH2Poly* LTPadPlane::fHistPadPlane = nullptr private
Definition at line 122 of file LTPadPlane.h.
Referenced by Clear(), CreateHistograms(), Draw(), FillDataToHist(), GetHist(), and SelectAndDrawChannel().
fHistPadPlaneSection
TH2Poly* LTPadPlane::fHistPadPlaneSection[8] private
Definition at line 120 of file LTPadPlane.h.
Referenced by Clear(), CreateHistograms(), Draw(), FillDataToHist(), GetHist(), and ZoomInWindow().
fHistSideView
TH2D* LTPadPlane::fHistSideView = nullptr private
Definition at line 126 of file LTPadPlane.h.
Referenced by Clear(), CreateHistograms(), Draw(), FillDataToHist(), and ZoomInWindow().
fHistTopView
TH2D* LTPadPlane::fHistTopView = nullptr private
Definition at line 125 of file LTPadPlane.h.
Referenced by Clear(), CreateHistograms(), FillDataToHist(), and ZoomInWindow().
fHistWaveform
TH2D* LTPadPlane::fHistWaveform = nullptr private
Definition at line 124 of file LTPadPlane.h.
Referenced by CreateHistograms(), Draw(), and FillDataToHist().
fHistZMin
Double_t LTPadPlane::fHistZMin = 0.1 private
Definition at line 70 of file LTPadPlane.h.
Referenced by CreateHistograms(), Draw(), and ZoomInWindow().
fHitArray
TClonesArray* LTPadPlane::fHitArray = nullptr private
Definition at line 137 of file LTPadPlane.h.
Referenced by FillDataToHist(), and SetDataFromBranch().
fInstance
LTPadPlane* LTPadPlane::fInstance static
Definition at line 14 of file LTPadPlane.h.
Referenced by LTPadPlane().
fMapCAACToPadID
int**** LTPadPlane::fMapCAACToPadID private
Definition at line 115 of file LTPadPlane.h.
Referenced by FindPadID(), and Init().
fMapSLRPToPadID
int**** LTPadPlane::fMapSLRPToPadID private
Definition at line 116 of file LTPadPlane.h.
Referenced by Init().
fMaxWaveformY
Int_t LTPadPlane::fMaxWaveformY = 4100 private
Definition at line 89 of file LTPadPlane.h.
Referenced by CreateHistograms().
fNumHalfRowsInLayer
int LTPadPlane::fNumHalfRowsInLayer[50] = {0} private
Definition at line 103 of file LTPadPlane.h.
Referenced by FindPadID(), FindPadID(), and Init().
fNumHalfRowsInLayerInput
int LTPadPlane::fNumHalfRowsInLayerInput[42] = {12,13,14,16,17,18,19,20,21,22,24,25,26,27,28,29,31,32,33,34,35,36,37,39,40,41,42,43,44,45,47,48,49,50,51,52,53,55,40,23,13,5} private
Definition at line 102 of file LTPadPlane.h.
Referenced by Init().
fNumLayers
Int_t LTPadPlane::fNumLayers = 42 private
Definition at line 86 of file LTPadPlane.h.
Referenced by CreateHistograms(), FindPadID(), FindPadID(), GetNumLayer(), and Init().
fNumPadsDownToLayer
int LTPadPlane::fNumPadsDownToLayer[50] = {0} private
in single section
Definition at line 104 of file LTPadPlane.h.
Referenced by FindPadID(), and Init().
fNumSkippedHalfRows
int LTPadPlane::fNumSkippedHalfRows[50] = {0} private
Definition at line 105 of file LTPadPlane.h.
Referenced by FindPadID(), and Init().
fNumTbs
Int_t LTPadPlane::fNumTbs = 512 private
Definition at line 88 of file LTPadPlane.h.
Referenced by CreateHistograms(), FillDataToHist(), and SelectAndDrawChannel().
fPadGap
Double_t LTPadPlane::fPadGap = 0.0 private
Definition at line 81 of file LTPadPlane.h.
Referenced by FindPadID(), GetPadGap(), and Init().
fPadHeight
Double_t LTPadPlane::fPadHeight = 10.5 private
Definition at line 83 of file LTPadPlane.h.
Referenced by FindPadID(), GetPadHeight(), and Init().
fPadWidth
Double_t LTPadPlane::fPadWidth = 3.5 private
Definition at line 82 of file LTPadPlane.h.
Referenced by FindPadID(), GetPadWidth(), and Init().
fPosSectionCorner
TVector2 LTPadPlane::fPosSectionCorner[8][4] private
Definition at line 72 of file LTPadPlane.h.
Referenced by CreateHistograms(), GetSectionParameters(), Init(), and ZoomInWindow().
fRadiusLayer0
Double_t LTPadPlane::fRadiusLayer0 = fRMin + 0.5*fPadHeight private
Definition at line 84 of file LTPadPlane.h.
Referenced by FindPadID(), and Init().
fRMax
Double_t LTPadPlane::fRMax = 545-41.5 private
Definition at line 75 of file LTPadPlane.h.
Referenced by GetRMax(), Init(), and IsInBoundary().
fRMin
Double_t LTPadPlane::fRMin = 105. private
Definition at line 74 of file LTPadPlane.h.
Referenced by GetRMin(), and Init().
fRSpacing
Double_t LTPadPlane::fRSpacing private
Definition at line 108 of file LTPadPlane.h.
Referenced by FindPadID(), GetPadRSpacing(), Init(), and PadDisplacement().
fRTopCut
Double_t LTPadPlane::fRTopCut = fRMax private
Definition at line 85 of file LTPadPlane.h.
Referenced by Init().
fSelectedPad
LKPad* LTPadPlane::fSelectedPad = nullptr private
Definition at line 141 of file LTPadPlane.h.
Referenced by SelectAndDrawChannel().
fSelectedSection
int LTPadPlane::fSelectedSection = 0 private
Definition at line 118 of file LTPadPlane.h.
Referenced by Draw(), and ZoomInWindow().
fSinPiNo4
Double_t LTPadPlane::fSinPiNo4[8] private
Definition at line 99 of file LTPadPlane.h.
Referenced by FindPadID(), and Init().
fStartRowFrom
int LTPadPlane::fStartRowFrom[42] = {0} private
Definition at line 101 of file LTPadPlane.h.
Referenced by Init().
fTanPi1o8
Double_t LTPadPlane::fTanPi1o8 private
Definition at line 94 of file LTPadPlane.h.
Referenced by FindSection(), and Init().
fTanPi3o8
Double_t LTPadPlane::fTanPi3o8 private
Definition at line 95 of file LTPadPlane.h.
Referenced by FindSection(), GetPadCenterYBoundAtX(), GetPadCutBoundaryXAtR(), GetPadCutBoundaryYAtX(), and Init().
fTanPi5o8
Double_t LTPadPlane::fTanPi5o8 private
Definition at line 96 of file LTPadPlane.h.
Referenced by FindSection(), and Init().
fTanPi7o8
Double_t LTPadPlane::fTanPi7o8 private
Definition at line 97 of file LTPadPlane.h.
Referenced by FindSection(), and Init().
fUseChannel1
bool LTPadPlane::fUseChannel1 = true private
Definition at line 134 of file LTPadPlane.h.
Referenced by SelectAndDrawChannel().
fXMax
Double_t LTPadPlane::fXMax = +550 private
Definition at line 63 of file LTPadPlane.h.
Referenced by CreateHistograms(), and ZoomInWindow().
fXMin
Double_t LTPadPlane::fXMin = -550 private
Definition at line 62 of file LTPadPlane.h.
Referenced by CreateHistograms(), and ZoomInWindow().
fXSpacing
Double_t LTPadPlane::fXSpacing private
Definition at line 107 of file LTPadPlane.h.
Referenced by FindPadID(), GetPadXSpacing(), Init(), and PadDisplacement().
fYMax
Double_t LTPadPlane::fYMax = +550 private
Definition at line 65 of file LTPadPlane.h.
Referenced by CreateHistograms(), and ZoomInWindow().
fYMin
Double_t LTPadPlane::fYMin = -550 private
Definition at line 64 of file LTPadPlane.h.
Referenced by CreateHistograms(), and ZoomInWindow().
fZBins
Int_t LTPadPlane::fZBins = 512 private
Definition at line 68 of file LTPadPlane.h.
Referenced by CreateHistograms().
fZMax
Double_t LTPadPlane::fZMax = 1350 private
Definition at line 67 of file LTPadPlane.h.
Referenced by CreateHistograms().
fZMin
Double_t LTPadPlane::fZMin = -350 private
Definition at line 66 of file LTPadPlane.h.
Referenced by CreateHistograms().
The documentation for this class was generated from the following files:
LTPadPlane.h
LTPadPlane.cpp