lilak: Json::StyledStreamWriter Class Reference
Json::StyledStreamWriter Class Reference
Writes a Value in JSON format in a human friendly way, to a stream rather than to a string.
#include <json.h>
Public Member Functions
StyledStreamWriter (String indentation="\t")
void write (OStream &out, const Value &root)
Serialize a Value in JSON format.
~StyledStreamWriter ()=default
Private Types
using ChildValues = std::vector< String >
Private Member Functions
void indent ()
bool isMultilineArray (const Value &value)
void pushValue (const String &value)
void unindent ()
void writeArrayValue (const Value &value)
void writeCommentAfterValueOnSameLine (const Value &root)
void writeCommentBeforeValue (const Value &root)
void writeIndent ()
void writeValue (const Value &value)
void writeWithIndent (const String &value)
Static Private Member Functions
static bool hasCommentForValue (const Value &value)
static String normalizeEOL (const String &text)
Private Attributes
bool addChildValues_: 1
ChildValues childValues_
OStream * document_
String indentation_
bool indented_: 1
String indentString_
unsigned int rightMargin_ {74}
Detailed Description
Writes a Value in JSON format in a human friendly way, to a stream rather than to a string.
The rules for line break and indent are as follow:
Object value:
if empty then print {} without indent and line break
if not empty the print '{', line break & indent, print one value per line and then unindent and line break and print '}'.
Array value:
if empty then print [] without indent and line break
if the array contains no object value, empty array or some other value types, and all the values fit on one lines, then print the array on a single line.
otherwise, it the values do not fit on one line, or the array contains object or non empty array, then print one value per line.
If the Value have comments then they are outputted according to their CommentPlacement.
See also
Reader, Value, Value::setComment()
Deprecated:
Use StreamWriterBuilder.
Definition at line 2196 of file json.h.
Member Typedef Documentation
ChildValues
using Json::StyledStreamWriter::ChildValues = std::vector<String> private
Definition at line 2228 of file json.h.
Constructor & Destructor Documentation
StyledStreamWriter()
Json::StyledStreamWriter::StyledStreamWriter (String indentation = "\t")
Parameters
indentation Each level will be indented by this amount extra.
Definition at line 4723 of file jsoncpp.cpp.
~StyledStreamWriter()
Json::StyledStreamWriter::~StyledStreamWriter () default
Member Function Documentation
hasCommentForValue()
bool Json::StyledStreamWriter::hasCommentForValue (const Value & value) static private
Definition at line 4933 of file jsoncpp.cpp.
References Json::commentAfter, Json::commentAfterOnSameLine, Json::commentBefore, and Json::Value::hasComment().
Referenced by isMultilineArray().
indent()
void Json::StyledStreamWriter::indent () private
Definition at line 4897 of file jsoncpp.cpp.
References indentation_, and indentString_.
Referenced by writeArrayValue(), and writeValue().
isMultilineArray()
bool Json::StyledStreamWriter::isMultilineArray (const Value & value) private
Definition at line 4848 of file jsoncpp.cpp.
References addChildValues_, childValues_, Json::Value::empty(), hasCommentForValue(), Json::Value::isArray(), Json::Value::isObject(), rightMargin_, Json::Value::size(), and writeValue().
Referenced by writeArrayValue().
normalizeEOL()
static String Json::StyledStreamWriter::normalizeEOL (const String & text) static private
pushValue()
void Json::StyledStreamWriter::pushValue (const String & value) private
Definition at line 4875 of file jsoncpp.cpp.
References addChildValues_, childValues_, and document_.
Referenced by writeArrayValue(), and writeValue().
unindent()
void Json::StyledStreamWriter::unindent () private
Definition at line 4899 of file jsoncpp.cpp.
References indentation_, and indentString_.
Referenced by writeArrayValue(), and writeValue().
write()
void Json::StyledStreamWriter::write (OStream & out, const Value & root)
Serialize a Value in JSON format.
Parameters
out Stream to write to. (Can be ostringstream, e.g.)
root Value to serialize.
Note
There is no point in deriving from Writer, since write() should not return a value.
Definition at line 4727 of file jsoncpp.cpp.
References addChildValues_, document_, indented_, indentString_, writeCommentAfterValueOnSameLine(), writeCommentBeforeValue(), writeIndent(), and writeValue().
writeArrayValue()
void Json::StyledStreamWriter::writeArrayValue (const Value & value) private
Definition at line 4802 of file jsoncpp.cpp.
References childValues_, document_, indent(), indented_, isMultilineArray(), pushValue(), Json::Value::size(), unindent(), writeCommentAfterValueOnSameLine(), writeCommentBeforeValue(), writeIndent(), writeValue(), and writeWithIndent().
Referenced by writeValue().
writeCommentAfterValueOnSameLine()
void Json::StyledStreamWriter::writeCommentAfterValueOnSameLine (const Value & root) private
Definition at line 4922 of file jsoncpp.cpp.
References Json::commentAfter, Json::commentAfterOnSameLine, document_, Json::Value::getComment(), Json::Value::hasComment(), indented_, and writeIndent().
Referenced by write(), writeArrayValue(), and writeValue().
writeCommentBeforeValue()
void Json::StyledStreamWriter::writeCommentBeforeValue (const Value & root) private
Definition at line 4904 of file jsoncpp.cpp.
References Json::commentBefore, document_, Json::Value::getComment(), Json::Value::hasComment(), indented_, indentString_, and writeIndent().
Referenced by write(), writeArrayValue(), and writeValue().
writeIndent()
void Json::StyledStreamWriter::writeIndent () private
Definition at line 4882 of file jsoncpp.cpp.
References document_, and indentString_.
Referenced by write(), writeArrayValue(), writeCommentAfterValueOnSameLine(), writeCommentBeforeValue(), and writeWithIndent().
writeValue()
void Json::StyledStreamWriter::writeValue (const Value & value) private
Definition at line 4742 of file jsoncpp.cpp.
References Json::arrayValue, Json::Value::asBool(), Json::Value::asDouble(), Json::Value::asLargestInt(), Json::Value::asLargestUInt(), Json::booleanValue, document_, Json::Value::getMemberNames(), Json::Value::getString(), indent(), Json::intValue, Json::nullValue, Json::objectValue, pushValue(), Json::realValue, Json::stringValue, Json::Value::type(), Json::uintValue, unindent(), Json::valueToQuotedString(), Json::valueToQuotedStringN(), Json::valueToString(), writeArrayValue(), writeCommentAfterValueOnSameLine(), writeCommentBeforeValue(), writeValue(), and writeWithIndent().
Referenced by isMultilineArray(), write(), writeArrayValue(), and writeValue().
writeWithIndent()
void Json::StyledStreamWriter::writeWithIndent (const String & value) private
Definition at line 4890 of file jsoncpp.cpp.
References document_, indented_, and writeIndent().
Referenced by writeArrayValue(), and writeValue().
Member Data Documentation
addChildValues_
bool Json::StyledStreamWriter::addChildValues_ private
Definition at line 2235 of file json.h.
Referenced by isMultilineArray(), pushValue(), and write().
childValues_
ChildValues Json::StyledStreamWriter::childValues_ private
Definition at line 2230 of file json.h.
Referenced by isMultilineArray(), pushValue(), and writeArrayValue().
document_
OStream* Json::StyledStreamWriter::document_ private
Definition at line 2231 of file json.h.
Referenced by pushValue(), write(), writeArrayValue(), writeCommentAfterValueOnSameLine(), writeCommentBeforeValue(), writeIndent(), writeValue(), and writeWithIndent().
indentation_
String Json::StyledStreamWriter::indentation_ private
Definition at line 2234 of file json.h.
Referenced by indent(), and unindent().
indented_
bool Json::StyledStreamWriter::indented_ private
Definition at line 2236 of file json.h.
Referenced by write(), writeArrayValue(), writeCommentAfterValueOnSameLine(), writeCommentBeforeValue(), and writeWithIndent().
indentString_
String Json::StyledStreamWriter::indentString_ private
Definition at line 2232 of file json.h.
Referenced by indent(), unindent(), write(), writeCommentBeforeValue(), and writeIndent().
rightMargin_
unsigned int Json::StyledStreamWriter::rightMargin_ {74} private
Definition at line 2233 of file json.h.
Referenced by isMultilineArray().
The documentation for this class was generated from the following files:
json.h
jsoncpp.cpp