lilak: LKHit Class Reference
LKHit Class Reference
#include <LKHit.h>
Public Member Functions
virtual void AddHit (LKHit *hit)
void AddTrackCand (Int_t id)
virtual void Clear (Option_t *option="")
virtual Int_t Compare (const TObject *obj) const
virtual void Copy (TObject &object) const
void CopyFrom (LKHit *hit)
virtual bool DrawByDefault ()
return true if to be displayed on eve.
bool FindTrackCand (Int_t id)
Double_t GetAlpha () const
Int_t GetChannelID () const
Double_t GetCharge () const
TVector3 GetCoSquaredMean () const
TVector3 GetCovariance () const
TVector3 GetDPosition () const
Double_t GetDX () const
Double_t GetDY () const
Double_t GetDZ () const
LKHitArray * GetHitArray ()
Int_t GetHitID () const
Int_t GetLayer () const
TVector3 GetMean () const
Int_t GetNumTrackCands ()
Int_t GetPadID () const
Double_t GetPedestal () const
TVector3 GetPosition () const
LKVector3 GetPosition (LKVector3::Axis ref) const
TVector3 GetPositionError () const
Int_t GetRow () const
Int_t GetSection () const
Double_t GetSortValue () const
TVector3 GetSquaredMean () const
TVector3 GetStdDev () const
Double_t GetTb () const
Int_t GetTrackCand (Int_t id)
vector< Int_t > * GetTrackCandArray ()
Int_t GetTrackID () const
TVector3 GetVariance () const
Double_t GetX () const
Double_t GetY () const
Double_t GetZ () const
virtual bool IsEveSet ()
virtual Bool_t IsSortable () const
LKHit ()
Temporary array for track ID candidates.
LKHit (Double_t x, Double_t y, Double_t z, Double_t q)
Double_t & operator[] (int i)
Double_t operator[] (int i) const
virtual void Print (Option_t *option="at") const
bool PropagateTrackCand ()
virtual void RemoveHit (LKHit *hit)
void RemoveTrackCand (Int_t trackID)
void SetAlpha (Double_t a)
void SetChannelID (Int_t id)
void SetCharge (Double_t charge)
void SetHitID (Int_t id)
void SetLayer (Int_t layer)
void SetPadID (Int_t id)
void SetPedestal (Double_t a)
void SetPosError (Double_t dx, Double_t dy, Double_t dz)
void SetPosError (TVector3 dpos)
void SetPosition (Double_t x, Double_t y, Double_t z)
void SetPosition (TVector3 pos)
void SetPositionError (Double_t dx, Double_t dy, Double_t dz)
void SetPositionError (TVector3 dpos)
void SetRow (Int_t row)
void SetSection (Int_t section)
void SetSortByCharge (bool sortEarlierIfSmaller)
void SetSortByDistanceTo (TVector3 point, bool sortEarlierIfCloser)
void SetSortByLayer (bool sortEarlierIfSmaller)
void SetSortByX (bool sortEarlierIfSmaller)
void SetSortByY (bool sortEarlierIfSmaller)
void SetSortByZ (bool sortEarlierIfSmaller)
void SetSortValue (Double_t val)
void SetTb (Double_t tb)
void SetTrackID (Int_t id)
void SetW (Double_t w)
Same as SetCharge.
void SetWeight (Double_t w)
void SetX (Double_t x)
void SetXError (Double_t dx)
void SetY (Double_t y)
void SetYError (Double_t dy)
void SetZ (Double_t z)
void SetZError (Double_t dz)
Double_t w () const
Double_t W () const
Double_t WeightPositionError () const
Double_t x () const
Double_t X () const
Double_t y () const
Double_t Y () const
Double_t z () const
Double_t Z () const
virtual ~LKHit ()
Public Member Functions inherited from LKContainer
virtual void Clear (Option_t *option="")
virtual void Copy (TObject &object) const
virtual bool DrawByDefault ()
return true if to be displayed on eve.
LKContainer ()
virtual ~LKContainer ()
Protected Attributes
Double_t fAlpha = -999
Use for polar angle.
Int_t fChannelID = -999
Double_t fDX = -999
Double_t fDY = -999
Double_t fDZ = -999
LKHitArray fHitArray
Temporary parameter for sorting. Sort earlier if smaller, latter if larger.
Int_t fHitID = -999
Int_t fLayer = -999
Int_t fPadID = -999
Double_t fPedestal = -999
Int_t fRow = -999
Int_t fSection = -999
Double_t fSortValue = 0
Double_t fTb = -999
vector< Int_t > fTrackCandArray
Temporary hit array.
Int_t fTrackID = -999
Double_t fW = -999
Double_t fX = -999
Double_t fY = -999
Double_t fZ = -999
Detailed Description
Definition at line 21 of file LKHit.h.
Constructor & Destructor Documentation
LKHit() [1/2]
LKHit::LKHit () inline
Temporary array for track ID candidates.
Definition at line 47 of file LKHit.h.
References Clear().
LKHit() [2/2]
LKHit::LKHit (Double_t x, Double_t y, Double_t z, Double_t q) inline
Definition at line 48 of file LKHit.h.
References Clear(), SetPosition(), SetW(), x(), y(), and z().
~LKHit()
virtual LKHit::~LKHit () inline virtual
Definition at line 49 of file LKHit.h.
Member Function Documentation
AddHit()
void LKHit::AddHit (LKHit * hit) virtual
Definition at line 247 of file LKHit.cpp.
References LKHitArray::AddHit(), fHitArray, fW, fX, fY, fZ, LKHitArray::GetMeanX(), LKHitArray::GetMeanY(), LKHitArray::GetMeanZ(), and LKHitArray::GetW().
Referenced by LKHitArray::Copy().
AddTrackCand()
void LKHit::AddTrackCand (Int_t id)
Definition at line 279 of file LKHit.cpp.
References fTrackCandArray.
Clear()
virtual void LKHit::Clear (Option_t * option = "") virtual
Reimplemented from LKContainer.
Reimplemented in LKVertex.
Referenced by LKVertex::Clear(), LKHit(), and LKHit().
Compare()
Int_t LKHit::Compare (const TObject * obj) const virtual
Definition at line 147 of file LKHit.cpp.
References fSortValue, and GetSortValue().
Copy()
void LKHit::Copy (TObject & object) const virtual
Reimplemented from LKContainer.
Reimplemented in LKVertex.
Definition at line 63 of file LKHit.cpp.
References LKContainer::Copy(), fAlpha, fChannelID, fDX, fDY, fDZ, fHitID, fLayer, fPadID, fPedestal, fRow, fSection, fTb, fTrackID, fW, fX, fY, and fZ.
Referenced by LKVertex::Copy().
CopyFrom()
void LKHit::CopyFrom (LKHit * hit)
Definition at line 89 of file LKHit.cpp.
References fAlpha, fChannelID, fDX, fDY, fDZ, fHitID, fLayer, fPadID, fPedestal, fRow, fSection, fSortValue, fTb, fTrackID, fW, fX, fY, fZ, GetAlpha(), GetChannelID(), GetCharge(), GetDX(), GetDY(), GetDZ(), GetHitID(), GetLayer(), GetPadID(), GetPedestal(), GetRow(), GetSection(), GetSortValue(), GetTb(), GetTrackID(), GetX(), GetY(), and GetZ().
DrawByDefault()
bool LKHit::DrawByDefault () virtual
return true if to be displayed on eve.
Reimplemented from LKContainer.
Definition at line 313 of file LKHit.cpp.
FindTrackCand()
bool LKHit::FindTrackCand (Int_t id)
Definition at line 293 of file LKHit.cpp.
References fTrackCandArray.
GetAlpha()
Double_t LKHit::GetAlpha () const inline
Definition at line 124 of file LKHit.h.
References fAlpha.
Referenced by CopyFrom(), and LKHitArray::FitHelix().
GetChannelID()
Int_t LKHit::GetChannelID () const inline
Definition at line 121 of file LKHit.h.
References fChannelID.
Referenced by CopyFrom().
GetCharge()
Double_t LKHit::GetCharge () const inline
Definition at line 110 of file LKHit.h.
References fW.
Referenced by LKHitArray::AddHit(), CopyFrom(), and LKHitArray::RemoveHit().
GetCoSquaredMean()
TVector3 LKHit::GetCoSquaredMean () const inline
Definition at line 136 of file LKHit.h.
References fHitArray, and LKHitArray::GetCoSquaredMean().
GetCovariance()
TVector3 LKHit::GetCovariance () const inline
Definition at line 133 of file LKHit.h.
References fHitArray, and LKHitArray::GetCovariance().
GetDPosition()
TVector3 LKHit::GetDPosition () const inline
Definition at line 113 of file LKHit.h.
References fDX, fDY, and fDZ.
GetDX()
Double_t LKHit::GetDX () const inline
Definition at line 115 of file LKHit.h.
References fDX.
Referenced by CopyFrom().
GetDY()
Double_t LKHit::GetDY () const inline
Definition at line 116 of file LKHit.h.
References fDY.
Referenced by CopyFrom().
GetDZ()
Double_t LKHit::GetDZ () const inline
Definition at line 117 of file LKHit.h.
References fDZ.
Referenced by CopyFrom().
GetHitArray()
LKHitArray * LKHit::GetHitArray () inline
Definition at line 97 of file LKHit.h.
References fHitArray.
GetHitID()
Int_t LKHit::GetHitID () const inline
Definition at line 119 of file LKHit.h.
References fHitID.
Referenced by LKTracklet::AddHit(), CopyFrom(), TTHTTrackingTask::TransformAndSelectHits(), and httask::TransformAndSelectHits().
GetLayer()
Int_t LKHit::GetLayer () const inline
Definition at line 126 of file LKHit.h.
References fLayer.
Referenced by CopyFrom().
GetMean()
TVector3 LKHit::GetMean () const inline
Definition at line 131 of file LKHit.h.
References fHitArray, and LKHitArray::GetMean().
GetNumTrackCands()
Int_t LKHit::GetNumTrackCands ()
Definition at line 277 of file LKHit.cpp.
References fTrackCandArray.
GetPadID()
Int_t LKHit::GetPadID () const inline
Definition at line 122 of file LKHit.h.
References fPadID.
Referenced by CopyFrom().
GetPedestal()
Double_t LKHit::GetPedestal () const inline
Definition at line 123 of file LKHit.h.
References fPedestal.
Referenced by CopyFrom().
GetPosition() [1/2]
TVector3 LKHit::GetPosition () const inline
Definition at line 111 of file LKHit.h.
References fX, fY, and fZ.
Referenced by LKHelixTrack::Continuity(), LKTracklet::Continuity(), LKHitArray::DrawGraph(), LKHitArray::FitHelix(), LKHitSortByDistanceTo::operator()(), LKHitSortByIncreasingLength::operator()(), LKHitSortByDecreasingLength::operator()(), SetSortByDistanceTo(), LKHelixTrack::SortHits(), and LKTracklet::SortHits().
GetPosition() [2/2]
LKVector3 LKHit::GetPosition (LKVector3::Axis ref) const inline
Definition at line 112 of file LKHit.h.
References fX, fY, and fZ.
GetPositionError()
TVector3 LKHit::GetPositionError () const inline
Definition at line 114 of file LKHit.h.
References fDX, fDY, and fDZ.
GetRow()
Int_t LKHit::GetRow () const inline
Definition at line 127 of file LKHit.h.
References fRow.
Referenced by CopyFrom().
GetSection()
Int_t LKHit::GetSection () const inline
Definition at line 125 of file LKHit.h.
References fSection.
Referenced by CopyFrom().
GetSortValue()
Double_t LKHit::GetSortValue () const inline
Definition at line 128 of file LKHit.h.
References fSortValue.
Referenced by Compare(), CopyFrom(), TTHTTrackingTask::TransformAndSelectHits(), and httask::TransformAndSelectHits().
GetSquaredMean()
TVector3 LKHit::GetSquaredMean () const inline
Definition at line 135 of file LKHit.h.
References fHitArray, and LKHitArray::GetSquaredMean().
GetStdDev()
TVector3 LKHit::GetStdDev () const inline
Definition at line 134 of file LKHit.h.
References fHitArray, and LKHitArray::GetStdDev().
GetTb()
Double_t LKHit::GetTb () const inline
Definition at line 118 of file LKHit.h.
References fTb.
Referenced by CopyFrom().
GetTrackCand()
Int_t LKHit::GetTrackCand (Int_t id)
Definition at line 278 of file LKHit.cpp.
References fTrackCandArray.
GetTrackCandArray()
std::vector< Int_t > * LKHit::GetTrackCandArray ()
Definition at line 276 of file LKHit.cpp.
References fTrackCandArray.
GetTrackID()
Int_t LKHit::GetTrackID () const inline
Definition at line 120 of file LKHit.h.
References fTrackID.
Referenced by CopyFrom(), and LKEveTask::SelectHit().
GetVariance()
TVector3 LKHit::GetVariance () const inline
Definition at line 132 of file LKHit.h.
References fHitArray, and LKHitArray::GetVariance().
GetX()
Double_t LKHit::GetX () const inline
Definition at line 107 of file LKHit.h.
References fX.
Referenced by LKHitArray::AddHit(), CopyFrom(), and LKHitArray::RemoveHit().
GetY()
Double_t LKHit::GetY () const inline
Definition at line 108 of file LKHit.h.
References fY.
Referenced by LKHitArray::AddHit(), CopyFrom(), and LKHitArray::RemoveHit().
GetZ()
Double_t LKHit::GetZ () const inline
Definition at line 109 of file LKHit.h.
References fZ.
Referenced by LKHitArray::AddHit(), CopyFrom(), and LKHitArray::RemoveHit().
IsEveSet()
bool LKHit::IsEveSet () virtual
Definition at line 314 of file LKHit.cpp.
IsSortable()
Bool_t LKHit::IsSortable () const virtual
Definition at line 145 of file LKHit.cpp.
operator[]() [1/2]
Double_t & LKHit::operator[] (int i) inline
Definition at line 138 of file LKHit.h.
References fX, fY, and fZ.
operator[]() [2/2]
Double_t LKHit::operator[] (int i) const inline
Definition at line 152 of file LKHit.h.
References fX, fY, and fZ.
Print()
void LKHit::Print (Option_t * option = "at") const virtual
Reimplemented in LKVertex.
Definition at line 39 of file LKHit.cpp.
References e_info, fChannelID, fHitID, fLayer, fPadID, fRow, fSection, fTb, fTrackID, fW, fX, fY, and fZ.
PropagateTrackCand()
bool LKHit::PropagateTrackCand ()
Definition at line 304 of file LKHit.cpp.
References fTrackCandArray, and SetTrackID().
RemoveHit()
void LKHit::RemoveHit (LKHit * hit) virtual
Definition at line 256 of file LKHit.cpp.
References fHitArray, fW, fX, fY, fZ, LKHitArray::GetMeanX(), LKHitArray::GetMeanY(), LKHitArray::GetMeanZ(), LKHitArray::GetW(), and LKHitArray::RemoveHit().
RemoveTrackCand()
void LKHit::RemoveTrackCand (Int_t trackID)
Definition at line 281 of file LKHit.cpp.
References fTrackCandArray.
SetAlpha()
void LKHit::SetAlpha (Double_t a) inline
Definition at line 81 of file LKHit.h.
References fAlpha.
SetChannelID()
void LKHit::SetChannelID (Int_t id) inline
Definition at line 78 of file LKHit.h.
References fChannelID.
SetCharge()
void LKHit::SetCharge (Double_t charge) inline
Definition at line 72 of file LKHit.h.
References fW.
SetHitID()
void LKHit::SetHitID (Int_t id) inline
Definition at line 76 of file LKHit.h.
References fHitID.
SetLayer()
void LKHit::SetLayer (Int_t layer) inline
Definition at line 91 of file LKHit.h.
References fLayer.
SetPadID()
void LKHit::SetPadID (Int_t id) inline
Definition at line 79 of file LKHit.h.
References fPadID.
SetPedestal()
void LKHit::SetPedestal (Double_t a) inline
Definition at line 80 of file LKHit.h.
References fPedestal.
SetPosError() [1/2]
void LKHit::SetPosError (Double_t dx, Double_t dy, Double_t dz) inline
Definition at line 85 of file LKHit.h.
References SetPositionError().
SetPosError() [2/2]
void LKHit::SetPosError (TVector3 dpos) inline
Definition at line 84 of file LKHit.h.
References SetPositionError().
SetPosition() [1/2]
void LKHit::SetPosition (Double_t x, Double_t y, Double_t z) inline
Definition at line 74 of file LKHit.h.
References fX, fY, fZ, x(), y(), and z().
Referenced by LKHit().
SetPosition() [2/2]
void LKHit::SetPosition (TVector3 pos) inline
Definition at line 75 of file LKHit.h.
References fX, fY, and fZ.
SetPositionError() [1/2]
void LKHit::SetPositionError (Double_t dx, Double_t dy, Double_t dz) inline
Definition at line 83 of file LKHit.h.
References fDX, fDY, and fDZ.
SetPositionError() [2/2]
void LKHit::SetPositionError (TVector3 dpos) inline
Definition at line 82 of file LKHit.h.
References fDX, fDY, and fDZ.
Referenced by SetPosError(), and SetPosError().
SetRow()
void LKHit::SetRow (Int_t row) inline
Definition at line 92 of file LKHit.h.
References fRow.
SetSection()
void LKHit::SetSection (Int_t section) inline
Definition at line 90 of file LKHit.h.
References fSection.
SetSortByCharge()
void LKHit::SetSortByCharge (bool sortEarlierIfSmaller)
Definition at line 126 of file LKHit.cpp.
References fSortValue, and fW.
SetSortByDistanceTo()
void LKHit::SetSortByDistanceTo (TVector3 point, bool sortEarlierIfCloser)
Definition at line 132 of file LKHit.cpp.
References fSortValue, and GetPosition().
SetSortByLayer()
void LKHit::SetSortByLayer (bool sortEarlierIfSmaller)
Definition at line 139 of file LKHit.cpp.
References fLayer, and fSortValue.
SetSortByX()
void LKHit::SetSortByX (bool sortEarlierIfSmaller)
Definition at line 111 of file LKHit.cpp.
References fSortValue, and fX.
SetSortByY()
void LKHit::SetSortByY (bool sortEarlierIfSmaller)
Definition at line 116 of file LKHit.cpp.
References fSortValue, and fY.
SetSortByZ()
void LKHit::SetSortByZ (bool sortEarlierIfSmaller)
Definition at line 121 of file LKHit.cpp.
References fSortValue, and fZ.
SetSortValue()
void LKHit::SetSortValue (Double_t val) inline
Definition at line 56 of file LKHit.h.
References fSortValue.
Referenced by LKEveTask::SelectHit().
SetTb()
void LKHit::SetTb (Double_t tb) inline
Definition at line 89 of file LKHit.h.
References fTb.
SetTrackID()
void LKHit::SetTrackID (Int_t id) inline
Definition at line 77 of file LKHit.h.
References fTrackID.
Referenced by PropagateTrackCand().
SetW()
void LKHit::SetW (Double_t w) inline
Same as SetCharge.
Definition at line 71 of file LKHit.h.
References fW, and w().
Referenced by LKHit().
SetWeight()
void LKHit::SetWeight (Double_t w) inline
Definition at line 73 of file LKHit.h.
References fW, and w().
SetX()
void LKHit::SetX (Double_t x) inline
Definition at line 68 of file LKHit.h.
References fX, and x().
SetXError()
void LKHit::SetXError (Double_t dx) inline
Definition at line 86 of file LKHit.h.
References fDX.
SetY()
void LKHit::SetY (Double_t y) inline
Definition at line 69 of file LKHit.h.
References fY, and y().
SetYError()
void LKHit::SetYError (Double_t dy) inline
Definition at line 87 of file LKHit.h.
References fDY.
SetZ()
void LKHit::SetZ (Double_t z) inline
Definition at line 70 of file LKHit.h.
References fZ, and z().
SetZError()
void LKHit::SetZError (Double_t dz) inline
Definition at line 88 of file LKHit.h.
References fDZ.
w()
Double_t LKHit::w () const inline
Definition at line 102 of file LKHit.h.
References fW.
Referenced by SetW(), and SetWeight().
W()
Double_t LKHit::W () const inline
Definition at line 106 of file LKHit.h.
References fW.
WeightPositionError()
Double_t LKHit::WeightPositionError () const
Definition at line 265 of file LKHit.cpp.
References e_error, fDX, fDY, and fDZ.
Referenced by LKHTLineTracker::AddHit(), and LKHTLineTracker::FitTrack3DWithParamPoint().
x()
Double_t LKHit::x () const inline
Definition at line 99 of file LKHit.h.
References fX.
Referenced by LKHit(), SetPosition(), and SetX().
X()
Double_t LKHit::X () const inline
Definition at line 103 of file LKHit.h.
References fX.
Referenced by LKHTLineTracker::FitTrack3DWithParamPoint(), LKHitSortX::operator()(), LKHitSortXInv::operator()(), LKHitSortXYZInv::operator()(), LKHitSortRho::operator()(), and LKHitSortRhoInv::operator()().
y()
Double_t LKHit::y () const inline
Definition at line 100 of file LKHit.h.
References fY.
Referenced by LKHit(), SetPosition(), and SetY().
Y()
Double_t LKHit::Y () const inline
Definition at line 104 of file LKHit.h.
References fY.
Referenced by LKHTLineTracker::FitTrack3DWithParamPoint(), LKHitSortY::operator()(), LKHitSortYInv::operator()(), and LKHitSortXYZInv::operator()().
z()
Double_t LKHit::z () const inline
Definition at line 101 of file LKHit.h.
References fZ.
Referenced by LKHit(), SetPosition(), and SetZ().
Z()
Double_t LKHit::Z () const inline
Definition at line 105 of file LKHit.h.
References fZ.
Referenced by LKHTLineTracker::FitTrack3DWithParamPoint(), LKHitSortZ::operator()(), LKHitSortZInv::operator()(), LKHitSortXYZInv::operator()(), LKHitSortRho::operator()(), and LKHitSortRhoInv::operator()().
Member Data Documentation
fAlpha
Double_t LKHit::fAlpha = -999 protected
Use for polar angle.
Definition at line 36 of file LKHit.h.
Referenced by ClassImp(), Copy(), CopyFrom(), GetAlpha(), and SetAlpha().
fChannelID
Int_t LKHit::fChannelID = -999 protected
Definition at line 34 of file LKHit.h.
Referenced by ClassImp(), Copy(), CopyFrom(), GetChannelID(), Print(), and SetChannelID().
fDX
Double_t LKHit::fDX = -999 protected
Definition at line 28 of file LKHit.h.
Referenced by ClassImp(), Copy(), CopyFrom(), GetDPosition(), GetDX(), GetPositionError(), SetPositionError(), SetPositionError(), SetXError(), and WeightPositionError().
fDY
Double_t LKHit::fDY = -999 protected
Definition at line 29 of file LKHit.h.
Referenced by ClassImp(), Copy(), CopyFrom(), GetDPosition(), GetDY(), GetPositionError(), SetPositionError(), SetPositionError(), SetYError(), and WeightPositionError().
fDZ
Double_t LKHit::fDZ = -999 protected
Definition at line 30 of file LKHit.h.
Referenced by ClassImp(), Copy(), CopyFrom(), GetDPosition(), GetDZ(), GetPositionError(), SetPositionError(), SetPositionError(), SetZError(), and WeightPositionError().
fHitArray
LKHitArray LKHit::fHitArray protected
Temporary parameter for sorting. Sort earlier if smaller, latter if larger.
Definition at line 43 of file LKHit.h.
Referenced by AddHit(), ClassImp(), GetCoSquaredMean(), GetCovariance(), GetHitArray(), GetMean(), GetSquaredMean(), GetStdDev(), GetVariance(), and RemoveHit().
fHitID
Int_t LKHit::fHitID = -999 protected
Definition at line 32 of file LKHit.h.
Referenced by ClassImp(), Copy(), CopyFrom(), GetHitID(), Print(), and SetHitID().
fLayer
Int_t LKHit::fLayer = -999 protected
Definition at line 39 of file LKHit.h.
Referenced by ClassImp(), Copy(), CopyFrom(), GetLayer(), Print(), SetLayer(), and SetSortByLayer().
fPadID
Int_t LKHit::fPadID = -999 protected
Definition at line 35 of file LKHit.h.
Referenced by ClassImp(), Copy(), CopyFrom(), GetPadID(), Print(), and SetPadID().
fPedestal
Double_t LKHit::fPedestal = -999 protected
Definition at line 37 of file LKHit.h.
Referenced by ClassImp(), Copy(), CopyFrom(), GetPedestal(), and SetPedestal().
fRow
Int_t LKHit::fRow = -999 protected
Definition at line 40 of file LKHit.h.
Referenced by ClassImp(), Copy(), CopyFrom(), GetRow(), Print(), and SetRow().
fSection
Int_t LKHit::fSection = -999 protected
Definition at line 38 of file LKHit.h.
Referenced by ClassImp(), Copy(), CopyFrom(), GetSection(), Print(), and SetSection().
fSortValue
Double_t LKHit::fSortValue = 0 protected
Definition at line 42 of file LKHit.h.
Referenced by ClassImp(), Compare(), CopyFrom(), GetSortValue(), SetSortByCharge(), SetSortByDistanceTo(), SetSortByLayer(), SetSortByX(), SetSortByY(), SetSortByZ(), and SetSortValue().
fTb
Double_t LKHit::fTb = -999 protected
Definition at line 31 of file LKHit.h.
Referenced by ClassImp(), Copy(), CopyFrom(), GetTb(), Print(), and SetTb().
fTrackCandArray
vector<Int_t> LKHit::fTrackCandArray protected
Temporary hit array.
Definition at line 44 of file LKHit.h.
Referenced by AddTrackCand(), ClassImp(), FindTrackCand(), GetNumTrackCands(), GetTrackCand(), GetTrackCandArray(), PropagateTrackCand(), and RemoveTrackCand().
fTrackID
Int_t LKHit::fTrackID = -999 protected
Definition at line 33 of file LKHit.h.
Referenced by ClassImp(), Copy(), CopyFrom(), GetTrackID(), Print(), and SetTrackID().
fW
Double_t LKHit::fW = -999 protected
Definition at line 27 of file LKHit.h.
Referenced by AddHit(), ClassImp(), Copy(), CopyFrom(), GetCharge(), Print(), RemoveHit(), SetCharge(), SetSortByCharge(), SetW(), SetWeight(), w(), and W().
fX
Double_t LKHit::fX = -999 protected
Definition at line 24 of file LKHit.h.
Referenced by AddHit(), ClassImp(), Copy(), CopyFrom(), GetPosition(), GetPosition(), GetX(), operator[](), operator[](), Print(), LKVertex::Print(), RemoveHit(), SetPosition(), SetPosition(), SetSortByX(), SetX(), x(), and X().
fY
Double_t LKHit::fY = -999 protected
Definition at line 25 of file LKHit.h.
Referenced by AddHit(), ClassImp(), Copy(), CopyFrom(), GetPosition(), GetPosition(), GetY(), operator[](), operator[](), Print(), LKVertex::Print(), RemoveHit(), SetPosition(), SetPosition(), SetSortByY(), SetY(), y(), and Y().
fZ
Double_t LKHit::fZ = -999 protected
Definition at line 26 of file LKHit.h.
Referenced by AddHit(), ClassImp(), Copy(), CopyFrom(), GetPosition(), GetPosition(), GetZ(), operator[](), operator[](), Print(), LKVertex::Print(), RemoveHit(), SetPosition(), SetPosition(), SetSortByZ(), SetZ(), z(), and Z().
The documentation for this class was generated from the following files:
LKHit.h
LKHit.cpp