LILAK: Json::Value::Comments Class Reference
Json::Value::Comments Class Reference
Public Member Functions
Comments ()=default
Comments (Comments &&that) noexcept
Comments (const Comments &that)
String get (CommentPlacement slot) const
bool has (CommentPlacement slot) const
Comments & operator= (Comments &&that) noexcept
Comments & operator= (const Comments &that)
void set (CommentPlacement slot, String comment)
Private Types
using Array = std::array< String, numberOfCommentPlacement >
Private Attributes
std::unique_ptr< Array > ptr_
Detailed Description
Definition at line 1161 of file json.h.
Member Typedef Documentation
Array
using Json::Value::Comments::Array = std::array<String, numberOfCommentPlacement> private
Definition at line 1173 of file json.h.
Constructor & Destructor Documentation
Comments() [1/3]
Json::Value::Comments::Comments () default
Comments() [2/3]
Json::Value::Comments::Comments (const Comments & that)
Definition at line 3800 of file jsoncpp.cpp.
Comments() [3/3]
Json::Value::Comments::Comments (Comments && that) noexcept
Definition at line 3803 of file jsoncpp.cpp.
Member Function Documentation
get()
String Json::Value::Comments::get (CommentPlacement slot) const
Definition at line 3820 of file jsoncpp.cpp.
Referenced by Json::Value::getComment().
has()
bool Json::Value::Comments::has (CommentPlacement slot) const
Definition at line 3816 of file jsoncpp.cpp.
Referenced by Json::Value::hasComment().
operator=() [1/2]
Value::Comments & Json::Value::Comments::operator= (Comments && that) noexcept
Definition at line 3811 of file jsoncpp.cpp.
operator=() [2/2]
Value::Comments & Json::Value::Comments::operator= (const Comments & that)
Definition at line 3806 of file jsoncpp.cpp.
References Json::cloneUnique(), and ptr_.
set()
void Json::Value::Comments::set (CommentPlacement slot, String comment)
Definition at line 3826 of file jsoncpp.cpp.
References Json::numberOfCommentPlacement.
Referenced by Json::Value::setComment().
Member Data Documentation
ptr_
std::unique_ptr<Array> Json::Value::Comments::ptr_ private
Definition at line 1174 of file json.h.
Referenced by operator=().
The documentation for this class was generated from the following files:
json.h
jsoncpp.cpp