LILAK: LKLogManager Class Reference
LKLogManager Class Reference
lilak logger manager
#include <LKLogger.h>
Public Member Functions
LKLogManager (const char *fileName)
LKLogManager (TString fileName)
Static Public Member Functions
static std::ofstream & GetLogFile ()
static std::ofstream & GetLogFile ()
static TString GetLogFileName ()
static const char * GetLogFileName ()
static bool LogToConsol ()
static bool LogToConsol ()
static bool LogToFile ()
static bool LogToFile ()
static bool PrintCout ()
static bool PrintCout ()
static bool PrintCurrent ()
static bool PrintCurrent ()
static bool PrintDebug ()
static bool PrintDebug ()
static bool PrintError ()
static bool PrintError ()
static bool PrintInfo ()
static bool PrintInfo ()
static bool PrintList ()
static bool PrintList ()
static bool PrintMessage ()
static bool PrintMessage ()
static bool PrintPlane ()
static bool PrintPlane ()
static bool PrintTest ()
static bool PrintTest ()
static bool PrintWarn ()
static bool PrintWarn ()
static LKLogManager * RunLogger (const char *fileName="", bool forceNewLogger=false)
static LKLogManager * RunLogger (TString fileName="", bool forceNewLogger=false)
static void SetLogToConsol (bool val)
static void SetLogToConsol (bool val)
static void SetLogToFile (bool val)
static void SetLogToFile (bool val)
static void SetPrintCout (bool val)
static void SetPrintCout (bool val)
static void SetPrintCurrent (bool val)
static void SetPrintCurrent (bool val)
static void SetPrintDebug (bool val)
static void SetPrintDebug (bool val)
static void SetPrintError (bool val)
static void SetPrintError (bool val)
static void SetPrintInfo (bool val)
static void SetPrintInfo (bool val)
static void SetPrintList (bool val)
static void SetPrintList (bool val)
static void SetPrintMessage (bool val)
static void SetPrintMessage (bool val)
static void SetPrintPlane (bool val)
static void SetPrintPlane (bool val)
static void SetPrintTest (bool val)
static void SetPrintTest (bool val)
static void SetPrintWarn (bool val)
static void SetPrintWarn (bool val)
Static Private Attributes
static std::ofstream fLogFile
static TString fLogFileName = ""
static const char * fLogFileName
static LKLogManager * fLogManager = nullptr
static bool fLogToConsol = true
static bool fLogToFile = false
static bool fPrintCout = true
static bool fPrintCurrent = true
static bool fPrintDebug = true
static bool fPrintError = true
static bool fPrintInfo = true
static bool fPrintList = true
static bool fPrintMessage = true
static bool fPrintPlane = false
static bool fPrintTest = true
static bool fPrintWarn = true
Detailed Description
lilak logger manager
Definition at line 45 of file LKLogger.h.
Constructor & Destructor Documentation
LKLogManager() [1/2]
LKLogManager::LKLogManager (TString fileName)
Definition at line 10 of file LKLogger.cpp.
References fLogFile, fLogFileName, fLogManager, fLogToFile, and LILAK_PATH.
LKLogManager() [2/2]
LKLogManager::LKLogManager (const char * fileName)
Definition at line 10 of file temp/LKLogger.cpp.
References fLogFile, fLogFileName, fLogManager, fLogToFile, and LILAK_PATH.
Member Function Documentation
GetLogFile() [1/2]
std::ofstream & LKLogManager::GetLogFile () static
Definition at line 36 of file LKLogger.cpp.
References fLogFile.
Referenced by LKLogger::LKLogger(), LKLogger::LKLogger(), LKLogger::LKLogger(), LKLogger::operator<<(), and LKLogger::operator<<().
GetLogFile() [2/2]
static std::ofstream & LKLogManager::GetLogFile () static
GetLogFileName() [1/2]
const char * LKLogManager::GetLogFileName () static
Definition at line 35 of file LKLogger.cpp.
References fLogFileName.
GetLogFileName() [2/2]
static const char * LKLogManager::GetLogFileName () static
LogToConsol() [1/2]
bool LKLogManager::LogToConsol () static
Definition at line 37 of file LKLogger.cpp.
References fLogToConsol.
Referenced by LKLogger::LKLogger(), LKLogger::LKLogger(), LKLogger::LKLogger(), LKLogger::operator<<(), and LKLogger::operator<<().
LogToConsol() [2/2]
static bool LKLogManager::LogToConsol () static
LogToFile() [1/2]
bool LKLogManager::LogToFile () static
Definition at line 38 of file LKLogger.cpp.
References fLogToFile.
Referenced by LKLogger::LKLogger(), LKLogger::LKLogger(), LKLogger::LKLogger(), LKLogger::operator<<(), and LKLogger::operator<<().
LogToFile() [2/2]
static bool LKLogManager::LogToFile () static
PrintCout() [1/2]
bool LKLogManager::PrintCout () static
Definition at line 63 of file LKLogger.cpp.
References fPrintCout.
Referenced by LKLogger::LKLogger(), and LKLogger::LKLogger().
PrintCout() [2/2]
static bool LKLogManager::PrintCout () static
PrintCurrent() [1/2]
bool LKLogManager::PrintCurrent () static
Definition at line 69 of file LKLogger.cpp.
References fPrintCurrent.
Referenced by LKLogger::LKLogger(), LKLogger::LKLogger(), LKLogger::LKLogger(), LKLogger::operator<<(), and LKLogger::operator<<().
PrintCurrent() [2/2]
static bool LKLogManager::PrintCurrent () static
PrintDebug() [1/2]
bool LKLogManager::PrintDebug () static
Definition at line 62 of file LKLogger.cpp.
References fPrintDebug.
Referenced by LKLogger::LKLogger().
PrintDebug() [2/2]
static bool LKLogManager::PrintDebug () static
PrintError() [1/2]
bool LKLogManager::PrintError () static
Definition at line 66 of file LKLogger.cpp.
References fPrintError.
Referenced by LKLogger::LKLogger(), and LKLogger::LKLogger().
PrintError() [2/2]
static bool LKLogManager::PrintError () static
PrintInfo() [1/2]
bool LKLogManager::PrintInfo () static
Definition at line 64 of file LKLogger.cpp.
References fPrintInfo.
Referenced by LKLogger::LKLogger(), and LKLogger::LKLogger().
PrintInfo() [2/2]
static bool LKLogManager::PrintInfo () static
PrintList() [1/2]
bool LKLogManager::PrintList () static
Definition at line 67 of file LKLogger.cpp.
References fPrintList.
Referenced by LKLogger::LKLogger(), and LKLogger::LKLogger().
PrintList() [2/2]
static bool LKLogManager::PrintList () static
PrintMessage() [1/2]
bool LKLogManager::PrintMessage () static
Definition at line 70 of file LKLogger.cpp.
References fPrintMessage.
Referenced by LKLogger::LKLogger(), LKLogger::LKLogger(), LKLogger::LKLogger(), LKLogger::operator<<(), and LKLogger::operator<<().
PrintMessage() [2/2]
static bool LKLogManager::PrintMessage () static
PrintPlane() [1/2]
bool LKLogManager::PrintPlane () static
Definition at line 61 of file LKLogger.cpp.
References fPrintPlane.
Referenced by LKLogger::LKLogger(), and LKLogger::LKLogger().
PrintPlane() [2/2]
static bool LKLogManager::PrintPlane () static
PrintTest() [1/2]
bool LKLogManager::PrintTest () static
Definition at line 68 of file LKLogger.cpp.
References fPrintTest.
Referenced by LKLogger::LKLogger(), and LKLogger::LKLogger().
PrintTest() [2/2]
static bool LKLogManager::PrintTest () static
PrintWarn() [1/2]
bool LKLogManager::PrintWarn () static
Definition at line 65 of file LKLogger.cpp.
References fPrintWarn.
Referenced by LKLogger::LKLogger(), and LKLogger::LKLogger().
PrintWarn() [2/2]
static bool LKLogManager::PrintWarn () static
RunLogger() [1/2]
LKLogManager * LKLogManager::RunLogger (const char * fileName = "", bool forceNewLogger = false) static
Definition at line 26 of file temp/LKLogger.cpp.
References fLogFileName, and fLogManager.
RunLogger() [2/2]
LKLogManager * LKLogManager::RunLogger (TString fileName = "", bool forceNewLogger = false) static
Definition at line 22 of file LKLogger.cpp.
References fLogFileName, and fLogManager.
SetLogToConsol() [1/2]
void LKLogManager::SetLogToConsol (bool val) static
Definition at line 39 of file LKLogger.cpp.
References fLogToConsol.
SetLogToConsol() [2/2]
static void LKLogManager::SetLogToConsol (bool val) static
SetLogToFile() [1/2]
void LKLogManager::SetLogToFile (bool val) static
Definition at line 40 of file LKLogger.cpp.
References fLogToFile.
SetLogToFile() [2/2]
static void LKLogManager::SetLogToFile (bool val) static
SetPrintCout() [1/2]
void LKLogManager::SetPrintCout (bool val) static
Definition at line 51 of file LKLogger.cpp.
References fPrintCout.
SetPrintCout() [2/2]
static void LKLogManager::SetPrintCout (bool val) static
SetPrintCurrent() [1/2]
void LKLogManager::SetPrintCurrent (bool val) static
Definition at line 59 of file LKLogger.cpp.
References fPrintCurrent.
Referenced by LKLogger::LKLogger(), LKLogger::LKLogger(), and LKLogger::LKLogger().
SetPrintCurrent() [2/2]
static void LKLogManager::SetPrintCurrent (bool val) static
SetPrintDebug() [1/2]
void LKLogManager::SetPrintDebug (bool val) static
Definition at line 57 of file LKLogger.cpp.
References fPrintDebug.
SetPrintDebug() [2/2]
static void LKLogManager::SetPrintDebug (bool val) static
SetPrintError() [1/2]
void LKLogManager::SetPrintError (bool val) static
Definition at line 56 of file LKLogger.cpp.
References fPrintError.
SetPrintError() [2/2]
static void LKLogManager::SetPrintError (bool val) static
SetPrintInfo() [1/2]
void LKLogManager::SetPrintInfo (bool val) static
Definition at line 52 of file LKLogger.cpp.
References fPrintInfo.
SetPrintInfo() [2/2]
static void LKLogManager::SetPrintInfo (bool val) static
SetPrintList() [1/2]
void LKLogManager::SetPrintList (bool val) static
Definition at line 54 of file LKLogger.cpp.
References fPrintList.
SetPrintList() [2/2]
static void LKLogManager::SetPrintList (bool val) static
SetPrintMessage() [1/2]
void LKLogManager::SetPrintMessage (bool val) static
Definition at line 60 of file LKLogger.cpp.
References fPrintMessage.
SetPrintMessage() [2/2]
static void LKLogManager::SetPrintMessage (bool val) static
SetPrintPlane() [1/2]
void LKLogManager::SetPrintPlane (bool val) static
Definition at line 55 of file LKLogger.cpp.
References fPrintPlane.
SetPrintPlane() [2/2]
static void LKLogManager::SetPrintPlane (bool val) static
SetPrintTest() [1/2]
void LKLogManager::SetPrintTest (bool val) static
Definition at line 58 of file LKLogger.cpp.
References fPrintTest.
SetPrintTest() [2/2]
static void LKLogManager::SetPrintTest (bool val) static
SetPrintWarn() [1/2]
void LKLogManager::SetPrintWarn (bool val) static
Definition at line 53 of file LKLogger.cpp.
References fPrintWarn.
SetPrintWarn() [2/2]
static void LKLogManager::SetPrintWarn (bool val) static
Member Data Documentation
fLogFile
static std::ofstream LKLogManager::fLogFile static private
Definition at line 50 of file LKLogger.h.
Referenced by GetLogFile(), LKLogManager(), and LKLogManager().
fLogFileName [1/2]
const char * LKLogManager::fLogFileName = "" static private
Definition at line 49 of file LKLogger.h.
Referenced by GetLogFileName(), LKLogManager(), LKLogManager(), RunLogger(), and RunLogger().
fLogFileName [2/2]
const char* LKLogManager::fLogFileName static private
Definition at line 49 of file temp/LKLogger.h.
fLogManager
static LKLogManager * LKLogManager::fLogManager = nullptr static private
Definition at line 48 of file LKLogger.h.
Referenced by LKLogManager(), LKLogManager(), RunLogger(), and RunLogger().
fLogToConsol
static bool LKLogManager::fLogToConsol = true static private
Definition at line 51 of file LKLogger.h.
Referenced by LogToConsol(), and SetLogToConsol().
fLogToFile
static bool LKLogManager::fLogToFile = false static private
Definition at line 52 of file LKLogger.h.
Referenced by LKLogManager(), LKLogManager(), LogToFile(), and SetLogToFile().
fPrintCout
static bool LKLogManager::fPrintCout = true static private
Definition at line 56 of file LKLogger.h.
Referenced by PrintCout(), and SetPrintCout().
fPrintCurrent
static bool LKLogManager::fPrintCurrent = true static private
Definition at line 62 of file LKLogger.h.
Referenced by PrintCurrent(), and SetPrintCurrent().
fPrintDebug
static bool LKLogManager::fPrintDebug = true static private
Definition at line 55 of file LKLogger.h.
Referenced by PrintDebug(), and SetPrintDebug().
fPrintError
static bool LKLogManager::fPrintError = true static private
Definition at line 59 of file LKLogger.h.
Referenced by PrintError(), and SetPrintError().
fPrintInfo
static bool LKLogManager::fPrintInfo = true static private
Definition at line 57 of file LKLogger.h.
Referenced by PrintInfo(), and SetPrintInfo().
fPrintList
static bool LKLogManager::fPrintList = true static private
Definition at line 60 of file LKLogger.h.
Referenced by PrintList(), and SetPrintList().
fPrintMessage
static bool LKLogManager::fPrintMessage = true static private
Definition at line 63 of file LKLogger.h.
Referenced by PrintMessage(), and SetPrintMessage().
fPrintPlane
static bool LKLogManager::fPrintPlane = false static private
Definition at line 54 of file LKLogger.h.
Referenced by PrintPlane(), and SetPrintPlane().
fPrintTest
static bool LKLogManager::fPrintTest = true static private
Definition at line 61 of file LKLogger.h.
Referenced by PrintTest(), and SetPrintTest().
fPrintWarn
static bool LKLogManager::fPrintWarn = true static private
Definition at line 58 of file LKLogger.h.
Referenced by PrintWarn(), and SetPrintWarn().
The documentation for this class was generated from the following files:
LKLogger.h
temp/LKLogger.h
LKLogger.cpp
temp/LKLogger.cpp