lilak: LKHTLineTracker Class Reference
LKHTLineTracker Class Reference
LKHTLineTracker is tool for finding and fitting a straight line track from a provided list of hits.
#include <LKHTLineTracker.h>
Public Member Functions
void AddHistogram (TH2 *hist)
void AddHit (LKHit *hit, LKVector3::Axis a1, LKVector3::Axis a2, double weightHT=1)
void AddImagePoint (double x, double xError, double y, double yError, double weightHT=1, double weightFit=-1)
void AddImagePointBox (double x1, double y1, double x2, double y2, double weightHT=1, double weightFit=-1)
void CleanLastParamPoint (double rWidth=-1, double tWidth=-1)
void Clear (Option_t *option="")
void ClearPoints ()
Reset parameter space range and parameter data. Clear track-array, hit-array, and point-array.
void DeTransformSelectedPoints ()
void Draw (TString option="")
void Draw (TVirtualPad *padImage, TVirtualPad *padParam)
void Draw (TVirtualPad *padImage, TVirtualPad *padParam, LKParamPointRT *paramPoint)
void Draw (TVirtualPad *padImage, TVirtualPad *padParam, LKParamPointRT *paramPoint, TString option)
void Draw (TVirtualPad *padImage, TVirtualPad *padParam, TString option)
void DrawAllParamBands ()
void DrawAllParamLines (int i=-1, bool drawRadialLine=true)
virtual void ExecMouseClickEventOnPad (TVirtualPad *pad, double xOnClick, double yOnClick)
LKParamPointRT * FindNextMaximumParamPoint ()
LKLinearTrack * FitTrack (LKParamPointRT *paramPoint, double weightCut=-1)
Used hits(points) will be removed from the hit array.
LKLinearTrack * FitTrack3D (LKParamPointRT *paramPoint, double weightCut=-1)
LKLinearTrack * FitTrack3DWithParamPoint (LKParamPointRT *paramPoint, double weightCut=-1)
Used hits(points) will be removed from the hit array.
LKLinearTrack * FitTrackWithParamPoint (LKParamPointRT *paramPoint, double weightCut=-1)
TString GetCorrelatorName () const
LKParamPointRT * GetCurrentMaximumParamPoint ()
TGraphErrors * GetDataGraphImageSpace ()
TH2D * GetHistImageSpace (TString name="", TString title="")
TH2D * GetHistParamSpace (TString name="", TString title="")
TObjArray * GetHitArray ()
LKImagePoint * GetImagePoint (int i)
double GetMaxWeightingDistance (double distance) const
int GetNumBinsImageSpace (int ixy) const
int GetNumBinsParamSpace (int ixy) const
int GetNumImagePoints () const
int GetNumParamPoints () const
double ** GetParamData () const
LKParamPointRT * GetParamPoint (int i)
LKParamPointRT * GetParamPoint (int ir, int it)
TString GetProcessName () const
double GetRangeImageSpace (int ixy, int i) const
double GetRangeParamSpace (int ixy, int i) const
TGraphErrors * GetSelectedDataGraph (LKParamPointRT *paramPoint)
TObjArray * GetSelectedHitArray ()
TVector3 GetTransformCenter () const
bool Init ()
bool IsCorrelateBoxBand ()
bool IsCorrelateBoxLine ()
bool IsCorrelateBoxRibbon ()
bool IsCorrelatePointBand ()
LKHTLineTracker ()
LKImagePoint * PopImagePoint (int i)
void Print (Option_t *option="") const
LKParamPointRT * ReinitializeFromLastParamPoint ()
void RemoveSelectedPoints ()
void Reset ()
Reset parameter space range and parameter data.
void RetransformFromLastParamPoint ()
void SelectPoints (LKParamPointRT *paramPoint, double weightCut=-1)
void SetCorrelateBoxBand ()
void SetCorrelateBoxLine ()
void SetCorrelateBoxRibbon ()
void SetCorrelatePointBand ()
void SetCutNumTrackHits (double value)
void SetImageData (double **imageData)
void SetImageSpaceRange (int nx, double x1, double x2, int ny, double y1, double y2)
void SetMaxWeightingDistance (double distance)
void SetParamSpaceBins (int nr, int nt)
void SetParamSpaceRange (int nr, double r2, double r1, int nt, double t1, double t2)
void SetTransformCenter (double x, double y)
void SetWeightCutTrackFit (double value)
void SetWeightingFunction (LKHTWeightingFunction *wf)
void SetWFConst ()
void SetWFGivenWeight ()
void SetWFInverse ()
void SetWFLinear ()
void Transform ()
virtual ~LKHTLineTracker ()
Public Member Functions inherited from LKPadInteractive
void AddInteractivePad (TVirtualPad *pad, TString option="")
virtual void ExecMouseClickEventOnPad (TVirtualPad *pad, double xOnClick, double yOnClick)
int GetPadInteractiveID () const
LKPadInteractive ()
void SetPadInteractiveID (int id)
virtual ~LKPadInteractive ()
Private Member Functions
ClassDef (LKHTLineTracker, 1)
Private Attributes
LKVector3::Axis fA1 = LKVector3::kX
LKVector3::Axis fA2 = LKVector3::kY
double fBinSizeImageSpace [2] = {0}
double fBinSizeMaxImageSpace = 0
double fBinSizeMaxParamSpace = 0
double fBinSizeParamSpace [2] = {0}
bool fClickedPadImage = true
LKParamPointRT * fClickSelectedParamPoint = nullptr
int fCorrelateType = kCorrelateBoxBand
int fCutNumTrackHits = 3
TGraph * fGraphBand = nullptr
TGraph * fGraphClicked = nullptr
TGraph * fGraphClickFitted = nullptr
TGraphErrors * fGraphImageData = nullptr
TGraphErrors * fGraphSelectedImageData = nullptr
TH2D * fHistImage = nullptr
TH2D * fHistParam = nullptr
TObjArray * fHitArray = nullptr
int fIdxSelectedR = -1
int fIdxSelectedT = -1
LKImagePoint * fImagePoint = nullptr
TClonesArray * fImagePointArray = nullptr
bool fInitializedImageData = false
bool fInitializedParamData = false
LKODRFitter * fLineFitter = nullptr
double fMaxWeightingDistance = 0
int fNumBinsImageSpace [2] = {10,10}
int fNumBinsParamSpace [2] = {10,10}
int fNumHits = 0
int fNumImagePoints = 0
int fNumLinearTracks = 0
TPad * fPadImage = nullptr
TPad * fPadParam = nullptr
double ** fParamData
LKParamPointRT * fParamPoint = nullptr
int fProcess = kNon
double fRangeImageSpace [2][2] = {{0}}
double fRangeParamSpace [2][2] = {{0}}
double fRangeParamSpaceInit [2][2] = {{0}}
TObjArray * fSelectedHitArray = nullptr
vector< int > fSelectedImagePointIdxs
TClonesArray * fTrackArray = nullptr
TVector3 fTransformCenter
double fWeightCutTrackFit = 0.2
LKHTWeightingFunction * fWeightingFunction = nullptr
const int kAddPoints = 1
const int kClear = 5
const int kClearPoints = 6
const int kCorrelateBoxBand = 3
const int kCorrelateBoxLine = 1
const int kCorrelateBoxRibbon = 2
const int kCorrelatePointBand = 0
const int kDeTransformPoints = 8
const int kFitTrack = 4
const int kNon = 0
const int kRemovePoints = 7
const int kSelectPoints = 3
const int kTransform = 2
Additional Inherited Members
Protected Attributes inherited from LKPadInteractive
int fPadInteractiveID = -1
Detailed Description
LKHTLineTracker is tool for finding and fitting a straight line track from a provided list of hits.
Abriviations for this document
Parameters
HT Hough Transform
IMS Image Space
IMP Image Point
IMB Image point Box : box representing the bin-range or error of image point.
PMS Parameter Space
PMP Parameter Point
PML Parameter point presented as a Line
PMB Parameter point presented as a Band
PML Radial Line comming out from the transform center
TC Transform Center : A origin point of Hough transform
WF Weighting Function
Definitions
The Hough transform (HT) introduces parameter space (PMS) to find the appropriate parameters for the given model, which, in this case, is a straight line. The space describing the real dimensions (x, y) is referred to as image space (IMS), while the space describing the parameters of a model, (a straight line for this case,) (radius and theta) is referred to as PMS. Each space is defined as classes LKImagePoint and LKParamPointRT.
We define a line; Parameter presented as a Line (PML), which is a straight line defined by two parameters selected from parameter space. The first parameter, "radius," represents the length of the radial line (PML) extending from the transform center. At the end of the PML, a PML is drawn perpendicular to it. The angle between the x-axis and the PML defines the second parameter, "theta". Thus, the angle between the x-axis and the PML is theta + 90 degrees. Note that the unit of angles used within this method is degrees.
Parameters
Transform-Center (TC) The transform center is the position in IMS where the HT will be performed. The choice of the transform center will affect the results. It must be set using SetTransformCenter().
Image-space-range The number of bins, minimum and maximum ranges for x and y, must be set. It must be set using SetImageSpaceRange().
Param-space-range The number of bins for radius and theta parameters should be set. The range of the radius is automatically calculated using the transform center and IMS range. The binning does not need to be finer than 200x200 (in cases the case of TPCs with "average" spatial resolution for example), if the HT is employed only for the purpose of collecting hits and not for fitting tracks. It must be set using SetParamSpaceBins(). In case user wants to set the full range of radius and theta, it can be set using SetParamSpaceRange(). For line fitting, the FitTrackWithParamPoint() method can be used.
Correlator Choose from the following options. More descriptions are given below paragraph.
Point-Band correlator : SetCorrelatePointBand()
Box-Line correlator : SetCorrelateBoxLine()
Box-Ribbon correlator : SetCorrelateBoxRibbon()
Box-Band correlator : SetCorrelateBoxBand()
Correlators
While the PML represents the line defined from the central value of the selected bin in PMS, a band; Parameter presented as a Band (PMB), represents the range that includes all parameter values within the selected bin range in PMS. It needs to be noted that each image point (IMP) also has its error represented by the bin in IMS. This definition will help understanding the correlator description below:
There are four correlation methods to choose from:
Point-Band correlator : This correlator checks if the PMB include the center point of the image point box (IMB). This method doos not care of the point error and take care of parameter point (PMP) error. The speed of correlator is the fastest out of all.
Box-Line correlator : This correlator checks if the PML passes through the IMB. By selecting this correlator, the PMP will be filled up only when the line precisely intersects the IMB. This method take care of the point error and do not take care of PMP error. This method is slower than Point-Band correlator. It is not recommanded to use this method unless one understands what this actually does.
Box-Band correlator : This correlator verifies whether there is an overlap between the PMB and the IMB. The correlation condition is less strict compared to the Point-Band and Box-Line correlators, but it is more reasonable because both the PMP and the PMP are represented as bin boxes rather than single points. This method provides a general explanation for and is suitable for detectors with average spatial resolution. However this method is slower than Point-Band and Box-Line correlators.
Box-RBand correlator : This correlator is similar to Box-Band correlator. However, r-band is defined only using the center theta value. This means that r-band do not overlap with the other neighboring parameter bins with same theta range. This correlator is default option.
Weighting function
Weighting function is a function that gives weight value to fill up the PMS bin by correlating with IMB. Defualt weighting function is LKHoughWFInverse. The weight in LKHoughWFInverse is defined by: weight = [IMP weight] * [IMP error] / ([distance from IMP to PML] + [IMP error]) Other weighting functions can be found in LKHTLineTracker.h. It is also possible to create an user defined weighting function by inheriting LKHTLineTracker class.
Usage of HT
The author of this method does not recommend the use of the HT method as a track fitter. The HT tool is efficient when it comes to grouping, But its performance as a fitter is limited by various factors. Instead, The author recommand to find the group of hits, then use FitTrackWithParamPoint() method which employ the least chi-squared method to fit straight line.
If one intends to employ HT for the fitter, it's needed to use the smallest possible PMS binning to meet the user's desired resolution. If the spatial resolution is not impressive, the Box-Band correlator should be used. However, these adjustments will increase computation time. Even if good track parameters are identified, there's no assurance that the fit result will be superior to the least chi-squared method. In case of situation where only a single track exist in the event, small number of bins for PMS can be used along with RetransformFromLastParamPoint() method. RetransformFromLastParamPoint() method find the maximum PMS-bin, and recalculate HT parameters to range PMS within the selected bin. After, the Transform() method will be called which is equalivant to dividing PMS in to n^2 x m^2 bins, where nxm is the binning chosen by the user.
Example macro
{
     auto tracker = new LKHTLineTracker();
     tracker -> SetTransformCenter(0,0);
     tracker -> SetImageSpaceRange(120, -150, 150, 120, 0, 500);
     tracker -> SetParamSpaceBins(numBinsR, numBinsT);
     for (...) {
         tracker -> AddImagePoint(x, xerror, y, yerror, weight);
     }
     tracker -> SetCorrelateBoxBand();
     tracker -> Transform();
     auto paramPoint = tracker -> FindNextMaximumParamPoint();
     track = tracker -> FitTrackWithParamPoint(paramPoint);
}
Todo:
performance & parameters guide
Definition at line 202 of file LKHTLineTracker.h.
Constructor & Destructor Documentation
LKHTLineTracker()
LKHTLineTracker::LKHTLineTracker ()
Definition at line 9 of file LKHTLineTracker.cpp.
References Clear(), fHitArray, fImagePoint, fImagePointArray, fLineFitter, fParamPoint, fSelectedHitArray, fTrackArray, and LKODRFitter::GetFitter().
~LKHTLineTracker()
virtual LKHTLineTracker::~LKHTLineTracker () inline virtual
Definition at line 206 of file LKHTLineTracker.h.
Member Function Documentation
AddHistogram()
void LKHTLineTracker::AddHistogram (TH2 * hist)
Add 2-dimensional histogram to set image space range and add data for each bin. Users do not need to call SetImageSpaceRange when using this method.
Definition at line 86 of file LKHTLineTracker.cpp.
References AddImagePointBox(), SetImageSpaceRange(), and y2.
AddHit()
void LKHTLineTracker::AddHit (LKHit * hit, LKVector3::Axis a1, LKVector3::Axis a2, double weightHT = 1)
Definition at line 254 of file LKHTLineTracker.cpp.
References AddImagePoint(), fA1, fA2, fHitArray, fNumHits, and LKHit::WeightPositionError().
Referenced by FitTrack3DWithParamPoint(), and FitTrackWithParamPoint().
AddImagePoint()
void LKHTLineTracker::AddImagePoint (double x, double xError, double y, double yError, double weightHT = 1, double weightFit = -1)
Definition at line 265 of file LKHTLineTracker.cpp.
References fImagePointArray, fNumImagePoints, fProcess, kAddPoints, SetPoint(), and y2.
Referenced by AddHit().
AddImagePointBox()
void LKHTLineTracker::AddImagePointBox (double x1, double y1, double x2, double y2, double weightHT = 1, double weightFit = -1)
Definition at line 278 of file LKHTLineTracker.cpp.
References fImagePointArray, fNumImagePoints, fProcess, kAddPoints, SetPoint(), and y2.
Referenced by AddHistogram().
ClassDef()
LKHTLineTracker::ClassDef (LKHTLineTracker , 1) private
CleanLastParamPoint()
void LKHTLineTracker::CleanLastParamPoint (double rWidth = -1, double tWidth = -1)
Definition at line 589 of file LKHTLineTracker.cpp.
References fBinSizeParamSpace, fIdxSelectedR, fIdxSelectedT, fNumBinsParamSpace, fParamData, and fRangeParamSpace.
Clear()
void LKHTLineTracker::Clear (Option_t * option = "")
Definition at line 47 of file LKHTLineTracker.cpp.
References Clear(), fBinSizeMaxParamSpace, fBinSizeParamSpace, fHitArray, fIdxSelectedR, fIdxSelectedT, fImagePointArray, fInitializedParamData, fNumBinsParamSpace, fNumHits, fNumImagePoints, fNumLinearTracks, fParamData, fProcess, fRangeParamSpace, fRangeParamSpaceInit, fTrackArray, and kClear.
Referenced by Clear(), ClearPoints(), GetParamPoint(), LKHTLineTracker(), and SelectPoints().
ClearPoints()
void LKHTLineTracker::ClearPoints ()
Reset parameter space range and parameter data. Clear track-array, hit-array, and point-array.
Definition at line 77 of file LKHTLineTracker.cpp.
References Clear(), fHitArray, fImagePointArray, fNumHits, fNumImagePoints, fProcess, and kClearPoints.
DeTransformSelectedPoints()
void LKHTLineTracker::DeTransformSelectedPoints ()
Definition at line 444 of file LKHTLineTracker.cpp.
References fBinSizeParamSpace, fCorrelateType, fIdxSelectedR, fIdxSelectedT, fImagePointArray, fNumBinsParamSpace, fParamData, fProcess, fRangeParamSpace, fSelectedHitArray, fTransformCenter, fWeightingFunction, GetParamPoint(), kCorrelateBoxBand, kCorrelateBoxLine, kCorrelateBoxRibbon, kCorrelatePointBand, and kDeTransformPoints.
Draw() [1/5]
void LKHTLineTracker::Draw (TString option = "")
Definition at line 1010 of file LKHTLineTracker.cpp.
References cvs, Draw(), and LKWindowManager::GetWindowManager().
Draw() [2/5]
void LKHTLineTracker::Draw (TVirtualPad * padImage, TVirtualPad * padParam) inline
Definition at line 318 of file LKHTLineTracker.h.
References Draw().
Referenced by Draw().
Draw() [3/5]
void LKHTLineTracker::Draw (TVirtualPad * padImage, TVirtualPad * padParam, LKParamPointRT * paramPoint) inline
Definition at line 316 of file LKHTLineTracker.h.
References Draw().
Referenced by Draw().
Draw() [4/5]
void LKHTLineTracker::Draw (TVirtualPad * padImage, TVirtualPad * padParam, LKParamPointRT * paramPoint, TString option)
Definition at line 962 of file LKHTLineTracker.cpp.
References LKPadInteractive::AddInteractivePad(), Draw(), e_info, ExecMouseClickEventOnPad(), fHistImage, fHistParam, fPadImage, LKPadInteractive::fPadInteractiveID, fPadParam, GetDataGraphImageSpace(), GetHistImageSpace(), GetHistParamSpace(), LKParamPointRT::GetR0(), LKParamPointRT::GetT0(), and Reset().
Referenced by Draw(), Draw(), DrawAllParamBands(), DrawAllParamLines(), and ExecMouseClickEventOnPad().
Draw() [5/5]
void LKHTLineTracker::Draw (TVirtualPad * padImage, TVirtualPad * padParam, TString option) inline
Definition at line 317 of file LKHTLineTracker.h.
References Draw().
Referenced by Draw().
DrawAllParamBands()
void LKHTLineTracker::DrawAllParamBands ()
Definition at line 860 of file LKHTLineTracker.cpp.
References Draw(), fNumBinsParamSpace, fRangeImageSpace, and GetParamPoint().
DrawAllParamLines()
void LKHTLineTracker::DrawAllParamLines (int i = -1, bool drawRadialLine = true)
Definition at line 832 of file LKHTLineTracker.cpp.
References Draw(), fBinSizeMaxImageSpace, fNumBinsParamSpace, fRangeImageSpace, and GetParamPoint().
ExecMouseClickEventOnPad()
void LKHTLineTracker::ExecMouseClickEventOnPad (TVirtualPad * pad, double xOnClick, double yOnClick) virtual
Reimplemented from LKPadInteractive.
Definition at line 1017 of file LKHTLineTracker.cpp.
References Draw(), e_error, fClickedPadImage, fClickSelectedParamPoint, fGraphBand, fGraphClicked, fGraphClickFitted, fHistParam, FitTrackWithParamPoint(), fPadImage, fPadParam, fRangeImageSpace, GetParamPoint(), GetSelectedDataGraph(), LKVector3::kX, LKVector3::kY, Print(), SetPoint(), and y2.
Referenced by Draw().
FindNextMaximumParamPoint()
LKParamPointRT * LKHTLineTracker::FindNextMaximumParamPoint ()
Definition at line 553 of file LKHTLineTracker.cpp.
References fIdxSelectedR, fIdxSelectedT, fNumBinsParamSpace, fParamData, fParamPoint, fTransformCenter, GetParamPoint(), lk_debug, and SetPoint().
FitTrack()
LKLinearTrack * LKHTLineTracker::FitTrack (LKParamPointRT * paramPoint, double weightCut = -1) inline
Used hits(points) will be removed from the hit array.
Definition at line 300 of file LKHTLineTracker.h.
References FitTrackWithParamPoint().
FitTrack3D()
LKLinearTrack * LKHTLineTracker::FitTrack3D (LKParamPointRT * paramPoint, double weightCut = -1) inline
Definition at line 301 of file LKHTLineTracker.h.
References FitTrack3DWithParamPoint().
FitTrack3DWithParamPoint()
LKLinearTrack * LKHTLineTracker::FitTrack3DWithParamPoint (LKParamPointRT * paramPoint, double weightCut = -1)
Used hits(points) will be removed from the hit array.
Definition at line 777 of file LKHTLineTracker.cpp.
References AddHit(), fCutNumTrackHits, fLineFitter, fNumLinearTracks, fProcess, fRangeImageSpace, fSelectedHitArray, fTrackArray, fWeightCutTrackFit, LKODRFitter::GetDirection(), LKODRFitter::GetNumPoints(), LKODRFitter::GetRMSLine(), kFitTrack, kSelectPoints, next(), Reset(), SelectPoints(), LKHit::WeightPositionError(), LKHit::X(), LKHit::Y(), and LKHit::Z().
Referenced by FitTrack3D().
FitTrackWithParamPoint()
LKLinearTrack * LKHTLineTracker::FitTrackWithParamPoint (LKParamPointRT * paramPoint, double weightCut = -1)
Definition at line 720 of file LKHTLineTracker.cpp.
References AddHit(), fCutNumTrackHits, fLineFitter, fNumLinearTracks, fProcess, fRangeImageSpace, fSelectedHitArray, fSelectedImagePointIdxs, fTrackArray, fWeightCutTrackFit, fWeightingFunction, LKODRFitter::GetDirection(), GetImagePoint(), LKODRFitter::GetNumPoints(), LKODRFitter::GetRMSLine(), kFitTrack, kSelectPoints, next(), Reset(), and SelectPoints().
Referenced by ExecMouseClickEventOnPad(), and FitTrack().
GetCorrelatorName()
TString LKHTLineTracker::GetCorrelatorName () const inline
Definition at line 245 of file LKHTLineTracker.h.
References fCorrelateType, kCorrelateBoxBand, kCorrelateBoxLine, kCorrelateBoxRibbon, and kCorrelatePointBand.
Referenced by GetHistImageSpace(), GetHistParamSpace(), and Print().
GetCurrentMaximumParamPoint()
LKParamPointRT * LKHTLineTracker::GetCurrentMaximumParamPoint () inline
Definition at line 293 of file LKHTLineTracker.h.
References fParamPoint.
GetDataGraphImageSpace()
TGraphErrors * LKHTLineTracker::GetDataGraphImageSpace ()
Definition at line 904 of file LKHTLineTracker.cpp.
References fGraphImageData, fImagePointArray, fNumImagePoints, and SetPoint().
Referenced by Draw().
GetHistImageSpace()
TH2D * LKHTLineTracker::GetHistImageSpace (TString name = "", TString title = "")
Definition at line 874 of file LKHTLineTracker.cpp.
References fHistImage, fImagePointArray, fNumBinsImageSpace, fNumBinsParamSpace, fNumImagePoints, fRangeImageSpace, fTransformCenter, and GetCorrelatorName().
Referenced by Draw().
GetHistParamSpace()
TH2D * LKHTLineTracker::GetHistParamSpace (TString name = "", TString title = "")
Definition at line 944 of file LKHTLineTracker.cpp.
References fNumBinsParamSpace, fParamData, fRangeParamSpace, and GetCorrelatorName().
Referenced by Draw().
GetHitArray()
TObjArray * LKHTLineTracker::GetHitArray () inline
Definition at line 225 of file LKHTLineTracker.h.
References fHitArray.
GetImagePoint()
LKImagePoint * LKHTLineTracker::GetImagePoint (int i)
Definition at line 287 of file LKHTLineTracker.cpp.
References fImagePointArray.
Referenced by FitTrackWithParamPoint(), SelectPoints(), and Transform().
GetMaxWeightingDistance()
double LKHTLineTracker::GetMaxWeightingDistance (double distance) const inline
Definition at line 224 of file LKHTLineTracker.h.
References fMaxWeightingDistance.
GetNumBinsImageSpace()
int LKHTLineTracker::GetNumBinsImageSpace (int ixy) const inline
Definition at line 217 of file LKHTLineTracker.h.
References fNumBinsImageSpace.
GetNumBinsParamSpace()
int LKHTLineTracker::GetNumBinsParamSpace (int ixy) const inline
Definition at line 218 of file LKHTLineTracker.h.
References fNumBinsParamSpace.
GetNumImagePoints()
int LKHTLineTracker::GetNumImagePoints () const inline
Definition at line 222 of file LKHTLineTracker.h.
References fNumImagePoints.
Referenced by DrawEvent(), and TTHTBeamTrackingTask::Exec().
GetNumParamPoints()
int LKHTLineTracker::GetNumParamPoints () const inline
Definition at line 223 of file LKHTLineTracker.h.
References fNumBinsParamSpace.
GetParamData()
double ** LKHTLineTracker::GetParamData () const inline
Definition at line 221 of file LKHTLineTracker.h.
References fParamData.
GetParamPoint() [1/2]
LKParamPointRT * LKHTLineTracker::GetParamPoint (int i)
Definition at line 300 of file LKHTLineTracker.cpp.
References Clear(), fBinSizeParamSpace, fNumBinsParamSpace, fParamData, fParamPoint, fRangeParamSpace, fTransformCenter, SetPoint(), t1, and t2.
Referenced by DeTransformSelectedPoints(), DrawAllParamBands(), DrawAllParamLines(), ExecMouseClickEventOnPad(), FindNextMaximumParamPoint(), ReinitializeFromLastParamPoint(), and Transform().
GetParamPoint() [2/2]
LKParamPointRT * LKHTLineTracker::GetParamPoint (int ir, int it)
Definition at line 323 of file LKHTLineTracker.cpp.
References fBinSizeParamSpace, fParamData, fParamPoint, fRangeParamSpace, fTransformCenter, SetPoint(), t1, and t2.
GetProcessName()
TString LKHTLineTracker::GetProcessName () const inline
Definition at line 254 of file LKHTLineTracker.h.
References fProcess, kAddPoints, kClear, kClearPoints, kFitTrack, kNon, kSelectPoints, and kTransform.
Referenced by Print().
GetRangeImageSpace()
double LKHTLineTracker::GetRangeImageSpace (int ixy, int i) const inline
Definition at line 219 of file LKHTLineTracker.h.
References fRangeImageSpace.
Referenced by DrawEvent().
GetRangeParamSpace()
double LKHTLineTracker::GetRangeParamSpace (int ixy, int i) const inline
Definition at line 220 of file LKHTLineTracker.h.
References fRangeParamSpace.
GetSelectedDataGraph()
TGraphErrors * LKHTLineTracker::GetSelectedDataGraph (LKParamPointRT * paramPoint)
Definition at line 920 of file LKHTLineTracker.cpp.
References fCorrelateType, fGraphSelectedImageData, fImagePointArray, fNumImagePoints, kCorrelateBoxBand, and SetPoint().
Referenced by ExecMouseClickEventOnPad().
GetSelectedHitArray()
TObjArray * LKHTLineTracker::GetSelectedHitArray () inline
Definition at line 226 of file LKHTLineTracker.h.
References fSelectedHitArray.
GetTransformCenter()
TVector3 LKHTLineTracker::GetTransformCenter () const inline
Definition at line 216 of file LKHTLineTracker.h.
References fTransformCenter.
Init()
bool LKHTLineTracker::Init ()
Definition at line 21 of file LKHTLineTracker.cpp.
IsCorrelateBoxBand()
bool LKHTLineTracker::IsCorrelateBoxBand () inline
Definition at line 269 of file LKHTLineTracker.h.
References fCorrelateType, and kCorrelateBoxBand.
IsCorrelateBoxLine()
bool LKHTLineTracker::IsCorrelateBoxLine () inline
Definition at line 267 of file LKHTLineTracker.h.
References fCorrelateType, and kCorrelateBoxLine.
IsCorrelateBoxRibbon()
bool LKHTLineTracker::IsCorrelateBoxRibbon () inline
Definition at line 268 of file LKHTLineTracker.h.
References fCorrelateType, and kCorrelateBoxRibbon.
IsCorrelatePointBand()
bool LKHTLineTracker::IsCorrelatePointBand () inline
Definition at line 266 of file LKHTLineTracker.h.
References fCorrelateType, and kCorrelatePointBand.
PopImagePoint()
LKImagePoint * LKHTLineTracker::PopImagePoint (int i)
Definition at line 293 of file LKHTLineTracker.cpp.
References fImagePointArray.
Referenced by RemoveSelectedPoints().
Print()
void LKHTLineTracker::Print (Option_t * option = "") const
Definition at line 113 of file LKHTLineTracker.cpp.
References e_info, fNumBinsImageSpace, fNumBinsParamSpace, fNumImagePoints, fRangeImageSpace, fRangeParamSpace, fTransformCenter, GetCorrelatorName(), and GetProcessName().
Referenced by ExecMouseClickEventOnPad().
ReinitializeFromLastParamPoint()
LKParamPointRT * LKHTLineTracker::ReinitializeFromLastParamPoint ()
Definition at line 611 of file LKHTLineTracker.cpp.
References fBinSizeMaxParamSpace, fBinSizeParamSpace, fIdxSelectedR, fIdxSelectedT, fInitializedParamData, fNumBinsParamSpace, fParamData, fParamPoint, fRangeParamSpace, fTransformCenter, GetParamPoint(), and SetPoint().
Referenced by RetransformFromLastParamPoint().
RemoveSelectedPoints()
void LKHTLineTracker::RemoveSelectedPoints ()
Definition at line 699 of file LKHTLineTracker.cpp.
References fHitArray, fImagePointArray, fNumImagePoints, fProcess, fSelectedHitArray, fSelectedImagePointIdxs, kRemovePoints, next(), and PopImagePoint().
Reset()
void LKHTLineTracker::Reset ()
Reset parameter space range and parameter data.
Definition at line 26 of file LKHTLineTracker.cpp.
References fBinSizeMaxParamSpace, fBinSizeParamSpace, fIdxSelectedR, fIdxSelectedT, fInitializedParamData, fNumBinsParamSpace, fParamData, fRangeParamSpace, and fRangeParamSpaceInit.
Referenced by Draw(), FitTrack3DWithParamPoint(), and FitTrackWithParamPoint().
RetransformFromLastParamPoint()
void LKHTLineTracker::RetransformFromLastParamPoint ()
Definition at line 658 of file LKHTLineTracker.cpp.
References ReinitializeFromLastParamPoint(), and Transform().
SelectPoints()
void LKHTLineTracker::SelectPoints (LKParamPointRT * paramPoint, double weightCut = -1)
Definition at line 664 of file LKHTLineTracker.cpp.
References Clear(), fCorrelateType, fHitArray, fNumImagePoints, fProcess, fSelectedHitArray, fSelectedImagePointIdxs, fWeightCutTrackFit, fWeightingFunction, GetImagePoint(), kCorrelateBoxBand, and kSelectPoints.
Referenced by FitTrack3DWithParamPoint(), and FitTrackWithParamPoint().
SetCorrelateBoxBand()
void LKHTLineTracker::SetCorrelateBoxBand ()
Definition at line 154 of file LKHTLineTracker.cpp.
References fCorrelateType, fWeightingFunction, kCorrelateBoxBand, and SetWFGivenWeight().
Referenced by Transform().
SetCorrelateBoxLine()
void LKHTLineTracker::SetCorrelateBoxLine ()
Definition at line 140 of file LKHTLineTracker.cpp.
References fCorrelateType, fWeightingFunction, kCorrelateBoxLine, and SetWFGivenWeight().
SetCorrelateBoxRibbon()
void LKHTLineTracker::SetCorrelateBoxRibbon ()
Definition at line 147 of file LKHTLineTracker.cpp.
References fCorrelateType, fWeightingFunction, kCorrelateBoxRibbon, and SetWFGivenWeight().
SetCorrelatePointBand()
void LKHTLineTracker::SetCorrelatePointBand ()
Definition at line 133 of file LKHTLineTracker.cpp.
References fCorrelateType, fWeightingFunction, kCorrelatePointBand, and SetWFGivenWeight().
SetCutNumTrackHits()
void LKHTLineTracker::SetCutNumTrackHits (double value) inline
Definition at line 276 of file LKHTLineTracker.h.
References fCutNumTrackHits.
SetImageData()
void LKHTLineTracker::SetImageData (double ** imageData)
SetImageSpaceRange()
void LKHTLineTracker::SetImageSpaceRange (int nx, double x1, double x2, int ny, double y1, double y2)
Definition at line 161 of file LKHTLineTracker.cpp.
References fBinSizeImageSpace, fBinSizeMaxImageSpace, fMaxWeightingDistance, fNumBinsImageSpace, fRangeImageSpace, and y2.
Referenced by AddHistogram().
SetMaxWeightingDistance()
void LKHTLineTracker::SetMaxWeightingDistance (double distance) inline
Definition at line 275 of file LKHTLineTracker.h.
References fMaxWeightingDistance.
SetParamSpaceBins()
void LKHTLineTracker::SetParamSpaceBins (int nr, int nt)
Definition at line 178 of file LKHTLineTracker.cpp.
References e_warning, fInitializedParamData, fRangeImageSpace, fTransformCenter, SetParamSpaceRange(), t1, t2, v3Diff, x0, and y0.
SetParamSpaceRange()
void LKHTLineTracker::SetParamSpaceRange (int nr, double r2, double r1, int nt, double t1, double t2)
Definition at line 216 of file LKHTLineTracker.cpp.
References e_warning, fBinSizeMaxParamSpace, fBinSizeParamSpace, fInitializedParamData, fNumBinsParamSpace, fParamData, fRangeParamSpace, fRangeParamSpaceInit, t1, and t2.
Referenced by SetParamSpaceBins().
SetTransformCenter()
void LKHTLineTracker::SetTransformCenter (double x, double y) inline
Definition at line 234 of file LKHTLineTracker.h.
References fTransformCenter.
SetWeightCutTrackFit()
void LKHTLineTracker::SetWeightCutTrackFit (double value) inline
Definition at line 241 of file LKHTLineTracker.h.
References fWeightCutTrackFit.
SetWeightingFunction()
void LKHTLineTracker::SetWeightingFunction (LKHTWeightingFunction * wf) inline
Definition at line 283 of file LKHTLineTracker.h.
References fWeightingFunction.
SetWFConst()
void LKHTLineTracker::SetWFConst () inline
Definition at line 278 of file LKHTLineTracker.h.
References fWeightingFunction.
SetWFGivenWeight()
void LKHTLineTracker::SetWFGivenWeight () inline
Definition at line 281 of file LKHTLineTracker.h.
References fWeightingFunction.
Referenced by SetCorrelateBoxBand(), SetCorrelateBoxLine(), SetCorrelateBoxRibbon(), and SetCorrelatePointBand().
SetWFInverse()
void LKHTLineTracker::SetWFInverse () inline
Definition at line 280 of file LKHTLineTracker.h.
References fWeightingFunction.
SetWFLinear()
void LKHTLineTracker::SetWFLinear () inline
Definition at line 279 of file LKHTLineTracker.h.
References fWeightingFunction.
Transform()
void LKHTLineTracker::Transform ()
Definition at line 333 of file LKHTLineTracker.cpp.
References e_warning, fBinSizeParamSpace, fCorrelateType, fIdxSelectedR, fIdxSelectedT, fNumBinsParamSpace, fNumImagePoints, fParamData, fProcess, fRangeParamSpace, fTransformCenter, fWeightingFunction, GetImagePoint(), GetParamPoint(), kCorrelateBoxBand, kCorrelateBoxLine, kCorrelateBoxRibbon, kCorrelatePointBand, kTransform, and SetCorrelateBoxBand().
Referenced by RetransformFromLastParamPoint().
Member Data Documentation
fA1
LKVector3::Axis LKHTLineTracker::fA1 = LKVector3::kX private
Definition at line 343 of file LKHTLineTracker.h.
Referenced by AddHit().
fA2
LKVector3::Axis LKHTLineTracker::fA2 = LKVector3::kY private
Definition at line 344 of file LKHTLineTracker.h.
Referenced by AddHit().
fBinSizeImageSpace
double LKHTLineTracker::fBinSizeImageSpace[2] = {0} private
Definition at line 329 of file LKHTLineTracker.h.
Referenced by SetImageSpaceRange().
fBinSizeMaxImageSpace
double LKHTLineTracker::fBinSizeMaxImageSpace = 0 private
Definition at line 331 of file LKHTLineTracker.h.
Referenced by DrawAllParamLines(), and SetImageSpaceRange().
fBinSizeMaxParamSpace
double LKHTLineTracker::fBinSizeMaxParamSpace = 0 private
Definition at line 332 of file LKHTLineTracker.h.
Referenced by Clear(), ReinitializeFromLastParamPoint(), Reset(), and SetParamSpaceRange().
fBinSizeParamSpace
double LKHTLineTracker::fBinSizeParamSpace[2] = {0} private
Definition at line 330 of file LKHTLineTracker.h.
Referenced by CleanLastParamPoint(), Clear(), DeTransformSelectedPoints(), GetParamPoint(), GetParamPoint(), ReinitializeFromLastParamPoint(), Reset(), SetParamSpaceRange(), and Transform().
fClickedPadImage
bool LKHTLineTracker::fClickedPadImage = true private
Definition at line 354 of file LKHTLineTracker.h.
Referenced by ExecMouseClickEventOnPad().
fClickSelectedParamPoint
LKParamPointRT* LKHTLineTracker::fClickSelectedParamPoint = nullptr private
Definition at line 355 of file LKHTLineTracker.h.
Referenced by ExecMouseClickEventOnPad().
fCorrelateType
int LKHTLineTracker::fCorrelateType = kCorrelateBoxBand private
Definition at line 368 of file LKHTLineTracker.h.
Referenced by DeTransformSelectedPoints(), GetCorrelatorName(), GetSelectedDataGraph(), IsCorrelateBoxBand(), IsCorrelateBoxLine(), IsCorrelateBoxRibbon(), IsCorrelatePointBand(), SelectPoints(), SetCorrelateBoxBand(), SetCorrelateBoxLine(), SetCorrelateBoxRibbon(), SetCorrelatePointBand(), and Transform().
fCutNumTrackHits
int LKHTLineTracker::fCutNumTrackHits = 3 private
Definition at line 361 of file LKHTLineTracker.h.
Referenced by FitTrack3DWithParamPoint(), FitTrackWithParamPoint(), and SetCutNumTrackHits().
fGraphBand
TGraph* LKHTLineTracker::fGraphBand = nullptr private
Definition at line 393 of file LKHTLineTracker.h.
Referenced by ExecMouseClickEventOnPad().
fGraphClicked
TGraph* LKHTLineTracker::fGraphClicked = nullptr private
Definition at line 399 of file LKHTLineTracker.h.
Referenced by ExecMouseClickEventOnPad().
fGraphClickFitted
TGraph* LKHTLineTracker::fGraphClickFitted = nullptr private
Definition at line 356 of file LKHTLineTracker.h.
Referenced by ExecMouseClickEventOnPad().
fGraphImageData
TGraphErrors* LKHTLineTracker::fGraphImageData = nullptr private
Definition at line 373 of file LKHTLineTracker.h.
Referenced by GetDataGraphImageSpace().
fGraphSelectedImageData
TGraphErrors* LKHTLineTracker::fGraphSelectedImageData = nullptr private
Definition at line 374 of file LKHTLineTracker.h.
Referenced by GetSelectedDataGraph().
fHistImage
TH2D* LKHTLineTracker::fHistImage = nullptr private
Definition at line 379 of file LKHTLineTracker.h.
Referenced by Draw(), and GetHistImageSpace().
fHistParam
TH2D* LKHTLineTracker::fHistParam = nullptr private
Definition at line 380 of file LKHTLineTracker.h.
Referenced by Draw(), and ExecMouseClickEventOnPad().
fHitArray
TObjArray* LKHTLineTracker::fHitArray = nullptr private
Definition at line 342 of file LKHTLineTracker.h.
Referenced by AddHit(), Clear(), ClearPoints(), GetHitArray(), LKHTLineTracker(), RemoveSelectedPoints(), and SelectPoints().
fIdxSelectedR
int LKHTLineTracker::fIdxSelectedR = -1 private
Definition at line 337 of file LKHTLineTracker.h.
Referenced by CleanLastParamPoint(), Clear(), DeTransformSelectedPoints(), FindNextMaximumParamPoint(), ReinitializeFromLastParamPoint(), Reset(), and Transform().
fIdxSelectedT
int LKHTLineTracker::fIdxSelectedT = -1 private
Definition at line 338 of file LKHTLineTracker.h.
Referenced by CleanLastParamPoint(), Clear(), DeTransformSelectedPoints(), FindNextMaximumParamPoint(), ReinitializeFromLastParamPoint(), Reset(), and Transform().
fImagePoint
LKImagePoint* LKHTLineTracker::fImagePoint = nullptr private
Definition at line 351 of file LKHTLineTracker.h.
Referenced by LKHTLineTracker().
fImagePointArray
TClonesArray* LKHTLineTracker::fImagePointArray = nullptr private
Definition at line 350 of file LKHTLineTracker.h.
Referenced by AddImagePoint(), AddImagePointBox(), Clear(), ClearPoints(), DeTransformSelectedPoints(), GetDataGraphImageSpace(), GetHistImageSpace(), GetImagePoint(), GetSelectedDataGraph(), LKHTLineTracker(), PopImagePoint(), and RemoveSelectedPoints().
fInitializedImageData
bool LKHTLineTracker::fInitializedImageData = false private
Definition at line 325 of file LKHTLineTracker.h.
fInitializedParamData
bool LKHTLineTracker::fInitializedParamData = false private
Definition at line 326 of file LKHTLineTracker.h.
Referenced by Clear(), ReinitializeFromLastParamPoint(), Reset(), SetParamSpaceBins(), and SetParamSpaceRange().
fLineFitter
LKODRFitter* LKHTLineTracker::fLineFitter = nullptr private
Definition at line 362 of file LKHTLineTracker.h.
Referenced by FitTrack3DWithParamPoint(), FitTrackWithParamPoint(), and LKHTLineTracker().
fMaxWeightingDistance
double LKHTLineTracker::fMaxWeightingDistance = 0 private
Definition at line 339 of file LKHTLineTracker.h.
Referenced by GetMaxWeightingDistance(), SetImageSpaceRange(), and SetMaxWeightingDistance().
fNumBinsImageSpace
int LKHTLineTracker::fNumBinsImageSpace[2] = {10,10} private
Definition at line 327 of file LKHTLineTracker.h.
Referenced by GetHistImageSpace(), GetNumBinsImageSpace(), Print(), and SetImageSpaceRange().
fNumBinsParamSpace
int LKHTLineTracker::fNumBinsParamSpace[2] = {10,10} private
Definition at line 328 of file LKHTLineTracker.h.
Referenced by CleanLastParamPoint(), Clear(), DeTransformSelectedPoints(), DrawAllParamBands(), DrawAllParamLines(), FindNextMaximumParamPoint(), GetHistImageSpace(), GetHistParamSpace(), GetNumBinsParamSpace(), GetNumParamPoints(), GetParamPoint(), Print(), ReinitializeFromLastParamPoint(), Reset(), SetParamSpaceRange(), and Transform().
fNumHits
int LKHTLineTracker::fNumHits = 0 private
Definition at line 341 of file LKHTLineTracker.h.
Referenced by AddHit(), Clear(), and ClearPoints().
fNumImagePoints
int LKHTLineTracker::fNumImagePoints = 0 private
Definition at line 349 of file LKHTLineTracker.h.
Referenced by AddImagePoint(), AddImagePointBox(), Clear(), ClearPoints(), GetDataGraphImageSpace(), GetHistImageSpace(), GetNumImagePoints(), GetSelectedDataGraph(), Print(), RemoveSelectedPoints(), SelectPoints(), and Transform().
fNumLinearTracks
int LKHTLineTracker::fNumLinearTracks = 0 private
Definition at line 358 of file LKHTLineTracker.h.
Referenced by Clear(), FitTrack3DWithParamPoint(), and FitTrackWithParamPoint().
fPadImage
TPad* LKHTLineTracker::fPadImage = nullptr private
Definition at line 377 of file LKHTLineTracker.h.
Referenced by Draw(), and ExecMouseClickEventOnPad().
fPadParam
TPad* LKHTLineTracker::fPadParam = nullptr private
Definition at line 378 of file LKHTLineTracker.h.
Referenced by Draw(), and ExecMouseClickEventOnPad().
fParamData
double** LKHTLineTracker::fParamData private
Definition at line 336 of file LKHTLineTracker.h.
Referenced by CleanLastParamPoint(), Clear(), DeTransformSelectedPoints(), FindNextMaximumParamPoint(), GetHistParamSpace(), GetParamData(), GetParamPoint(), GetParamPoint(), ReinitializeFromLastParamPoint(), Reset(), SetParamSpaceRange(), and Transform().
fParamPoint
LKParamPointRT* LKHTLineTracker::fParamPoint = nullptr private
Definition at line 352 of file LKHTLineTracker.h.
Referenced by FindNextMaximumParamPoint(), GetCurrentMaximumParamPoint(), GetParamPoint(), GetParamPoint(), LKHTLineTracker(), and ReinitializeFromLastParamPoint().
fProcess
int LKHTLineTracker::fProcess = kNon private
Definition at line 391 of file LKHTLineTracker.h.
Referenced by AddImagePoint(), AddImagePointBox(), Clear(), ClearPoints(), DeTransformSelectedPoints(), FitTrack3DWithParamPoint(), FitTrackWithParamPoint(), GetProcessName(), RemoveSelectedPoints(), SelectPoints(), and Transform().
fRangeImageSpace
double LKHTLineTracker::fRangeImageSpace[2][2] = {{0}} private
Definition at line 333 of file LKHTLineTracker.h.
Referenced by DrawAllParamBands(), DrawAllParamLines(), ExecMouseClickEventOnPad(), FitTrack3DWithParamPoint(), FitTrackWithParamPoint(), GetHistImageSpace(), GetRangeImageSpace(), Print(), SetImageSpaceRange(), and SetParamSpaceBins().
fRangeParamSpace
double LKHTLineTracker::fRangeParamSpace[2][2] = {{0}} private
Definition at line 334 of file LKHTLineTracker.h.
Referenced by CleanLastParamPoint(), Clear(), DeTransformSelectedPoints(), GetHistParamSpace(), GetParamPoint(), GetParamPoint(), GetRangeParamSpace(), Print(), ReinitializeFromLastParamPoint(), Reset(), SetParamSpaceRange(), and Transform().
fRangeParamSpaceInit
double LKHTLineTracker::fRangeParamSpaceInit[2][2] = {{0}} private
Definition at line 335 of file LKHTLineTracker.h.
Referenced by Clear(), Reset(), and SetParamSpaceRange().
fSelectedHitArray
TObjArray* LKHTLineTracker::fSelectedHitArray = nullptr private
Definition at line 346 of file LKHTLineTracker.h.
Referenced by DeTransformSelectedPoints(), FitTrack3DWithParamPoint(), FitTrackWithParamPoint(), GetSelectedHitArray(), LKHTLineTracker(), RemoveSelectedPoints(), and SelectPoints().
fSelectedImagePointIdxs
vector<int> LKHTLineTracker::fSelectedImagePointIdxs private
Definition at line 347 of file LKHTLineTracker.h.
Referenced by FitTrackWithParamPoint(), RemoveSelectedPoints(), and SelectPoints().
fTrackArray
TClonesArray* LKHTLineTracker::fTrackArray = nullptr private
Definition at line 359 of file LKHTLineTracker.h.
Referenced by Clear(), FitTrack3DWithParamPoint(), FitTrackWithParamPoint(), and LKHTLineTracker().
fTransformCenter
TVector3 LKHTLineTracker::fTransformCenter private
Definition at line 324 of file LKHTLineTracker.h.
Referenced by DeTransformSelectedPoints(), FindNextMaximumParamPoint(), GetHistImageSpace(), GetParamPoint(), GetParamPoint(), GetTransformCenter(), Print(), ReinitializeFromLastParamPoint(), SetParamSpaceBins(), SetTransformCenter(), and Transform().
fWeightCutTrackFit
double LKHTLineTracker::fWeightCutTrackFit = 0.2 private
Definition at line 371 of file LKHTLineTracker.h.
Referenced by FitTrack3DWithParamPoint(), FitTrackWithParamPoint(), SelectPoints(), and SetWeightCutTrackFit().
fWeightingFunction
LKHTWeightingFunction* LKHTLineTracker::fWeightingFunction = nullptr private
Definition at line 370 of file LKHTLineTracker.h.
Referenced by DeTransformSelectedPoints(), FitTrackWithParamPoint(), SelectPoints(), SetCorrelateBoxBand(), SetCorrelateBoxLine(), SetCorrelateBoxRibbon(), SetCorrelatePointBand(), SetWeightingFunction(), SetWFConst(), SetWFGivenWeight(), SetWFInverse(), SetWFLinear(), and Transform().
kAddPoints
const int LKHTLineTracker::kAddPoints = 1 private
Definition at line 383 of file LKHTLineTracker.h.
Referenced by AddImagePoint(), AddImagePointBox(), and GetProcessName().
kClear
const int LKHTLineTracker::kClear = 5 private
Definition at line 387 of file LKHTLineTracker.h.
Referenced by Clear(), and GetProcessName().
kClearPoints
const int LKHTLineTracker::kClearPoints = 6 private
Definition at line 388 of file LKHTLineTracker.h.
Referenced by ClearPoints(), and GetProcessName().
kCorrelateBoxBand
const int LKHTLineTracker::kCorrelateBoxBand = 3 private
Definition at line 367 of file LKHTLineTracker.h.
Referenced by DeTransformSelectedPoints(), GetCorrelatorName(), GetSelectedDataGraph(), IsCorrelateBoxBand(), SelectPoints(), SetCorrelateBoxBand(), and Transform().
kCorrelateBoxLine
const int LKHTLineTracker::kCorrelateBoxLine = 1 private
Definition at line 365 of file LKHTLineTracker.h.
Referenced by DeTransformSelectedPoints(), GetCorrelatorName(), IsCorrelateBoxLine(), SetCorrelateBoxLine(), and Transform().
kCorrelateBoxRibbon
const int LKHTLineTracker::kCorrelateBoxRibbon = 2 private
Definition at line 366 of file LKHTLineTracker.h.
Referenced by DeTransformSelectedPoints(), GetCorrelatorName(), IsCorrelateBoxRibbon(), SetCorrelateBoxRibbon(), and Transform().
kCorrelatePointBand
const int LKHTLineTracker::kCorrelatePointBand = 0 private
Definition at line 364 of file LKHTLineTracker.h.
Referenced by DeTransformSelectedPoints(), GetCorrelatorName(), IsCorrelatePointBand(), SetCorrelatePointBand(), and Transform().
kDeTransformPoints
const int LKHTLineTracker::kDeTransformPoints = 8 private
Definition at line 390 of file LKHTLineTracker.h.
Referenced by DeTransformSelectedPoints().
kFitTrack
const int LKHTLineTracker::kFitTrack = 4 private
Definition at line 386 of file LKHTLineTracker.h.
Referenced by FitTrack3DWithParamPoint(), FitTrackWithParamPoint(), and GetProcessName().
kNon
const int LKHTLineTracker::kNon = 0 private
Definition at line 382 of file LKHTLineTracker.h.
Referenced by GetProcessName().
kRemovePoints
const int LKHTLineTracker::kRemovePoints = 7 private
Definition at line 389 of file LKHTLineTracker.h.
Referenced by RemoveSelectedPoints().
kSelectPoints
const int LKHTLineTracker::kSelectPoints = 3 private
Definition at line 385 of file LKHTLineTracker.h.
Referenced by FitTrack3DWithParamPoint(), FitTrackWithParamPoint(), GetProcessName(), and SelectPoints().
kTransform
const int LKHTLineTracker::kTransform = 2 private
Definition at line 384 of file LKHTLineTracker.h.
Referenced by GetProcessName(), and Transform().
The documentation for this class was generated from the following files:
LKHTLineTracker.h
LKHTLineTracker.cpp