lilak: LKSiChannel Class Reference
LKSiChannel Class Reference
#include <LKSiChannel.h>
Public Member Functions
virtual void Clear (Option_t *option="")
virtual TObject * Clone (const char *newname="") const
virtual void Copy (TObject &object) const
int GetDetID () const
bool GetDirection () const
virtual TH1D * GetHist (TString name="")
int GetPairArrayIndex () const
LKSiChannel * GetPairChannel () const
double GetPhi1 () const
double GetPhi2 () const
bool GetSide () const
int GetStrip () const
double GetTheta1 () const
double GetTheta2 () const
bool IsPair (LKSiChannel *channel)
LKSiChannel ()
virtual TString MakeTitle ()
virtual void Print (Option_t *option="") const
void SetDetID (int value)
void SetDirection (bool direction)
void SetPairArrayIndex (int pair)
void SetPairChannel (LKSiChannel *pairChannel)
void SetPhi1 (double phi)
void SetPhi2 (double phi)
void SetSide (bool side)
void SetStrip (int strip)
void SetTheta1 (double theta)
void SetTheta2 (double theta)
virtual ~LKSiChannel ()
Public Member Functions inherited from GETChannel
void AddHit (LKHit *hit)
double CalculateGroupFluctuation (int numGroups=8, int tb2=512)
virtual void Clear (Option_t *option="")
void ClearHits ()
virtual TObject * Clone (const char *newname="") const
virtual void Copy (TObject &object) const
virtual void Draw (Option_t *option="")
void FillGraph (TGraph *graph)
void FillHist (TH1 *hist)
LKBufferI GetBuffer ()
int * GetBufferArray ()
GETChannel ()
void GetGroupMeanStdDev (int numGroups, int tb2, double *pedestalGroup, double *stddevGroup)
virtual TH1D * GetHist (TString name="")
LKHit * GetHit (int idx)
LKHitArray * GetHitArray ()
TGraph * GetHitGraph ()
int GetNumHits () const
double GetScale (double *buffer)
double GetScale (int *buffer)
int * GetWaveformY ()
virtual TString MakeTitle ()
virtual void Print (Option_t *option="") const
void PullOutHits (LKHitArray *hits)
void PullOutHits (vector< LKHit * > *hits)
LKHit * PullOutNextFreeHit ()
void SetBuffer (LKBufferI buffer)
void SetWaveformY (const int *array)
void SetWaveformY (const unsigned int *array)
void SetWaveformY (std::vector< unsigned int > array)
void SubtractArray (double *buffer)
void SubtractArray (double *buffer, double scale)
void SubtractArray (int *buffer)
void SubtractArray (int *buffer, double scale)
virtual ~GETChannel ()
Public Member Functions inherited from LKChannel
virtual void Clear (Option_t *option="")
virtual TObject * Clone (const char *newname="") const
virtual void Copy (TObject &obj) const
int GetChannelID () const
int GetDetID () const
double GetEnergy () const
double GetNoiseScale () const
int GetPadID () const
double GetPedestal () const
double GetTime () const
LKChannel ()
virtual void Print (Option_t *option="") const
void SetChannelID (int value)
void SetDetID (int value)
void SetEnergy (double value)
void SetNoiseScale (double value)
void SetPadID (int value)
void SetPedestal (double value)
void SetTime (double value)
virtual ~LKChannel ()
Public Member Functions inherited from LKContainer
virtual void Clear (Option_t *option="")
virtual TObject * Clone (const char *newname="") const
virtual void Copy (TObject &object) const
virtual bool DrawByDefault ()
return true if to be displayed on eve.
LKContainer ()
virtual ~LKContainer ()
Public Member Functions inherited from GETParameters
virtual void ClearParameters ()
int GetAget () const
int GetAsad () const
int GetCAAC () const
int GetChan () const
int GetCobo () const
int GetDecayNo () const
int GetDetType () const
int GetFrameNo () const
GETParameters ()
virtual void PrintParameters (TString option="") const
void SetAget (int aget)
void SetAsad (int asad)
void SetChan (int chan)
void SetCobo (int cobo)
void SetDecayNo (int id)
void SetDetType (int id)
void SetFrameNo (int id)
virtual ~GETParameters ()
Protected Member Functions
ClassDef (LKSiChannel, 1)
Protected Member Functions inherited from GETChannel
ClassDef (GETChannel, 4)
Protected Attributes
bool fDirection
int fPairArrayIndex = -1
LKSiChannel * fPairChannel
double fPhi1 = 0
double fPhi2 = 0
bool fSide
int fStrip
double fTheta1 = 0
double fTheta2 = 0
Protected Attributes inherited from GETChannel
LKBufferI fBufferRawSig
TGraph * fGraphHit = nullptr
LKHitArray fHitArray
Protected Attributes inherited from LKChannel
int fChannelID = -1
double fEnergy = -1
double fNoiseScale = -1
int fPadID = -1
double fPedestal = -1
double fTime = -1
Protected Attributes inherited from GETParameters
int fAget = -1
int fAsad = -1
int fChan = -1
int fCobo = -1
int fDecayNo = -1
int fDetType = -1
int fFrameNo = -1
Detailed Description
Definition at line 12 of file LKSiChannel.h.
Constructor & Destructor Documentation
LKSiChannel()
LKSiChannel::LKSiChannel ()
Definition at line 5 of file LKSiChannel.cpp.
References Clear().
~LKSiChannel()
virtual LKSiChannel::~LKSiChannel () inline virtual
Definition at line 16 of file LKSiChannel.h.
Member Function Documentation
ClassDef()
LKSiChannel::ClassDef (LKSiChannel , 1) protected
Clear()
void LKSiChannel::Clear (Option_t * option = "") virtual
Reimplemented from GETChannel.
Definition at line 10 of file LKSiChannel.cpp.
References GETChannel::Clear(), fDirection, fPairArrayIndex, fPairChannel, fPhi1, fPhi2, fSide, fStrip, fTheta1, and fTheta2.
Referenced by LKSiChannel().
Clone()
TObject * LKSiChannel::Clone (const char * newname = "") const virtual
Reimplemented from GETChannel.
Definition at line 38 of file LKSiChannel.cpp.
References GETChannel::Clone(), fDirection, fPairArrayIndex, fPairChannel, fPhi1, fPhi2, fSide, fStrip, fTheta1, fTheta2, SetDirection(), SetPairArrayIndex(), SetPairChannel(), SetPhi1(), SetPhi2(), SetSide(), SetStrip(), SetTheta1(), and SetTheta2().
Copy()
void LKSiChannel::Copy (TObject & object) const virtual
Reimplemented from GETChannel.
Definition at line 25 of file LKSiChannel.cpp.
References GETChannel::Copy(), fDirection, fPhi1, fPhi2, fSide, fStrip, fTheta1, and fTheta2.
GetDetID()
int LKSiChannel::GetDetID () const inline
Definition at line 34 of file LKSiChannel.h.
References LKChannel::GetPadID().
Referenced by IsPair().
GetDirection()
bool LKSiChannel::GetDirection () const inline
Definition at line 29 of file LKSiChannel.h.
References fDirection.
GetHist()
TH1D * LKSiChannel::GetHist (TString name = "") virtual
Reimplemented from GETChannel.
Definition at line 63 of file LKSiChannel.cpp.
References GETChannel::fBufferRawSig, GETParameters::GetCAAC(), LKBufferI::GetHist(), and MakeTitle().
GetPairArrayIndex()
int LKSiChannel::GetPairArrayIndex () const inline
Definition at line 35 of file LKSiChannel.h.
References fPairArrayIndex.
GetPairChannel()
LKSiChannel * LKSiChannel::GetPairChannel () const inline
Definition at line 36 of file LKSiChannel.h.
References fPairChannel.
GetPhi1()
double LKSiChannel::GetPhi1 () const inline
Definition at line 30 of file LKSiChannel.h.
References fPhi1.
GetPhi2()
double LKSiChannel::GetPhi2 () const inline
Definition at line 31 of file LKSiChannel.h.
References fPhi2.
GetSide()
bool LKSiChannel::GetSide () const inline
Definition at line 27 of file LKSiChannel.h.
References fSide.
Referenced by IsPair().
GetStrip()
int LKSiChannel::GetStrip () const inline
Definition at line 28 of file LKSiChannel.h.
References fStrip.
Referenced by IsPair().
GetTheta1()
double LKSiChannel::GetTheta1 () const inline
Definition at line 32 of file LKSiChannel.h.
References fTheta1.
GetTheta2()
double LKSiChannel::GetTheta2 () const inline
Definition at line 33 of file LKSiChannel.h.
References fTheta2.
IsPair()
bool LKSiChannel::IsPair (LKSiChannel * channel)
Definition at line 72 of file LKSiChannel.cpp.
References LKChannel::fPadID, fSide, fStrip, GetDetID(), GetSide(), and GetStrip().
MakeTitle()
virtual TString LKSiChannel::MakeTitle () inline virtual
Reimplemented from GETChannel.
Definition at line 24 of file LKSiChannel.h.
References GETParameters::fDetType, fDirection, LKChannel::fPadID, fSide, and fStrip.
Referenced by GetHist().
Print()
void LKSiChannel::Print (Option_t * option = "") const virtual
Reimplemented from GETChannel.
Definition at line 53 of file LKSiChannel.cpp.
References e_info, fDirection, LKChannel::fPadID, fPhi1, fPhi2, fSide, fStrip, fTheta1, fTheta2, GETChannel::Print(), and GETParameters::PrintParameters().
SetDetID()
void LKSiChannel::SetDetID (int value) inline
Definition at line 46 of file LKSiChannel.h.
References LKChannel::SetPadID().
SetDirection()
void LKSiChannel::SetDirection (bool direction) inline
Definition at line 41 of file LKSiChannel.h.
References fDirection.
Referenced by Clone().
SetPairArrayIndex()
void LKSiChannel::SetPairArrayIndex (int pair) inline
Definition at line 47 of file LKSiChannel.h.
References fPairArrayIndex.
Referenced by Clone().
SetPairChannel()
void LKSiChannel::SetPairChannel (LKSiChannel * pairChannel) inline
Definition at line 48 of file LKSiChannel.h.
References fPairChannel.
Referenced by Clone().
SetPhi1()
void LKSiChannel::SetPhi1 (double phi) inline
Definition at line 42 of file LKSiChannel.h.
References fPhi1.
Referenced by Clone().
SetPhi2()
void LKSiChannel::SetPhi2 (double phi) inline
Definition at line 43 of file LKSiChannel.h.
References fPhi2.
Referenced by Clone().
SetSide()
void LKSiChannel::SetSide (bool side) inline
Definition at line 39 of file LKSiChannel.h.
References fSide.
Referenced by Clone().
SetStrip()
void LKSiChannel::SetStrip (int strip) inline
Definition at line 40 of file LKSiChannel.h.
References fStrip.
Referenced by Clone().
SetTheta1()
void LKSiChannel::SetTheta1 (double theta) inline
Definition at line 44 of file LKSiChannel.h.
References fTheta1.
Referenced by Clone().
SetTheta2()
void LKSiChannel::SetTheta2 (double theta) inline
Definition at line 45 of file LKSiChannel.h.
References fTheta2.
Referenced by Clone().
Member Data Documentation
fDirection
bool LKSiChannel::fDirection protected
Definition at line 55 of file LKSiChannel.h.
Referenced by Clear(), Clone(), Copy(), GetDirection(), MakeTitle(), Print(), and SetDirection().
fPairArrayIndex
int LKSiChannel::fPairArrayIndex = -1 protected
Definition at line 57 of file LKSiChannel.h.
Referenced by Clear(), Clone(), GetPairArrayIndex(), and SetPairArrayIndex().
fPairChannel
LKSiChannel* LKSiChannel::fPairChannel protected
Definition at line 58 of file LKSiChannel.h.
Referenced by Clear(), Clone(), GetPairChannel(), and SetPairChannel().
fPhi1
double LKSiChannel::fPhi1 = 0 protected
Definition at line 60 of file LKSiChannel.h.
Referenced by Clear(), Clone(), Copy(), GetPhi1(), Print(), and SetPhi1().
fPhi2
double LKSiChannel::fPhi2 = 0 protected
Definition at line 61 of file LKSiChannel.h.
Referenced by Clear(), Clone(), Copy(), GetPhi2(), Print(), and SetPhi2().
fSide
bool LKSiChannel::fSide protected
Definition at line 53 of file LKSiChannel.h.
Referenced by Clear(), Clone(), Copy(), GetSide(), IsPair(), MakeTitle(), Print(), and SetSide().
fStrip
int LKSiChannel::fStrip protected
Definition at line 54 of file LKSiChannel.h.
Referenced by Clear(), Clone(), Copy(), GetStrip(), IsPair(), MakeTitle(), Print(), and SetStrip().
fTheta1
double LKSiChannel::fTheta1 = 0 protected
Definition at line 62 of file LKSiChannel.h.
Referenced by Clear(), Clone(), Copy(), GetTheta1(), Print(), and SetTheta1().
fTheta2
double LKSiChannel::fTheta2 = 0 protected
Definition at line 63 of file LKSiChannel.h.
Referenced by Clear(), Clone(), Copy(), GetTheta2(), Print(), and SetTheta2().
The documentation for this class was generated from the following files:
LKSiChannel.h
LKSiChannel.cpp