lilak: LKGeoPlane Class Reference
LKGeoPlane Class Reference
fA*x + fB*y + fC*z + fD = 0
#include <LKGeoPlane.h>
Public Member Functions
virtual TVector3 ClosestPointOnPlane (TVector3 pos) const
virtual Double_t DistanceToPlane (Double_t x, Double_t y, Double_t z) const
virtual Double_t DistanceToPlane (TVector3 pos) const
Double_t GetA () const
Double_t GetB () const
Double_t GetC () const
Double_t GetD () const
TVector3 GetNormal () const
Double_t GetX (Double_t y, Double_t z) const
Double_t GetY (Double_t z, Double_t x) const
Double_t GetZ (Double_t x, Double_t y) const
LKGeoPlane ()
LKGeoPlane (Double_t a, Double_t b, Double_t c, Double_t d)
LKGeoPlane (Double_t x, Double_t y, Double_t z, Double_t xn, Double_t yn, Double_t zn)
LKGeoPlane (TVector3 pos, TVector3 nnn)
void SetPlane (Double_t a, Double_t b, Double_t c, Double_t d)
void SetPlane (Double_t x, Double_t y, Double_t z, Double_t xn, Double_t yn, Double_t zn)
void SetPlane (TVector3 pos, TVector3 nnn)
virtual ~LKGeoPlane ()
Public Member Functions inherited from LKGeometry
Double_t GetRMS () const
LKGeometry ()
void SetRMS (Double_t val)
virtual ~LKGeometry ()
Protected Attributes
Double_t fA = 0
Double_t fB = 0
Double_t fC = 0
Double_t fD = 0
Protected Attributes inherited from LKGeometry
Double_t fRMS = -1
Detailed Description
fA*x + fB*y + fC*z + fD = 0
Definition at line 12 of file LKGeoPlane.h.
Constructor & Destructor Documentation
LKGeoPlane() [1/4]
LKGeoPlane::LKGeoPlane ()
LKGeoPlane() [2/4]
LKGeoPlane::LKGeoPlane (TVector3 pos, TVector3 nnn)
Definition at line 16 of file LKGeoPlane.cpp.
References SetPlane().
LKGeoPlane() [3/4]
LKGeoPlane::LKGeoPlane (Double_t x, Double_t y, Double_t z, Double_t xn, Double_t yn, Double_t zn)
Definition at line 11 of file LKGeoPlane.cpp.
References SetPlane(), x, and y.
LKGeoPlane() [4/4]
LKGeoPlane::LKGeoPlane (Double_t a, Double_t b, Double_t c, Double_t d)
Definition at line 21 of file LKGeoPlane.cpp.
References SetPlane().
~LKGeoPlane()
virtual LKGeoPlane::~LKGeoPlane () inline virtual
Definition at line 19 of file LKGeoPlane.h.
Member Function Documentation
ClosestPointOnPlane()
TVector3 LKGeoPlane::ClosestPointOnPlane (TVector3 pos) const virtual
Definition at line 59 of file LKGeoPlane.cpp.
References fA, fB, and fC.
Referenced by DistanceToPlane().
DistanceToPlane() [1/2]
Double_t LKGeoPlane::DistanceToPlane (Double_t x, Double_t y, Double_t z) const virtual
Definition at line 67 of file LKGeoPlane.cpp.
References DistanceToPlane(), x, and y.
Referenced by DistanceToPlane().
DistanceToPlane() [2/2]
Double_t LKGeoPlane::DistanceToPlane (TVector3 pos) const virtual
Definition at line 72 of file LKGeoPlane.cpp.
References ClosestPointOnPlane().
GetA()
Double_t LKGeoPlane::GetA () const
Definition at line 49 of file LKGeoPlane.cpp.
References fA.
Referenced by LKGeoPlaneBox::GetCrossSectionLine(), and LKGeoPlaneWithCenter::GetCrossSectionLine().
GetB()
Double_t LKGeoPlane::GetB () const
Definition at line 50 of file LKGeoPlane.cpp.
References fB.
Referenced by LKGeoPlaneBox::GetCrossSectionLine(), and LKGeoPlaneWithCenter::GetCrossSectionLine().
GetC()
Double_t LKGeoPlane::GetC () const
Definition at line 51 of file LKGeoPlane.cpp.
References fC.
Referenced by LKGeoPlaneBox::GetCrossSectionLine(), and LKGeoPlaneWithCenter::GetCrossSectionLine().
GetD()
Double_t LKGeoPlane::GetD () const
Definition at line 52 of file LKGeoPlane.cpp.
References fD.
Referenced by LKGeoLine::GetCrossingPoint(), LKGeoPlaneBox::GetCrossSectionLine(), and LKGeoPlaneWithCenter::GetCrossSectionLine().
GetNormal()
TVector3 LKGeoPlane::GetNormal () const
Definition at line 53 of file LKGeoPlane.cpp.
References fA, fB, and fC.
Referenced by LKGeoLine::GetCrossingPoint(), LKGeoPlaneBox::GetCrossSectionLine(), LKGeoPlaneWithCenter::GetCrossSectionLine(), LKGeoPlaneWithCenter::GetVectorV(), LKGeoPlaneWithCenter::Print(), and LKGeoPlaneBox::Print().
GetX()
Double_t LKGeoPlane::GetX (Double_t y, Double_t z) const
Definition at line 55 of file LKGeoPlane.cpp.
References fA, fB, fC, fD, and y.
Referenced by LKGeoPlaneWithCenter::GetVectorU().
GetY()
Double_t LKGeoPlane::GetY (Double_t z, Double_t x) const
Definition at line 56 of file LKGeoPlane.cpp.
References fA, fB, fC, fD, and x.
Referenced by LKGeoPlaneWithCenter::GetVectorU().
GetZ()
Double_t LKGeoPlane::GetZ (Double_t x, Double_t y) const
Definition at line 57 of file LKGeoPlane.cpp.
References fA, fB, fC, fD, x, and y.
Referenced by LKGeoPlaneWithCenter::GetVectorU().
SetPlane() [1/3]
void LKGeoPlane::SetPlane (Double_t a, Double_t b, Double_t c, Double_t d)
Definition at line 40 of file LKGeoPlane.cpp.
References fA, fB, fC, and fD.
SetPlane() [2/3]
void LKGeoPlane::SetPlane (Double_t x, Double_t y, Double_t z, Double_t xn, Double_t yn, Double_t zn)
Definition at line 35 of file LKGeoPlane.cpp.
References SetPlane(), x, and y.
SetPlane() [3/3]
void LKGeoPlane::SetPlane (TVector3 pos, TVector3 nnn)
Definition at line 26 of file LKGeoPlane.cpp.
References fA, fB, fC, and fD.
Referenced by LKHitArray::FitPlane(), LKGeoPlane(), LKGeoPlane(), LKGeoPlane(), and SetPlane().
Member Data Documentation
fA
Double_t LKGeoPlane::fA = 0 protected
Definition at line 41 of file LKGeoPlane.h.
Referenced by ClosestPointOnPlane(), GetA(), GetNormal(), LKGeoPlaneWithCenter::GetVectorU(), GetX(), GetY(), GetZ(), LKGeoPlaneWithCenter::Intersection(), SetPlane(), SetPlane(), LKGeoPlaneWithCenter::SetPlane(), and LKGeoPlaneBox::SetPlane().
fB
Double_t LKGeoPlane::fB = 0 protected
Definition at line 42 of file LKGeoPlane.h.
Referenced by ClosestPointOnPlane(), GetB(), GetNormal(), LKGeoPlaneWithCenter::GetVectorU(), GetX(), GetY(), GetZ(), LKGeoPlaneWithCenter::Intersection(), SetPlane(), SetPlane(), LKGeoPlaneWithCenter::SetPlane(), and LKGeoPlaneBox::SetPlane().
fC
Double_t LKGeoPlane::fC = 0 protected
Definition at line 43 of file LKGeoPlane.h.
Referenced by ClosestPointOnPlane(), GetC(), GetNormal(), LKGeoPlaneWithCenter::GetVectorU(), GetX(), GetY(), GetZ(), LKGeoPlaneWithCenter::Intersection(), SetPlane(), SetPlane(), LKGeoPlaneWithCenter::SetPlane(), and LKGeoPlaneBox::SetPlane().
fD
Double_t LKGeoPlane::fD = 0 protected
Definition at line 44 of file LKGeoPlane.h.
Referenced by GetD(), GetX(), GetY(), GetZ(), LKGeoPlaneWithCenter::Intersection(), SetPlane(), SetPlane(), LKGeoPlaneWithCenter::SetPlane(), and LKGeoPlaneBox::SetPlane().
The documentation for this class was generated from the following files:
LKGeoPlane.h
LKGeoPlane.cpp