LILAK: LKDetectorSystem Class Reference
LKDetectorSystem Class Reference
#include <LKDetectorSystem.h>
Public Member Functions
void AddDetector (LKDetector *detector)
void AddPar (LKParameterContainer *par)
void AddPar (TString fname)
virtual void AddParameterContainer (LKParameterContainer *par)
virtual void AddParameterContainer (TString fname)
void CreateParameterContainer ()
LKDetector * FindDetector (const char *name)
LKDetectorPlane * FindDetectorPlane (const char *name)
LKDetector * GetDetector (Int_t idx=0) const
LKDetectorPlane * GetDetectorPlane (Int_t idx=0) const
TGeoManager * GetGeoManager () const
TGeoVolume * GetGeoTopVolume () const
Int_t GetNumDetectors () const
Int_t GetNumPlanes () const
LKParameterContainer * GetPar () const
LKParameterContainer * GetParameterContainer () const
Int_t GetRank () const
virtual bool Init ()
LKDetectorSystem ()
LKDetectorSystem (const char *name)
virtual void Print (Option_t *option="") const
void SetGeoManager (TGeoManager *)
void SetPar (LKParameterContainer *par)
virtual void SetParameterContainer (LKParameterContainer *par)
virtual void SetRank (Int_t rank)
void SetRun (LKRun *run)
void SetTransparency (Int_t transparency)
virtual ~LKDetectorSystem ()
Static Public Member Functions
static LKDetectorSystem * GetDS ()
Protected Member Functions
void SetDetector (LKDetector *detector)
void SetDetectorPar ()
Protected Attributes
TGeoManager * fGeoManager = nullptr
LKParameterContainer * fPar = nullptr
Int_t fRank = 0
LKRun * fRun = nullptr
Static Private Attributes
static LKDetectorSystem * fInstance
Detailed Description
Definition at line 16 of file LKDetectorSystem.h.
Constructor & Destructor Documentation
LKDetectorSystem() [1/2]
LKDetectorSystem::LKDetectorSystem ()
Definition at line 17 of file LKDetectorSystem.cpp.
References fInstance.
LKDetectorSystem() [2/2]
LKDetectorSystem::LKDetectorSystem (const char * name)
Definition at line 23 of file LKDetectorSystem.cpp.
References fGeoManager.
~LKDetectorSystem()
virtual LKDetectorSystem::~LKDetectorSystem () inline virtual
Definition at line 23 of file LKDetectorSystem.h.
Member Function Documentation
AddDetector()
void LKDetectorSystem::AddDetector (LKDetector * detector)
Definition at line 95 of file LKDetectorSystem.cpp.
References SetDetector().
AddPar() [1/2]
void LKGear::AddPar (LKParameterContainer * par) inline inherited
Definition at line 27 of file LKGear.h.
References LKGear::AddParameterContainer().
Referenced by LKTask::Add(), LKRun::EndOfRun(), LKRun::Init(), LKG4RunManager::Initialize(), LAMPSTPC::LAMPSTPC(), LAMPSTPC::LAMPSTPC(), SetDetectorPar(), LKRun::SetEventTrigger(), LKG4RunManager::SetSensitiveDetector(), LKG4RunManager::SetVolume(), LKRun::StartOfRun(), TexAT2::TexAT2(), TexAT2::TexAT2(), and TTMicromegas::WriteCurrentChannel().
AddPar() [2/2]
void LKGear::AddPar (TString fname) inline inherited
Definition at line 28 of file LKGear.h.
References LKGear::AddParameterContainer().
AddParameterContainer() [1/2]
void LKGear::AddParameterContainer (LKParameterContainer * par) virtual inherited
Definition at line 14 of file LKGear.cpp.
References LKGear::AddParameterContainer(), and LKGear::fPar.
Referenced by LKGear::AddPar(), LKGear::AddPar(), LKGear::AddParameterContainer(), LHTpc::BuildDetectorPlane(), and LKRun::Init().
AddParameterContainer() [2/2]
void LKGear::AddParameterContainer (TString fname) virtual inherited
Definition at line 22 of file LKGear.cpp.
References LKGear::fPar.
CreateParameterContainer()
void LKGear::CreateParameterContainer () inherited
Referenced by LKRun::AddDetector(), and LKRun::LKRun().
FindDetector()
LKDetector * LKDetectorSystem::FindDetector (const char * name)
Definition at line 158 of file LKDetectorSystem.cpp.
FindDetectorPlane()
LKDetectorPlane * LKDetectorSystem::FindDetectorPlane (const char * name)
Definition at line 173 of file LKDetectorSystem.cpp.
References GetDetectorPlane(), and GetNumPlanes().
GetDetector()
LKDetector * LKDetectorSystem::GetDetector (Int_t idx = 0) const
Definition at line 103 of file LKDetectorSystem.cpp.
GetDetectorPlane()
LKDetectorPlane * LKDetectorSystem::GetDetectorPlane (Int_t idx = 0) const
Definition at line 117 of file LKDetectorSystem.cpp.
References GetDetectorPlane(), GetNumPlanes(), and next().
Referenced by FindDetectorPlane(), GetDetectorPlane(), and Init().
GetDS()
static LKDetectorSystem * LKDetectorSystem::GetDS () static
GetGeoManager()
TGeoManager * LKDetectorSystem::GetGeoManager () const
Definition at line 75 of file LKDetectorSystem.cpp.
References fGeoManager.
GetGeoTopVolume()
TGeoVolume * LKDetectorSystem::GetGeoTopVolume () const
Definition at line 76 of file LKDetectorSystem.cpp.
References fGeoManager.
GetNumDetectors()
Int_t LKDetectorSystem::GetNumDetectors () const
Definition at line 102 of file LKDetectorSystem.cpp.
Referenced by LKRun::Init().
GetNumPlanes()
Int_t LKDetectorSystem::GetNumPlanes () const
Definition at line 105 of file LKDetectorSystem.cpp.
References GetNumPlanes(), and next().
Referenced by FindDetectorPlane(), GetDetectorPlane(), GetNumPlanes(), LKRun::Init(), Init(), LKGETChannelViewer::Init(), and LKPulseShapeAnalysisTask::Init().
GetPar()
LKParameterContainer * LKGear::GetPar () const inherited
Definition at line 33 of file LKGear.cpp.
References LKGear::fPar.
GetParameterContainer()
LKParameterContainer * LKGear::GetParameterContainer () const inherited
Definition at line 32 of file LKGear.cpp.
References LKGear::fPar.
Referenced by ClassImp(), LHElectronicsTask::Init(), and LHVertexFindingTask::Init().
GetRank()
Int_t LKGear::GetRank () const inherited
Definition at line 36 of file LKGear.cpp.
References LKGear::fRank.
Init()
bool LKDetectorSystem::Init () virtual
Definition at line 39 of file LKDetectorSystem.cpp.
References fGeoManager, GetDetectorPlane(), GetNumPlanes(), Init(), lk_info, next(), SetDetector(), and SetDetectorPar().
Referenced by Init().
Print()
void LKDetectorSystem::Print (Option_t * option = "") const virtual
Definition at line 31 of file LKDetectorSystem.cpp.
References next(), and Print().
Referenced by Print().
SetDetector()
void LKDetectorSystem::SetDetector (LKDetector * detector) protected
Definition at line 135 of file LKDetectorSystem.cpp.
References fGeoManager, LKGear::fRank, LKGear::fRun, SetGeoManager(), LKGear::SetRank(), and LKGear::SetRun().
Referenced by AddDetector(), and Init().
SetDetectorPar()
void LKDetectorSystem::SetDetectorPar () protected
Definition at line 150 of file LKDetectorSystem.cpp.
References LKGear::AddPar(), LKGear::fPar, and next().
Referenced by Init().
SetGeoManager()
void LKDetectorSystem::SetGeoManager (TGeoManager * man)
Definition at line 77 of file LKDetectorSystem.cpp.
References fGeoManager, next(), and SetGeoManager().
Referenced by SetDetector(), and SetGeoManager().
SetPar()
void LKGear::SetPar (LKParameterContainer * par) inline inherited
Definition at line 26 of file LKGear.h.
References LKGear::SetParameterContainer().
Referenced by LKDetector::AddPlane(), LKRun::Init(), LKDetector::Init(), and LKMFMConversionTask::Init().
SetParameterContainer()
void LKGear::SetParameterContainer (LKParameterContainer * par) virtual inherited
Definition at line 10 of file LKGear.cpp.
References LKGear::fPar.
Referenced by ATTPC::BuildDetectorPlane(), and LKGear::SetPar().
SetRank()
void LKGear::SetRank (Int_t rank) virtual inherited
Reimplemented in LKTask.
Definition at line 35 of file LKGear.cpp.
References LKGear::fRank.
Referenced by LKDetector::AddPlane(), and SetDetector().
SetRun()
void LKGear::SetRun (LKRun * run) inline inherited
Definition at line 36 of file LKGear.h.
References LKGear::fRun, and run.
Referenced by LKRun::Add(), LKRun::AddDetector(), LKRun::Init(), SetDetector(), and LKRun::SetEventTrigger().
SetTransparency()
void LKDetectorSystem::SetTransparency (Int_t transparency)
Definition at line 87 of file LKDetectorSystem.cpp.
References SetTransparency().
Referenced by SetTransparency().
Member Data Documentation
fGeoManager
TGeoManager* LKDetectorSystem::fGeoManager = nullptr protected
Definition at line 45 of file LKDetectorSystem.h.
Referenced by GetGeoManager(), GetGeoTopVolume(), Init(), LKDetectorSystem(), SetDetector(), and SetGeoManager().
fInstance
LKDetectorSystem* LKDetectorSystem::fInstance static private
Definition at line 51 of file LKDetectorSystem.h.
Referenced by LKDetectorSystem().
fPar
LKParameterContainer* LKGear::fPar = nullptr protected inherited
Definition at line 39 of file LKGear.h.
Referenced by LKTask::Add(), LKRun::AddDetector(), LKGear::AddParameterContainer(), LKGear::AddParameterContainer(), LKDetector::AddPlane(), LHTpc::BuildDetectorPlane(), ATTPC::BuildDetectorPlane(), LHTpc::BuildGeometry(), ATTPC::BuildGeometry(), ClassImp(), ClassImp(), ClassImp(), ClassImp(), LKEveTask::DrawEve3D(), LKPadPlane::DrawHist(), LKG4RunManager::EndOfRun(), LKPulseExtractionTask::EndOfRun(), LKDetectorPlane::FillDataToHist(), LKPadPlane::FillDataToHist(), LTPadPlane::GetChannelAnalyzer(), LKDetector::GetChannelAnalyzer(), LKDetectorPlane::GetChannelAnalyzer(), LKEvePlane::GetChannelAnalyzer(), LKGear::GetPar(), LKGear::GetParameterContainer(), ATMicromegas::Init(), AToMX::Init(), LTPadPlane::Init(), LKRun::Init(), LKDetector::Init(), LKEvePlane::Init(), LKMFMConversionTask::Init(), LKDriftElectronTask::Init(), LKEveTask::Init(), LKGETChannelViewer::Init(), LKNoiseSubtractionTask::Init(), LKPulseExtractionTask::Init(), LHPSATask::Init(), TexAT2::Init(), TTMicromegas::Init(), TTHTBeamTrackingTask::Init(), TTHTTrackingTask::Init(), TTPulseExtractionTask::Init(), LHPadPlaneFan::Init(), LHPadPlaneRCut::Init(), LHPadPlaneYCut::Init(), ATTPC::Init(), ATTPC20RectanglePad::Init(), ATTPCHoneyCombPad::Init(), ATTPCRectanglePad::Init(), ATTPCStripPad::Init(), TTFrontPlane::Init(), LKRun::InitAndCollectParameters(), TexAT2::InitChannelAnalyzer(), LKG4RunManager::Initialize(), LKRun::Print(), LKRun::RegisterBranchA(), LKG4RunManager::Run(), LKDetectorPlane::SetDataFromBranch(), LKPadPlane::SetDataFromBranch(), SetDetectorPar(), LKEveTask::SetEveLineAtt(), LKEveTask::SetEveMarkerAtt(), LKRun::SetEventTrigger(), LKEveTask::SetGraphAtt(), LKEveTask::SetGraphAtt(), LKG4RunManager::SetOutputFile(), LKGear::SetParameterContainer(), TTMicromegas::WriteCurrentChannel(), and LKRun::WriteOutputFile().
fRank
Int_t LKGear::fRank = 0 protected inherited
Definition at line 41 of file LKGear.h.
Referenced by LKTask::Add(), LKDetector::AddPlane(), LKGear::GetRank(), SetDetector(), LKRun::SetEventTrigger(), LKGear::SetRank(), and LKTask::SetRank().
fRun
LKRun* LKGear::fRun = nullptr protected inherited
Definition at line 40 of file LKGear.h.
Referenced by LKDetector::AddPlane(), ClassImp(), ClassImp(), ClassImp(), LKEvePlane::ClickedControlEvent1(), LKEvePlane::ClickedControlEvent1(), LKEvePlane::ClickedControlEvent2(), LKEveTask::DrawDetectorPlanes(), LKEveTask::DrawEve3D(), LKPulseExtractionTask::EndOfRun(), TTPulseExtractionTask::EndOfRun(), LKGETChannelViewer::Exec(), LKPulseExtractionTask::Exec(), TTHitFindingHoughTask::Exec(), TTPulseExtractionTask::Exec(), TTMicromegas::FillDataToHist(), LTPadPlane::FillDataToHist(), LKEvePlane::FillDataToHistEventDisplay1(), LKEvePlane::GetHistControlEvent1(), LTPadPlane::Init(), LTEventPreviewTask::Init(), TTPulseAnalysisTask::Init(), LKEvePlane::Init(), LKMFMConversionTask::Init(), LKDriftElectronTask::Init(), LKEveTask::Init(), LKGETChannelViewer::Init(), LKNoiseSubtractionTask::Init(), LKPulseExtractionTask::Init(), LKPulseShapeAnalysisTask::Init(), TTBeamSelectionTask::Init(), TTDrawBeamEnergyTask::Init(), TTDrawRawWaveformTask::Init(), TTEventSelectionTask::Init(), TTFindBeamTimingTask::Init(), TTGetPedestalTask::Init(), TTPID_FSivsFCsI::Init(), TTPID_MMvsFSi::Init(), TTPID_MMvsX6::Init(), TTPID_X6vsCsI::Init(), TTReadEventListTask::Init(), TTHTtBeamTrackingTask::Init(), TTEventNumberSelectionTask::Init(), TTEventPreviewTask::Init(), TTHitFindingHoughTask::Init(), TTHTBeamTrackingTask::Init(), TTHTTrackingTask::Init(), TTPulseExtractionTask::Init(), httask::Init(), LKMFMConversionTask::Run(), LKGETChannelViewer::SelectMenu(), LKDetectorPlane::SetDataFromBranch(), LKPadPlane::SetDataFromBranch(), TTMicromegas::SetDataFromBranch(), TTFrontPlane::SetDataFromBranch(), SetDetector(), LKEvePlane::SetPalette(), LKGear::SetRun(), LKDetector::SetRun(), LKMFMConversionTask::SignalNextEvent(), LKEvePlane::UpdateControlEvent1(), and LKEvePlane::UpdateControlEvent2().
The documentation for this class was generated from the following files:
LKDetectorSystem.h
LKDetectorSystem.cpp