LILAK: LKVector3 Class Reference
LKVector3 Class Reference
#include <LKVector3.h>
Public Types
enum Axis : int {
kNon = 0 , kX = 1 , kMX = 2 , kY = 3 ,
kMY = 4 , kZ = 5 , kMZ = 6 , kI = 7 ,
kMI = 8 , kJ = 9 , kMJ = 10 , kK = 11 ,
kMK = 12
}
Public Member Functions
void AddAt (Double_t value, Axis ka, bool ignoreNegative=false)
TArrow * ArrowXY ()
TArrow * ArrowYZ ()
TArrow * ArrowZX ()
Double_t At (Axis ka) const
virtual void Clear (Option_t *option="")
Axis GetGlobalAxis (Axis ka) const
TVector3 GetIJK () const
Axis GetReferenceAxis () const
TVector3 GetXYZ () const
Double_t I () const
Double_t J () const
Double_t K () const
LKVector3 ()
LKVector3 (Axis referenceAxis)
LKVector3 (Axis referenceAxis, Double_t i, Double_t j, Double_t k)
LKVector3 (Axis referenceAxis, TVector3 ijk)
LKVector3 (const LKVector3 &p)
LKVector3 (const TVector3 &p, Axis referenceAxis=kNon)
LKVector3 (Double_t x, Double_t y, Double_t z, Axis referenceAxis=kNon)
LKVector3 operator- () const
LKVector3 & operator= (const LKVector3 &p)
virtual void Print (Option_t *option="at") const
void Rotate (Double_t angle, Axis ka=kNon)
void SetAt (Double_t value, Axis ka, bool ignoreNegative=false)
void SetI (Double_t i)
void SetIJK (Double_t i, Double_t j, Double_t k)
void SetIJKR (Double_t i, Double_t j, Double_t k, Axis referenceAxis)
void SetJ (Double_t j)
void SetK (Double_t k)
void SetReferenceAxis (Axis referenceAxis)
virtual ~LKVector3 ()
Static Public Member Functions
static TString AxisName (Axis axisIn)
static Axis GetAxis (TString name)
static bool IsGlobalAxis (Axis axisIn)
static bool IsLocalAxis (Axis axisIn)
static bool IsNegative (Axis axisIn)
static bool IsPositive (Axis axisIn)
Private Attributes
Axis fReferenceAxis = kNon
Friends
std::ostream & operator<< (std::ostream &out, const Axis axisIn)
Detailed Description
Utility class to handel global axis (x,y,z) and local axis (i,j,k) togeter. Local axis (i,j,k) is definded to have reference axis same as k-axis and i,j-axis defined by right-handed orientation in i,j,k order.
Definition at line 14 of file LKVector3.h.
Member Enumeration Documentation
Axis
enum LKVector3::Axis : int
Enumerator
kNon
kX
kMX
kY
kMY
kZ
kMZ
kI
kMI
kJ
kMJ
kK
kMK
Definition at line 17 of file LKVector3.h.
Constructor & Destructor Documentation
LKVector3() [1/7]
LKVector3::LKVector3 () inline
Definition at line 109 of file LKVector3.h.
References Clear().
Referenced by operator-().
LKVector3() [2/7]
LKVector3::LKVector3 (Axis referenceAxis) inline
Definition at line 112 of file LKVector3.h.
LKVector3() [3/7]
LKVector3::LKVector3 (const LKVector3 & p) inline
Definition at line 115 of file LKVector3.h.
LKVector3() [4/7]
LKVector3::LKVector3 (const TVector3 & p, Axis referenceAxis = kNon) inline
Definition at line 118 of file LKVector3.h.
LKVector3() [5/7]
LKVector3::LKVector3 (Double_t x, Double_t y, Double_t z, Axis referenceAxis = kNon) inline
Definition at line 121 of file LKVector3.h.
LKVector3() [6/7]
LKVector3::LKVector3 (Axis referenceAxis, Double_t i, Double_t j, Double_t k) inline
Definition at line 124 of file LKVector3.h.
References SetIJK().
LKVector3() [7/7]
LKVector3::LKVector3 (Axis referenceAxis, TVector3 ijk) inline
Definition at line 127 of file LKVector3.h.
References SetIJK().
~LKVector3()
virtual LKVector3::~LKVector3 () inline virtual
Definition at line 130 of file LKVector3.h.
Member Function Documentation
AddAt()
void LKVector3::AddAt (Double_t value, Axis ka, bool ignoreNegative = false)
Definition at line 102 of file LKVector3.cpp.
References e_error, I(), J(), K(), kI, kJ, kK, kMI, kMJ, kMK, kMX, kMY, kMZ, kX, kY, kZ, SetI(), SetJ(), and SetK().
Referenced by LKGeoBoxStack::GetBox(), LHTpc::GetEField(), and ATTPC::GetEField().
ArrowXY()
TArrow * LKVector3::ArrowXY ()
Definition at line 167 of file LKVector3.cpp.
References LKGeoLine::DrawArrowXY(), and GetXYZ().
ArrowYZ()
TArrow * LKVector3::ArrowYZ ()
Definition at line 168 of file LKVector3.cpp.
References LKGeoLine::DrawArrowYZ(), and GetXYZ().
ArrowZX()
TArrow * LKVector3::ArrowZX ()
Definition at line 169 of file LKVector3.cpp.
References LKGeoLine::DrawArrowZX(), and GetXYZ().
At()
Double_t LKVector3::At (LKVector3::Axis ka) const
Definition at line 82 of file LKVector3.cpp.
References e_error, I(), J(), K(), kI, kJ, kK, kMI, kMJ, kMK, kMX, kMY, kMZ, kX, kY, and kZ.
Referenced by LHHelixTrackFindingTask::CheckTrackContinuity(), LTHelixTrackFindingTask::CheckTrackContinuity(), LKEveTask::DrawEve3D(), LKHitArray::DrawGraph(), LKGeoBoxStack::DrawStackHist(), LKDetectorPlane::DriftElectron(), LKGeoBoxStack::GetFaceAxisCenter(), LKGeoBoxStack::GetFaceAxisDisplacement(), LKGeoBoxStack::GetLongAxisCenter(), LKGeoBoxStack::GetLongAxisDisplacement(), LKGeoBoxStack::GetStackAxisCenter(), LKGeoBoxStack::GetStackAxisDisplacement(), I(), J(), K(), and LKLinearTrack::ProjectionOnPlane().
AxisName()
static TString LKVector3::AxisName (Axis axisIn) inline static
Definition at line 64 of file LKVector3.h.
References kI, kJ, kK, kMI, kMJ, kMK, kMX, kMY, kMZ, kNon, kX, kY, and kZ.
Referenced by LKGeoBoxStack::DrawStackHist(), LKGeoBoxStack::DrawStackHistPoly(), ATTPC20RectanglePad::GetHist(), ATTPCHoneyCombPad::GetHist(), ATTPCRectanglePad::GetHist(), and ATTPCStripPad::GetHist().
Clear()
virtual void LKVector3::Clear (Option_t * option = "") virtual
Referenced by LKVector3().
GetAxis()
static Axis LKVector3::GetAxis (TString name) inline static
Definition at line 47 of file LKVector3.h.
References kI, kJ, kK, kMI, kMJ, kMK, kMX, kMY, kMZ, kNon, kX, kY, and kZ.
GetGlobalAxis()
LKVector3::Axis LKVector3::GetGlobalAxis (Axis ka) const
Definition at line 53 of file LKVector3.cpp.
References fReferenceAxis, IsGlobalAxis(), kI, kJ, kNon, kX, kY, and kZ.
Referenced by I(), J(), K(), Rotate(), SetI(), SetIJK(), SetJ(), and SetK().
GetIJK()
TVector3 LKVector3::GetIJK () const
Definition at line 165 of file LKVector3.cpp.
References I(), J(), and K().
GetReferenceAxis()
LKVector3::Axis LKVector3::GetReferenceAxis () const
Definition at line 51 of file LKVector3.cpp.
References fReferenceAxis.
Referenced by operator*(), operator*(), operator*(), operator*(), operator+(), operator-(), and LKPad::Print().
GetXYZ()
TVector3 LKVector3::GetXYZ () const
Definition at line 164 of file LKVector3.cpp.
Referenced by ArrowXY(), ArrowYZ(), ArrowZX(), LKHelixTrack::CrossSectionOnPlane(), LKGeoHelix::Direction(), LKDetectorPlane::DriftElectronBack(), LKHelixTrack::ExtrapolateToAlpha(), LKHelixTrack::ExtrapolateToPointAlpha(), LKHelixTrack::ExtrapolateToPointK(), LKGeoHelix::GetCenter(), LKGeoHelix::PositionAtAlpha(), Rotate(), and LHVertexFindingTask::TestVertexAtK().
I()
Double_t LKVector3::I () const
Definition at line 160 of file LKVector3.cpp.
References At(), GetGlobalAxis(), and kI.
Referenced by AddAt(), At(), ClassImp(), LTHelixTrackFindingTask::CorrelateHitWithTrackCandidate(), LHHelixTrackFindingTask::CorrelateHitWithTrackCandidate(), LKHitArray::DrawFitCircle(), LKHelixTrack::ExtrapolateToPointAlpha(), ATTPC20RectanglePad::FindPadID(), ATTPCHoneyCombPad::FindPadID(), ATTPCRectanglePad::FindPadID(), ATTPCStripPad::FindPadID(), LKHitArray::FitCircle(), LKPad::GetI(), GetIJK(), LKPad::GetPosition(), LKGeoHelix::HelicoidMap(), and ATTPCStripPad::PadNeighborIndex().
IsGlobalAxis()
static bool LKVector3::IsGlobalAxis (Axis axisIn) inline static
Definition at line 84 of file LKVector3.h.
Referenced by GetGlobalAxis(), SetIJKR(), and SetReferenceAxis().
IsLocalAxis()
static bool LKVector3::IsLocalAxis (Axis axisIn) inline static
Definition at line 90 of file LKVector3.h.
IsNegative()
static bool LKVector3::IsNegative (Axis axisIn) inline static
Definition at line 102 of file LKVector3.h.
Referenced by LKGeoBoxStack::DrawStackGraph(), LKGeoBoxStack::DrawStackHist(), and LKGeoBoxStack::DrawStackHistPoly().
IsPositive()
static bool LKVector3::IsPositive (Axis axisIn) inline static
Definition at line 96 of file LKVector3.h.
J()
Double_t LKVector3::J () const
Definition at line 161 of file LKVector3.cpp.
References At(), GetGlobalAxis(), and kJ.
Referenced by AddAt(), At(), ClassImp(), LTHelixTrackFindingTask::CorrelateHitWithTrackCandidate(), LHHelixTrackFindingTask::CorrelateHitWithTrackCandidate(), LKHitArray::DrawFitCircle(), LKHelixTrack::ExtrapolateToPointAlpha(), ATTPC20RectanglePad::FindPadID(), ATTPCHoneyCombPad::FindPadID(), ATTPCRectanglePad::FindPadID(), ATTPCStripPad::FindPadID(), LKHitArray::FitCircle(), GetIJK(), LKPad::GetJ(), LKPad::GetPosition(), LKGeoHelix::HelicoidMap(), and ATTPCStripPad::PadNeighborIndex().
K()
Double_t LKVector3::K () const
Definition at line 162 of file LKVector3.cpp.
References At(), GetGlobalAxis(), and kK.
Referenced by AddAt(), At(), ClassImp(), LTHelixTrackFindingTask::CorrelateHitWithTrackCandidate(), LHHelixTrackFindingTask::CorrelateHitWithTrackCandidate(), LKHitArray::DrawFitCircle(), LKHelixTrack::ExtrapolateByMap(), LKHelixTrack::ExtrapolateToPointAlpha(), LKHelixTrack::ExtrapolateToPointK(), LKHitArray::FitCircle(), GetIJK(), LKPad::GetK(), LKGeoHelix::HelicoidMap(), LHHelixTrackFindingTask::StepConfirmation(), and LTHelixTrackFindingTask::StepConfirmation().
operator-()
LKVector3 LKVector3::operator- () const inline
Definition at line 132 of file LKVector3.h.
References fReferenceAxis, and LKVector3().
operator=()
LKVector3 & LKVector3::operator= (const LKVector3 & p) inline
Definition at line 136 of file LKVector3.h.
References fReferenceAxis.
Print()
virtual void LKVector3::Print (Option_t * option = "at") const virtual
Rotate()
void LKVector3::Rotate (Double_t angle, Axis ka = kNon)
Definition at line 171 of file LKVector3.cpp.
References fReferenceAxis, GetGlobalAxis(), GetXYZ(), kNon, and SetAt().
SetAt()
void LKVector3::SetAt (Double_t value, Axis ka, bool ignoreNegative = false)
Definition at line 120 of file LKVector3.cpp.
References e_error, kI, kJ, kK, kMI, kMJ, kMK, kMX, kMY, kMZ, kX, kY, kZ, SetI(), SetJ(), and SetK().
Referenced by Rotate(), SetI(), SetIJK(), SetJ(), and SetK().
SetI()
void LKVector3::SetI (Double_t i)
Definition at line 156 of file LKVector3.cpp.
References GetGlobalAxis(), kI, and SetAt().
Referenced by AddAt(), LKDetectorPlane::DriftElectronBack(), SetAt(), and LKPad::SetPosition().
SetIJK()
void LKVector3::SetIJK (Double_t i, Double_t j, Double_t k)
Definition at line 149 of file LKVector3.cpp.
References GetGlobalAxis(), kI, kJ, kK, and SetAt().
Referenced by LKHelixTrack::ExtrapolateToAlpha(), LKHelixTrack::ExtrapolateToPointAlpha(), LKVector3(), LKVector3(), and SetIJKR().
SetIJKR()
void LKVector3::SetIJKR (Double_t i, Double_t j, Double_t k, LKVector3::Axis referenceAxis)
Definition at line 138 of file LKVector3.cpp.
References e_error, fReferenceAxis, IsGlobalAxis(), and SetIJK().
SetJ()
void LKVector3::SetJ (Double_t j)
Definition at line 157 of file LKVector3.cpp.
References GetGlobalAxis(), kJ, and SetAt().
Referenced by AddAt(), LKDetectorPlane::DriftElectronBack(), SetAt(), and LKPad::SetPosition().
SetK()
void LKVector3::SetK (Double_t k)
Definition at line 158 of file LKVector3.cpp.
References GetGlobalAxis(), kK, and SetAt().
Referenced by AddAt(), LTHelixTrackFindingTask::CorrelateHitWithTrackCandidate(), LHHelixTrackFindingTask::CorrelateHitWithTrackCandidate(), LKGeoHelix::Direction(), LKDetectorPlane::DriftElectronBack(), LKHelixTrack::ExtrapolateToPointAlpha(), and SetAt().
SetReferenceAxis()
void LKVector3::SetReferenceAxis (LKVector3::Axis referenceAxis)
Definition at line 42 of file LKVector3.cpp.
References e_error, fReferenceAxis, and IsGlobalAxis().
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & out, const Axis axisIn) friend
Definition at line 27 of file LKVector3.h.
Member Data Documentation
fReferenceAxis
Axis LKVector3::fReferenceAxis = kNon private
Definition at line 183 of file LKVector3.h.
Referenced by ClassImp(), GetGlobalAxis(), GetReferenceAxis(), operator-(), operator=(), Rotate(), SetIJKR(), and SetReferenceAxis().
The documentation for this class was generated from the following files:
LKVector3.h
LKVector3.cpp