lilak: LKGeo2DBox Class Reference
LKGeo2DBox Class Reference
#include <LKGeo2DBox.h>
Public Member Functions
TGraph * DrawGraph ()
virtual TVector3 GetCenter () const
TVector3 GetCorner (Int_t idx) const
TVector3 GetCorner (Int_t xpm, Int_t ypm) const
Double_t GetdX () const
Double_t GetdY () const
LKGeoLine GetEdge (Int_t idx) const
LKGeoLine GetEdge (Int_t xpm, Int_t ypm) const
pm of edge axis is 0 while the other should be 1(high) or -1(low)
Double_t GetX (Int_t idx) const
Double_t GetXCenter () const
Double_t GetY (Int_t idx) const
Double_t GetYCenter () const
LKGeo2DBox ()
LKGeo2DBox (Double_t x1, Double_t x2, Double_t y1, Double_t y2)
LKGeo2DBox (Double_t xc, Double_t yc, Double_t dx, Double_t dy, Double_t rotation)
virtual void Print (Option_t *option="") const
void Rotate (Double_t deg, Double_t x, Double_t y)
void Set2DBox (Double_t x1, Double_t x2, Double_t y1, Double_t y2)
void Set2DBox (Double_t xc, Double_t yc, Double_t dx, Double_t dy, Double_t rotation)
void Translate (Double_t x, Double_t y)
virtual ~LKGeo2DBox ()
Public Member Functions inherited from LKGeoRotated
virtual void Clear (Option_t *option="")
virtual TVector3 GetCenter () const
TRotation GetRotation () const
TVector3 InvRotate (TVector3 pos) const
LKGeoRotated ()
TVector3 Rotate (TVector3 pos) const
void SetRotation (TRotation rot)
virtual ~LKGeoRotated ()
Public Member Functions inherited from LKGeometry
Double_t GetRMS () const
LKGeometry ()
void SetRMS (Double_t val)
virtual ~LKGeometry ()
Protected Attributes
Double_t fX [4]
Double_t fY [4]
Protected Attributes inherited from LKGeoRotated
TRotation fRotation
Protected Attributes inherited from LKGeometry
Double_t fRMS = -1
Detailed Description
Definition at line 10 of file LKGeo2DBox.h.
Constructor & Destructor Documentation
LKGeo2DBox() [1/3]
LKGeo2DBox::LKGeo2DBox ()
LKGeo2DBox() [2/3]
LKGeo2DBox::LKGeo2DBox (Double_t x1, Double_t x2, Double_t y1, Double_t y2)
Definition at line 10 of file LKGeo2DBox.cpp.
References Set2DBox(), and y2.
LKGeo2DBox() [3/3]
LKGeo2DBox::LKGeo2DBox (Double_t xc, Double_t yc, Double_t dx, Double_t dy, Double_t rotation)
Definition at line 15 of file LKGeo2DBox.cpp.
References Set2DBox().
~LKGeo2DBox()
virtual LKGeo2DBox::~LKGeo2DBox () inline virtual
Definition at line 16 of file LKGeo2DBox.h.
Member Function Documentation
DrawGraph()
TGraph * LKGeo2DBox::DrawGraph ()
Definition at line 119 of file LKGeo2DBox.cpp.
References GetCorner(), and SetPoint().
Referenced by LKGeoBox::Draw2DBox().
GetCenter()
TVector3 LKGeo2DBox::GetCenter () const virtual
Reimplemented from LKGeoRotated.
Definition at line 35 of file LKGeo2DBox.cpp.
References GetXCenter(), and GetYCenter().
GetCorner() [1/2]
TVector3 LKGeo2DBox::GetCorner (Int_t idx) const
Definition at line 68 of file LKGeo2DBox.cpp.
References fX, and fY.
Referenced by DrawGraph(), GetEdge(), and GetEdge().
GetCorner() [2/2]
TVector3 LKGeo2DBox::GetCorner (Int_t xpm, Int_t ypm) const
Definition at line 80 of file LKGeo2DBox.cpp.
References fX, fY, x, and y.
GetdX()
Double_t LKGeo2DBox::GetdX () const
Definition at line 61 of file LKGeo2DBox.cpp.
References fX.
GetdY()
Double_t LKGeo2DBox::GetdY () const
Definition at line 65 of file LKGeo2DBox.cpp.
References fY.
GetEdge() [1/2]
LKGeoLine LKGeo2DBox::GetEdge (Int_t idx) const
Definition at line 91 of file LKGeo2DBox.cpp.
References c1, and GetCorner().
GetEdge() [2/2]
LKGeoLine LKGeo2DBox::GetEdge (Int_t xpm, Int_t ypm) const
pm of edge axis is 0 while the other should be 1(high) or -1(low)
Definition at line 101 of file LKGeo2DBox.cpp.
References c1, and GetCorner().
GetX()
Double_t LKGeo2DBox::GetX (Int_t idx) const
Definition at line 62 of file LKGeo2DBox.cpp.
References fX.
Referenced by Print().
GetXCenter()
Double_t LKGeo2DBox::GetXCenter () const
Definition at line 60 of file LKGeo2DBox.cpp.
References fX.
Referenced by GetCenter().
GetY()
Double_t LKGeo2DBox::GetY (Int_t idx) const
Definition at line 66 of file LKGeo2DBox.cpp.
References fY.
Referenced by Print().
GetYCenter()
Double_t LKGeo2DBox::GetYCenter () const
Definition at line 64 of file LKGeo2DBox.cpp.
References fY.
Referenced by GetCenter().
Print()
void LKGeo2DBox::Print (Option_t * option = "") const virtual
Definition at line 20 of file LKGeo2DBox.cpp.
References e_cout, GetX(), and GetY().
Rotate()
void LKGeo2DBox::Rotate (Double_t deg, Double_t x, Double_t y)
Definition at line 138 of file LKGeo2DBox.cpp.
References fX, fY, x, and y.
Set2DBox() [1/2]
void LKGeo2DBox::Set2DBox (Double_t x1, Double_t x2, Double_t y1, Double_t y2)
Definition at line 37 of file LKGeo2DBox.cpp.
References fX, fY, and y2.
Referenced by LKGeo2DBox(), and LKGeo2DBox().
Set2DBox() [2/2]
void LKGeo2DBox::Set2DBox (Double_t xc, Double_t yc, Double_t dx, Double_t dy, Double_t rotation)
Definition at line 45 of file LKGeo2DBox.cpp.
References fX, and fY.
Translate()
void LKGeo2DBox::Translate (Double_t x, Double_t y)
Definition at line 130 of file LKGeo2DBox.cpp.
References fX, fY, x, and y.
Member Data Documentation
fX
Double_t LKGeo2DBox::fX[4] protected
Definition at line 47 of file LKGeo2DBox.h.
Referenced by GetCorner(), GetCorner(), GetdX(), GetX(), GetXCenter(), Rotate(), Set2DBox(), Set2DBox(), and Translate().
fY
Double_t LKGeo2DBox::fY[4] protected
Definition at line 48 of file LKGeo2DBox.h.
Referenced by GetCorner(), GetCorner(), GetdY(), GetY(), GetYCenter(), Rotate(), Set2DBox(), Set2DBox(), and Translate().
The documentation for this class was generated from the following files:
LKGeo2DBox.h
LKGeo2DBox.cpp