LILAK: LKTbIterationParameters Class Reference
LKTbIterationParameters Class Reference
#include <LKChannelAnalyzer.h>
Public Member Functions
bool Add (double c0, double t0)
LKTbIterationParameters ()
double NextTb (double tb) const
void SetScaleTbStep (double value)
double Slope () const
double TbStep () const
Public Attributes
double fC1 = DBL_MAX
double fC2 = DBL_MAX
double fScaleTbStep = 1
double fScaleTbStep0 = 1
double fT1 = 0
double fT2 = 0
Detailed Description
Definition at line 31 of file tpc_general/tool/LKChannelAnalyzer.h.
Constructor & Destructor Documentation
LKTbIterationParameters()
LKTbIterationParameters::LKTbIterationParameters () inline
Definition at line 34 of file tpc_general/tool/LKChannelAnalyzer.h.
Member Function Documentation
Add()
bool LKTbIterationParameters::Add (double c0, double t0) inline
Definition at line 66 of file tpc_general/tool/LKChannelAnalyzer.h.
References fC1, fC2, fScaleTbStep, fScaleTbStep0, fT1, and fT2.
Referenced by LKChannelAnalyzer::FitPulse().
NextTb()
double LKTbIterationParameters::NextTb (double tb) const inline
Definition at line 58 of file tpc_general/tool/LKChannelAnalyzer.h.
References TbStep().
Referenced by LKChannelAnalyzer::FitPulse().
SetScaleTbStep()
void LKTbIterationParameters::SetScaleTbStep (double value) inline
Definition at line 43 of file tpc_general/tool/LKChannelAnalyzer.h.
References fScaleTbStep, and fScaleTbStep0.
Referenced by LKChannelAnalyzer::FitPulse().
Slope()
double LKTbIterationParameters::Slope () const inline
Definition at line 48 of file tpc_general/tool/LKChannelAnalyzer.h.
References fC1, fC2, fT1, and fT2.
Referenced by LKChannelAnalyzer::FitPulse(), and TbStep().
TbStep()
double LKTbIterationParameters::TbStep () const inline
Definition at line 53 of file tpc_general/tool/LKChannelAnalyzer.h.
References fScaleTbStep, and Slope().
Referenced by LKChannelAnalyzer::FitPulse(), and NextTb().
Member Data Documentation
fC1
double LKTbIterationParameters::fC1 = DBL_MAX
Definition at line 36 of file tpc_general/tool/LKChannelAnalyzer.h.
Referenced by Add(), LKChannelAnalyzer::FitPulse(), and Slope().
fC2
double LKTbIterationParameters::fC2 = DBL_MAX
Definition at line 37 of file tpc_general/tool/LKChannelAnalyzer.h.
Referenced by Add(), and Slope().
fScaleTbStep
double LKTbIterationParameters::fScaleTbStep = 1
Definition at line 41 of file tpc_general/tool/LKChannelAnalyzer.h.
Referenced by Add(), SetScaleTbStep(), and TbStep().
fScaleTbStep0
double LKTbIterationParameters::fScaleTbStep0 = 1
Definition at line 40 of file tpc_general/tool/LKChannelAnalyzer.h.
Referenced by Add(), and SetScaleTbStep().
fT1
double LKTbIterationParameters::fT1 = 0
Definition at line 38 of file tpc_general/tool/LKChannelAnalyzer.h.
Referenced by Add(), LKChannelAnalyzer::FitPulse(), and Slope().
fT2
double LKTbIterationParameters::fT2 = 0
Definition at line 39 of file tpc_general/tool/LKChannelAnalyzer.h.
Referenced by Add(), and Slope().
The documentation for this class was generated from the following file:
tpc_general/tool/LKChannelAnalyzer.h