lilak: Json::FastWriter Class Reference
Json::FastWriter Class Reference
Outputs a Value in JSON format without formatting (not human friendly).
#include <json.h>
Public Member Functions
void dropNullPlaceholders ()
Drop the "null" string from the writer's output for nullValues. Strictly speaking, this is not valid JSON. But when the output is being fed to a browser's JavaScript, it makes for smaller output and the browser can handle the output just fine.
void enableYAMLCompatibility ()
FastWriter ()
void omitEndingLineFeed ()
String write (const Value &root) override
~FastWriter () override=default
Public Member Functions inherited from Json::Writer
virtual String write (const Value &root)=0
virtual ~Writer ()
Private Member Functions
void writeValue (const Value &value)
Private Attributes
String document_
bool dropNullPlaceholders_ {false}
bool omitEndingLineFeed_ {false}
bool yamlCompatibilityEnabled_ {false}
Detailed Description
Outputs a Value in JSON format without formatting (not human friendly).
The JSON document is written in a single line. It is not intended for 'human' consumption, but may be useful to support feature such as RPC where bandwidth is limited.
See also
Reader, Value
Deprecated:
Use StreamWriterBuilder.
Definition at line 2067 of file json.h.
Constructor & Destructor Documentation
FastWriter()
Json::FastWriter::FastWriter () default
~FastWriter()
Json::FastWriter::~FastWriter () override default
Member Function Documentation
dropNullPlaceholders()
void Json::FastWriter::dropNullPlaceholders ()
Drop the "null" string from the writer's output for nullValues. Strictly speaking, this is not valid JSON. But when the output is being fed to a browser's JavaScript, it makes for smaller output and the browser can handle the output just fine.
Definition at line 4443 of file jsoncpp.cpp.
References dropNullPlaceholders_.
enableYAMLCompatibility()
void Json::FastWriter::enableYAMLCompatibility ()
Definition at line 4441 of file jsoncpp.cpp.
References yamlCompatibilityEnabled_.
omitEndingLineFeed()
void Json::FastWriter::omitEndingLineFeed ()
Definition at line 4445 of file jsoncpp.cpp.
References omitEndingLineFeed_.
write()
String Json::FastWriter::write (const Value & root) override virtual
Implements Json::Writer.
Definition at line 4447 of file jsoncpp.cpp.
References document_, omitEndingLineFeed_, and writeValue().
writeValue()
void Json::FastWriter::writeValue (const Value & value) private
Definition at line 4455 of file jsoncpp.cpp.
References Json::arrayValue, Json::Value::asBool(), Json::Value::asDouble(), Json::Value::asLargestInt(), Json::Value::asLargestUInt(), Json::booleanValue, document_, dropNullPlaceholders_, Json::Value::getMemberNames(), Json::Value::getString(), Json::intValue, Json::nullValue, Json::objectValue, Json::realValue, Json::Value::size(), Json::stringValue, Json::Value::type(), Json::uintValue, Json::valueToQuotedStringN(), Json::valueToString(), writeValue(), and yamlCompatibilityEnabled_.
Referenced by write(), and writeValue().
Member Data Documentation
document_
String Json::FastWriter::document_ private
Definition at line 2090 of file json.h.
Referenced by write(), and writeValue().
dropNullPlaceholders_
bool Json::FastWriter::dropNullPlaceholders_ {false} private
Definition at line 2092 of file json.h.
Referenced by dropNullPlaceholders(), and writeValue().
omitEndingLineFeed_
bool Json::FastWriter::omitEndingLineFeed_ {false} private
Definition at line 2093 of file json.h.
Referenced by omitEndingLineFeed(), and write().
yamlCompatibilityEnabled_
bool Json::FastWriter::yamlCompatibilityEnabled_ {false} private
Definition at line 2091 of file json.h.
Referenced by enableYAMLCompatibility(), and writeValue().
The documentation for this class was generated from the following files:
json.h
jsoncpp.cpp