lilak: ejungwoo::Range Class Reference
ejungwoo::Range Class Reference
#include <ejungwooA.h>
Public Member Functions
void AddRange (double range1, double range2, bool setToMaximum)
void AddRange (double range1, double range2, bool setToMaximum)
void AddRange (double range1, double range2, bool setToMaximum)
bool IsInRange (double value)
bool IsInRange (double value)
bool IsInRange (double value)
Range ()
Range ()
Range ()
Range (double range1, double range2, bool setToMaximum)
Range (double range1, double range2, bool setToMaximum)
Range (double range1, double range2, bool setToMaximum)
double SetValue (double value)
double SetValue (double value)
double SetValue (double value)
Public Attributes
int fNumRanges = 0
vector< double > fRange1
vector< double > fRange2
double fRangeMaximum
double fRangeMinimum
bool fSetToMaximum = true
Detailed Description
Definition at line 275 of file macros_detectorplane/ejungwooA.h.
Constructor & Destructor Documentation
Range() [1/6]
ejungwoo::Range::Range () inline
Definition at line 285 of file macros_detectorplane/ejungwooA.h.
Range() [2/6]
ejungwoo::Range::Range (double range1, double range2, bool setToMaximum) inline
Definition at line 286 of file macros_detectorplane/ejungwooA.h.
References AddRange().
Range() [3/6]
ejungwoo::Range::Range () inline
Definition at line 286 of file macros_hough/ejungwooA.h.
Range() [4/6]
ejungwoo::Range::Range (double range1, double range2, bool setToMaximum) inline
Definition at line 287 of file macros_hough/ejungwooA.h.
References AddRange().
Range() [5/6]
ejungwoo::Range::Range () inline
Definition at line 285 of file macros_psa/ejungwooA.h.
Range() [6/6]
ejungwoo::Range::Range (double range1, double range2, bool setToMaximum) inline
Definition at line 286 of file macros_psa/ejungwooA.h.
References AddRange().
Member Function Documentation
AddRange() [1/3]
void ejungwoo::Range::AddRange (double range1, double range2, bool setToMaximum) inline
Definition at line 289 of file macros_detectorplane/ejungwooA.h.
References fNumRanges, fRange1, fRange2, fRangeMaximum, fRangeMinimum, and fSetToMaximum.
Referenced by Range().
AddRange() [2/3]
void ejungwoo::Range::AddRange (double range1, double range2, bool setToMaximum) inline
Definition at line 290 of file macros_hough/ejungwooA.h.
References fNumRanges, fRange1, fRange2, fRangeMaximum, fRangeMinimum, and fSetToMaximum.
AddRange() [3/3]
void ejungwoo::Range::AddRange (double range1, double range2, bool setToMaximum) inline
Definition at line 289 of file macros_psa/ejungwooA.h.
References fNumRanges, fRange1, fRange2, fRangeMaximum, fRangeMinimum, and fSetToMaximum.
IsInRange() [1/3]
bool ejungwoo::Range::IsInRange (double value) inline
Definition at line 302 of file macros_detectorplane/ejungwooA.h.
References fNumRanges, fRange1, and fRange2.
Referenced by SetValue().
IsInRange() [2/3]
bool ejungwoo::Range::IsInRange (double value) inline
Definition at line 303 of file macros_hough/ejungwooA.h.
References fNumRanges, fRange1, and fRange2.
IsInRange() [3/3]
bool ejungwoo::Range::IsInRange (double value) inline
Definition at line 302 of file macros_psa/ejungwooA.h.
References fNumRanges, fRange1, and fRange2.
SetValue() [1/3]
double ejungwoo::Range::SetValue (double value) inline
Definition at line 313 of file macros_detectorplane/ejungwooA.h.
References fRangeMaximum, fRangeMinimum, fSetToMaximum, and IsInRange().
Referenced by ejungwoo::Frame().
SetValue() [2/3]
double ejungwoo::Range::SetValue (double value) inline
Definition at line 314 of file macros_hough/ejungwooA.h.
References fRangeMaximum, fRangeMinimum, fSetToMaximum, and IsInRange().
SetValue() [3/3]
double ejungwoo::Range::SetValue (double value) inline
Definition at line 313 of file macros_psa/ejungwooA.h.
References fRangeMaximum, fRangeMinimum, fSetToMaximum, and IsInRange().
Member Data Documentation
fNumRanges
int ejungwoo::Range::fNumRanges = 0
Definition at line 278 of file macros_detectorplane/ejungwooA.h.
Referenced by AddRange(), and IsInRange().
fRange1
vector< double > ejungwoo::Range::fRange1
Definition at line 281 of file macros_detectorplane/ejungwooA.h.
Referenced by AddRange(), and IsInRange().
fRange2
vector< double > ejungwoo::Range::fRange2
Definition at line 282 of file macros_detectorplane/ejungwooA.h.
Referenced by AddRange(), and IsInRange().
fRangeMaximum
double ejungwoo::Range::fRangeMaximum
Definition at line 279 of file macros_detectorplane/ejungwooA.h.
Referenced by AddRange(), and SetValue().
fRangeMinimum
double ejungwoo::Range::fRangeMinimum
Definition at line 280 of file macros_detectorplane/ejungwooA.h.
Referenced by AddRange(), and SetValue().
fSetToMaximum
bool ejungwoo::Range::fSetToMaximum = true
Definition at line 283 of file macros_detectorplane/ejungwooA.h.
Referenced by AddRange(), and SetValue().
The documentation for this class was generated from the following files:
macros_detectorplane/ejungwooA.h
macros_hough/ejungwooA.h
macros_psa/ejungwooA.h