lilak: TTFrontPlane Class Reference
TTFrontPlane Class Reference
#include <TTFrontPlane.h>
Public Member Functions
void Clear (Option_t *option="")
void Draw (Option_t *option="")
Implementation recommanded for event display. Draw event display to the canvas.
void DrawFrame (Option_t *option="")
void FillDataToHist ()
Implementation recommanded. Fill data to histograms.
Int_t FindChannelID (Double_t x, Double_t y)
Int_t FindChannelID (Int_t section, Int_t row, Int_t layer)
TCanvas * GetCanvas (Option_t *option="")
Implementation recommanded for event display.
TH2 * GetHist (Option_t *option="")
bool Init ()
bool IsInBoundary (Double_t x, Double_t y)
void Print (Option_t *option="") const
void SelectAndDrawChannel (bool isChain=0, Int_t bin=-1)
void SelectAndDrawChannelChain (Int_t bin=-1)
bool SetDataFromBranch ()
Implementation recommanded. Set waveform and hit data from input tree branches to pads.
TTFrontPlane ()
virtual ~TTFrontPlane ()
Public Member Functions inherited from LKPadPlane
void AddHit (LKTpcHit *hit)
virtual void Clear (Option_t *option="")
virtual void DrawHist ()
virtual TVector3 DriftElectron (TVector3 xGlobal)
return (x,y,l). l : electron-drift-length
void FillBufferIn (Double_t i, Double_t j, Double_t tb, Double_t val, Int_t trackID=-1)
void FillDataToHist ()
Implementation recommanded. Fill data to histograms.
virtual Int_t FindChannelID (Double_t i, Double_t j)
virtual Int_t FindChannelID (Int_t section, Int_t layer, Int_t row)
virtual Int_t FindPadID (Double_t i, Double_t j)
virtual Int_t FindPadID (Int_t section, Int_t layer, Int_t row)
Int_t GetNumPads ()
LKPad * GetPad (Double_t i, Double_t j)
LKPad * GetPad (Int_t padID)
LKPad * GetPad (Int_t section, Int_t layer, Int_t row)
TObjArray * GetPadArray ()
LKPad * GetPadFast (Int_t padID)
void GrabNeighborPads (vector< LKPad * > *pads, vector< LKPad * > *neighborPads)
LKPadPlane ()
LKPadPlane (const char *name, const char *title)
Double_t PadDisplacement () const
Return average pad displacement to each other.
bool PadNeighborChecker ()
bool PadPositionChecker (bool checkCorners=true)
virtual void Print (Option_t *option="") const
void PullOutNeighborHits (Double_t x, Double_t y, Int_t range, LKHitArray *neighborHits)
void PullOutNeighborHits (Double_t x, Double_t y, Int_t range, vector< LKTpcHit * > *neighborHits)
void PullOutNeighborHits (LKHitArray *hits, LKHitArray *neighborHits)
void PullOutNeighborHits (TVector2 p, Int_t range, vector< LKTpcHit * > *neighborHits)
void PullOutNeighborHits (vector< LKTpcHit * > *hits, vector< LKTpcHit * > *neighborHits)
virtual LKTpcHit * PullOutNextFreeHit ()
For tracking use.
virtual void ResetEvent ()
For tracking use.
virtual void ResetHitMap ()
For tracking use.
virtual bool SetDataFromBranch ()
Implementation recommanded. Set waveform and hit data from input tree branches to pads.
void SetHitArray (TClonesArray *hitArray)
void SetPadArray (TClonesArray *padArray)
virtual TVector3 TbToGlobalPosition (LKPad *pad, int tb)
virtual ~LKPadPlane ()
Public Member Functions inherited from LKDetectorPlane
void AddChannel (LKChannel *channel)
Add channel to channel array in detector plane. For interanl use.
void AddHit (LKHit *hit)
void AddPad (LKPad *pad)
Add pad to pad array in detector plane. For interanl use.
virtual void Clear (Option_t *option="")
virtual void Draw (Option_t *option="")
Implementation recommanded for event display. Draw event display to the canvas.
virtual void DrawFrame (Option_t *option="")
virtual void DrawHist (Option_t *option="")
virtual void DriftElectron (TVector3 posGlobal, TVector3 &posFinal, double &driftLength)
virtual double DriftElectronBack (double tb)
virtual void DriftElectronBack (int padID, double tb, TVector3 &posReco, double &driftLength)
virtual void DriftElectronBack (LKPad *pad, double tb, TVector3 &posReco, double &driftLength)
virtual void FillDataToHist ()
Implementation recommanded. Fill data to histograms.
void FillPlane (double i, double j, double tb, double charge, int trackID=-1)
Find pad corresponding to the position (i,j) and fill time-bin by amount of charge.
virtual int FindChannelID (double i, double j)
Implementation recommanded. Find channel using position.
virtual int FindChannelID (int section, int layer, int row)
Implementation recommanded. Find channel using section, layer, row info.
virtual int FindPadID (double i, double j)
virtual int FindPadID (int cobo, int asad, int aget, int chan)
virtual int FindPadID (int section, int layer, int row)
virtual TPad * Get3DEventPad ()
If user wants to place 3D event display other than default canvas, this method should return corresponding TPad.
virtual axis_t GetAxis1 (int iPad=0) const
virtual axis_t GetAxis2 (int iPad=0) const
virtual axis_t GetAxis3 () const
virtual axis_t GetAxisDrift () const
virtual TCanvas * GetCanvas (Option_t *option="")
Implementation recommanded for event display.
LKChannel * GetChannel (int idx)
virtual LKChannelAnalyzer * GetChannelAnalyzer (int id=0)
TObjArray * GetChannelArray ()
LKChannel * GetChannelFast (int idx)
virtual TPad * GetCPad (int iPad)
For grabbing inner pads of canvas.
virtual TH2 * GetHist (Option_t *option="-1")
int GetNChannels ()
virtual int GetNumCPads ()
Get number of inner pads of canvas.
int GetNumPads ()
LKPad * GetPad (double i, double j)
LKPad * GetPad (int cobo, int asad, int aget, int chan)
LKPad * GetPad (int padID)
LKPad * GetPad (int section, int layer, int row)
TObjArray * GetPadArray ()
LKPad * GetPadFast (int idx)
int GetPlaneID () const
double GetPosition () const
virtual TVector3 GetPositionError (int padID)
double GetTbToLength () const
virtual TVector3 GlobalToLocalAxis (TVector3 posGlobal)
Implementation recommanded. Convert global position to local detector plane position.
void GrabNeighborPads (vector< LKPad * > *pads, vector< LKPad * > *neighborPads)
For tracking use.
virtual bool Init ()
virtual bool IsInBoundary (double i, double j)
Implementation recommanded. Return if position (i,j) is inside the effective detector plane boundary.
LKDetectorPlane ()
LKDetectorPlane (const char *name, const char *title)
virtual TVector3 LocalToGlobalAxis (TVector3 posLocal)
virtual double PadDisplacement () const
Return average pad displacement to each other.
bool PadMapChecker ()
bool PadNeighborChecker ()
bool PadPositionChecker (bool checkCorners=true)
virtual void Print (Option_t *option="") const
void PullOutNeighborHits (double x, double y, int range, LKHitArray *neighborHits)
For tracking use.
void PullOutNeighborHits (double x, double y, int range, vector< LKHit * > *neighborHits)
For tracking use.
void PullOutNeighborHits (LKHitArray *hits, LKHitArray *neighborHits)
For tracking use.
void PullOutNeighborHits (TVector2 p, int range, vector< LKHit * > *neighborHits)
For tracking use.
void PullOutNeighborHits (vector< LKHit * > *hits, vector< LKHit * > *neighborHits)
For tracking use.
virtual LKHit * PullOutNextFreeHit ()
For tracking use.
virtual void ResetEvent ()
For tracking use.
virtual void ResetHitMap ()
For tracking use.
virtual bool SetDataFromBranch ()
Implementation recommanded. Set waveform and hit data from input tree branches to pads.
void SetDetector (LKDetector *detector)
void SetDetectorName (TString name)
void SetHitArray (TClonesArray *hitArray)
void SetPadArray (TClonesArray *padArray)
void SetPlaneID (int id)
virtual ~LKDetectorPlane ()
Public Member Functions inherited from LKGear
void AddPar (LKParameterContainer *par)
void AddPar (TString fname)
virtual void AddParameterContainer (LKParameterContainer *par)
virtual void AddParameterContainer (TString fname)
void CreateParameterContainer ()
LKParameterContainer * GetPar () const
LKParameterContainer * GetParameterContainer () const
Int_t GetRank () const
LKGear ()
void SetPar (LKParameterContainer *par)
virtual void SetParameterContainer (LKParameterContainer *par)
virtual void SetRank (Int_t rank)
void SetRun (LKRun *run)
virtual ~LKGear ()
Static Public Member Functions
static TTFrontPlane * GetMMCC ()
static void MouseClickEventChain ()
Private Member Functions
ClassDef (TTFrontPlane, 1)
Private Attributes
TClonesArray * fBufferArray = nullptr
TGraph * fGraphChannelBoundaryChain = nullptr
TH1D * fHistChannelChain = nullptr
TH2Poly * fHistPlaneChain = nullptr
TClonesArray * fHitCenterArray = nullptr
TClonesArray * fHitLChainArray = nullptr
TClonesArray * fHitRChainArray = nullptr
std::map< int, int > fMapBinToCAACChain
std::map< int, double > fMapBinToX1Chain
std::map< int, double > fMapBinToX2Chain
std::map< int, double > fMapBinToZ1Chain
std::map< int, double > fMapBinToZ2Chain
std::map< int, int > fMapCAACToBinChain
Double_t fXMax = -DBL_MAX
double_t fXMin = DBL_MAX
Double_t fZMax = -DBL_MAX
Double_t fZMin = DBL_MAX
Static Private Attributes
static TTFrontPlane * fInstance = nullptr
Additional Inherited Members
Protected Attributes inherited from LKPadPlane
TCanvas * fCvsChannelBuffer = nullptr
Int_t fEFieldAxis = -1
bool fFilledHit = false
bool fFilledPad = false
Int_t fFreePadIdx = 0
TGraph * fGraphChannelBoundary = nullptr
TGraph * fGraphChannelBoundaryNb [20] = {0}
Protected Attributes inherited from LKDetectorPlane
axis_t fAxis1 = LKVector3::kNon
Axis-1 lying in plane. Must be set by input parameter.
axis_t fAxis2 = LKVector3::kNon
Axis-2 lying in plane. Must be set by input parameter.
axis_t fAxis3 = LKVector3::kNon
Axis-3 = Axis-1 x Axis-2 perpendicular to plane.
axis_t fAxisDrift = LKVector3::kNon
Axis perpendicular to plane, in electron drifting direction. Must be set by input parameter.
TCanvas * fCanvas = nullptr
LKChannelAnalyzer * fChannelAnalyzer = nullptr
TObjArray * fChannelArray = nullptr
TCanvas * fCvsChannelBuffer = nullptr
LKDetector * fDetector = nullptr
TString fDetName
int fFreePadIdx = 0
TGraph * fGraphChannelBoundary = nullptr
TGraph * fGraphChannelBoundaryNb [20] = {0}
TH2 * fH2Plane = nullptr
bool fHitDataIsSet = false
bool fPadDataIsSet = false
int fPlaneID = -1
Detector plane id.
double fPosition
Global position of pad plane center.
double fTbToLength = 1
time-bin (tb) to position conversion factor. Must be set by input parameter.
Protected Attributes inherited from LKGear
LKParameterContainer * fPar = nullptr
Int_t fRank = 0
LKRun * fRun = nullptr
Detailed Description
Definition at line 56 of file TTFrontPlane.h.
Constructor & Destructor Documentation
TTFrontPlane()
TTFrontPlane::TTFrontPlane ()
Definition at line 8 of file TTFrontPlane.cpp.
References fInstance.
~TTFrontPlane()
virtual TTFrontPlane::~TTFrontPlane () inline virtual
Definition at line 62 of file TTFrontPlane.h.
Member Function Documentation
ClassDef()
TTFrontPlane::ClassDef (TTFrontPlane , 1) private
Clear()
void TTFrontPlane::Clear (Option_t * option = "") virtual
Reimplemented from LKPadPlane.
Definition at line 68 of file TTFrontPlane.cpp.
References LKPadPlane::Clear().
Draw()
void TTFrontPlane::Draw (Option_t * option = "") virtual
Implementation recommanded for event display. Draw event display to the canvas.
Reimplemented from LKDetectorPlane.
Definition at line 269 of file TTFrontPlane.cpp.
References cvs, Draw(), fHistChannelChain, fHistPlaneChain, FillDataToHist(), and GetCanvas().
Referenced by Draw(), GetCanvas(), and SelectAndDrawChannel().
DrawFrame()
void TTFrontPlane::DrawFrame (Option_t * option = "") virtual
Reimplemented from LKDetectorPlane.
Definition at line 264 of file TTFrontPlane.cpp.
FillDataToHist()
void TTFrontPlane::FillDataToHist () virtual
Implementation recommanded. Fill data to histograms.
Reimplemented from LKPadPlane.
Definition at line 134 of file TTFrontPlane.cpp.
References fHistPlaneChain, fHitCenterArray, fHitLChainArray, fHitRChainArray, LKDetectorPlane::GetPosition(), and SelectAndDrawChannelChain().
Referenced by Draw().
FindChannelID() [1/2]
Int_t TTFrontPlane::FindChannelID (Double_t x, Double_t y) virtual
Reimplemented from LKPadPlane.
Definition at line 85 of file TTFrontPlane.cpp.
FindChannelID() [2/2]
Int_t TTFrontPlane::FindChannelID (Int_t section, Int_t row, Int_t layer) virtual
Reimplemented from LKPadPlane.
Definition at line 91 of file TTFrontPlane.cpp.
GetCanvas()
TCanvas * TTFrontPlane::GetCanvas (Option_t * option = "") virtual
Implementation recommanded for event display.
Reimplemented from LKDetectorPlane.
Definition at line 99 of file TTFrontPlane.cpp.
References Draw(), and LKDetectorPlane::fCanvas.
Referenced by Draw(), and MouseClickEventChain().
GetHist()
TH2 * TTFrontPlane::GetHist (Option_t * option = "") virtual
Reimplemented from LKDetectorPlane.
Definition at line 117 of file TTFrontPlane.cpp.
References fHistPlaneChain.
GetMMCC()
TTFrontPlane * TTFrontPlane::GetMMCC () static
Definition at line 6 of file TTFrontPlane.cpp.
References fInstance.
Referenced by MouseClickEventChain().
Init()
bool TTFrontPlane::Init () virtual
Implementation recommanded. Init() method should implement pad information (id, position, neighbor) and add channel using AddChannel() or AddPad() method. All parameters should be configured such as axis-1,2,3, fPosition, fTbToLength from parameter container.
Reimplemented from LKDetectorPlane.
Definition at line 14 of file TTFrontPlane.cpp.
References e_info, fGraphChannelBoundaryChain, fHistChannelChain, fHistPlaneChain, fMapBinToCAACChain, fMapBinToX1Chain, fMapBinToX2Chain, fMapBinToZ1Chain, fMapBinToZ2Chain, fMapCAACToBinChain, LKGear::fPar, fXMax, fXMin, fZMax, fZMin, SetDataFromBranch(), x0, z0, z1, and z2.
IsInBoundary()
bool TTFrontPlane::IsInBoundary (Double_t x, Double_t y)
Definition at line 78 of file TTFrontPlane.cpp.
References fXMin, fZMax, and fZMin.
MouseClickEventChain()
void TTFrontPlane::MouseClickEventChain () static
Definition at line 294 of file TTFrontPlane.cpp.
References GetCanvas(), GetMMCC(), and SelectAndDrawChannelChain().
Print()
void TTFrontPlane::Print (Option_t * option = "") const virtual
Reimplemented from LKPadPlane.
Definition at line 73 of file TTFrontPlane.cpp.
References e_info.
SelectAndDrawChannel()
void TTFrontPlane::SelectAndDrawChannel (bool isChain = 0, Int_t bin = -1)
Definition at line 154 of file TTFrontPlane.cpp.
References Draw(), fBufferArray, LKDetectorPlane::fCanvas, LKDetectorPlane::fDetector, fGraphChannelBoundaryChain, fHistChannelChain, fHitCenterArray, fHitLChainArray, fHitRChainArray, fMapBinToCAACChain, fMapBinToX1Chain, fMapBinToX2Chain, fMapBinToZ1Chain, fMapBinToZ2Chain, fMapCAACToBinChain, LKDetectorPlane::GetChannelAnalyzer(), iChannel, lk_info, SetPoint(), x0, z0, z1, and z2.
Referenced by SelectAndDrawChannelChain().
SelectAndDrawChannelChain()
void TTFrontPlane::SelectAndDrawChannelChain (Int_t bin = -1) inline
Definition at line 80 of file TTFrontPlane.h.
References SelectAndDrawChannel().
Referenced by FillDataToHist(), and MouseClickEventChain().
SetDataFromBranch()
bool TTFrontPlane::SetDataFromBranch () virtual
Implementation recommanded. Set waveform and hit data from input tree branches to pads.
Reimplemented from LKPadPlane.
Definition at line 122 of file TTFrontPlane.cpp.
References fBufferArray, fHitCenterArray, fHitLChainArray, fHitRChainArray, and LKGear::fRun.
Referenced by Init().
Member Data Documentation
fBufferArray
TClonesArray* TTFrontPlane::fBufferArray = nullptr private
Definition at line 96 of file TTFrontPlane.h.
Referenced by SelectAndDrawChannel(), and SetDataFromBranch().
fGraphChannelBoundaryChain
TGraph* TTFrontPlane::fGraphChannelBoundaryChain = nullptr private
Definition at line 94 of file TTFrontPlane.h.
Referenced by Init(), and SelectAndDrawChannel().
fHistChannelChain
TH1D* TTFrontPlane::fHistChannelChain = nullptr private
Definition at line 88 of file TTFrontPlane.h.
Referenced by Draw(), Init(), and SelectAndDrawChannel().
fHistPlaneChain
TH2Poly* TTFrontPlane::fHistPlaneChain = nullptr private
Definition at line 87 of file TTFrontPlane.h.
Referenced by Draw(), FillDataToHist(), GetHist(), and Init().
fHitCenterArray
TClonesArray* TTFrontPlane::fHitCenterArray = nullptr private
Definition at line 97 of file TTFrontPlane.h.
Referenced by FillDataToHist(), SelectAndDrawChannel(), and SetDataFromBranch().
fHitLChainArray
TClonesArray* TTFrontPlane::fHitLChainArray = nullptr private
Definition at line 98 of file TTFrontPlane.h.
Referenced by FillDataToHist(), SelectAndDrawChannel(), and SetDataFromBranch().
fHitRChainArray
TClonesArray* TTFrontPlane::fHitRChainArray = nullptr private
Definition at line 99 of file TTFrontPlane.h.
Referenced by FillDataToHist(), SelectAndDrawChannel(), and SetDataFromBranch().
fInstance
TTFrontPlane * TTFrontPlane::fInstance = nullptr static private
Definition at line 108 of file TTFrontPlane.h.
Referenced by GetMMCC(), and TTFrontPlane().
fMapBinToCAACChain
std::map<int, int> TTFrontPlane::fMapBinToCAACChain private
Definition at line 101 of file TTFrontPlane.h.
Referenced by Init(), and SelectAndDrawChannel().
fMapBinToX1Chain
std::map<int, double> TTFrontPlane::fMapBinToX1Chain private
Definition at line 103 of file TTFrontPlane.h.
Referenced by Init(), and SelectAndDrawChannel().
fMapBinToX2Chain
std::map<int, double> TTFrontPlane::fMapBinToX2Chain private
Definition at line 104 of file TTFrontPlane.h.
Referenced by Init(), and SelectAndDrawChannel().
fMapBinToZ1Chain
std::map<int, double> TTFrontPlane::fMapBinToZ1Chain private
Definition at line 105 of file TTFrontPlane.h.
Referenced by Init(), and SelectAndDrawChannel().
fMapBinToZ2Chain
std::map<int, double> TTFrontPlane::fMapBinToZ2Chain private
Definition at line 106 of file TTFrontPlane.h.
Referenced by Init(), and SelectAndDrawChannel().
fMapCAACToBinChain
std::map<int, int> TTFrontPlane::fMapCAACToBinChain private
Definition at line 102 of file TTFrontPlane.h.
Referenced by Init(), and SelectAndDrawChannel().
fXMax
Double_t TTFrontPlane::fXMax = -DBL_MAX private
Definition at line 90 of file TTFrontPlane.h.
Referenced by Init().
fXMin
double_t TTFrontPlane::fXMin = DBL_MAX private
Definition at line 89 of file TTFrontPlane.h.
Referenced by Init(), and IsInBoundary().
fZMax
Double_t TTFrontPlane::fZMax = -DBL_MAX private
Definition at line 92 of file TTFrontPlane.h.
Referenced by Init(), and IsInBoundary().
fZMin
Double_t TTFrontPlane::fZMin = DBL_MAX private
Definition at line 91 of file TTFrontPlane.h.
Referenced by Init(), and IsInBoundary().
The documentation for this class was generated from the following files:
TTFrontPlane.h
TTFrontPlane.cpp