LILAK: LKParamPointRT Class Reference
LKParamPointRT Class Reference
#include <LKParamPointRT.h>
Public Member Functions
ClassDef (LKParamPointRT, 1)
void Clear (Option_t *option="")
void Copy (TObject &object) const
double CorrelateBoxBand (LKImagePoint *imagePoint)
double CorrelateBoxLine (LKImagePoint *imagePoint)
double CorrelateBoxRibbon (LKImagePoint *imagePoint)
double DistanceToImagePoint (int iParamCorner, LKImagePoint *imagePoint)
double DistanceToImagePoint (LKImagePoint *imagePoint)
double DistanceToPoint (int iParamCorner, TVector3 point)
double DistanceToPoint (TVector3 point)
double EvalX (double y) const
double EvalX (int iParamCorner, double y) const
double EvalY (double x) const
double EvalY (int iParamCorner, double x) const
TGraph * GetBandInImageSpace (double x1, double x2, double y1, double y2)
double GetCenterR () const
double GetCenterT () const
TVector3 GetCorner (int iParamCorner) const
LKGeoLine GetGeoLine (int iParamCorner, double x1, double x2, double y1, double y2)
LKGeoLine GetGeoLineInImageSpace (int iParamCorner, double x1, double x2, double y1, double y2)
void GetImagePoints (int iParamCorner, double &x1, double &x2, double &y1, double &y2)
TGraph * GetLineInImageSpace (int iParamCorner, double x1, double x2, double y1, double y2)
TVector3 GetPOCA (int iParamCorner)
double GetR0 () const
double GetR1 () const
double GetR2 () const
TGraph * GetRadialLineInImageSpace (int iParamCorner, double angleSize)
TGraph * GetRangeGraphInParamSpace (bool drawYX=true)
TGraph * GetRibbonInImageSpace (double x1, double x2, double y1, double y2)
double GetT0 () const
double GetT1 () const
double GetT2 () const
double GetWeight () const
bool IsInside (double r, double t)
LKParamPointRT ()
LKParamPointRT (double xc, double yc, double r1, double t1, double r2, double t2, double w=0)
void Print (Option_t *option="") const
void SetPoint (double xc, double yc, double r1, double t1, double r2, double t2, double w)
void SetRadius (double r1, double r2)
void SetTheta (double t1, double t2)
void SetTransformCenter (double xc, double yc)
void SetWeight (double weight)
virtual ~LKParamPointRT ()
Public Attributes
double fRadius0
double fRadius1
double fRadius2
double fTheta0
double fTheta1
double fTheta2
double fWeight
double fXTransformCenter
double fYTransformCenter
Detailed Description
Indexing iParamCorner
0 : center of parameter bin
1 : left bottom corner of parameter bin
2 : left top corner of parameter bin
3 : right bottom corner of parameter bin
4 : right top corner of parameter bin
9rrtt : rr and tt range between 0 - 10. The parameter point will be (r, t) where r = r1 + 0.1*rr*(r2-r1) and t = t1 + 0.1*tt*(t2-t1).
Definition at line 22 of file LKParamPointRT.h.
Constructor & Destructor Documentation
LKParamPointRT() [1/2]
LKParamPointRT::LKParamPointRT ()
Definition at line 7 of file LKParamPointRT.cpp.
References Clear().
LKParamPointRT() [2/2]
LKParamPointRT::LKParamPointRT (double xc, double yc, double r1, double t1, double r2, double t2, double w = 0)
Definition at line 12 of file LKParamPointRT.cpp.
References Clear(), SetPoint(), t1, and t2.
~LKParamPointRT()
virtual LKParamPointRT::~LKParamPointRT () inline virtual
Definition at line 28 of file LKParamPointRT.h.
Member Function Documentation
ClassDef()
LKParamPointRT::ClassDef (LKParamPointRT , 1)
Clear()
void LKParamPointRT::Clear (Option_t * option = "")
Definition at line 18 of file LKParamPointRT.cpp.
References fRadius0, fRadius1, fRadius2, fTheta0, fTheta1, fTheta2, fWeight, fXTransformCenter, and fYTransformCenter.
Referenced by LKParamPointRT(), and LKParamPointRT().
Copy()
void LKParamPointRT::Copy (TObject & object) const
Definition at line 39 of file LKParamPointRT.cpp.
References fRadius1, fRadius2, fTheta1, and fWeight.
CorrelateBoxBand()
double LKParamPointRT::CorrelateBoxBand (LKImagePoint * imagePoint)
Definition at line 463 of file LKParamPointRT.cpp.
References DistanceToPoint(), EvalY(), LKImagePoint::GetCenter(), and GetCorner().
CorrelateBoxLine()
double LKParamPointRT::CorrelateBoxLine (LKImagePoint * imagePoint)
Definition at line 398 of file LKParamPointRT.cpp.
References DistanceToPoint(), EvalY(), LKImagePoint::GetCenter(), and GetCorner().
CorrelateBoxRibbon()
double LKParamPointRT::CorrelateBoxRibbon (LKImagePoint * imagePoint)
Definition at line 417 of file LKParamPointRT.cpp.
References DistanceToPoint(), EvalY(), LKImagePoint::GetCenter(), and GetCorner().
DistanceToImagePoint() [1/2]
double LKParamPointRT::DistanceToImagePoint (int iParamCorner, LKImagePoint * imagePoint)
Definition at line 520 of file LKParamPointRT.cpp.
References DistanceToPoint(), and LKImagePoint::GetCenter().
DistanceToImagePoint() [2/2]
double LKParamPointRT::DistanceToImagePoint (LKImagePoint * imagePoint)
Definition at line 514 of file LKParamPointRT.cpp.
References DistanceToPoint(), and LKImagePoint::GetCenter().
DistanceToPoint() [1/2]
double LKParamPointRT::DistanceToPoint (int iParamCorner, TVector3 point)
Definition at line 383 of file LKParamPointRT.cpp.
References GetImagePoints().
DistanceToPoint() [2/2]
double LKParamPointRT::DistanceToPoint (TVector3 point)
Definition at line 368 of file LKParamPointRT.cpp.
References GetImagePoints().
Referenced by CorrelateBoxBand(), CorrelateBoxLine(), CorrelateBoxRibbon(), DistanceToImagePoint(), and DistanceToImagePoint().
EvalX() [1/2]
double LKParamPointRT::EvalX (double y) const inline
Definition at line 71 of file LKParamPointRT.h.
References EvalX().
Referenced by EvalX().
EvalX() [2/2]
double LKParamPointRT::EvalX (int iParamCorner, double y) const
Definition at line 320 of file LKParamPointRT.cpp.
References fXTransformCenter, fYTransformCenter, and GetCorner().
Referenced by GetImagePoints().
EvalY() [1/2]
double LKParamPointRT::EvalY (double x) const inline
Definition at line 72 of file LKParamPointRT.h.
References EvalY().
Referenced by EvalY().
EvalY() [2/2]
double LKParamPointRT::EvalY (int iParamCorner, double x) const
Definition at line 310 of file LKParamPointRT.cpp.
References fXTransformCenter, fYTransformCenter, and GetCorner().
Referenced by CorrelateBoxBand(), CorrelateBoxLine(), CorrelateBoxRibbon(), and GetImagePoints().
GetBandInImageSpace()
TGraph * LKParamPointRT::GetBandInImageSpace (double x1, double x2, double y1, double y2)
Definition at line 140 of file LKParamPointRT.cpp.
References GetImagePoints(), SetPoint(), and y2.
GetCenterR()
double LKParamPointRT::GetCenterR () const
GetCenterT()
double LKParamPointRT::GetCenterT () const
GetCorner()
TVector3 LKParamPointRT::GetCorner (int iParamCorner) const
Definition at line 49 of file LKParamPointRT.cpp.
References fRadius0, fRadius1, fRadius2, fTheta0, fTheta1, and fTheta2.
Referenced by CorrelateBoxBand(), CorrelateBoxLine(), CorrelateBoxRibbon(), EvalX(), EvalY(), GetPOCA(), and GetRangeGraphInParamSpace().
GetGeoLine()
LKGeoLine LKParamPointRT::GetGeoLine (int iParamCorner, double x1, double x2, double y1, double y2)
Definition at line 361 of file LKParamPointRT.cpp.
References GetImagePoints(), and y2.
GetGeoLineInImageSpace()
LKGeoLine LKParamPointRT::GetGeoLineInImageSpace (int iParamCorner, double x1, double x2, double y1, double y2)
Definition at line 76 of file LKParamPointRT.cpp.
References GetImagePoints(), and y2.
GetImagePoints()
void LKParamPointRT::GetImagePoints (int iParamCorner, double & x1, double & x2, double & y1, double & y2)
Evaluate two end points of straight line (x1,y1) and (x2,y2) in image space from parameter bin corner of index=iParamCorner (see Indexing iParamCorner). The position of two end points are evaluated within given x/y-ranges (x1, x2) and (y1, y2).
Definition at line 330 of file LKParamPointRT.cpp.
References EvalX(), EvalY(), fTheta0, fXTransformCenter, fYTransformCenter, and y2.
Referenced by DistanceToPoint(), DistanceToPoint(), GetBandInImageSpace(), GetGeoLine(), GetGeoLineInImageSpace(), GetLineInImageSpace(), GetRadialLineInImageSpace(), and GetRibbonInImageSpace().
GetLineInImageSpace()
TGraph * LKParamPointRT::GetLineInImageSpace (int iParamCorner, double x1, double x2, double y1, double y2)
Definition at line 83 of file LKParamPointRT.cpp.
References GetImagePoints(), SetPoint(), and y2.
GetPOCA()
TVector3 LKParamPointRT::GetPOCA (int iParamCorner)
Definition at line 302 of file LKParamPointRT.cpp.
References fXTransformCenter, fYTransformCenter, and GetCorner().
Referenced by GetRadialLineInImageSpace().
GetR0()
double LKParamPointRT::GetR0 () const inline
Definition at line 34 of file LKParamPointRT.h.
References fRadius0.
GetR1()
double LKParamPointRT::GetR1 () const inline
Definition at line 35 of file LKParamPointRT.h.
References fRadius1.
GetR2()
double LKParamPointRT::GetR2 () const inline
Definition at line 36 of file LKParamPointRT.h.
References fRadius2.
GetRadialLineInImageSpace()
TGraph * LKParamPointRT::GetRadialLineInImageSpace (int iParamCorner, double angleSize)
Definition at line 93 of file LKParamPointRT.cpp.
References fXTransformCenter, fYTransformCenter, GetImagePoints(), GetPOCA(), and SetPoint().
GetRangeGraphInParamSpace()
TGraph * LKParamPointRT::GetRangeGraphInParamSpace (bool drawYX = true)
Definition at line 287 of file LKParamPointRT.cpp.
References GetCorner(), and SetPoint().
GetRibbonInImageSpace()
TGraph * LKParamPointRT::GetRibbonInImageSpace (double x1, double x2, double y1, double y2)
Definition at line 191 of file LKParamPointRT.cpp.
References GetImagePoints(), SetPoint(), and y2.
GetT0()
double LKParamPointRT::GetT0 () const inline
Definition at line 37 of file LKParamPointRT.h.
References fTheta0.
GetT1()
double LKParamPointRT::GetT1 () const inline
Definition at line 38 of file LKParamPointRT.h.
References fTheta1.
GetT2()
double LKParamPointRT::GetT2 () const inline
Definition at line 39 of file LKParamPointRT.h.
References fTheta2.
GetWeight()
double LKParamPointRT::GetWeight () const inline
Definition at line 40 of file LKParamPointRT.h.
References fWeight.
Referenced by drawDefinition().
IsInside()
bool LKParamPointRT::IsInside (double r, double t)
Definition at line 70 of file LKParamPointRT.cpp.
Print()
void LKParamPointRT::Print (Option_t * option = "") const
Definition at line 32 of file LKParamPointRT.cpp.
References e_info, fRadius0, fRadius1, fRadius2, fTheta0, fTheta1, fTheta2, and fWeight.
SetPoint()
void LKParamPointRT::SetPoint (double xc, double yc, double r1, double t1, double r2, double t2, double w) inline
Definition at line 43 of file LKParamPointRT.h.
References fWeight, SetRadius(), SetTheta(), SetTransformCenter(), t1, and t2.
Referenced by GetBandInImageSpace(), GetLineInImageSpace(), GetRadialLineInImageSpace(), GetRangeGraphInParamSpace(), GetRibbonInImageSpace(), and LKParamPointRT().
SetRadius()
void LKParamPointRT::SetRadius (double r1, double r2) inline
Definition at line 45 of file LKParamPointRT.h.
References fRadius0, fRadius1, and fRadius2.
Referenced by SetPoint().
SetTheta()
void LKParamPointRT::SetTheta (double t1, double t2) inline
Definition at line 46 of file LKParamPointRT.h.
References fTheta0, fTheta1, fTheta2, t1, and t2.
Referenced by SetPoint().
SetTransformCenter()
void LKParamPointRT::SetTransformCenter (double xc, double yc) inline
Definition at line 44 of file LKParamPointRT.h.
References fXTransformCenter, and fYTransformCenter.
Referenced by SetPoint().
SetWeight()
void LKParamPointRT::SetWeight (double weight) inline
Definition at line 47 of file LKParamPointRT.h.
References fWeight.
Member Data Documentation
fRadius0
double LKParamPointRT::fRadius0
Definition at line 80 of file LKParamPointRT.h.
Referenced by Clear(), GetCorner(), GetR0(), Print(), and SetRadius().
fRadius1
double LKParamPointRT::fRadius1
Definition at line 81 of file LKParamPointRT.h.
Referenced by Clear(), Copy(), GetCorner(), GetR1(), Print(), and SetRadius().
fRadius2
double LKParamPointRT::fRadius2
Definition at line 82 of file LKParamPointRT.h.
Referenced by Clear(), Copy(), GetCorner(), GetR2(), Print(), and SetRadius().
fTheta0
double LKParamPointRT::fTheta0
Definition at line 83 of file LKParamPointRT.h.
Referenced by Clear(), GetCorner(), GetImagePoints(), GetT0(), Print(), and SetTheta().
fTheta1
double LKParamPointRT::fTheta1
Definition at line 84 of file LKParamPointRT.h.
Referenced by Clear(), Copy(), GetCorner(), GetT1(), Print(), and SetTheta().
fTheta2
double LKParamPointRT::fTheta2
Definition at line 85 of file LKParamPointRT.h.
Referenced by Clear(), GetCorner(), GetT2(), Print(), and SetTheta().
fWeight
double LKParamPointRT::fWeight
Definition at line 86 of file LKParamPointRT.h.
Referenced by Clear(), Copy(), GetWeight(), Print(), SetPoint(), and SetWeight().
fXTransformCenter
double LKParamPointRT::fXTransformCenter
Definition at line 78 of file LKParamPointRT.h.
Referenced by Clear(), EvalX(), EvalY(), GetImagePoints(), GetPOCA(), GetRadialLineInImageSpace(), and SetTransformCenter().
fYTransformCenter
double LKParamPointRT::fYTransformCenter
Definition at line 79 of file LKParamPointRT.h.
Referenced by Clear(), EvalX(), EvalY(), GetImagePoints(), GetPOCA(), GetRadialLineInImageSpace(), and SetTransformCenter().
The documentation for this class was generated from the following files:
LKParamPointRT.h
LKParamPointRT.cpp