LILAK: LKPad Class Reference
LKPad Class Reference
#include <LKPad.h>
Public Member Functions
void AddHit (LKHit *hit)
void AddNeighborPad (LKPad *pad)
void AddPadCorner (double i, double j)
double CalculateGroupFluctuation (int numGroups=8, int tb2=512)
virtual void Clear (Option_t *option="")
void ClearHits ()
virtual void ClearParameters ()
virtual int Compare (const TObject *obj) const
virtual void Copy (TObject &object) const
void CopyPadData (LKPad *padRef)
virtual void Draw (Option_t *option="out:hit")
in(raw), out(shaped), hit
virtual bool DrawByDefault ()
return true if to be displayed on eve.
void DrawHits ()
void FillBufferRawSig (int t, double val, int id=-1)
void FillGraph (TGraph *graph)
void FillHist (TH1D *hist)
int GetAget () const
int * GetArrayRawSig ()
double * GetArrayShaped ()
int GetAsad () const
LKBufferI GetBuffer ()
int * GetBufferArray ()
LKBufferI GetBufferRawSig ()
LKBufferD GetBufferShaped ()
int GetCAAC () const
int GetChan () const
int GetChannelID () const
int GetCobo () const
int GetDataIndex () const
int GetDecayNo () const
int GetDetType () const
double GetEnergy () const
int GetFrameNo () const
void GetGroupMeanStdDev (int numGroups, int tb2, double *pedestalGroup, double *stddevGroup)
TH1D * GetHist (Option_t *option="")
TH1D * GetHist (TString name="")
LKHit * GetHit (int idx)
LKHitArray * GetHitArray ()
TGraph * GetHitGraph ()
double GetI () const
double GetJ () const
double GetK () const
int GetLayer () const
vector< LKPad * > * GetNeighborPadArray ()
double GetNoiseScale () const
int GetNumHits () const
vector< TVector2 > * GetPadCorners ()
int GetPadID () const
double GetPedestal () const
int GetPlaneID () const
LKVector3 GetPosition () const
int GetRow () const
double GetScale (double *buffer)
double GetScale (int *buffer)
int GetSection () const
double GetSortValue ()
double GetTime () const
int * GetWaveformY ()
double GetX () const
double GetY () const
double GetZ () const
void Grab ()
bool IsActive () const
bool IsGrabed () const
virtual bool IsSortable () const
void LetGo ()
LKPad ()
virtual void Print (Option_t *option="") const
virtual void PrintParameters (TString option="") const
void PullOutHits (LKHitArray *hits)
void PullOutHits (vector< LKHit * > *hits)
LKHit * PullOutNextFreeHit ()
void SetActive (bool active=true)
void SetAget (int aget)
void SetAsad (int asad)
void SetBuffer (LKBufferI buffer)
void SetBufferRawSig (int *array)
void SetBufferRawSig (LKBufferI buffer)
void SetBufferShaped (double *array)
void SetBufferShaped (LKBufferD buffer)
void SetChan (int chan)
void SetChannelID (int value)
void SetCobo (int cobo)
void SetDataIndex (int idx)
void SetDecayNo (int id)
void SetDetType (int id)
void SetEnergy (double value)
void SetFrameNo (int id)
void SetHist (TH1D *hist, Option_t *option="out:hit")
void SetLayer (int layer)
void SetNoiseScale (double value)
void SetPad (LKPad *padRef)
void SetPadID (int value)
void SetPedestal (double value)
void SetPlaneID (int id)
void SetPosition (double i, double j)
void SetPosition (LKVector3 pos)
void SetRow (int row)
void SetSection (int section)
void SetSectionLayerRow (int section, int layer, int row)
void SetSortValue (double value)
void SetTime (double value)
void SetWaveformY (const int *array)
void SetWaveformY (const unsigned int *array)
void SetWaveformY (std::vector< unsigned int > array)
void SubtractArray (double *buffer)
void SubtractArray (double *buffer, double scale)
void SubtractArray (int *buffer)
void SubtractArray (int *buffer, double scale)
virtual ~LKPad ()
Protected Member Functions
ClassDef (GETChannel, 4)
Protected Attributes
int fAget = -1
int fAsad = -1
LKBufferI fBufferRawSig
int fChan = -1
int fChannelID = -1
int fCobo = -1
int fDecayNo = -1
int fDetType = -1
double fEnergy = -1
int fFrameNo = -1
TGraph * fGraphHit
LKHitArray fHitArray
double fNoiseScale = -1
int fPadID = -1
double fPedestal = -1
double fTime = -1
Private Attributes
bool fActive = false
LKBufferD fBufferShaped
int fDataIndex = 1
bool fGrabed = false
TH1D * fHist = nullptr
int fLayer = -1
vector< LKPad * > fNeighborPadArray
vector< TVector2 > fPadCorners
int fPlaneID = 0
LKVector3 fPosition = LKVector3(LKVector3::kZ)
int fRow = -1
int fSection = -1
double fSortValue = -1
Detailed Description
Definition at line 14 of file LKPad.h.
Constructor & Destructor Documentation
LKPad()
LKPad::LKPad () inline
Definition at line 17 of file LKPad.h.
References Clear().
~LKPad()
virtual LKPad::~LKPad () inline virtual
Definition at line 18 of file LKPad.h.
Member Function Documentation
AddHit()
void GETChannel::AddHit (LKHit * hit) inline inherited
Definition at line 52 of file GETChannel.h.
References LKHitArray::AddHit(), and GETChannel::fHitArray.
Referenced by GETChannel::PullOutHits().
AddNeighborPad()
void LKPad::AddNeighborPad (LKPad * pad) inline
Definition at line 76 of file LKPad.h.
References fNeighborPadArray.
AddPadCorner()
void LKPad::AddPadCorner (double i, double j) inline
Definition at line 80 of file LKPad.h.
References fPadCorners.
CalculateGroupFluctuation()
double GETChannel::CalculateGroupFluctuation (int numGroups = 8, int tb2 = 512) inline inherited
Definition at line 68 of file GETChannel.h.
References LKBufferI::CalculateGroupFluctuation(), and GETChannel::fBufferRawSig.
ClassDef()
GETChannel::ClassDef (GETChannel , 4) protected inherited
Clear()
virtual void LKPad::Clear (Option_t * option = "") virtual
Reimplemented from GETChannel.
Referenced by LKPad().
ClearHits()
void GETChannel::ClearHits () inline inherited
Definition at line 55 of file GETChannel.h.
References LKHitArray::Clear(), and GETChannel::fHitArray.
ClearParameters()
void GETParameters::ClearParameters () virtual inherited
Definition at line 12 of file GETParameters.cpp.
References GETParameters::fAget, GETParameters::fAsad, GETParameters::fChan, GETParameters::fCobo, GETParameters::fDecayNo, GETParameters::fDetType, and GETParameters::fFrameNo.
Referenced by GETChannel::Clear().
Compare()
int LKPad::Compare (const TObject * obj) const virtual
By default, the pads should be sorted from the outer-side of the TPC to the inner-side of the TPC. This sorting is used in LKPadPlane::PullOutNextFreeHit(). In track finding LKPadPlane::PullOutNextFreeHit() method is used and the hits are pull from first index of the pad array to the last indes of the pad array assumming that the pads are sorted this way. Here we assume that the layer numbering is given from inner-side to the outer-side of the TPC in increasing order.
Definition at line 97 of file LKPad.cpp.
References fLayer, fRow, fSection, fSortValue, GetLayer(), GetRow(), GetSection(), and GetSortValue().
Copy()
void GETChannel::Copy (TObject & object) const virtual inherited
Reimplemented from LKChannel.
Definition at line 18 of file GETChannel.cpp.
References LKChannel::Copy(), GETParameters::fAget, GETParameters::fAsad, GETChannel::fBufferRawSig, GETParameters::fChan, GETParameters::fCobo, and GETParameters::fDetType.
CopyPadData()
void LKPad::CopyPadData (LKPad * padRef)
Definition at line 157 of file LKPad.cpp.
References LKChannel::fEnergy, LKChannel::fNoiseScale, LKChannel::fPedestal, LKChannel::fTime, GetBufferRawSig(), GetBufferShaped(), LKChannel::GetEnergy(), LKChannel::GetNoiseScale(), LKChannel::GetPedestal(), LKChannel::GetTime(), IsActive(), SetActive(), SetBufferRawSig(), and SetBufferShaped().
Draw()
void LKPad::Draw (Option_t * option = "out:hit") virtual
in(raw), out(shaped), hit
Reimplemented from GETChannel.
Definition at line 47 of file LKPad.cpp.
References Draw(), DrawHits(), and GetHist().
Referenced by Draw().
DrawByDefault()
virtual bool LKContainer::DrawByDefault () inline virtual inherited
return true if to be displayed on eve.
Reimplemented in LKHit, and LKTracklet.
Definition at line 18 of file LKContainer.h.
Referenced by LKEveTask::DrawEve3D().
DrawHits()
void LKPad::DrawHits ()
Definition at line 80 of file LKPad.cpp.
Referenced by Draw().
FillBufferRawSig()
void LKPad::FillBufferRawSig (int t, double val, int id = -1) inline
Definition at line 31 of file LKPad.h.
References fActive, GETChannel::fBufferRawSig, and LKBufferI::Fill().
FillGraph()
void GETChannel::FillGraph (TGraph * graph) inherited
Definition at line 60 of file GETChannel.cpp.
References GETChannel::fBufferRawSig, and LKBufferI::FillGraph().
FillHist()
void GETChannel::FillHist (TH1D * hist) inherited
Definition at line 53 of file GETChannel.cpp.
References GETParameters::fAget, GETParameters::fAsad, GETChannel::fBufferRawSig, GETParameters::fChan, GETParameters::fCobo, and LKBufferI::FillHist().
GetAget()
int GETParameters::GetAget () const inline inherited
Definition at line 19 of file GETParameters.h.
References GETParameters::fAget.
Referenced by LTPadPlane::FillDataToHist(), LKEvePlane::FillDataToHistEventDisplay1(), and SetPad().
GetArrayRawSig()
int * LKPad::GetArrayRawSig () inline
Definition at line 37 of file LKPad.h.
References GETChannel::fBufferRawSig, and LKBufferI::GetArray().
GetArrayShaped()
double * LKPad::GetArrayShaped () inline
Definition at line 38 of file LKPad.h.
References fBufferShaped, and LKBufferD::GetArray().
GetAsad()
int GETParameters::GetAsad () const inline inherited
Definition at line 18 of file GETParameters.h.
References GETParameters::fAsad.
Referenced by LTPadPlane::FillDataToHist(), LKEvePlane::FillDataToHistEventDisplay1(), and SetPad().
GetBuffer()
LKBufferI GETChannel::GetBuffer () inline inherited
Definition at line 43 of file GETChannel.h.
References GETChannel::fBufferRawSig.
GetBufferArray()
int * GETChannel::GetBufferArray () inline inherited
Definition at line 42 of file GETChannel.h.
References GETChannel::fBufferRawSig, and LKBufferI::GetArray().
GetBufferRawSig()
LKBufferI LKPad::GetBufferRawSig () inline
Definition at line 39 of file LKPad.h.
References GETChannel::fBufferRawSig.
Referenced by CopyPadData().
GetBufferShaped()
LKBufferD LKPad::GetBufferShaped () inline
Definition at line 40 of file LKPad.h.
References fBufferShaped.
Referenced by CopyPadData().
GetCAAC()
int GETParameters::GetCAAC () const inline inherited
Definition at line 22 of file GETParameters.h.
References GETParameters::fAget, GETParameters::fAsad, GETParameters::fChan, and GETParameters::fCobo.
GetChan()
int GETParameters::GetChan () const inline inherited
Definition at line 20 of file GETParameters.h.
References GETParameters::fChan.
Referenced by LTPadPlane::FillDataToHist(), LKEvePlane::FillDataToHistEventDisplay1(), and SetPad().
GetChannelID()
int LKChannel::GetChannelID () const inline inherited
Definition at line 27 of file LKChannel.h.
References LKChannel::fChannelID.
Referenced by SetPad().
GetCobo()
int GETParameters::GetCobo () const inline inherited
Definition at line 17 of file GETParameters.h.
References GETParameters::fCobo.
Referenced by LTPadPlane::FillDataToHist(), LKEvePlane::FillDataToHistEventDisplay1(), and SetPad().
GetDataIndex()
int LKPad::GetDataIndex () const inline
Definition at line 64 of file LKPad.h.
References fDataIndex.
Referenced by SetPad().
GetDecayNo()
int GETParameters::GetDecayNo () const inline inherited
Definition at line 15 of file GETParameters.h.
References GETParameters::fDecayNo.
GetDetType()
int GETParameters::GetDetType () const inline inherited
Definition at line 16 of file GETParameters.h.
References GETParameters::fDetType.
GetEnergy()
double LKChannel::GetEnergy () const inline inherited
Definition at line 30 of file LKChannel.h.
References LKChannel::fEnergy.
Referenced by CopyPadData(), and SetPad().
GetFrameNo()
int GETParameters::GetFrameNo () const inline inherited
Definition at line 14 of file GETParameters.h.
References GETParameters::fFrameNo.
GetGroupMeanStdDev()
void GETChannel::GetGroupMeanStdDev (int numGroups, int tb2, double * pedestalGroup, double * stddevGroup) inline inherited
Definition at line 69 of file GETChannel.h.
References GETChannel::fBufferRawSig, and LKBufferI::GetGroupMeanStdDev().
GetHist() [1/2]
TH1D * LKPad::GetHist (Option_t * option = "")
Definition at line 53 of file LKPad.cpp.
References LKChannel::fChannelID, fHist, and SetHist().
Referenced by Draw().
GetHist() [2/2]
TH1D * GETChannel::GetHist (TString name = "") inherited
Definition at line 46 of file GETChannel.cpp.
References GETParameters::fAget, GETParameters::fAsad, GETChannel::fBufferRawSig, GETParameters::fChan, GETParameters::fCobo, and LKBufferI::GetHist().
Referenced by GETChannel::Draw().
GetHit()
LKHit * GETChannel::GetHit (int idx) inline inherited
Definition at line 54 of file GETChannel.h.
References GETChannel::fHitArray, and LKHitArray::GetHit().
GetHitArray()
LKHitArray * GETChannel::GetHitArray () inline inherited
Definition at line 51 of file GETChannel.h.
References GETChannel::fHitArray.
GetHitGraph()
TGraph * GETChannel::GetHitGraph () inherited
Definition at line 66 of file GETChannel.cpp.
References LKChannel::fEnergy, GETChannel::fGraphHit, LKChannel::fPedestal, LKChannel::fTime, and SetPoint().
Referenced by GETChannel::Draw().
GetI()
double LKPad::GetI () const inline
Definition at line 55 of file LKPad.h.
References fPosition, and LKVector3::I().
Referenced by LKDetectorPlane::DriftElectronBack(), LKDetectorPlane::FillDataToHist(), LKPadPlane::FillDataToHist(), LTPadPlane::FillDataToHist(), LKEvePlane::FillDataToHistEventDisplay1(), LKDetectorPlane::PadNeighborChecker(), and LKPadPlane::PadNeighborChecker().
GetJ()
double LKPad::GetJ () const inline
Definition at line 56 of file LKPad.h.
References fPosition, and LKVector3::J().
Referenced by LKDetectorPlane::DriftElectronBack(), LKDetectorPlane::FillDataToHist(), LKPadPlane::FillDataToHist(), LTPadPlane::FillDataToHist(), LKEvePlane::FillDataToHistEventDisplay1(), LKDetectorPlane::PadNeighborChecker(), and LKPadPlane::PadNeighborChecker().
GetK()
double LKPad::GetK () const inline
Definition at line 57 of file LKPad.h.
References fPosition, and LKVector3::K().
GetLayer()
int LKPad::GetLayer () const inline
Definition at line 62 of file LKPad.h.
References fLayer.
Referenced by Compare(), LKDetectorPlane::FillDataToHist(), LKPadPlane::FillDataToHist(), LTPadPlane::FillDataToHist(), LKEvePlane::FillDataToHistEventDisplay1(), LHPadPlaneFan::PullOutNeighborHitsIn(), LHPadPlaneFan::PullOutNeighborHitsIn(), and SetPad().
GetNeighborPadArray()
vector< LKPad * > * LKPad::GetNeighborPadArray () inline
Definition at line 77 of file LKPad.h.
References fNeighborPadArray.
GetNoiseScale()
double LKChannel::GetNoiseScale () const inline inherited
Definition at line 32 of file LKChannel.h.
References LKChannel::fNoiseScale.
Referenced by CopyPadData(), and SetPad().
GetNumHits()
int GETChannel::GetNumHits () const inline inherited
Definition at line 53 of file GETChannel.h.
References GETChannel::fHitArray, and LKHitArray::GetNumHits().
Referenced by LKDetectorPlane::FillDataToHist(), LKPadPlane::FillDataToHist(), LTPadPlane::FillDataToHist(), and LKEvePlane::FillDataToHistEventDisplay1().
GetPadCorners()
vector< TVector2 > * LKPad::GetPadCorners () inline
Definition at line 81 of file LKPad.h.
References fPadCorners.
Referenced by LKDetectorPlane::PadPositionChecker(), and LKPadPlane::PadPositionChecker().
GetPadID()
int LKChannel::GetPadID () const inline inherited
Definition at line 28 of file LKChannel.h.
References LKChannel::fPadID.
Referenced by LKDetectorPlane::FillDataToHist(), LKPadPlane::FillDataToHist(), LTPadPlane::FillDataToHist(), LKEvePlane::FillDataToHistEventDisplay1(), LHPadPlaneFan::MapPad(), LKDetectorPlane::PadNeighborChecker(), LKPadPlane::PadNeighborChecker(), and SetPad().
GetPedestal()
double LKChannel::GetPedestal () const inline inherited
Definition at line 31 of file LKChannel.h.
References LKChannel::fPedestal.
Referenced by CopyPadData(), and SetPad().
GetPlaneID()
int LKPad::GetPlaneID () const inline
Definition at line 53 of file LKPad.h.
References fPlaneID.
Referenced by SetPad().
GetPosition()
LKVector3 LKPad::GetPosition () const inline
Definition at line 54 of file LKPad.h.
References fPosition.
Referenced by SetPad().
GetRow()
int LKPad::GetRow () const inline
Definition at line 63 of file LKPad.h.
References fRow.
Referenced by Compare(), LKDetectorPlane::FillDataToHist(), LKPadPlane::FillDataToHist(), LTPadPlane::FillDataToHist(), LKEvePlane::FillDataToHistEventDisplay1(), and SetPad().
GetScale() [1/2]
double GETChannel::GetScale (double * buffer) inline inherited
Definition at line 67 of file GETChannel.h.
References GETChannel::fBufferRawSig, and LKBufferI::GetScale().
GetScale() [2/2]
double GETChannel::GetScale (int * buffer) inline inherited
Definition at line 66 of file GETChannel.h.
References GETChannel::fBufferRawSig, and LKBufferI::GetScale().
GetSection()
int LKPad::GetSection () const inline
Definition at line 61 of file LKPad.h.
References fSection.
Referenced by Compare(), LKDetectorPlane::FillDataToHist(), LKPadPlane::FillDataToHist(), LTPadPlane::FillDataToHist(), LKEvePlane::FillDataToHistEventDisplay1(), and SetPad().
GetSortValue()
double LKPad::GetSortValue () inline
Definition at line 65 of file LKPad.h.
References fSortValue.
Referenced by Compare().
GetTime()
double LKChannel::GetTime () const inline inherited
Definition at line 29 of file LKChannel.h.
References LKChannel::fTime.
Referenced by CopyPadData(), and SetPad().
GetWaveformY()
int * GETChannel::GetWaveformY () inline inherited
Definition at line 41 of file GETChannel.h.
References GETChannel::fBufferRawSig, and LKBufferI::GetArray().
GetX()
double LKPad::GetX () const inline
Definition at line 58 of file LKPad.h.
References fPosition.
GetY()
double LKPad::GetY () const inline
Definition at line 59 of file LKPad.h.
References fPosition.
GetZ()
double LKPad::GetZ () const inline
Definition at line 60 of file LKPad.h.
References fPosition.
Grab()
void LKPad::Grab () inline
Definition at line 85 of file LKPad.h.
References fGrabed.
IsActive()
bool LKPad::IsActive () const inline
Definition at line 69 of file LKPad.h.
References fActive.
Referenced by CopyPadData().
IsGrabed()
bool LKPad::IsGrabed () const inline
Definition at line 84 of file LKPad.h.
References fGrabed.
IsSortable()
virtual bool LKPad::IsSortable () const inline virtual
Definition at line 22 of file LKPad.h.
LetGo()
void LKPad::LetGo () inline
Definition at line 86 of file LKPad.h.
References fGrabed.
Print()
void LKPad::Print (Option_t * option = "") const virtual
Reimplemented from GETChannel.
Definition at line 35 of file LKPad.cpp.
References e_info, fActive, fBufferShaped, fGrabed, fLayer, fNeighborPadArray, fPlaneID, fPosition, fRow, fSection, LKVector3::I(), LKVector3::J(), GETChannel::Print(), and LKBufferD::Print().
PrintParameters()
void GETParameters::PrintParameters (TString option = "") const virtual inherited
Definition at line 23 of file GETParameters.cpp.
References e_info, GETParameters::fAget, GETParameters::fAsad, GETParameters::fChan, GETParameters::fCobo, and GETParameters::fDetType.
Referenced by GETChannel::Print().
PullOutHits() [1/2]
void GETChannel::PullOutHits (LKHitArray * hits) inherited
Definition at line 97 of file GETChannel.cpp.
References GETChannel::AddHit(), LKHitArray::Clear(), GETChannel::fHitArray, LKHitArray::GetHit(), and LKHitArray::GetNumHits().
PullOutHits() [2/2]
void GETChannel::PullOutHits (vector< LKHit * > * hits) inherited
Definition at line 109 of file GETChannel.cpp.
References LKHitArray::Clear(), GETChannel::fHitArray, LKHitArray::GetHit(), and LKHitArray::GetNumHits().
PullOutNextFreeHit()
LKHit * GETChannel::PullOutNextFreeHit () inherited
Definition at line 80 of file GETChannel.cpp.
References GETChannel::fHitArray, LKHitArray::GetHit(), LKHitArray::GetNumHits(), and LKHitArray::RemoveHit().
SetActive()
void LKPad::SetActive (bool active = true) inline
Definition at line 68 of file LKPad.h.
References fActive.
Referenced by CopyPadData().
SetAget()
void GETParameters::SetAget (int aget) inline inherited
Definition at line 29 of file GETParameters.h.
References GETParameters::fAget.
SetAsad()
void GETParameters::SetAsad (int asad) inline inherited
Definition at line 28 of file GETParameters.h.
References GETParameters::fAsad.
SetBuffer()
void GETChannel::SetBuffer (LKBufferI buffer) inline inherited
Definition at line 48 of file GETChannel.h.
References GETChannel::fBufferRawSig, and LKBufferI::SetBuffer().
SetBufferRawSig() [1/2]
void LKPad::SetBufferRawSig (int * array) inline
Definition at line 32 of file LKPad.h.
References GETChannel::fBufferRawSig, and LKBufferI::SetArray().
Referenced by CopyPadData().
SetBufferRawSig() [2/2]
void LKPad::SetBufferRawSig (LKBufferI buffer) inline
Definition at line 34 of file LKPad.h.
References GETChannel::fBufferRawSig, and LKBufferI::SetBuffer().
SetBufferShaped() [1/2]
void LKPad::SetBufferShaped (double * array) inline
Definition at line 33 of file LKPad.h.
References fBufferShaped, and LKBufferD::SetArray().
Referenced by CopyPadData().
SetBufferShaped() [2/2]
void LKPad::SetBufferShaped (LKBufferD buffer) inline
Definition at line 35 of file LKPad.h.
References fBufferShaped, and LKBufferD::SetBuffer().
SetChan()
void GETParameters::SetChan (int chan) inline inherited
Definition at line 30 of file GETParameters.h.
References GETParameters::fChan.
SetChannelID()
void LKChannel::SetChannelID (int value) inline inherited
Definition at line 20 of file LKChannel.h.
References LKChannel::fChannelID.
SetCobo()
void GETParameters::SetCobo (int cobo) inline inherited
Definition at line 27 of file GETParameters.h.
References GETParameters::fCobo.
SetDataIndex()
void LKPad::SetDataIndex (int idx) inline
Definition at line 50 of file LKPad.h.
References fDataIndex.
SetDecayNo()
void GETParameters::SetDecayNo (int id) inline inherited
Definition at line 25 of file GETParameters.h.
References GETParameters::fDecayNo.
SetDetType()
void GETParameters::SetDetType (int id) inline inherited
Definition at line 26 of file GETParameters.h.
References GETParameters::fDetType.
SetEnergy()
void LKChannel::SetEnergy (double value) inline inherited
Definition at line 23 of file LKChannel.h.
References LKChannel::fEnergy.
SetFrameNo()
void GETParameters::SetFrameNo (int id) inline inherited
Definition at line 24 of file GETParameters.h.
References GETParameters::fFrameNo.
SetHist()
void LKPad::SetHist (TH1D * hist, Option_t * option = "out:hit")
Definition at line 62 of file LKPad.cpp.
References GETParameters::fAget, GETParameters::fAsad, GETChannel::fBufferRawSig, fBufferShaped, GETParameters::fChan, LKChannel::fChannelID, GETParameters::fCobo, LKBufferD::FillHist(), and LKBufferI::FillHist().
Referenced by GetHist().
SetLayer()
void LKPad::SetLayer (int layer) inline
Definition at line 48 of file LKPad.h.
References fLayer.
SetNoiseScale()
void LKChannel::SetNoiseScale (double value) inline inherited
Definition at line 25 of file LKChannel.h.
References LKChannel::fNoiseScale.
SetPad()
void LKPad::SetPad (LKPad * padRef)
Definition at line 134 of file LKPad.cpp.
References GETParameters::fAget, GETParameters::fAsad, GETParameters::fChan, LKChannel::fChannelID, GETParameters::fCobo, fDataIndex, LKChannel::fEnergy, fLayer, LKChannel::fNoiseScale, LKChannel::fPadID, LKChannel::fPedestal, fPlaneID, fPosition, fRow, fSection, LKChannel::fTime, GETParameters::GetAget(), GETParameters::GetAsad(), GETParameters::GetChan(), LKChannel::GetChannelID(), GETParameters::GetCobo(), GetDataIndex(), LKChannel::GetEnergy(), GetLayer(), LKChannel::GetNoiseScale(), LKChannel::GetPadID(), LKChannel::GetPedestal(), GetPlaneID(), GetPosition(), GetRow(), GetSection(), and LKChannel::GetTime().
SetPadID()
void LKChannel::SetPadID (int value) inline inherited
Definition at line 21 of file LKChannel.h.
References LKChannel::fPadID.
SetPedestal()
void LKChannel::SetPedestal (double value) inline inherited
Definition at line 24 of file LKChannel.h.
References LKChannel::fPedestal.
SetPlaneID()
void LKPad::SetPlaneID (int id) inline
Definition at line 43 of file LKPad.h.
References fPlaneID.
SetPosition() [1/2]
void LKPad::SetPosition (double i, double j) inline
Definition at line 45 of file LKPad.h.
References fPosition, LKVector3::SetI(), and LKVector3::SetJ().
SetPosition() [2/2]
void LKPad::SetPosition (LKVector3 pos) inline
Definition at line 44 of file LKPad.h.
References fPosition.
SetRow()
void LKPad::SetRow (int row) inline
Definition at line 49 of file LKPad.h.
References fRow.
SetSection()
void LKPad::SetSection (int section) inline
Definition at line 47 of file LKPad.h.
References fSection.
SetSectionLayerRow()
void LKPad::SetSectionLayerRow (int section, int layer, int row) inline
Definition at line 46 of file LKPad.h.
References fLayer, fRow, and fSection.
SetSortValue()
void LKPad::SetSortValue (double value) inline
Definition at line 51 of file LKPad.h.
References fSortValue.
SetTime()
void LKChannel::SetTime (double value) inline inherited
Definition at line 22 of file LKChannel.h.
References LKChannel::fTime.
SetWaveformY() [1/3]
void GETChannel::SetWaveformY (const int * array) inline inherited
Definition at line 45 of file GETChannel.h.
References GETChannel::fBufferRawSig, and LKBufferI::SetArray().
SetWaveformY() [2/3]
void GETChannel::SetWaveformY (const unsigned int * array) inline inherited
Definition at line 46 of file GETChannel.h.
References GETChannel::fBufferRawSig, and LKBufferI::SetArray().
SetWaveformY() [3/3]
void GETChannel::SetWaveformY (std::vector< unsigned int > array) inline inherited
Definition at line 47 of file GETChannel.h.
References GETChannel::fBufferRawSig, and LKBufferI::SetArray().
SubtractArray() [1/4]
void GETChannel::SubtractArray (double * buffer) inline inherited
Definition at line 62 of file GETChannel.h.
References GETChannel::fBufferRawSig, and LKBufferI::SubtractArray().
SubtractArray() [2/4]
void GETChannel::SubtractArray (double * buffer, double scale) inline inherited
Definition at line 64 of file GETChannel.h.
References GETChannel::fBufferRawSig, and LKBufferI::SubtractArray().
SubtractArray() [3/4]
void GETChannel::SubtractArray (int * buffer) inline inherited
Definition at line 61 of file GETChannel.h.
References GETChannel::fBufferRawSig, and LKBufferI::SubtractArray().
SubtractArray() [4/4]
void GETChannel::SubtractArray (int * buffer, double scale) inline inherited
Definition at line 63 of file GETChannel.h.
References GETChannel::fBufferRawSig, and LKBufferI::SubtractArray().
Member Data Documentation
fActive
bool LKPad::fActive = false private
Definition at line 101 of file LKPad.h.
Referenced by ClassImp(), FillBufferRawSig(), IsActive(), Print(), and SetActive().
fAget
int GETParameters::fAget = -1 protected inherited
Definition at line 38 of file GETParameters.h.
Referenced by GETParameters::ClearParameters(), GETChannel::Copy(), GETChannel::FillHist(), GETParameters::GetAget(), GETParameters::GetCAAC(), GETChannel::GetHist(), GETParameters::PrintParameters(), GETParameters::SetAget(), SetHist(), and SetPad().
fAsad
int GETParameters::fAsad = -1 protected inherited
Definition at line 37 of file GETParameters.h.
Referenced by GETParameters::ClearParameters(), GETChannel::Copy(), GETChannel::FillHist(), GETParameters::GetAsad(), GETParameters::GetCAAC(), GETChannel::GetHist(), GETParameters::PrintParameters(), GETParameters::SetAsad(), SetHist(), and SetPad().
fBufferRawSig
LKBufferI GETChannel::fBufferRawSig protected inherited
Definition at line 72 of file GETChannel.h.
Referenced by GETChannel::CalculateGroupFluctuation(), GETChannel::Clear(), GETChannel::Copy(), FillBufferRawSig(), GETChannel::FillGraph(), GETChannel::FillHist(), GetArrayRawSig(), GETChannel::GetBuffer(), GETChannel::GetBufferArray(), GetBufferRawSig(), GETChannel::GetGroupMeanStdDev(), GETChannel::GetHist(), GETChannel::GetScale(), GETChannel::GetScale(), GETChannel::GetWaveformY(), GETChannel::Print(), GETChannel::SetBuffer(), SetBufferRawSig(), SetBufferRawSig(), SetHist(), GETChannel::SetWaveformY(), GETChannel::SetWaveformY(), GETChannel::SetWaveformY(), GETChannel::SubtractArray(), GETChannel::SubtractArray(), GETChannel::SubtractArray(), and GETChannel::SubtractArray().
fBufferShaped
LKBufferD LKPad::fBufferShaped private
Definition at line 89 of file LKPad.h.
Referenced by ClassImp(), GetArrayShaped(), GetBufferShaped(), Print(), SetBufferShaped(), SetBufferShaped(), and SetHist().
fChan
int GETParameters::fChan = -1 protected inherited
Definition at line 39 of file GETParameters.h.
Referenced by GETParameters::ClearParameters(), GETChannel::Copy(), GETChannel::FillHist(), GETParameters::GetCAAC(), GETParameters::GetChan(), GETChannel::GetHist(), GETParameters::PrintParameters(), GETParameters::SetChan(), SetHist(), and SetPad().
fChannelID
int LKChannel::fChannelID = -1 protected inherited
Definition at line 35 of file LKChannel.h.
Referenced by LKChannel::Clear(), LKChannel::Copy(), LKChannel::GetChannelID(), GetHist(), LKChannel::Print(), LKChannel::SetChannelID(), SetHist(), and SetPad().
fCobo
int GETParameters::fCobo = -1 protected inherited
Definition at line 36 of file GETParameters.h.
Referenced by GETParameters::ClearParameters(), GETChannel::Copy(), GETChannel::FillHist(), GETParameters::GetCAAC(), GETParameters::GetCobo(), GETChannel::GetHist(), GETParameters::PrintParameters(), GETParameters::SetCobo(), SetHist(), and SetPad().
fDataIndex
int LKPad::fDataIndex = 1 private
Definition at line 95 of file LKPad.h.
Referenced by ClassImp(), GetDataIndex(), SetDataIndex(), and SetPad().
fDecayNo
int GETParameters::fDecayNo = -1 protected inherited
Definition at line 34 of file GETParameters.h.
Referenced by GETParameters::ClearParameters(), GETParameters::GetDecayNo(), and GETParameters::SetDecayNo().
fDetType
int GETParameters::fDetType = -1 protected inherited
Definition at line 35 of file GETParameters.h.
Referenced by GETParameters::ClearParameters(), GETChannel::Copy(), GETParameters::GetDetType(), GETParameters::PrintParameters(), and GETParameters::SetDetType().
fEnergy
double LKChannel::fEnergy = -1 protected inherited
Definition at line 38 of file LKChannel.h.
Referenced by LKChannel::Clear(), LKChannel::Copy(), CopyPadData(), LKChannel::GetEnergy(), GETChannel::GetHitGraph(), LKChannel::Print(), LKChannel::SetEnergy(), and SetPad().
fFrameNo
int GETParameters::fFrameNo = -1 protected inherited
Definition at line 33 of file GETParameters.h.
Referenced by GETParameters::ClearParameters(), GETParameters::GetFrameNo(), and GETParameters::SetFrameNo().
fGrabed
bool LKPad::fGrabed = false private
Definition at line 102 of file LKPad.h.
Referenced by ClassImp(), Grab(), IsGrabed(), LetGo(), and Print().
fGraphHit
TGraph* GETChannel::fGraphHit protected inherited
Definition at line 75 of file GETChannel.h.
Referenced by GETChannel::GetHitGraph().
fHist
TH1D* LKPad::fHist = nullptr private
Definition at line 104 of file LKPad.h.
Referenced by GetHist().
fHitArray
LKHitArray GETChannel::fHitArray protected inherited
Definition at line 74 of file GETChannel.h.
Referenced by GETChannel::AddHit(), GETChannel::Clear(), GETChannel::ClearHits(), GETChannel::GetHit(), GETChannel::GetHitArray(), GETChannel::GetNumHits(), GETChannel::Print(), GETChannel::PullOutHits(), GETChannel::PullOutHits(), and GETChannel::PullOutNextFreeHit().
fLayer
int LKPad::fLayer = -1 private
Definition at line 93 of file LKPad.h.
Referenced by ClassImp(), Compare(), GetLayer(), Print(), SetLayer(), SetPad(), and SetSectionLayerRow().
fNeighborPadArray
vector<LKPad *> LKPad::fNeighborPadArray private
Definition at line 105 of file LKPad.h.
Referenced by AddNeighborPad(), ClassImp(), GetNeighborPadArray(), and Print().
fNoiseScale
double LKChannel::fNoiseScale = -1 protected inherited
Definition at line 40 of file LKChannel.h.
Referenced by LKChannel::Clear(), LKChannel::Copy(), CopyPadData(), LKChannel::GetNoiseScale(), LKChannel::Print(), LKChannel::SetNoiseScale(), and SetPad().
fPadCorners
vector<TVector2> LKPad::fPadCorners private
Definition at line 98 of file LKPad.h.
Referenced by AddPadCorner(), ClassImp(), and GetPadCorners().
fPadID
int LKChannel::fPadID = -1 protected inherited
Definition at line 36 of file LKChannel.h.
Referenced by LKChannel::Clear(), LKChannel::Copy(), LKChannel::GetPadID(), LKChannel::Print(), SetPad(), and LKChannel::SetPadID().
fPedestal
double LKChannel::fPedestal = -1 protected inherited
Definition at line 39 of file LKChannel.h.
Referenced by LKChannel::Clear(), LKChannel::Copy(), CopyPadData(), GETChannel::GetHitGraph(), LKChannel::GetPedestal(), LKChannel::Print(), SetPad(), and LKChannel::SetPedestal().
fPlaneID
int LKPad::fPlaneID = 0 private
Definition at line 91 of file LKPad.h.
Referenced by ClassImp(), GetPlaneID(), Print(), SetPad(), and SetPlaneID().
fPosition
LKVector3 LKPad::fPosition = LKVector3(LKVector3::kZ) private
Definition at line 97 of file LKPad.h.
Referenced by ClassImp(), GetI(), GetJ(), GetK(), GetPosition(), GetX(), GetY(), GetZ(), Print(), SetPad(), SetPosition(), and SetPosition().
fRow
int LKPad::fRow = -1 private
Definition at line 94 of file LKPad.h.
Referenced by ClassImp(), Compare(), GetRow(), Print(), SetPad(), SetRow(), and SetSectionLayerRow().
fSection
int LKPad::fSection = -1 private
Definition at line 92 of file LKPad.h.
Referenced by ClassImp(), Compare(), GetSection(), Print(), SetPad(), SetSection(), and SetSectionLayerRow().
fSortValue
double LKPad::fSortValue = -1 private
Definition at line 100 of file LKPad.h.
Referenced by ClassImp(), Compare(), GetSortValue(), and SetSortValue().
fTime
double LKChannel::fTime = -1 protected inherited
Definition at line 37 of file LKChannel.h.
Referenced by LKChannel::Clear(), LKChannel::Copy(), CopyPadData(), GETChannel::GetHitGraph(), LKChannel::GetTime(), LKChannel::Print(), SetPad(), and LKChannel::SetTime().
The documentation for this class was generated from the following files:
LKPad.h
LKPad.cpp