LILAK: LKTask Class Reference
LKTask Class Reference
#include <LKTask.h>
Public Member Functions
virtual void Add (TTask *task)
virtual bool EndOfRun ()
bool EndOfRunTask ()
bool EndOfRunTasks ()
virtual bool Init ()
bool InitTask ()
bool InitTasks ()
LKTask ()
LKTask (const char *name, const char *title)
virtual void SetRank (Int_t rank)
virtual ~LKTask ()
Public Member Functions inherited from LKGear
void AddPar (LKParameterContainer *par)
void AddPar (TString fname)
virtual void AddParameterContainer (LKParameterContainer *par)
virtual void AddParameterContainer (TString fname)
void CreateParameterContainer ()
LKParameterContainer * GetPar () const
LKParameterContainer * GetParameterContainer () const
Int_t GetRank () const
LKGear ()
void SetPar (LKParameterContainer *par)
virtual void SetParameterContainer (LKParameterContainer *par)
virtual void SetRank (Int_t rank)
void SetRun (LKRun *run)
virtual ~LKGear ()
Additional Inherited Members
Protected Attributes inherited from LKGear
LKParameterContainer * fPar = nullptr
Int_t fRank = 0
LKRun * fRun = nullptr
Detailed Description
Definition at line 13 of file LKTask.h.
Constructor & Destructor Documentation
LKTask() [1/2]
LKTask::LKTask ()
Definition at line 6 of file LKTask.cpp.
LKTask() [2/2]
LKTask::LKTask (const char * name, const char * title)
Definition at line 11 of file LKTask.cpp.
~LKTask()
virtual LKTask::~LKTask () inline virtual
Definition at line 18 of file LKTask.h.
Member Function Documentation
Add()
void LKTask::Add (TTask * task) virtual
Reimplemented in LKRun.
Definition at line 16 of file LKTask.cpp.
References LKGear::AddPar(), LKGear::fPar, LKGear::fRank, and SetRank().
Referenced by LKRun::Add(), LKEveTask::ConfigureDetectorPlanes(), and LKEveTask::DrawEve3D().
EndOfRun()
bool LKTask::EndOfRun () virtual
Reimplemented in TTHitFindingTask, TTPulseAnalysisTask, LKRun, TTBeamSelectionTask, TTDrawBeamEnergyTask, TTDrawRawWaveformTask, TTEventSelectionTask, TTFindBeamTimingTask, TTGetPedestalTask, TTPID_FSivsFCsI, TTPID_MMvsFSi, TTPID_MMvsX6, TTPID_X6vsCsI, TTReadEventListTask, TTCalibrationTask, TTHitFindingHoughTask, TTHitFindingTask, TTHoughTestTask, TTRootConversionTask, LKDriftElectronTask, LKElectronicsTask, TTPulseAnalysisTask, and TTPulseExtractionTask.
Definition at line 70 of file LKTask.cpp.
Referenced by EndOfRunTask(), and EndOfRunTasks().
EndOfRunTask()
bool LKTask::EndOfRunTask ()
Definition at line 58 of file LKTask.cpp.
References EndOfRun(), and EndOfRunTasks().
EndOfRunTasks()
bool LKTask::EndOfRunTasks ()
Definition at line 75 of file LKTask.cpp.
References EndOfRun(), lk_info, and lk_warning.
Referenced by LKRun::EndOfRun(), and EndOfRunTask().
Init()
bool LKTask::Init () virtual
Reimplemented in LHElectronicsTask, LHHelixTrackFindingTask, LHVertexFindingTask, TTHitFindingTask, TTPulseAnalysisTask, LKEveTask, LKRun, LHPSATask, TTBeamSelectionTask, TTDrawBeamEnergyTask, TTDrawRawWaveformTask, TTEventSelectionTask, TTFindBeamTimingTask, TTGetPedestalTask, TTPID_FSivsFCsI, TTPID_MMvsFSi, TTPID_MMvsX6, TTPID_X6vsCsI, TTReadEventListTask, TTCalibrationTask, TTHitFindingHoughTask, TTHitFindingTask, TTHoughTestTask, TTRootConversionTask, LKDriftElectronTask, LKElectronicsTask, TTPulseAnalysisTask, and TTPulseExtractionTask.
Definition at line 37 of file LKTask.cpp.
Referenced by InitTask(), and InitTasks().
InitTask()
bool LKTask::InitTask ()
Definition at line 25 of file LKTask.cpp.
References Init(), and InitTasks().
InitTasks()
bool LKTask::InitTasks ()
Definition at line 42 of file LKTask.cpp.
References Init(), lk_info, and lk_warning.
Referenced by LKRun::Init(), and InitTask().
SetRank()
void LKTask::SetRank (Int_t rank) virtual
Reimplemented from LKGear.
Definition at line 91 of file LKTask.cpp.
References LKGear::fRank, and SetRank().
Referenced by Add(), and SetRank().
The documentation for this class was generated from the following files:
LKTask.h
LKTask.cpp