lilak: LKPainter Class Reference
LKPainter Class Reference
#include <LKPainter.h>
Public Member Functions
TCanvas * Canvas (TString name="cvs_lilak", Int_t mode=0, double value1=1, double value2=-1, double value3=-1)
TCanvas * CanvasDefault (TString name="cvs_lilak", double ratio=1)
TCanvas * CanvasFull (TString name="cvs_lilak", double ratio=1, double ratio2=-1)
TCanvas * CanvasResize (TString name, Int_t width0, int height0, double ratio=-1)
TCanvas * CanvasSquare (TString name="cvs_lilak", double ratio=1)
void Clear (Option_t *option="")
TString ConfigureName (TString name)
void FixCanvasPosition ()
UInt_t GetHCurrentDisplay () const
UInt_t GetWCurrentDisplay () const
int GetXCurrentDisplay () const
int GetYCurrentDisplay () const
bool Init ()
LKPainter ()
TCanvas * NewCanvas (TString name, TString title, int x, int y, int width, int height)
void Print (Option_t *option="") const
void SetDeadFrame (UInt_t left, UInt_t right, UInt_t bottom, UInt_t top)
void SetDeadFrameBottom (UInt_t val)
void SetDeadFrameLeft (UInt_t val)
void SetDeadFrameRight (UInt_t val)
void SetDeadFrameTop (UInt_t val)
void SetHCanvas (UInt_t hCanvas)
void SetHSpacing (UInt_t dhCanvas)
double SetRatio (double ratio, double defaultValue=1)
void SetWCanvas (UInt_t wCanvas)
void SetWSpacing (UInt_t dwCanvas)
void UpdateNextCanvasPosition ()
virtual ~LKPainter ()
Static Public Member Functions
static LKPainter * GetPainter ()
Public Attributes
const int kDefault = 0
const int kFull = 1
const int kResize = 3
const int kSquare = 2
Private Member Functions
ClassDef (LKPainter, 1)
void ConfigureDisplay ()
Private Attributes
int fCountCanvases = 0
default height of canvas assuming that width of the display is 1250
UInt_t fDeadFrameSize [4] = {25,25,80,50}
Bool_t fFixCanvasPosition = true
UInt_t fHCurrentDisplay = 0
width of current display
int fHDefault = fHDefaultOrigin
default width of canvas
int fHDefaultOrigin = 500
default width of canvas assuming that width of the display is 1250
int fHSpacing = 25
default width spacing of canvas
double fResizeFactor = 1
default height spacing of canvas
UInt_t fWCurrentDisplay = 0
int fWDefault = fWDefaultOrigin
int fWDefaultOrigin = 700
height position of next canvas
int fWSpacing = 25
default height of canvas
int fXCurrentCanvas = 0
relative height position of current display from main display
int fXCurrentDisplay = -1
height of current display
int fYCurrentCanvas = 0
width position of next canvas
int fYCurrentDisplay = -1
relative width position of current display from main display
Static Private Attributes
static LKPainter * fInstance = nullptr
Detailed Description
Definition at line 15 of file LKPainter.h.
Constructor & Destructor Documentation
LKPainter()
LKPainter::LKPainter ()
Definition at line 18 of file LKPainter.cpp.
References Init().
Referenced by GetPainter().
~LKPainter()
virtual LKPainter::~LKPainter () inline virtual
Definition at line 19 of file LKPainter.h.
Member Function Documentation
Canvas()
TCanvas * LKPainter::Canvas (TString name = "cvs_lilak", Int_t mode = 0, double value1 = 1, double value2 = -1, double value3 = -1)
mode = 0 (kDefault) : default canvas with fWDefault x fHDefault (600 x 450). mode = 1 (kFull) : full size canvas that fits in the current display. mode = 2 (kSquare) : square canvas. mode = 3 (kResize) : resize canvas from given w,h = (value1, value2) to show similar scale in the current display.
Definition at line 105 of file LKPainter.cpp.
References CanvasDefault(), CanvasFull(), CanvasResize(), CanvasSquare(), kDefault, kFull, and kResize.
CanvasDefault()
TCanvas * LKPainter::CanvasDefault (TString name = "cvs_lilak", double ratio = 1)
Definition at line 151 of file LKPainter.cpp.
References cvs, fHDefault, fWDefault, fXCurrentCanvas, fYCurrentCanvas, NewCanvas(), SetRatio(), and UpdateNextCanvasPosition().
Referenced by Canvas().
CanvasFull()
TCanvas * LKPainter::CanvasFull (TString name = "cvs_lilak", double ratio = 1, double ratio2 = -1)
Definition at line 161 of file LKPainter.cpp.
References cvs, fHCurrentDisplay, fWCurrentDisplay, fXCurrentCanvas, fYCurrentCanvas, NewCanvas(), SetRatio(), and UpdateNextCanvasPosition().
Referenced by Canvas().
CanvasResize()
TCanvas * LKPainter::CanvasResize (TString name, Int_t width0, int height0, double ratio = -1)
Definition at line 186 of file LKPainter.cpp.
References cvs, fHCurrentDisplay, fResizeFactor, fWCurrentDisplay, fXCurrentCanvas, fYCurrentCanvas, NewCanvas(), SetRatio(), and UpdateNextCanvasPosition().
Referenced by Canvas().
CanvasSquare()
TCanvas * LKPainter::CanvasSquare (TString name = "cvs_lilak", double ratio = 1)
Definition at line 174 of file LKPainter.cpp.
References cvs, fHCurrentDisplay, fWCurrentDisplay, fXCurrentCanvas, fYCurrentCanvas, NewCanvas(), SetRatio(), and UpdateNextCanvasPosition().
Referenced by Canvas().
ClassDef()
LKPainter::ClassDef (LKPainter , 1) private
Clear()
void LKPainter::Clear (Option_t * option = "")
Definition at line 33 of file LKPainter.cpp.
References fDeadFrameSize, fHCurrentDisplay, fHDefault, fHSpacing, fWCurrentDisplay, fWDefault, fWSpacing, fXCurrentCanvas, fXCurrentDisplay, fYCurrentCanvas, and fYCurrentDisplay.
ConfigureDisplay()
void LKPainter::ConfigureDisplay () private
Definition at line 70 of file LKPainter.cpp.
References e_info, fDeadFrameSize, fHCurrentDisplay, fHDefault, fHDefaultOrigin, fResizeFactor, fWCurrentDisplay, fWDefault, fWDefaultOrigin, fXCurrentCanvas, fXCurrentDisplay, fYCurrentCanvas, and fYCurrentDisplay.
Referenced by Init().
ConfigureName()
TString LKPainter::ConfigureName (TString name)
Definition at line 133 of file LKPainter.cpp.
References fCountCanvases.
Referenced by NewCanvas().
FixCanvasPosition()
void LKPainter::FixCanvasPosition () inline
Definition at line 48 of file LKPainter.h.
References fFixCanvasPosition.
GetHCurrentDisplay()
UInt_t LKPainter::GetHCurrentDisplay () const inline
Definition at line 29 of file LKPainter.h.
References fHCurrentDisplay.
GetPainter()
LKPainter * LKPainter::GetPainter () static
Definition at line 12 of file LKPainter.cpp.
References fInstance, and LKPainter().
Referenced by LKHTLineTracker::Draw(), LKEveTask::DrawEve3D(), LKDetectorPlane::GetCanvas(), LKEvePlane::GetCanvas(), SKSiArrayPlane::GetCanvas(), LKGETChannelViewer::Init(), LKDataViewer::InitCanvas(), and SKDrawTodayTask::InitCanvas().
GetWCurrentDisplay()
UInt_t LKPainter::GetWCurrentDisplay () const inline
Definition at line 28 of file LKPainter.h.
References fWCurrentDisplay.
GetXCurrentDisplay()
int LKPainter::GetXCurrentDisplay () const inline
Definition at line 26 of file LKPainter.h.
References fXCurrentDisplay.
GetYCurrentDisplay()
int LKPainter::GetYCurrentDisplay () const inline
Definition at line 27 of file LKPainter.h.
References fYCurrentDisplay.
Init()
bool LKPainter::Init ()
Definition at line 23 of file LKPainter.cpp.
References ConfigureDisplay(), and e_info.
Referenced by LKPainter().
NewCanvas()
TCanvas * LKPainter::NewCanvas (TString name, TString title, int x, int y, int width, int height)
Definition at line 141 of file LKPainter.cpp.
References ConfigureName(), cvs, fCountCanvases, fXCurrentCanvas, and fYCurrentCanvas.
Referenced by CanvasDefault(), CanvasFull(), CanvasResize(), and CanvasSquare().
Print()
void LKPainter::Print (Option_t * option = "") const
Definition at line 52 of file LKPainter.cpp.
References e_info, fDeadFrameSize, fHCurrentDisplay, fHDefault, fHSpacing, fWCurrentDisplay, fWDefault, fWSpacing, fXCurrentCanvas, fXCurrentDisplay, fYCurrentCanvas, and fYCurrentDisplay.
SetDeadFrame()
void LKPainter::SetDeadFrame (UInt_t left, UInt_t right, UInt_t bottom, UInt_t top) inline
Definition at line 35 of file LKPainter.h.
References SetDeadFrameBottom(), SetDeadFrameLeft(), SetDeadFrameRight(), and SetDeadFrameTop().
SetDeadFrameBottom()
void LKPainter::SetDeadFrameBottom (UInt_t val)
Definition at line 94 of file LKPainter.cpp.
References fDeadFrameSize, and fWCurrentDisplay.
Referenced by SetDeadFrame().
SetDeadFrameLeft()
void LKPainter::SetDeadFrameLeft (UInt_t val)
Definition at line 84 of file LKPainter.cpp.
References fDeadFrameSize, and fWCurrentDisplay.
Referenced by SetDeadFrame().
SetDeadFrameRight()
void LKPainter::SetDeadFrameRight (UInt_t val)
Definition at line 89 of file LKPainter.cpp.
References fDeadFrameSize, and fWCurrentDisplay.
Referenced by SetDeadFrame().
SetDeadFrameTop()
void LKPainter::SetDeadFrameTop (UInt_t val)
Definition at line 99 of file LKPainter.cpp.
References fDeadFrameSize, and fWCurrentDisplay.
Referenced by SetDeadFrame().
SetHCanvas()
void LKPainter::SetHCanvas (UInt_t hCanvas) inline
Definition at line 42 of file LKPainter.h.
References fHDefault, fHDefaultOrigin, and fResizeFactor.
SetHSpacing()
void LKPainter::SetHSpacing (UInt_t dhCanvas) inline
Definition at line 44 of file LKPainter.h.
References fHSpacing.
SetRatio()
double LKPainter::SetRatio (double ratio, double defaultValue = 1)
Definition at line 123 of file LKPainter.cpp.
References e_warning.
Referenced by CanvasDefault(), CanvasFull(), CanvasResize(), and CanvasSquare().
SetWCanvas()
void LKPainter::SetWCanvas (UInt_t wCanvas) inline
Definition at line 41 of file LKPainter.h.
References fResizeFactor, fWDefault, and fWDefaultOrigin.
SetWSpacing()
void LKPainter::SetWSpacing (UInt_t dwCanvas) inline
Definition at line 43 of file LKPainter.h.
References fWSpacing.
UpdateNextCanvasPosition()
void LKPainter::UpdateNextCanvasPosition ()
Definition at line 115 of file LKPainter.cpp.
References fFixCanvasPosition, fHSpacing, fWSpacing, fXCurrentCanvas, and fYCurrentCanvas.
Referenced by CanvasDefault(), CanvasFull(), CanvasResize(), and CanvasSquare().
Member Data Documentation
fCountCanvases
int LKPainter::fCountCanvases = 0 private
default height of canvas assuming that width of the display is 1250
Definition at line 85 of file LKPainter.h.
Referenced by ConfigureName(), and NewCanvas().
fDeadFrameSize
UInt_t LKPainter::fDeadFrameSize[4] = {25,25,80,50} private
Definition at line 76 of file LKPainter.h.
Referenced by Clear(), ConfigureDisplay(), Print(), SetDeadFrameBottom(), SetDeadFrameLeft(), SetDeadFrameRight(), and SetDeadFrameTop().
fFixCanvasPosition
Bool_t LKPainter::fFixCanvasPosition = true private
Definition at line 75 of file LKPainter.h.
Referenced by FixCanvasPosition(), and UpdateNextCanvasPosition().
fHCurrentDisplay
UInt_t LKPainter::fHCurrentDisplay = 0 private
width of current display
Definition at line 78 of file LKPainter.h.
Referenced by CanvasFull(), CanvasResize(), CanvasSquare(), Clear(), ConfigureDisplay(), GetHCurrentDisplay(), and Print().
fHDefault
int LKPainter::fHDefault = fHDefaultOrigin private
default width of canvas
Definition at line 87 of file LKPainter.h.
Referenced by CanvasDefault(), Clear(), ConfigureDisplay(), Print(), and SetHCanvas().
fHDefaultOrigin
int LKPainter::fHDefaultOrigin = 500 private
default width of canvas assuming that width of the display is 1250
Definition at line 84 of file LKPainter.h.
Referenced by ConfigureDisplay(), and SetHCanvas().
fHSpacing
int LKPainter::fHSpacing = 25 private
default width spacing of canvas
Definition at line 89 of file LKPainter.h.
Referenced by Clear(), Print(), SetHSpacing(), and UpdateNextCanvasPosition().
fInstance
LKPainter * LKPainter::fInstance = nullptr static private
Definition at line 73 of file LKPainter.h.
Referenced by GetPainter().
fResizeFactor
double LKPainter::fResizeFactor = 1 private
default height spacing of canvas
Definition at line 90 of file LKPainter.h.
Referenced by CanvasResize(), ConfigureDisplay(), SetHCanvas(), and SetWCanvas().
fWCurrentDisplay
UInt_t LKPainter::fWCurrentDisplay = 0 private
Definition at line 77 of file LKPainter.h.
Referenced by CanvasFull(), CanvasResize(), CanvasSquare(), Clear(), ConfigureDisplay(), GetWCurrentDisplay(), Print(), SetDeadFrameBottom(), SetDeadFrameLeft(), SetDeadFrameRight(), and SetDeadFrameTop().
fWDefault
int LKPainter::fWDefault = fWDefaultOrigin private
Definition at line 86 of file LKPainter.h.
Referenced by CanvasDefault(), Clear(), ConfigureDisplay(), Print(), and SetWCanvas().
fWDefaultOrigin
int LKPainter::fWDefaultOrigin = 700 private
height position of next canvas
Definition at line 83 of file LKPainter.h.
Referenced by ConfigureDisplay(), and SetWCanvas().
fWSpacing
int LKPainter::fWSpacing = 25 private
default height of canvas
Definition at line 88 of file LKPainter.h.
Referenced by Clear(), Print(), SetWSpacing(), and UpdateNextCanvasPosition().
fXCurrentCanvas
int LKPainter::fXCurrentCanvas = 0 private
relative height position of current display from main display
Definition at line 81 of file LKPainter.h.
Referenced by CanvasDefault(), CanvasFull(), CanvasResize(), CanvasSquare(), Clear(), ConfigureDisplay(), NewCanvas(), Print(), and UpdateNextCanvasPosition().
fXCurrentDisplay
int LKPainter::fXCurrentDisplay = -1 private
height of current display
Definition at line 79 of file LKPainter.h.
Referenced by Clear(), ConfigureDisplay(), GetXCurrentDisplay(), and Print().
fYCurrentCanvas
int LKPainter::fYCurrentCanvas = 0 private
width position of next canvas
Definition at line 82 of file LKPainter.h.
Referenced by CanvasDefault(), CanvasFull(), CanvasResize(), CanvasSquare(), Clear(), ConfigureDisplay(), NewCanvas(), Print(), and UpdateNextCanvasPosition().
fYCurrentDisplay
int LKPainter::fYCurrentDisplay = -1 private
relative width position of current display from main display
Definition at line 80 of file LKPainter.h.
Referenced by Clear(), ConfigureDisplay(), GetYCurrentDisplay(), and Print().
kDefault
const int LKPainter::kDefault = 0
Definition at line 64 of file LKPainter.h.
Referenced by Canvas().
kFull
const int LKPainter::kFull = 1
Definition at line 65 of file LKPainter.h.
Referenced by Canvas().
kResize
const int LKPainter::kResize = 3
Definition at line 67 of file LKPainter.h.
Referenced by Canvas().
kSquare
const int LKPainter::kSquare = 2
Definition at line 66 of file LKPainter.h.
The documentation for this class was generated from the following files:
LKPainter.h
LKPainter.cpp