lilak: LKNoiseAnalyzer Class Reference
LKNoiseAnalyzer Class Reference
#include <LKNoiseAnalyzer.h>
Public Member Functions
void Add (GETChannel *channel)
void AddFPNData (GETChannel *channel)
bool Analyze ()
void Clear (Option_t *option="")
int FindRefChannelID ()
double * GetFPNData ()
bool Init ()
LKNoiseAnalyzer ()
bool TestValidity ()
virtual ~LKNoiseAnalyzer ()
Private Member Functions
ClassDef (LKNoiseAnalyzer, 1)
Private Attributes
TObjArray * fChannelArray = nullptr
GETChannel * fChannelRef = nullptr
double fFluctuationThreshold = 100
double fFPNData [512]
int fNumFPNData = 0
bool fUseFPNData = true
Detailed Description
Definition at line 9 of file LKNoiseAnalyzer.h.
Constructor & Destructor Documentation
LKNoiseAnalyzer()
LKNoiseAnalyzer::LKNoiseAnalyzer () inline
Definition at line 12 of file LKNoiseAnalyzer.h.
~LKNoiseAnalyzer()
virtual LKNoiseAnalyzer::~LKNoiseAnalyzer () inline virtual
Definition at line 13 of file LKNoiseAnalyzer.h.
Member Function Documentation
Add()
void LKNoiseAnalyzer::Add (GETChannel * channel)
Definition at line 25 of file LKNoiseAnalyzer.cpp.
References Add(), and fChannelArray.
Referenced by Add().
AddFPNData()
void LKNoiseAnalyzer::AddFPNData (GETChannel * channel)
Definition at line 30 of file LKNoiseAnalyzer.cpp.
References fFPNData, and fNumFPNData.
Analyze()
bool LKNoiseAnalyzer::Analyze ()
Definition at line 60 of file LKNoiseAnalyzer.cpp.
References fChannelArray, fChannelRef, FindRefChannelID(), and iChannel.
ClassDef()
LKNoiseAnalyzer::ClassDef (LKNoiseAnalyzer , 1) private
Clear()
void LKNoiseAnalyzer::Clear (Option_t * option = "")
Definition at line 17 of file LKNoiseAnalyzer.cpp.
References Clear(), fChannelArray, fChannelRef, fFPNData, and fNumFPNData.
Referenced by Clear().
FindRefChannelID()
int LKNoiseAnalyzer::FindRefChannelID ()
Definition at line 38 of file LKNoiseAnalyzer.cpp.
References fChannelArray, fFPNData, fNumFPNData, fUseFPNData, and iChannel.
Referenced by Analyze(), and TestValidity().
GetFPNData()
double * LKNoiseAnalyzer::GetFPNData () inline
Definition at line 18 of file LKNoiseAnalyzer.h.
References fFPNData.
Init()
bool LKNoiseAnalyzer::Init ()
TestValidity()
bool LKNoiseAnalyzer::TestValidity () inline
Definition at line 24 of file LKNoiseAnalyzer.h.
References FindRefChannelID().
Member Data Documentation
fChannelArray
TObjArray* LKNoiseAnalyzer::fChannelArray = nullptr private
Definition at line 28 of file LKNoiseAnalyzer.h.
Referenced by Add(), Analyze(), Clear(), and FindRefChannelID().
fChannelRef
GETChannel* LKNoiseAnalyzer::fChannelRef = nullptr private
Definition at line 35 of file LKNoiseAnalyzer.h.
Referenced by Analyze(), and Clear().
fFluctuationThreshold
double LKNoiseAnalyzer::fFluctuationThreshold = 100 private
Definition at line 33 of file LKNoiseAnalyzer.h.
fFPNData
double LKNoiseAnalyzer::fFPNData[512] private
Definition at line 31 of file LKNoiseAnalyzer.h.
Referenced by AddFPNData(), Clear(), FindRefChannelID(), and GetFPNData().
fNumFPNData
int LKNoiseAnalyzer::fNumFPNData = 0 private
Definition at line 32 of file LKNoiseAnalyzer.h.
Referenced by AddFPNData(), Clear(), and FindRefChannelID().
fUseFPNData
bool LKNoiseAnalyzer::fUseFPNData = true private
Definition at line 30 of file LKNoiseAnalyzer.h.
Referenced by FindRefChannelID().
The documentation for this class was generated from the following files:
LKNoiseAnalyzer.h
LKNoiseAnalyzer.cpp