lilak: LHHelixTrackFindingTask Class Reference
LHHelixTrackFindingTask Class Reference
#include <LHHelixTrackFindingTask.h>
Public Types
enum StepNo : int {
kStepInitArray , kStepNewTrack , kStepRemoveTrack , kStepInitTrack ,
kStepInitTrackAddHit , kStepContinuum , kStepContinuumAddHit , kStepExtrapolation ,
kStepExtrapolationAddHit , kStepConfirmation , kStepFinalizeTrack , kStepNextPhase ,
kStepEndEvent , kStepEndOfEvent
}
Public Member Functions
virtual void Exec (Option_t *)
bool ExecStep ()
bool ExecStepUptoTrackNum (Int_t numTracks)
LKHelixTrack * GetCurrentTrack () const
virtual bool Init ()
LHHelixTrackFindingTask ()
void SetHitBranchName (TString name)
void SetTrackletBranchName (TString name)
void SetTrackPersistency (bool val)
virtual ~LHHelixTrackFindingTask ()
Public Member Functions inherited from LKTask
virtual void Add (TTask *task)
virtual void Add (TTask *task)
virtual void AddTriggerInputFile (TString fileName, TString opt)
virtual void AddTriggerInputFile (TString fileName, TString opt)
virtual bool EndOfRun ()
virtual bool EndOfRun ()
bool EndOfRunTask ()
bool EndOfRunTask ()
bool EndOfRunTasks ()
bool EndOfRunTasks ()
virtual bool Init ()
virtual bool Init ()
bool InitTask ()
bool InitTask ()
bool InitTasks ()
bool InitTasks ()
virtual bool IsEventTrigger ()
virtual bool IsEventTrigger ()
LKTask ()
LKTask ()
LKTask (const char *name, const char *title)
LKTask (const char *name, const char *title)
virtual void Run (Long64_t numEvents=-1)
virtual void Run (Long64_t numEvents=-1)
virtual void RunOnline ()
virtual void RunOnline ()
virtual void SetRank (Int_t rank)
virtual void SetRank (Int_t rank)
virtual void SignalNextEvent ()
virtual void SignalNextEvent ()
virtual ~LKTask ()
virtual ~LKTask ()
Public Member Functions inherited from LKGear
void AddPar (LKParameterContainer *par)
void AddPar (TString fname)
virtual void AddParameterContainer (LKParameterContainer *par)
virtual void AddParameterContainer (TString fname)
void CreateParameterContainer ()
LKParameterContainer * GetPar () const
LKParameterContainer * GetParameterContainer () const
Int_t GetRank () const
LKGear ()
void SetAllowControlLogger (bool val)
void SetPar (LKParameterContainer *par)
virtual void SetParameterContainer (LKParameterContainer *par)
virtual void SetRank (Int_t rank)
void SetRun (LKRun *run)
virtual ~LKGear ()
Private Member Functions
bool AutoBuildAtPosition (LKHelixTrack *track, TVector3 p, bool &tailToHead, Double_t &extrapolationLength, Double_t scale=1)
bool AutoBuildByExtrapolation (LKHelixTrack *track, bool &buildHead, Double_t &extrapolationLength)
bool BuildAndConfirmTrack (LKHelixTrack *track, bool &tailToHead)
bool CheckHitDistInAlphaIsLargerThanQuarterPi (LKHelixTrack *track, Double_t dLength)
int CheckParentTrackID (LKHit *hit)
double CheckTrackContinuity (LKHelixTrack *track)
bool CheckTrackQuality (LKHelixTrack *track)
double CorrelateHitWithTrack (LKHelixTrack *track, LKHit *hit, Double_t scale=1)
double CorrelateHitWithTrackCandidate (LKHelixTrack *track, LKHit *hit)
void ReturnBadHitsToPadPlane ()
int StepConfirmation ()
int StepContinuum ()
int StepContinuumAddHit ()
int StepEndEvent ()
int StepExtrapolation ()
int StepExtrapolationAddHit ()
int StepFinalizeTrack ()
int StepInitArray ()
int StepInitTrack ()
int StepInitTrackAddHit ()
int StepNewTrack ()
int StepNextPhase ()
int StepRemoveTrack ()
Private Attributes
LKHitArray * fBadHits = nullptr
TString fBranchNameHit = "Hit"
TString fBranchNameTracklet = "Tracklet"
LKHitArray * fCandHits = nullptr
LKHelixTrack * fCurrentTrack = nullptr
Double_t fCutdkInExpectedTrackPath = 4.
Int_t fCutMaxNumHitsInitTrack = 15
return hits if track has more than this number of hits within initialization stage
Double_t fCutMinHelixRadius = 30.
helix radius cut for initialization stage
Int_t fCutMinNumHitsFinalTrack = 15
remove track if track has smaller than this number of hits within initialization stage
Int_t fCutMinNumHitsInitTrack = 10
TCanvas * fCvsCurrentTrack = nullptr
Double_t fDefaultScale
LKHitArray * fGoodHits = nullptr
TGraphErrors * fGraphCurrentTrackPoint = nullptr
TClonesArray * fHitArray = nullptr
Int_t fMinHitsToFitInitTrack = 7
try track fit if track has more than this number of hits in track
Int_t fNextStep = StepNo::kStepInitArray
Int_t fNumBadHits
Int_t fNumCandHits
Int_t fNumGoodHits
LKDetectorPlane * fPadPlane = nullptr
bool fPersistency = true
Int_t fPhaseIndex = 0
LKVector3::Axis fReferenceAxis
LHTpc * fTpc = nullptr
TClonesArray * fTrackArray = nullptr
Double_t fTrackHCutHL
Track height cut high limit.
Double_t fTrackHCutLL
Track height cut low limit.
LKHitArray * fTrackHits = nullptr
Double_t fTrackLengthCutScale = 2.5
track length cut for initialization stage is [this_var] * track -> GetRMSR()
Double_t fTrackWCutHL
Track width cut high limit.
Double_t fTrackWCutLL
Track width cut low limit.
Additional Inherited Members
Protected Attributes inherited from LKTask
vector< TString > fTriggerInputFileNameArray
for event trigger task
Protected Attributes inherited from LKGear
bool fAllowControlLogger = true
LKParameterContainer * fPar = nullptr
Int_t fRank = 0
LKRun * fRun = nullptr
Detailed Description
Definition at line 18 of file LHHelixTrackFindingTask.h.
Member Enumeration Documentation
StepNo
enum LHHelixTrackFindingTask::StepNo : int
Enumerator
kStepInitArray
kStepNewTrack
kStepRemoveTrack
kStepInitTrack
kStepInitTrackAddHit
kStepContinuum
kStepContinuumAddHit
kStepExtrapolation
kStepExtrapolationAddHit
kStepConfirmation
kStepFinalizeTrack
kStepNextPhase
kStepEndEvent
kStepEndOfEvent
Definition at line 29 of file LHHelixTrackFindingTask.h.
Constructor & Destructor Documentation
LHHelixTrackFindingTask()
LHHelixTrackFindingTask::LHHelixTrackFindingTask () inline
Definition at line 21 of file LHHelixTrackFindingTask.h.
~LHHelixTrackFindingTask()
virtual LHHelixTrackFindingTask::~LHHelixTrackFindingTask () inline virtual
Definition at line 22 of file LHHelixTrackFindingTask.h.
Member Function Documentation
AutoBuildAtPosition()
bool LHHelixTrackFindingTask::AutoBuildAtPosition (LKHelixTrack * track, TVector3 p, bool & tailToHead, Double_t & extrapolationLength, Double_t scale = 1) private
Definition at line 779 of file LHHelixTrackFindingTask.cpp.
References CheckParentTrackID(), CorrelateHitWithTrack(), fBadHits, fCandHits, fNumCandHits, fPadPlane, fReferenceAxis, and p2.
Referenced by AutoBuildByExtrapolation().
AutoBuildByExtrapolation()
bool LHHelixTrackFindingTask::AutoBuildByExtrapolation (LKHelixTrack * track, bool & buildHead, Double_t & extrapolationLength) private
Definition at line 764 of file LHHelixTrackFindingTask.cpp.
References AutoBuildAtPosition(), and fCutMinNumHitsFinalTrack.
Referenced by BuildAndConfirmTrack(), and StepExtrapolationAddHit().
BuildAndConfirmTrack()
bool LHHelixTrackFindingTask::BuildAndConfirmTrack (LKHelixTrack * track, bool & tailToHead) private
Definition at line 715 of file LHHelixTrackFindingTask.cpp.
References AutoBuildByExtrapolation(), CorrelateHitWithTrack(), fCutMinNumHitsFinalTrack, and lk_debug.
Referenced by StepConfirmation().
CheckHitDistInAlphaIsLargerThanQuarterPi()
bool LHHelixTrackFindingTask::CheckHitDistInAlphaIsLargerThanQuarterPi (LKHelixTrack * track, Double_t dLength) private
Definition at line 915 of file LHHelixTrackFindingTask.cpp.
Referenced by CorrelateHitWithTrack().
CheckParentTrackID()
int LHHelixTrackFindingTask::CheckParentTrackID (LKHit * hit) private
Definition at line 834 of file LHHelixTrackFindingTask.cpp.
Referenced by AutoBuildAtPosition(), and StepContinuumAddHit().
CheckTrackContinuity()
double LHHelixTrackFindingTask::CheckTrackContinuity (LKHelixTrack * track) private
Definition at line 868 of file LHHelixTrackFindingTask.cpp.
References LKVector3::At(), fPadPlane, and fReferenceAxis.
CheckTrackQuality()
bool LHHelixTrackFindingTask::CheckTrackQuality (LKHelixTrack * track) private
Definition at line 852 of file LHHelixTrackFindingTask.cpp.
References fCutMinHelixRadius.
Referenced by StepExtrapolationAddHit().
CorrelateHitWithTrack()
double LHHelixTrackFindingTask::CorrelateHitWithTrack (LKHelixTrack * track, LKHit * hit, Double_t scale = 1) private
Definition at line 655 of file LHHelixTrackFindingTask.cpp.
References CheckHitDistInAlphaIsLargerThanQuarterPi(), fDefaultScale, fTrackHCutHL, fTrackHCutLL, fTrackWCutHL, and fTrackWCutLL.
Referenced by AutoBuildAtPosition(), BuildAndConfirmTrack(), StepContinuumAddHit(), and StepInitTrackAddHit().
CorrelateHitWithTrackCandidate()
double LHHelixTrackFindingTask::CorrelateHitWithTrackCandidate (LKHelixTrack * track, LKHit * hit) private
Definition at line 545 of file LHHelixTrackFindingTask.cpp.
References fCurrentTrack, fCutdkInExpectedTrackPath, fReferenceAxis, fTrackHCutHL, fTrackHCutLL, LKVector3::I(), LKVector3::J(), LKVector3::K(), lk_debug, and LKVector3::SetK().
Referenced by StepInitTrackAddHit().
Exec()
void LHHelixTrackFindingTask::Exec (Option_t *) virtual
Definition at line 43 of file LHHelixTrackFindingTask.cpp.
References ExecStep(), fNextStep, and kStepInitArray.
ExecStep()
bool LHHelixTrackFindingTask::ExecStep ()
Definition at line 49 of file LHHelixTrackFindingTask.cpp.
References fCurrentTrack, fNextStep, kStepConfirmation, kStepContinuum, kStepContinuumAddHit, kStepEndEvent, kStepEndOfEvent, kStepExtrapolation, kStepExtrapolationAddHit, kStepFinalizeTrack, kStepInitArray, kStepInitTrack, kStepInitTrackAddHit, kStepNewTrack, kStepNextPhase, kStepRemoveTrack, lk_debug, StepConfirmation(), StepContinuum(), StepContinuumAddHit(), StepEndEvent(), StepExtrapolation(), StepExtrapolationAddHit(), StepFinalizeTrack(), StepInitArray(), StepInitTrack(), StepInitTrackAddHit(), StepNewTrack(), StepNextPhase(), and StepRemoveTrack().
Referenced by Exec(), and ExecStepUptoTrackNum().
ExecStepUptoTrackNum()
bool LHHelixTrackFindingTask::ExecStepUptoTrackNum (Int_t numTracks)
Definition at line 87 of file LHHelixTrackFindingTask.cpp.
References ExecStep(), fNextStep, fTrackArray, kStepEndOfEvent, and kStepNewTrack.
GetCurrentTrack()
LKHelixTrack * LHHelixTrackFindingTask::GetCurrentTrack () const inline
Definition at line 50 of file LHHelixTrackFindingTask.h.
References fCurrentTrack.
Init()
virtual bool LHHelixTrackFindingTask::Init () virtual
Reimplemented from LKTask.
ReturnBadHitsToPadPlane()
void LHHelixTrackFindingTask::ReturnBadHitsToPadPlane () private
Definition at line 533 of file LHHelixTrackFindingTask.cpp.
References fBadHits, fNumBadHits, and fPadPlane.
Referenced by StepConfirmation(), StepExtrapolation(), StepExtrapolationAddHit(), StepNewTrack(), StepNextPhase(), and StepRemoveTrack().
SetHitBranchName()
void LHHelixTrackFindingTask::SetHitBranchName (TString name) inline
Definition at line 52 of file LHHelixTrackFindingTask.h.
References fBranchNameHit.
SetTrackletBranchName()
void LHHelixTrackFindingTask::SetTrackletBranchName (TString name) inline
Definition at line 53 of file LHHelixTrackFindingTask.h.
References fBranchNameTracklet.
SetTrackPersistency()
void LHHelixTrackFindingTask::SetTrackPersistency (bool val) inline
Definition at line 27 of file LHHelixTrackFindingTask.h.
References fPersistency.
StepConfirmation()
int LHHelixTrackFindingTask::StepConfirmation () private
Definition at line 425 of file LHHelixTrackFindingTask.cpp.
References BuildAndConfirmTrack(), fCurrentTrack, fReferenceAxis, LKVector3::K(), kStepFinalizeTrack, kStepRemoveTrack, lk_debug, and ReturnBadHitsToPadPlane().
Referenced by ExecStep().
StepContinuum()
int LHHelixTrackFindingTask::StepContinuum () private
Definition at line 319 of file LHHelixTrackFindingTask.cpp.
References fCandHits, fGoodHits, fNumCandHits, fPadPlane, fTrackHits, kStepContinuumAddHit, kStepExtrapolation, and lk_debug.
Referenced by ExecStep().
StepContinuumAddHit()
int LHHelixTrackFindingTask::StepContinuumAddHit () private
Definition at line 337 of file LHHelixTrackFindingTask.cpp.
References CheckParentTrackID(), CorrelateHitWithTrack(), fBadHits, fCandHits, fCurrentTrack, fGoodHits, fNumCandHits, kStepContinuum, and lk_debug.
Referenced by ExecStep().
StepEndEvent()
int LHHelixTrackFindingTask::StepEndEvent () private
Definition at line 513 of file LHHelixTrackFindingTask.cpp.
References fTrackArray, kStepEndOfEvent, and lk_info.
Referenced by ExecStep().
StepExtrapolation()
int LHHelixTrackFindingTask::StepExtrapolation () private
Definition at line 372 of file LHHelixTrackFindingTask.cpp.
References kStepExtrapolationAddHit, lk_debug, and ReturnBadHitsToPadPlane().
Referenced by ExecStep().
StepExtrapolationAddHit()
int LHHelixTrackFindingTask::StepExtrapolationAddHit () private
Definition at line 382 of file LHHelixTrackFindingTask.cpp.
References AutoBuildByExtrapolation(), CheckTrackQuality(), fCurrentTrack, kStepConfirmation, kStepRemoveTrack, lk_debug, and ReturnBadHitsToPadPlane().
Referenced by ExecStep().
StepFinalizeTrack()
int LHHelixTrackFindingTask::StepFinalizeTrack () private
Definition at line 470 of file LHHelixTrackFindingTask.cpp.
References fCurrentTrack, fGoodHits, fPadPlane, fTrackHits, and kStepNewTrack.
Referenced by ExecStep().
StepInitArray()
int LHHelixTrackFindingTask::StepInitArray () private
Definition at line 100 of file LHHelixTrackFindingTask.cpp.
References fBadHits, fCandHits, fCurrentTrack, fGoodHits, fHitArray, fPadPlane, fPhaseIndex, fTrackArray, fTrackHits, kStepNewTrack, and lk_debug.
Referenced by ExecStep().
StepInitTrack()
int LHHelixTrackFindingTask::StepInitTrack () private
Definition at line 207 of file LHHelixTrackFindingTask.cpp.
References fCandHits, fCurrentTrack, fGoodHits, fNumCandHits, fPadPlane, fTrackHits, kStepInitTrackAddHit, kStepRemoveTrack, and lk_debug.
Referenced by ExecStep().
StepInitTrackAddHit()
int LHHelixTrackFindingTask::StepInitTrackAddHit () private
Definition at line 229 of file LHHelixTrackFindingTask.cpp.
References CorrelateHitWithTrack(), CorrelateHitWithTrackCandidate(), fBadHits, fCandHits, fCurrentTrack, fCutMaxNumHitsInitTrack, fCutMinHelixRadius, fCutMinNumHitsInitTrack, fGoodHits, fMinHitsToFitInitTrack, fNumCandHits, fPadPlane, fTrackLengthCutScale, kStepContinuum, kStepInitTrack, kStepInitTrackAddHit, kStepRemoveTrack, and lk_debug.
Referenced by ExecStep().
StepNewTrack()
int LHHelixTrackFindingTask::StepNewTrack () private
Definition at line 128 of file LHHelixTrackFindingTask.cpp.
References fCandHits, fCurrentTrack, fGoodHits, fPadPlane, fReferenceAxis, fTrackArray, fTrackHits, kStepInitTrack, kStepNextPhase, lk_debug, and ReturnBadHitsToPadPlane().
Referenced by ExecStep().
StepNextPhase()
int LHHelixTrackFindingTask::StepNextPhase () private
Definition at line 487 of file LHHelixTrackFindingTask.cpp.
References fCandHits, fCutMaxNumHitsInitTrack, fGoodHits, fPadPlane, fPhaseIndex, fTrackHits, kStepEndEvent, kStepNewTrack, and ReturnBadHitsToPadPlane().
Referenced by ExecStep().
StepRemoveTrack()
int LHHelixTrackFindingTask::StepRemoveTrack () private
Definition at line 160 of file LHHelixTrackFindingTask.cpp.
References fCandHits, fCurrentTrack, fGoodHits, fPadPlane, fTrackArray, fTrackHits, kStepNewTrack, lk_debug, and ReturnBadHitsToPadPlane().
Referenced by ExecStep().
Member Data Documentation
fBadHits
LKHitArray* LHHelixTrackFindingTask::fBadHits = nullptr private
Definition at line 98 of file LHHelixTrackFindingTask.h.
Referenced by AutoBuildAtPosition(), ClassImp(), ReturnBadHitsToPadPlane(), StepContinuumAddHit(), StepInitArray(), and StepInitTrackAddHit().
fBranchNameHit
TString LHHelixTrackFindingTask::fBranchNameHit = "Hit" private
Definition at line 90 of file LHHelixTrackFindingTask.h.
Referenced by ClassImp(), and SetHitBranchName().
fBranchNameTracklet
TString LHHelixTrackFindingTask::fBranchNameTracklet = "Tracklet" private
Definition at line 91 of file LHHelixTrackFindingTask.h.
Referenced by ClassImp(), and SetTrackletBranchName().
fCandHits
LKHitArray* LHHelixTrackFindingTask::fCandHits = nullptr private
Definition at line 96 of file LHHelixTrackFindingTask.h.
Referenced by AutoBuildAtPosition(), ClassImp(), StepContinuum(), StepContinuumAddHit(), StepInitArray(), StepInitTrack(), StepInitTrackAddHit(), StepNewTrack(), StepNextPhase(), and StepRemoveTrack().
fCurrentTrack
LKHelixTrack* LHHelixTrackFindingTask::fCurrentTrack = nullptr private
Definition at line 118 of file LHHelixTrackFindingTask.h.
Referenced by CorrelateHitWithTrackCandidate(), ExecStep(), GetCurrentTrack(), StepConfirmation(), StepContinuumAddHit(), StepExtrapolationAddHit(), StepFinalizeTrack(), StepInitArray(), StepInitTrack(), StepInitTrackAddHit(), StepNewTrack(), and StepRemoveTrack().
fCutdkInExpectedTrackPath
Double_t LHHelixTrackFindingTask::fCutdkInExpectedTrackPath = 4. private
Definition at line 116 of file LHHelixTrackFindingTask.h.
Referenced by CorrelateHitWithTrackCandidate().
fCutMaxNumHitsInitTrack
Int_t LHHelixTrackFindingTask::fCutMaxNumHitsInitTrack = 15 private
return hits if track has more than this number of hits within initialization stage
Definition at line 112 of file LHHelixTrackFindingTask.h.
Referenced by StepInitTrackAddHit(), and StepNextPhase().
fCutMinHelixRadius
Double_t LHHelixTrackFindingTask::fCutMinHelixRadius = 30. private
helix radius cut for initialization stage
Definition at line 114 of file LHHelixTrackFindingTask.h.
Referenced by CheckTrackQuality(), and StepInitTrackAddHit().
fCutMinNumHitsFinalTrack
Int_t LHHelixTrackFindingTask::fCutMinNumHitsFinalTrack = 15 private
remove track if track has smaller than this number of hits within initialization stage
Definition at line 113 of file LHHelixTrackFindingTask.h.
Referenced by AutoBuildByExtrapolation(), and BuildAndConfirmTrack().
fCutMinNumHitsInitTrack
Int_t LHHelixTrackFindingTask::fCutMinNumHitsInitTrack = 10 private
Definition at line 111 of file LHHelixTrackFindingTask.h.
Referenced by StepInitTrackAddHit().
fCvsCurrentTrack
TCanvas* LHHelixTrackFindingTask::fCvsCurrentTrack = nullptr private
Definition at line 125 of file LHHelixTrackFindingTask.h.
fDefaultScale
Double_t LHHelixTrackFindingTask::fDefaultScale private
Definition at line 100 of file LHHelixTrackFindingTask.h.
Referenced by ClassImp(), and CorrelateHitWithTrack().
fGoodHits
LKHitArray* LHHelixTrackFindingTask::fGoodHits = nullptr private
Definition at line 97 of file LHHelixTrackFindingTask.h.
Referenced by ClassImp(), StepContinuum(), StepContinuumAddHit(), StepFinalizeTrack(), StepInitArray(), StepInitTrack(), StepInitTrackAddHit(), StepNewTrack(), StepNextPhase(), and StepRemoveTrack().
fGraphCurrentTrackPoint
TGraphErrors* LHHelixTrackFindingTask::fGraphCurrentTrackPoint = nullptr private
Definition at line 126 of file LHHelixTrackFindingTask.h.
fHitArray
TClonesArray* LHHelixTrackFindingTask::fHitArray = nullptr private
Definition at line 87 of file LHHelixTrackFindingTask.h.
Referenced by ClassImp(), and StepInitArray().
fMinHitsToFitInitTrack
Int_t LHHelixTrackFindingTask::fMinHitsToFitInitTrack = 7 private
try track fit if track has more than this number of hits in track
Definition at line 110 of file LHHelixTrackFindingTask.h.
Referenced by StepInitTrackAddHit().
fNextStep
Int_t LHHelixTrackFindingTask::fNextStep = StepNo::kStepInitArray private
Definition at line 120 of file LHHelixTrackFindingTask.h.
Referenced by ClassImp(), Exec(), ExecStep(), and ExecStepUptoTrackNum().
fNumBadHits
Int_t LHHelixTrackFindingTask::fNumBadHits private
Definition at line 123 of file LHHelixTrackFindingTask.h.
Referenced by ReturnBadHitsToPadPlane().
fNumCandHits
Int_t LHHelixTrackFindingTask::fNumCandHits private
Definition at line 121 of file LHHelixTrackFindingTask.h.
Referenced by AutoBuildAtPosition(), StepContinuum(), StepContinuumAddHit(), StepInitTrack(), and StepInitTrackAddHit().
fNumGoodHits
Int_t LHHelixTrackFindingTask::fNumGoodHits private
Definition at line 122 of file LHHelixTrackFindingTask.h.
fPadPlane
LKDetectorPlane* LHHelixTrackFindingTask::fPadPlane = nullptr private
Definition at line 86 of file LHHelixTrackFindingTask.h.
Referenced by AutoBuildAtPosition(), CheckTrackContinuity(), ClassImp(), ReturnBadHitsToPadPlane(), StepContinuum(), StepFinalizeTrack(), StepInitArray(), StepInitTrack(), StepInitTrackAddHit(), StepNewTrack(), StepNextPhase(), and StepRemoveTrack().
fPersistency
bool LHHelixTrackFindingTask::fPersistency = true private
Definition at line 93 of file LHHelixTrackFindingTask.h.
Referenced by ClassImp(), and SetTrackPersistency().
fPhaseIndex
Int_t LHHelixTrackFindingTask::fPhaseIndex = 0 private
Definition at line 108 of file LHHelixTrackFindingTask.h.
Referenced by StepInitArray(), and StepNextPhase().
fReferenceAxis
LKVector3::Axis LHHelixTrackFindingTask::fReferenceAxis private
Definition at line 106 of file LHHelixTrackFindingTask.h.
Referenced by AutoBuildAtPosition(), CheckTrackContinuity(), ClassImp(), CorrelateHitWithTrackCandidate(), StepConfirmation(), and StepNewTrack().
fTpc
LHTpc* LHHelixTrackFindingTask::fTpc = nullptr private
Definition at line 85 of file LHHelixTrackFindingTask.h.
fTrackArray
TClonesArray* LHHelixTrackFindingTask::fTrackArray = nullptr private
Definition at line 88 of file LHHelixTrackFindingTask.h.
Referenced by ClassImp(), ExecStepUptoTrackNum(), StepEndEvent(), StepInitArray(), StepNewTrack(), and StepRemoveTrack().
fTrackHCutHL
Double_t LHHelixTrackFindingTask::fTrackHCutHL private
Track height cut high limit.
Definition at line 104 of file LHHelixTrackFindingTask.h.
Referenced by ClassImp(), CorrelateHitWithTrack(), and CorrelateHitWithTrackCandidate().
fTrackHCutLL
Double_t LHHelixTrackFindingTask::fTrackHCutLL private
Track height cut low limit.
Definition at line 103 of file LHHelixTrackFindingTask.h.
Referenced by ClassImp(), CorrelateHitWithTrack(), and CorrelateHitWithTrackCandidate().
fTrackHits
LKHitArray* LHHelixTrackFindingTask::fTrackHits = nullptr private
Definition at line 95 of file LHHelixTrackFindingTask.h.
Referenced by ClassImp(), StepContinuum(), StepFinalizeTrack(), StepInitArray(), StepInitTrack(), StepNewTrack(), StepNextPhase(), and StepRemoveTrack().
fTrackLengthCutScale
Double_t LHHelixTrackFindingTask::fTrackLengthCutScale = 2.5 private
track length cut for initialization stage is [this_var] * track -> GetRMSR()
Definition at line 115 of file LHHelixTrackFindingTask.h.
Referenced by StepInitTrackAddHit().
fTrackWCutHL
Double_t LHHelixTrackFindingTask::fTrackWCutHL private
Track width cut high limit.
Definition at line 102 of file LHHelixTrackFindingTask.h.
Referenced by ClassImp(), and CorrelateHitWithTrack().
fTrackWCutLL
Double_t LHHelixTrackFindingTask::fTrackWCutLL private
Track width cut low limit.
Definition at line 101 of file LHHelixTrackFindingTask.h.
Referenced by ClassImp(), and CorrelateHitWithTrack().
The documentation for this class was generated from the following files:
LHHelixTrackFindingTask.h
LHHelixTrackFindingTask.cpp