lilak: LKParameterContainer Class Reference
LKParameterContainer Class Reference
#include <LKParameterContainer.h>
Public Member Functions
virtual Int_t AddFile (TString fileName)
virtual Int_t AddFile (TString parName, TString fileName)
Add parameter file.
Int_t AddLine (std::string line)
Set parameter by line.
Bool_t AddPar (TString name, Double_t val, TString comment="")
Set parameter Double_t.
Bool_t AddPar (TString name, Int_t val, TString comment="")
Set parameter Int_t.
Bool_t AddPar (TString name, Long64_t val, TString comment="")
Set parameter Double_t.
Bool_t AddPar (TString name, TString val, TString comment="")
Set parameter TString.
virtual Int_t AddParameterContainer (LKParameterContainer *parc)
Add parameter container pointer.
Bool_t CheckPar (TString name) const
Bool_t CheckParTypeAxis (TString name, int idx=-1) const
Bool_t CheckParTypeBool (TString name, int idx=-1) const
Bool_t CheckParTypeColor (TString name, int idx=-1) const
Bool_t CheckParTypeDouble (TString name, int idx=-1) const
Bool_t CheckParTypeInt (TString name, int idx=-1) const
Bool_t CheckParTypeLong (TString name, int idx=-1) const
Bool_t CheckParTypeSize (TString name, int idx=-1) const
Bool_t CheckParTypeString (TString name, int idx=-1) const
Bool_t CheckParTypeStyle (TString name, int idx=-1) const
Bool_t CheckParTypeV3 (TString name) const
Bool_t CheckParTypeWidth (TString name, int idx=-1) const
Bool_t CheckParTypeX (TString name) const
Bool_t CheckParTypeY (TString name) const
Bool_t CheckParTypeZ (TString name) const
Bool_t CheckValue (TString name) const
LKParameterContainer * CloneParameterContainer (TString name="", bool addTemporary=false) const
LKParameterContainer * CreateGroupContainer (TString nameGroup)
LKParameterContainer * CreateMultiParContainer (TString parNameGiven)
Int_t GetNumInputFiles () const
Get number of input parameter files.
LKParameter * GetParameter (int idx)
axis_t GetParAxis (TString name, int idx=-1) const
Bool_t GetParBool (TString name, int idx=-1) const
Get parameter in Bool_t.
Int_t GetParColor (TString name, int idx=-1) const
Get parameter in Color_t.
Double_t GetParDouble (TString name, int idx=-1) const
Get parameter in Double_t.
Int_t GetParIndex (TString name) const
Int_t GetParInt (TString name, int idx=-1) const
Get parameter in Int_t.
Long64_t GetParLong (TString name, int idx=-1) const
Get parameter in Long64_t.
Int_t GetParN (TString name) const
Get number of parameters in array of given name.
Double_t GetParSize (TString name, int idx=-1) const
TString GetParString (TString name, int idx=-1) const
Get parameter in TString.
Int_t GetParStyle (TString name, int idx=-1) const
TVector3 GetParV3 (TString name) const
Get parameter in TVector.
std::vector< bool > GetParVBool (TString name) const
std::vector< int > GetParVColor (TString name) const
std::vector< double > GetParVDouble (TString name) const
std::vector< int > GetParVInt (TString name) const
std::vector< double > GetParVSize (TString name) const
std::vector< TString > GetParVString (TString name) const
std::vector< int > GetParVStyle (TString name) const
std::vector< int > GetParVWidth (TString name) const
Int_t GetParWidth (TString name, int idx=-1) const
Double_t GetParX (TString name) const
Double_t GetParY (TString name) const
Double_t GetParZ (TString name) const
bool IsEmpty () const
Return true if empty.
LKParameterContainer ()
LKParameterContainer (const char *parName)
Constructor with input parameter file name.
virtual void Print (Option_t *option="") const
void PrintCollection (TString fileName="")
void Recompile ()
void ReplaceEnvVariables (TString &val)
evaluate and replace all unraveled variables with ({par},+,-,...)
void ReplaceVariables (TString &val)
evaluate and replace all unraveled variables with ({par},+,-,...)
void Require (TString name, TString value, TString comment, TString type="", int compare=-1)
void SaveAs (const char *filename, Option_t *option="") const
bool SearchAndAddPar (TString dirName="")
void SetCollectParameters (bool collect)
void SetIsNewCollection ()
void SetParType (TString name, TString type)
void UpdateBinning (TString name, Int_t &n, Double_t &x1, Double_t &x2) const
void UpdatePar (axis_t &value, TString name, int idx=-1) const
See UpdatePar(Bool_t, TString, int)
void UpdatePar (Bool_t &value, TString name, int idx=-1) const
UpdatePar() will update given value, if parameter with name and idx exist. If not, value will not be changed.
void UpdatePar (Double_t &value, TString name, int idx=-1) const
See UpdatePar(Bool_t, TString, int)
void UpdatePar (Int_t &value, TString name, int idx=-1) const
See UpdatePar(Bool_t, TString, int)
void UpdatePar (Long64_t &value, TString name, int idx=-1) const
See UpdatePar(Bool_t, TString, int)
void UpdatePar (TString &value, TString name, int idx=-1) const
See UpdatePar(Bool_t, TString, int)
void UpdateV3 (TString name, Double_t &x, Double_t &y, Double_t &z) const
virtual ~LKParameterContainer ()
Protected Member Functions
LKParameter * FindPar (TString givenName, bool terminateIfNull=false) const
LKParameter * FindParFree (TString givenName, bool terminateIfNull=false)
LKParameter * SetInputFile (TString name, TString value)
LKParameter * SetLineComment (TString comment)
LKParameter * SetPar (TString name, Double_t val, TString comment="")
Set parameter Double_t.
LKParameter * SetPar (TString name, Int_t val, TString comment="")
Set parameter Int_t.
LKParameter * SetPar (TString name, TString raw, TString val, TString comment, int parameterType=1)
LKParameter * SetPar (TString name, TString val, TString comment="")
Set parameter string.
LKParameter * SetParCont (TString name)
LKParameter * SetParFile (TString name)
Private Member Functions
bool CheckFormulaValidity (TString formula, bool isInt=false) const
void CollectParameter ()
double Eval (TString formula) const
void ProcessTypeError (TString name, TString val, TString type) const
Private Attributes
LKParameterContainer * fCollectedParameterContainer = nullptr
TString fCurrentGroupName
vector< TString > fGroupNameArray
Int_t fNumInputFiles = 0
bool fParameterCollectionMode = false
Int_t fPreviousTabSize = 0
Int_t fRank = 0
vector< Int_t > fTabSizeArray
bool fThisIsNewCollection = false
Detailed Description
LKParameterContainer
LKParameterContainer is a list of parameters defined by LKParameter The key features of LKParameter are [group], [name], [value], [comment]. When parameter is defined from text file, line should have a form : [header] [name] [value] [comment]
[comment]
Comments should start with "#". Lines starting with "#" are defined as hidden line comment.
[header]
[header] defines the characteristic of line.
< : Input parameter file. The parameter-value will be given as anohter input parameter file.
@ : Conditional parameter. May be used when user wants to define parameter, only when group name is defined as parameter-name or parameter-value, ex) @group/name value
[tab] : See [group] section below.
[name] and group
[name] should not contain empty spaces.
[name] can set group using "/". ex) group/name
To add additional parameter file, start [name] with "<". ex) <common_parameters path/to/additional/config.mac
[value]
[value] can be a single value or a list of values.
If [value] is a list of values, they should be separated by empty spaces.
[value] can reference other parameters values using {...}. ex) {[name]}, {[name][1]}.
[value] can reference environment variable using e{...}. ex) e{ROOTSYS}, e{HOME}, e{LILAK_PATH}
Folloing symbols should not be included in name / value
name : < @ & ! = { } / *
value : { } =
[group]
If a [name] ends with '/' and do not have [value], it will define [group].
To define parameter under [group], parameter should have [tab], with size of [tab] larger than the [tab] of line where group was defined.
Size of [tab] should not be different under same group.
Another [group] can be defined under [group] definition
Final name of the parameter will have [group]/[name]
example parameter file
# example parameter file
<input_file  path/file/to/add.par
LKRun/RunName  lilak 1 sim   # this parameter will last only within the first lilak output file
using       option1
option1/par  value1  # parameter "par" will be set as "value1" because it was defined previously
option2/par  value2  # parameter "par" will not be set
option3/par  value3  # parameter "par" will not be set
title        common parameter definitions
dimension    50 60 70
length       {dimension[2]}+30  # parameter value will be evaluated to 70+30 which is 100
color        kRed+1  # parameter value will be evaluated to 633 when GetParColor is called.
persistency/  # group
    hit      false   # this parameter will be defined as "persistency/hit false"
    track    true    # this parameter will be defined as "persistency/track true"
color       kBlue+3 # parameter value will overwrite above parameter "color"
# sometimes user want to define parameter with same name for some reason...
SameName   1
SameName   2
SameName   3
Get parameter
The type of parameters are decided when Getter is called. Featured types: TString, int, double, bool, TVector3, Color_t, Width_t, Size_t.
GetParInt("size") will return parameter value 100 as int type, GetParString("size") will return parameter value 100 as TString type, GetParString("title") will return TString type "this is title" GetParString("title",0) will return TString type "this" GetParString("title",3) will return TString type "5" GetParDouble("title",3) will return double type 5 GetParDouble("length") will return double type 80 GetParString("length") will return TString type "70+10" GetParV3("dimension"), will return TVector3(50,60,70) With GetParColor("color") will return Color_t(int) type 633
GetParV3 use the first 3 values as the x, y, and z coordinates of the return value TVector3(x,y,z). The root color keyword will be converted from kRed+1 to an integer value 633 when GetParColor is called.
Definition at line 116 of file LKParameterContainer.h.
Constructor & Destructor Documentation
LKParameterContainer() [1/2]
LKParameterContainer::LKParameterContainer ()
Referenced by CloneParameterContainer(), CreateGroupContainer(), CreateMultiParContainer(), and SetCollectParameters().
LKParameterContainer() [2/2]
LKParameterContainer::LKParameterContainer (const char * parName)
Constructor with input parameter file name.
Definition at line 30 of file LKParameterContainer.cpp.
References AddFile().
~LKParameterContainer()
virtual LKParameterContainer::~LKParameterContainer () inline virtual
Definition at line 121 of file LKParameterContainer.h.
Member Function Documentation
AddFile() [1/2]
virtual Int_t LKParameterContainer::AddFile (TString fileName) inline virtual
Definition at line 158 of file LKParameterContainer.h.
References AddFile().
Referenced by AddFile().
AddFile() [2/2]
Int_t LKParameterContainer::AddFile (TString parName, TString fileName) virtual
Add parameter file.
Add parameter by given fileName. If fileName does not include path, file will be searched in path/to/LILAK/input.
fileName will also be registered as parameter. parameter name will be set as INPUT_PARAMETER_FILE[fNumInputFiles]
Definition at line 228 of file LKParameterContainer.cpp.
References AddLine(), fNumInputFiles, LILAK_PATH, lk_error, lk_info, Recompile(), ReplaceEnvVariables(), and SetLineComment().
Referenced by AddPar(), LKParameterContainer(), and SearchAndAddPar().
AddLine()
Int_t LKParameterContainer::AddLine (std::string line)
Set parameter by line.
Definition at line 696 of file LKParameterContainer.cpp.
References AddPar(), e_cout, fCurrentGroupName, fGroupNameArray, fPreviousTabSize, fTabSizeArray, lk_debug, lk_error, lk_info, and SetLineComment().
Referenced by AddFile(), FindPar(), and FindParFree().
AddPar() [1/4]
Bool_t LKParameterContainer::AddPar (TString name, Double_t val, TString comment = "") inline
Set parameter Double_t.
Definition at line 173 of file LKParameterContainer.h.
References AddPar().
Referenced by AddPar().
AddPar() [2/4]
Bool_t LKParameterContainer::AddPar (TString name, Int_t val, TString comment = "") inline
Set parameter Int_t.
Definition at line 171 of file LKParameterContainer.h.
References AddPar().
Referenced by AddPar().
AddPar() [3/4]
Bool_t LKParameterContainer::AddPar (TString name, Long64_t val, TString comment = "") inline
Set parameter Double_t.
Definition at line 172 of file LKParameterContainer.h.
References AddPar().
Referenced by AddPar().
AddPar() [4/4]
Bool_t LKParameterContainer::AddPar (TString name, TString val, TString comment = "")
Set parameter TString.
Definition at line 879 of file LKParameterContainer.cpp.
References AddFile(), CheckPar(), CheckValue(), e_cout, FindParFree(), fThisIsNewCollection, LKParameter::GetType(), lk_error, lk_info, lk_warning, LKParameter::SetIsConditional(), LKParameter::SetIsMultiple(), LKParameter::SetIsRewrite(), LKParameter::SetIsTemporary(), SetLineComment(), and SetPar().
Referenced by AddLine(), CreateGroupContainer(), and SKSiArrayPlane::Init().
AddParameterContainer()
Int_t LKParameterContainer::AddParameterContainer (LKParameterContainer * parc) virtual
Add parameter container pointer.
Definition at line 315 of file LKParameterContainer.cpp.
References FindPar(), fNumInputFiles, LKParameter::GetComment(), LKParameter::GetRaw(), LKParameter::GetType(), LKParameter::GetValue(), lk_info, lk_warning, Recompile(), SetLineComment(), SetPar(), and SetParCont().
CheckFormulaValidity()
bool LKParameterContainer::CheckFormulaValidity (TString formula, bool isInt = false) const private
Definition at line 40 of file LKParameterContainer.cpp.
Referenced by ReplaceVariables().
CheckPar()
Bool_t LKParameterContainer::CheckPar (TString name) const
Definition at line 1087 of file LKParameterContainer.cpp.
References FindPar().
Referenced by AddPar(), LHTpc::BuildDetectorPlane(), ATTPC::BuildDetectorPlane(), LKEveTask::DrawEve3D(), LKPadPlane::DrawHist(), LTPadPlane::GetChannelAnalyzer(), LKDetector::GetChannelAnalyzer(), LKDetectorPlane::GetChannelAnalyzer(), LKRun::Init(), LKMFMConversionTask::Init(), LKEveTask::Init(), SKSiArrayPlane::Init(), SKEnergyRestorationTask::Init(), TTPulseExtractionTask::Init(), LKG4RunManager::Run(), LKEveTask::SetEveLineAtt(), LKEveTask::SetEveMarkerAtt(), LKEveTask::SetGraphAtt(), LKEveTask::SetGraphAtt(), UpdateBinning(), UpdatePar(), UpdatePar(), UpdatePar(), UpdatePar(), UpdatePar(), UpdatePar(), and UpdateV3().
CheckParTypeAxis()
Bool_t LKParameterContainer::CheckParTypeAxis (TString name, int idx = -1) const inline
Definition at line 191 of file LKParameterContainer.h.
References FindPar().
CheckParTypeBool()
Bool_t LKParameterContainer::CheckParTypeBool (TString name, int idx = -1) const inline
Definition at line 178 of file LKParameterContainer.h.
References FindPar().
CheckParTypeColor()
Bool_t LKParameterContainer::CheckParTypeColor (TString name, int idx = -1) const inline
Definition at line 183 of file LKParameterContainer.h.
References FindPar().
CheckParTypeDouble()
Bool_t LKParameterContainer::CheckParTypeDouble (TString name, int idx = -1) const inline
Definition at line 181 of file LKParameterContainer.h.
References FindPar().
Referenced by CheckParTypeSize(), CheckParTypeX(), CheckParTypeY(), and CheckParTypeZ().
CheckParTypeInt()
Bool_t LKParameterContainer::CheckParTypeInt (TString name, int idx = -1) const inline
Definition at line 179 of file LKParameterContainer.h.
References FindPar().
Referenced by CheckParTypeStyle(), and CheckParTypeWidth().
CheckParTypeLong()
Bool_t LKParameterContainer::CheckParTypeLong (TString name, int idx = -1) const inline
Definition at line 180 of file LKParameterContainer.h.
References FindPar().
CheckParTypeSize()
Bool_t LKParameterContainer::CheckParTypeSize (TString name, int idx = -1) const inline
Definition at line 190 of file LKParameterContainer.h.
References CheckParTypeDouble().
CheckParTypeString()
Bool_t LKParameterContainer::CheckParTypeString (TString name, int idx = -1) const inline
Definition at line 182 of file LKParameterContainer.h.
References FindPar().
CheckParTypeStyle()
Bool_t LKParameterContainer::CheckParTypeStyle (TString name, int idx = -1) const inline
Definition at line 188 of file LKParameterContainer.h.
References CheckParTypeInt().
CheckParTypeV3()
Bool_t LKParameterContainer::CheckParTypeV3 (TString name) const inline
Definition at line 184 of file LKParameterContainer.h.
References FindPar().
CheckParTypeWidth()
Bool_t LKParameterContainer::CheckParTypeWidth (TString name, int idx = -1) const inline
Definition at line 189 of file LKParameterContainer.h.
References CheckParTypeInt().
CheckParTypeX()
Bool_t LKParameterContainer::CheckParTypeX (TString name) const inline
Definition at line 185 of file LKParameterContainer.h.
References CheckParTypeDouble().
CheckParTypeY()
Bool_t LKParameterContainer::CheckParTypeY (TString name) const inline
Definition at line 186 of file LKParameterContainer.h.
References CheckParTypeDouble().
CheckParTypeZ()
Bool_t LKParameterContainer::CheckParTypeZ (TString name) const inline
Definition at line 187 of file LKParameterContainer.h.
References CheckParTypeDouble().
CheckValue()
Bool_t LKParameterContainer::CheckValue (TString name) const
Definition at line 1094 of file LKParameterContainer.cpp.
Referenced by AddPar().
CloneParameterContainer()
LKParameterContainer * LKParameterContainer::CloneParameterContainer (TString name = "", bool addTemporary = false) const
Definition at line 670 of file LKParameterContainer.cpp.
References LKParameter::GetComment(), LKParameter::GetLine(), LKParameter::IsLineComment(), LKParameter::IsTemporary(), LKParameterContainer(), and SetLineComment().
CollectParameter()
void LKParameterContainer::CollectParameter () private
CreateGroupContainer()
LKParameterContainer * LKParameterContainer::CreateGroupContainer (TString nameGroup)
Definition at line 1009 of file LKParameterContainer.cpp.
References AddPar(), LKParameter::GetGroup(), and LKParameterContainer().
CreateMultiParContainer()
LKParameterContainer * LKParameterContainer::CreateMultiParContainer (TString parNameGiven)
Definition at line 1033 of file LKParameterContainer.cpp.
References LKParameterContainer().
Eval()
double LKParameterContainer::Eval (TString formula) const private
Definition at line 66 of file LKParameterContainer.cpp.
Referenced by ReplaceVariables().
FindPar()
LKParameter * LKParameterContainer::FindPar (TString givenName, bool terminateIfNull = false) const protected
Definition at line 1173 of file LKParameterContainer.cpp.
References AddLine(), fCollectedParameterContainer, FindPar(), fParameterCollectionMode, LKParameter::GetLine(), and lk_error.
Referenced by AddParameterContainer(), CheckPar(), CheckParTypeAxis(), CheckParTypeBool(), CheckParTypeColor(), CheckParTypeDouble(), CheckParTypeInt(), CheckParTypeLong(), CheckParTypeString(), CheckParTypeV3(), FindPar(), FindParFree(), GetParAxis(), GetParBool(), GetParColor(), GetParDouble(), GetParInt(), GetParLong(), GetParN(), GetParString(), GetParV3(), GetParVBool(), GetParVDouble(), GetParVInt(), GetParVString(), and Require().
FindParFree()
LKParameter * LKParameterContainer::FindParFree (TString givenName, bool terminateIfNull = false) protected
Definition at line 1108 of file LKParameterContainer.cpp.
References AddLine(), fCollectedParameterContainer, FindPar(), fParameterCollectionMode, LKParameter::GetLine(), and lk_error.
Referenced by AddPar(), Require(), and SetParType().
GetNumInputFiles()
Int_t LKParameterContainer::GetNumInputFiles () const inline
Get number of input parameter files.
Definition at line 160 of file LKParameterContainer.h.
References fNumInputFiles.
GetParameter()
LKParameter * LKParameterContainer::GetParameter (int idx) inline
Definition at line 163 of file LKParameterContainer.h.
GetParAxis()
axis_t LKParameterContainer::GetParAxis (TString name, int idx = -1) const inline
Definition at line 208 of file LKParameterContainer.h.
References FindPar().
Referenced by UpdatePar().
GetParBool()
Bool_t LKParameterContainer::GetParBool (TString name, int idx = -1) const inline
Get parameter in Bool_t.
Definition at line 195 of file LKParameterContainer.h.
References FindPar().
Referenced by LKEveTask::DrawEve3D(), and UpdatePar().
GetParColor()
Int_t LKParameterContainer::GetParColor (TString name, int idx = -1) const inline
Get parameter in Color_t.
Definition at line 200 of file LKParameterContainer.h.
References FindPar().
GetParDouble()
Double_t LKParameterContainer::GetParDouble (TString name, int idx = -1) const inline
Get parameter in Double_t.
Definition at line 198 of file LKParameterContainer.h.
References FindPar().
Referenced by LKEveTask::DrawEve3D(), LKPadPlane::DrawHist(), GetParSize(), GetParX(), GetParY(), GetParZ(), UpdateBinning(), UpdatePar(), and UpdateV3().
GetParIndex()
int LKParameterContainer::GetParIndex (TString name) const
Definition at line 1071 of file LKParameterContainer.cpp.
Referenced by SKSiArrayPlane::Init().
GetParInt()
Int_t LKParameterContainer::GetParInt (TString name, int idx = -1) const inline
Get parameter in Int_t.
Definition at line 196 of file LKParameterContainer.h.
References FindPar().
Referenced by GetParStyle(), GetParWidth(), UpdateBinning(), and UpdatePar().
GetParLong()
Long64_t LKParameterContainer::GetParLong (TString name, int idx = -1) const inline
Get parameter in Long64_t.
Definition at line 197 of file LKParameterContainer.h.
References FindPar().
Referenced by UpdatePar().
GetParN()
Int_t LKParameterContainer::GetParN (TString name) const inline
Get number of parameters in array of given name.
Definition at line 194 of file LKParameterContainer.h.
References FindPar().
Referenced by UpdateBinning(), and UpdateV3().
GetParSize()
Double_t LKParameterContainer::GetParSize (TString name, int idx = -1) const inline
Definition at line 207 of file LKParameterContainer.h.
References GetParDouble().
GetParString()
TString LKParameterContainer::GetParString (TString name, int idx = -1) const inline
Get parameter in TString.
Definition at line 199 of file LKParameterContainer.h.
References FindPar().
Referenced by LHTpc::BuildDetectorPlane(), LKG4RunManager::Initialize(), ReplaceVariables(), and UpdatePar().
GetParStyle()
Int_t LKParameterContainer::GetParStyle (TString name, int idx = -1) const inline
Definition at line 205 of file LKParameterContainer.h.
References GetParInt().
GetParV3()
TVector3 LKParameterContainer::GetParV3 (TString name) const inline
Get parameter in TVector.
Definition at line 201 of file LKParameterContainer.h.
References FindPar().
GetParVBool()
std::vector< bool > LKParameterContainer::GetParVBool (TString name) const inline
Definition at line 210 of file LKParameterContainer.h.
References FindPar().
GetParVColor()
std::vector< int > LKParameterContainer::GetParVColor (TString name) const inline
Definition at line 216 of file LKParameterContainer.h.
References GetParVInt().
GetParVDouble()
std::vector< double > LKParameterContainer::GetParVDouble (TString name) const inline
Definition at line 212 of file LKParameterContainer.h.
References FindPar().
Referenced by GetParVSize().
GetParVInt()
std::vector< int > LKParameterContainer::GetParVInt (TString name) const inline
Definition at line 211 of file LKParameterContainer.h.
References FindPar().
Referenced by GetParVColor(), GetParVStyle(), and GetParVWidth().
GetParVSize()
std::vector< double > LKParameterContainer::GetParVSize (TString name) const inline
Definition at line 217 of file LKParameterContainer.h.
References GetParVDouble().
GetParVString()
std::vector< TString > LKParameterContainer::GetParVString (TString name) const inline
Definition at line 213 of file LKParameterContainer.h.
References FindPar().
GetParVStyle()
std::vector< int > LKParameterContainer::GetParVStyle (TString name) const inline
Definition at line 214 of file LKParameterContainer.h.
References GetParVInt().
GetParVWidth()
std::vector< int > LKParameterContainer::GetParVWidth (TString name) const inline
Definition at line 215 of file LKParameterContainer.h.
References GetParVInt().
GetParWidth()
Int_t LKParameterContainer::GetParWidth (TString name, int idx = -1) const inline
Definition at line 206 of file LKParameterContainer.h.
References GetParInt().
GetParX()
Double_t LKParameterContainer::GetParX (TString name) const inline
Definition at line 202 of file LKParameterContainer.h.
References GetParDouble().
GetParY()
Double_t LKParameterContainer::GetParY (TString name) const inline
Definition at line 203 of file LKParameterContainer.h.
References GetParDouble().
GetParZ()
Double_t LKParameterContainer::GetParZ (TString name) const inline
Definition at line 204 of file LKParameterContainer.h.
References GetParDouble().
IsEmpty()
bool LKParameterContainer::IsEmpty () const
Return true if empty.
Definition at line 92 of file LKParameterContainer.cpp.
Print()
void LKParameterContainer::Print (Option_t * option = "") const virtual
Print to screen or file
How to give option
If file name is not given, parameter container will be printed on the screen. ex) Print() If file name is given with an extension (".par") parameter container will be written to the file. ex) Print("file.par") Options may be added with and addition to ":" or space. ex) Print("file.par:line#:par#"), Print("eval:par#")
options
eval : evaluate and replace all unraveled variables with ({par},+,-,...)
line# : show line comments
par# : show parameter comments
all : show all hidden parameters (not recommended to write file with this mode)
raw : print from TObjArray::Print()
Definition at line 518 of file LKParameterContainer.cpp.
References e_cout, e_list, LKParameter::GetLine(), and lk_info.
Referenced by PrintCollection(), SaveAs(), and test_parameter().
PrintCollection()
void LKParameterContainer::PrintCollection (TString fileName = "")
Definition at line 1250 of file LKParameterContainer.cpp.
References fCollectedParameterContainer, Print(), and SaveAs().
ProcessTypeError()
void LKParameterContainer::ProcessTypeError (TString name, TString val, TString type) const private
Definition at line 35 of file LKParameterContainer.cpp.
References lk_error.
Recompile()
void LKParameterContainer::Recompile ()
Definition at line 79 of file LKParameterContainer.cpp.
References ReplaceVariables().
Referenced by AddFile(), and AddParameterContainer().
ReplaceEnvVariables()
void LKParameterContainer::ReplaceEnvVariables (TString & val)
evaluate and replace all unraveled variables with ({par},+,-,...)
Definition at line 99 of file LKParameterContainer.cpp.
Referenced by AddFile(), and ReplaceVariables().
ReplaceVariables()
void LKParameterContainer::ReplaceVariables (TString & val)
evaluate and replace all unraveled variables with ({par},+,-,...)
Definition at line 124 of file LKParameterContainer.cpp.
References CheckFormulaValidity(), Eval(), GetParString(), LILAK_HASH, LILAK_HOSTNAME, LILAK_HOSTUSER, LILAK_MAINPROJECT_HASH, LILAK_MAINPROJECT_VERSION, LILAK_PATH, LILAK_USERNAME, LILAK_VERSION, lk_error, and ReplaceEnvVariables().
Referenced by Recompile(), and SetPar().
Require()
void LKParameterContainer::Require (TString name, TString value, TString comment, TString type = "", int compare = -1)
type: s: Standard l: Legacy r: Rewrite m: Multiple t: Temporary i: InputFile c: Conditional #: LineComment
Definition at line 1055 of file LKParameterContainer.cpp.
References fCollectedParameterContainer, FindPar(), FindParFree(), fParameterCollectionMode, SetPar(), and SetType().
SaveAs()
void LKParameterContainer::SaveAs (const char * filename, Option_t * option = "") const
Definition at line 71 of file LKParameterContainer.cpp.
References Print().
Referenced by PrintCollection().
SearchAndAddPar()
bool LKParameterContainer::SearchAndAddPar (TString dirName = "")
Definition at line 356 of file LKParameterContainer.cpp.
References AddFile(), e_error, e_info, e_warning, lk_info, next(), and SearchAndAddPar().
Referenced by SearchAndAddPar().
SetCollectParameters()
void LKParameterContainer::SetCollectParameters (bool collect)
Definition at line 1238 of file LKParameterContainer.cpp.
References fCollectedParameterContainer, fParameterCollectionMode, LKParameterContainer(), and SetIsNewCollection().
SetInputFile()
LKParameter * LKParameterContainer::SetInputFile (TString name, TString value) protected
Definition at line 965 of file LKParameterContainer.cpp.
SetIsNewCollection()
void LKParameterContainer::SetIsNewCollection () inline
Definition at line 277 of file LKParameterContainer.h.
References fThisIsNewCollection.
Referenced by SetCollectParameters().
SetLineComment()
LKParameter * LKParameterContainer::SetLineComment (TString comment) protected
Definition at line 972 of file LKParameterContainer.cpp.
References SetLineComment().
Referenced by AddFile(), AddLine(), AddPar(), AddParameterContainer(), CloneParameterContainer(), SetLineComment(), SetParCont(), and SetParFile().
SetPar() [1/4]
LKParameter * LKParameterContainer::SetPar (TString name, Double_t val, TString comment = "") inline protected
Set parameter Double_t.
Definition at line 251 of file LKParameterContainer.h.
References SetPar().
Referenced by SetPar().
SetPar() [2/4]
LKParameter * LKParameterContainer::SetPar (TString name, Int_t val, TString comment = "") inline protected
Set parameter Int_t.
Definition at line 250 of file LKParameterContainer.h.
References SetPar().
Referenced by SetPar().
SetPar() [3/4]
LKParameter * LKParameterContainer::SetPar (TString name, TString raw, TString val, TString comment, int parameterType = 1) protected
Definition at line 955 of file LKParameterContainer.cpp.
References ReplaceVariables().
Referenced by AddPar(), AddParameterContainer(), and Require().
SetPar() [4/4]
LKParameter * LKParameterContainer::SetPar (TString name, TString val, TString comment = "") inline protected
Set parameter string.
Definition at line 249 of file LKParameterContainer.h.
References SetPar().
Referenced by SetPar().
SetParCont()
LKParameter * LKParameterContainer::SetParCont (TString name) protected
Definition at line 985 of file LKParameterContainer.cpp.
References SetLineComment().
Referenced by AddParameterContainer().
SetParFile()
LKParameter * LKParameterContainer::SetParFile (TString name) protected
Definition at line 981 of file LKParameterContainer.cpp.
References SetLineComment().
SetParType()
void LKParameterContainer::SetParType (TString name, TString type) inline
Definition at line 245 of file LKParameterContainer.h.
References FindParFree(), and SetType().
UpdateBinning()
void LKParameterContainer::UpdateBinning (TString name, Int_t & n, Double_t & x1, Double_t & x2) const
Definition at line 989 of file LKParameterContainer.cpp.
References CheckPar(), GetParDouble(), GetParInt(), and GetParN().
UpdatePar() [1/6]
void LKParameterContainer::UpdatePar (axis_t & value, TString name, int idx = -1) const inline
See UpdatePar(Bool_t, TString, int)
Definition at line 225 of file LKParameterContainer.h.
References CheckPar(), and GetParAxis().
UpdatePar() [2/6]
void LKParameterContainer::UpdatePar (Bool_t & value, TString name, int idx = -1) const inline
UpdatePar() will update given value, if parameter with name and idx exist. If not, value will not be changed.
Definition at line 220 of file LKParameterContainer.h.
References CheckPar(), and GetParBool().
UpdatePar() [3/6]
void LKParameterContainer::UpdatePar (Double_t & value, TString name, int idx = -1) const inline
See UpdatePar(Bool_t, TString, int)
Definition at line 223 of file LKParameterContainer.h.
References CheckPar(), and GetParDouble().
UpdatePar() [4/6]
void LKParameterContainer::UpdatePar (Int_t & value, TString name, int idx = -1) const inline
See UpdatePar(Bool_t, TString, int)
Definition at line 221 of file LKParameterContainer.h.
References CheckPar(), and GetParInt().
UpdatePar() [5/6]
void LKParameterContainer::UpdatePar (Long64_t & value, TString name, int idx = -1) const inline
See UpdatePar(Bool_t, TString, int)
Definition at line 222 of file LKParameterContainer.h.
References CheckPar(), and GetParLong().
UpdatePar() [6/6]
void LKParameterContainer::UpdatePar (TString & value, TString name, int idx = -1) const inline
See UpdatePar(Bool_t, TString, int)
Definition at line 224 of file LKParameterContainer.h.
References CheckPar(), and GetParString().
UpdateV3()
void LKParameterContainer::UpdateV3 (TString name, Double_t & x, Double_t & y, Double_t & z) const
Definition at line 999 of file LKParameterContainer.cpp.
References CheckPar(), GetParDouble(), GetParN(), x, and y.
Member Data Documentation
fCollectedParameterContainer
LKParameterContainer* LKParameterContainer::fCollectedParameterContainer = nullptr private
Definition at line 283 of file LKParameterContainer.h.
Referenced by FindPar(), FindParFree(), PrintCollection(), Require(), and SetCollectParameters().
fCurrentGroupName
TString LKParameterContainer::fCurrentGroupName private
Definition at line 269 of file LKParameterContainer.h.
Referenced by AddLine().
fGroupNameArray
vector<TString> LKParameterContainer::fGroupNameArray private
Definition at line 272 of file LKParameterContainer.h.
Referenced by AddLine().
fNumInputFiles
Int_t LKParameterContainer::fNumInputFiles = 0 private
Definition at line 265 of file LKParameterContainer.h.
Referenced by AddFile(), AddParameterContainer(), and GetNumInputFiles().
fParameterCollectionMode
bool LKParameterContainer::fParameterCollectionMode = false private
Definition at line 281 of file LKParameterContainer.h.
Referenced by FindPar(), FindParFree(), Require(), and SetCollectParameters().
fPreviousTabSize
Int_t LKParameterContainer::fPreviousTabSize = 0 private
Definition at line 270 of file LKParameterContainer.h.
Referenced by AddLine().
fRank
Int_t LKParameterContainer::fRank = 0 private
Definition at line 266 of file LKParameterContainer.h.
fTabSizeArray
vector<Int_t> LKParameterContainer::fTabSizeArray private
Definition at line 271 of file LKParameterContainer.h.
Referenced by AddLine().
fThisIsNewCollection
bool LKParameterContainer::fThisIsNewCollection = false private
Definition at line 282 of file LKParameterContainer.h.
Referenced by AddPar(), and SetIsNewCollection().
The documentation for this class was generated from the following files:
LKParameterContainer.h
LKParameterContainer.cpp