LILAK: LKLinearTrack Class Reference
LKLinearTrack Class Reference abstract
#include <LKLinearTrack.h>
Public Types
enum LKFitStatus : int {
kNone = -1 , kBad = 0 , kLine = 1 , kPlane = 2 ,
kHelix = 3 , kGenfitTrack = 4
}
Public Member Functions
virtual void AddHit (LKHit *hit)
void Clear (Option_t *option="")
virtual void ClearHits ()
void ClosestPointOnLine (Double_t x, Double_t y, Double_t z, Double_t &x0, Double_t &y0, Double_t &z0) const
TVector3 ClosestPointOnLine (TVector3 pos) const
virtual double Continuity (double &totalLength, double &continuousLength, double distCut=25)
virtual double Continuity (double distCut=25)
virtual void Copy (TObject &object) const
void CopyFrom (LKLinearTrack *track)
bool Create3DTrack (LKLinearTrack *track1, TString planeAxes1, LKLinearTrack *track2, TString planeAxes2)
TVector3 Direction () const
1 to 2
Double_t DistanceToLine (Double_t x, Double_t y, Double_t z) const
Double_t DistanceToLine (TVector3 pos) const
virtual bool DoDrawOnDetectorPlane ()
TArrow * DrawArrowXY (Double_t asize=0.02)
TArrow * DrawArrowXZ (Double_t asize=0.02)
TArrow * DrawArrowYZ (Double_t asize=0.02)
TArrow * DrawArrowZX (Double_t asize=0.02)
TArrow * DrawArrowZY (Double_t asize=0.02)
virtual bool DrawByDefault ()
return true if to be displayed on eve.
virtual TVector3 ExtrapolateByLength (double l) const =0
Extrapolate by length (tail:0), returns extrapolated position.
virtual TVector3 ExtrapolateByLength (Double_t l) const
virtual TVector3 ExtrapolateByRatio (double r) const =0
Extrapolate by ratio (tail:0, head:1), returns extrapolated position.
virtual TVector3 ExtrapolateByRatio (Double_t r) const
virtual TVector3 ExtrapolateHead (double l) const =0
Extrapolate head of track about length, returns extrapolated position.
virtual TVector3 ExtrapolateHead (Double_t l) const
virtual TVector3 ExtrapolateTail (double l) const =0
Extrapolate tail of track about length, returns extrapolated position.
virtual TVector3 ExtrapolateTail (Double_t l) const
virtual TVector3 ExtrapolateTo (TVector3 point) const
Extrapolate to POCA from point, returns extrapolated position.
void FillTrajectory (TGraphErrors *graphTrack, LKVector3::Axis axis1, LKVector3::Axis axis2)
void FillTrajectory (TGraphErrors *graphTrack, LKVector3::Axis axis1, LKVector3::Axis axis2, bool(*fisout)(TVector3 pos))
void FillTrajectory3D (TGraph2DErrors *graphTrack3D, LKVector3::Axis axis1, LKVector3::Axis axis2, LKVector3::Axis axis3)
void FillTrajectory3D (TGraph2DErrors *graphTrack3D, LKVector3::Axis axis1, LKVector3::Axis axis2, LKVector3::Axis axis3, bool(*fisout)(TVector3 pos))
virtual void FinalizeHits ()
virtual bool Fit ()
virtual LKGeoHelix FitHelix (LKVector3::Axis ref)
virtual LKGeoLine FitLine ()
virtual LKGeoPlane FitPlane ()
virtual TVector3 GetCenter () const
double GetChargeSum () const
TVector3 GetCrossingPoint (LKGeoPlaneWithCenter plane2) const
LKTracklet::LKFitStatus GetFitStatus () const
TString GetFitStatusString () const
TGraph2D * GetGraphXYZ ()
TGraph2D * GetGraphZXY ()
LKHit * GetHit (int idx) const
LKHitArray * GetHitArray ()
int GetHitID (int idx) const
std::vector< int > * GetHitIDArray ()
TVector3 GetMean () const
int GetNumHits () const
int GetParentID () const
int GetPDG () const
TVector3 GetPoint1 () const
TVector3 GetPoint2 () const
TVector3 GetPointAtT (double t) const
TVector3 GetPointAtX (double x) const
TVector3 GetPointAtY (double y) const
TVector3 GetPointAtZ (double z) const
Double_t GetQuality ()
Double_t GetRMS () const
Double_t GetT () const
int GetTrackID () const
Double_t GetX1 () const
Double_t GetX2 () const
Double_t GetY1 () const
Double_t GetY2 () const
Double_t GetZ1 () const
Double_t GetZ2 () const
bool IsBad () const
bool IsGenfitTrack () const
bool IsHelix () const
bool IsHoldingHits ()
bool IsLine () const
bool IsPlane () const
Double_t Length () const
Double_t Length (Double_t x, Double_t y, Double_t z) const
Double_t Length (TVector3 position) const
virtual Double_t LengthAt (TVector3 point) const
Length at POCA from point, where tail=0, head=TrackLength.
LKLinearTrack ()
LKLinearTrack (Double_t x1, Double_t y1, Double_t z1, Double_t x2, Double_t y2, Double_t z2)
LKLinearTrack (LKLinearTrack *track1, TString planeAxes1, LKLinearTrack *track2, TString planeAxes2)
LKLinearTrack (TVector3 pos1, TVector3 pos2)
virtual TVector3 Momentum (double B=0.5) const =0
Momentum of track at head.
virtual TVector3 Momentum (Double_t B=0.5) const
virtual TVector3 PositionAtHead () const
Position at head of helix.
virtual TVector3 PositionAtTail () const
Position at tail of helix.
virtual void Print (Option_t *option="") const
virtual TGraph * ProjectionOnPlane (axis_t axis1, axis_t axis2, Double_t scale=1)
virtual int RecoverHitArrayWithHitID (TClonesArray *hitArray)
virtual int RecoverHitArrayWithTrackID (TClonesArray *hitArray)
virtual void RemoveHit (LKHit *hit)
void SetFitStatus (LKFitStatus value)
void SetIsBad ()
void SetIsGenfitTrack ()
void SetIsHelix ()
void SetIsLine ()
void SetIsPlane ()
virtual void SetLine (Double_t x1, Double_t y1, Double_t z1, Double_t x2, Double_t y2, Double_t z2)
virtual void SetLine (LKGeoLine *line)
virtual void SetLine (TVector3 pos1, TVector3 pos2)
void SetParentID (int val)
void SetPDG (int val)
void SetQuality (Double_t val)
bool SetRange (LKGeoBox *box)
void SetRMS (Double_t val)
void SetTrack (TVector3 pos1, TVector3 pos2)
void SetTrackID (int val)
virtual void SortHits (bool increasing=true)
virtual Double_t TrackLength () const
Length of track calculated from head to tail.
virtual TGraphErrors * TrajectoryOnPlane (LKDetectorPlane *plane, double scale=1)
virtual TGraphErrors * TrajectoryOnPlane (LKVector3::Axis axis1, LKVector3::Axis axis2, bool(*fisout)(TVector3 pos), double scale=1)
virtual TGraphErrors * TrajectoryOnPlane (LKVector3::Axis axis1, LKVector3::Axis axis2, double scale=1)
virtual ~LKLinearTrack ()
Protected Attributes
LKFitStatus fFitStatus
One of kBad, kHelix and kLine.
Double_t fHeight = -1
LKHitArray fHitArray
vector< int > fHitIDArray
int fParentID = -1
Vertex ID.
int fPDG = -1
TVector3 fPerpDirectionInPlane
Double_t fQuality = -1
Double_t fRMS = -1
int fTrackID = -1
TGraphErrors * fTrajectoryOnPlane = nullptr
Double_t fWidth = -1
Double_t fX1 = 0
Double_t fX2 = 0
Double_t fY1 = 0
Double_t fY2 = 0
Double_t fZ1 = 0
Double_t fZ2 = 0
Detailed Description
Definition at line 9 of file LKLinearTrack.h.
Member Enumeration Documentation
LKFitStatus
enum LKTracklet::LKFitStatus : int inherited
Enumerator
kNone
kBad
kLine
kPlane
kHelix
kGenfitTrack
Definition at line 19 of file LKTracklet.h.
Constructor & Destructor Documentation
LKLinearTrack() [1/4]
LKLinearTrack::LKLinearTrack ()
LKLinearTrack() [2/4]
LKLinearTrack::LKLinearTrack (Double_t x1, Double_t y1, Double_t z1, Double_t x2, Double_t y2, Double_t z2)
Definition at line 12 of file LKLinearTrack.cpp.
LKLinearTrack() [3/4]
LKLinearTrack::LKLinearTrack (TVector3 pos1, TVector3 pos2)
Definition at line 17 of file LKLinearTrack.cpp.
LKLinearTrack() [4/4]
LKLinearTrack::LKLinearTrack (LKLinearTrack * track1, TString planeAxes1, LKLinearTrack * track2, TString planeAxes2)
Create 3-dimensionl linear track from two 2-dimensional linear tracks which lie in one of planes. planeAxes1 and planeAxes2 should be one of xy, yz, zx, yx, zy, xz
Definition at line 22 of file LKLinearTrack.cpp.
References Create3DTrack().
~LKLinearTrack()
virtual LKLinearTrack::~LKLinearTrack () inline virtual
Definition at line 19 of file LKLinearTrack.h.
Member Function Documentation
AddHit()
void LKTracklet::AddHit (LKHit * hit) virtual inherited
Definition at line 42 of file LKTracklet.cpp.
References LKHitArray::AddHit(), LKTracklet::fHitArray, LKTracklet::fHitIDArray, LKTracklet::fTrackID, LKHit::GetHitID(), and LKTracklet::SetTrackID().
Clear()
void LKLinearTrack::Clear (Option_t * option = "") virtual
Reimplemented from LKTracklet.
Definition at line 249 of file LKLinearTrack.cpp.
References LKTracklet::Clear(), fHeight, fPerpDirectionInPlane, fQuality, fWidth, LKGeoLine::fX1, LKGeoLine::fX2, LKGeoLine::fY1, LKGeoLine::fY2, LKGeoLine::fZ1, and LKGeoLine::fZ2.
ClearHits()
void LKTracklet::ClearHits () virtual inherited
Definition at line 36 of file LKTracklet.cpp.
References LKHitArray::Clear(), LKTracklet::fHitArray, and LKTracklet::fHitIDArray.
ClosestPointOnLine() [1/2]
void LKGeoLine::ClosestPointOnLine (Double_t x, Double_t y, Double_t z, Double_t & x0, Double_t & y0, Double_t & z0) const inherited
Definition at line 116 of file LKGeoLine.cpp.
References LKGeoLine::ClosestPointOnLine(), x0, y0, and z0.
Referenced by LKGeoLine::ClosestPointOnLine(), LKGeoLine::DistanceToLine(), LKGeoLine::DistanceToLine(), ExtrapolateTo(), LKExtrapolatedTrack::ExtrapolateTo(), Fit(), and SetLine().
ClosestPointOnLine() [2/2]
TVector3 LKGeoLine::ClosestPointOnLine (TVector3 pos) const inherited
Definition at line 125 of file LKGeoLine.cpp.
References LKGeoLine::Direction(), LKGeoLine::fX1, LKGeoLine::fY1, and LKGeoLine::fZ1.
Continuity() [1/2]
double LKTracklet::Continuity (double & totalLength, double & continuousLength, double distCut = 25) virtual inherited
Check continuity of the track. Hit array must be filled. Returns ratio of the continuous region. (-1 if less than 2 hits)
If difference between "length from hits" is smaller than distCut, (> pad-diagonal, < 2*pad-row) the region is considered to be connected.
The total length calculation is different from TrackLength(), because TrackLength() use only the head/tail alpha angle information but this method calculate length directly from the hit using Map(...) method.
Parameters
continuousLength calculated length of continuos region.
totalLength calculated total length of the track.
Reimplemented in LKHelixTrack.
Definition at line 214 of file LKTracklet.cpp.
References LKTracklet::fHitArray, LKHitArray::GetHit(), LKHitArray::GetNumHits(), LKHit::GetPosition(), and LKTracklet::SortHits().
Continuity() [2/2]
virtual double LKTracklet::Continuity (double distCut = 25) inline virtual inherited
Definition at line 164 of file LKTracklet.h.
References LKTracklet::Continuity().
Referenced by LKTracklet::Continuity().
Copy()
void LKContainer::Copy (TObject & object) const virtual inherited
Reimplemented in LKChannel, LKHoughPointRT, LKImagePoint, LKEventHeader, LKMCTagged, LKHit, LKVertex, LKWPoint, GETChannel, LKHelixTrack, LKImagePoint, TTBeamHeader, TTChannelCalibrationData, and TTEventHeader.
Definition at line 16 of file LKContainer.cpp.
Referenced by LKChannel::Copy(), LKHoughPointRT::Copy(), LKImagePoint::Copy(), LKEventHeader::Copy(), LKMCTagged::Copy(), LKHit::Copy(), LKWPoint::Copy(), TTBeamHeader::Copy(), TTChannelCalibrationData::Copy(), and TTEventHeader::Copy().
CopyFrom()
void LKLinearTrack::CopyFrom (LKLinearTrack * track)
Definition at line 27 of file LKLinearTrack.cpp.
References LKHitArray::AddHit(), LKTracklet::fHitArray, LKTracklet::fHitIDArray, LKTracklet::fParentID, LKTracklet::fPDG, fQuality, LKTracklet::fTrackID, LKGeoLine::fX1, LKGeoLine::fX2, LKGeoLine::fY1, LKGeoLine::fY2, LKGeoLine::fZ1, LKGeoLine::fZ2, LKTracklet::GetHitArray(), LKTracklet::GetHitIDArray(), LKTracklet::GetParentID(), LKTracklet::GetPDG(), GetQuality(), LKTracklet::GetTrackID(), LKGeoLine::GetX1(), LKGeoLine::GetX2(), LKGeoLine::GetY1(), LKGeoLine::GetY2(), LKGeoLine::GetZ1(), LKGeoLine::GetZ2(), and SetLine().
Create3DTrack()
bool LKLinearTrack::Create3DTrack (LKLinearTrack * track1, TString planeAxes1, LKLinearTrack * track2, TString planeAxes2)
Create and set this track as 3-dimensionl linear track from two 2-dimensional linear tracks which lie in one of planes. planeAxes1 and planeAxes2 should be one of xy, yz, zx, yx, zy, xz Quality will be set -1 if two lines do not make 3-dimentison line. Quality will be set 1 if two lines make 3-dimentison line.
Definition at line 128 of file LKLinearTrack.cpp.
References LKGeoLine::Direction(), fQuality, LKGeoPlaneWithCenter::GetCrossSectionLine(), LKGeoLine::GetPointAtX(), LKGeoLine::GetPointAtY(), LKGeoLine::GetPointAtZ(), LKGeoLine::GetX1(), LKGeoLine::GetX2(), LKVector3::GetXYZ(), LKGeoLine::GetY1(), LKGeoLine::GetY2(), LKVector3::kX, LKVector3::kY, LKVector3::kZ, LKVector3::SetAt(), and SetTrack().
Referenced by LKLinearTrack().
Direction()
TVector3 LKGeoLine::Direction () const inherited
1 to 2
Definition at line 95 of file LKGeoLine.cpp.
References LKGeoLine::fX1, LKGeoLine::fX2, LKGeoLine::fY1, LKGeoLine::fY2, LKGeoLine::fZ1, and LKGeoLine::fZ2.
Referenced by LKGeoLine::ClosestPointOnLine(), Create3DTrack(), LKGeoLine::GetCrossingPoint(), LKGeoLine::GetPointAtT(), LKGeoLine::GetT(), LKGeoPlaneWithCenter::Intersection(), Momentum(), and LKGeoLine::Print().
DistanceToLine() [1/2]
Double_t LKGeoLine::DistanceToLine (Double_t x, Double_t y, Double_t z) const inherited
Definition at line 185 of file LKGeoLine.cpp.
References LKGeoLine::ClosestPointOnLine(), x0, y0, and z0.
DistanceToLine() [2/2]
Double_t LKGeoLine::DistanceToLine (TVector3 pos) const inherited
Definition at line 194 of file LKGeoLine.cpp.
References LKGeoLine::ClosestPointOnLine(), x0, y0, and z0.
DoDrawOnDetectorPlane()
bool LKTracklet::DoDrawOnDetectorPlane () virtual inherited
Definition at line 155 of file LKTracklet.cpp.
DrawArrowXY()
TArrow * LKGeoLine::DrawArrowXY (Double_t asize = 0.02) inherited
Definition at line 213 of file LKGeoLine.cpp.
References LKGeoLine::fX1, LKGeoLine::fX2, LKGeoLine::fY1, and LKGeoLine::fY2.
Referenced by LKVector3::ArrowXY(), and LKHitArray::DrawFitCircle().
DrawArrowXZ()
TArrow * LKGeoLine::DrawArrowXZ (Double_t asize = 0.02) inherited
Definition at line 217 of file LKGeoLine.cpp.
References LKGeoLine::fX1, LKGeoLine::fX2, LKGeoLine::fZ1, and LKGeoLine::fZ2.
DrawArrowYZ()
TArrow * LKGeoLine::DrawArrowYZ (Double_t asize = 0.02) inherited
Definition at line 214 of file LKGeoLine.cpp.
References LKGeoLine::fY1, LKGeoLine::fY2, LKGeoLine::fZ1, and LKGeoLine::fZ2.
Referenced by LKVector3::ArrowYZ().
DrawArrowZX()
TArrow * LKGeoLine::DrawArrowZX (Double_t asize = 0.02) inherited
Definition at line 216 of file LKGeoLine.cpp.
References LKGeoLine::fX1, LKGeoLine::fX2, LKGeoLine::fZ1, and LKGeoLine::fZ2.
Referenced by LKVector3::ArrowZX().
DrawArrowZY()
TArrow * LKGeoLine::DrawArrowZY (Double_t asize = 0.02) inherited
Definition at line 215 of file LKGeoLine.cpp.
References LKGeoLine::fY1, LKGeoLine::fY2, LKGeoLine::fZ1, and LKGeoLine::fZ2.
DrawByDefault()
bool LKTracklet::DrawByDefault () virtual inherited
return true if to be displayed on eve.
Reimplemented from LKContainer.
Definition at line 116 of file LKTracklet.cpp.
ExtrapolateByLength() [1/2]
virtual TVector3 LKTracklet::ExtrapolateByLength (double l) const pure virtual inherited
Extrapolate by length (tail:0), returns extrapolated position.
ExtrapolateByLength() [2/2]
TVector3 LKLinearTrack::ExtrapolateByLength (Double_t l) const virtual
Definition at line 347 of file LKLinearTrack.cpp.
References Momentum(), and PositionAtTail().
ExtrapolateByRatio() [1/2]
virtual TVector3 LKTracklet::ExtrapolateByRatio (double r) const pure virtual inherited
Extrapolate by ratio (tail:0, head:1), returns extrapolated position.
Referenced by LKTracklet::FillTrajectory(), and LKTracklet::FillTrajectory3D().
ExtrapolateByRatio() [2/2]
TVector3 LKLinearTrack::ExtrapolateByRatio (Double_t r) const virtual
Definition at line 338 of file LKLinearTrack.cpp.
References Momentum(), PositionAtTail(), and TrackLength().
ExtrapolateHead() [1/2]
virtual TVector3 LKTracklet::ExtrapolateHead (double l) const pure virtual inherited
Extrapolate head of track about length, returns extrapolated position.
ExtrapolateHead() [2/2]
TVector3 LKLinearTrack::ExtrapolateHead (Double_t l) const virtual
Definition at line 322 of file LKLinearTrack.cpp.
References Momentum(), and PositionAtHead().
ExtrapolateTail() [1/2]
virtual TVector3 LKTracklet::ExtrapolateTail (double l) const pure virtual inherited
Extrapolate tail of track about length, returns extrapolated position.
ExtrapolateTail() [2/2]
TVector3 LKLinearTrack::ExtrapolateTail (Double_t l) const virtual
Definition at line 330 of file LKLinearTrack.cpp.
References Momentum(), and PositionAtTail().
ExtrapolateTo()
TVector3 LKLinearTrack::ExtrapolateTo (TVector3 point) const virtual
Extrapolate to POCA from point, returns extrapolated position.
Implements LKTracklet.
Definition at line 317 of file LKLinearTrack.cpp.
References LKGeoLine::ClosestPointOnLine().
Referenced by LengthAt().
FillTrajectory() [1/2]
void LKTracklet::FillTrajectory (TGraphErrors * graphTrack, LKVector3::Axis axis1, LKVector3::Axis axis2) inherited
Definition at line 193 of file LKTracklet.cpp.
References LKTracklet::FillTrajectory().
FillTrajectory() [2/2]
void LKTracklet::FillTrajectory (TGraphErrors * graphTrack, LKVector3::Axis axis1, LKVector3::Axis axis2, bool(*)(TVector3 pos) fisout) inherited
Definition at line 184 of file LKTracklet.cpp.
References LKTracklet::ExtrapolateByRatio(), LKVector3::kZ, and SetPoint().
Referenced by LKTracklet::FillTrajectory(), and LKTracklet::TrajectoryOnPlane().
FillTrajectory3D() [1/2]
void LKTracklet::FillTrajectory3D (TGraph2DErrors * graphTrack3D, LKVector3::Axis axis1, LKVector3::Axis axis2, LKVector3::Axis axis3) inherited
Definition at line 208 of file LKTracklet.cpp.
References LKTracklet::FillTrajectory3D().
FillTrajectory3D() [2/2]
void LKTracklet::FillTrajectory3D (TGraph2DErrors * graphTrack3D, LKVector3::Axis axis1, LKVector3::Axis axis2, LKVector3::Axis axis3, bool(*)(TVector3 pos) fisout) inherited
Definition at line 199 of file LKTracklet.cpp.
References LKTracklet::ExtrapolateByRatio(), LKVector3::kZ, and SetPoint().
Referenced by LKTracklet::FillTrajectory3D().
FinalizeHits()
void LKTracklet::FinalizeHits () virtual inherited
Definition at line 62 of file LKTracklet.cpp.
References LKTracklet::fHitArray, LKTracklet::fTrackID, next(), and LKTracklet::SetTrackID().
Fit()
bool LKLinearTrack::Fit () virtual
Reimplemented from LKTracklet.
Definition at line 284 of file LKLinearTrack.cpp.
References LKGeoLine::ClosestPointOnLine(), LKTracklet::fHitArray, LKHitArray::FitLine(), LKGeometry::fRMS, LKHitArray::GetHit(), LKHitArray::GetNumHits(), LKGeoLine::Length(), and SetLine().
FitHelix()
LKGeoHelix LKTracklet::FitHelix (LKVector3::Axis ref) virtual inherited
Definition at line 260 of file LKTracklet.cpp.
References LKTracklet::fHitArray, LKHitArray::FitHelix(), LKGeometry::GetRMS(), and LKTracklet::SetIsHelix().
FitLine()
LKGeoLine LKTracklet::FitLine () virtual inherited
Definition at line 244 of file LKTracklet.cpp.
References LKTracklet::fHitArray, LKHitArray::FitLine(), LKGeometry::GetRMS(), and LKTracklet::SetIsLine().
FitPlane()
LKGeoPlane LKTracklet::FitPlane () virtual inherited
Reimplemented in LKHelixTrack.
Definition at line 252 of file LKTracklet.cpp.
References LKTracklet::fHitArray, LKHitArray::FitPlane(), LKGeometry::GetRMS(), and LKTracklet::SetIsPlane().
GetCenter()
TVector3 LKGeoLine::GetCenter () const virtual inherited
Definition at line 31 of file LKGeoLine.cpp.
References LKGeoLine::fX1, LKGeoLine::fX2, LKGeoLine::fY1, LKGeoLine::fY2, LKGeoLine::fZ1, and LKGeoLine::fZ2.
GetChargeSum()
double LKTracklet::GetChargeSum () const inline inherited
Definition at line 90 of file LKTracklet.h.
References LKTracklet::fHitArray, and LKHitArray::GetW().
GetCrossingPoint()
TVector3 LKGeoLine::GetCrossingPoint (LKGeoPlaneWithCenter plane2) const inherited
Definition at line 79 of file LKGeoLine.cpp.
References LKGeoLine::Direction(), LKGeoPlane::GetD(), LKGeoPlane::GetNormal(), LKGeoLine::GetPoint1(), and LKGeoLine::GetPointAtT().
Referenced by LKGeoLine::GetPointAtX(), LKGeoLine::GetPointAtY(), and LKGeoLine::GetPointAtZ().
GetFitStatus()
LKTracklet::LKFitStatus LKTracklet::GetFitStatus () const inline inherited
Definition at line 35 of file LKTracklet.h.
References LKTracklet::fFitStatus.
GetFitStatusString()
TString LKTracklet::GetFitStatusString () const inline inherited
Definition at line 42 of file LKTracklet.h.
References LKTracklet::fFitStatus, LKTracklet::kBad, LKTracklet::kGenfitTrack, LKTracklet::kHelix, LKTracklet::kLine, and LKTracklet::kPlane.
Referenced by LKHelixTrack::Print().
GetGraphXYZ()
TGraph2D * LKGeoLine::GetGraphXYZ () inherited
Definition at line 219 of file LKGeoLine.cpp.
References LKGeoLine::fX1, LKGeoLine::fX2, LKGeoLine::fY1, LKGeoLine::fY2, LKGeoLine::fZ1, LKGeoLine::fZ2, and SetPoint().
GetGraphZXY()
TGraph2D * LKGeoLine::GetGraphZXY () inherited
Definition at line 227 of file LKGeoLine.cpp.
References LKGeoLine::fX1, LKGeoLine::fX2, LKGeoLine::fY1, LKGeoLine::fY2, LKGeoLine::fZ1, LKGeoLine::fZ2, and SetPoint().
Referenced by DrawEvent().
GetHit()
LKHit * LKTracklet::GetHit (int idx) const inline inherited
Definition at line 84 of file LKTracklet.h.
References LKTracklet::fHitArray, and LKHitArray::GetHit().
GetHitArray()
LKHitArray * LKTracklet::GetHitArray () inline inherited
Definition at line 86 of file LKTracklet.h.
References LKTracklet::fHitArray.
Referenced by CopyFrom(), TTHTTrackingTask::MakeTrack(), and TTHTtBeamTrackingTask::MakeTrack().
GetHitID()
int LKTracklet::GetHitID (int idx) const inline inherited
Definition at line 85 of file LKTracklet.h.
References LKTracklet::fHitIDArray.
Referenced by LKTracklet::RecoverHitArrayWithHitID(), and LKTracklet::RemoveHit().
GetHitIDArray()
std::vector< int > * LKTracklet::GetHitIDArray () inline inherited
Definition at line 87 of file LKTracklet.h.
References LKTracklet::fHitIDArray.
Referenced by CopyFrom().
GetMean()
TVector3 LKTracklet::GetMean () const inline inherited
Definition at line 89 of file LKTracklet.h.
References LKTracklet::fHitArray, and LKHitArray::GetMean().
GetNumHits()
int LKTracklet::GetNumHits () const inline inherited
Definition at line 83 of file LKTracklet.h.
References LKTracklet::fHitIDArray.
Referenced by Print().
GetParentID()
int LKTracklet::GetParentID () const inline inherited
Definition at line 80 of file LKTracklet.h.
References LKTracklet::fParentID.
Referenced by CopyFrom(), and LKEveTask::SelectTrack().
GetPDG()
int LKTracklet::GetPDG () const inline inherited
Definition at line 81 of file LKTracklet.h.
References LKTracklet::fPDG.
Referenced by CopyFrom(), and LKEveTask::SelectTrack().
GetPoint1()
TVector3 LKGeoLine::GetPoint1 () const inherited
Definition at line 76 of file LKGeoLine.cpp.
References LKGeoLine::fX1, LKGeoLine::fY1, and LKGeoLine::fZ1.
Referenced by LKGeoLine::GetCrossingPoint(), LKGeoPlaneWithCenter::Intersection(), and PositionAtTail().
GetPoint2()
TVector3 LKGeoLine::GetPoint2 () const inherited
Definition at line 77 of file LKGeoLine.cpp.
References LKGeoLine::fX2, LKGeoLine::fY2, and LKGeoLine::fZ2.
Referenced by PositionAtHead().
GetPointAtT()
TVector3 LKGeoLine::GetPointAtT (double t) const inherited
Definition at line 90 of file LKGeoLine.cpp.
References LKGeoLine::Direction(), LKGeoLine::fX1, LKGeoLine::fY1, and LKGeoLine::fZ1.
Referenced by LKGeoLine::GetCrossingPoint().
GetPointAtX()
TVector3 LKGeoLine::GetPointAtX (double x) const inherited
Definition at line 87 of file LKGeoLine.cpp.
References LKGeoLine::GetCrossingPoint().
Referenced by Create3DTrack(), DrawEvent(), and httask::MakeTrack().
GetPointAtY()
TVector3 LKGeoLine::GetPointAtY (double y) const inherited
Definition at line 88 of file LKGeoLine.cpp.
References LKGeoLine::GetCrossingPoint().
Referenced by Create3DTrack().
GetPointAtZ()
TVector3 LKGeoLine::GetPointAtZ (double z) const inherited
Definition at line 89 of file LKGeoLine.cpp.
References LKGeoLine::GetCrossingPoint().
Referenced by Create3DTrack(), and TTHTtBeamTrackingTask::MakeTrack().
GetQuality()
Double_t LKLinearTrack::GetQuality ()
Definition at line 364 of file LKLinearTrack.cpp.
References fQuality.
Referenced by CopyFrom().
GetRMS()
Double_t LKGeometry::GetRMS () const inline inherited
Definition at line 16 of file LKGeometry.h.
References LKGeometry::fRMS.
Referenced by LKTracklet::FitHelix(), LKTracklet::FitLine(), and LKTracklet::FitPlane().
GetT()
Double_t LKGeoLine::GetT () const inherited
Definition at line 69 of file LKGeoLine.cpp.
References LKGeoLine::Direction(), LKGeoLine::fX1, LKGeoLine::fX2, LKGeoLine::fY1, LKGeoLine::fY2, LKGeoLine::fZ1, and LKGeoLine::fZ2.
GetTrackID()
int LKTracklet::GetTrackID () const inline inherited
Definition at line 79 of file LKTracklet.h.
References LKTracklet::fTrackID.
Referenced by LKVertex::AddTrack(), CopyFrom(), and LKEveTask::SelectTrack().
GetX1()
Double_t LKGeoLine::GetX1 () const inherited
Definition at line 63 of file LKGeoLine.cpp.
References LKGeoLine::fX1.
Referenced by CopyFrom(), Create3DTrack(), and LKGeoLine::SetLine().
GetX2()
Double_t LKGeoLine::GetX2 () const inherited
Definition at line 66 of file LKGeoLine.cpp.
References LKGeoLine::fX2.
Referenced by CopyFrom(), Create3DTrack(), and LKGeoLine::SetLine().
GetY1()
Double_t LKGeoLine::GetY1 () const inherited
Definition at line 64 of file LKGeoLine.cpp.
References LKGeoLine::fY1.
Referenced by CopyFrom(), Create3DTrack(), and LKGeoLine::SetLine().
GetY2()
Double_t LKGeoLine::GetY2 () const inherited
Definition at line 67 of file LKGeoLine.cpp.
References LKGeoLine::fY2.
Referenced by CopyFrom(), Create3DTrack(), and LKGeoLine::SetLine().
GetZ1()
Double_t LKGeoLine::GetZ1 () const inherited
Definition at line 65 of file LKGeoLine.cpp.
References LKGeoLine::fZ1.
Referenced by CopyFrom(), and LKGeoLine::SetLine().
GetZ2()
Double_t LKGeoLine::GetZ2 () const inherited
Definition at line 68 of file LKGeoLine.cpp.
References LKGeoLine::fZ2.
Referenced by CopyFrom(), and LKGeoLine::SetLine().
IsBad()
bool LKTracklet::IsBad () const inline inherited
Definition at line 36 of file LKTracklet.h.
References LKTracklet::fFitStatus, and LKTracklet::kBad.
IsGenfitTrack()
bool LKTracklet::IsGenfitTrack () const inline inherited
Definition at line 40 of file LKTracklet.h.
References LKTracklet::fFitStatus, and LKTracklet::kGenfitTrack.
Referenced by LKHelixTrack::Momentum().
IsHelix()
bool LKTracklet::IsHelix () const inline inherited
Definition at line 39 of file LKTracklet.h.
References LKTracklet::fFitStatus, and LKTracklet::kHelix.
Referenced by LKHelixTrack::Momentum().
IsHoldingHits()
bool LKTracklet::IsHoldingHits () inherited
Definition at line 107 of file LKTracklet.cpp.
References LKTracklet::fHitArray, LKTracklet::fHitIDArray, and LKHitArray::GetNumHits().
IsLine()
bool LKTracklet::IsLine () const inline inherited
Definition at line 37 of file LKTracklet.h.
References LKTracklet::fFitStatus, and LKTracklet::kLine.
IsPlane()
bool LKTracklet::IsPlane () const inline inherited
Definition at line 38 of file LKTracklet.h.
References LKTracklet::fFitStatus, and LKTracklet::kPlane.
Length() [1/3]
Double_t LKGeoLine::Length () const inherited
Definition at line 114 of file LKGeoLine.cpp.
References LKGeoLine::fX1, LKGeoLine::fX2, LKGeoLine::fY1, LKGeoLine::fY2, LKGeoLine::fZ1, and LKGeoLine::fZ2.
Referenced by Fit(), LKGeoLine::Length(), SetLine(), and TrackLength().
Length() [2/3]
Double_t LKGeoLine::Length (Double_t x, Double_t y, Double_t z) const inherited
Definition at line 101 of file LKGeoLine.cpp.
References LKGeoLine::fX1, LKGeoLine::fX2, LKGeoLine::fY1, LKGeoLine::fY2, LKGeoLine::fZ1, and LKGeoLine::fZ2.
Length() [3/3]
Double_t LKGeoLine::Length (TVector3 position) const inherited
Definition at line 113 of file LKGeoLine.cpp.
References LKGeoLine::Length().
LengthAt()
Double_t LKLinearTrack::LengthAt (TVector3 point) const virtual
Length at POCA from point, where tail=0, head=TrackLength.
Implements LKTracklet.
Definition at line 355 of file LKLinearTrack.cpp.
References ExtrapolateTo(), and PositionAtTail().
Momentum() [1/2]
virtual TVector3 LKTracklet::Momentum (double B = 0.5) const pure virtual inherited
Momentum of track at head.
Momentum() [2/2]
TVector3 LKLinearTrack::Momentum (Double_t B = 0.5) const virtual
Definition at line 312 of file LKLinearTrack.cpp.
References LKGeoLine::Direction().
Referenced by ExtrapolateByLength(), ExtrapolateByRatio(), ExtrapolateHead(), and ExtrapolateTail().
PositionAtHead()
TVector3 LKLinearTrack::PositionAtHead () const virtual
Position at head of helix.
Implements LKTracklet.
Definition at line 313 of file LKLinearTrack.cpp.
References LKGeoLine::GetPoint2().
Referenced by ExtrapolateHead().
PositionAtTail()
TVector3 LKLinearTrack::PositionAtTail () const virtual
Position at tail of helix.
Implements LKTracklet.
Definition at line 314 of file LKLinearTrack.cpp.
References LKGeoLine::GetPoint1().
Referenced by ExtrapolateByLength(), ExtrapolateByRatio(), ExtrapolateTail(), and LengthAt().
Print()
void LKLinearTrack::Print (Option_t * option = "") const virtual
Definition at line 266 of file LKLinearTrack.cpp.
References e_info, LKTracklet::fHitArray, LKTracklet::fHitIDArray, LKTracklet::fTrackID, LKGeoLine::fX1, LKGeoLine::fX2, LKGeoLine::fY1, LKGeoLine::fY2, LKGeoLine::fZ1, LKGeoLine::fZ2, LKHitArray::GetNumHits(), and LKTracklet::GetNumHits().
ProjectionOnPlane()
TGraph * LKLinearTrack::ProjectionOnPlane (axis_t axis1, axis_t axis2, Double_t scale = 1) virtual
Definition at line 390 of file LKLinearTrack.cpp.
References LKVector3::At(), fPerpDirectionInPlane, fWidth, LKGeoLine::fX1, LKGeoLine::fX2, LKGeoLine::fY1, LKGeoLine::fY2, LKGeoLine::fZ1, LKGeoLine::fZ2, and SetPoint().
RecoverHitArrayWithHitID()
int LKTracklet::RecoverHitArrayWithHitID (TClonesArray * hitArray) virtual inherited
Be cautious on using this method! This method assumes that hit array was used to create track in same run and event This method will recover hit-array of track, which is removed before end of LILAK run. The track store hit IDs. The method will use this information to recover hit array.
Definition at line 87 of file LKTracklet.cpp.
References LKHitArray::AddHit(), LKTracklet::fHitArray, LKTracklet::fHitIDArray, and LKTracklet::GetHitID().
RecoverHitArrayWithTrackID()
int LKTracklet::RecoverHitArrayWithTrackID (TClonesArray * hitArray) virtual inherited
Be cautious on using this method! This method assumes that hit array and track were cretaed in same run and event This method will recover hit-array of track, which is removed before end of LILAK run. The track ID is set in hit container. The method will use this information to recover hit array.
Definition at line 72 of file LKTracklet.cpp.
References LKHitArray::AddHit(), LKTracklet::fHitArray, and LKTracklet::fTrackID.
RemoveHit()
void LKTracklet::RemoveHit (LKHit * hit) virtual inherited
Definition at line 49 of file LKTracklet.cpp.
References LKTracklet::fHitArray, LKTracklet::fHitIDArray, LKTracklet::GetHitID(), and LKHitArray::RemoveHit().
SetFitStatus()
void LKTracklet::SetFitStatus (LKFitStatus value) inline inherited
Definition at line 28 of file LKTracklet.h.
References LKTracklet::fFitStatus.
SetIsBad()
void LKTracklet::SetIsBad () inline inherited
Definition at line 29 of file LKTracklet.h.
References LKTracklet::fFitStatus, and LKTracklet::kBad.
SetIsGenfitTrack()
void LKTracklet::SetIsGenfitTrack () inline inherited
Definition at line 33 of file LKTracklet.h.
References LKTracklet::fFitStatus, and LKTracklet::kGenfitTrack.
SetIsHelix()
void LKTracklet::SetIsHelix () inline inherited
Definition at line 32 of file LKTracklet.h.
References LKTracklet::fFitStatus, and LKTracklet::kHelix.
Referenced by LKHelixTrack::Fit(), and LKTracklet::FitHelix().
SetIsLine()
void LKTracklet::SetIsLine () inline inherited
Definition at line 30 of file LKTracklet.h.
References LKTracklet::fFitStatus, and LKTracklet::kLine.
Referenced by LKTracklet::FitLine(), and LKHelixTrack::FitPlane().
SetIsPlane()
void LKTracklet::SetIsPlane () inline inherited
Definition at line 31 of file LKTracklet.h.
References LKTracklet::fFitStatus, and LKTracklet::kPlane.
Referenced by LKHelixTrack::FitPlane(), and LKTracklet::FitPlane().
SetLine() [1/3]
void LKLinearTrack::SetLine (Double_t x1, Double_t y1, Double_t z1, Double_t x2, Double_t y2, Double_t z2) virtual
Reimplemented from LKGeoLine.
Definition at line 52 of file LKLinearTrack.cpp.
References LKGeoLine::ClosestPointOnLine(), fHeight, LKTracklet::fHitArray, fPerpDirectionInPlane, fWidth, LKGeoLine::fX1, LKGeoLine::fX2, LKGeoLine::fY1, LKGeoLine::fY2, LKGeoLine::fZ1, LKGeoLine::fZ2, LKHitArray::GetHit(), LKHitArray::GetNumHits(), LKGeoLine::Length(), y2, z1, and z2.
Referenced by CopyFrom(), Fit(), and SetLine().
SetLine() [2/3]
void LKLinearTrack::SetLine (LKGeoLine * line) virtual
Reimplemented from LKGeoLine.
Definition at line 123 of file LKLinearTrack.cpp.
References LKGeoLine::SetLine().
SetLine() [3/3]
void LKLinearTrack::SetLine (TVector3 pos1, TVector3 pos2) virtual
Reimplemented from LKGeoLine.
Definition at line 113 of file LKLinearTrack.cpp.
References SetLine().
SetParentID()
void LKTracklet::SetParentID (int val) inline inherited
Definition at line 76 of file LKTracklet.h.
References LKTracklet::fParentID.
SetPDG()
void LKTracklet::SetPDG (int val) inline inherited
Definition at line 77 of file LKTracklet.h.
References LKTracklet::fPDG.
SetQuality()
void LKLinearTrack::SetQuality (Double_t val)
Definition at line 363 of file LKLinearTrack.cpp.
References fQuality.
SetRange()
bool LKGeoLine::SetRange (LKGeoBox * box) inherited
Definition at line 203 of file LKGeoLine.cpp.
References LKGeoLine::fX1, LKGeoLine::fX2, LKGeoLine::fY1, LKGeoLine::fY2, LKGeoLine::fZ1, LKGeoLine::fZ2, and LKGeoLine::SetLine().
SetRMS()
void LKGeometry::SetRMS (Double_t val) inline inherited
Definition at line 15 of file LKGeometry.h.
References LKGeometry::fRMS.
Referenced by LKHitArray::DrawFitCircle(), LKHelixTrack::Fit(), LKHitArray::FitCircle(), LKHitArray::FitHelix(), LKHitArray::FitLine(), LKHitArray::FitPlane(), and LKHelixTrack::FitPlane().
SetTrack()
void LKLinearTrack::SetTrack (TVector3 pos1, TVector3 pos2)
Definition at line 118 of file LKLinearTrack.cpp.
References LKGeoLine::SetLine().
Referenced by Create3DTrack().
SetTrackID()
void LKTracklet::SetTrackID (int val) inline inherited
Definition at line 75 of file LKTracklet.h.
References LKTracklet::fTrackID.
Referenced by LKTracklet::AddHit(), and LKTracklet::FinalizeHits().
SortHits()
void LKTracklet::SortHits (bool increasing = true) virtual inherited
Reimplemented in LKHelixTrack.
Definition at line 268 of file LKTracklet.cpp.
References LKTracklet::fHitArray, LKHit::GetPosition(), and next().
Referenced by LKTracklet::Continuity().
TrackLength()
Double_t LKLinearTrack::TrackLength () const virtual
Length of track calculated from head to tail.
Implements LKTracklet.
Definition at line 315 of file LKLinearTrack.cpp.
References LKGeoLine::Length().
Referenced by ExtrapolateByRatio().
TrajectoryOnPlane() [1/3]
TGraphErrors * LKTracklet::TrajectoryOnPlane (LKDetectorPlane * plane, double scale = 1) virtual inherited
Definition at line 179 of file LKTracklet.cpp.
References LKDetectorPlane::GetAxis1(), LKDetectorPlane::GetAxis2(), and LKTracklet::TrajectoryOnPlane().
TrajectoryOnPlane() [2/3]
TGraphErrors * LKTracklet::TrajectoryOnPlane (LKVector3::Axis axis1, LKVector3::Axis axis2, bool(*)(TVector3 pos) fisout, double scale = 1) virtual inherited
Definition at line 160 of file LKTracklet.cpp.
References LKTracklet::FillTrajectory(), and LKTracklet::fTrajectoryOnPlane.
Referenced by LKTracklet::TrajectoryOnPlane(), and LKTracklet::TrajectoryOnPlane().
TrajectoryOnPlane() [3/3]
TGraphErrors * LKTracklet::TrajectoryOnPlane (LKVector3::Axis axis1, LKVector3::Axis axis2, double scale = 1) virtual inherited
Definition at line 173 of file LKTracklet.cpp.
References LKTracklet::TrajectoryOnPlane().
Member Data Documentation
fFitStatus
LKFitStatus LKTracklet::fFitStatus protected inherited
One of kBad, kHelix and kLine.
Definition at line 61 of file LKTracklet.h.
Referenced by LKHelixTrack::Clear(), LKHelixTrack::Copy(), LKTracklet::GetFitStatus(), LKTracklet::GetFitStatusString(), LKTracklet::IsBad(), LKTracklet::IsGenfitTrack(), LKTracklet::IsHelix(), LKTracklet::IsLine(), LKTracklet::IsPlane(), LKHelixTrack::Print(), LKTracklet::SetFitStatus(), LKTracklet::SetIsBad(), LKTracklet::SetIsGenfitTrack(), LKTracklet::SetIsHelix(), LKTracklet::SetIsLine(), and LKTracklet::SetIsPlane().
fHeight
Double_t LKLinearTrack::fHeight = -1 protected
Definition at line 64 of file LKLinearTrack.h.
Referenced by Clear(), and SetLine().
fHitArray
LKHitArray LKTracklet::fHitArray protected inherited
Definition at line 56 of file LKTracklet.h.
Referenced by LKTracklet::AddHit(), ClassImp(), LKTracklet::ClearHits(), LKHelixTrack::Continuity(), LKTracklet::Continuity(), LKHelixTrack::Copy(), CopyFrom(), LKTracklet::FinalizeHits(), LKHelixTrack::Fit(), Fit(), LKTracklet::FitHelix(), LKTracklet::FitLine(), LKHelixTrack::FitPlane(), LKTracklet::FitPlane(), LKTracklet::GetChargeSum(), LKTracklet::GetHit(), LKTracklet::GetHitArray(), LKTracklet::GetMean(), LKTracklet::IsHoldingHits(), LKHelixTrack::PerpLine(), LKHelixTrack::PerpPlane(), LKHelixTrack::Print(), Print(), LKTracklet::RecoverHitArrayWithHitID(), LKTracklet::RecoverHitArrayWithTrackID(), LKTracklet::RemoveHit(), SetLine(), LKHelixTrack::SortHits(), and LKTracklet::SortHits().
fHitIDArray
vector<int> LKTracklet::fHitIDArray protected inherited
Definition at line 57 of file LKTracklet.h.
Referenced by LKTracklet::AddHit(), ClassImp(), LKTracklet::ClearHits(), CopyFrom(), LKTracklet::GetHitID(), LKTracklet::GetHitIDArray(), LKTracklet::GetNumHits(), LKTracklet::IsHoldingHits(), Print(), LKTracklet::RecoverHitArrayWithHitID(), and LKTracklet::RemoveHit().
fParentID
int LKTracklet::fParentID = -1 protected inherited
Vertex ID.
Definition at line 53 of file LKTracklet.h.
Referenced by ClassImp(), LKHelixTrack::Copy(), CopyFrom(), LKTracklet::GetParentID(), LKHelixTrack::Print(), LKMCTrack::Print(), LKMCTrack::SetMCTrack(), LKTracklet::SetParentID(), and LKMCTrack::TrajectoryOnPlane().
fPDG
int LKTracklet::fPDG = -1 protected inherited
Definition at line 54 of file LKTracklet.h.
Referenced by ClassImp(), CopyFrom(), LKTracklet::GetPDG(), LKMCTrack::Print(), LKMCTrack::SetMCTrack(), LKTracklet::SetPDG(), and LKMCTrack::TrajectoryOnPlane().
fPerpDirectionInPlane
TVector3 LKLinearTrack::fPerpDirectionInPlane protected
Definition at line 65 of file LKLinearTrack.h.
Referenced by Clear(), ProjectionOnPlane(), and SetLine().
fQuality
Double_t LKLinearTrack::fQuality = -1 protected
Definition at line 62 of file LKLinearTrack.h.
Referenced by Clear(), CopyFrom(), Create3DTrack(), GetQuality(), and SetQuality().
fRMS
Double_t LKGeometry::fRMS = -1 protected inherited
Definition at line 9 of file LKGeometry.h.
Referenced by Fit(), LKGeometry::GetRMS(), and LKGeometry::SetRMS().
fTrackID
int LKTracklet::fTrackID = -1 protected inherited
Definition at line 52 of file LKTracklet.h.
Referenced by LKTracklet::AddHit(), ClassImp(), LKHelixTrack::Copy(), CopyFrom(), LKTracklet::FinalizeHits(), LKTracklet::GetTrackID(), LKHelixTrack::LKHelixTrack(), LKHelixTrack::Print(), Print(), LKMCTrack::Print(), LKTracklet::RecoverHitArrayWithTrackID(), LKMCTrack::SetMCTrack(), and LKTracklet::SetTrackID().
fTrajectoryOnPlane
TGraphErrors* LKTracklet::fTrajectoryOnPlane = nullptr protected inherited
Definition at line 59 of file LKTracklet.h.
Referenced by LKMCTrack::TrajectoryOnPlane(), LKTracklet::TrajectoryOnPlane(), LKExtrapolatedTrack::TrajectoryOnPlane(), and LKExtrapolatedTrack::TrajectoryOnPlane().
fWidth
Double_t LKLinearTrack::fWidth = -1 protected
Definition at line 63 of file LKLinearTrack.h.
Referenced by Clear(), ProjectionOnPlane(), and SetLine().
fX1
Double_t LKGeoLine::fX1 = 0 protected inherited
Definition at line 85 of file LKGeoLine.h.
Referenced by Clear(), LKGeoLine::ClosestPointOnLine(), CopyFrom(), LKGeoLine::Direction(), LKGeoLine::DrawArrowXY(), LKGeoLine::DrawArrowXZ(), LKGeoLine::DrawArrowZX(), LKGeoLine::GetCenter(), LKGeoLine::GetGraphXYZ(), LKGeoLine::GetGraphZXY(), LKGeoLine::GetPoint1(), LKGeoLine::GetPointAtT(), LKGeoLine::GetT(), LKGeoLine::GetX1(), LKGeoLine::Length(), LKGeoLine::Length(), Print(), LKGeoLine::Print(), ProjectionOnPlane(), SetLine(), LKGeoLine::SetLine(), LKGeoLine::SetLine(), LKGeoLine::SetLine(), and LKGeoLine::SetRange().
fX2
Double_t LKGeoLine::fX2 = 0 protected inherited
Definition at line 89 of file LKGeoLine.h.
Referenced by Clear(), CopyFrom(), LKGeoLine::Direction(), LKGeoLine::DrawArrowXY(), LKGeoLine::DrawArrowXZ(), LKGeoLine::DrawArrowZX(), LKGeoLine::GetCenter(), LKGeoLine::GetGraphXYZ(), LKGeoLine::GetGraphZXY(), LKGeoLine::GetPoint2(), LKGeoLine::GetT(), LKGeoLine::GetX2(), LKGeoLine::Length(), LKGeoLine::Length(), Print(), LKGeoLine::Print(), ProjectionOnPlane(), SetLine(), LKGeoLine::SetLine(), LKGeoLine::SetLine(), LKGeoLine::SetLine(), and LKGeoLine::SetRange().
fY1
Double_t LKGeoLine::fY1 = 0 protected inherited
Definition at line 86 of file LKGeoLine.h.
Referenced by Clear(), LKGeoLine::ClosestPointOnLine(), CopyFrom(), LKGeoLine::Direction(), LKGeoLine::DrawArrowXY(), LKGeoLine::DrawArrowYZ(), LKGeoLine::DrawArrowZY(), LKGeoLine::GetCenter(), LKGeoLine::GetGraphXYZ(), LKGeoLine::GetGraphZXY(), LKGeoLine::GetPoint1(), LKGeoLine::GetPointAtT(), LKGeoLine::GetT(), LKGeoLine::GetY1(), LKGeoLine::Length(), LKGeoLine::Length(), Print(), LKGeoLine::Print(), ProjectionOnPlane(), SetLine(), LKGeoLine::SetLine(), LKGeoLine::SetLine(), LKGeoLine::SetLine(), and LKGeoLine::SetRange().
fY2
Double_t LKGeoLine::fY2 = 0 protected inherited
Definition at line 90 of file LKGeoLine.h.
Referenced by Clear(), CopyFrom(), LKGeoLine::Direction(), LKGeoLine::DrawArrowXY(), LKGeoLine::DrawArrowYZ(), LKGeoLine::DrawArrowZY(), LKGeoLine::GetCenter(), LKGeoLine::GetGraphXYZ(), LKGeoLine::GetGraphZXY(), LKGeoLine::GetPoint2(), LKGeoLine::GetT(), LKGeoLine::GetY2(), LKGeoLine::Length(), LKGeoLine::Length(), Print(), LKGeoLine::Print(), ProjectionOnPlane(), SetLine(), LKGeoLine::SetLine(), LKGeoLine::SetLine(), LKGeoLine::SetLine(), and LKGeoLine::SetRange().
fZ1
Double_t LKGeoLine::fZ1 = 0 protected inherited
Definition at line 87 of file LKGeoLine.h.
Referenced by Clear(), LKGeoLine::ClosestPointOnLine(), CopyFrom(), LKGeoLine::Direction(), LKGeoLine::DrawArrowXZ(), LKGeoLine::DrawArrowYZ(), LKGeoLine::DrawArrowZX(), LKGeoLine::DrawArrowZY(), LKGeoLine::GetCenter(), LKGeoLine::GetGraphXYZ(), LKGeoLine::GetGraphZXY(), LKGeoLine::GetPoint1(), LKGeoLine::GetPointAtT(), LKGeoLine::GetT(), LKGeoLine::GetZ1(), LKGeoLine::Length(), LKGeoLine::Length(), Print(), LKGeoLine::Print(), ProjectionOnPlane(), SetLine(), LKGeoLine::SetLine(), LKGeoLine::SetLine(), LKGeoLine::SetLine(), and LKGeoLine::SetRange().
fZ2
Double_t LKGeoLine::fZ2 = 0 protected inherited
Definition at line 91 of file LKGeoLine.h.
Referenced by Clear(), CopyFrom(), LKGeoLine::Direction(), LKGeoLine::DrawArrowXZ(), LKGeoLine::DrawArrowYZ(), LKGeoLine::DrawArrowZX(), LKGeoLine::DrawArrowZY(), LKGeoLine::GetCenter(), LKGeoLine::GetGraphXYZ(), LKGeoLine::GetGraphZXY(), LKGeoLine::GetPoint2(), LKGeoLine::GetT(), LKGeoLine::GetZ2(), LKGeoLine::Length(), LKGeoLine::Length(), Print(), LKGeoLine::Print(), ProjectionOnPlane(), SetLine(), LKGeoLine::SetLine(), LKGeoLine::SetLine(), LKGeoLine::SetLine(), and LKGeoLine::SetRange().
The documentation for this class was generated from the following files:
LKLinearTrack.h
LKLinearTrack.cpp