lilak: LKBufferD Class Reference
LKBufferD Class Reference
#include <LKBufferD.h>
Public Member Functions
double CalculateGroupFluctuation (int numGroups=8, int tb2=512)
Divide 0-tb2 into numGroups. Calculate std-dev of group means.
void Clear (Option_t *option="")
void Copy (TObject &object) const
void Draw (Option_t *option="")
void Fill (int tb, double value)
virtual void FillGraph (TGraph *graph)
virtual void FillHist (TH1 *hist)
double * GetArray ()
virtual TGraph * GetGraph ()
void GetGroupMeanStdDev (int numGroups, int tb2, double *pedestalGroup, double *stddevGroup)
Divide 0-tb2 into numGroups. Evaluate pedestal(mean) and std-dev of each group.
virtual TH1D * GetHist (TString name="")
double GetScale (double *buffer)
return [scale] where [scale] is fit parameter of fArray = [scale] x buffer.
double GetScale (int *buffer)
return [scale] where [scale] is fit parameter of fArray = [scale] x buffer.
bool IsEmpty () const
LKBufferD ()
void Print (Option_t *option="") const
void SetArray (const double *buffer)
void SetArray (const int *buffer)
void SetArray (const unsigned int *buffer)
void SetArray (std::vector< unsigned int > buffer)
void SetBuffer (LKBufferD buffer)
void SubtractArray (double *buffer)
void SubtractArray (double *buffer, double scale)
void SubtractArray (int *buffer)
void SubtractArray (int *buffer, double scale)
virtual ~LKBufferD ()
Protected Member Functions
ClassDef (LKBufferD, 1)
Protected Attributes
double fArray [512]
bool fEmpty = true
TGraph * fGraph = nullptr
TH1D * fHist = nullptr
Detailed Description
Definition at line 8 of file LKBufferD.h.
Constructor & Destructor Documentation
LKBufferD()
LKBufferD::LKBufferD ()
Definition at line 6 of file LKBufferD.cpp.
References Clear().
~LKBufferD()
virtual LKBufferD::~LKBufferD () inline virtual
Definition at line 12 of file LKBufferD.h.
Member Function Documentation
CalculateGroupFluctuation()
double LKBufferD::CalculateGroupFluctuation (int numGroups = 8, int tb2 = 512)
Divide 0-tb2 into numGroups. Calculate std-dev of group means.
Definition at line 106 of file LKBufferD.cpp.
References GetGroupMeanStdDev().
ClassDef()
LKBufferD::ClassDef (LKBufferD , 1) protected
Clear()
void LKBufferD::Clear (Option_t * option = "")
Definition at line 11 of file LKBufferD.cpp.
References fArray, and fEmpty.
Referenced by ClassImp(), and LKBufferD().
Copy()
void LKBufferD::Copy (TObject & object) const
Definition at line 17 of file LKBufferD.cpp.
References fArray.
Draw()
void LKBufferD::Draw (Option_t * option = "")
Definition at line 35 of file LKBufferD.cpp.
References Draw(), and GetHist().
Referenced by Draw().
Fill()
void LKBufferD::Fill (int tb, double value) inline
Definition at line 32 of file LKBufferD.h.
References fArray.
FillGraph()
void LKBufferD::FillGraph (TGraph * graph) virtual
Definition at line 65 of file LKBufferD.cpp.
References fArray, and SetPoint().
Referenced by GetGraph().
FillHist()
void LKBufferD::FillHist (TH1 * hist) virtual
Definition at line 50 of file LKBufferD.cpp.
References fArray.
Referenced by GetHist(), and LKPad::SetHist().
GetArray()
double * LKBufferD::GetArray () inline
Definition at line 34 of file LKBufferD.h.
References fArray.
Referenced by LKPad::GetArrayShaped(), and SetBuffer().
GetGraph()
TGraph * LKBufferD::GetGraph () virtual
Definition at line 56 of file LKBufferD.cpp.
References fGraph, and FillGraph().
GetGroupMeanStdDev()
void LKBufferD::GetGroupMeanStdDev (int numGroups, int tb2, double * pedestalGroup, double * stddevGroup)
Divide 0-tb2 into numGroups. Evaluate pedestal(mean) and std-dev of each group.
Definition at line 125 of file LKBufferD.cpp.
References fArray.
Referenced by CalculateGroupFluctuation().
GetHist()
TH1D * LKBufferD::GetHist (TString name = "") virtual
Definition at line 40 of file LKBufferD.cpp.
References fHist, and FillHist().
Referenced by Draw().
GetScale() [1/2]
double LKBufferD::GetScale (double * buffer)
return [scale] where [scale] is fit parameter of fArray = [scale] x buffer.
Definition at line 92 of file LKBufferD.cpp.
References fArray.
GetScale() [2/2]
double LKBufferD::GetScale (int * buffer)
return [scale] where [scale] is fit parameter of fArray = [scale] x buffer.
Definition at line 78 of file LKBufferD.cpp.
References fArray.
IsEmpty()
bool LKBufferD::IsEmpty () const inline
Definition at line 23 of file LKBufferD.h.
References fEmpty.
Referenced by SetBuffer().
Print()
void LKBufferD::Print (Option_t * option = "") const
Definition at line 23 of file LKBufferD.cpp.
References e_cout, e_info, fArray, and fEmpty.
Referenced by LKPad::Print().
SetArray() [1/4]
void LKBufferD::SetArray (const double * buffer) inline
Definition at line 28 of file LKBufferD.h.
References fArray, and fEmpty.
SetArray() [2/4]
void LKBufferD::SetArray (const int * buffer) inline
Definition at line 27 of file LKBufferD.h.
References fArray, and fEmpty.
Referenced by LKPad::SetBufferShaped().
SetArray() [3/4]
void LKBufferD::SetArray (const unsigned int * buffer) inline
Definition at line 29 of file LKBufferD.h.
References fArray, and fEmpty.
SetArray() [4/4]
void LKBufferD::SetArray (std::vector< unsigned int > buffer) inline
Definition at line 30 of file LKBufferD.h.
References fArray, and fEmpty.
SetBuffer()
void LKBufferD::SetBuffer (LKBufferD buffer)
Definition at line 72 of file LKBufferD.cpp.
References fArray, fEmpty, GetArray(), and IsEmpty().
Referenced by LKPad::SetBufferShaped().
SubtractArray() [1/4]
void LKBufferD::SubtractArray (double * buffer) inline
Definition at line 37 of file LKBufferD.h.
References fArray.
SubtractArray() [2/4]
void LKBufferD::SubtractArray (double * buffer, double scale) inline
Definition at line 39 of file LKBufferD.h.
References fArray.
SubtractArray() [3/4]
void LKBufferD::SubtractArray (int * buffer) inline
Definition at line 36 of file LKBufferD.h.
References fArray.
SubtractArray() [4/4]
void LKBufferD::SubtractArray (int * buffer, double scale) inline
Definition at line 38 of file LKBufferD.h.
References fArray.
Member Data Documentation
fArray
double LKBufferD::fArray[512] protected
Definition at line 48 of file LKBufferD.h.
Referenced by Clear(), Copy(), Fill(), FillGraph(), FillHist(), GetArray(), GetGroupMeanStdDev(), GetScale(), GetScale(), Print(), SetArray(), SetArray(), SetArray(), SetArray(), SetBuffer(), SubtractArray(), SubtractArray(), SubtractArray(), and SubtractArray().
fEmpty
bool LKBufferD::fEmpty = true protected
Definition at line 47 of file LKBufferD.h.
Referenced by Clear(), IsEmpty(), Print(), SetArray(), SetArray(), SetArray(), SetArray(), and SetBuffer().
fGraph
TGraph* LKBufferD::fGraph = nullptr protected
Definition at line 51 of file LKBufferD.h.
Referenced by GetGraph().
fHist
TH1D* LKBufferD::fHist = nullptr protected
Definition at line 50 of file LKBufferD.h.
Referenced by GetHist().
The documentation for this class was generated from the following files:
LKBufferD.h
LKBufferD.cpp