lilak: Json::StreamWriterBuilder Class Reference
Json::StreamWriterBuilder Class Reference
Build a StreamWriter implementation.
#include <json.h>
Public Member Functions
StreamWriter * newStreamWriter () const override
Value & operator[] (const String &key)
StreamWriterBuilder ()
bool validate (Json::Value *invalid) const
~StreamWriterBuilder () override
Public Member Functions inherited from Json::StreamWriter::Factory
virtual StreamWriter * newStreamWriter () const =0
Allocate a CharReader via operator new().
virtual ~Factory ()
Static Public Member Functions
static void setDefaults (Json::Value *settings)
Public Attributes
Json::Value settings_
Detailed Description
Build a StreamWriter implementation.
Usage:
using namespace Json;
Value value = ...;
StreamWriterBuilder builder;
builder["commentStyle"] = "None";
builder["indentation"] = "   ";  // or whatever you like
std::unique_ptr<Json::StreamWriter> writer(
   builder.newStreamWriter());
writer->write(value, &std::cout);
std::cout << std::endl;  // add lf and flush
Definition at line 1986 of file json.h.
Constructor & Destructor Documentation
StreamWriterBuilder()
Json::StreamWriterBuilder::StreamWriterBuilder ()
Definition at line 5234 of file jsoncpp.cpp.
References setDefaults(), and settings_.
~StreamWriterBuilder()
Json::StreamWriterBuilder::~StreamWriterBuilder () override default
Member Function Documentation
newStreamWriter()
StreamWriter * Json::StreamWriterBuilder::newStreamWriter () const override virtual
Exceptions
std::exception if something goes wrong (e.g. invalid settings)
Implements Json::StreamWriter::Factory.
Definition at line 5236 of file jsoncpp.cpp.
References Json::CommentStyle::All, Json::Value::asBool(), Json::Value::asString(), Json::Value::asUInt(), Json::decimalPlaces, Json::CommentStyle::None, settings_, Json::significantDigits, and Json::throwRuntimeError().
Referenced by Json::operator<<().
operator[]()
Value & Json::StreamWriterBuilder::operator[] (const String & key)
A simple way to update a specific setting.
Definition at line 5302 of file jsoncpp.cpp.
References settings_.
setDefaults()
void Json::StreamWriterBuilder::setDefaults (Json::Value * settings) static
Called by ctor, but you can use this to reset settings_.
Precondition
'settings' != NULL (but Json::null is fine)
Remarks
Defaults:
[StreamWriterBuilderDefaults]
[StreamWriterBuilderDefaults]
Definition at line 5306 of file jsoncpp.cpp.
Referenced by StreamWriterBuilder().
validate()
bool Json::StreamWriterBuilder::validate (Json::Value * invalid) const
Returns
true if 'settings' are legal and consistent; otherwise, indicate bad settings via 'invalid'.
Definition at line 5279 of file jsoncpp.cpp.
References Json::Value::begin(), Json::Value::empty(), Json::Value::end(), and settings_.
Member Data Documentation
settings_
Json::Value Json::StreamWriterBuilder::settings_
Configuration of this builder. Available settings (case-sensitive):
"commentStyle": "None" or "All"
"indentation": "<anything>".
Setting this to an empty string also omits newline characters.
"enableYAMLCompatibility": false or true
slightly change the whitespace around colons
"dropNullPlaceholders": false or true
Drop the "null" string from the writer's output for nullValues. Strictly speaking, this is not valid JSON. But when the output is being fed to a browser's JavaScript, it makes for smaller output and the browser can handle the output just fine.
"useSpecialFloats": false or true
If true, outputs non-finite floating point values in the following way: NaN values as "NaN", positive infinity as "Infinity", and negative infinity as "-Infinity".
"precision": int
Number of precision digits for formatting of real values.
"precisionType": "significant"(default) or "decimal"
Type of precision for formatting of real values.
"emitUTF8": false or true
If true, outputs raw UTF8 strings instead of escaping them.
You can examine 'settings_` yourself to see the defaults. You can also write and read them just like any JSON Value.
See also
setDefaults()
Definition at line 2018 of file json.h.
Referenced by newStreamWriter(), operator[](), StreamWriterBuilder(), and validate().
The documentation for this class was generated from the following files:
json.h
jsoncpp.cpp