lilak: LKLinearTrackFindingTask Class Reference
LKLinearTrackFindingTask Class Reference
#include <LKLinearTrackFindingTask.h>
Public Types
enum StepNo : int {
kStepInitArray , kStepNewTrack , kStepRemoveTrack , kStepInitTrack ,
kStepInitTrackAddHit , kStepContinuum , kStepContinuumAddHit , kStepExtrapolation ,
kStepExtrapolationAddHit , kStepConfirmation , kStepFinalizeTrack , kStepNextPhase ,
kStepEndEvent , kStepEndOfEvent
}
Public Member Functions
virtual void Exec (Option_t *)
bool ExecStep ()
bool ExecStepUptoTrackNum (int numTracks)
LKLinearTrack * GetCurrentTrack () const
virtual bool Init ()
LKLinearTrackFindingTask ()
void SetHitBranchName (TString name)
void SetTrackletBranchName (TString name)
void SetTrackPersistency (bool val)
virtual ~LKLinearTrackFindingTask ()
Public Member Functions inherited from LKTask
virtual void Add (TTask *task)
virtual void Add (TTask *task)
virtual void AddTriggerInputFile (TString fileName, TString opt)
virtual void AddTriggerInputFile (TString fileName, TString opt)
virtual bool EndOfRun ()
virtual bool EndOfRun ()
bool EndOfRunTask ()
bool EndOfRunTask ()
bool EndOfRunTasks ()
bool EndOfRunTasks ()
virtual bool Init ()
virtual bool Init ()
bool InitTask ()
bool InitTask ()
bool InitTasks ()
bool InitTasks ()
virtual bool IsEventTrigger ()
virtual bool IsEventTrigger ()
LKTask ()
LKTask ()
LKTask (const char *name, const char *title)
LKTask (const char *name, const char *title)
virtual void Run (Long64_t numEvents=-1)
virtual void Run (Long64_t numEvents=-1)
virtual void RunOnline ()
virtual void RunOnline ()
virtual void SetRank (Int_t rank)
virtual void SetRank (Int_t rank)
virtual void SignalNextEvent ()
virtual void SignalNextEvent ()
virtual ~LKTask ()
virtual ~LKTask ()
Public Member Functions inherited from LKGear
void AddPar (LKParameterContainer *par)
void AddPar (TString fname)
virtual void AddParameterContainer (LKParameterContainer *par)
virtual void AddParameterContainer (TString fname)
void CreateParameterContainer ()
LKParameterContainer * GetPar () const
LKParameterContainer * GetParameterContainer () const
Int_t GetRank () const
LKGear ()
void SetAllowControlLogger (bool val)
void SetPar (LKParameterContainer *par)
virtual void SetParameterContainer (LKParameterContainer *par)
virtual void SetRank (Int_t rank)
void SetRun (LKRun *run)
virtual ~LKGear ()
Private Member Functions
bool AutoBuildAtPosition (LKLinearTrack *track, TVector3 p, bool &tailToHead, double &extrapolationLength, double scale=1)
bool AutoBuildByExtrapolation (LKLinearTrack *track, bool &buildHead, double &extrapolationLength)
bool BuildAndConfirmTrack (LKLinearTrack *track, bool &tailToHead)
bool CheckHitDistInAlphaIsLargerThanQuarterPi (LKLinearTrack *track, double dLength)
int CheckParentTrackID (LKHit *hit)
double CheckTrackContinuity (LKLinearTrack *track)
bool CheckTrackQuality (LKLinearTrack *track)
double CorrelateHitWithTrack (LKLinearTrack *track, LKHit *hit, double scale=1)
double CorrelateHitWithTrackCandidate (LKLinearTrack *track, LKHit *hit)
void ReturnBadHitsToPadPlane ()
int StepConfirmation ()
int StepContinuum ()
int StepContinuumAddHit ()
int StepEndEvent ()
int StepExtrapolation ()
int StepExtrapolationAddHit ()
int StepFinalizeTrack ()
int StepInitArray ()
int StepInitTrack ()
int StepInitTrackAddHit ()
int StepNewTrack ()
int StepNextPhase ()
int StepRemoveTrack ()
Private Attributes
LKHitArray * fBadHits = nullptr
TString fBranchNameHit = "Hit"
TString fBranchNameTracklet = "Tracklet"
LKHitArray * fCandHits = nullptr
LKLinearTrack * fCurrentTrack = nullptr
double fCutdkInExpectedTrackPath = 4.
int fCutMaxNumHitsInitTrack = 15
return hits if track has more than this number of hits within initialization stage
int fCutMinNumHitsFinalTrack = 15
remove track if track has smaller than this number of hits within initialization stage
int fCutMinNumHitsInitTrack = 10
TCanvas * fCvsCurrentTrack = nullptr
double fDefaultScale = 2.5
LKHitArray * fGoodHits = nullptr
TGraphErrors * fGraphCurrentTrackPoint = nullptr
TClonesArray * fHitArray = nullptr
int fMinHitsToFitInitTrack = 7
try track fit if track has more than this number of hits in track
int fNextStep = StepNo::kStepInitArray
int fNumBadHits
int fNumCandHits
int fNumGoodHits
LKDetectorPlane * fPadPlane = nullptr
bool fPersistency = true
int fPhaseIndex = 0
LKVector3::Axis fReferenceAxis = LKVector3::kZ
LKDetector * fTpc = nullptr
TClonesArray * fTrackArray = nullptr
double fTrackHCutHL = 15.
Track height cut high limit.
double fTrackHCutLL = 5.
Track height cut low limit.
LKHitArray * fTrackHits = nullptr
double fTrackLengthCut = 10
TODO.
double fTrackLengthCutScale = 2.5
track length cut for initialization stage is [this_var] * track -> GetRMSR()
double fTrackWCutHL = 15.
Track width cut high limit.
double fTrackWCutLL = 5.
Track width cut low limit.
Additional Inherited Members
Protected Attributes inherited from LKTask
vector< TString > fTriggerInputFileNameArray
for event trigger task
Protected Attributes inherited from LKGear
bool fAllowControlLogger = true
LKParameterContainer * fPar = nullptr
Int_t fRank = 0
LKRun * fRun = nullptr
Detailed Description
Definition at line 20 of file LKLinearTrackFindingTask.h.
Member Enumeration Documentation
StepNo
enum LKLinearTrackFindingTask::StepNo : int
Enumerator
kStepInitArray
kStepNewTrack
kStepRemoveTrack
kStepInitTrack
kStepInitTrackAddHit
kStepContinuum
kStepContinuumAddHit
kStepExtrapolation
kStepExtrapolationAddHit
kStepConfirmation
kStepFinalizeTrack
kStepNextPhase
kStepEndEvent
kStepEndOfEvent
Definition at line 31 of file LKLinearTrackFindingTask.h.
Constructor & Destructor Documentation
LKLinearTrackFindingTask()
LKLinearTrackFindingTask::LKLinearTrackFindingTask () inline
Definition at line 23 of file LKLinearTrackFindingTask.h.
~LKLinearTrackFindingTask()
virtual LKLinearTrackFindingTask::~LKLinearTrackFindingTask () inline virtual
Definition at line 24 of file LKLinearTrackFindingTask.h.
Member Function Documentation
AutoBuildAtPosition()
bool LKLinearTrackFindingTask::AutoBuildAtPosition (LKLinearTrack * track, TVector3 p, bool & tailToHead, double & extrapolationLength, double scale = 1) private
Definition at line 539 of file LKLinearTrackFindingTask.cpp.
References CheckParentTrackID(), CorrelateHitWithTrack(), fBadHits, fCandHits, fNumCandHits, fPadPlane, fReferenceAxis, and p2.
Referenced by AutoBuildByExtrapolation().
AutoBuildByExtrapolation()
bool LKLinearTrackFindingTask::AutoBuildByExtrapolation (LKLinearTrack * track, bool & buildHead, double & extrapolationLength) private
Definition at line 527 of file LKLinearTrackFindingTask.cpp.
References AutoBuildAtPosition(), and fCutMinNumHitsFinalTrack.
Referenced by BuildAndConfirmTrack(), and StepExtrapolationAddHit().
BuildAndConfirmTrack()
bool LKLinearTrackFindingTask::BuildAndConfirmTrack (LKLinearTrack * track, bool & tailToHead) private
Definition at line 482 of file LKLinearTrackFindingTask.cpp.
References AutoBuildByExtrapolation(), CorrelateHitWithTrack(), and fCutMinNumHitsFinalTrack.
Referenced by StepConfirmation().
CheckHitDistInAlphaIsLargerThanQuarterPi()
bool LKLinearTrackFindingTask::CheckHitDistInAlphaIsLargerThanQuarterPi (LKLinearTrack * track, double dLength) private
CheckParentTrackID()
int LKLinearTrackFindingTask::CheckParentTrackID (LKHit * hit) private
Definition at line 594 of file LKLinearTrackFindingTask.cpp.
Referenced by AutoBuildAtPosition(), and StepContinuumAddHit().
CheckTrackContinuity()
double LKLinearTrackFindingTask::CheckTrackContinuity (LKLinearTrack * track) private
Definition at line 617 of file LKLinearTrackFindingTask.cpp.
References LKVector3::At(), fPadPlane, and fReferenceAxis.
CheckTrackQuality()
bool LKLinearTrackFindingTask::CheckTrackQuality (LKLinearTrack * track) private
Definition at line 612 of file LKLinearTrackFindingTask.cpp.
Referenced by StepExtrapolationAddHit().
CorrelateHitWithTrack()
double LKLinearTrackFindingTask::CorrelateHitWithTrack (LKLinearTrack * track, LKHit * hit, double scale = 1) private
Definition at line 434 of file LKLinearTrackFindingTask.cpp.
Referenced by AutoBuildAtPosition(), BuildAndConfirmTrack(), and StepContinuumAddHit().
CorrelateHitWithTrackCandidate()
double LKLinearTrackFindingTask::CorrelateHitWithTrackCandidate (LKLinearTrack * track, LKHit * hit) private
Definition at line 386 of file LKLinearTrackFindingTask.cpp.
References fCutdkInExpectedTrackPath.
Referenced by StepInitTrackAddHit().
Exec()
void LKLinearTrackFindingTask::Exec (Option_t *) virtual
Definition at line 36 of file LKLinearTrackFindingTask.cpp.
References ExecStep(), fNextStep, and kStepInitArray.
ExecStep()
bool LKLinearTrackFindingTask::ExecStep ()
Definition at line 42 of file LKLinearTrackFindingTask.cpp.
References fNextStep, kStepConfirmation, kStepContinuum, kStepContinuumAddHit, kStepEndEvent, kStepEndOfEvent, kStepExtrapolation, kStepExtrapolationAddHit, kStepFinalizeTrack, kStepInitArray, kStepInitTrack, kStepInitTrackAddHit, kStepNewTrack, kStepNextPhase, kStepRemoveTrack, StepConfirmation(), StepContinuum(), StepContinuumAddHit(), StepEndEvent(), StepExtrapolation(), StepExtrapolationAddHit(), StepFinalizeTrack(), StepInitArray(), StepInitTrack(), StepInitTrackAddHit(), StepNewTrack(), StepNextPhase(), and StepRemoveTrack().
Referenced by Exec(), and ExecStepUptoTrackNum().
ExecStepUptoTrackNum()
bool LKLinearTrackFindingTask::ExecStepUptoTrackNum (int numTracks)
Definition at line 62 of file LKLinearTrackFindingTask.cpp.
References ExecStep(), fNextStep, fTrackArray, kStepEndOfEvent, and kStepNewTrack.
GetCurrentTrack()
LKLinearTrack * LKLinearTrackFindingTask::GetCurrentTrack () const inline
Definition at line 52 of file LKLinearTrackFindingTask.h.
References fCurrentTrack.
Init()
virtual bool LKLinearTrackFindingTask::Init () virtual
Reimplemented from LKTask.
ReturnBadHitsToPadPlane()
void LKLinearTrackFindingTask::ReturnBadHitsToPadPlane () private
Definition at line 374 of file LKLinearTrackFindingTask.cpp.
References fBadHits, fNumBadHits, and fPadPlane.
Referenced by StepConfirmation(), StepExtrapolation(), StepExtrapolationAddHit(), StepNewTrack(), StepNextPhase(), and StepRemoveTrack().
SetHitBranchName()
void LKLinearTrackFindingTask::SetHitBranchName (TString name) inline
Definition at line 54 of file LKLinearTrackFindingTask.h.
References fBranchNameHit.
SetTrackletBranchName()
void LKLinearTrackFindingTask::SetTrackletBranchName (TString name) inline
Definition at line 55 of file LKLinearTrackFindingTask.h.
References fBranchNameTracklet.
SetTrackPersistency()
void LKLinearTrackFindingTask::SetTrackPersistency (bool val) inline
Definition at line 29 of file LKLinearTrackFindingTask.h.
References fPersistency.
StepConfirmation()
int LKLinearTrackFindingTask::StepConfirmation () private
Definition at line 284 of file LKLinearTrackFindingTask.cpp.
References BuildAndConfirmTrack(), fCurrentTrack, fReferenceAxis, LKVector3::K(), kStepFinalizeTrack, kStepRemoveTrack, and ReturnBadHitsToPadPlane().
Referenced by ExecStep().
StepContinuum()
int LKLinearTrackFindingTask::StepContinuum () private
Definition at line 204 of file LKLinearTrackFindingTask.cpp.
References fCandHits, fGoodHits, fNumCandHits, fPadPlane, fTrackHits, kStepContinuumAddHit, and kStepExtrapolation.
Referenced by ExecStep().
StepContinuumAddHit()
int LKLinearTrackFindingTask::StepContinuumAddHit () private
Definition at line 217 of file LKLinearTrackFindingTask.cpp.
References CheckParentTrackID(), CorrelateHitWithTrack(), fBadHits, fCandHits, fCurrentTrack, fGoodHits, fNumCandHits, and kStepContinuum.
Referenced by ExecStep().
StepEndEvent()
int LKLinearTrackFindingTask::StepEndEvent () private
Definition at line 354 of file LKLinearTrackFindingTask.cpp.
References fTrackArray, kStepEndOfEvent, and lk_info.
Referenced by ExecStep().
StepExtrapolation()
int LKLinearTrackFindingTask::StepExtrapolation () private
Definition at line 243 of file LKLinearTrackFindingTask.cpp.
References kStepExtrapolationAddHit, and ReturnBadHitsToPadPlane().
Referenced by ExecStep().
StepExtrapolationAddHit()
int LKLinearTrackFindingTask::StepExtrapolationAddHit () private
Definition at line 250 of file LKLinearTrackFindingTask.cpp.
References AutoBuildByExtrapolation(), CheckTrackQuality(), fCurrentTrack, kStepConfirmation, kStepRemoveTrack, and ReturnBadHitsToPadPlane().
Referenced by ExecStep().
StepFinalizeTrack()
int LKLinearTrackFindingTask::StepFinalizeTrack () private
Definition at line 312 of file LKLinearTrackFindingTask.cpp.
References fCurrentTrack, fGoodHits, fPadPlane, fTrackHits, and kStepNewTrack.
Referenced by ExecStep().
StepInitArray()
int LKLinearTrackFindingTask::StepInitArray () private
Definition at line 75 of file LKLinearTrackFindingTask.cpp.
References fBadHits, fCandHits, fCurrentTrack, fGoodHits, fHitArray, fPadPlane, fPhaseIndex, fTrackArray, fTrackHits, and kStepNewTrack.
Referenced by ExecStep().
StepInitTrack()
int LKLinearTrackFindingTask::StepInitTrack () private
Definition at line 140 of file LKLinearTrackFindingTask.cpp.
References fCandHits, fCurrentTrack, fGoodHits, fNumCandHits, fPadPlane, fTrackHits, kStepInitTrackAddHit, and kStepRemoveTrack.
Referenced by ExecStep().
StepInitTrackAddHit()
int LKLinearTrackFindingTask::StepInitTrackAddHit () private
Definition at line 153 of file LKLinearTrackFindingTask.cpp.
References CorrelateHitWithTrackCandidate(), fBadHits, fCandHits, fCurrentTrack, fCutMaxNumHitsInitTrack, fCutMinNumHitsInitTrack, fGoodHits, fMinHitsToFitInitTrack, fNumCandHits, fPadPlane, fTrackLengthCut, fTrackLengthCutScale, kStepContinuum, kStepInitTrack, kStepInitTrackAddHit, and kStepRemoveTrack.
Referenced by ExecStep().
StepNewTrack()
int LKLinearTrackFindingTask::StepNewTrack () private
Definition at line 94 of file LKLinearTrackFindingTask.cpp.
References fCandHits, fCurrentTrack, fGoodHits, fPadPlane, fTrackArray, fTrackHits, kStepInitTrack, kStepNextPhase, and ReturnBadHitsToPadPlane().
Referenced by ExecStep().
StepNextPhase()
int LKLinearTrackFindingTask::StepNextPhase () private
Definition at line 329 of file LKLinearTrackFindingTask.cpp.
References fCandHits, fCutMaxNumHitsInitTrack, fGoodHits, fPadPlane, fPhaseIndex, fTrackHits, kStepEndEvent, kStepNewTrack, and ReturnBadHitsToPadPlane().
Referenced by ExecStep().
StepRemoveTrack()
int LKLinearTrackFindingTask::StepRemoveTrack () private
Definition at line 114 of file LKLinearTrackFindingTask.cpp.
References fCandHits, fCurrentTrack, fGoodHits, fPadPlane, fTrackArray, fTrackHits, kStepNewTrack, and ReturnBadHitsToPadPlane().
Referenced by ExecStep().
Member Data Documentation
fBadHits
LKHitArray* LKLinearTrackFindingTask::fBadHits = nullptr private
Definition at line 100 of file LKLinearTrackFindingTask.h.
Referenced by AutoBuildAtPosition(), ClassImp(), ReturnBadHitsToPadPlane(), StepContinuumAddHit(), StepInitArray(), and StepInitTrackAddHit().
fBranchNameHit
TString LKLinearTrackFindingTask::fBranchNameHit = "Hit" private
Definition at line 92 of file LKLinearTrackFindingTask.h.
Referenced by ClassImp(), and SetHitBranchName().
fBranchNameTracklet
TString LKLinearTrackFindingTask::fBranchNameTracklet = "Tracklet" private
Definition at line 93 of file LKLinearTrackFindingTask.h.
Referenced by SetTrackletBranchName().
fCandHits
LKHitArray* LKLinearTrackFindingTask::fCandHits = nullptr private
Definition at line 98 of file LKLinearTrackFindingTask.h.
Referenced by AutoBuildAtPosition(), ClassImp(), StepContinuum(), StepContinuumAddHit(), StepInitArray(), StepInitTrack(), StepInitTrackAddHit(), StepNewTrack(), StepNextPhase(), and StepRemoveTrack().
fCurrentTrack
LKLinearTrack* LKLinearTrackFindingTask::fCurrentTrack = nullptr private
Definition at line 120 of file LKLinearTrackFindingTask.h.
Referenced by GetCurrentTrack(), StepConfirmation(), StepContinuumAddHit(), StepExtrapolationAddHit(), StepFinalizeTrack(), StepInitArray(), StepInitTrack(), StepInitTrackAddHit(), StepNewTrack(), and StepRemoveTrack().
fCutdkInExpectedTrackPath
double LKLinearTrackFindingTask::fCutdkInExpectedTrackPath = 4. private
Definition at line 117 of file LKLinearTrackFindingTask.h.
Referenced by CorrelateHitWithTrackCandidate().
fCutMaxNumHitsInitTrack
int LKLinearTrackFindingTask::fCutMaxNumHitsInitTrack = 15 private
return hits if track has more than this number of hits within initialization stage
Definition at line 113 of file LKLinearTrackFindingTask.h.
Referenced by StepInitTrackAddHit(), and StepNextPhase().
fCutMinNumHitsFinalTrack
int LKLinearTrackFindingTask::fCutMinNumHitsFinalTrack = 15 private
remove track if track has smaller than this number of hits within initialization stage
Definition at line 114 of file LKLinearTrackFindingTask.h.
Referenced by AutoBuildByExtrapolation(), and BuildAndConfirmTrack().
fCutMinNumHitsInitTrack
int LKLinearTrackFindingTask::fCutMinNumHitsInitTrack = 10 private
Definition at line 112 of file LKLinearTrackFindingTask.h.
Referenced by StepInitTrackAddHit().
fCvsCurrentTrack
TCanvas* LKLinearTrackFindingTask::fCvsCurrentTrack = nullptr private
Definition at line 127 of file LKLinearTrackFindingTask.h.
fDefaultScale
double LKLinearTrackFindingTask::fDefaultScale = 2.5 private
Definition at line 102 of file LKLinearTrackFindingTask.h.
Referenced by ClassImp().
fGoodHits
LKHitArray* LKLinearTrackFindingTask::fGoodHits = nullptr private
Definition at line 99 of file LKLinearTrackFindingTask.h.
Referenced by ClassImp(), StepContinuum(), StepContinuumAddHit(), StepFinalizeTrack(), StepInitArray(), StepInitTrack(), StepInitTrackAddHit(), StepNewTrack(), StepNextPhase(), and StepRemoveTrack().
fGraphCurrentTrackPoint
TGraphErrors* LKLinearTrackFindingTask::fGraphCurrentTrackPoint = nullptr private
Definition at line 128 of file LKLinearTrackFindingTask.h.
fHitArray
TClonesArray* LKLinearTrackFindingTask::fHitArray = nullptr private
Definition at line 89 of file LKLinearTrackFindingTask.h.
Referenced by ClassImp(), and StepInitArray().
fMinHitsToFitInitTrack
int LKLinearTrackFindingTask::fMinHitsToFitInitTrack = 7 private
try track fit if track has more than this number of hits in track
Definition at line 111 of file LKLinearTrackFindingTask.h.
Referenced by StepInitTrackAddHit().
fNextStep
int LKLinearTrackFindingTask::fNextStep = StepNo::kStepInitArray private
Definition at line 122 of file LKLinearTrackFindingTask.h.
Referenced by ClassImp(), Exec(), ExecStep(), and ExecStepUptoTrackNum().
fNumBadHits
int LKLinearTrackFindingTask::fNumBadHits private
Definition at line 125 of file LKLinearTrackFindingTask.h.
Referenced by ReturnBadHitsToPadPlane().
fNumCandHits
int LKLinearTrackFindingTask::fNumCandHits private
Definition at line 123 of file LKLinearTrackFindingTask.h.
Referenced by AutoBuildAtPosition(), StepContinuum(), StepContinuumAddHit(), StepInitTrack(), and StepInitTrackAddHit().
fNumGoodHits
int LKLinearTrackFindingTask::fNumGoodHits private
Definition at line 124 of file LKLinearTrackFindingTask.h.
fPadPlane
LKDetectorPlane* LKLinearTrackFindingTask::fPadPlane = nullptr private
Definition at line 88 of file LKLinearTrackFindingTask.h.
Referenced by AutoBuildAtPosition(), CheckTrackContinuity(), ClassImp(), ReturnBadHitsToPadPlane(), StepContinuum(), StepFinalizeTrack(), StepInitArray(), StepInitTrack(), StepInitTrackAddHit(), StepNewTrack(), StepNextPhase(), and StepRemoveTrack().
fPersistency
bool LKLinearTrackFindingTask::fPersistency = true private
Definition at line 95 of file LKLinearTrackFindingTask.h.
Referenced by SetTrackPersistency().
fPhaseIndex
int LKLinearTrackFindingTask::fPhaseIndex = 0 private
Definition at line 109 of file LKLinearTrackFindingTask.h.
Referenced by StepInitArray(), and StepNextPhase().
fReferenceAxis
LKVector3::Axis LKLinearTrackFindingTask::fReferenceAxis = LKVector3::kZ private
Definition at line 107 of file LKLinearTrackFindingTask.h.
Referenced by AutoBuildAtPosition(), CheckTrackContinuity(), ClassImp(), and StepConfirmation().
fTpc
LKDetector* LKLinearTrackFindingTask::fTpc = nullptr private
Definition at line 87 of file LKLinearTrackFindingTask.h.
fTrackArray
TClonesArray* LKLinearTrackFindingTask::fTrackArray = nullptr private
Definition at line 90 of file LKLinearTrackFindingTask.h.
Referenced by ClassImp(), ExecStepUptoTrackNum(), StepEndEvent(), StepInitArray(), StepNewTrack(), and StepRemoveTrack().
fTrackHCutHL
double LKLinearTrackFindingTask::fTrackHCutHL = 15. private
Track height cut high limit.
Definition at line 106 of file LKLinearTrackFindingTask.h.
Referenced by ClassImp().
fTrackHCutLL
double LKLinearTrackFindingTask::fTrackHCutLL = 5. private
Track height cut low limit.
Definition at line 105 of file LKLinearTrackFindingTask.h.
Referenced by ClassImp().
fTrackHits
LKHitArray* LKLinearTrackFindingTask::fTrackHits = nullptr private
Definition at line 97 of file LKLinearTrackFindingTask.h.
Referenced by ClassImp(), StepContinuum(), StepFinalizeTrack(), StepInitArray(), StepInitTrack(), StepNewTrack(), StepNextPhase(), and StepRemoveTrack().
fTrackLengthCut
double LKLinearTrackFindingTask::fTrackLengthCut = 10 private
TODO.
Definition at line 118 of file LKLinearTrackFindingTask.h.
Referenced by ClassImp(), and StepInitTrackAddHit().
fTrackLengthCutScale
double LKLinearTrackFindingTask::fTrackLengthCutScale = 2.5 private
track length cut for initialization stage is [this_var] * track -> GetRMSR()
Definition at line 116 of file LKLinearTrackFindingTask.h.
Referenced by StepInitTrackAddHit().
fTrackWCutHL
double LKLinearTrackFindingTask::fTrackWCutHL = 15. private
Track width cut high limit.
Definition at line 104 of file LKLinearTrackFindingTask.h.
Referenced by ClassImp().
fTrackWCutLL
double LKLinearTrackFindingTask::fTrackWCutLL = 5. private
Track width cut low limit.
Definition at line 103 of file LKLinearTrackFindingTask.h.
Referenced by ClassImp().
The documentation for this class was generated from the following files:
LKLinearTrackFindingTask.h
LKLinearTrackFindingTask.cpp