lilak: LKGeoPlaneWithCenter Class Reference
LKGeoPlaneWithCenter Class Reference
#include <LKGeoPlaneWithCenter.h>
Public Member Functions
TVector3 GetCenter () const
LKGeoLine GetCrossSectionLine (LKGeoPlaneWithCenter plane2) const
TVector3 GetVectorU () const
TVector3 GetVectorV () const
Double_t GetX () const
Double_t GetY () const
Double_t GetZ () const
int Intersection (LKGeoLine line, TVector3 &intersection)
LKGeoPlaneWithCenter ()
LKGeoPlaneWithCenter (Double_t x, Double_t y, Double_t z, Double_t xn, Double_t yn, Double_t zn)
LKGeoPlaneWithCenter (TVector3 pos, TVector3 nnn)
void Print (Option_t *option="") const
virtual void SetPlane (Double_t x, Double_t y, Double_t z, Double_t xn, Double_t yn, Double_t zn)
virtual void SetPlane (TVector3 pos, TVector3 nnn)
virtual ~LKGeoPlaneWithCenter ()
Public Member Functions inherited from LKGeoPlane
virtual TVector3 ClosestPointOnPlane (TVector3 pos) const
virtual Double_t DistanceToPlane (Double_t x, Double_t y, Double_t z) const
virtual Double_t DistanceToPlane (TVector3 pos) const
Double_t GetA () const
Double_t GetB () const
Double_t GetC () const
Double_t GetD () const
TVector3 GetNormal () const
Double_t GetX (Double_t y, Double_t z) const
Double_t GetY (Double_t z, Double_t x) const
Double_t GetZ (Double_t x, Double_t y) const
LKGeoPlane ()
LKGeoPlane (Double_t a, Double_t b, Double_t c, Double_t d)
LKGeoPlane (Double_t x, Double_t y, Double_t z, Double_t xn, Double_t yn, Double_t zn)
LKGeoPlane (TVector3 pos, TVector3 nnn)
void SetPlane (Double_t a, Double_t b, Double_t c, Double_t d)
void SetPlane (Double_t x, Double_t y, Double_t z, Double_t xn, Double_t yn, Double_t zn)
void SetPlane (TVector3 pos, TVector3 nnn)
virtual ~LKGeoPlane ()
Public Member Functions inherited from LKGeometry
Double_t GetRMS () const
LKGeometry ()
void SetRMS (Double_t val)
virtual ~LKGeometry ()
Protected Attributes
Double_t fX = 0
Double_t fY = 0
Double_t fZ = 0
Protected Attributes inherited from LKGeoPlane
Double_t fA = 0
Double_t fB = 0
Double_t fC = 0
Double_t fD = 0
Protected Attributes inherited from LKGeometry
Double_t fRMS = -1
Detailed Description
Definition at line 10 of file LKGeoPlaneWithCenter.h.
Constructor & Destructor Documentation
LKGeoPlaneWithCenter() [1/3]
LKGeoPlaneWithCenter::LKGeoPlaneWithCenter ()
LKGeoPlaneWithCenter() [2/3]
LKGeoPlaneWithCenter::LKGeoPlaneWithCenter (TVector3 pos, TVector3 nnn)
Definition at line 31 of file LKGeoPlaneWithCenter.cpp.
References SetPlane().
LKGeoPlaneWithCenter() [3/3]
LKGeoPlaneWithCenter::LKGeoPlaneWithCenter (Double_t x, Double_t y, Double_t z, Double_t xn, Double_t yn, Double_t zn)
Definition at line 13 of file LKGeoPlaneWithCenter.cpp.
References SetPlane().
~LKGeoPlaneWithCenter()
virtual LKGeoPlaneWithCenter::~LKGeoPlaneWithCenter () inline virtual
Definition at line 16 of file LKGeoPlaneWithCenter.h.
Member Function Documentation
GetCenter()
TVector3 LKGeoPlaneWithCenter::GetCenter () const
Definition at line 54 of file LKGeoPlaneWithCenter.cpp.
References fX, fY, and fZ.
Referenced by Print().
GetCrossSectionLine()
LKGeoLine LKGeoPlaneWithCenter::GetCrossSectionLine (LKGeoPlaneWithCenter plane2) const
Definition at line 79 of file LKGeoPlaneWithCenter.cpp.
References LKGeoPlane::GetA(), LKGeoPlane::GetB(), LKGeoPlane::GetC(), LKGeoPlane::GetD(), LKGeoPlane::GetNormal(), GetX(), GetY(), and GetZ().
Referenced by LKLinearTrack::Create3DTrack(), DrawEvent(), httask::MakeTrack(), and TTHTtBeamTrackingTask::MakeTrack().
GetVectorU()
TVector3 LKGeoPlaneWithCenter::GetVectorU () const
Definition at line 60 of file LKGeoPlaneWithCenter.cpp.
References LKGeoPlane::fA, LKGeoPlane::fB, LKGeoPlane::fC, fX, fY, fZ, LKGeoPlane::GetX(), LKGeoPlane::GetY(), and LKGeoPlane::GetZ().
Referenced by GetVectorV(), Print(), and LKGeoPlaneBox::Print().
GetVectorV()
TVector3 LKGeoPlaneWithCenter::GetVectorV () const
Definition at line 74 of file LKGeoPlaneWithCenter.cpp.
References LKGeoPlane::GetNormal(), and GetVectorU().
Referenced by Print(), and LKGeoPlaneBox::Print().
GetX()
Double_t LKGeoPlaneWithCenter::GetX () const
Definition at line 56 of file LKGeoPlaneWithCenter.cpp.
References fX.
Referenced by GetCrossSectionLine().
GetY()
Double_t LKGeoPlaneWithCenter::GetY () const
Definition at line 57 of file LKGeoPlaneWithCenter.cpp.
References fY.
Referenced by GetCrossSectionLine().
GetZ()
Double_t LKGeoPlaneWithCenter::GetZ () const
Definition at line 58 of file LKGeoPlaneWithCenter.cpp.
References fZ.
Referenced by GetCrossSectionLine().
Intersection()
int LKGeoPlaneWithCenter::Intersection (LKGeoLine line, TVector3 & intersection)
Definition at line 115 of file LKGeoPlaneWithCenter.cpp.
References LKGeoLine::Direction(), LKGeoPlane::fA, LKGeoPlane::fB, LKGeoPlane::fC, LKGeoPlane::fD, LKGeoLine::GetPoint1(), and z1.
Print()
void LKGeoPlaneWithCenter::Print (Option_t * option = "") const
Definition at line 18 of file LKGeoPlaneWithCenter.cpp.
References e_info, GetCenter(), LKGeoPlane::GetNormal(), GetVectorU(), and GetVectorV().
SetPlane() [1/2]
void LKGeoPlaneWithCenter::SetPlane (Double_t x, Double_t y, Double_t z, Double_t xn, Double_t yn, Double_t zn) virtual
Reimplemented in LKGeoPlaneBox.
Definition at line 49 of file LKGeoPlaneWithCenter.cpp.
References SetPlane().
SetPlane() [2/2]
void LKGeoPlaneWithCenter::SetPlane (TVector3 pos, TVector3 nnn) virtual
Reimplemented in LKGeoPlaneBox.
Definition at line 36 of file LKGeoPlaneWithCenter.cpp.
References LKGeoPlane::fA, LKGeoPlane::fB, LKGeoPlane::fC, LKGeoPlane::fD, fX, fY, and fZ.
Referenced by LKGeoPlaneWithCenter(), LKGeoPlaneWithCenter(), and SetPlane().
Member Data Documentation
fX
Double_t LKGeoPlaneWithCenter::fX = 0 protected
Definition at line 44 of file LKGeoPlaneWithCenter.h.
Referenced by GetCenter(), LKGeoPlaneBox::GetCenter(), GetVectorU(), GetX(), LKGeoPlaneBox::GetX(), SetPlane(), and LKGeoPlaneBox::SetPlane().
fY
Double_t LKGeoPlaneWithCenter::fY = 0 protected
Definition at line 45 of file LKGeoPlaneWithCenter.h.
Referenced by GetCenter(), LKGeoPlaneBox::GetCenter(), GetVectorU(), GetY(), LKGeoPlaneBox::GetY(), SetPlane(), and LKGeoPlaneBox::SetPlane().
fZ
Double_t LKGeoPlaneWithCenter::fZ = 0 protected
Definition at line 46 of file LKGeoPlaneWithCenter.h.
Referenced by GetCenter(), LKGeoPlaneBox::GetCenter(), GetVectorU(), GetZ(), LKGeoPlaneBox::GetZ(), SetPlane(), and LKGeoPlaneBox::SetPlane().
The documentation for this class was generated from the following files:
LKGeoPlaneWithCenter.h
LKGeoPlaneWithCenter.cpp