lilak: create_slope_corrected_histograms.C File Reference
create_slope_corrected_histograms.C File Reference
#include "si_calibration.h"
Functions
void create_slope_corrected_histograms (int run=-1, bool drawExample=true)
Function Documentation
create_slope_corrected_histograms()
void create_slope_corrected_histograms (int run = -1, bool drawExample = true)
Definition at line 3 of file create_slope_corrected_histograms.C.
References cvs, cvs1, cvs2, det, fBinE1, fBinE2, fC1HistFileName, fC1ParFileName, fRecoFileName, g1Array, g2Array, iChannel, iEvent, MakeCanvas(), MakeHistName(), MakeRun(), run, and strip.