LILAK: drawDefinition.C File Reference
drawDefinition.C File Reference
#include "ejungwooA.h"
#include "LKHTLineTracker.cpp"
Functions
void drawDefinition ()
Function Documentation
drawDefinition()
void drawDefinition ()
Definition at line 4 of file drawDefinition.C.
References ejungwoo::Canvas(), cvs, LKGeoCircle::DrawCircle(), e_save_all, LKParamPointRT::GetWeight(), SetImageSpaceRange(), SetPoint(), and y2.