lilak: drawTT.C File Reference
drawTT.C File Reference
#include "setTT.h"
#include "ejungwooA.h"
Functions
void drawTT ()
void SetDrawing ()
Variables
TCanvas * fCanvas = nullptr
TexAT2 * fDetector
TH2Poly * fHistXZ [10]
Function Documentation
drawTT()
void drawTT ()
Definition at line 10 of file drawTT.C.
References fCanvas, fDetector, fHistXZ, fRun, GetType(), TexAT2::kHighCenter, TexAT2::kLeftChain, TexAT2::kLeftStrip, TexAT2::kLowCenter, TexAT2::kNon, TexAT2::kRightChain, TexAT2::kRightStrip, SetDrawing(), x0, z0, z1, and z2.
SetDrawing()
void SetDrawing ()
Definition at line 125 of file drawTT.C.
References ejungwoo::Canvas(), fCanvas, and fHistXZ.
Referenced by drawTT().
Variable Documentation
fCanvas
TCanvas* fCanvas = nullptr
Definition at line 5 of file drawTT.C.
Referenced by drawTT(), and SetDrawing().
fDetector
TexAT2* fDetector
Definition at line 4 of file drawTT.C.
Referenced by drawTT().
fHistXZ
TH2Poly* fHistXZ[10]
Definition at line 6 of file drawTT.C.
Referenced by drawTT(), and SetDrawing().