lilak: run_eve.C File Reference
lamps/macros/run_eve.C File Reference
#include "LKLogger.h"
Functions
void next (int eventID=-1)
void run_eve ()
Function Documentation
next()
void next (int eventID = -1)
Definition at line 1 of file lamps/macros/run_eve.C.
References LKRun::ExecuteEvent(), LKRun::ExecuteNextEvent(), and LKRun::GetRun().
run_eve()
void run_eve ()
Definition at line 10 of file lamps/macros/run_eve.C.
References lk_logger, next(), and run.