LILAK: LKVector3.h File Reference
LKVector3.h File Reference
#include "TVector3.h"
#include "TArrow.h"
#include <map>
Classes
class LKVector3
Functions
LKVector3::Axis operator% (const LKVector3::Axis &a1, const LKVector3::Axis &a2)
LKVector3 operator* (const LKVector3 &p, Double_t a)
LKVector3 operator* (const LKVector3 &p, Int_t a)
LKVector3 operator* (Double_t a, const LKVector3 &p)
LKVector3 operator* (Int_t a, const LKVector3 &p)
LKVector3 operator+ (const LKVector3 &a, const LKVector3 &b)
LKVector3::Axis operator++ (const LKVector3::Axis &a)
LKVector3 operator- (const LKVector3 &a, const LKVector3 &b)
LKVector3::Axis operator-- (const LKVector3::Axis &a)
Function Documentation
operator%()
LKVector3::Axis operator% (const LKVector3::Axis & a1, const LKVector3::Axis & a2)
Definition at line 211 of file LKVector3.cpp.
References LKVector3::kI, LKVector3::kJ, LKVector3::kK, LKVector3::kMI, LKVector3::kMJ, LKVector3::kMK, LKVector3::kMX, LKVector3::kMY, LKVector3::kMZ, LKVector3::kNon, LKVector3::kX, LKVector3::kY, and LKVector3::kZ.
operator*() [1/4]
LKVector3 operator* (const LKVector3 & p, Double_t a)
Definition at line 199 of file LKVector3.cpp.
References LKVector3::GetReferenceAxis().
operator*() [2/4]
LKVector3 operator* (const LKVector3 & p, Int_t a)
Definition at line 207 of file LKVector3.cpp.
References LKVector3::GetReferenceAxis().
operator*() [3/4]
LKVector3 operator* (Double_t a, const LKVector3 & p)
Definition at line 195 of file LKVector3.cpp.
References LKVector3::GetReferenceAxis().
operator*() [4/4]
LKVector3 operator* (Int_t a, const LKVector3 & p)
Definition at line 203 of file LKVector3.cpp.
References LKVector3::GetReferenceAxis().
operator+()
LKVector3 operator+ (const LKVector3 & a, const LKVector3 & b)
Definition at line 187 of file LKVector3.cpp.
References LKVector3::GetReferenceAxis(), and LKVector3::kNon.
operator++()
LKVector3::Axis operator++ (const LKVector3::Axis & a)
Definition at line 349 of file LKVector3.cpp.
References LKVector3::kMX, LKVector3::kMY, LKVector3::kMZ, LKVector3::kNon, LKVector3::kX, LKVector3::kY, and LKVector3::kZ.
operator-()
LKVector3 operator- (const LKVector3 & a, const LKVector3 & b)
Definition at line 179 of file LKVector3.cpp.
References LKVector3::GetReferenceAxis(), and LKVector3::kNon.
operator--()
LKVector3::Axis operator-- (const LKVector3::Axis & a)
Definition at line 337 of file LKVector3.cpp.
References LKVector3::kMX, LKVector3::kMY, LKVector3::kMZ, LKVector3::kNon, LKVector3::kX, LKVector3::kY, and LKVector3::kZ.