lilak: make_c2_histograms.C File Reference
make_c2_histograms.C File Reference
#include "si_calibration.h"
#include "energy_calibration.h"
Functions
void make_c2_histograms (int run=-1, bool drawExample=true)
Function Documentation
make_c2_histograms()
void make_c2_histograms (int run = -1, bool drawExample = true)
Definition at line 4 of file make_c2_histograms.C.
References b0, b1, b2, ContinueRegardingToDataType(), cvs, cvs1, cvs2, cvs3, det, f241AmAlphaEnergy1, fBinE1, fBinE2, fBinX1, fBinX2, fC0Parameters, fC1Parameters, fC2HistFileName, fC2Parameters, fExampleGroupArrayR, fExampleGroupArrayS, fHistEnergy, fHistEnergyDetector, fHistEnergyPosition, fHistEnergyPositionAll, fHistEnergySum, fHistLeftRight, fMaxEvents, fNBinE, fNBinEFix, fNBinX, fNumDetectors, fNumJStrips, fNumOStrips, fRecoFileName, fStripArrayR, fStripArrayS, GetC0Parameters(), GetC1Parameters(), GetC2Parameters(), iChannel, iEvent, IsPositionSensitiveStrip(), lk_debug, MakeCanvas(), MakeHist1(), MakeHist2(), MakeRun(), run, and strip.