lilak: make_dummy_pulse_data.C File Reference
make_dummy_pulse_data.C File Reference
Functions
int GetAmplitudeSomehow ()
int GetTbSomehow ()
void make_dummy_pulse_data ()
Function Documentation
GetAmplitudeSomehow()
int GetAmplitudeSomehow ()
Definition at line 2 of file make_dummy_pulse_data.C.
Referenced by make_dummy_pulse_data().
GetTbSomehow()
int GetTbSomehow ()
Definition at line 1 of file make_dummy_pulse_data.C.
Referenced by make_dummy_pulse_data().
make_dummy_pulse_data()
void make_dummy_pulse_data ()
Definition at line 4 of file make_dummy_pulse_data.C.
References ana, cvs, GetAmplitudeSomehow(), and GetTbSomehow().