lilak: Json Namespace Reference
Json Namespace Reference
JSON (JavaScript Object Notation).
Classes
struct BuiltStyledStreamWriter
class CharReader
class CharReaderBuilder
Build a CharReader implementation.
struct CommentStyle
Scoped enums are not available until C++11.
class Exception
class FastWriter
Outputs a Value in JSON format without formatting (not human friendly).
class Features
Configuration passed to reader and writer. This configuration object can be used to force the Reader or Writer to behave in a standard conforming way.
class LogicError
class OurCharReader
class OurFeatures
class OurReader
class Path
Experimental and untested: represents a "path" to access a node.
class PathArgument
Experimental and untested: represents an element of the "path" to access a node.
class Reader
Unserialize a JSON document into a Value.
class RuntimeError
class SecureAllocator
class StaticString
Lightweight wrapper to tag static string.
class StreamWriter
class StreamWriterBuilder
Build a StreamWriter implementation.
class StyledStreamWriter
Writes a Value in JSON format in a human friendly way, to a stream rather than to a string.
class StyledWriter
Writes a Value in JSON format in a human friendly way.
class Value
Represents a JSON value.
class ValueConstIterator
const iterator for object and array value.
class ValueIterator
Iterator for object and array value.
class ValueIteratorBase
base class for Value iterators.
class Writer
Abstract class for writers.
Typedefs
template<typename T >
using Allocator = typename std::conditional< JSONCPP_USING_SECURE_MEMORY, SecureAllocator< T >, std::allocator< T > >::type
using ArrayIndex = unsigned int
using CharReaderPtr = std::auto_ptr< CharReader >
using Int = int
using Int64 = int64_t
using IStream = std::istream
using IStringStream = std::basic_istringstream< String::value_type, String::traits_type, String::allocator_type >
using LargestInt = Int64
using LargestUInt = UInt64
using OStream = std::ostream
using OStringStream = std::basic_ostringstream< String::value_type, String::traits_type, String::allocator_type >
using StreamWriterPtr = std::auto_ptr< StreamWriter >
using String = std::basic_string< char, std::char_traits< char >, Allocator< char > >
using UInt = unsigned int
using UInt64 = uint64_t
using UIntToStringBuffer = char[uintToStringBufferSize]
Enumerations
enum { uintToStringBufferSize = 3 * sizeof(LargestUInt) + 1 }
enum CommentPlacement { commentBefore = 0 , commentAfterOnSameLine , commentAfter , numberOfCommentPlacement }
enum PrecisionType { significantDigits = 0 , decimalPlaces }
Type of precision for formatting of real values.
enum ValueType {
nullValue = 0 , intValue , uintValue , realValue ,
stringValue , booleanValue , arrayValue , objectValue
}
Type of the value held by a Value object.
Functions
static void appendHex (String &result, unsigned ch)
static void appendRaw (String &result, unsigned ch)
template<typename T >
static std::unique_ptr< T > cloneUnique (const std::unique_ptr< T > &p)
static String codePointToUTF8 (unsigned int cp)
Converts a unicode code-point to UTF-8.
static void decodePrefixedString (bool isPrefixed, char const *prefixed, unsigned *length, char const **value)
static bool doesAnyCharRequireEscaping (char const *s, size_t n)
static char * duplicateAndPrefixStringValue (const char *value, unsigned int length)
static char * duplicateStringValue (const char *value, size_t length)
template<typename Iter >
Iter fixNumericLocale (Iter begin, Iter end)
template<typename Iter >
void fixNumericLocaleInput (Iter begin, Iter end)
template<typename Iter >
Iter fixZerosInTheEnd (Iter begin, Iter end, unsigned int precision)
static char getDecimalPoint ()
template<typename T , typename U >
static bool InRange (double d, T min, U max)
static bool IsIntegral (double d)
template<typename T , typename U >
bool operator!= (const SecureAllocator< T > &, const SecureAllocator< U > &)
JSON_API OStream & operator<< (OStream &, const Value &root)
Output using the StyledStreamWriter.
template<typename T , typename U >
bool operator== (const SecureAllocator< T > &, const SecureAllocator< U > &)
JSON_API IStream & operator>> (IStream &, Value &)
Read from 'sin' into 'root'.
bool JSON_API parseFromStream (CharReader::Factory const &, IStream &, Value *root, String *errs)
static void releasePrefixedStringValue (char *value)
static void releaseStringValue (char *value, unsigned)
void swap (Value &a, Value &b)
JSONCPP_NORETURN void throwLogicError (String const &msg)
used internally
JSONCPP_NORETURN void throwRuntimeError (String const &msg)
used internally
static String toHex16Bit (unsigned int x)
static void uintToString (LargestUInt value, char *&current)
static unsigned int utf8ToCodepoint (const char *&s, const char *e)
String JSON_API valueToQuotedString (const char *value)
static String valueToQuotedStringN (const char *value, size_t length, bool emitUTF8=false)
String JSON_API valueToString (bool value)
String JSON_API valueToString (double value, unsigned int precision=Value::defaultRealPrecision, PrecisionType precisionType=PrecisionType::significantDigits)
String JSON_API valueToString (Int value)
String JSON_API valueToString (LargestInt value)
String JSON_API valueToString (LargestUInt value)
String JSON_API valueToString (UInt value)
String JSON_API writeString (StreamWriter::Factory const &factory, Value const &root)
Write into stringstream, then return string, for convenience. A StreamWriter will be created from the factory, used, and then deleted.
Variables
static const char hex2 []
Detailed Description
JSON (JavaScript Object Notation).
Typedef Documentation
Allocator
template<typename T > using Json::Allocator = typedef typename std::conditional<JSONCPP_USING_SECURE_MEMORY, SecureAllocator<T>, std::allocator<T> >::type
Definition at line 359 of file json-forwards.h.
ArrayIndex
typedef unsigned int Json::ArrayIndex
Definition at line 426 of file json-forwards.h.
CharReaderPtr
using Json::CharReaderPtr = typedef std::auto_ptr<CharReader>
Definition at line 297 of file jsoncpp.cpp.
Int
typedef int Json::Int
Definition at line 338 of file json-forwards.h.
Int64
typedef int64_t Json::Int64
Definition at line 350 of file json-forwards.h.
IStream
typedef std::istream Json::IStream
Definition at line 369 of file json-forwards.h.
IStringStream
typedef std::basic_istringstream< String::value_type, String::traits_type, String::allocator_type > Json::IStringStream
Definition at line 363 of file json-forwards.h.
LargestInt
typedef Int64 Json::LargestInt
Definition at line 353 of file json-forwards.h.
LargestUInt
typedef UInt64 Json::LargestUInt
Definition at line 354 of file json-forwards.h.
OStream
typedef std::ostream Json::OStream
Definition at line 370 of file json-forwards.h.
OStringStream
typedef std::basic_ostringstream< String::value_type, String::traits_type, String::allocator_type > Json::OStringStream
Definition at line 366 of file json-forwards.h.
StreamWriterPtr
using Json::StreamWriterPtr = typedef std::auto_ptr<StreamWriter>
Definition at line 4165 of file jsoncpp.cpp.
String
typedef std::basic_string< char, std::char_traits< char >, Allocator< char > > Json::String
Definition at line 362 of file json-forwards.h.
UInt
typedef unsigned int Json::UInt
Definition at line 339 of file json-forwards.h.
UInt64
typedef uint64_t Json::UInt64
Definition at line 351 of file json-forwards.h.
UIntToStringBuffer
using Json::UIntToStringBuffer = typedef char[uintToStringBufferSize]
Definition at line 160 of file jsoncpp.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
uintToStringBufferSize
Constant that specify the size of the buffer that must be passed to uintToString.
Definition at line 153 of file jsoncpp.cpp.
CommentPlacement
enum Json::CommentPlacement
Enumerator
commentBefore
a comment placed on the line before a value
commentAfterOnSameLine
a comment just after a value on the same line
commentAfter
a comment on the line after a value (only make sense for
numberOfCommentPlacement
root value)
Definition at line 645 of file json.h.
PrecisionType
enum Json::PrecisionType
Type of precision for formatting of real values.
Enumerator
significantDigits
we set max number of significant digits in string
decimalPlaces
we set max number of digits after "." in string
Definition at line 655 of file json.h.
ValueType
enum Json::ValueType
Type of the value held by a Value object.
Enumerator
nullValue
'null' value
intValue
signed integer value
uintValue
unsigned integer value
realValue
double value
stringValue
UTF-8 string value.
booleanValue
bool value
arrayValue
array value (ordered list)
objectValue
object value (collection of name/value pairs).
Definition at line 634 of file json.h.
Function Documentation
appendHex()
static void Json::appendHex (String & result, unsigned ch) static
Definition at line 4345 of file jsoncpp.cpp.
References toHex16Bit().
Referenced by valueToQuotedStringN().
appendRaw()
static void Json::appendRaw (String & result, unsigned ch) static
Definition at line 4341 of file jsoncpp.cpp.
Referenced by valueToQuotedStringN().
cloneUnique()
template<typename T > static std::unique_ptr< T > Json::cloneUnique (const std::unique_ptr< T > & p) static
Definition at line 2478 of file jsoncpp.cpp.
Referenced by Json::Value::Comments::operator=().
codePointToUTF8()
static String Json::codePointToUTF8 (unsigned int cp) inline static
Converts a unicode code-point to UTF-8.
Definition at line 125 of file jsoncpp.cpp.
Referenced by Json::Reader::decodeString(), and Json::OurReader::decodeString().
decodePrefixedString()
static void Json::decodePrefixedString (bool isPrefixed, char const * prefixed, unsigned * length, char const ** value) inline static
Definition at line 2579 of file jsoncpp.cpp.
Referenced by Json::Value::asCString(), Json::Value::asString(), Json::Value::dupPayload(), Json::Value::getString(), Json::Value::operator<(), and Json::Value::operator==().
doesAnyCharRequireEscaping()
static bool Json::doesAnyCharRequireEscaping (char const * s, size_t n) static
Definition at line 4254 of file jsoncpp.cpp.
Referenced by valueToQuotedStringN().
duplicateAndPrefixStringValue()
static char * Json::duplicateAndPrefixStringValue (const char * value, unsigned int length) inline static
Definition at line 2559 of file jsoncpp.cpp.
References JSON_ASSERT_MESSAGE, Json::Value::maxInt, and throwRuntimeError().
Referenced by Json::Value::dupPayload(), Json::Value::Value(), Json::Value::Value(), and Json::Value::Value().
duplicateStringValue()
static char * Json::duplicateStringValue (const char * value, size_t length) inline static
Duplicates the specified string value.
Parameters
value Pointer to the string to duplicate. Must be zero-terminated if length is "unknown".
length Length of the value. if equals to unknown, then it will be computed using strlen(value).
Returns
Pointer on the duplicate instance of string.
Definition at line 2541 of file jsoncpp.cpp.
References Json::Value::maxInt, and throwRuntimeError().
Referenced by Json::Value::CZString::CZString().
fixNumericLocale()
template<typename Iter > Iter Json::fixNumericLocale (Iter begin, Iter end)
Change ',' to '.' everywhere in buffer.
We had a sophisticated way, but it did not work in WinCE.
See also
https://github.com/open-source-parsers/jsoncpp/pull/9
Definition at line 180 of file jsoncpp.cpp.
fixNumericLocaleInput()
template<typename Iter > void Json::fixNumericLocaleInput (Iter begin, Iter end)
Definition at line 189 of file jsoncpp.cpp.
References getDecimalPoint().
fixZerosInTheEnd()
template<typename Iter > Iter Json::fixZerosInTheEnd (Iter begin, Iter end, unsigned int precision)
Return iterator that would be the new end of the range [begin,end), if we were to delete zeros in the end of string, but not the last zero before '.'.
Definition at line 206 of file jsoncpp.cpp.
getDecimalPoint()
static char Json::getDecimalPoint () inline static
Definition at line 115 of file jsoncpp.cpp.
Referenced by fixNumericLocaleInput().
InRange()
template<typename T , typename U > static bool Json::InRange (double d, T min, U max) inline static
Definition at line 2513 of file jsoncpp.cpp.
Referenced by Json::Value::asInt(), Json::Value::asInt64(), Json::Value::asUInt(), Json::Value::asUInt64(), and Json::Value::isConvertibleTo().
IsIntegral()
static bool Json::IsIntegral (double d) static
Definition at line 3675 of file jsoncpp.cpp.
Referenced by Json::Value::isInt(), Json::Value::isInt64(), Json::Value::isIntegral(), Json::Value::isUInt(), and Json::Value::isUInt64().
operator!=()
template<typename T , typename U > bool Json::operator!= (const SecureAllocator< T > & , const SecureAllocator< U > &)
Definition at line 208 of file json-forwards.h.
Referenced by Json::Value::Value().
operator<<()
OStream & Json::operator<< (OStream & sout, const Value & root)
Output using the StyledStreamWriter.
See also
Json::operator>>()
Definition at line 5326 of file jsoncpp.cpp.
References Json::StreamWriterBuilder::newStreamWriter().
operator==()
template<typename T , typename U > bool Json::operator== (const SecureAllocator< T > & , const SecureAllocator< U > &)
Definition at line 203 of file json-forwards.h.
Referenced by Json::Value::Value().
operator>>()
IStream & Json::operator>> (IStream & sin, Value & root)
Read from 'sin' into 'root'.
Always keep comments from the input JSON.
This can be used to read a file into a particular sub-object. For example:
Json::Value root;
cin >> root["dir"]["file"];
cout << root;
Result:
* {
* "dir": {
*    "file": {
*    // The input stream JSON would be nested here.
*    }
* }
* }
*
Exceptions
std::exception on parse error.
See also
Json::operator<<()
Definition at line 2232 of file jsoncpp.cpp.
References parseFromStream(), and throwRuntimeError().
parseFromStream()
bool Json::parseFromStream (CharReader::Factory const & fact, IStream & sin, Value * root, String * errs)
Consume entire stream and use its begin/end. Someday we might have a real StreamReader, but for now this is convenient.
Definition at line 2220 of file jsoncpp.cpp.
References Json::CharReader::Factory::newCharReader().
Referenced by operator>>().
releasePrefixedStringValue()
static void Json::releasePrefixedStringValue (char * value) inline static
Free the string duplicated by duplicateStringValue()/duplicateAndPrefixStringValue().
Definition at line 2608 of file jsoncpp.cpp.
Referenced by Json::Value::releasePayload().
releaseStringValue()
static void Json::releaseStringValue (char * value, unsigned) inline static
Definition at line 2609 of file jsoncpp.cpp.
Referenced by Json::Value::CZString::~CZString().
swap()
void Json::swap (Value & a, Value & b) inline
Definition at line 1452 of file json.h.
References swap(), and Json::Value::swap().
Referenced by swap(), and Json::Value::Value().
throwLogicError()
JSONCPP_NORETURN void Json::throwLogicError (String const & msg)
used internally
Definition at line 2637 of file jsoncpp.cpp.
throwRuntimeError()
JSONCPP_NORETURN void Json::throwRuntimeError (String const & msg)
used internally
Definition at line 2634 of file jsoncpp.cpp.
Referenced by duplicateAndPrefixStringValue(), duplicateStringValue(), Json::StreamWriterBuilder::newStreamWriter(), operator>>(), Json::OurReader::readObject(), Json::Reader::readValue(), Json::OurReader::readValue(), and Json::ValueIterator::ValueIterator().
toHex16Bit()
static String Json::toHex16Bit (unsigned int x) static
Definition at line 4330 of file jsoncpp.cpp.
References hex2, and x.
Referenced by appendHex().
uintToString()
static void Json::uintToString (LargestUInt value, char *& current) inline static
Converts an unsigned integer to string.
Parameters
value Unsigned integer to convert to string
current Input/Output string buffer. Must have at least uintToStringBufferSize chars free.
Definition at line 167 of file jsoncpp.cpp.
Referenced by valueToString(), and valueToString().
utf8ToCodepoint()
static unsigned int Json::utf8ToCodepoint (const char *& s, const char * e) static
Definition at line 4262 of file jsoncpp.cpp.
Referenced by valueToQuotedStringN().
valueToQuotedString()
String Json::valueToQuotedString (const char * value)
Definition at line 4426 of file jsoncpp.cpp.
References valueToQuotedStringN().
Referenced by Json::StyledWriter::writeValue(), and Json::StyledStreamWriter::writeValue().
valueToQuotedStringN()
static String Json::valueToQuotedStringN (const char * value, size_t length, bool emitUTF8 = false) static
Definition at line 4349 of file jsoncpp.cpp.
References appendHex(), appendRaw(), doesAnyCharRequireEscaping(), and utf8ToCodepoint().
Referenced by valueToQuotedString(), Json::FastWriter::writeValue(), Json::StyledWriter::writeValue(), Json::StyledStreamWriter::writeValue(), and Json::BuiltStyledStreamWriter::writeValue().
valueToString() [1/6]
String Json::valueToString (bool value)
Definition at line 4252 of file jsoncpp.cpp.
valueToString() [2/6]
String Json::valueToString (double value, unsigned int precision = Value::defaultRealPrecision, PrecisionType precisionType = PrecisionType::significantDigits)
Definition at line 4247 of file jsoncpp.cpp.
References valueToString().
valueToString() [3/6]
String Json::valueToString (Int value)
Definition at line 4194 of file jsoncpp.cpp.
References valueToString().
Referenced by Json::Value::asString(), valueToString(), valueToString(), valueToString(), Json::FastWriter::writeValue(), Json::StyledWriter::writeValue(), Json::StyledStreamWriter::writeValue(), and Json::BuiltStyledStreamWriter::writeValue().
valueToString() [4/6]
String Json::valueToString (LargestInt value)
Definition at line 4168 of file jsoncpp.cpp.
References Json::Value::maxLargestInt, Json::Value::minLargestInt, and uintToString().
valueToString() [5/6]
String Json::valueToString (LargestUInt value)
Definition at line 4184 of file jsoncpp.cpp.
References uintToString().
valueToString() [6/6]
String Json::valueToString (UInt value)
Definition at line 4196 of file jsoncpp.cpp.
References valueToString().
writeString()
String Json::writeString (StreamWriter::Factory const & factory, Value const & root)
Write into stringstream, then return string, for convenience. A StreamWriter will be created from the factory, used, and then deleted.
Definition at line 5319 of file jsoncpp.cpp.
References Json::StreamWriter::Factory::newStreamWriter().
Referenced by Json::Value::toStyledString().
Variable Documentation
hex2
const char Json::hex2[] static
Initial value:
= "000102030405060708090a0b0c0d0e0f"
                           "101112131415161718191a1b1c1d1e1f"
                           "202122232425262728292a2b2c2d2e2f"
                           "303132333435363738393a3b3c3d3e3f"
                           "404142434445464748494a4b4c4d4e4f"
                           "505152535455565758595a5b5c5d5e5f"
                           "606162636465666768696a6b6c6d6e6f"
                           "707172737475767778797a7b7c7d7e7f"
                           "808182838485868788898a8b8c8d8e8f"
                           "909192939495969798999a9b9c9d9e9f"
                           "a0a1a2a3a4a5a6a7a8a9aaabacadaeaf"
                           "b0b1b2b3b4b5b6b7b8b9babbbcbdbebf"
                           "c0c1c2c3c4c5c6c7c8c9cacbcccdcecf"
                           "d0d1d2d3d4d5d6d7d8d9dadbdcdddedf"
                           "e0e1e2e3e4e5e6e7e8e9eaebecedeeef"
                           "f0f1f2f3f4f5f6f7f8f9fafbfcfdfeff"
Definition at line 4313 of file jsoncpp.cpp.
Referenced by toHex16Bit().