LILAK: ejungwoo Namespace Reference
ejungwoo Namespace Reference
Classes
class Binning
class Range
Functions
void Add (TObject *object, const char *subfolder="")
void Batch ()
TCanvas * Canvas (const char *name="", double wx=800, double wy=680, int dx=1, int dy=1)
TCanvas * Canvas (const char *name="", int wx=800, int wy=680, int dx=1, int dy=1)
TF1 * FitG (TH1D *hist, double sigmaWidth, Option_t *opt="RQ0")
TH2D * Frame (TGraph *graph, const char *name, const char *title="", ejungwoo::Range rx1=ejungwoo::Range(), ejungwoo::Range rx2=ejungwoo::Range(), ejungwoo::Range ry1=ejungwoo::Range(), ejungwoo::Range ry2=ejungwoo::Range())
TH1D * MakeChannelHist (double *data, int nTb, TString name)
TH1D * MakeChannelHist (int *data, int nTb, TString name)
void Save (TObject *object, const char *fileType="", const char *nameVersion="", bool savePrimitives=false, bool simplifyNames=false)
void SaveAll (const char *fileType="", const char *nameVersion="", bool savePrimitives=false, bool simplifyNames=false)
void SetHist (TH1 *hist)
void UseHttpServer (bool value=true)
Variables
bool fAlwaysUseHttpServer = false
Function Documentation
Add()
void ejungwoo::Add (TObject * object, const char * subfolder = "")
Definition at line 475 of file macros_detectorplane/ejungwooA.h.
References Add(), eArray, eServer, and fAlwaysUseHttpServer.
Referenced by Add(), Canvas(), and Canvas().
Batch()
void ejungwoo::Batch ()
Definition at line 467 of file macros_detectorplane/ejungwooA.h.
References LKWindowManager::GetWindowManager().
Canvas() [1/2]
TCanvas * ejungwoo::Canvas (const char * name = "", double wx = 800, double wy = 680, int dx = 1, int dy = 1)
Definition at line 522 of file macros_hough/ejungwooA.h.
References Add(), Canvas(), e_info, and LKWindowManager::GetWindowManager().
Canvas() [2/2]
TCanvas * ejungwoo::Canvas (const char * name = "", int wx = 800, int wy = 680, int dx = 1, int dy = 1)
Definition at line 500 of file macros_detectorplane/ejungwooA.h.
References Add(), Canvas(), and LKWindowManager::GetWindowManager().
Referenced by anaFitPulse(), Canvas(), Canvas(), drawDefinition(), drawHit(), drawTexat(), drawWeightingFunction(), read_and_drawTT(), SetDrawing(), testCorrelators(), testIterate(), and testMultiTracks().
FitG()
TF1 * ejungwoo::FitG (TH1D * hist, double sigmaWidth = 1.5, Option_t * opt = "RQ0")
Definition at line 639 of file macros_detectorplane/ejungwooA.h.
Frame()
TH2D * ejungwoo::Frame (TGraph * graph, const char * name, const char * title = "", ejungwoo::Range rx1 = ejungwoo::Range(), ejungwoo::Range rx2 = ejungwoo::Range(), ejungwoo::Range ry1 = ejungwoo::Range(), ejungwoo::Range ry2 = ejungwoo::Range())
Definition at line 613 of file macros_detectorplane/ejungwooA.h.
References ejungwoo::Range::SetValue(), x0, y0, and y2.
Referenced by NextChannel().
MakeChannelHist() [1/2]
TH1D * ejungwoo::MakeChannelHist (double * data, int nTb, TString name)
Definition at line 667 of file macros_detectorplane/ejungwooA.h.
MakeChannelHist() [2/2]
TH1D * ejungwoo::MakeChannelHist (int * data, int nTb, TString name)
Definition at line 655 of file macros_detectorplane/ejungwooA.h.
Referenced by NextChannel().
Save()
void ejungwoo::Save (TObject * object, const char * fileType = "", const char * nameVersion = "", bool savePrimitives = false, bool simplifyNames = false)
Definition at line 533 of file macros_detectorplane/ejungwooA.h.
References cvs, and Save().
Referenced by Save(), and SaveAll().
SaveAll()
void ejungwoo::SaveAll (const char * fileType = "", const char * nameVersion = "", bool savePrimitives = false, bool simplifyNames = false)
Definition at line 603 of file macros_detectorplane/ejungwooA.h.
References eArray, next(), and Save().
SetHist()
void ejungwoo::SetHist (TH1 * hist)
Definition at line 708 of file macros_hough/ejungwooA.h.
UseHttpServer()
void ejungwoo::UseHttpServer (bool value = true)
Definition at line 463 of file macros_detectorplane/ejungwooA.h.
References fAlwaysUseHttpServer.
Variable Documentation
fAlwaysUseHttpServer
bool ejungwoo::fAlwaysUseHttpServer = false
Definition at line 462 of file macros_detectorplane/ejungwooA.h.
Referenced by Add(), and UseHttpServer().