lilak: odr_fitter_and_weight.C File Reference
odr_fitter_and_weight.C File Reference
#include "LKWindowManager.h"
Functions
void odr_fitter_and_weight ()
Function Documentation
odr_fitter_and_weight()
void odr_fitter_and_weight ()
Definition at line 3 of file odr_fitter_and_weight.C.
References cvs, LKGeoLine::DrawArrowXY(), e_cout, e_error, e_info, LKODRFitter::GetFitter(), lk_win, SetPoint(), LKGeoLine::SetRange(), x, x0, y, and y0.