lilak: run_eve_reco.C File Reference
run_eve_reco.C File Reference
#include "LKLogger.h"
Functions
void debug_htt ()
void next (int eventID=-1)
void run_eve_reco ()
Variables
TClonesArray * fBeamArray = nullptr
TTHTBeamTrackingTask * fBeamFindingTask
TCanvas * fCvs = nullptr
TCanvas * fCvs1 = nullptr
TClonesArray * fTrackArray = nullptr
TTHTTrackingTask * fTrackFindingTask
Function Documentation
debug_htt()
void debug_htt ()
Definition at line 10 of file run_eve_reco.C.
References e_cout, e_info, fBeamFindingTask, fCvs, fCvs1, fTrackFindingTask, LKRun::GetRun(), kLeft, kRight, kViewXY, and kViewZY.
Referenced by next().
next()
void next (int eventID = -1)
Definition at line 53 of file run_eve_reco.C.
References debug_htt(), and LKRun::GetRun().
run_eve_reco()
void run_eve_reco ()
Definition at line 64 of file run_eve_reco.C.
References fBeamArray, fBeamFindingTask, fCvs, fCvs1, fTrackArray, fTrackFindingTask, lk_logger, next(), and run.
Variable Documentation
fBeamArray
TClonesArray* fBeamArray = nullptr
Definition at line 8 of file run_eve_reco.C.
Referenced by run_eve_reco().
fBeamFindingTask
TTHTBeamTrackingTask* fBeamFindingTask
Definition at line 6 of file run_eve_reco.C.
Referenced by debug_htt(), and run_eve_reco().
fCvs
TCanvas* fCvs = nullptr
Definition at line 3 of file run_eve_reco.C.
Referenced by debug_htt(), and run_eve_reco().
fCvs1
TCanvas* fCvs1 = nullptr
Definition at line 4 of file run_eve_reco.C.
Referenced by debug_htt(), and run_eve_reco().
fTrackArray
TClonesArray* fTrackArray = nullptr
Definition at line 7 of file run_eve_reco.C.
Referenced by run_eve_reco().
fTrackFindingTask
TTHTTrackingTask* fTrackFindingTask
Definition at line 5 of file run_eve_reco.C.
Referenced by debug_htt(), and run_eve_reco().