lilak: server.cc File Reference
server.cc File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <fstream>
#include <iostream>
#include <unistd.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
Macros
#define PORT 10205
Functions
void error (const char *msg)
int main (int argc, char *argv[])
Macro Definition Documentation
PORT
#define PORT 10205
Definition at line 13 of file server.cc.
Function Documentation
error()
void error (const char * msg)
Definition at line 17 of file server.cc.
Referenced by LKPulseAnalyzer::AddChannel(), LKChannelSimulator::AddHit(), anaExtractPulse(), LKPulseAnalyzer::DrawAverage(), LKHoughWFLinear::EvalFromDistance(), LKHoughWFInverse::EvalFromDistance(), LKHTWeightingFunction::EvalFromPoints(), LKPulseAnalyzer::FullWidthRatioMaximum(), Json::Reader::getFormattedErrorMessages(), Json::OurReader::getFormattedErrorMessages(), LKPulseAnalyzer::GetReferencePulse(), Json::Reader::getStructuredErrors(), Json::OurReader::getStructuredErrors(), and main().
main()
int main (int argc, char * argv[])
Definition at line 23 of file server.cc.
References error(), PORT, and write().