lilak: susoX6_stark.C File Reference
susoX6_stark.C File Reference
#include "X6_stark.h"
Functions
void susoX6_stark (string filename="253", int FirstEntry=0, int LastEntry=0)
Function Documentation
susoX6_stark()
void susoX6_stark (string filename = "253", int FirstEntry = 0, int LastEntry = 0)
Definition at line 3 of file susoX6_stark.C.
References aback, b0, b1, b2, bback, det, Ebal_strip, Ecal_backs, Ecal_strip, Energy, Eraw_backs, Eraw_strip, Evspos_bal, Evspos_cal, Evspos_tot, FirstEntry(), gdwn, gup, histos(), LastEntry(), readcal(), readmap(), Signal, stark_map, STARK_Mult, starktree, starktreedef(), strip, tr, treeaddress(), UpvsDown, X6aget, X6asad, X6chan, X6det, X6det2, X6energy, X6energy_back, X6energy_back_cal, X6energy_cal, X6energy_dw, X6energy_dw_cal, X6energy_raw, X6energy_up, X6energy_up_cal, X6flag, X6Mult, X6Mult_back, X6Mult_dw, X6Mult_up, X6nrj, X6position, X6position_cal, X6strip, X6strip_back, and X6strip_front.