lilak: test_psa.C File Reference
test_psa.C File Reference
Functions
void next ()
void test_psa ()
Variables
LKChannelAnalyzer * ana
TClonesArray * channelArray
int iChannel = 0
Function Documentation
next()
void next ()
Definition at line 5 of file test_psa.C.
References ana, channelArray, and iChannel.
Referenced by LKHitArray::Copy(), drawDetectorPlane(), LKHitArray::DrawGraph(), LKTracklet::FinalizeHits(), LKHTLineTracker::FitTrack3DWithParamPoint(), LKHTLineTracker::FitTrackWithParamPoint(), LKDetectorSystem::GetDetectorPlane(), LKDetectorSystem::GetNumPlanes(), LKRun::Init(), LKDetectorSystem::Init(), make_hist(), httask::MakeTrack(), LKHitArray::MoveHitsTo(), LKHitArray::Print(), LKDetectorSystem::Print(), LKRun::Print(), LKHitArray::PrintHitIDs(), LKHitArray::PrintHits(), LKHTLineTracker::RemoveSelectedPoints(), LKG4RunManager::Run(), run_eve(), run_eve_reco(), run_viewer(), ejungwoo::SaveAll(), LKParameterContainer::SearchAndAddPar(), LKEvePlane::SetDataFromBranch(), LKDetectorSystem::SetDetectorPar(), LKDetectorSystem::SetGeoManager(), LKHitArray::SortByCharge(), LKHitArray::SortByDistanceTo(), LKHitArray::SortByLayer(), LKHitArray::SortByX(), LKHitArray::SortByY(), LKHitArray::SortByZ(), LKHelixTrack::SortHits(), LKTracklet::SortHits(), and test_psa().
test_psa()
void test_psa ()
Definition at line 14 of file test_psa.C.
References ana, channelArray, cvs, LKWindowManager::GetWindowManager(), next(), and run.
Variable Documentation
ana
LKChannelAnalyzer* ana
Definition at line 3 of file test_psa.C.
Referenced by anaExtractPulse(), anaSimChannel(), example_psa(), example_tool(), make_hist(), next(), NextChannel(), run_pulse_extraction(), test_chana(), test_psa(), and testPSA().
channelArray
TClonesArray* channelArray
Definition at line 2 of file test_psa.C.
Referenced by anaExtractPulse(), example_psa(), make_hist(), next(), read_conv(), read_raw_file(), read_reco(), test(), test_psa(), and test_read().
iChannel
int iChannel = 0
Definition at line 1 of file test_psa.C.
Referenced by anaExtractPulse(), LKNoiseAnalyzer::Analyze(), draw_entry(), draw_mm(), draw_MMSLR(), LKGETChannelViewer::DrawCurrentIndvChannels(), LKGETChannelViewer::DrawCurrentMCAAChannels(), example_psa(), LTEventPreviewTask::Exec(), TTPulseAnalysisTask::Exec(), LKNoiseSubtractionTask::Exec(), LKPulseExtractionTask::Exec(), LKPulseShapeAnalysisTask::Exec(), TTBeamSelectionTask::Exec(), TTDrawBeamEnergyTask::Exec(), TTDrawRawWaveformTask::Exec(), TTEventSelectionTask::Exec(), TTFindBeamTimingTask::Exec(), TTGetPedestalTask::Exec(), TTPID_FSivsFCsI::Exec(), TTPID_MMvsFSi::Exec(), TTPID_MMvsX6::Exec(), TTPID_X6vsCsI::Exec(), TTEventPreviewTask::Exec(), TTHitFindingHoughTask::Exec(), TTPulseExtractionTask::Exec(), LKGETChannelViewer::FillChannelGraph(), LKGETChannelViewer::FillChannelGraph(), LKNoiseAnalyzer::FindRefChannelID(), make_hist(), next(), LKDetectorPlane::Print(), LKPadPlane::Print(), read_conv(), read_raw_file(), LKGETChannelViewer::SelectAget(), LKGETChannelViewer::SelectAll(), TTMicromegas::SelectAndDrawChannel(), TTFrontPlane::SelectAndDrawChannel(), LKGETChannelViewer::SelectAsad(), LKGETChannelViewer::SelectCobo(), and test().