lilak: run_eve.C File Reference
texat_reco/macros/run_eve.C File Reference
Functions
void next ()
void read_event ()
void run_eve ()
void write ()
Variables
TClonesArray * beamArray = nullptr
TClonesArray * trackArray = nullptr
Function Documentation
next()
void next ()
Definition at line 15 of file texat_reco/macros/run_eve.C.
References LKRun::GetRun(), and read_event().
Referenced by run_eve().
read_event()
void read_event ()
Definition at line 4 of file texat_reco/macros/run_eve.C.
References beamArray, and trackArray.
Referenced by next().
run_eve()
void run_eve ()
Definition at line 25 of file texat_reco/macros/run_eve.C.
References beamArray, LKWindowManager::GetWindowManager(), next(), run, and trackArray.
write()
void write ()
Definition at line 23 of file texat_reco/macros/run_eve.C.
References TTMicromegas::GetPlane().
Referenced by main().
Variable Documentation
beamArray
TClonesArray* beamArray = nullptr
Definition at line 2 of file texat_reco/macros/run_eve.C.
Referenced by read_event(), and run_eve().
trackArray
TClonesArray* trackArray = nullptr
Definition at line 1 of file texat_reco/macros/run_eve.C.
Referenced by draw_energy(), draw_hough(), read_event(), run_eve(), and test_track().