LILAK: anaExtractPulse.C File Reference
texat_reco/macros_tracking/anaExtractPulse.C File Reference
#include "LKChannelAnalyzer.cpp"
#include "LKChannelAnalyzer.h"
Functions
void anaExtractPulse ()
void e_add (TObject *, const char *opt="")
void e_save (TObject *, const char *opt="")
int GetType (int cobo, int asad, int aget, int chan)
Variables
int eCsICT = 10
int efCsI = 7
int efSiJunction = 5
int efSiOhmic = 6
int eMMCenter = 0
int eMMLeftCenter = 2
int eMMLeftSide = 1
int eMMRightCenter = 4
int eMMRightSide = 3
int eX6Junction = 9
int eX6Ohmic = 8
bool fInvertChannel [fNumTypes] = {0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1}
int fNumCvsGroup = 1
const int fNumTypes = 11
int fPulseHeightCuts [fNumTypes][2] = {{800,4000}, {800,4000}, {800,4000}, {800,4000}, {800,4000}, {800,4000}, {800,4000}, {800,4000}, {800,4000}, {800,4000}, {800,4000}}
int fPulseHeightMax = 4000
int fPulseHeightMin = 800
int fPulseTbMax = 50
int fPulseTbMin = 10
int fPulseWidthCuts [fNumTypes][2] = {{20,40}, {20,40}, {20,40}, {20,40}, {20,40}, {20,40}, {20,40}, {2,10}, {20,40}, {10,25}, {10,30}}
int fSelTypes [] = {eMMCenter, eMMLeftSide, eMMLeftCenter, eMMRightSide, eMMRightCenter, efSiJunction, efSiOhmic, efCsI, eX6Ohmic, eX6Junction, eCsICT}
int fThresholds [] = {700,700,700,700,700,450,600,400,650,500,500}
const char * fTypeNames [fNumTypes] = {"MMCenter", "MMLeftSide", "MMLeftCenter", "MMRightSide", "MMRightCenter", "fSiJunction", "fSiOhmic", "fCsI", "X6Ohmic", "X6Junction", "CsICT"}
Function Documentation
anaExtractPulse()
void anaExtractPulse ()
Definition at line 62 of file texat_reco/macros_tracking/anaExtractPulse.C.
References e_add, fInvertChannel, fNumCvsGroup, fNumTypes, fPulseHeightMax, fPulseHeightMin, fPulseTbMax, fPulseTbMin, fPulseWidthCuts, fSelTypes, fThresholds, fTypeNames, LKChannelAnalyzer::FullWidthRatioMaximum(), GetType(), and lk_logger.
e_add()
void e_add (TObject * , const char * opt = "")
Definition at line 5 of file texat_reco/macros_tracking/anaExtractPulse.C.
e_save()
void e_save (TObject * , const char * opt = "")
Definition at line 6 of file texat_reco/macros_tracking/anaExtractPulse.C.
GetType()
int GetType (int cobo, int asad, int aget, int chan)
Definition at line 194 of file texat_reco/macros_tracking/anaExtractPulse.C.
References eCsICT, efCsI, efSiJunction, efSiOhmic, eMMCenter, eMMLeftCenter, eMMLeftSide, eMMRightCenter, eMMRightSide, eX6Junction, and eX6Ohmic.
Referenced by anaExtractPulse(), anaExtractPulse(), anaFitPulse(), draw_entry(), draw_mm(), draw_MMSLR(), TTBeamSelectionTask::Exec(), TTDrawBeamEnergyTask::Exec(), TTDrawRawWaveformTask::Exec(), TTEventSelectionTask::Exec(), TTFindBeamTimingTask::Exec(), TTPID_FSivsFCsI::Exec(), TTPID_MMvsFSi::Exec(), TTPID_MMvsX6::Exec(), TTPID_X6vsCsI::Exec(), TTHitFindingHoughTask::Exec(), TTHoughTestTask::Exec(), and TTRootConversionTask::Exec().
Variable Documentation
eCsICT
int eCsICT = 10
Definition at line 26 of file texat_reco/macros_tracking/anaExtractPulse.C.
Referenced by GetType().
efCsI
int efCsI = 7
Definition at line 23 of file texat_reco/macros_tracking/anaExtractPulse.C.
Referenced by anaExtractPulse(), and GetType().
efSiJunction
int efSiJunction = 5
Definition at line 21 of file texat_reco/macros_tracking/anaExtractPulse.C.
Referenced by GetType().
efSiOhmic
int efSiOhmic = 6
Definition at line 22 of file texat_reco/macros_tracking/anaExtractPulse.C.
Referenced by GetType().
eMMCenter
int eMMCenter = 0
Definition at line 16 of file texat_reco/macros_tracking/anaExtractPulse.C.
Referenced by GetType().
eMMLeftCenter
int eMMLeftCenter = 2
Definition at line 18 of file texat_reco/macros_tracking/anaExtractPulse.C.
Referenced by GetType().
eMMLeftSide
int eMMLeftSide = 1
Definition at line 17 of file texat_reco/macros_tracking/anaExtractPulse.C.
Referenced by GetType().
eMMRightCenter
int eMMRightCenter = 4
Definition at line 20 of file texat_reco/macros_tracking/anaExtractPulse.C.
Referenced by GetType().
eMMRightSide
int eMMRightSide = 3
Definition at line 19 of file texat_reco/macros_tracking/anaExtractPulse.C.
Referenced by GetType().
eX6Junction
int eX6Junction = 9
Definition at line 25 of file texat_reco/macros_tracking/anaExtractPulse.C.
Referenced by GetType().
eX6Ohmic
int eX6Ohmic = 8
Definition at line 24 of file texat_reco/macros_tracking/anaExtractPulse.C.
Referenced by GetType().
fInvertChannel
bool fInvertChannel[fNumTypes] = {0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1}
Definition at line 28 of file texat_reco/macros_tracking/anaExtractPulse.C.
Referenced by anaExtractPulse().
fNumCvsGroup
int fNumCvsGroup = 1
Definition at line 9 of file texat_reco/macros_tracking/anaExtractPulse.C.
Referenced by anaExtractPulse(), and anaFitPulse().
fNumTypes
const int fNumTypes = 11
Definition at line 15 of file texat_reco/macros_tracking/anaExtractPulse.C.
Referenced by anaExtractPulse().
fPulseHeightCuts
int fPulseHeightCuts[fNumTypes][2] = {{800,4000}, {800,4000}, {800,4000}, {800,4000}, {800,4000}, {800,4000}, {800,4000}, {800,4000}, {800,4000}, {800,4000}, {800,4000}}
Definition at line 30 of file texat_reco/macros_tracking/anaExtractPulse.C.
fPulseHeightMax
int fPulseHeightMax = 4000
Definition at line 11 of file texat_reco/macros_tracking/anaExtractPulse.C.
Referenced by anaExtractPulse().
fPulseHeightMin
int fPulseHeightMin = 800
Definition at line 10 of file texat_reco/macros_tracking/anaExtractPulse.C.
Referenced by anaExtractPulse().
fPulseTbMax
int fPulseTbMax = 50
Definition at line 13 of file texat_reco/macros_tracking/anaExtractPulse.C.
Referenced by anaExtractPulse().
fPulseTbMin
int fPulseTbMin = 10
Definition at line 12 of file texat_reco/macros_tracking/anaExtractPulse.C.
Referenced by anaExtractPulse().
fPulseWidthCuts
int fPulseWidthCuts[fNumTypes][2] = {{20,40}, {20,40}, {20,40}, {20,40}, {20,40}, {20,40}, {20,40}, {2,10}, {20,40}, {10,25}, {10,30}}
Definition at line 31 of file texat_reco/macros_tracking/anaExtractPulse.C.
Referenced by anaExtractPulse().
fSelTypes
int fSelTypes[] = {eMMCenter, eMMLeftSide, eMMLeftCenter, eMMRightSide, eMMRightCenter, efSiJunction, efSiOhmic, efCsI, eX6Ohmic, eX6Junction, eCsICT}
Definition at line 34 of file texat_reco/macros_tracking/anaExtractPulse.C.
Referenced by anaExtractPulse(), anaExtractPulse(), anaFitPulse(), and drawExtractSummary().
fThresholds
int fThresholds[] = {700,700,700,700,700,450,600,400,650,500,500}
Definition at line 29 of file texat_reco/macros_tracking/anaExtractPulse.C.
Referenced by anaExtractPulse().
fTypeNames
const char* fTypeNames[fNumTypes] = {"MMCenter", "MMLeftSide", "MMLeftCenter", "MMRightSide", "MMRightCenter", "fSiJunction", "fSiOhmic", "fCsI", "X6Ohmic", "X6Junction", "CsICT"}
Definition at line 27 of file texat_reco/macros_tracking/anaExtractPulse.C.
Referenced by anaExtractPulse(), anaExtractPulse(), anaFitPulse(), and drawExtractSummary().