lilak: run_energy_calibration.C File Reference
zzz/run_energy_calibration.C File Reference
Functions
double EvalX (Double_t *xy, Double_t *par)
void run_energy_calibration ()
Variables
const double f148GdAlphaBranchingRatio = 1
const double f148GdAlphaEnergy = 3.1822
const double f241AmAlphaBranchingRatio1 = .852
const double f241AmAlphaBranchingRatio2 = .128
const double f241AmAlphaEnergy1 = 5.486
const double f241AmAlphaEnergy2 = 5.443
Function Documentation
EvalX()
double EvalX (Double_t * xy, Double_t * par)
Definition at line 8 of file zzz/run_energy_calibration.C.
References f148GdAlphaEnergy, f241AmAlphaBranchingRatio1, f241AmAlphaBranchingRatio2, f241AmAlphaEnergy1, f241AmAlphaEnergy2, and x.
Referenced by run_energy_calibration().
run_energy_calibration()
void run_energy_calibration ()
Definition at line 94 of file zzz/run_energy_calibration.C.
References cvs, det, EvalX(), LKPainter::GetPainter(), histEnergySum, and strip.
Variable Documentation
f148GdAlphaBranchingRatio
const double f148GdAlphaBranchingRatio = 1
Definition at line 6 of file zzz/run_energy_calibration.C.
f148GdAlphaEnergy
const double f148GdAlphaEnergy = 3.1822
Definition at line 5 of file zzz/run_energy_calibration.C.
Referenced by EvalX().
f241AmAlphaBranchingRatio1
const double f241AmAlphaBranchingRatio1 = .852
Definition at line 3 of file zzz/run_energy_calibration.C.
Referenced by EvalX().
f241AmAlphaBranchingRatio2
const double f241AmAlphaBranchingRatio2 = .128
Definition at line 4 of file zzz/run_energy_calibration.C.
Referenced by EvalX().
f241AmAlphaEnergy1
const double f241AmAlphaEnergy1 = 5.486
Definition at line 1 of file zzz/run_energy_calibration.C.
Referenced by EvalX().
f241AmAlphaEnergy2
const double f241AmAlphaEnergy2 = 5.443
Definition at line 2 of file zzz/run_energy_calibration.C.
Referenced by EvalX().